### ISSUE TITLE
More animals

### ISSUE THREAD

**Issue by LaursenW** [TerraFirmaCraft/TerraFirmaCraft#1001]
**Describe the request**
I suggest adding foxes and more birds like sparrows for making the world a bit more lively. 
And fox can prey on birds and chicken. 
If there will be a body temperature system for players, the fox fur can be used for keeping warm or trade.

**Meta Info**
 - TFC Version: 1.0.2.129
 - An enhancement for TFC alone

**Comment by Azaysol** [comment]
MC 1.15 adds Foxes and Pandas already which will be added when TFC updates to 1.15. There are no plans atm to add body temperature.

**Comment by Xelbayria** [comment]
I would suggest that you look at Animania mod, it added a lot of animals and birds. Female and Male, too

It would good to see if there's a compatibility between TFC and Animania.

**Comment by DisasterMoo** [comment]
We added a bunch of animals recently, I think it is enough for 1.12, and will have more in 1.15.
