### ISSUE TITLE
Server creation

### ISSUE THREAD

**Issue by BOOP-HUB** [TerraFirmaCraft/TerraFirmaCraft#1005]
It's impossible to create a 1.12.2 tfc server because it glitches insanely right after creating the world and the created world is always vanilla.

**Comment by alcatrazEscapee** [comment]
level type `tfc_classic` or delete `server.properties` and `world` and try again.

**Comment by recolic** [comment]
I noticed that, the server always creates a vanilla world, if `level_type=default`. 

Should TFC-TNG automatically re-write this setting? (just like single user world)

https://terrafirmacraft.com/f/topic/10286-my-server-only-generates-a-vanilla-world/

**Comment by alcatrazEscapee** [comment]
If the `server.properties` does not already exist, we do default it. We do not rewrite it if the world already exists as that is a recipe for causing problems.

**Comment by recolic** [comment]
It seems that there's no documentation, and no warning for that. That's sometimes confusing...

Maybe it's better to add a documentation entry on TFC wiki, or print a warning message in server log.
