### ISSUE TITLE
TFCT: Cat AI seemed to not follow player up/down slopes, expand range

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1006]
1. What did you expect to happen?
Cats track and attack player, even when at different Y level
2. What actually happened instead (i.e. what was the bug)
Sat, spun some, and didn't move
https://clips.twitch.tv/MoistPricklyCasetteVoHiYo

Alc says "Moo pls fix"

**Meta Info**
 - TFC Version: 1.0.0.128 -- TFC Tuesday server

**Comment by Azaysol** [comment]
i dont think this is an AI issue, as they seem to still be tracking the player, i think it might be a model hotbox collision issue. ill look into it a bit
