### ISSUE TITLE
TFCT: Ore generation needs rebalanced

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1007]
TFC Tuesday players noticed lots of ore everywhere.
Investigation shows more ore than expected, but appears to match rarity configuration.

Therefore, need to rebalance ore rarities. Related to #867 

Alc: "Moo pls fix"

**Meta Info**
 - TFC Version: 1.0.1.128

**Comment by DisasterMoo** [comment]
Somehow the commit that address this got lost
