### ISSUE TITLE
Crucible ore values discrepancy

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#1008]
Values shown in crucible don't match tooltip (see screenshot).

**Meta Info**
 - TFC Version: 0.X.X.128 on test server
 
![image](https://user-images.githubusercontent.com/58256171/79582257-6e8e0280-80c3-11ea-954c-d07cde691f36.png)

**Comment by p0kes** [comment]
A rounding error? The tooltip is correct.

**Comment by alcatrazEscapee** [comment]
Yes, that seems accurate to me. The units number is approximate, and it has to be as you can very easily have fractional units in the crucible. We display the rounded units (and even if there's < 1 unit it will display "< 1"), and the percentage (as that's what should be used to compare alloys), and then the tooltip should show the exact amount of total alloy. Not much we can really do here other than accept that floating point makes everyone sad.
