### ISSUE TITLE
Bears

### ISSUE THREAD

**Issue by Wraugan** [TerraFirmaCraft/TerraFirmaCraft#1010]
Bears have buggy attack animation.

![bear](https://user-images.githubusercontent.com/59112514/79590338-2aa4f880-80d7-11ea-9686-ca2ef0c7ee72.png)

**Meta Info**
 - TFC Version: latest (1.0.2.129)
 - Were any other mods included? Only TFC-TNG and Armor Chroma

**Comment by lamoyrl90** [comment]
I can second this. I've got TFC in a modpack however.
