### ISSUE TITLE
TFCT: wool block recipe activates immediate after right click held down for weaving

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1020]
Players get confused when placed just-weaved wool cloth back on loom immediately after removing the cloth.

https://clips.twitch.tv/NaiveCulturedCaterpillarOSsloth

**To Reproduce**
1. Weave wool cloth on loom holding down right click.
2. Weaving finishes and right click removes finished cloth
3. Right click places cloth back down onto loom
4. Right click stops doing anything, and more yarn cannot be placed.
5. Player gets confused.

Suggest shift-click to remove cloth from loom, like shift-click is required to remove individual items. Maybe prevent holding down right click to weave?

**Meta Info**
 - TFC Version: build 129

**Comment by Gaelmare** [comment]
"That's what should happen" - Alc

**Comment by alcatrazEscapee** [comment]
Couldn't've said it better myself.
