### ISSUE TITLE
TFCT: Oredict on clay indicator flowers

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1023]
All of the flowers that indicate clay should have a common oredict tag, maybe "clayIndicator"

- TFC Version: build 129

**Comment by Gaelmare** [comment]
Or perhaps a 1.15 tag

**Comment by Gaelmare** [comment]
"this does really nothing, it's not used by us, it's very unlikely to be used by addons. It's not a tooltip. Also, *doesn't help unless you actually find the plant.*" - Alc

**Comment by alcatrazEscapee** [comment]
Yeah, no, this is a bastardization of the ore dictionary system for no reason.
