### ISSUE TITLE
Should be easier to know when crops are mature

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1027]
Knowing when crops are mature is challenging.
Two options to help:
JEI should show what mature crops look like as the recipe to grow the resulting food/crop
WAILA support for maturity display (as an addon, presumably)

 - TFC Version: build 129

**Comment by aliceingame** [comment]
Why not just putting back the metal hoe mode to see if crop is ready ?

**Comment by DisasterMoo** [comment]
Hwyla and TOP are added, and so, i think this is closed.
