### ISSUE TITLE
TFCT: predators should be afraid of fire

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1030]
Firepits and perhaps torches (in hand too?) should drive hostile predators away.

 - TFC Version: build 129

**Comment by Azaysol** [comment]
wouldn't that just make nights way to easy?(for the torch at least)

**Comment by DisasterMoo** [comment]
Since it would make the game far more easier than it already is, we aren't doing it. Closing
