### ISSUE TITLE
TFCT: Trees should decay if floating

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1031]
Unplaced(i.e. worldgen or grown) unsupported logs should decay. This was a Classic feature. Not implemented because of performance challenges?

 - TFC Version: build 129

**Comment by Gaelmare** [comment]
"either it becomes super easy to cut down trees by breaking dirt under them, or trees magically disappear with nothing left behind, neither of which I like" - Alc

**Comment by alcatrazEscapee** [comment]
Single unconnected logs already do decay. Whole trees do not.
