### ISSUE TITLE
Copy Concrete and Aggregate to TFC falling blocks.

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#1035]
129

Currently these don't act like TFC blocks. If we want any consistency with falling blocks they should be updated to match.
Likely a 1.15 jober.

**Comment by alcatrazEscapee** [comment]
> Likely a 1.15 jober.

Yup, and with the current falling block infrastructure, can quite simply be done.
[reference](https://github.com/orgs/TerraFirmaCraft/projects/1#card-38299510)
