### ISSUE TITLE
Vessel with molten metal move up and down in hand

### ISSUE THREAD

**Issue by aliceingame** [TerraFirmaCraft/TerraFirmaCraft#1043]
**Describe the bug**
Make sure to include:
1. What did you expect to happen? Item to stay still
2. What actually happened instead (i.e. what was the bug) Vessel go up and down in hand, repeating the same movement as when opening an empty vessel. Sometimes continue to flicker when casting metal.

**To Reproduce**
Attention to detail is important!
1. Take small vessel with molten metal inside

**Meta Info**
 - TFC Version: 0.X.X.131

**Comment by alcatrazEscapee** [comment]
I've noticed this, It *may* be due to the additional sync logic I added to brute force some of that, although I'd rather not remove that if possible.
