### ISSUE TITLE
Ore generation and melting improvements.

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#1049]
This would likely be a 1.15 improvement.

There is two ways to attack the generation part. In both the vein grades stay the same but what they spawn is different.

1. Veins use mixed spawning, So a poor vein could be made mostly up of poor ores and then have normal mixed with it.
2. Veins spawn a set amount of ore and it's grade sets the size.

The other half of the improvement would be looking modifying the stack size per ore grade so poorer ores don't suck so much fuel to be processed. So poor ores could stack up to 32 or such instead of 16.

**Comment by alcatrazEscapee** [comment]
Since it's aimed at 1.15, moved to https://github.com/orgs/TerraFirmaCraft/projects/1#card-36744573
