### ISSUE TITLE
Rock Knives do not take damage when breaking grass

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#105]
When grass is broken with a knife to harvest straw, the knife does not take any damage and remains at full durability.

**Comment by Red3Tango** [comment]
**[0.9.1.46]**
Rock Knife (all four variants) still do not take damage, however, metal knifes do take damage.

**Comment by alcatrazEscapee** [comment]
Fixed again with rock knives in 0083639c47572d363f5353a1d94c9b462ea67163
