### ISSUE TITLE
Current Temperature should not require debug mode to see in F3

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1052]
Players should not need to stop the game, change debug option, restart, and have a bunch of other  info on F3 to know what the current temperature is.

 - TFC Version: build 132

**Comment by gospodin55** [comment]
how about limiting the f3 function so that you can get temperature data by making a thermometer, or rock information by making prospectors pick

**Comment by TEXHIK** [comment]
May be add an alcohol thermometer?
Casing be crafted for example by pouring glass in a mold.
Content will be an alchohol with a dye. 
I have no good idea of how to mix them in non-wasting way, as you will only need very small amount - about 100mb or even 10mb. 
So for now I would suggest to first fill it with alchohol (RMB or placing in a barrel) and then with dye same way.

**Comment by DisasterMoo** [comment]
Might point out that recently added waila integration shows temperature when you look at dirt, grass, sand, stone and any rock blocks.
