### ISSUE TITLE
[Request] Config option for breaking speeds

### ISSUE THREAD

**Issue by lamoyrl90** [TerraFirmaCraft/TerraFirmaCraft#1060]
So, I understand the realism that it's hard to break stone and chop trees, but it's super grindy. For the users' sake, would it be possible to add a config option to customize the break speed of logs and stone? Just one number you could change and the different stone materials and pickaxe materials would scale to that number. Maybe something standard, like copper against granite/oak.

Thanks for your consideration.

**Comment by Claycorp** [comment]
1. You can do this with other mods.
2. Trees are intentionally hard to cut as it cuts the whole tree.
3. Every metal tier is an improvement on the last. Stone/Copper in TFC is like Wood in Vanilla.
