### ISSUE TITLE
TFCT: Food stacking weirdness

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1066]
https://clips.twitch.tv/DependableResolutePresidentAsianGlow

Stacked server side, but not client side?

 - TFC Version: build 132

**Comment by Gaelmare** [comment]
Also had salted cooked meat combine with charcoal grilled meat and overrode a more recent expiration date:
https://clips.twitch.tv/AthleticRockyPelicanNotATK

**Comment by alcatrazEscapee** [comment]
Two issues here:
 - server vs. client side stacking is quite strange indeed. I'm not exactly sure what would cause that particular sync issue, may be a vanilla interaction or general lag effect.
 - Food combination recipes ignoring food traits is a separate issue, and I'm splitting it off there so it can get looked at individually, see #1086

**Comment by alcatrazEscapee** [comment]
Needs update to confirm post v1.0.11.140. I have been completely (as per usual) to reproduce this type of issue and pending any further specific instances, I don't think there's really anything we can do here. It may just be a "server is laggy" problem.

**Comment by DisasterMoo** [comment]
> I don't think there's really anything we can do here. It may just be a "server is laggy" problem.

I've tested it for a bunch of time and didn't got anything, either it's working correctly now or it's a thing that can happen on packet loss/lag. Anyway, I agree there's not much we can do here to improve, so, closing this issue.
