### ISSUE TITLE
Blue bed needs regular Dye recipe.

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#1067]
TFC 133
~Beds shouldn't use the dye recipes like the blue bed.~
Blue bed should get it's dye recipe back.

**Comment by UnlimatedStone9** [comment]
Might I add that some other items, like terracotta and stained glass, shouldn't have normal crafting recipes? 🤔

**Comment by alcatrazEscapee** [comment]
I was under the impression that both recipes were left in intentionally - as the vanilla recipe is more less dye efficient but simpler?

**Comment by Claycorp** [comment]
Yes, Not sure what I was thinking. The blue one should get the recipe added back.
