### ISSUE TITLE
Crash when creating debug world

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#107]
[crash-2019-06-27_21.46.14-client.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/3336553/crash-2019-06-27_21.46.14-client.txt)

**Comment by alcatrazEscapee** [comment]
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/808f7fae1e28b56defe6510cb538799ee067afd7/src/main/java/net/dries007/tfc/objects/blocks/BlockFluidFiniteTFC.java#L24
Huh
