### ISSUE TITLE
Right clicking a barrel on water overwrites the barrel and deletes its contents.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#1071]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
The barrel to fill with water WITHOUT deleting my vessel.
2. What actually happened instead (i.e. what was the bug)
Haha barrel go delete content.

**Meta Info**
 - TFC Version: 1.12.2-1.0.6.133

**Comment by DisasterMoo** [comment]
So, it was sealed and it picked up water?

**Comment by UnlimatedStone9** [comment]
It was sealed, with about 9800mb of fresh water, I had a vessel inside of it, I right clicked the fresh water source block and it overwrote the entire barrel, giving me only 10000 fresh water and no vessel.
