### ISSUE TITLE
TFCT: Anvil contents show incorrectly to other players in world

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1074]
When two players are looking at an anvil, what is displayed on one screen will often not match the actual state or the state as viewed by another player.

https://clips.twitch.tv/BeautifulHilariousCamelDendiFace for example

 - TFC Version: build 133

**Comment by Gaelmare** [comment]
May be related to #378 ?

**Comment by alcatrazEscapee** [comment]
Need update to confirm post v1.0.11.140

**Comment by DisasterMoo** [comment]
Closing since it seems to be fixed. If anyone have this bug again, feel free to reopen / tell us in discord.
