### ISSUE TITLE
TFCT: Anvil will complain items aren't hot enough to weld when they are

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1075]
https://clips.twitch.tv/AssiduousCrazyElephantOMGScoots as an example

**Describe the bug**
Get a message "The item(s) are not hot enough to work" when welding them actually does work

**To Reproduce**
1. Place two weldable temperature ingots onto an appropriate tier anvil
2. Smack with hammer, hear sound of weld.
3. See warning message that is incorrect

 - TFC Version: build 133

**Comment by Kalzeroth** [comment]
Can attest I saw it as well

**Comment by alcatrazEscapee** [comment]
Needs update to confirm post v1.0.11.140

**Comment by DisasterMoo** [comment]
Closing since it seems to be fixed. If anyone have this bug again, feel free to reopen / tell us in discord.

**Comment by Gaelmare** [comment]
https://clips.twitch.tv/RealTemperedDolphinFloof

Still happening as of build 144

**Comment by EntropyParadigm** [comment]
Version: TerraFirmaCraft-MC1.12.2-1.5.5.155

Still happening in 155 - Tungsten Steel - Cannot "weld" or "work" metal, including the sheet versions:
![2020-10-21_14 28 31](https://user-images.githubusercontent.com/32775097/96790119-1bb34180-13ab-11eb-8180-2550f1ecb566.png)
![2020-10-21_13 41 28](https://user-images.githubusercontent.com/32775097/96790124-1ce46e80-13ab-11eb-932b-0f9b67b4b193.png)
![2020-10-21_14 13 50](https://user-images.githubusercontent.com/32775097/96790125-1e159b80-13ab-11eb-8780-b129fe2207b9.png)
![2020-10-21_14 17 53](https://user-images.githubusercontent.com/32775097/96790131-1eae3200-13ab-11eb-9355-4de94985d62e.png)
![2020-10-21_14 28 16](https://user-images.githubusercontent.com/32775097/96790134-1fdf5f00-13ab-11eb-8a1b-fc87ddf1e27f.png)

No work around for armor crafting - but can use Tinkers to liquify the metals and pour them into casts from TFC - this however doesn't give the smithing skill bonus to the item.

**Comment by alcatrazEscapee** [comment]
This issue does not apply, or has been fixed in the current MC 1.18 versions of TFC, and as MC 1.12 is receiving no more development, it will be closed. If this issue arises again in 1.18, please file a new issue report.
