### ISSUE TITLE
Animal spawn rate configuration code not valid

### ISSUE THREAD

**Issue by Azaysol** [TerraFirmaCraft/TerraFirmaCraft#1078]
**Describe the bug**
1. What did you expect to happen? 
- set the spawn rate of animals to 0 in ConfigTFC
2. What actually happened instead (i.e. what was the bug)
-  tons of animals still spawned
3. If they would help to explain the issue, include screenshots
![image](https://user-images.githubusercontent.com/1907447/80039784-949e1300-84c6-11ea-9ed3-21630b65bd40.png)

**To Reproduce**
Attention to detail is important!
1. Do '...' 
- set ConfigTFC to 0 

**Meta Info**
 - TFC Version: .133
 - Were any other mods included? Can you reproduce it without these other mods?
  -No

**Comment by DisasterMoo** [comment]
Fixed by build 142.
