### ISSUE TITLE
"The Bronze Age" advancement doesn't detect bismuth bronze or black bronze anvils.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#1082]
**Describe the bug**

![image](https://user-images.githubusercontent.com/40124890/80045027-26754280-84fe-11ea-9bec-874a0e803f71.png)

**To Reproduce**
Make any non standard bronze anvil.
No Advancement

**Meta Info**
 - TFC Version: 1.12.2-1.0.6.133

**Comment by alcatrazEscapee** [comment]
Yup
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/30b05fe351a82d2c7493a1436dd16df5b585453e/src/main/resources/assets/tfc/advancements/main/bronze_age.json#L21
