### ISSUE TITLE
Food that stay preserved in inventory (sometimes)

### ISSUE THREAD

**Issue by aliceingame** [TerraFirmaCraft/TerraFirmaCraft#1083]
**Describe the bug**
Make sure to include:
1. What did you expect to happen? Only food stored in vessel to have the "preserved" trait and the trait is removed when food is back in inventory.
2. What actually happened instead (i.e. what was the bug)
When you open a small vessel and add an item, if get the "preserved" trait, if you take a different food item from you inventory and put it in the vessel in place of a food item already there, the item that you pick will keep the "preserved" trait even if you put it in your inventory.
That make it so you only have to put one food item in the vessel and switch it with other items that you put back in inventory to preserve them.

**To Reproduce**
Attention to detail is important!
1. put food item in vessel
2. take a different item and add put it in the same slot
3. now you have the first item selected and you can put it in your normal inventory with "preserved" attached to it.

**Meta Info**
 - TFC Version: 133

**Comment by Gaelmare** [comment]
Can you screenshot this after relog to confirm it isn't a desync issue etc.?

**Comment by aliceingame** [comment]
I did quit to title and reload and here is an example.
The expiration date is the same as the item in the vessel (I took two from the same stack) but the date is earlier if I just remove one from the vessel.

![image](https://user-images.githubusercontent.com/4293373/80061358-0db95c80-84ff-11ea-85d8-143d0c5cd7a6.png)

**Comment by DisasterMoo** [comment]
I didn't have luck fixing this, if anyone would dare try, reproduction steps are fairly simple: Just swap a food with another item (I tested one food for another). The extracted food will keep the preserved trait, even tho the extract function is called normally (and the trait removal is called and everything should be working).
