### ISSUE TITLE
Broken glass item from breaking glass.

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#1091]
TFC 133
TFC Glass is sorta expensive, Adding a chance for shards to drop or making glass piles crafted from shards to be remelted would be a good addition to glass. Yes lots of mods do this, but I think we can add it.

**Comment by alcatrazEscapee** [comment]
Or alternatively, a specific method or tool which is used for cutting / breaking glass which returns the blocks broken. Could function as a replacement for silk touch for specific scenarios (since that's the vanilla solution to this problem)
