### ISSUE TITLE
Config to disable creation of log piles.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#1106]
**Describe the request**
Self explanatory, a config file to disable the ability to place log piles would be useful.

**Comment by Firedale** [comment]
How would you then create Charcoal which is necessary for progression?

**Comment by UnlimatedStone9** [comment]
> How would you then create Charcoal which is necessary for progression?

Through whatever method you please?
It's called a ``config file`` for a reason......
