### ISSUE TITLE
Sandwiches and salads rot in JEI

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#1109]
**Meta Info**
 - TFC Version: 1.12.2-1.0.6.133
![image](https://user-images.githubusercontent.com/40124890/80303040-b1c43180-87a5-11ea-86ce-5233b93869bb.png)

**Comment by alcatrazEscapee** [comment]
Insufficient issue information, can't reproduce.

**Comment by UnlimatedStone9** [comment]
> Sandwiches and salads rot in JEI

Visibly not just sandwiches and salads, that's what I assumed too at first. Those are rotten too...
![image](https://user-images.githubusercontent.com/40124890/80350177-3c6d6500-8868-11ea-8e00-442f88b833a8.png)
![image](https://user-images.githubusercontent.com/40124890/80350189-40998280-8868-11ea-8aea-479bbca5ca92.png)
I'm not sure how I could explain how to reproduce it, other than just play the game as per usual?
