### ISSUE TITLE
Certain blocks drop items in creative mode when they aren't supposed to

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#111]
The following blocks drop items when broken directly in Creative mode:

- tfc:placed_item
- tfc:placed_item_flat
- tfc:ingot_pile

**Comment by alcatrazEscapee** [comment]
This is unavoidable. Same reason why chests drop their contents when broken in creative.

**Comment by muzikbike** [comment]
Ingot piles could be fixed by splitting them up into individual block IDs for each metal type and then using block states to determine the amount of ingots present, and flat items could be fixed by splitting into individual block IDs for sticks, each type of rock, each ore and each seeds, however this may not be feasible pre-flattening.

**Comment by alcatrazEscapee** [comment]
No, they can't. Block Properties have a maximum of 16 states. Flat items can't be split as they don't just store sticks / rocks / ores / seeds, and even if so, that's a ridiculous over complication for something that is just an item holder.
