### ISSUE TITLE
Hunger potion effect should no longer affect thirst.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#1110]
Since the soon to occur addition of the "thirst" potion effect, the "hunger" potion effect added by Vanilla should no longer affect thirst.

**Comment by alcatrazEscapee** [comment]
This is not possible given the current way exhaustion works:
 - The "hunger" potion effect does not actually decrement hunger, it decrements exhaustion. This is vanilla behavior.
 - Hunger, saturation, and thirst all work the same way: they decrement when your exhaustion rolls over.

And looking through the call paths there is a very hard-coded behavior (see `Potion#performEffect`) where this exhaustion addition happens. I see no way in which we could nicely inject into this, nor do I think we should. The hunger potion effect does what it always does: add exhaustion. This in turns decrements your hunger, saturation, and thirst.
