### ISSUE TITLE
Config option to list "by default rotten" items, like rotten flesh is now.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#1112]
**Describe the request**
Currently rotten flesh obtained in TFC TNG is always rotten, might I propose a configuration option to select which foods are to always be rotten by default, this would make integrating other mods "rotten food" items with TFC much nicer.

**Comment by alcatrazEscapee** [comment]
The way TFC does this (and the way that is possible to do this via craft tweaker already), is to register a food with decay modifier of `Float.POSITIVE_INFINITY`.

For example:
```zs
var POSITIVE_INFINITY = 1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.0 as float;
ItemRegistry.registerFood(<minecraft:chorus_fruit>,1,0.1,0.1,POSITIVE_INFINITY,0,0.2,0.1,0,0);
```
(I tested this in debug and CT properly converts that number to positive infinity. If there's a better way to reference that I'm unaware of one)
