### ISSUE TITLE
Isolated stone blocks dropping

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#112]
In 1.7.10 TerraFirmaCraft and earlier, blocks of raw stone which are not attached to any other blocks via a face drop themselves as items, allowing players in survival to obtain these raw stone blocks.

This feature does not yet exist in 1.12.2 TerraFirmaCraft.

**Comment by alcatrazEscapee** [comment]
Added in #145
