### ISSUE TITLE
Firestarter cannot be placed in a tool rack

### ISSUE THREAD

**Issue by frebib** [TerraFirmaCraft/TerraFirmaCraft#1125]
**Describe the bug**
Firestarters should be placeable in tool racks(?). Afaik they were in the 1.7.x version. Instead the player swings as if they are trying to light the tool rack alight

**To Reproduce**
1. Right click on a toolrack with a firestarter
2. Firestarter remains in hand

**Meta Info**
 - TFC Version: 1.0.6.133

**Comment by aliceingame** [comment]
Just tried in classic, and no you could not place the firestarter on the rack. However, that does not mean that it is a bad idea, would be handy to have easy access to it (and flint and steel if nor already)

**Comment by frebib** [comment]
Oh, maybe you are correct. I think I could be recalling placing them in shelves from another mod
