### ISSUE TITLE
GoldPan

### ISSUE THREAD

**Issue by Pelemesh** [TerraFirmaCraft/TerraFirmaCraft#1131]
**Describe the bug**
Make sure to include:
1. Expected my prospecting skill to increase when i gold pan for things, I have 80% Adept skill

* *Meta Info**
 - TFC Version: .134

**Comment by Gaelmare** [comment]
See the differences page. https://tng.terrafirmacraft.com/Differences_From_Classic#The_Player
Panning does not increase prospecting skill. If you think it should, please open an enhancement request.

**Comment by DisasterMoo** [comment]
That's intended, prospecting skill is not the same as classic. You now have to find a vein and click on it with your prospector's pick to grain levels, also, won't work on the same vein obviously.
