### ISSUE TITLE
Clean up decay mods and add another early storage type

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#1136]
Currently decay mods for foods don't match what they should be. IE: Root veg don't last long enough.

 Add a Cellar shelf that holds items and does preservation based off temp(?) and/or light(?) or add an option to burry foods inside of it?

**Comment by Azaysol** [comment]
i think making it based on temp rather then light would be better. would make living in colder regions more viable and the warmer regions have a negative, since they can grow food for longer/more of it.

**Comment by alcatrazEscapee** [comment]
Part one was fixed in #1157, part two kind of needs discussion as to what exactly to do in that regard (and waiting to see what's necessary post the balance changes from #1157), so for now I'll close this.
