### ISSUE TITLE
Some barrel recipe doesn't work with JEI

### ISSUE THREAD

**Issue by noahg7** [TerraFirmaCraft/TerraFirmaCraft#1141]
I'm sorry I'm not English-speaking. You could be inconvenient to read.

**Describe the bug**
Make sure to include:
1. What did you expect to happen?
Putting vinegar bucket into salt water barrel to make brine
2. What actually happened instead (i.e. what was the bug)
Nothing happened. No brine has been made.
The same problem occurred with vinegar bucket and milk barrel.
This problem only occurs with JEI.
Without JEI, it works normally.

**To Reproduce**
Attention to detail is important!
ex)
1. Put vinegar bucket into 9000mB salt water barrel slot.
2. Nothing happens.

**Meta Info**
 - TFC Version: 1.0.8.136
 - Were any other mods included? Can you reproduce it without these other mods?
 - If necessary, what other mods (including versions) MUST be present to experience the bug?
I tried with JEI versions 4.15.0.291, 4.15.0.293. Both occurred this problem.

**Comment by DisasterMoo** [comment]
Seems to be a missing `copy()` here: https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/32e9f741e225b5316d9d8181b059e990f58d43cd/src/main/java/net/dries007/tfc/objects/inventory/ingredient/IngredientFluidItem.java#L72
