### ISSUE TITLE
Config to disable mold right click item output.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#1147]
**Describe the request**
A config option to disable the ability to take items out of molds via right clicking them would be incredibly useful.
1. What problem or issue would this enhancement solve?
As a progression design in my modpack, I have molds output unworked scrap metals which need to be worked into useful ingots, problem is, the new introduction of this feature allows players to obtain the readily forged ingots with a simple right click, that's not ideal.
Similarly TFC tool parts are not meant to be obtained in the traditional sense, in which case I have other tool parts crafting from the molds which need to be refined into valid tool parts.
2. Describe the feature itself - what would change, what would happen. In general more detail is good!
``rightClickUnmoldsMetal=false``

**Meta Info**
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
Yes.

**Comment by DisasterMoo** [comment]
There may be a *hidden* bug here. It should be searching for a valid crafting recipe and doing the same thing as if the player were crafting a filled mold in workbench, so, in theory, if you change your recipe to scraps or just remove it, it should be affecting this feature as well. Can you confirm that you are removing the recipes in your pack and this feature is still working?

**Comment by DisasterMoo** [comment]
I've confirmed that removing the recipe also prevents the unmolding on right click feature. Closing.
