### ISSUE TITLE
TFC Placed items do not respect creative mode

### ISSUE THREAD

**Issue by eerussianguy** [TerraFirmaCraft/TerraFirmaCraft#1155]
Version 136

Placing things with V or shift+V takes the item out of your inventory in Creative. Likewise, breaking a placed item will cause it to drop as an item.

**Comment by Claycorp** [comment]
Problem one can be fixed, problem two, not so much.
Inventories are expected to drop items when broken, This is an inventory. Changing that would be super annoying as it would be the only thing that does it.

Edit: I may have misunderstood, Are you saying in creative breaking a placed item drops a "Placed Itemblock" like what it was doing before?

**Comment by alcatrazEscapee** [comment]
Seconding that problem two is consistent with any other inventory's behavior in vanilla - they drop contents all the time.
