### ISSUE TITLE
Prospecting Pick Doesn't Guide Toward Vein

### ISSUE THREAD

**Issue by FrederikRasmussen** [TerraFirmaCraft/TerraFirmaCraft#1156]
**Description**
Un-intuitive prospecting pick results.

As shown in the image, I was pretty much only getting "Nothing" or "Very Large" samples, even though I was quite far from the actual copper vein. Worthy of note is that I only saw "Large" and "Medium" in the middle locations, just before the actual copper vein.
![unknown](https://user-images.githubusercontent.com/3720563/80891478-9933aa00-8cc4-11ea-835c-4c7b635597e4.png)

I expected to continuously get bigger and bigger samples as I neared the vein. As it is, if I walk down the hallway to the vein, the right hand side gives Nothing samples, and the left hand side gives Very Large sample.

In general, as I was searching for the vein, it kept trying to make me progress to the left hand side of the last hallway, but as soon as I went more than 3 or so blocks in that direction, I would get Nothing samples again.

**Meta Info**
- TFC Version: 1.0.8.136
- Many other mods included, TFC: Metallum among them
- I have no reason to believe other mods are required to experience this bug.

**Comment by aliceingame** [comment]
You might misunderstand how the propick work. There is a possibility of false negative.
Also, it is not an indication of how close of far the vein is, but how many ore blocks are in the area.
To find the direction of a vein the trick is to to look for a place were it switch between 2 sample size, and go 12 blocks toward the biggest result.
If you got very large more than 12 blocks away, it can mean that there is 2 veins or that there is more ore closer to that point, maybe lower, if you really want to know, make a copy of the world and use the stripworld command, it will get rid of all stone and you will be able to see the vein.

**Comment by FrederikRasmussen** [comment]
I see.

Is this information available on the wiki? I tried searching, but to no immediate avail.

It would still be nice to see a more intuitive experience for the prospecting pick, but alas, that is not a bug - so I will close the issue.

**Comment by aliceingame** [comment]
The info on the old wiki is not super detailed, the video by kitty is not totally bad, but you could read on the way down and look for the point when there is a change in the reading and dig down 12 from there, so you would already be a the right dept. 
I also made a guide on the old forum, https://terrafirmacraft.com/f/topic/3509-prospectors-pick-how-to-use-at-its-best/?do=findComment&comment=56355

New wiki not complete yet
