### ISSUE TITLE
Mod Priorities List

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#1158]
**Describe the request**
Make sure to include:
I have no idea if this is even possible with the way TFC is written at the moment, but...
A priorities list in the config file for which mods are prioritised over or under TFC would be incredibly useful. Similar to mods like ImmersiveEngineering, GregTech CE and so on.
**1. What problem or issue would this enhancement solve?**
Allows TFC to inherit modded items as the standard output for recipes.
**2. Describe the feature itself - what would change, what would happen. In general more detail is good!**
A mod priorities list in TFC's config file that allows configuring which mods (by mod ID) are prioritized over or under TFC.

**Meta Info**
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
Both.

**Comment by alcatrazEscapee** [comment]
This is *possible*, however it's a huge amount of work, involves writing some pretty hardcoded mechanics in what is supposed to be (and will be, in 1.15) data driven recipe definitions.

Firstly, this is a convenience feature. It provides no more customization options than ones that already exist. If you wish recipes to use specific mod items as outputs, then you need to add recipes that do said output conversion, and remove ones that don't follow with your standard. Anything that's not possible already with removing recipes will not become magically possible by adding mod-id lists, it's a separate customization issue.

Secondly, this request is for a system which is *heavily* anti-data driven design. In 1.15, every single recipe is going to become a json, and every single one of them will be modifiable. In addition, it will become *much* simpler to specify specific items, metals, etc. to TFC to treat as having certain properties. The end result being, this kind of system is more and more difficult to maintain, and relies on basically circumventing the benefits that data driven design get you.

Finally, this is a solution only for a very limited subset of actual recipes, namely, ones that produces such common items that many mods add them.

That said, there's a couple of things that should be possible **in 1.15**:
 - every recipe is a json file, meaning it can be overwritten, replaced, modified, etc.
 - recipes can specify outputs by tag, which can get resolved to specific mod IDs at load time (using this kind of suggestion)

Which, for future reference, is noted [here](https://github.com/orgs/TerraFirmaCraft/projects/1#card-37469205)
