### ISSUE TITLE
Temperature change indicator of small vessel while heated in forge is reversed

### ISSUE THREAD

**Issue by Dan-Gecko** [TerraFirmaCraft/TerraFirmaCraft#1167]
**Describe the bug**
The qualitative temperature indicator (i.e. warm-hot-faint red) in the small vessel tool tip as well as the ingot cast while hovering over a vessel/cast being warmed up in a forge progresses in reversed fashion. Warming up is shown as cooling down. 
> The small vessel/cast actually heats up correctly. Only indication is wrong.
> When in the inventory the progression of the qualitative temperature indicator is correct. 
> Ingots/Tools are not affected.

**To Reproduce**
Attention to detail is important!
1. Have a fired small vessel/cast
2. Light the forge using charcoal
3. Put small vessel/cast containing anything or nothing in the forge
4. The **actual** qualitative temperature of the vessel is shown only briefly upon entering the forge UI and declining with progressing time.

**Meta Info**
 TFC Version: TerraFirmaCraft-MC1.12.2-1.0.9.138
other mods are
 1. theoneprobe-1.12-1.4.28
 2. NotEnoughItems-1.12.2-2.4.3.245-universal
 3. jei_1.12.2-4.15.0.291
 4. journeymap-1.12.2-5.7.1
 5. CodeChickenLib-1.12.2-3.2.3.358-universal

EDIT: also casts are affected. changed text accordingly.

**Comment by Dan-Gecko** [comment]
here are the logs
[debug.log](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/4573695/debug.log)
[latest.log](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/4573696/latest.log)

EDIT: updated logs

**Comment by alcatrazEscapee** [comment]
29f57960f383b3f28330c915fb96f6a5934c50f0
