### ISSUE TITLE
Firepit GUI doesn't update/sync when cooking

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#1174]
Place item in firepit to cook (e.g. dough). It never changes to cooked visually. Exiting the GUI and re-entering and it will be cooked. 

**Meta Info**
 - TFC Version: 0.X.X.138 on test server

**Comment by alcatrazEscapee** [comment]
Duplicate of #1167 (same root issue, and fix)
