### ISSUE TITLE
TFCT: Rain snowing

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1176]
Rain displayed, but snow is accumulating. Related to #598 

https://clips.twitch.tv/CrepuscularGleamingEggRlyTho

 - TFC Version: build 135

**Comment by alcatrazEscapee** [comment]
This issue does not apply, or has been fixed in the current MC 1.18 versions of TFC, and as MC 1.12 is receiving no more development, it will be closed. If this issue arises again in 1.18, please file a new issue report.
