### ISSUE TITLE
Sequoia trees can be partially floating

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#118]
Flying sequoia trees are back. One example:

seed: 2903243570992731770
x: 1991
z: 170

**Comment by alcatrazEscapee** [comment]
Can you verify if this was caused by the sequoia tree spawning on all non-solid blocks? Or was it the tree spawning on top of blocks that then fell down (i.e. grass that updated and later fell down a hill, leaving the tree unsupported)
Pictures would help.

**Comment by muzikbike** [comment]
Generated a new world with the same seed and then immediately teleported to the site, and didn't see anything indicative of collapsed blocks. The tree does seem to be "supported" by tall grass, though.
![2019-06-27_23 17 24](https://user-images.githubusercontent.com/52297970/60304595-d22b2180-9931-11e9-94db-76b92ae1f6b8.png)

**Comment by alcatrazEscapee** [comment]
That's helpful, thanks.
