### ISSUE TITLE
some animals missing old textures

### ISSUE THREAD

**Issue by Azaysol** [TerraFirmaCraft/TerraFirmaCraft#1181]
Make sure to include:
1. What did you expect to happen?
all animals to have old textures

**Meta Info**
 - TFC Version: 139/140

**Comment by eerussianguy** [comment]
we consciously didn't include old textures for non-husbandry animals. the capability exists but we figured it didn't matter.

**Comment by Azaysol** [comment]
@eerussianguy yea, this was mainly for the animals i added that were missing it, for the predators thing see #1182 
- i removed them

**Comment by DisasterMoo** [comment]
Closed in https://github.com/TerraFirmaCraft/TerraFirmaCraft/commit/3a8ac4b1f135f853b01f017dcf7031cc67ec899e
