### ISSUE TITLE
predators have old and young textures

### ISSUE THREAD

**Issue by Azaysol** [TerraFirmaCraft/TerraFirmaCraft#1182]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
predators/hunteable animals cant be tamed and age does not matter

**Meta Info**
 - TFC Version: 139/140

**Comment by DisasterMoo** [comment]
Closed in https://github.com/TerraFirmaCraft/TerraFirmaCraft/commit/3a8ac4b1f135f853b01f017dcf7031cc67ec899e
