### ISSUE TITLE
Chiseling collapse mechanic should cancel itself if a collapse occurs

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1185]
Chiseled blocks took 200% longer to break than raw stone in classic. Currently take 75% of the time of raw stone.

With the chiseling cavein change, and new mining techniques, this tradeoff needs to come back,

 - TFC Version: build 135

**Comment by Azaysol** [comment]
is this a change to allow chiseled blocks to work more like raw blocks? where they can collapse and become cobble? if so i think its a pretty good idea considering the recent changes to smooth stone

**Comment by Gaelmare** [comment]
Per discussion, the hardness of chiseled blocks will also be increased to match raw.

**Comment by Azaysol** [comment]
@Gaelmare please see #1192
