### ISSUE TITLE
Making some animals omnivores

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1186]
I'd like to see pigs, chickens and ducks be omnivores, that is, making it so they can be familiarized using any type of food, be it rotten or not. This would make it closer to reality as well as give a use for rotten food.

 - TFC Version: 1.0.9.138 (at time of request)

**Comment by Azaysol** [comment]
pigs and chickens accept rotten grains, not sure about allowing meats and other foods as well

**Comment by nuuno2000** [comment]
Yes, that is true, but if you consider that irl pigs dont eat grain very frequently (if at all) feeding moslty on veg, fruit and sometimes meat it would make more snese to make it so they can eat any food, rotten or not. Same thing goes for chickens and ducks, they just just about anything.

**Comment by DisasterMoo** [comment]
Superseded by #1240, probably will do that one so you can have any way you like it.
