### ISSUE TITLE
Issue when shift clicking to make sandwiches with unproporcional ammont of ingredients

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1187]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
To make an amount of sandwiches equal to the amount of the limiting ingredient
2. What actually happened instead (i.e. what was the bug)
It makes sandwitches until the bread is gone
3. If it was a crash, upload the full log file (`latest.log`)
4. If they would help to explain the issue, include screenshots

**To Reproduce**
Attention to detail is important!
Create a sandwich with 3 ingredients but have 1 in a a lower amount (1 meat 20 veg 20 fruit)
This will make 1 sandwich with all 3 ingredients and 19 with only veg and fruit, while i expected it to make only one.

**Meta Info**
 - TFC Version: 1.0.9.138

**Comment by alcatrazEscapee** [comment]
This is consistent with vanilla behavior for recipes, *considering* the fact that there is one recipe for a sandwich that accepts any amount of ingredients.

As a QoL change, this could quite easily be split up into separate recipes and vanilla should handle this as expected. I would advise against trying to hack this functionality into the crafting operation through other means.

**Comment by alcatrazEscapee** [comment]
As of current 1.18.x, sandwiches aren't craftable with anything other than 3 items, so the root cause of the recipe doesn't exist.

The above comment will still apply if we choose to reintroduce this feature.
