### ISSUE TITLE
Several crops report "Growing\nGrowth: Mature" in HWYLA when not at max growth state

### ISSUE THREAD

**Issue by frebib** [TerraFirmaCraft/TerraFirmaCraft#1188]
**Describe the bug**
Make sure to include:
HYWLA says crop is mature, yet breaking yields only seed. Reproduced with Jute, Maize and Cabbages at least. Jute growth stage is 4, yet has 6 growth states according to the wiki and the code
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/23c40880d6ec3041ce9bcee0882e6dd676208969/src/main/java/net/dries007/tfc/util/agriculture/Crop.java#L56

**To Reproduce**
Attention to detail is important!
1. Let Jute (or other crop) grow to stage 4, note Hwyla says `Growing\nGrowth: Mature` yet crop is not actually mature
2. Break and only get seeds

**Meta Info**
 - TFC Version: 1.0.11.140
 - Wawla 2.6.275
 - Hwyla 1.8.26-B41

**Comment by alcatrazEscapee** [comment]
I'm going to assume this is a sync issue related to #1180 and needs to be verified.
