### ISSUE TITLE
Unsealing barrel puts it in a "sealed but usable state"

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1189]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
The barrel to unseal

2. What actually happened instead (i.e. what was the bug)
the barrels GUI show it was sealed at 00:00 on 1 Jan 1000 and you can interact with it, but its weird as it leaves ghost items and such

4. If they would help to explain the issue, include screenshots
![image](https://user-images.githubusercontent.com/64791157/81118135-43f3d480-8f20-11ea-8db0-4e53119aa554.png)
The bucket is a ghost bucket

**To Reproduce**
-Seal a barrel
-Unseal it

**Meta Info**
 - TFC Version: 1.0.11.140

**Comment by alcatrazEscapee** [comment]
I'm going to assume this is a sync issue related to #1180 and needs to be verified.

**Comment by Gaelmare** [comment]
Verified in build 140:
https://clips.twitch.tv/RacyChillyTortoiseBIRB

**Comment by Grigoriewich** [comment]
Can I add a video?
https://youtu.be/pnIm2BouQdI
