### ISSUE TITLE
Vanilla bugs with crop placement

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#119]
Some vanilla bugs with crop placement were fixed in 1.14. While they still exist in vanilla 1.12.2, it may be possible to fix these for specifically TerraFirmaCraft crops.

- No sounds produced while placing crops: one of the issues listed under https://bugs.mojang.com/browse/MC-93281 and fixed in 19w03a

- Crops must be placed while directly aiming at farmland, and not while aiming at the side or bottom of another block: reported as https://bugs.mojang.com/browse/MC-135157 and fixed in 19w11a

**Comment by alcatrazEscapee** [comment]
We are not porting vanilla bug fixes back to 1.12 - If they've been fixed in 1.14 then we will adopt said fix as well when we port to 1.14.

**Comment by alcatrazEscapee** [comment]
Whoops

**Comment by alcatrazEscapee** [comment]
This bug occurs and is fixed as part of vanilla's right click handling logic. As such, we won't be screwing with it in 1.12, and we shouldn't have to do anything about it in 1.14
