### ISSUE TITLE
Cave-ins when attempting for Raw Rock drops

### ISSUE THREAD

**Issue by DerSchleimpilz** [TerraFirmaCraft/TerraFirmaCraft#1190]
When mining rock to obtain raw rock blocks the targeted block sometimes falls as cobblestone (cave-in) instead of dropping as an item as it is supposed to. This happens when the block underneath the target block is mined before all other five adjacent blocks (sides and top) are mined. Even if the target block is floating in the end it has a chance to fall (cave-in) instead of dropping as an item.

To reproduce mine all blocks arouund a rock block except bottom, then bottom. Of course this only occurs if the block decides to fall, which means you may need to try several times to reproduce it.
**Meta Info**
 - TFC Version: 1.0.9.138
 - Other mods: Hwyla, JourneyMap, Inventory Tweaks, JEI, Rebind Narrator and Controlling. I did not reproduce the bug without these, although they should not influence it.

**Comment by alcatrazEscapee** [comment]
If it's unsupported, yes, it can collapse. You mined a raw block, which causes a collapse check firstly, the raw stone comes second. If it's important you can place supports down.

**Comment by DerSchleimpilz** [comment]
wouldn't it make sense for the raw stone check to come first? I mean... a floating block drops. The block floats. I don't need to support it to make it float (in theory). It maay be more of a quality of life change than a real bug, but to me it doesn't make much sense the way it works now.
