### ISSUE TITLE
Parrots should be able to perch on leaves.

### ISSUE THREAD

**Issue by eerussianguy** [TerraFirmaCraft/TerraFirmaCraft#1195]
140ish. It makes sense that they'd be able to sit on tree branches. Their AI causes them to attempt to however they fall through and end up flying

**Comment by Azaysol** [comment]
so im pretty sure whats going on here is that the vanilla AI has them flying to a leave block and trying to land on it. Vanilla MC leaves blocks or solid, but TFCs are not so they fall through

**Comment by DisasterMoo** [comment]
Not possible, our leaf blocks are not "solid", so any entity keep falling. Even if we did some "hack" and add an AI to make parrots glide over it, their wings would keep flapping.

TL;DR: Closing since it is impossible without making leaves "solid".
