### ISSUE TITLE
Block state that determines the half of a tall grass block inconsistent with vanilla nomenclature

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#120]
TFC blocks such as switchgrass use a blockstate to determine which half of the plant this block represents. This block state is named "part". This is inconsistent with the vanilla block state used for double plants such as sunflowers, as well as vanilla and TFC doors, which is named "half".

**Comment by alcatrazEscapee** [comment]
While true, we aren't going to change this, as TFC tall grasses have more than two states: The `part` blockstate can be `upper`, `lower`, `middle` or `single`.
