### ISSUE TITLE
Cooked eggs give the wrong nutrition type

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1202]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
Eggs to increase the "meat" nutrition bar
2. What actually happened instead (i.e. what was the bug)
Eggs increase the "dairy" nutriton bar

**To Reproduce**
I gave myselft hunger in creative so all my nutrition bars whould be at 0 and then ate a few eggs, the only bar that wasnt at 0 after eating the eggs was dairy

**Meta Info**
 - TFC Version: 1.0.11.140

**Comment by nuuno2000** [comment]
Update: in 141 the missing nutrition description is now present when pressing shift, confirming that eggs give dairy instead of "meat"
![2020-05-08_13 17 09](https://user-images.githubusercontent.com/64791157/81404831-4e83b900-912e-11ea-9bc3-c68a3871ebc1.png)

**Comment by Claycorp** [comment]
It was designed like this but really should change, Options for getting dairy faster has been talked about.
