### ISSUE TITLE
Lower the default amount of ore veins and nuggets above them

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1207]
I know this can be changed in the config but the default amount should be set a lot lower, are an example, in about a 100 block radius on the test server i found 2 tetrahedrite veins, 1 magnetite vein, 1 gypsum vein,1 bismuthinite vein and 2 native platinum vein. This is considering all 3 rock layers but its still too much.
I also managed to collect 8*16 small tetrahedrite (which makes me think there was 1 more vein) which is just a huge ammount (didint pick up any of the other ore nuggets)
The reduction of theamount of veins would prevent them from merging together and being way harder to pinpoint with the prospectors pick, while increasing the challenge to find ores that are usually rarer as well.
Reducing the ammount of nuggets would prevent people from not having to mine certain ores that arent needed in a big amount (such as cassiterite or sphalerite)

Im not sure if the test server runs the default configs in this regard but if it doesnt and is instead running higher rates of ore spawn, id suggest lowering it.
**Meta Info**
 - TFC Version: 1.0.11.140 (at time of request)

**Comment by Azaysol** [comment]
i kinda agree, you can find several veins of ore in just about any 50 block radius

**Comment by DisasterMoo** [comment]
Nuggets are fine, there was a bug in that version that caused ore veins to be registered twice. Not sure how well balanced it is now but surely it would be nice if we could have help from the community to find the best rarity values here, like a task force who everyone generates chunks in single player worlds and then use the command to dump veins.

**Comment by p0kes** [comment]
[tfc-veins-rate.log](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/4747026/tfc-veins-rate.log)

**Comment by Mrthomas20121** [comment]
https://gist.github.com/Mrthomas20121/3ecfcbd21d77f99d99b2e8c35a934ed9

**Comment by p0kes** [comment]
[tfc-veins-rate.log](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/4747374/tfc-veins-rate.log)

**Comment by eerussianguy** [comment]
@Mrthomas20121 those are not native TFC ores, not sure how useful that is

**Comment by DisasterMoo** [comment]
As EER mentioned, those can help TFC-Metallum but not TFC itself.

**Comment by alcatrazEscapee** [comment]
Lots of ore veins have been tweaked:
 - surface veins vs. non surface veins should be more relevant.
 - lots of rarity tweaks, generally upwards.
 - some y range tweaks, mostly for surface veins.

Feedback welcome if this is too much / too little.

**Comment by alcatrazEscapee** [comment]
Seems this is in a good spot for the moment.
