### ISSUE TITLE
Addition of goat and sheeps milk

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1208]
I would like to be able to milk goats and sheep in the same way we can milk cows, this would give another use to both of the animals, which is especially good for goats as their only funcion now is to be slaughtered for meat. Obviously the milk from these animals could then be used to make cheese in the same way as cows milk, making dairy more accessible even for players who cant find cows.

**Meta Info**
 - TFC Version: 1.0.10.140 (at time of request)

**Comment by DisasterMoo** [comment]
Goats do give milk, but for balancing purposes, the cooldown is 3 days while cows are 1. Also, Sheeps already gives wool, which, for the same balancing purposes, we aren't going to add milking to them.
