### ISSUE TITLE
Wood-dependent signs

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#121]
As of vanilla 1.14, signs must be made using identical wood, instead of mixing and matching, and the output sign matches the wood type used to craft it. This feature could be implemented in 1.12.2 TerraFirmaCraft with its wood types.

**Comment by alcatrazEscapee** [comment]
We aren't trying to backport 1.14 features to 1.12 TFC - If vanilla does a thing in 1.14 we will add similar features when we move to 1.14, i.e. sign variants, stripped logs, log vs wood blocks etc.

**Comment by alcatrazEscapee** [comment]
Been noted in https://github.com/TerraFirmaCraft/TerraFirmaCraft/projects/6#card-29397197 instead at it's not a current issue.
