### ISSUE TITLE
TFCT: Finding floating seeds in the world

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1210]
I had written this off to other players in the test server, but now I've seen it too often including on the TFCT server.

Occasionally will discover seed item entities just floating in the world in new(?) chunks. 

**Meta Info**
 - TFC Version: build 140

**Comment by Azaysol** [comment]
ice run across this issue personally as well on the test server

**Comment by DisasterMoo** [comment]
May have fixed this in build 142 after I moved wild crops generation to the bottom of chunk generation.

**Comment by DisasterMoo** [comment]
Not finding any more seeds since i did that change. Closing this but if anyone finds it again please reopen this.
