### ISSUE TITLE
TFCT: Sheets don't stack after placed in world and broken

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1212]
Looks like the item block is retaining empty NBT data like wooden buckets were in #946 ?

 - TFC Version: build 140

**Comment by eerussianguy** [comment]
Let's add a key that stacks them, like food

**Comment by alcatrazEscapee** [comment]
> Let's add a key that stacks them, like food
No, if there's a bug, let's fix the bug.

That said, I cannot reproduce in SMP or SSP. Everything seems to be working as intended and I see no possible code paths through which this should be possible.

Are you sure they just weren't different temperatures?

**Comment by Gaelmare** [comment]
Pretty sure one was placed and then broken. I'll see if I can find it on
their stream.

**Comment by Gaelmare** [comment]
https://clips.twitch.tv/BadCuriousCakeTBTacoRight
that's build 140

**Comment by DisasterMoo** [comment]
If this happens again, would be awesome to get a world save to check if this is NBT related or something. Since neither me nor Alc could reproduce, Closing (reopen with reproduction steps or world save if happens again).
