### ISSUE TITLE
Items displayed in JEI that should not be displayed in JEI.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#1214]
![image](https://user-images.githubusercontent.com/40124890/81310979-b4176d00-907c-11ea-9ca1-1d7ef1816cfa.png)

**Comment by eerussianguy** [comment]
That's actually a JEI info thingy. Click on it and it displays a little box telling you how to use a placed item

**Comment by UnlimatedStone9** [comment]
Why are they so horrible looking then? They're like debug items. 😄

**Comment by Claycorp** [comment]
Anode made as they are required for showing up in the tooltips/jei, If anyone is willing to make something better and understandable it's up for changing.

**Comment by AnodeCathode** [comment]
Hey! I spent nearly 6 seconds making those gorgeous icons

**Comment by alcatrazEscapee** [comment]
These are *grumbles* intentional additions. If someone wants to PR better textures be my guest. Otherwise this is working as intended, as hiding them would be rather counterproductive to making them JEI integrated in the first place.
