### ISSUE TITLE
Terrrible Hostile Animals 

### ISSUE THREAD

**Issue by SammyMorane** [TerraFirmaCraft/TerraFirmaCraft#1215]
TFC version is MC1.12.2-1.0.6.133
Hello TFC mod developers. Not so long ago, I began to go through your mod and ran into one problem. Damn wild animals. Bears, lions, especially panthers often spawn to madness often, and most importantly in huge quantities. Earlier this mod (on version 1.7.10) gave only vanilla mobs, which at least did not attack around the clock.
Please reduce the spawn rate of hostile animals or add the possibility of their enmity with each other. In my world there are bears in the floor of the forest, wolves in the floor of the forest, who ate everyone except deer and annoying goats. Thank you for the attention

**Comment by DisasterMoo** [comment]
There's config for this:
- You can lower the spawn rate or even disable predators entirely.
- You can re-enable vanilla's mobs to surface.
- Lastly, there's peaceful mode too.
