### ISSUE TITLE
Water plants create air pockets

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#122]
This is probably an extremely obvious one, but still worth noting here anyway.

Plants which are set to generate within water cause air pockets to appear around them. This is not a case of the water simply not being invisible, as you cannot drink from these areas and the plants do not stop fall damage as water would.
![2019-06-28_14 14 18](https://user-images.githubusercontent.com/52297970/60344893-88811c00-99af-11e9-8d19-a7797922d32c.png)

**Comment by muzikbike** [comment]
![2019-06-28_14 22 25](https://user-images.githubusercontent.com/52297970/60345142-3d1b3d80-99b0-11e9-822a-122552a699d7.png)

**Comment by Dunkleosteus** [comment]
lmao, this is why I made waterplants into the blocks _below_ the water, ie the gravel or sand. Those blocks just rendered a plant above them. It meant there was never a physical plant in that space, only a water block, which prevented stuff like this.

**Comment by Claycorp** [comment]
100% intentional as there is no water logging in 1.12. They where made with 1.14 in mind like most of the other stuff.

It's been reported by almost everyone at this point.

**Comment by Dunkleosteus** [comment]
Just saying 1.7.10 didn't use water logging and avoided this problem.

**Comment by Claycorp** [comment]
Why make something that is just going to get dumped anyway..?
Extra work on an already giant project is all it is.

**Comment by alcatrazEscapee** [comment]
Yeah, I know that 1.7.10 did it that way, and it did work for the most part. These will probably get disabled or reworked in 1.12 as they are a bit of an eyesore. In 1.14 we'll enable them add waterlogging capabilities

**Comment by alcatrazEscapee** [comment]
These have been disabled, subject to future revisiting either in 1.14 or via a different method in 1.12.
