### ISSUE TITLE
Brining and pickling keep repeating

### ISSUE THREAD

**Issue by kingkoronov** [TerraFirmaCraft/TerraFirmaCraft#1220]
**Describe the bug**
1. What did you expect to happen?
When an item is finished brining or pickling in a barrel, it uses up an appropriate amount of brine/vinegar and then can be left in the barrel indefinitely without using up more brine/vinegar
2. What actually happened instead (i.e. what was the bug)
When brining/pickling finishes, the barrel sealed date updates to the current date and after another 4 hours, it uses more brine/vinegar.

**To Reproduce**
1. Fill a barrel with brine.
2. Put some brineable food into the barrel.
3. Wait 4 in-game hours, observe the barrel GUI
4. Wait another 4 in-game hours, observe the barrel again.

**Meta Info**
 - TFC Version: 1.0.12.141
 - I tested it on TFC only.

**Comment by nuuno2000** [comment]
Can confirm this happens. It also prevents the use of the "keeping in vinegar feature which gives a 0.1 multiplier, because if you keep food in vinegar it will pickle multiple times untill all the vinegar is gone.
