### ISSUE TITLE
Duck breeding

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1224]
I had fully famiarized ducks and a fully familiarized drake but the eggs in the nest box didnt seem to get fertilized.
Im not sure if this has been inplemented yet

**Meta Info**
 - TFC Version: 1.0.11.140

**Comment by DisasterMoo** [comment]
Just tested, it's working. You're supposed to give food to both (familiarity should be at 30%) and wait until drake feels like mating and entices a duck. You're going to see both mating by the heart particles and both trying to approach each other, also, the tooltip (hwyla or the one probe) will show you that the female is fertilized.

**Comment by nuuno2000** [comment]
hmm, alright, i just got some more ducks, ill try again.
