### ISSUE TITLE
Firepit damages you even when not touching the model

### ISSUE THREAD

**Issue by eerussianguy** [TerraFirmaCraft/TerraFirmaCraft#1226]
141. I was jumping over the fire pit, because I was trying to get into character, but I noticed that it actually damages you when you're occupying the same block as it, not when you're touching the model. Can anyone else confirm?

**Comment by DisasterMoo** [comment]
Unfortunately, this collides with another issue #1025, so, we choose to stick to the other one since fire things should be dangerous.

**Comment by alcatrazEscapee** [comment]
Fire pits are deadly! Use proper fire safety methods! Be warned: it is not required to touch the coals directly in order to burn yourself! If on fire, call your representative!
