### ISSUE TITLE
Unintended uses for rotten food

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1228]
Ive found 2 ways in which rotten food can be used that i assume are not intentional:
-Vinegar from rotten fruit
You can use rotten fruit to make vinegar, no differences from normal fruit
-Rotten food sandwiches
You can put 3 rotten foods in a sandwich (i havent tried to make it using rotten bread too) and the sandwich will not be rotten
I assume when making a sandwich it makes an average of the decay of all the ingredients, and since the bread still had a long time before becoming rotten it made up for the rotten food.

**Meta Info**
 - TFC Version: 1.0.12.141

**Comment by alcatrazEscapee** [comment]
> I assume when making a sandwich it makes an average of the decay of all the ingredients.
It does not, it intentionally just resets to the creation date of the sandwich, which combined with the higher decay rate of sandwiches compensates for this simplistic meal creation.

It should not accept rotten ingredients though.

**Comment by nuuno2000** [comment]
> > I assume when making a sandwich it makes an average of the decay of all the ingredients.
> > It does not, it intentionally just resets to the creation date of the sandwich, which combined with the higher decay rate of sandwiches compensates for this simplistic meal creation.
> 
> It should not accept rotten ingredients though.

it did tho, so something is not quite right

**Comment by Gaelmare** [comment]
I think rotten fruits should be allowed to make vinegar.
