### ISSUE TITLE
Animals going through fences

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1229]
Sometime i find that one of my animals has gone through the fence is outside, im not sure how to replicate it becasue ive never seen it happen, ive always just found the animals outside the fenced area

**Meta Info**
 - TFC Version: 1.0.12.141
 - Were any other mods included? Can you reproduce it without these other mods?
 - If necessary, what other mods (including versions) MUST be present to experience the bug?

**Comment by DisasterMoo** [comment]
May be related to #807, which the hitboxes isn't updated until the entity in question is reloaded.

**Comment by DisasterMoo** [comment]
Not yet fixed #1274.

**Comment by DisasterMoo** [comment]
Just want to note that this is my last attempt at fixing this. Vanilla also have the same issues: https://bugs.mojang.com/browse/MC-2025
