### ISSUE TITLE
Drinking water requires that a block be targeted, not the water itself

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#123]
Players must target a block which is underneath fresh water to be able to drink the water. This should probably be changed so that targeting the water allows the player to drink as well, regardless of whether or not a solid block is within reach.
![2019-06-28_14 28 24](https://user-images.githubusercontent.com/52297970/60345640-61c3e500-99b1-11e9-934c-bd92948dfbeb.png)
![2019-06-28_14 28 38](https://user-images.githubusercontent.com/52297970/60345642-61c3e500-99b1-11e9-805f-1dc85bada60c.png)

**Comment by alcatrazEscapee** [comment]
This is intentional, as `RightClickEmpty` does not fire on the server and it would be a huge pain to add the logic to control that.
