### ISSUE TITLE
Genetic size difference in animals

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1235]
In CTFC every animal had a slightly different size which would affect the ammount of meat dropped. This made selective breeding a way to get more food from one, as well as being a fun mechanic.
As was suggested in #1143 by DisasterMoo the butchering skill needs a nerf, so selective breeding would be another way of getting more food per animal.

**Meta Info**
 - TFC Version: 1.0.12.141 (at time of request)

**Comment by Azaysol** [comment]
i had forgotten about this feature, would be nice to see it come back
