### ISSUE TITLE
Full bucket gets dumped when clicking a barrel

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1236]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
To open the barrel GUI
2. What actually happened instead (i.e. what was the bug)
The liquid gets dumped onto the ground

**Meta Info**
 - TFC Version: 1.0.12.141

**Comment by nuuno2000** [comment]
I should also point out this only happens if the barrel in question alsready has a liquid that is not the same the bucket is filled with

**Comment by DisasterMoo** [comment]
You mean sneaking (shift) clicking? Because that's vanilla behavior.

**Comment by nuuno2000** [comment]
I could have sworn i wasnt shifting when this kept happening to me, but i just tested it and it seems to be working fine. Closing the issue, sorry.

**Comment by nuuno2000** [comment]
Reopening as ive been able to reproduce it again.
-Sealed barrel with liquid 1 (it was fresh water)
-Bucket with liquid 2 (it was milk)
-Right click the barrel with the bucket in hand

What happens:
The GUI of the barrel opens but the bucket also gets dumped

**Comment by DisasterMoo** [comment]
That is a bug interaction all right
