### ISSUE TITLE
Support Beams

### ISSUE THREAD

**Issue by Pelemesh** [TerraFirmaCraft/TerraFirmaCraft#1237]
**Describe the request**
Make sure to include:
1. What problem or issue would this enhancement solve?
 - Support beams being more convinient to use in certain situations
2. Describe the feature itself - what would change, what would happen. In general more detail is good!
- Vertical support beams can be only place on top of each other or on the bottom of the block if there is a vertical beam 1 block below it. **Would be nice to be able to place them by shift clicking on the placed vertical support beam and be able to extend it upwards**
- Can't place support beams on bottom half slabs, upside stairs

**Meta Info**
 - TFC Version: 0.X.X.XX (at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
 - If necessary, what other mods (including versions) would this require?

**Comment by Azaysol** [comment]
pretty sure 1.7 actually had this feature, Dries has also brought it up on stream i believe
