### ISSUE TITLE
Spanish moss texture is gray

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1238]
Title

**Meta Info**
 - TFC Version: 1.0.12.141

**Comment by alcatrazEscapee** [comment]
![spanish moss](https://forevergreentreeservice.com/wp-content/uploads/2019/05/Spanish-Moss-is-Not-a-Moss-1200x675.jpeg)

yes, yes it is.

**Comment by nuuno2000** [comment]
hahaha, it looks like when a texture fails to load or whatever, thought it wasnt supposed to be like that xD
