### ISSUE TITLE
Food duplication using food stacking key in non-player inventories.

### ISSUE THREAD

**Issue by officialGerero** [TerraFirmaCraft/TerraFirmaCraft#1239]
So its simple to replicate 
1. Get all the ingridients 
2. Put out a recipe
3. Craft one portion
4. Press X on sandwich in ur inventory
5.Then take out one part of sandwich and place it back
6. Repeat

Hope this is usefull, the taking a part out is just reset a recipe

**Comment by officialGerero** [comment]
Wanted to apoligize havent seen a bug template, stoopid me i guess =)

**Describe the bug**
Make sure to include:
1. What did you expect to happen?
When pressing x crafting reciper either ignores it or makes a cycle
2. What actually happened instead (i.e. what was the bug)
Sandwiches got duped
3. If it was a crash, upload the full log file (`latest.log`)
No, it wasnt
4. If they would help to explain the issue, include screenshots
Video mb would do it

**To Reproduce**
Attention to detail is important!
1. Get any ingredients
2. Put out a recipe
3. Craft one portion
4. Press X on sandwiches in ur inventory
5. Then take out one part of sandwich and place it back

Can be done with any amount\type of ingredients
https://drive.google.com/open?id=16oxFlvhd_trRmRxrJgkum_jYFIUdpHTN



**Meta Info**
 - TFC Version: 1.0.12.141
 - Were any other mods included? Can you reproduce it without these other mods?
Yes i got mods that are on a screenshot, pretty sure can be done in vanilla tfc
 - If necessary, what other mods (including versions) MUST be present to experience the bug?
Hope that none

**Comment by officialGerero** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/40302455/81501382-bbd74b80-92e0-11ea-86e8-6b98d86d0249.png)

**Comment by alcatrazEscapee** [comment]
Looks like the food stack key needs to either only scan the player inventory (and not the entire container), or only work in the player inventory GUI. That would be the best to avoid weird interactions with other containers (I'm sure salads also will have this issue, as does any other food crafting recipe.)

**Comment by officialGerero** [comment]
Yea probably, a cool feature tho.

**Comment by officialGerero** [comment]
Sup alcatraz =)

**Comment by officialGerero** [comment]
Also this time its in the player inventory, just to be clear xD
