### ISSUE TITLE
Plants can be placed in inappropiate climates

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#124]
It is possible to place a plant down in a climate where it would not survive. However, the plant is then immediately deleted afterwards, wasting the plant.

Instead, the plant should simply be prevented from being placed down at all.
![2019-06-28_14 40 00](https://user-images.githubusercontent.com/52297970/60346366-e400d900-99b2-11e9-9308-76937837eacc.png)

**Comment by Claycorp** [comment]
Place a plant in a place it can't grow and it dies, Seems logical enough.

Adding extra checks just adds more complexity for little reason.

**Comment by alcatrazEscapee** [comment]
The indicator under the plant does specify the climate that the plant will survive in. That said, I'm open to debate here.

**Comment by Konlii** [comment]
In survival mode the plant pops off as an item you can pick right back up.  It only disappears in creative mode, which is fine because the stack in your hand doesn't decrement anyway.

**Comment by alcatrazEscapee** [comment]
That seems like a reasonable solution to me.
