### ISSUE TITLE
Glass as a valid block for charcoal pits

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1241]
This would give a good way to know when the charcoal is ready and i would say glass should be able to withstand the temperatures posed by charcoal making, since bricks also do.
**Meta Info**
 - TFC Version: 1.0.12.141(at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
 - If necessary, what other mods (including versions) would this require?

**Comment by alcatrazEscapee** [comment]
Have you actually *tried* this, and found that it doesn't work?

**Comment by nuuno2000** [comment]
yes
