### ISSUE TITLE
Lava Blue steel lamps

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1242]
In CTFC we had the hability to fill blue steel lamps with lava for a permantent light source, im not sure if this feature was remove intencionally, but id like to see it in TNG as we dont currently have a way to have a permanent light source and olive oil is impossible to come by in the north. I dont think its op as blue steel is very late game.

**Meta Info**
 - TFC Version: 1.0.12.141 (at time of request)

**Comment by eerussianguy** [comment]
i'm not sure if that was a Classic feature or if that was the addon that added lamps

**Comment by Gaelmare** [comment]
It was a classic feature.

**Comment by eerussianguy** [comment]
Added in 1.18
