### ISSUE TITLE
Oceans are typically 6,000 to 14,000 blocks long, rivers are too rare

### ISSUE THREAD

**Issue by eerussianguy** [TerraFirmaCraft/TerraFirmaCraft#1244]
Version 141. This is half a feature, but still it's difficult to pick up and move when the nearest continent is half a world away. The ocean is empty, so there's no real justification for making them as large as they are. And then there's the deal with rivers spawning very rarely, which we've all talked about before.

Easiest way to reproduce is to TP yourself to the tropical region 10,000 blocks +Z, then TP laterally 2000 blocks at a time. Not every seed does this but many many do

**Comment by alcatrazEscapee** [comment]
Not getting changed in 1.12 as it's a direct port of classic world gen. Already getting looked at in 1.15.
