### ISSUE TITLE
Animals not providing product even after maxed out familiarity

### ISSUE THREAD

**Issue by BigE1293** [TerraFirmaCraft/TerraFirmaCraft#1246]
**Describe the bug**
Make sure to include:
1. What did you expect to happen? when a female cow or goat was maxed out with familiarity, I should be able to milk it
2. What actually happened instead (i.e. what was the bug) cows or goats with familiarity mostly or entirely maxed out dont provide milk
3. If it was a crash, upload the full log file (`latest.log`)
4. If they would help to explain the issue, include screenshots
(can show you screenshots tomorrow, WAILA says they are milkable but not
**To Reproduce**
Attention to detail is important!
1. Do 'get a female goat or cow to max familiarity'
2. Then do 'try to milk the cow or goat'

**Meta Info**
 - TFC Version: 0.X.12.141
 - Were any other mods included? Can you reproduce it without these other mods? (just waila and journey map, nothing else)
 - If necessary, what other mods (including versions) MUST be present to experience the bug?

**Comment by DisasterMoo** [comment]
A few things, if waila do not show them:
- They should be adult (not old or child). Not sure if waila don't show "Can Milk" on old cows.
- There's a cooldown after one milking. iirc, 1 day for cows and 3 for goats. Although Waila won't show the value, it should show that you "Can Milk"
- Last: How are you trying to milk your animals? Wooden Bucket, Vanilla Bucket, Other mod bucket, Jugs? And, are you on survival or Creative?

**Comment by BigE1293** [comment]
WAILA says their adults (otherwise it would say that it matures by X date). Even after max familiarity, they still can’t be milked with a wooden bucket. 

I have not tried an iron vanilla bucket, but if that’s the case, that might be an issue. I might have to make a workaround for that but I should be able to milk it with a wooden bucket no problem. 

Survival only. (I can update you with DMs of screenshots if possible)

(Edit: it does work with the vanilla bucket but not the wooden one)

**Comment by DisasterMoo** [comment]
As per discord discussion, this is not a bug but an outdated config.
