### ISSUE TITLE
Eating Wheat or other grains dont increase your grain stat

### ISSUE THREAD

**Issue by BigE1293** [TerraFirmaCraft/TerraFirmaCraft#1247]
**Describe the bug**
Make sure to include:
1. What did you expect to happen? to have my health increase when I eat a wheat grain
2. What actually happened instead (i.e. what was the bug) my hunger fills but my health doesn't chance, nor does the grain stat
3. If it was a crash, upload the full log file (`latest.log`)
4. If they would help to explain the issue, include screenshots
(can show tomorrow,)
**To Reproduce**
Attention to detail is important!
1. Do 'find wheat and/or turn it into a grain'
2. Then do 'eat the wheat or grain'

**Meta Info**
 - TFC Version: 0.X.12.141
 - Were any other mods included? Can you reproduce it without these other mods? WAILA and journey map, nothing else
 - If necessary, what other mods (including versions) MUST be present to experience the bug?

**Comment by alcatrazEscapee** [comment]
See #1152, #943.
