### ISSUE TITLE
Skeleton horses spawn

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1248]
Im not sure but i doubt keep this feature was intencional. If it was i suggest making them behave like TFC horses, ie the need for a lead when riding etc

**Meta Info**
 - TFC Version: 1.0.12.141
 - Were any other mods included? Can you reproduce it without these other mods?
 - If necessary, what other mods (including versions) MUST be present to experience the bug?

**Comment by Azaysol** [comment]
i had this happen, they are a mob not a tameable entity, they spawn with a rider that will agro you, but they die during daytime sometimes

**Comment by nuuno2000** [comment]
yeah, but still, are they meant to be in TFC?

**Comment by Azaysol** [comment]
that i do not know

**Comment by DisasterMoo** [comment]
Are they spawning on surface? Imo they should be limited to spawn only underground if possible, or not at all.

**Comment by Azaysol** [comment]
it seems their spawn condition is a thunder storm. when i was playing it spawned after a lightning strike next to me, spawned like 3 of them

**Comment by nuuno2000** [comment]
A "skeleton trap" gets spawned during a thunderstorm , then when a player aproaches it lightning strikes it spawning a few of the skeleton horses being riden by skeletons. Id sy they should just be removed as i dont see a way for lightning to strike one of those traps undergorund

**Comment by DisasterMoo** [comment]
Problem here is that skeleton horses aren't considered mobs since it extends the same class as horses
```java
public class EntitySkeletonHorse extends AbstractHorse
```
To fix: we need to specifically prevent EntitySkeletonHorse from spawning
