### ISSUE TITLE
Tool crating recipes should be made shapeless

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#125]
When I go to craft a shovel, I impulsively arrange the tool head and handle like this:
![2019-06-28_16 50 07](https://user-images.githubusercontent.com/52297970/60354841-17e4fa00-99c5-11e9-8f30-ed6f04f1ba7f.png)

As can be seen in the screenshot, this does not work. I propose that this should be made to work, either through making the recipe for tools shapeless or by allowing sticks diagonally adjacent to tool heads to work.

**Comment by alcatrazEscapee** [comment]
Crafting recipe related issues should use #63.
That said, this was not a feature in 1.7.10 iirc, and I don't see why it should be in 1.12.
