### ISSUE TITLE
Large blooms always give only 100 units?

### ISSUE THREAD

**Issue by C1ffisme** [TerraFirmaCraft/TerraFirmaCraft#1252]
**Describe the bug**

Smelting blooms in crucibles or on raw forges always produces 100 units of iron unless it's less than 100 units of iron. This is especially annoying as there is no way to craft 400-unit blooms into smaller chunks, etc.

**Meta Info**
 - TFC Version: 1.0.12.141 (Latest Curseforge)
 - Were any other mods included? Can you reproduce it without these other mods? JEI, HWYLA, Journeymap, and BlockRenderer, but I don't know that any of these would have an effect on the recipe.
 - If necessary, what other mods (including versions) MUST be present to experience the bug? N/A?

**Comment by alcatrazEscapee** [comment]
> This is especially annoying as there is no way to craft 400-unit blooms into smaller chunks

Except there is... the anvil will do that for you.
Or chuck them back into the bloomery to use again as fuel.

**Comment by C1ffisme** [comment]
I didn't know of this, thank you. (That being said it would be nice if this was disclaimed to the user in some way)
