### ISSUE TITLE
Polar Bear Ticking Entity

### ISSUE THREAD

**Issue by AnodeCathode** [TerraFirmaCraft/TerraFirmaCraft#1256]
**Describe the bug**
Make sure to include:
1. What did you expect to happen? Get eaten by a Polar Bear
2. What actually happened instead (i.e. what was the bug) Crash
3. If it was a crash, upload the full log file (`latest.log`)
  Crash Report: https://pastebin.com/00MPsbvL
  Relevant bits from Full Log:  https://pastebin.com/kieFgXN7
4. If they would help to explain the issue, include screenshots
https://i.imgur.com/fn5ZuyV.jpg

**To Reproduce**
Attention to detail is important!
1. Do '...' Go near Polarbear
2. Then do '...' restart 

**Meta Info**
 - TFC Version: 1.0.12.141
 - Were any other mods included? JEI, Journeymap, Hwyla
Can you reproduce it without these other mods? Yes

**Comment by Gaelmare** [comment]
Same issue as #1093
