### ISSUE TITLE
Add debug for damage types and entity names.

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#1257]
As per conversation on discord.

Any missing systems for getting info to use our config should be added. Currently this is just Damage types and Entity names. Update Config coments as well.

**Comment by alcatrazEscapee** [comment]
This issue does not apply, or has been fixed in the current MC 1.18 versions of TFC, and as MC 1.12 is receiving no more development, it will be closed. If this issue arises again in 1.18, please file a new issue report.
