### ISSUE TITLE
Crucible dupe

### ISSUE THREAD

**Issue by DisasterMoo** [TerraFirmaCraft/TerraFirmaCraft#1258]
Recent changes to small vessel heat recipe opened a bug in `TECrucible`. Basically, since the cached item isn't updated you end up with a duplicated small vessel because `HeatRecipe` does a copy

`ItemStack` and `Capability` instances both have to be updated after all this: https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/254ee67e5d554df9844f4b09a97dc80743a46465/src/main/java/net/dries007/tfc/objects/te/TECrucible.java#L116-L134
(hint here is that inventory is re-updated from recipe but the instance isn't)

**Comment by nuuno2000** [comment]
Im not comletly sure what this means, but ive found that when heating up small vessels containing ore in a crucible the ore melts and liquid metal starts pouring into the crucible, but the amount in the vessel always stays the same, essentially making metal from nothing.

**Comment by DisasterMoo** [comment]
That's essentially the dupe which i described above in code terms.
