### ISSUE TITLE
Male Adult (and sometimes young male) seem to not exist in the wild

### ISSUE THREAD

**Issue by BigE1293** [TerraFirmaCraft/TerraFirmaCraft#1260]
**Describe the bug**
Make sure to include:
1. What did you expect to happen? to come back to my farm with a male cow and a female cow and goats
2. What actually happened instead (i.e. what was the bug) my fully familiariarized cow and goat male just dont exist
3. If it was a crash, upload the full log file (`latest.log`)
4. If they would help to explain the issue, include screenshots (I have an old screenshot from the last "bug" I had, but this is a pretty big one)

**To Reproduce**
Attention to detail is important!
1. Do 'update from 141 to 142'
2. Then do 'find male animals are just gone no matter where you go'
(the issue seems to linger with existing worlds for some reason, this could be an isolated case but loading a new world did spawn male animals)
**Meta Info**
 - TFC Version: 0.X.X.142
 - Were any other mods included? Can you reproduce it without these other mods? (just WAILA, JEI, and journey map
 - If necessary, what other mods (including versions) MUST be present to experience the bug?

**Comment by DisasterMoo** [comment]
Not sure if it is something to old worlds, but for me it's working as intended. Some animals have a grouping rule: `Solo male or Female mother with children`, `Elder from the pack + everyone else`, `Male king and females`. This means that this last group will see much less males, but still have some.

Lastly, respawning or using spawn eggs have a 50% chance of spawning adult males or females, which i confirmed working.
