### ISSUE TITLE
Game suddenly crashed for no apparent reason

### ISSUE THREAD

**Issue by GivensRS** [TerraFirmaCraft/TerraFirmaCraft#1261]
Game suddenly crashed for no apparent reason
[spoiler](https://pastebin.com/wFdnn2LX)

I don't know how to reproduce this, i just had melting copper.

 - TFC Version: 1.0.12.141
 - All mods presented at crashlog.

**Comment by BigE1293** [comment]
Was this crash when logging out, or during gameplay?

**Comment by alcatrazEscapee** [comment]
Duplicate of #840.
