### ISSUE TITLE
Config to disable seasons

### ISSUE THREAD

**Issue by Xelbayria** [TerraFirmaCraft/TerraFirmaCraft#1264]
**Disabling the generation:**  
Seasons feature (honestly, I don't know much about this feature whether it's advanced or not) 

**Meta Info**
 - TFC Version: using the latest version 

### Details on why should you add the feature or disable:
I wish to use the "Serene Seasons" mod because it has plenty of features. I cannot find any information on TFC's season feature. There is not enough information for me to determine whether they are better or not. So Disabling is a better opinion rather than enhance the feature of seasons.

**Comment by eerussianguy** [comment]
https://tng.terrafirmacraft.com/No

**Comment by Xelbayria** [comment]
> https://tng.terrafirmacraft.com/No

I see. I'll remove that feature. that answered my question.

**Comment by alcatrazEscapee** [comment]
> food rotting feature (there are mods that can add this feature)

This can be done already. If you remember, I showed you the exact line in the config file which you need to change in order to do this.

> Disabling seasons

What *specifically* do you want to disable? There are many things here, many of which would *absolutely, completely* break TFC if we were to disable them. Saying "I want to disable this because I don't know anything about it" really does not help your case...

Also, if you have separate issues, *make separate issues*.

**Comment by Xelbayria** [comment]
Alright, if you don't know about the wiki not having any information about Seasons. 

what I would like to disable is the feature of changing colour/textures from 4 seasons and other features that would allow me to use the "Serene Seasons" mod without affecting how the environment works with TFC. I don't know if there would be a conflict between the TFC season feature and Serene Season features. 
When I say "disabling seasons" I meant all of the features that involved Season features. I don't think I was clear on that part. 

the part about food rotting, I ended up forgetting about it, sorry about that. You just jogged my memory. I'll just strike the feature out. 
**Edit:**
nvm, I see you have removed a few details from my first post.

**Comment by alcatrazEscapee** [comment]
Wiki from 1.7.10 is mostly accurate, as for 1.12 it's open for anyone to contribute to.

> I don't know if there would be a conflict between the TFC season feature and Serene Season features.

Why don't you try it?

> without affecting how the environment works with TFC

This is not going to be possible. Disabling seasons basically involves forcing the temperature to be constant which is going to have quite massive effects on every crop, bush, tree, grass, etc.

Is there a particular reason you want to use serene seasons? It's *much* easier, in the case that another mod does *exactly the same things as TFC*, to just *use the built-in TFC feature* for that.

**Comment by Xelbayria** [comment]
I see. hmm, I've taken a look at the feature of seasons. it's very simple where it only has to do with calender and dates. BUT I know that seasons are related to temperature and environment and how plants grow. 

Serene Seasons has the texture that you can tell by looking at the colour of the leaf, for example, it's fall season, you would see the orange/red-ish on the leaf. Winter seasons would have no leaves at all. Senere Seasons has all of that. It even has the same features that TFC has an effect on the crops and the environment. 

If TFC has the texturing for the leaves to change throughout the 4 seasons. then It looks like It was not necessary to post this request.

**Comment by alcatrazEscapee** [comment]
> It even has the same features that TFC has an effect on the crops and the environment.

These 99% won't work with TFC crops.

> If TFC has the texturing for the leaves to change throughout the 4 seasons.

Yes it does.

> It looks like It was not necessary to post this request.

In which case...

**Comment by Xelbayria** [comment]
sigh... in that case, I have no further requests to ask the developers... that's why it's not necessary to post this request. Thank you for answering all of my questions. I've learned a lot of things from you. Have a great day.
