### ISSUE TITLE
Raw eggs decays too fast

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1265]
- Even though fertilized ducks now display "Fertilized" in HWYLA, the eggs they lay dont display the same tag, making it hard to distinguish them from normal eggs.
- Raw eggs now rot, but way too fast, they should take at least 60 days to rot
 - TFC Version: 1.1.0.142

**Comment by DisasterMoo** [comment]
Clearly there's something else happening here: 
![image](https://user-images.githubusercontent.com/22617477/81960844-ef1f2080-95e7-11ea-8c6a-61ae48e6132f.png)

**Comment by DisasterMoo** [comment]
60 is too much, it would mean your eggs last for more than a half year in default config.
16 is a more reasonable number, and since you can continue producing eggs from both ducks and chickens through the winter, i don't see a reason for not using 16 days.

**Comment by nuuno2000** [comment]
well, i gave a limit to what eggs irl last for, idk how that translates into TFC, and yeah, its true you can keep producing them through the winter so it might not need to much.

I also have another issue open about how they give dairy instead of meat, which apperently was designed that way but just isnt right
