### ISSUE TITLE
Grain processing

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#127]
Currently there's no way to process raw harvested grains into the item grains, like there is in 1.7.10. This behaviour should be ported to 1.12.2.
![2019-06-28_17 01 44](https://user-images.githubusercontent.com/52297970/60357628-1408a600-99cc-11e9-8c9d-48f0e8a8961e.png)

**Comment by Red3Tango** [comment]
Processing grain with a knife does not give a piece of straw as in 1.7.10.
