### ISSUE TITLE
Animals disappear

### ISSUE THREAD

**Issue by Grigoriewich** [TerraFirmaCraft/TerraFirmaCraft#1270]
**Describe the bug**

Used mode creative.
Fed animals.
Time set day.
Animals sometimes disappear.
Video: https://youtu.be/dbe-tNgO0kE
This happens to other animals. Horse, duck, cow, chicken...

**Meta Info**
 - TFC Version: 1.1.0.142

**Comment by weiplume** [comment]
A similar problem. Only I still periodically issued a notice of the death of the animal from starvation.

**Comment by ghost** [comment]
Same. Investigated this when trying to tame horse in creative mode by setting next day after feeding

**Comment by DisasterMoo** [comment]
Duplicate of #1268
