### ISSUE TITLE
NOT Fixed gold pan desync (Closes #885).

### ISSUE THREAD

**Issue by Grigoriewich** [TerraFirmaCraft/TerraFirmaCraft#1271]
**Describe the bug**

 Sorry. I did not see a bug fix # 885
Goldpan works the same as before.
Video: https://youtu.be/ZjOjlRl9yD4

**Meta Info**

 - TFC Version: 1.1.0.142

**Comment by DisasterMoo** [comment]
Closing this in favor of reopening the not fixed issue #885
