### ISSUE TITLE
Rain should turn off fire pits and charcoal forges

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1276]
Rain doesnt turn off forges like i assume its suposed to (as thats how it was in 1.7.10)
havent tested pit kilns
**Meta Info**
 - TFC Version: 0.X.X.142

**Comment by Gaelmare** [comment]
pitkilns didn't go out in Classic, and don't in TNG either.

Firepits don't go out in TNG, and I think that's a bug.

**Comment by nuuno2000** [comment]
Yeah, i mean firepits :l
