### ISSUE TITLE
Goats' milking cooldown isn't working

### ISSUE THREAD

**Issue by seito88** [TerraFirmaCraft/TerraFirmaCraft#1277]
Hello,

I found some problems after new update. I can milk my goats indefinitely and also I noticed that some of my animals just vanished. Before last update this didn't happen before.

I play TFC with mods: Gravestone, Harvest, Hwyla, JEI, NEI, TFCTech, WailaHarvestability.

**Comment by DisasterMoo** [comment]
> I noticed that some of my animals just vanished

Duplicate, of the duplicate, of the duplicate of issue #1268 

Otherwise, the milking cooldown is a new issue, thanks to let us know
