### ISSUE TITLE
Berry bushes

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#128]
In 1.6.4 and I believe 1.7.10 TFC, there existed berry bushes which would give berries when harvested. Since the berry items exist in the game I believe that the bushes are planned.

- Blackberry
- Blueberry
- Bunchberry
- Cloudberry
- Cranberry
- Elderberry
- Gooseberry
- Raspberry
- Snowberry
- Strawberry
- Wintergreen Berry

**Comment by alcatrazEscapee** [comment]
Added in #174, and then #199
