### ISSUE TITLE
Deers (Doe) dont drop anything.

### ISSUE THREAD

**Issue by ghost** [TerraFirmaCraft/TerraFirmaCraft#1280]
Deers that marked as Doe dont drop anything.

Here is video:

https://youtu.be/tfpDoyK5Zy4

Not sure but maybe other animals have this bug.

 - TFC Version: MC1.12-1.1.0.142

**Comment by DisasterMoo** [comment]
You mean baby animals? Because even on your video, the last one you kill is a doe.

And yeah, baby animals won't drop anything, that's vanilla.

**Comment by ghost** [comment]
Looks like I was wrong because some baby deers looks like adult

https://i.imgur.com/S4ffiEh.jpg
