### ISSUE TITLE
Please make it possible to change the length of the year in the configuration file

### ISSUE THREAD

**Issue by LevFilatov** [TerraFirmaCraft/TerraFirmaCraft#1281]
1.This may not solve any problems, but it will give us more time to grow the crop, and it will add more realistic survival
2. Two new lines will be added to the configuration file. First, to change the number of days in the year, and second, to switch to the real year (true or false), the number of days in the month will be increased from 8 to the real one (February 30, 31, and 28 in February). if possible, please implement leap years (1 day will be added every 4 years in February).

 - TFC Version: 1.1.0.142 (at time of request)
 - This will definitely affect TFC, I don't know about mods.
 - starting with the next version, mods are not required

**Comment by DisasterMoo** [comment]
The requested feature already exists: https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/254ee67e5d554df9844f4b09a97dc80743a46465/src/main/java/net/dries007/tfc/ConfigTFC.java#L476-L478

**Comment by alcatrazEscapee** [comment]
I will add, that this specific config will only affect new worlds. To change the month length in an existing world, you need to use the command `/timetfc set monthlength [value]` to avoid totally messing up the calendar.

**Comment by LevFilatov** [comment]
Okay, thanks

**Comment by Mortis10** [comment]
Is this an option in 1.20? The command doesn't work for me.
