### ISSUE TITLE
Creation of ghost blocks due to instant mine

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1284]
Im not sure if this has to do with TFC or just minecraft itself, but insta breaking blocks leave an insane amount of ghost blocks (invisible but still there). This is made worse because the smithing skill is way too easy to get to a high level, making tools very fast and allowing for insta minig of a lot of blocks.

**Meta Info**
 - TFC Version: 0.X.X.142
 - Were any other mods included? Can you reproduce it without these other mods?
 - If necessary, what other mods (including versions) MUST be present to experience the bug?

**Comment by alcatrazEscapee** [comment]
This is a well known vanilla bug.
<https://bugs.mojang.com/browse/MC-156852>
