### ISSUE TITLE
Everything in a barrel with water is "Preserve in vinager" now

### ISSUE THREAD

**Issue by dries007** [TerraFirmaCraft/TerraFirmaCraft#1286]
**Describe the bug**

![image](https://user-images.githubusercontent.com/1346725/82161440-e3a84f80-989c-11ea-8a62-14bbd37d1001.png)

I suspect that it's due to the recent changes in regards to #1266

Also happens with other stuff in fresh water barels. I haven't tested other fluids yet.

**To Reproduce**
1. Put maple log in barrel of fresh water

I did this on a server, did not verify on SSP.

**Meta Info**
 - TFC Version: 1.2.0.143 (+ my worldgen patch, but that shouldn't matter)
 - Other mods leather watersacks and some other minor junk (jei, top, ...)
   I'm too lazy to go check if it happens without them.

**Comment by dries007** [comment]
Oh and this is actually preventing crafting of recipes, like scraped to soaked hides

**Comment by nuuno2000** [comment]
Gotta preserve your wood in vinegar
