### ISSUE TITLE
Tomato is fruit.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#1288]
Bad food is bad.
![image](https://user-images.githubusercontent.com/40124890/82166894-e497ac00-98b1-11ea-87ee-224461498abb.png)

Tomatoes are fruits.

**Comment by alcatrazEscapee** [comment]
> Knowledge is knowing that a tomato is a fruit; wisdom is not putting it in a fruit salad.
