### ISSUE TITLE
Better moving + TFC = broken helmet models.

### ISSUE THREAD

**Issue by M8-u** [TerraFirmaCraft/TerraFirmaCraft#1290]
![2020-05-17_09 31 50](https://user-images.githubusercontent.com/53875064/82262818-9c1ed380-992f-11ea-8ad7-275605747bd7.png)
Note: it displays correctly on entities
Bug occurs on TFC version 1.2.0.142, 1.2.0.143 and 1.2.0.144.
To reproduce: Equip a helmet (that is not bronze).
Look at the player in either 3rd person views or the player inventory.

**Comment by M8-u** [comment]
Update: This visual error is caused by the better movement mod. I could've sworn that I replicated this in vanilla TFC. After removing the mod I realized that helmets actually do display correctly. This can become a low priority enhancement/bug fix, or closed.

**Comment by alcatrazEscapee** [comment]
Given that I can't actually find this better movement mod, nor do I particularly want to, and that as far as I can tell our helmet's work exactly the same as vanilla, I'm going to give this ole "yeah we aren't going to do anything about this" treatment.
