### ISSUE TITLE
Barrels with any liquid when sealed display "preserving in vinegar"

### ISSUE THREAD

**Issue by M8-u** [TerraFirmaCraft/TerraFirmaCraft#1291]
![2020-05-18_14 35 10](https://user-images.githubusercontent.com/53875064/82263024-0d5e8680-9930-11ea-818c-b32083c2f73d.png)

Bug occurs on TFC version 1.2.0.143

**Comment by alcatrazEscapee** [comment]
Duplicate of #1286
