### ISSUE TITLE
Leather knapping is broken

### ISSUE THREAD

**Issue by M8-u** [TerraFirmaCraft/TerraFirmaCraft#1295]
**Describe the bug**
1. What did you expect to happen?
Open the leather knapping GUI.
2. What actually happened instead (i.e. what was the bug)
Right clicking the leather(s) does nothing.
![2020-05-19_16 10 32](https://user-images.githubusercontent.com/53875064/82374647-57f20880-99ed-11ea-80d2-c368c6c73fad.png)

**To Reproduce**
Attention to detail is important!
1. Right click leather.

**Meta Info**
 - TFC Version: 1.2.1.144
No other mods were present and can be replicated in creative with leather.

**Comment by alcatrazEscapee** [comment]
Except it's not. You need a knife in your inventory.
