### ISSUE TITLE
Sleeping in other dimensions does not pass the night

### ISSUE THREAD

**Issue by prestomajesto** [TerraFirmaCraft/TerraFirmaCraft#1298]
Using Nomadic Tents and sleeping inside the "tent dimension" passes no time. I'm not sure if this is a problem with TFC or Nomadic Tents, but it might be worth looking into.

**Comment by eerussianguy** [comment]
In vanilla, the overworld is the only dimensioo you are able to sleep in, so I'm not surprised there's an incompatibility here. Please also make an issue on the Nomadic Tents github

**Comment by alcatrazEscapee** [comment]
This issue does not apply, or has been fixed in the current MC 1.18 versions of TFC, and as MC 1.12 is receiving no more development, it will be closed. If this issue arises again in 1.18, please file a new issue report.
