### ISSUE TITLE
Geologist Advancement

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1300]
The geologist advancement is supposed to be given to the player once they have found every type of rock and a specimen of every gem, however this would come up to 33 gems and rocks, and the achievment is given to the player once they reach 17 out of the 33 types of gems/rocks. I havent found every rock type and ive just found the only gem type i was missing but i still got the advancement.

**Meta Info**
 - TFC Version: 0.X.X.142
 - Were any other mods included? Can you reproduce it without these other mods?
 - If necessary, what other mods (including versions) MUST be present to experience the bug?

**Comment by alcatrazEscapee** [comment]
> The geologist advancement is supposed to be given to the player once they have found every type of rock and a specimen of every gem

Yes, every *type* of rock, i.e. Sedimentary, Metamorphic, Igneous Extrusive, Igneous Intrusive. Not every rock.
