### ISSUE TITLE
Improved food stacking

### ISSUE THREAD

**Issue by ghost** [TerraFirmaCraft/TerraFirmaCraft#1304]
In the current state, food is stacked so that the rotting time of the stack becomes the same as that of the oldest piece of food.

This does not make sense, because if, for example, you put together a piece of pork that rots after 20 days and which rots after 5 days, then the food will rot in a stack after 5 days.

Maybe then to make it so that when combining food, the value of the time of decay was calculated by the arithmetic mean? For example, if you combine the same pieces of pork for 20 and 5 days, you will get food that rot in 20+5/2 = 12.5 days (if round, then 13 days)

**Comment by Grigoriewich** [comment]
I will support. That would be fair.

**Comment by DisasterMoo** [comment]
> One bad apple spoils the bunch

yeah, this is true also in TFC, and will still be true here, both for gameplay and for "realism"

Just ponder your idea for a bit: If you have an almost rotten piece of meat and you want to "restore" it, you just need to stack with a "just created" one, and keep doing that so your food supply will never spoil.

Lastly: The stacking mechanic is something used as gameplay choice: You either stack foods together for convenience while losing precious expiration time, or you don't to keep good ones still going.
