### ISSUE TITLE
TFCT: Need cold climate source for lamp fuel

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1306]
Now that olives need 19 degC to ripen in October, most temperate locations won't work for olive oil. We should have another source.

Possibilities:
Tallow
Petroleum products (shale/coal oil?)
Latex/resin
Alcohol
Seed/nut oils
?

 - TFC Version: build 144

**Comment by nuuno2000** [comment]
Imo 19C in october is too hot for olive trees anyways, should be 15 at the most, and id make it lower so northern reagions can get olive oil

**Comment by Azaysol** [comment]
i would like to see alcohol have another used besides a roleplaying aspect. but besides that another one that would be also easy to implement is prob tallow

**Comment by alcatrazEscapee** [comment]
Ah, #1309
