### ISSUE TITLE
TFCT: goatcry3.ogg is bad

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1312]
I think this sound file should burn in a fire.

 - TFC Version: build 144

**Comment by alcatrazEscapee** [comment]
I don't see any issue with it. ¯\\\_(ツ)\_/¯

**Comment by Gaelmare** [comment]
Wait, what? I'm very surprised you don't hear the 96Hz hum in the soundfile. Perhaps play goatcry2 then goatcry3? It's very bad, and was roundly denounced both on TFCT and during some discord discussion after.

**Comment by alcatrazEscapee** [comment]
*maybe you should of put that in the issue description instead of making a joke.*
