### ISSUE TITLE
TFCT: Anvil recipe for output not selected even if single

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1314]
When making steel from pig iron, the just-created high carbon steel ingot must be picked up and placed down before the single anvil plan is automatically selected.

 - TFC Version: build 144

**Comment by Claycorp** [comment]
This is a limitation of the way the block updates as the recipe setting for single options is part of the overall recipe setting.

A slots item getting replaced with another doesn't actually trigger it to update anything and thus the recipe doesn't get applied.
