### ISSUE TITLE
TFCT: Make 2x handstone handles reachable from the side

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1317]
When looking sideways at two querns, you can't quite get both handles one after another without changing viewpoint a little.

It would be convenient if they lined up better.

See stream clip: https://clips.twitch.tv/CrunchyShinyHerbsRedCoat

 - TFC Version: build 144

**Comment by DisasterMoo** [comment]
A few concerns:
- Handle is outside the block's bounding box, it's actually a little bit inside the above block's space.
- While rising the bounding box to full block might fix this issue, it's gonna make entities hang over, which is weird.

**Comment by alcatrazEscapee** [comment]
This looks like a simple issue of "you're looking at the quern at an angle". Of course it's not going to line up perfectly. The player has a nonzero height and there's probably some perfect height you need to be at to draw a parallel line from the player's eye level across several querns.

That said it seems ridiculous to special case this specific interaction with a hitbox change, especially when the hit box, is already accurate to the model.
