### ISSUE TITLE
TFCT: Leads are more flaky than they used to be?

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1318]
On an early test server, I yanked 3 cows on leads across 1k blocks of water with no issues. 
Now, the TFCT crowd had leads break several times in the water. Is this new?

**To Reproduce**
1. Get three pigs on leads next to the water
2. Get in a boat, and drag them into the water
3. Paddle the boat a few hundred blocks, and observe the leads break.
4. F5 mode was used.

 - TFC Version: build 144

**Comment by p0kes** [comment]
That's been my experience too. They didn't break hardly at all but since a few versions ago are now even worse than Classic.

**Comment by Gaelmare** [comment]
We need to compare build 136 against 144+ for lead usage. 137 is where the passive mob AI was changed to try and run from the player. If this broke leads, we need to consider fixing it.

**Comment by Gaelmare** [comment]
Just tested this with and without a check for isLeashed in shouldExecute of TameableAvoidPlayer. Didn't help in SSP, only had leads break once in each case.

**Comment by eerussianguy** [comment]
Mojang please
