### ISSUE TITLE
Dirt falling due to gravity crashes through ores

### ISSUE THREAD

**Issue by StandardHunter** [TerraFirmaCraft/TerraFirmaCraft#1319]
1. What did you expect to happen?
That the dirt lands on the ore.
2. What actually happened instead:
Dirt (not tested with other blocks) falling (straight or sideways) destroys any ore block it fall on (even multiple blocks in a row) settling in the lowest ore position; ores are completely destroyed (no drops).

**Meta Info**
 - Minecraft 1.12.2
 - Forge 14.23.5.2854
 - TFC Version: 1.2.1.144
 - No other mods

**Comment by DisasterMoo** [comment]
Intentional. There's a config for disable falling blocks, or just the ore destruction part.

**Comment by StandardHunter** [comment]
Thank you for the response.

Suggestion:

Side note: I fully support this to be working as such in the event of a cave-in.

Is it maybe possible to alter it so that a single dirt block falling one block deep does not have enough "impact power" to destroy ores.

Either by giving the option to disable this feature for lighter block specifically
or to tie the impact somehow to fall height?

**Comment by DisasterMoo** [comment]
Saddly, there's no "impact power" to falling blocks, and i don't think we can disable only dirt ones from breaking ores without hard coding it. I can only suggest waiting for 1.15, the falling mechanic there was rewritten and ore blocks works differently (they fall! but are not destroyed by dirt).

**Comment by StandardHunter** [comment]
Okay , thank you.
