### ISSUE TITLE
Large Vessel can not be filled at watersource / with any fluid

### ISSUE THREAD

**Issue by StandardHunter** [TerraFirmaCraft/TerraFirmaCraft#1320]
1. What did you expect to happen?
According to the classic wiki one should be able to fill large vessels similar to buckets.
(Just for drinking, not to create water blocks.)

> Large Vessel
>
>Large Vessels are a lower tier version of barrels. As you are unable to make a wooden bucket in the >stone age, **you will only be able to fill the large vessel with liquid by either using it like a bucket >on a source block of salt or fresh water**, or by leaving it unsealed and exposed to the sky while it >is raining to slowly fill it with fresh water. 

2. What actually happened instead 
Was unable to do so. Could only "place" vessel in water, were it immediately got destroyed dropping the vessel.

**Meta Info**
 - Minecraft 1.12.2
 - Forge 14.23.5.2854
 - TFC Version: 1.2.1.144
 - No other mods

**Comment by StandardHunter** [comment]
Does not work via bucket either.

**Comment by DisasterMoo** [comment]
> According to the classic wiki

Not the case in TNG:
Barrel = Fluid container.
Large Vessel = Item Container.
