### ISSUE TITLE
Explosions should not destroy ores

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1325]
This is a Classic feature: Ore blocks always dropped as items when destroyed by explosions.

Items would still be destroyed by falling blocks though.
https://1710-wiki.terrafirmacraft.com/Barrel#Powder_Keg describes how explosions affected Ore in Classic.

**Meta Info**
 - TFC Version: build 145

**Comment by DisasterMoo** [comment]
I believe then it should be implemented in your PR #1307 
You probably need to make something on `onExplosionDestroy`

**Comment by Gaelmare** [comment]
Ok, will do.
