### ISSUE TITLE
TFCT: Forges and Blast Furnaces should spread fire like pitkilns

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1326]
These blocks get extremely hot, and should light other blocks on fire like pitkilns when they are lit.

 - TFC Version: build 142

**Comment by DisasterMoo** [comment]
Both for gameplay and for realism: No!

Both indeed get hot, iron melt at 1600 ºC which is the indicative that they get close to this temperature but heat alone don't light stuff on fire, that depends on where this heat is radiating to. Yes, paper, wood and other flammable materials would catch fire, but those multiblocks are constructed by fire resistant stuff: Fire clay and stone blocks. And yes, they contain heat.
