### ISSUE TITLE
fire blocks should implement Block#isBurning to help AI pathfinding

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1327]
Only BlockPitKiln implements isBurning. Should be implemented on at least Firepits, Forges, and Bloomeries.

**Meta Info**
 - TFC Version: build 145

**Comment by DisasterMoo** [comment]
Bloomery is a block that is always covered from all sides but the front, it would not add any functionality. The others should light entities on fire if they walk above, so i agree.

**Comment by Gaelmare** [comment]
I meant the blockMolten at the top of the bloomery and blast furnace columns, sorry.
