### ISSUE TITLE
TFCT: Metal items should heat faster in a hot crucible with enough liquid

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1331]
If an item is completely surrounded with hot metal, it will heat faster.

I think this would be believable and useful.

 - TFC Version: build 140

**Comment by Wahazar** [comment]
Also small ore pieces should heat up faster than normal objects. About 10x..3x faster, because they are 10x..3x smaller than ingot.
