### ISSUE TITLE
Barrel recipe for flour + water -> dough.

### ISSUE THREAD

**Issue by alcatrazEscapee** [TerraFirmaCraft/TerraFirmaCraft#1337]
1 flour + 1 B fresh water -> 2x dough. Same ratio as crafting, just slightly more convenient when crafting in bulk (although may still be preferred if you want to just craft 1-2 instances).

**Comment by eerussianguy** [comment]
Instant?

**Comment by alcatrazEscapee** [comment]
Never mind, this wouldn't work as many flours are used for alcohol. If the issue is to be addressed it needs a different approach.

**Comment by nuuno2000** [comment]
Maybe make it so 1 bucket can "hydrate" up to 8 flour, like, you can craft a bucket with up to 8 flour (in a crafting bench)
