### ISSUE TITLE
Crucible and Refined Iron Bloom

### ISSUE THREAD

**Issue by MrByryndyk** [TerraFirmaCraft/TerraFirmaCraft#1338]
Hi!
Smelted Refined Iron Bloom with 840 units in Crucible. But I get only 100 units of Wrought Iron.
![2020-05-27_10 39 16](https://user-images.githubusercontent.com/26432677/82991956-2093e500-a007-11ea-880d-3a6a1eee1980.png)
![2020-05-27_10 39 28](https://user-images.githubusercontent.com/26432677/82991964-238ed580-a007-11ea-819b-2fb52f7b890b.png)

**Meta Info**
 - TFC Version: 1.12.2-1.3.2147
 - Forge 14.23.5.2854
 - Without other mods, everything is exactly the same.

**Comment by boltonlass** [comment]
I did this the first time (and the second!).  You have to put the bloom back in the anvil after you have refined it and split it into smaller ones, you should get 8 x 100 and a 40 unit.  They can then be processed further either by melting in the crucible or you can work the 100 unit ones on the anvil.  It will give you two in the anvil and spit the rest out at the side so make sure you pick them all up.

**Comment by MrByryndyk** [comment]
Hm, ok. It's work.
But it is strange that you cannot melt the whole bloom at once -_-
