### ISSUE TITLE
Item entities should cool down when in water

### ISSUE THREAD

**Issue by CosmoTheCosmicCat** [TerraFirmaCraft/TerraFirmaCraft#1347]
Right now, the only way to cool down items faster is to put them in a barrel of water. It would make sense if putting the items in a body of water would do the same. Since tossing the items into the water wouldn't work in 1.12.2, having the player stand in water to cool down items in the inventory would be a good alternative.

**Meta Info**
 - TFC Version: 1.3.2.147 (at time of request)
 - TFC Enhancement
 - None

**Comment by alcatrazEscapee** [comment]
Or, ya know, just cool down items in water...
