### ISSUE TITLE
Issue between TFC and CraftTweaker / Dropt 

### ISSUE THREAD

**Issue by Xelbayria** [TerraFirmaCraft/TerraFirmaCraft#1348]
**Meta Info**
 - TerraFirmaCraft-MC1.12.2-1.3.2.147
 - dropt-1.12.2-1.18.0
 - PrimalCore-1.12.2-0.6.105
 - athenaeum-1.12.2-1.18.1 (core for DROPT) 
**FORGE**: forge-14.23.5.2854

SCRIPT: https://pastebin.com/yYHNXsFp

================================================================

**Details:** 
The issue is very similar with Craft Tweaker where I tried everything and nothing work. It's same for
DROPT mod as well. How does it work? The Script is created to add an ingredient to any grass from TFC where I can pick up one ingredient (from PrimalCore, Plant Fiber) 

**Am I 100% sure that the script is working?** Yes, it is working as it's expected. I tested it in Biome O' Plenty without TFC and included all of the grasses from BOP in the script and I am able to get the ingredient without any trouble. I don't know why, but one thing for sure is that TFC doesn't have fully support for Craft Tweaker and DROPT. 

If you have any questions, then ask. If you wish to run the script for CraftTweaker, then I can provide the script for testing. Just ask. 

================================================================

**If you wish to reproduce the issue and confirm:** 

1) get all of these mods in the list

2) once you run the Minecraft to load and it will crash (this is a conflict between PrimalCore and TFC) 

3) go to Config and find primal.cfg and disable the following: 
Line 1414, B:REPLACE_VANILLA_TORCHES = true    -> false 

4) now get the script from pastebin and make sure you save the script as filename.json. then drop it in DROPT's folder via config folder    (.../config/dropt/filename.json) 

5) run the Minecraft and create a new world in TFC worldgen. Once you are in-game, do ( /dropt reload ) so you can see it's processing one file. 

6) now try to break any grass to get an ingredient called "Plant Fiber" with an empty hand
 
**Result:** it doesn't matter which grasses / plants you break and you won't see any plant dropping one ingredient (Plant Fiber from PrimalCore).

================================================================

**Extra detail**
Edit: I forgot to add one more thing. When I ran the script with CraftTweaker (CrT) and breaking any grass and nothing dropped. I've discussed with some people about this and they said that the "event" from CrT is not firing even the script is correctly coded. That's one possibility for why the ingredient is not dropping at all. 

I also tried it with Biome O plenty and CrT... it worked just fine. 

the best way to fix this is to add "drop event" or "event" to TFC so Craft Tweaker or Dropt can work with TFC.

**Comment by DisasterMoo** [comment]
Harvesting event is not fired at all, majority of our plants won't need it if you are not using the required tool, either bypass the harvest check by using `PlayerEvent.HarvestCheck` or use another event like `BlockEvent.BreakEvent` (in CT is `BlockBreakEvent`) that is fired regardless of the harvesting check.

**Comment by Xelbayria** [comment]
wasn't "PlayerEvent.HarvestCheck" from Minecraft Forge? and I am familiar with BlockEvent.BreakEvent, 

i've tried it. It doesn't work at all. I've tried everything using CraftTweaker (CrT). I even tried "event.BlockHarvestDropsEvent"
 it also doesn't work either. 

EDIT: 
you should change the TFC's code where it has read the code from CraftTweaker's scripts if the block is broken and will drop an item/ingredient with an empty hand (no knife or any tools). 
I found out the rule is that block cannot drop without the knife from TFC, not knives from other mods. SERIOUS?!
TFC has full support on Craft Tweaker, yeah right. You should add this to your description on the TFC website and Curseforge. 

if you are not planning to do that, then you should give me an example of the script that will work with TFC using a knife from another mod and using an empty hand. I've tried everything, I've run out of ideas.

**Comment by alcatrazEscapee** [comment]
> wasn't "PlayerEvent.HarvestCheck" from Minecraft Forge? and I am familiar with BlockEvent.BreakEvent,

Yes, both of these are forge events, seeing as this is an actual mod that uses forge.

> you should change the TFC's code where it has read the code from CraftTweaker's scripts

We don't read code from craft tweaker scripts. Craft tweaker reads its scripts and executes them. All we do is register additional methods that can be called into TFC APIs. What you're complaining about has nothing to do with our craft tweaker support. It's an interaction (which we've said multiple times now, is working as intended) to do with harvest checks in vanilla minecraft.

> I found out the rule is that block cannot drop without the knife from TFC, not knives from other mods

The knife requirement in question is for the tool class `knife` being present. If there's a case for a different more pack-maker friendly check that you would like done here, feel free to open another issue with that *specific* request.

> if you are not planning to do that, then you should give me an example of the script that will work

I could fairly trivially write a mod that adds the prerequisite drops using the provided forge events. I am not going to, because frankly I have no interest in doing so, and am not beholden to make you a script that proves my point. If craft tweaker supports the prerequisite events, then it's possible. Your inability to write a functioning script does not our craft tweaker compatibility invalidate.

**Comment by Xelbayria** [comment]
alright, then what are events that TFC and Craft Tweaker can support? If you don't mind giving me a list of events that would allow me to find a workaround the issue. Where the events that could work with events without the required tool and so that I can add another ingredient from another mod to the plant.

**Comment by Xelbayria** [comment]
Hello? 

I am trying to understand how the system of TFC works? Can you please give me some information so I can find the right script that will work with TFC? 

EDIT: You say this is working as intended? did you use the script I posted to test to see if it worked or not? 
There are tall grasses that I can easily just used my own hands to pick them up (I don't even need the tools). This is why I posted the issue on TFC's issue list.
