### ISSUE TITLE
Hostile ranged mobs should be restored

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1349]
While the armored mobs are a bit challenging, adding back ranged mobs would add another dimension. The iconic javelin skeletons and vanilla bow skeletons would be great, and shouldn't require much model work. It would also be good to have a effective ranged weapon against them, but perhaps that's an addon (slings?)

 - TFC Version: build 147

**Comment by Azaysol** [comment]
would also like to see these return

**Comment by alcatrazEscapee** [comment]
> The iconic javelin skeletons

Nah
