### ISSUE TITLE
Animals spawn environment 

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1350]
Some animals already have specific spawn environments (Polar bears, Camels, Ocelots, Chickens etc.) but some others also need to be limited to specific environments:
- Sheep in cold environments (was this was in 1.7.10)
- Sabertooth Tigers and Wolves in cold environments
- Lions in hot dry environments (such as savanas and deserts)
- Hyenas in hot environments
- Bears and Deer in cold and temperate environments (maybe only forests)
- Cows, Phesants, Pigs everywhere but hot dry environments (such as deserts and savanas)
- Rabbits in temperate environments
- Horses and Donkeys in temperate and hot dry environments (such desests, savanas and plains)
- Black Panthers in Tropical environments
- Ducks in temperate environments and close to fresh water (rivers, lakes etc.)
- Goats in cold environments (especially mountainous)

This along with the lowering of animal spawn rates would make it harder for players to get every single animal, making exploring new environments important. This would also make it so you can only find certain predators in certain regions. Overall this would make the distribution of animals in the world more realistic.
 - TFC Version: 0.X.X.146 (at time of request)

**Comment by DisasterMoo** [comment]
Not possible at 1.12 (biomes are unreliable) . Wait for 1.15.
