### ISSUE TITLE
Rabbits killing themselves

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1353]
Most animals run from the player when they arent domesticated and the player isnt holding grain, but they dont jump to their death when they encounter a cliff, rabbits othe the other hand just jump to their death.
**Meta Info**
 - TFC Version: 0.X.X.146 (at time of request)

**Comment by eerussianguy** [comment]
This is a vanilla bug. Silly Minecraft AI is baked into the game. Not sure what you're getting at here

**Comment by nuuno2000** [comment]
Havent played vanilla in a long time, thought this behavior might have been cause by some changed made to the rabbits, closing
