### ISSUE TITLE
Extinction of prey animals 

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1356]
Animals such as sheep, ducks and chickens can be easily hunted to extinction by their predators, making them hard to find in chuncks that are loaded for some time.
Prey should be able to run away more efficiently from their predators and animals capable of fighting back (such as rams) should do it if they cant run away.
Predators should also not hunt all the time, having a cooldown to do so.
Making prey animals respawn if their number in a specific area drop very low would also help the problem.

**Meta Info**
 - TFC Version: 0.X.X.146 (at time of request)

**Comment by DisasterMoo** [comment]
There is a config to change which animals are hunted for food by some carnivores. Also, respawning is another configurable feature you can add which livestock animals respawn if you want.
