### ISSUE TITLE
Polishing to animals

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1357]
- Vanilla animals are very boxy and less detailed compared to their TFC conterparts, so i would suggest making them as detailed as TFC's
- I would also suggest renaming certain animals depending on their gender and age, i.e. male cow - bull and male sheep - ram, young cow - calf and young sheep - lamb
- I also suggest reskining and renaming some animals as like their wild counterparts, such as pigs being bigger and brown in colour, as well as having big teeth (and maybe more agressive, making them harder to domesticate) and rabits being thinner, longer and with bigger ears, making them hares.

**Meta Info**
 - TFC Version: 0.X.X.146 (at time of request)

**Comment by Azaysol** [comment]
some of this is already being worked on for 1.12 (hares/hogs and some other new animals for biome diversity) the rest like updating vanilla animals might be left for 1.15

1st point - will prob be left for 1.15
2nd point - will consider with others and see about changing with new animals update (1.12)
3rd point - being worked on for 1.12
