### ISSUE TITLE
Different crops should require different temp/railfall to grow (like fruit trees)

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1358]
At the moment crops all have the same requirements when it comes to temp/rainfall to grow besides bell peppers, jute and sugarcane, imo it should be different for each crop, like it is for fruit trees.
I also recomend that crops and fruit trees only spawn where the environment is suitable

**Meta Info**
 - TFC Version: 0.X.X.146 (at time of request)

**Comment by DisasterMoo** [comment]
Good catch, seems it was forgotten: https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/254ee67e5d554df9844f4b09a97dc80743a46465/src/main/java/net/dries007/tfc/util/agriculture/Crop.java#L31-L37

**Comment by Gaelmare** [comment]
Seems like with the taste system gone, there's less reason to need a bunch of different vegetables and grain. Balancing these so they're believable and available in enough climates will be work. Potatoes are very hardy, and are grown above 10,000 ft in the Andes and Nepal. :)

**Comment by eerussianguy** [comment]
Related: #802 but I don't see why we'd implement that when we didn't for fruit trees and berries.
