### ISSUE TITLE
Olive paste doesnt spoil

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1359]
It should spoil at least twice as fast as olives themselves.

**Meta Info**
 - TFC Version: 0.X.X.146

**Comment by eerussianguy** [comment]
Why would you eat olive paste?

**Comment by nuuno2000** [comment]
i wouldnt, but i still think it should rot if you dont make olive oil from it, atm you can just keep it forever

**Comment by Gaelmare** [comment]
It's called tapenade. I hadn't considered olive paste a food, so it doesn't spoil.

**Comment by alcatrazEscapee** [comment]
Many things made with food products don't spoil (speaking of TFC). I see no particular reason why this should as has been said, it's not a food.
