### ISSUE TITLE
Fruit trees fruit too many times per month

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1360]
Ive managed to get 4 harvests out of my olive trees in the single month they fruit, which i think is a bit excessive. In my opinions they should only fruit once or maybe twice assuming not all frui was harvested the first time as some wasnt ripe yet.

**Meta Info**
 - TFC Version: 0.X.X.146 (at time of request)

**Comment by DisasterMoo** [comment]
Then, use the config.

**Comment by nuuno2000** [comment]
I prefer to play on servers and im currently playing on the test server, so i have no control over the configs, and (this applies to all my suggestions in which you answered with "use the config" or similar) i think the default configs should be the most correct one, thus my suggestion was to change the default config.

**Comment by DisasterMoo** [comment]
> default configs should be the most correct one

You know that this is your opinion, right? "Correct one" here is actually your preference (which isn't the same as the rest of the community), and if you can't change how a server work, why should we (the dev team) have that power?

Now default configs are debatable, and until we can hear more people wanting it to change, won't.

**Comment by nuuno2000** [comment]
Yes, it is my preference, as i prefer things to be more realistic, i think we can agree that being able to harvest a fruit tree 4 times per month is not realistic at all, but i do understand that its up to what most people want sometimes, not whats more realistic
