### ISSUE TITLE
Wild crops should despawn/die after one year

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1361]
In places where the temperature never drops below 0ºC wild crops can become way tooa bundant if not harvested as they dont die.

**Meta Info**
 - TFC Version: 0.X.X.146 (at time of request)

**Comment by alcatrazEscapee** [comment]
> In places where the temperature never drops below 0ºC wild crops can become way too abundant if not harvested as they don't die.

This is ridiculous. How can they "become" too abundant. Either they *are* to abundant, everywhere, or they aren't.

**Comment by nuuno2000** [comment]
the difference is in colder places they die off in the winter so they dont add up year after year, but in hotter places where the temp doesnt drop below 0ºC they keep adding up

**Comment by alcatrazEscapee** [comment]
> but in hotter places where the temp doesn't drop below 0ºC they keep adding up

yes, in 1.7.10. Not so in 1.12, so the point is moot.
