### ISSUE TITLE
Addition of camels milk

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1362]
Camels milk has historicaly been consumed and in game it would be another source for milk when cows/goats arent available, while also being the only "mobile"  milk source(because you can ride them), which is very helpful since drinking milk after a meal now increases dairy.

**Meta Info**
 - TFC Version: 0.X.X.146 (at time of request)

**Comment by DisasterMoo** [comment]
Suggestions should be discussed in discord first. This one is denied, camels already do enough things, we don't want to make an OP animal that can be do everything.
