### ISSUE TITLE
Brine shouldnt require vinegar to be made

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1365]
Brine is just really salty water, so it should be made by adding salt to salt water or by boiling down salt water in a pot.
Would also be nice (im not sure if possible though) to have the hability to make salt water from fresh water by adding salt. So adding a set amount of salt to fresh water would make it salty, but if that ammount was too great it would make it into brine.

**Meta Info**
 - TFC Version: 0.X.X.146 (at time of request)

**Comment by DisasterMoo** [comment]
Suggestions should be discussed in discord first. We already denied this because rock salt would be obsolete if salt was easy to come by.

**Comment by nuuno2000** [comment]
I didnt mean to say boil it down to get salt, i meant boil it down to get brine, as imo brine shouldnt be in game what it is irl, really salty water, and dhouldnt require vinegar
