### ISSUE TITLE
The liquid metal inside the mold disappear because of click action.

### ISSUE THREAD

**Issue by BeakBlue** [TerraFirmaCraft/TerraFirmaCraft#1372]
**Describe the bug**

1. This bug only happened in the server that installs the TFC, It's normal in the local environment.
2. After you put the liquid metal into the mold to make things, you can not use the mouse click to move the mold. If you do, the metal inside the mold will disappear and you will totally lose it.
3. It destroys the game because you can't make anything.

**To Reproduce**
 
1. Install the TFC to the server.
2. Connect to the server play the game.
3. Put the liquid metal into the mold.
4. Use the mouse clicks the mold to move or use.
5. The liquid metal inside the mold will disappear because of the click action.

**Meta Info**
 - TFC Version: TerraFirmaCraft-MC1.12.2-1.3.0.145
 - only have TFC loaded

**Comment by BeakBlue** [comment]
First I click the mold to move it into my inventory and close the GUI
![1](https://user-images.githubusercontent.com/56828189/83327898-02054680-a2b2-11ea-9ce2-5705759c013c.png)
![2](https://user-images.githubusercontent.com/56828189/83327911-1ba68e00-a2b2-11ea-9abb-683d1335502b.png)
Then I open my inventory again and the metal in the mold disappear immediately
![3](https://user-images.githubusercontent.com/56828189/83327977-8061e880-a2b2-11ea-86f1-9c9e5dce3cc2.png)
![4](https://user-images.githubusercontent.com/56828189/83327980-83f56f80-a2b2-11ea-9b3d-1472fd1e8119.png)

**Comment by BeakBlue** [comment]
Use the creative mode just to demonstrate the bug, it's same in the survival mode

**Comment by Gaelmare** [comment]
This is a visual bug. The contents of the mold are still there.

**Comment by BeakBlue** [comment]
> This is a visual bug. The contents of the mold are still there.

No, it's not. 
![11](https://user-images.githubusercontent.com/56828189/83343554-89909b00-a32e-11ea-99e5-0ad53897df0b.png)
The next time you open the inventory and check it. It will be an “empty mold” again. Without anything in it and can be refilled.
![12](https://user-images.githubusercontent.com/56828189/83343597-16d3ef80-a32f-11ea-8f24-9bc52ea29a10.png)
![13](https://user-images.githubusercontent.com/56828189/83343601-1c313a00-a32f-11ea-8da3-c64d0e02b725.png)

**Comment by DisasterMoo** [comment]
Does this bug only occur on creative? ie: the item is "emptied" on creative, and of course it is carried to survival if you switch to it? If so, related to #1098.

**Comment by BeakBlue** [comment]
> Does this bug only occur on creative? ie: the item is "emptied" on creative, and of course it is carried to survival if you switch to it? If so, related to #1098.

No, I use the creative mode just to demonstrate the bug. It occurs in the survival. It's normal in a single play, but if I install the TFC to a server and invite my friend to play, the bug will occur.  And the mold can be moved by keyboard in normal but if you move it by clicking on it, the mold will become an "empty mold" just like be replaced

**Comment by BeakBlue** [comment]
> Does this bug only occur on creative? ie: the item is "emptied" on creative, and of course it is carried to survival if you switch to it? If so, related to #1098.

I have recorded the bug test video and upload it
[https://drive.google.com/drive/folders/1HfDUe0VcX7_S6Yr__94qYr-a7v4d9Ff2?usp=sharing](url)

**Comment by BeakBlue** [comment]
> This is a visual bug. The contents of the mold are still there.

I have tested the bug in survival and recorded it. You can check it.
https://drive.google.com/drive/folders/1HfDUe0VcX7_S6Yr__94qYr-a7v4d9Ff2?usp=sharing

**Comment by alcatrazEscapee** [comment]
This issue does not apply, or has been fixed in the current MC 1.18 versions of TFC, and as MC 1.12 is receiving no more development, it will be closed. If this issue arises again in 1.18, please file a new issue report.
