### ISSUE TITLE
Korean translation file. 1.12.2-1.3.2.147

### ISSUE THREAD

**Issue by FlowerBlue0114** [TerraFirmaCraft/TerraFirmaCraft#1373]
**Describe the request**
Make sure to include:
1. What problem or issue would this enhancement solve?
Korean added.

2. Describe the feature itself - what would change, what would happen. In general more detail is good!
You can play this game in Korean.
However, since this is the first translation, it can be awkward.

**Meta Info**
 - TFC Version: 1.12.2-1.3.2.147 (at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
   Probably only translated by TFC.
 - If necessary, what other mods (including versions) would this require?
   No.

[ko_kr.zip](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/4706072/ko_kr.zip)

**Comment by alcatrazEscapee** [comment]
This is not a pull request, luckily there was somebody nicer than me who actually went about adding said translation. See #1375.
