### ISSUE TITLE
Unable to move olive oil water with buckets

### ISSUE THREAD

**Issue by boltonlass** [TerraFirmaCraft/TerraFirmaCraft#1374]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
To be able to use a bucket to remove some olive oil water from a barrel to enable me to strain small amounts with jute nets in another barrel.
2. What actually happened instead (i.e. what was the bug)
Buckets will not fill with the liquid either when right clicking the barrel or when put in the internal barrel slots.

**Meta Info**
 - TFC Version:  TerraFirmaCraft-MC1.12.2-1.3.2.147

**Comment by nuuno2000** [comment]
It seems to be working properly, the barrel needs to have at least 1000mL to fill a bucket

**Comment by Gaelmare** [comment]
This is an issue with olive oil water. Reproduced.
