### ISSUE TITLE
Ability to right click barrel fluids into other barrels.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#1377]
Right clicking a sealed barrel in your hand onto another barrel should move it's fluid contents.
This is especially useful when a fluid is in a barrel you'd rather not waste, but can't even use.
Eg: Barrel with 100mb limewater in it, no recipe can use so little, no container can move so little.

**Comment by alcatrazEscapee** [comment]
Duplicate of #493
