### ISSUE TITLE
Adding straw to pit kilns in creative mode consumes the straw

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#138]
Found while testing the previous issue. Inconsistent with other placements such as charcoal.

![2019-06-29_17 42 38](https://user-images.githubusercontent.com/52297970/60387031-78dc0300-9a95-11e9-9e8c-351d5a3120b5.png)
![2019-06-29_17 42 27](https://user-images.githubusercontent.com/52297970/60387032-79749980-9a95-11e9-8641-e7378bb41f9d.png)

**Comment by alcatrazEscapee** [comment]
This is consistent with how other inventory blocks function
