### ISSUE TITLE
Animals dying of suffocation

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1382]
When animals are close to full blocks (when in a pit for example) and the chunks are loaded there is a chance those animals will end up inside the block and will suffocate and die. I assume this is the same issue that causes animals to go through fences, as they arent solid blocks so they dont die and eventually just go through. Im not sure how to keep animals as they escape through fences and die if in a pit...
(Ive olnly seen the suffocation happen with baby animals, not sure if it happens with other animals too)
**Meta Info**
 - TFC Version: 0.X.X.146
 - Were any other mods included? Can you reproduce it without these other mods?
 - If necessary, what other mods (including versions) MUST be present to experience the bug?

**Comment by DisasterMoo** [comment]
Nothing i can do, related to #1229 and vanilla bug https://bugs.mojang.com/browse/MC-2025
