### ISSUE TITLE
Rename Animal Spawn Count -> Animal Respawn Count

### ISSUE THREAD

**Issue by ghost** [TerraFirmaCraft/TerraFirmaCraft#1384]
Animal Spawn Count option in config doesnt work because if i set count to 0 animals will still spawn.

![javaw_pgfkGlOKSN](https://user-images.githubusercontent.com/64742329/83635319-604e6400-a5e7-11ea-84ff-cc16dfe04155.png)
![javaw_3PEe9UWYcI](https://user-images.githubusercontent.com/64742329/83635323-617f9100-a5e7-11ea-8ea3-e8f0a2967829.png)

I use TFC version 1.3.3.148

**Comment by DisasterMoo** [comment]
That is only for respawn. Sorry, I should've described better.

There is 2 kinds of spawning in MC:
- On chunk generation.
- Respawns (occurs on loaded chunks). 

So there is two configs to control this behavior. Default is: Livestock animals (like sheeps, which you are showing) only spawns on chunk generation (wolves and cats are special cased), any others respawns over time using that config.

If you want to disable sheeps specifically, or other animals on chunk generation, you have to go over Animals config and disable each one.
