### ISSUE TITLE
Starting to work clay shows gear equipped in subtitles

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#139]
Since no gear is actually being equipped here I'm inclined to believe that this subtitle is incorrect.

This may be a vanilla bug, as I've seen it appearing in odd cases in vanilla as well.

![2019-06-29_17 48 59](https://user-images.githubusercontent.com/52297970/60387101-804fdc00-9a96-11e9-9322-327d7e1cced3.png)

**Comment by alcatrazEscapee** [comment]
That subtitle is also the sound of switching items in your hotbar - i.e. scrolling or pressing the number keys will make this sound. It is not exclusive to equipping armor, neither in vanilla or TFC
