### ISSUE TITLE
Add config or crafttweaker support to disable metal products' melting into fluid

### ISSUE THREAD

**Issue by a757403** [TerraFirmaCraft/TerraFirmaCraft#1391]
All metallic items can be melted down and turn into fluid.These melting recipes can't be removed or altered by config or CT scripts,making it impossible to disable a specific melting recipe.

**Comment by DisasterMoo** [comment]
That's already possible, you need to remove heating recipes by the recipe name. Each metal melting recipe is registered by `[metal_name]_melting` ie: `bronze_melting`.

But take in mind this will disable ALL melting recipes from said metal like ores, and also, your metal items will not be destroyed if heated above their melting point (which will make the tooltip ` - Liquid` without it being liquid)
