### ISSUE TITLE
Pigmen drop vanilla swords

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1395]
**Meta Info**
 - TFC Version: 0.X.X.146
 - Were any other mods included? Can you reproduce it without these other mods?
 - If necessary, what other mods (including versions) MUST be present to experience the bug?

**Comment by DisasterMoo** [comment]
No issues here, they spawn outside the scope of TFC (nether).

**Comment by nuuno2000** [comment]
I see, but maybe make it so the gold swords can be melted down, so at least they have a use.
