### ISSUE TITLE
More unintetional uses for rotten food

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1397]
- Rotten olives can be made into olive paste
- Rotten sugar cane can be turned into paper
- Sugar can be made from rotten sugar cane
**Meta Info**
 - TFC Version: 0.X.X.146
 - Were any other mods included? Can you reproduce it without these other mods?
 - If necessary, what other mods (including versions) MUST be present to experience the bug?

**Comment by DisasterMoo** [comment]
I have a concern before any fix: Can sugar rot?

The others can be fixed no problem.

**Comment by nuuno2000** [comment]
I dont think sugar can rot, not in most circumstances at least, but none of the points i made were about sugar, but sugar cane.

**Comment by DisasterMoo** [comment]
Oh well, silly me, *eyes are poor need stronger glasses*.

Edit: Imo, making paper is fine from rotten sugar cane. My reasons: 
1 - From the gameplay standpoint, it gives a use for this rotten food at least.
2 - It is made from the fibers, which i think are not the rotten parts.
