### ISSUE TITLE
Mules have identical stats for Jump and Speed in HWYLA

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#1400]
Breeding several mules on the test server and they have identical numbers for Jump and Speed, see image.

![Inked2020-06-07_00 46 29_LI](https://user-images.githubusercontent.com/58256171/83956782-9bf06480-a859-11ea-9b14-b0cabe315cbd.jpg)

Possibly related to #1142 ?

**Meta Info**
 - TFC Version: 0.X.X.149 on test server

**Comment by p0kes** [comment]
This looks wrong (to a non-coder)

Line 343 of EntityHorseTFC.java:

        this.geneSpeed = nbt.getFloat("geneSpeed");
        this.geneJump = nbt.getFloat("geneSpeed");
        this.geneHealth = nbt.getFloat("geneSpeed");

**Comment by p0kes** [comment]
Also fits with #1381

**Comment by DisasterMoo** [comment]
Copy-pasta-forgot-to-change-to-correct-values bug, thanks for finding that

**Comment by DisasterMoo** [comment]
Moved to #1381
