### ISSUE TITLE
Charcoal from sticks

### ISSUE THREAD

**Issue by DerSchleimpilz** [TerraFirmaCraft/TerraFirmaCraft#1403]
1. What problem or issue would this enhancement solve?
ridiculous amounts of sticks pile up in a wood farm. Those can only be left to despawn at some point, since torches and ladders are not in as high demand as charcoal and wood for building. 
2. Describe the feature itself - what would change, what would happen. In general more detail is good!
I suggest sticks can be placed in log piles - 16 or 64 per slot. Those log piles can be turned into charcoal just like any other log pile depending how full they are.

**Meta Info**
 - TFC Version: 1.4.0.149 (at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
no
 - If necessary, what other mods (including versions) would this require?
none

**Comment by nuuno2000** [comment]
Would also make sense if bunches of stick could be used as fuel in firepits

**Comment by Azaysol** [comment]
i had asked for them to be added as a fuel source, guess it didnt make it in. but would support that. not sure about sticks into coal, although technically something that is done, think it would break some game balance

**Comment by DerSchleimpilz** [comment]
I do not believe it would unbalance the game at all, since the amount of sticks that would be required for a few pieces of charcoal should be very high, in the region of 64 sticks to 4-8 charcoal. This would mean that for purpose of charcoal, every tree gives you roughly half a logs worth of extra charcoal. This would not be a great source of charcoal, but give us something to do with chests upon chests of sticks. I also like the idea of using them as fuel where currently logs are used, but i doubt you can burn as many sticks as you get from farming trees.
