### ISSUE TITLE
Some plants in flower pots do not render properly

### ISSUE THREAD

**Issue by GustavoLongatto** [TerraFirmaCraft/TerraFirmaCraft#1405]
Plants such like morning glory, water lily, moss, reindeer lichen, tree fern and barrel cactus do not render properly when placed into flower pots.

![2020-06-10_00 53 24](https://user-images.githubusercontent.com/19748061/84225966-e6bae800-aab6-11ea-8fb5-525f25b5f8f7.png)

**Comment by eerussianguy** [comment]
I don't really see how you'd get spreading plants to render in flower pots in a meaningful way

**Comment by GustavoLongatto** [comment]
Sorry, i just realized that this is a quark feature
