### ISSUE TITLE
Spawn a new animal when an unfamiliarized one dies of old age (reincarnation)

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#1408]
When an old unfamiliarized animal dies a new young animal should spawn in its place.

Helps to avoid:
- only old animals around the spawn area on servers because old-age-dying is turned off.
- depletion of wild animals on an older server because dying is turned on.

Perhaps old age dying and this 'reincarnation' could then both be turned on by default.

**Comment by alcatrazEscapee** [comment]
See #1310.
