### ISSUE TITLE
Bear / Polar bear issues

### ISSUE THREAD

**Issue by boltonlass** [TerraFirmaCraft/TerraFirmaCraft#1409]
**Describe the bug**
Since updating to the latest versions (after the world gen fixes) I have noticed there are no bears in the temperate regions including around spawn.  This leaves a gap in the predator tree as in certain areas there are just leopards and sabre tooth tigers, both night hunters.  I had to go to about -15000 in one world to find a bear and then they are found living alongside polar bears.

Also an issue is that killing a polar bear does not give the "bear in mind" achievement.

**Meta Info**
 - TFC Version: 149

**Comment by eerussianguy** [comment]
@Abdyman something to consider in your animal update

**Comment by Azaysol** [comment]
the bear in mind thing is a bug. the other thing sounds like its intended. animal spawn conditions have not been changed, and most of the predators added so far are night hunters, we are also trying to avoid having night and day hunters in the same locations as to avoid it always being dangerous to go out.
