### ISSUE TITLE
Add an option to rename items / name tags

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#1412]
Self explanatory, emulate the Vanilla renaming system on a TFC anvil.

**Comment by alcatrazEscapee** [comment]
I'm going to say no for a couple reasons:
 - The TFC anvil GUI is already complex enough, and this would be adding a whole new separate mechanic to it.
 - There's no *a priori* reason why using a name tag should require an anvil (except for the fact it does in vanilla).

However, this still leaves the problem of what to do with name tags (and to a lesser extent, naming items). So I propose several possible solutions:
 - Add a recipe for the vanilla anvil, but rename it to "deadweight" (the BWM solution)
 - Add a "scribing table" which's *only* purpose is renaming name tags and/or naming items (potentially with the XP cost removed?)
 - Add a GUI directly to name tags (I think classic did something of this sort). Possibly make name tags apply-able directly to items as well.

**Comment by DisasterMoo** [comment]
I like the scribing table idea, maybe using ink instead of XP?

**Comment by UnlimatedStone9** [comment]
Scribing table sounds wonderful actually, although using ink to rename your wrought iron pickaxe is weird.
I really dislike the idea of bolting a GUI onto name tags too, even without needing to add a new item, and the way Classic went about it didn't look good either.

**Comment by eerussianguy** [comment]
I like a scribing table as well, though a GUI would be welcome as well. Wouldn't recommend using XP, I think dye (to get colored text?) is fine

**Comment by Azaysol** [comment]
Scribing table with ink sounds great especially if dyes can be used, not sure how it would be shown in game though. just give a text above their heads, maybe color that? could also use a chisel instead if prefered for "engraving" the name into the nameplate

**Comment by alcatrazEscapee** [comment]
As of #1964, the scribing table was added, which comes with this functionality.
