### ISSUE TITLE
Forges can be de-ventilated after creation and then relit indefinitely

### ISSUE THREAD

**Issue by JuhaJGamer** [TerraFirmaCraft/TerraFirmaCraft#1413]
**Describe the bug**
A forge lit under skylight or otherwise proper ventilation can have its ventilation channel blocked and be re-lit without it infinitely often. This makes no sense, and removes all point from the ventilation system in the first place. This works *sometimes*, as my current main forge has the bug and still works, but trying to reproduce the issue results in it randomly working correctly.

**To Reproduce**
1. Construct a forge that is ventilated, and light it for the first time
2. Remove the ventilation channel to the forge or block its view of the sky
3. Re-light the forge

**Meta Info**
 - TFC Version: 1.4.0.149
 - No other mods

**Comment by JuhaJGamer** [comment]
Okay, now there is more fuckery afoot. Creating a forge without ventilation is impossible sometimes, but not always, and reloading the save seems to make every block think it is ventilated sometimes? Inconsistent behaviour at the very least, but far outside what I initially thought was the problem. For the longest time I couldnt create an unventialted forge, then I suddenly could, and now I once again cannot.

**Comment by alcatrazEscapee** [comment]
As I cannot reproduce this, I'm tempted to believe that there's a case of misunderstanding what the conditions for a forge being able to light are:
 - The block directly above the forge must be air or a crucible
 - A block that is up to 2 blocks away, in any cardinal direction, must be able to see sky
 - The blocks on the other five sides of the forge must be solid stone blocks

Given then, this forge is un-light-able:
![2020-06-16_17 20 59](https://user-images.githubusercontent.com/35673674/84829471-d6929380-aff5-11ea-9575-c21e00e14c16.png)

But this one can be:
![2020-06-16_17 21 10](https://user-images.githubusercontent.com/35673674/84829496-e0b49200-aff5-11ea-99d1-5236f921d27f.png)

I haven't been able to reproduce any cases of a forge being improperly constructed and yet still light-able. A screenshot or explanation of the exact construction would be helpful.

**Comment by JuhaJGamer** [comment]
As of recent it has stopped. I did get a forge going in an empty, closed off room once, but it would not relight after relogging. Probably just a one-off bug caused by some more fundamental minecraft or forge level issue as similar problems have appeared in the main game without TFC in the past. Best to close this since I can't reproduce it either anymore, if it shows up again I guess I'll properly science the conditions before making another issue.
