### ISSUE TITLE
Skeleton horses still spawn

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1414]
Apparently people have found some even though they should be spawning after #1263 which closes #1248.

**Meta Info**
 - TFC Version: 0.X.X.149
 - Were any other mods included? Can you reproduce it without these other mods?
 - If necessary, what other mods (including versions) MUST be present to experience the bug?

**Comment by alcatrazEscapee** [comment]
@DisasterMoo skeleton horses != zombie horses :P

https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/a9344719eafe37a7556d95bd53981b2660a997ff/src/main/java/net/dries007/tfc/util/Helpers.java#L92
