### ISSUE TITLE
Powder Kegs can't be placed against other faces of blocks when no block is below them.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#1418]
Self explanatory, you can't place a powder keg against say, the roof, when there is no block below where they would have been placed, similarly to how pumpkins used to work in old game versions before being fixed.
~~Discord rant~~

**Comment by Gaelmare** [comment]
As I said in Discord, this behavior is where I landed after play testing powderkegs. They can't pop off if the block below them is removed, or they will not get triggered correctly during chained explosions, as the block below may be removed by the explosion before the powderkeg knows it should be triggered. I was uncomfortable making them placeable everywhere. They must be placed on solid blocks or on other powderkegs. Yes, this is less than perfect.
