### ISSUE TITLE
Players in Peaceful mode can get thirsty

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#142]
Since peaceful mode stops players from getting hungry, I'd assume it would be meant to stop thirst as well.

**Comment by alcatrazEscapee** [comment]
Fixed in https://github.com/alcatrazEscapee/TerraFirmaCraft/tree/damage-food-v2

**Comment by alcatrazEscapee** [comment]
Duplicate of #108
