### ISSUE TITLE
Config control on rideable animals

### ISSUE THREAD

**Issue by HeartyYF** [TerraFirmaCraft/TerraFirmaCraft#1423]
**Describe the request**
Make it configurable that which kinds of animals are rideable, and whether it needs halter to ride them.

**Meta Info**
 - TFC Version: 1.5.1
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
Maybe both?

**Comment by Azaysol** [comment]
the current ride-able animals are the only animals that even have any code for it. this would require much more then just adding a config option

**Comment by DisasterMoo** [comment]
Impossible, all these needs to be done via code, can't be delegated to config options.
