### ISSUE TITLE
Stone Knives do more damage than some metal ones

### ISSUE THREAD

**Issue by Therighthon** [TerraFirmaCraft/TerraFirmaCraft#1424]
All metal knives before steel are outclassed as weapons by stone knives. Stone knives also do more damage than a lot of other early weapons, and at a higher rate. Stone knives should have their damage reduced to 2-2.5 attack damage.

**Comment by alcatrazEscapee** [comment]
Turns out, also applies to axes, hammers, and javelins (although the latter were already fixed in #1016)
