### ISSUE TITLE
Larger Forges/Change Forge Placement requirements

### ISSUE THREAD

**Issue by Therighthon** [TerraFirmaCraft/TerraFirmaCraft#1425]
When you get into the late game, the 5 slots of the forge are usually not enough for all of the metal you are processing, so people set up multiple forges, often side by side. What if we changed the forge placement requirements so that they could be bordered not just by stone, but by other forges. Each block could still behave independently for the sake of simplicity, but it would allow people to build forges in cool shapes as they please.

**Comment by M8-u** [comment]
If you're having issues with melting metals then use a crucible.

**Comment by Claycorp** [comment]
Everything that can heat objects can do it.
Just upgrade to a crucible like M8-u said. Now you have 9 slots that heat with a built in liquid catcher.

**Comment by DisasterMoo** [comment]
A few things:
- The purpose of charcoal forge is to heat metal items into workable temperatures, so you can weld or craft tools.
- As Clay and M8-u mentioned, crucibles are the way to go if you want more ingots. You can even pair that with small vessels for 4x9 slots total.
- The same idea for small vessels also work for forges, you can use it there instead and have 4x5 slots

So, unless you're suggesting more slots / larger forges for a different reason, your desired feature already exists.
