### ISSUE TITLE
Configurable ocean size

### ISSUE THREAD

**Issue by MadAlchemist** [TerraFirmaCraft/TerraFirmaCraft#1426]
In TFC world, oceans are almost always very large. It is OK when playing in single-player, when world size is almost infinite. But on multiplayer servers with world border this is catastrophic - entire map will contain only one island and lot of ocean.
It is necessary to have option to reduce ocean size - because no world border will quickly consume all disk space in multiplayer game.

**Meta Info**
 - TFC Version: TerraFirmaCraft-MC1.12.2-1.4.0.149
 This doesn't depends on any mods, but makes multiplayer game with limited world size very problematic.

**Comment by alcatrazEscapee** [comment]
This is already planned (and basically done) as a feature in the 1.15 world generation rewrite. Unforunatley unless somebody wants to PR this themselves it's not going to make it into 1.12 as the current state of 1.12 world generation is "nobody touch this because it's getting tossed and rewritten"
