### ISSUE TITLE
Livestock animals should have a utility attribute

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#1428]
Livestock type animals should have utility attributes, which when exhausted cause the animal to become old.

e.g. can get pregnant 8 times, can be milked 30 times etc.

Once the animal becomes old it could then die a while afterwards.

The attribute could be variable and inheritable, to encourage breeding superior livestock such as happens with speed/jump for horses.

Females could have different limits to males, e.g. female cattle can get pregnant 8 times, male could have 2x that.

Distance limit for horses too? You might be able to literally run them into lameness / old age.

This helps solve the issue of 'all nearby animals are old' on a server and enhances gameplay.

**Comment by alcatrazEscapee** [comment]
This is an attempt to solve #1310 crossed with "this is discord #suggestions material"
