### ISSUE TITLE
I can't edit ore_spawn_data.json

### ISSUE THREAD

**Issue by w3ricardo** [TerraFirmaCraft/TerraFirmaCraft#1433]
ore_spawn_data.json gets rewritten every time I launch Minecraft. I changed the density of kaolinite from 70 to 71 just to test it and then launched Minecraft, When the main screen shows, before loading a save, I opened the ore_spawn_data.json and the value was back to 70.

Forge: 14.23.5.2854
TFC: 1.5.2.152
Other mods: no

**Comment by alcatrazEscapee** [comment]
In the config:
```
# If true, TFC will override default ore gen file. Pack Makers: Disable this to keep your ore gen file from being reset to default.
B:forceDefaultOreGenFile=true
```
