### ISSUE TITLE
i can not make fire with firestater and 3 stiks i dont now why

### ISSUE THREAD

**Issue by blobblub1** [TerraFirmaCraft/TerraFirmaCraft#1434]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
2. What actually happened instead (i.e. what was the bug)
3. If it was a crash, upload the full log file (`latest.log`)
4. If they would help to explain the issue, include screenshots

**To Reproduce**
Attention to detail is important!
1. Do '...'
2. Then do '...'

**Meta Info**
 - TFC Version: 0.X.X.XX
 - Were any other mods included? Can you reproduce it without these other mods?
 - If necessary, what other mods (including versions) MUST be present to experience the bug?

**Comment by alcatrazEscapee** [comment]
[Need a log as well](https://tng.terrafirmacraft.com/Differences_From_Classic)
