### ISSUE TITLE
Dyed alabaster bricks can be dyed the same color multiple times

### ISSUE THREAD

**Issue by nuuno2000** [TerraFirmaCraft/TerraFirmaCraft#1435]
Dyed alabaster bricks can be dyed the same color multiple times, which ends up using all of the dye in the barrel
I assume the same problem happens with all the items that can be dyed.

**Meta Info**
 - TFC Version: 0.X.X.152
 - Were any other mods included? Can you reproduce it without these other mods?
 - If necessary, what other mods (including versions) MUST be present to experience the bug?

**Comment by alcatrazEscapee** [comment]
A couple options here:
 - Special case the input for each dyeing recipe to exclude *only* the color that is being produced (ugh, very ugly)
 - In consistency with vanilla, restrict the input to only uncolored / white alabaster. (Possibly making sure there is an "undyeing" mechanic.
 - Special case barrels to not execute recipes if the output would be the same as the input. (Might be doable with little to no side effects, may result in unexpected behavior, especially using a conventional recipe system.

**Comment by eerussianguy** [comment]
Vanilla way is less cool but it's probably best
