### ISSUE TITLE
Crash on startup ("GameRuleChangeEvent")

### ISSUE THREAD

**Issue by flarn2006** [TerraFirmaCraft/TerraFirmaCraft#1436]
I installed the mod, but it just crashes when I start Minecraft. All the other information you need should be in the log file I attached.

[fml-client-latest.log](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/4839800/fml-client-latest.log)

**Comment by alcatrazEscapee** [comment]
Update your forge version

**Comment by flarn2006** [comment]
I just downloaded it, and it said it was the latest one for Minecraft 1.12.2. Which version should I be using?

**Comment by alcatrazEscapee** [comment]
You have 14.23.1.2590, which was released at 01/16/18 05:30 AM. Very much not the latest version. TFC needs at least 14.23.5.2816

**Comment by flarn2006** [comment]
Ah, I see what I did wrong. I did indeed download that version, but I selected the wrong one from the list in the launcher. It works now; thanks for the help. :)
