### ISSUE TITLE
Option to specify food category when registering new food

### ISSUE THREAD

**Issue by SeriousCreeper** [TerraFirmaCraft/TerraFirmaCraft#1438]
While we can add food **values** to non-tfc food, but we can not specify what food **category** it is part of. 
This is a problem when it comes to soups and such, as they specifically check for categories (for example soup checks for `Food.Category.FRUIT, Food.Category.VEGETABLE, Food.Category.COOKED_MEAT, Food.Category.MEAT`). 

This means currently any non-tfc food would not work in soups (and im guessing sandwiches/salads, but i didn't double check the code for those).

**Meta Info**
 - TFC Version: 1.5.2.152
 - Mod compatibility

**Comment by alcatrazEscapee** [comment]
Yes you can, as the category is simply an ore dictionary name of the category, prefixed by the word `category`. (`categoryFruit`, `categoryVegetable`, etc.)

**Comment by SeriousCreeper** [comment]
Ahh that's really good to know, wasn't aware of that feature, my bad!
