### ISSUE TITLE
Let decay food disapear maybe better

### ISSUE THREAD

**Issue by Woody-0w0** [TerraFirmaCraft/TerraFirmaCraft#1443]
**Describe the request**
Make sure to include:
1. Decay food will refresh as a material after craft (the tag of decay seems not compate with crafttweaker); In some case (such as plate of  Mr_Crayfish's furniture Mod), put decay food in and out will refresh it.
2. Suggest：let decay food disapear, or change it to another item(pigs or ducks can eat).

**Meta Info**
 - TFC Version:1.5.2.152
 - Both compatibility feature for other mods and enhancement for TFC.

**Comment by Woody-0w0** [comment]
A little more, the tag of traits such as brined or pickled seems not compate with crafttweaker either.

**Comment by alcatrazEscapee** [comment]
> In some case (such as plate of Mr_Crayfish's furniture Mod), put decay food in and out will refresh it.

This is a problem with the other mod not handling item capabilities correctly.

> let decay food disapear

This is not happening for a variety of reasons.
