### ISSUE TITLE
Anvils should require solid blocks below for placement

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1447]
![2020-07-04_12 55 45](https://user-images.githubusercontent.com/58122689/86519198-c3edcc00-bdf5-11ea-85b6-f91ed7142976.png)

**Meta Info**
 - TFC Version: 1.5.3

**Comment by eerussianguy** [comment]
They should probably also fall as well

**Comment by alcatrazEscapee** [comment]
y tho
