### ISSUE TITLE
Sabertooth cats not dropping gran_feline loot

### ISSUE THREAD

**Issue by Nohicom** [TerraFirmaCraft/TerraFirmaCraft#1450]
**Describe the bug**
Sabertooths do not drop any loot upon death. I tried killing both naturally-spawned and player-spawned cats, both with a player kill (using a sword) and a "natural" death (dropping gravel on them). I used LootTweaker to check, and both panthers and sabertooths are listed as using the "tfc:animals/gran_feline" loot table. In testing, panthers would always drop at least some loot from that table in all of the listed scenarios, whereas sabertooths never dropped anything at all.

**To Reproduce**
Spawn or find a sabertooth cat and kill it.

**Meta Info**
 - TFC Version:
TerraFirmaCraft-MC1.12.2-1.5.2.152
 - Were any other mods included? Can you reproduce it without these other mods?
I originally noticed the issue while building a modpack with a number of other mods, but could easily reproduce the issue using only TFC:TNG on its own. Both instances used the above listed TFC version, and the latest Forge version, 14.23.5.2854.
 - If necessary, what other mods (including versions) MUST be present to experience the bug?
N/A

**Comment by Nohicom** [comment]
Update: I tried it with the (currently) newest version of TFC, 1.5.3.153, on both the newest version of Forge (listed above) and the oldest compatible, 14.23.5.2816, with no success.

**Comment by alcatrazEscapee** [comment]
Working fine for me. I'm highly suspicious that the animals you were killing were not adults, and thus not dropping anything.

**Comment by Nohicom** [comment]
You are correct. After using WAILA to look at their age, the sabertooths were in fact not adults yet. I used an NBT editor to artificially age one because I didn't feel like waiting, and once it was an adult it dropped the gran_feline loot as normal.

So I guess this bug needs to be renamed/recategorized to be that sabertooths seem to usually/always spawn both naturally and from spawn eggs as children, whereas panthers usually/always spawn as adults. I say usually/always because from my experience when testing this bug and just playing normally this seems to always be the case, but perhaps I'm just extremely lucky (or unlucky, depending on how you look at it.)
