### ISSUE TITLE
Chickens spawning underground

### ISSUE THREAD

**Issue by alcatrazEscapee** [TerraFirmaCraft/TerraFirmaCraft#1453]
Probably due to chicken jockies spawning, being replaced with TFC variants and either having the zombie despawn or dismount during the replacement. Need to investigate if it's possible to modify this to vanilla esque mechanics (Despawning / mounting), but using our chickens, or if we need to prevent them spawning entirely.

**Comment by Azaysol** [comment]
would disabling the ability for having Jockies spawn fix this?
