### ISSUE TITLE
Shields not getting damaged from some mobs

### ISSUE THREAD

**Issue by EmErDogi** [TerraFirmaCraft/TerraFirmaCraft#1456]
Shields don't get damaged when attacked by spiders, hyenas, baby saber tooths and randomly from wolves. I've checked all available TFC shields on 1.5.3.153 and all of them acted the same. What's the weirdest thing for me is that shields were damaged by wolves only every couple hits

**Comment by alcatrazEscapee** [comment]
Sounds like vanilla mechanics. From the MC Wiki:

> When the shield blocks an attack of 4♥♥ or stronger, it takes damage equal to the strength of the attack rounded up.

Unless this isn't the case we have no intent to change this.
