### ISSUE TITLE
Bronze armors should have different durabilities

### ISSUE THREAD

**Issue by EmErDogi** [TerraFirmaCraft/TerraFirmaCraft#1457]
Bismuth bronze, bronze and black bronze tools all have durability differences and weapons made from these metals also have damage differences. This isn't the case with armors as they all have the same values for durability. Slightly lowering bismuth bronze armor's durability and increasing black bronze's would make it more consistent with tool and weapon situation and make it more worth to use more expensive alloy rather than using cheaper alternative

**Comment by alcatrazEscapee** [comment]
While this would be nice, due to the way MC's armor durability calculation works, we can't have small variants in durability without messing with a bunch of nonsense.
