### ISSUE TITLE
Ceramic pots should show their content

### ISSUE THREAD

**Issue by EmErDogi** [TerraFirmaCraft/TerraFirmaCraft#1459]
Ceramic pots placed on campfires should show their contents, so players can know without constantly opening the GUI, what's the current state of cooking, whether it's empty, needs ingredients or if soup is ready.

**Comment by alcatrazEscapee** [comment]
While, sure, there are some aesthetic improvements that could be made to the cooking pot, this is also rather inconsistent with literally every other gui we have (forge, fire pit, grill, crucible, etc.) Every single one of those requires you to open the GUI to see the details of what's going on inside, and that isn't going to change.
