### ISSUE TITLE
Fluids are goddammed broken

### ISSUE THREAD

**Issue by alcatrazEscapee** [TerraFirmaCraft/TerraFirmaCraft#146]
word.

**Comment by DavidTriphon** [comment]
Some examples of how water is broken:

Overlapping water of different fluids can lead to lingering water flows when no matching source fluid block is present.
https://youtu.be/JOxSFg-u-Rs

We want sources that are closer to be able replace other water flows.
An example case where the flows are parallel:
https://youtu.be/JOxSFg-u-Rs

**Comment by DavidTriphon** [comment]
Design notes on fluid interactions:
flowing water should not ever replace a source block

flowing waters from alternate fluids should equalize their flows against one another, similar to how fluids of the same type interact.

Discussed order on when water should replace other water:
Fluid flow strength > fluid density > first present > alphabetical name

**Comment by DavidTriphon** [comment]
Fluids should equalize like this when on the same level:

![2019-08-09_13 44 43](https://user-images.githubusercontent.com/20526831/62808108-0145be80-baac-11e9-9a15-0fa4ea1a4ba4.png)

But currently if you place one or the other first, you get this:
![2019-08-09_13 44 59](https://user-images.githubusercontent.com/20526831/62808121-0c98ea00-baac-11e9-844c-7b49bd33ebf6.png)
![Uploading 2019-08-09_13.45.09.png…]()
