### ISSUE TITLE
Unused advancement lang entries

### ISSUE THREAD

**Issue by HeartyYF** [TerraFirmaCraft/TerraFirmaCraft#1460]
**Describe the bug**
We found that some advancement entries exist but unused.

- advancements.tfc.main.stone_anvil
- advancements.tfc.world.rutabaga
- advancements.tfc.world.find_sylvite

If they're designed to use, please add corresponding advancements, otherwise delete them.

**Meta Info**
 - TFC Version: since advancement added

**Comment by eerussianguy** [comment]
Can someone add a config option to disable these entries
