### ISSUE TITLE
Compatability bug: only one tree block (from DynamicTrees) gets destroyed by gravity-affected blocks.

### ISSUE THREAD

**Issue by Lgmrszd** [TerraFirmaCraft/TerraFirmaCraft#1463]
**Describe the bug**
Dynamic Trees aren't supposed to get their particular blocks destroyed without affecting connected ones. Destruction by gravity-affected blocks violates that.

1. What did you expect to happen? Blocks shouldn't fall in place of tree. (Or destroy the whole tree, but that would break game making it possible to obtain wood without axe)
2. What actually happened instead (i.e. what was the bug): blocks destroy particular tree blocks (see screenshots)
3. No crash happened.
4. If they would help to explain the issue, include screenshots: [here](https://i.imgur.com/pJWiazr.png)

**To Reproduce**
1. Place dirt/gravel/sand/cobble block near the base of the tree.
2. Place 2-3 more blocks on top of that one.

**Meta Info**
 - TFC Version: 1.5.3.153
 - Were any other mods included? DynamicTrees (1.12.2-0.9.8) and DynamicTreesTFC (0.9.11), with bunch of other mods. Can you reproduce it without these other mods? Haven't tried, I don't think other mods directly affect this.
 - If necessary, what other mods (including versions) MUST be present to experience the bug? DynamicTrees (1.12.2-0.9.8) and DynamicTreesTFC (0.9.11) (should be possible to reproduce without DTTFC by placing DT tree on vanilla dirt first)

**Comment by eerussianguy** [comment]
Trees are not gravity-affected in TFC so they are allowed to float. I'm 90% sure this isn't something that can be fixed by changing something in TFC, since you're talking about interactions with DT blocks

**Comment by Gaelmare** [comment]
Would be nice to know what the right behavior should be here. When a block collapses against a non-full block DT trunk, what should happen? Or, should even a non-full DT block be considered support for a TFC gravity block? That would be strange too.

This probably belongs in https://github.com/Gaelmare/dynamictreestfc/issues instead of here.
https://github.com/Gaelmare/dynamictreestfc/issues/25

**Comment by alcatrazEscapee** [comment]
This issue does not apply, or has been fixed in the current MC 1.18 versions of TFC, and as MC 1.12 is receiving no more development, it will be closed. If this issue arises again in 1.18, please file a new issue report.
