### ISSUE TITLE
Suggestion: Even more wood types, plus wood stains

### ISSUE THREAD

**Issue by TenkenNoSoujiro** [TerraFirmaCraft/TerraFirmaCraft#1464]
I originally wanted to only suggest adding a variant of Cherry that produces logs and not just fruit, as Cherry is a very common wood type IRL used for flooring and furnishings, but there are a number of other interesting exotic wood types that would interesting to see added:

- [African Padauk](https://www.wood-database.com/african-padauk/) - Color varies from pinkish-orange to brownish-red. Often used for veneering, flooring, and musical instruments.
- [African Blackwood](https://www.wood-database.com/african-blackwood/) - An amazingly dark black hardwood that's much.
- [Leopardwood](https://www.wood-database.com/leopardwood/) - Brownish wood with a very unique grain pattern
- [Wenge](https://www.wood-database.com/wenge/) - A dark-brown, almost black wood whose heartwood has extremely narrow grain lines
- [Zebrawood](https://www.wood-database.com/zebrawood/) - A light brown wood with darker brown grain lines.
- [Macadamia Nut](https://www.wood-database.com/macadamia-nut/) - Reddish brown wood. Upside is that it produces macadamia nuts so it could possibly be added as a "fruit" tree instead.

Its not just the different colors of wood that would be interesting, but the different wood textures that could be used for planks (and stripped-log versions in 1.15).

In addition to the various wood types, it would be interesting if the base TFC game added support for things like Stains to "dye" wood to different shades as is done IRL. A Stain is a liquid suspension of some particulate in either a water, alcohol, or petroleum based vehicle or solvent. Usually you'd just take a pigment or dye and mix it with water or alcohol to produce the wood stain similar to how dies for Alabaster are applied in-game currently.

I would have been tempted to suggest the addition of Varnishes, Lacquers, or Shellacs; however, without shaders, Minecraft wouldn't be able to render the reflectivity.

**Meta Info**
 - TFC Version: 1.5.3 (at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone? Enhancement for TFC
 - If necessary, what other mods (including versions) would this require? None

**Comment by eerussianguy** [comment]
In general I'm a fan of adding more trees (I even have a secret spreadsheet full of all the trees I like) but one thing to consider is that adding a new tree should cover some sort of color that is not already represented. For example, we already have a blackwood.

In terms of stained wood, I've explored trying to texture things of this sort, and it was very difficult. There's not a good way to represent that in game.

Some things that are realistic to add -- nut trees as a variant of fruit trees that grow in winter, a generic 'fruitwood' that drops from fruit tree logs, and maybe a couple more tree types.

**Comment by alcatrazEscapee** [comment]
Large feature suggestions (and not small improvements of QoL changes) should be discussed in our [discord](discord.gg/pruakvy) as we get *a lot* of them and we try not to clutter the actual issues and enhancements with them here.
