### ISSUE TITLE
Suggestion: Cisterns, water towers, and copper piping

### ISSUE THREAD

**Issue by TenkenNoSoujiro** [TerraFirmaCraft/TerraFirmaCraft#1465]
Cisterns and water towers would provide an early-mid game way to store water for crop irrigation, cooking, smithing, etc. A [cistern](https://en.wikipedia.org/wiki/Cistern) is an underground reservoir used for storing rainwater, and could be possibly constructed by creating a stone basin and lining it with copper sheets. Filling a cistern often relies on a rain gutter and pipes, and drawing water from a cistern often requires the use of a pump.

A [water tower](https://en.wikipedia.org/wiki/Water_tower) could be considered functionally similar to a cistern as a place to collect rainwater, but it uses the effect of gravity to create water pressure to push water through pipes.

Additional craftable items would include:
- [Wooden](https://en.wikipedia.org/wiki/Piping#Wooden_piping_history), [copper](https://en.wikipedia.org/wiki/Copper_pipe), [cast iron](https://en.wikipedia.org/wiki/Cast_iron_pipe), [galvanized steel](https://en.wikipedia.org/wiki/Galvanized_steel) and even lead pipes were used throughout history to move water (though I'd probably avoid lead pipes due to lead poisoning...)
- [Hand Pumps](https://en.wikipedia.org/wiki/Hand_pump) made from cast iron
- Faucets could be made from copper, brass, bronze, or cast iron

**Meta Info**
 - TFC Version: 1.5.3 (at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone? TFC
 - If necessary, what other mods (including versions) would this require? None

**Comment by Claycorp** [comment]
This would be a new mechanic and should have been discussed on the discord.

If you have copper sheets you have a saw. You can fill a whole barrel from a single source block of water. All of this doesn't really add anything new or useful to the game in the current state. This would be something for an addon not core TFC.
