### ISSUE TITLE
Food Heat Bug 1.7.10

### ISSUE THREAD

**Issue by HellFireBro** [TerraFirmaCraft/TerraFirmaCraft#147]
When your food cooked and still too hot to eat and also have at least 0.1% decay level you can use knife to remove decay level as well as reset heat level to 0 so you can instantly start consume cooked food without waiting

**Comment by Bunsan** [comment]
1.7.10 is no longer being maintained. FYI there is no too hot to eat it just does an odd animation; keep holding and it will be consumed. Even putting food alone in crafting grub will set heat to 0.
