### ISSUE TITLE
BiblioCraft compatability food decay bug.

### ISSUE THREAD

**Issue by ghost** [TerraFirmaCraft/TerraFirmaCraft#1478]
How to reproduce this bug:

1) Put any food in any BiblioCraft container.
2) Use command /timetfc add days/months/years to skip time.
3) Open containers and you will see that food successfully rotted.
4) Break the containers with food inside or pick up food and you will see that droped meals resets to initial state without any decay (this works both in creative and survival).

Here is video presentation:

https://dl.dropboxusercontent.com/s/uq4w4n37vtk3js3/jXtAR3ss5I.mp4

 - TFC Version: MC1.12.2-1.5.4.154

**Comment by alcatrazEscapee** [comment]
Let's see shall we...
✔️ Closed source mod interaction
✔️ Other mod not updated in over a year
✔️ Evidently dropping items / storing inventory in a non-standard way (or this would've worked)
✔️ Doing something screwy with food decay, completely our of our control

Oh look, the four horsemen of "nothing we can do about this one I'm afraid."
