### ISSUE TITLE
giveVanillaMobsEquipment works not how it should.

### ISSUE THREAD

**Issue by ghost** [TerraFirmaCraft/TerraFirmaCraft#1479]
Config clearly says 
![notepad++_8qjSqK2QfS](https://user-images.githubusercontent.com/64742329/87936682-9895fd00-cad6-11ea-96f9-59d628b3086f.png)

I set false on server-side but players and me with default config on client-side can see that mobs still have armor.

I tried to set false on client-side and yes, there is no armor or weapons now but HWYLA says that they have it even if i cant see equipment.

So looks like config change only visual appearance not the physical. It is intended or bug?

Version: TerraFirmaCraft MC1.12.2-1.5.4.154

**Comment by alcatrazEscapee** [comment]
It's your responsibility to ensure that players have the correct / same config settings. We are not going to the effort to synchronize our config in 1.12. If this isn't still an issue when *both* have the same config setting, well, there's your problem.

**Comment by ghost** [comment]
Not an issue for me now.
