### ISSUE TITLE
Rotten food doesn't behave properly

### ISSUE THREAD

**Issue by Grigoriewich** [TerraFirmaCraft/TerraFirmaCraft#1481]
**Describe the bug**
Make sure to include:
Rotten food sometimes takes on a shelf life, which is misleading.
Sometimes I mix food, eat it and get poisoned.
This does not always happen. When I lift her off the ground. When I put it in a chest or vessel.
I could not find a specific process to reproduce. Happens by chance.
Video. Pay attention to the expiration dates of the products. They are all really rotten.
https://youtu.be/QDM1DVgXQ6c

**Meta Info**
 - TFC Version: 1.5.4.154
 - Yes. Other modifications are present, but I first encountered this on the official test server with no other modifications.

**Comment by DisasterMoo** [comment]
Looks like desync to me.

**Comment by alcatrazEscapee** [comment]
This issue does not apply, or has been fixed in the current MC 1.18 versions of TFC, and as MC 1.12 is receiving no more development, it will be closed. If this issue arises again in 1.18, please file a new issue report.
