### ISSUE TITLE
Config option to make only cobble collapsed from stone fallable

### ISSUE THREAD

**Issue by Lumintorious** [TerraFirmaCraft/TerraFirmaCraft#1483]
1. What problem or issue would this enhancement solve?
Wanting to have challenging mining with support beams but without affecting player placed cobble so that you can build with it
without sneakily hiding support beams underground or behind double walls or using stairs as walls to cheat the system.
2. Describe the feature itself - what would change, what would happen. In general more detail is good!
It would work like the latest change to smooth stones ( player placed ones cannot collapse but chiselled ones do collapse), but would be configurable.

**Comment by eerussianguy** [comment]
You are naturally limited in your building materials in TFC by gravity. You can either live in a straw house or invest in some stronger materials like bricks or wood

**Comment by alcatrazEscapee** [comment]
This is indirectly accomplishable in the indev 1.18 branch using both tag and landslide recipe modifications. As yet, they would need to be different blocks to be distinct at all, which is a solvable problem. In any case, we don't provide an explicit config for the behavior as listed.
