### ISSUE TITLE
neighborChanged on raw stone blocks broken, makes breaking blocks pop as if in the silk touch effect

### ISSUE THREAD

**Issue by DisasterMoo** [TerraFirmaCraft/TerraFirmaCraft#149]
And i must say, as a developer that this is VERY funny. Why? well this:

    if (worldIn.getBlockState(pos.up()).getMaterial().isReplaceable()
        && worldIn.getBlockState(pos.down()).getMaterial().isReplaceable()
        && worldIn.getBlockState(pos.north()).getMaterial().isReplaceable()
        && worldIn.getBlockState(pos.south()).getMaterial().isReplaceable()
        && worldIn.getBlockState(pos.east()).getMaterial().isReplaceable()
        && worldIn.getBlockState(pos.west()).getMaterial().isReplaceable())
    {
        //Silk touch effect
        worldIn.setBlockToAir(pos);
        Helpers.spawnItemStack(worldIn, pos, new ItemStack(state.getBlock(), 1));
    }

works, but this:

    public void neighborChanged(IBlockState state, World worldIn, BlockPos pos, Block blockIn, BlockPos fromPos)
    {
        for (EnumFacing face : EnumFacing.values())
        {
            if (!worldIn.getBlockState(pos.offset(face)).getBlock().isReplaceable(worldIn, pos))
            {
                break;
            }
            // No supporting solid blocks, so pop off as an item
            worldIn.setBlockToAir(pos);
            Helpers.spawnItemStack(worldIn, pos, new ItemStack(state.getBlock(), 1));
        }
        super.neighborChanged(state, worldIn, pos, blockIn, fromPos);
    }

don't!

**Comment by Red3Tango** [comment]
Question, would this also effect other blocks such as grass? Ran across this and not sure if it is related or a new bug...

Break the "Shale Gravel" and when the "Granite Grass" block and "Claystone Gravel" block fall into the same space, the second (grass) pops out like using Silk Touch.

![before](https://user-images.githubusercontent.com/13739585/60670924-16855880-9e2f-11e9-9c34-bc947f02ad59.png)
![after](https://user-images.githubusercontent.com/13739585/60670927-18e7b280-9e2f-11e9-80e5-644563ae7386.png)
