### ISSUE TITLE
Config option to make player nutrition not reset after death.

### ISSUE THREAD

**Issue by ghost** [TerraFirmaCraft/TerraFirmaCraft#1495]
The first issue was written poorly and little bit ignored so that i closed it and rewrited it. Sorry for duplicate.

The enhancement is exactly what title says. 

For me nutrition reset after death a real problem. With a reset i dont see any reason why i need to up or support my nutrition because it is not worth time if you die. Especially on servers where, besides of animals and mobs on the surface (if config option is turned on), players can kill you easily.

This is maybe unrealistic but why then skills dont reset after death?

And this is why i think the config option to disable/enable reset will be good idea.

**Comment by alcatrazEscapee** [comment]
f5c87a439bf7cda3e47b095ef34d8f9393d18e57
