### ISSUE TITLE
Certain food recipe shows turning into other foods

### ISSUE THREAD

**Issue by HeartyYF** [TerraFirmaCraft/TerraFirmaCraft#1503]
**Describe the bug**
![20200729104637](https://user-images.githubusercontent.com/17660052/88750832-eff83500-d188-11ea-8cb4-e428687f2444.png)
When viewing one certain food, it shows that it can turn into other foods. I think it's because they're concluded into one category to show when viewing liquid or barrel recipes, but when it comes to viewing one certain food, it doesn't fix the product, only the ingredient.

**To Reproduce**
1. Check one certain food recipe, for example, green apple.

**Meta Info**
 - TFC Version: 1.6.0

**Comment by alcatrazEscapee** [comment]
This issue does not apply, or has been fixed in the current MC 1.18 versions of TFC, and as MC 1.12 is receiving no more development, it will be closed. If this issue arises again in 1.18, please file a new issue report.
