### ISSUE TITLE
An unexpected quit happend when breaking stairs in creative mode.

### ISSUE THREAD

**Issue by kwk1001** [TerraFirmaCraft/TerraFirmaCraft#1504]
**Describe the bug**
An unexpected quit will happen if you follow the following steps:
1.Hold a hammer in your offhand and a chisel in your mainhand.
2.Change a complete block into a stair block.
3.Don't change anything in your hand and break the stair block with the chisel. 
4.The game may quit immediately.

*The stair block I tested was smooth shale stair.
*The bug will also happen in survival mode.
*I broke the stair with a pickaxe and the bug happend again.

I am not sure under what condition will the bug happen.Maybe it can happen when breaking other blocks.

**Meta Info**
 - TFC Version:1.6.0.156
 - Mod Patchouli-1.0-20 and jei_1.12.2-4.15.0.293 are included.

**Comment by alcatrazEscapee** [comment]
Need the crash log

**Comment by kwk1001** [comment]
[minecraft-exported-logs-2020-07-29T21-16-42.log](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/4995056/minecraft-exported-logs-2020-07-29T21-16-42.log)
The crash log is here.
