### ISSUE TITLE
GregTech Community Edition's Saltwater overrides TFC's

### ISSUE THREAD

**Issue by mechobree** [TerraFirmaCraft/TerraFirmaCraft#1508]
**Describe the bug**

When playing with both tfc and gtce, tfc's saltwater is forcibly replaced by gtce's and the colours do not match at all. It was not possible to change the texture of gtce's salt water and call it a day as it doesn't even have a texture. What's also weird to note, is that it no longer shows tfc's salt water in jei and theoneprobe displays gtce's saltwater as tfc's salt water, and you are still able to drink from it. Functionally it's almost the exact same.

If I should also put this issue in gtce's issue page, please let me know.

**To Reproduce**
Install both TerraFirmaCraft and GregTech Community Edition

**Meta Info**
 - TFC Version: 0.5.5.155
 - Were any other mods included? Can you reproduce it without these other mods?
GregTech Community Edition was included, no it cannot reproduced without it.
 - If necessary, what other mods (including versions) MUST be present to experience the bug?
GregTech Community Edition 1.9.2.515 (though I think any version will have the same issue)

**Comment by alcatrazEscapee** [comment]
So what I'm seeing is the mod-compatible part of the forge fluid registry is working as intended. This is a direct consequence of both fluids being the same thing. Fluids should *not* be namespaced (I have been informed by Lex directly on this topic). This allows the exact behavior where the fluids are now the same, can be used in the same recipes, etc.

Nothing we will be changing here.
