### ISSUE TITLE
Fire spreading towards some plants positioned incorrectly

### ISSUE THREAD

**Issue by HeartyYF** [TerraFirmaCraft/TerraFirmaCraft#1509]
**Describe the bug**
![2020-07-30_15 02 19](https://user-images.githubusercontent.com/17660052/88891449-d254c980-d275-11ea-8f00-d550bc71bf63.png)

For example, when it spread to reindeer lichen or scutch grass, sometimes the fire floats.

**To Reproduce**
Light a fire beside some plants.

**Meta Info**
 - TFC Version: 1.6.1

**Comment by eerussianguy** [comment]
This is vanilla behavior. See vanilla tall grass doing the same thing

**Comment by HeartyYF** [comment]
Vanilla tall grass has a height of 2 blocks, but these TFC grass has only 1 block of height

**Comment by eerussianguy** [comment]
![here you go](https://user-images.githubusercontent.com/59940116/89059860-f7a60e00-d32f-11ea-8bce-4290291aa178.png)

**Comment by HeartyYF** [comment]
OK
