### ISSUE TITLE
Collapsible blocks falling into same spot

### ISSUE THREAD

**Issue by Red3Tango** [TerraFirmaCraft/TerraFirmaCraft#151]
**[0.9.1.46]**
When two falling blocks fall into the same spot, the second one will "pop out" as an item.

Break the "Shale Gravel" and when the "Granite Grass" block and "Claystone Gravel" block fall into the same space, the second (grass) pops out like using Silk Touch.

![before](https://user-images.githubusercontent.com/13739585/60672118-d5427800-9e31-11e9-92ef-9c571799e7b5.png)
![after](https://user-images.githubusercontent.com/13739585/60672120-d673a500-9e31-11e9-9389-0dc6ac23262a.png)

**Comment by alcatrazEscapee** [comment]
This happens in vanilla if you have multiple falling sand entities that fall into the same spot at the same time - I don't think there's anything we can really do about it.

**Comment by LightningSh0ck** [comment]
We could make the falling blocks collide so it doesn't happen though.
