### ISSUE TITLE
can't creat a new world with 1.15.X tfc0.1.0

### ISSUE THREAD

**Issue by Watout** [TerraFirmaCraft/TerraFirmaCraft#1514]
**Describe the bug**
I input the .jar file tfc-0.1.0.jar from gardlew build directly from the IDE console, but when I start the game version 1.15.2 forge version 31.2.25, I can't create a new world. 

Here's the error report from Client
[minecraft-exported-logs-2020-08-01T18-24-49.log](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/5010748/minecraft-exported-logs-2020-08-01T18-24-49.log)

**To Reproduce**
just download the source code and compile it

**Meta Info**
 - TFC Version: 0.1.0

**Comment by alcatrazEscapee** [comment]
> just download the source code and compile it

Nope!

(We aren't going to support things that aren't anywhere close to release. If you're going to build the mod yourself from a unfinished development branch, be prepared for problems!)
