### ISSUE TITLE
Enhancement for shields and maces

### ISSUE THREAD

**Issue by ghost** [TerraFirmaCraft/TerraFirmaCraft#1525]
I have one suggestion for TFC shields and maces. 

The problem is that, if in PvP your opponent turns shield on, it is really hard to give any damage to him because shield cancel all damage in front. In vanilla you can hit player with axe and shield will be disabled for cooldown.

So i think it will be good idea to give this feature from vanilla for TFC maces or for axes at least, if it possible.

**Comment by alcatrazEscapee** [comment]
This was fixed by edd7b6d60e976a320c9f97de47985e8fa369f56c
