### ISSUE TITLE
Mobs not spawning on the surface

### ISSUE THREAD

**Issue by JonJonsonsSon** [TerraFirmaCraft/TerraFirmaCraft#1526]
...even with the following config file setting, and having restarted the server multiple times since saving these changes:
#Prevent mob spawning on surface?
        B:preventMobsOnSurface=false

I'm playing on a multiplayer server using TerraFirmaCraft-MC1.12.2-1.6.1.157.

**Comment by alcatrazEscapee** [comment]
Have you checked that spawn protection isn't denying potential spawns?

**Comment by JonJonsonsSon** [comment]
Confirmed. Spawn Protection = false everywhere I go, I'm using a night vision potion to make enemies much easier to see if they ever spawn, and the difficulty is locked to Hard, unchangeable clientside

**Comment by JonJonsonsSon** [comment]
> 
> Have you checked that spawn protection isn't denying potential spawns?

Confirmed. Spawn Protection = false everywhere I go, I'm using a night vision potion to make enemies much easier to see if they ever spawn, and the difficulty is locked to Hard, unchangeable clientside

**Comment by JonJonsonsSon** [comment]
I updated from TFC 1.6.1.157 to 1.7.3.161, skipping several versions in the process. As of 1.7.3.161 or some earlier point, this bug no longer occurs in either single player or multiplayer. 👍

**Comment by alcatrazEscapee** [comment]
*The unseen bug fix is the deadliest*
