### ISSUE TITLE
Lanterns don't save state

### ISSUE THREAD

**Issue by alcatrazEscapee** [TerraFirmaCraft/TerraFirmaCraft#1527]
> pakratt0013 / Today at 9:56 AM
hey, I'm a bit late to update from Tuesday, but I'm hoping that you guys saw that lanterns are broken?
we tested them pretty extensively for a good portion of the last hour.
turning the server off and on emptied the olive oil from the lantern, whether it was on or off...though when the server loaded, it looked on.  I don't know if they just stay on after that, but I'm pretty sure the one I set up last week died at some point.

**Comment by agilmore2** [comment]
Related to #1513 

NO idea how to fix this other than need to add something about serializatron in the TE?

**Comment by alcatrazEscapee** [comment]
Whoops, didn't see it was already an issue.
