### ISSUE TITLE
Vending block mod conflict

### ISSUE THREAD

**Issue by ghost** [TerraFirmaCraft/TerraFirmaCraft#1528]
Info interface of filled vending block not appearing if TFC is installed.

I tested this without any other mods in singleplayer and dont found any related errors in log.

This is how it should look (without TFC):

![javaw_dMeJJAJgOA](https://user-images.githubusercontent.com/64742329/89770850-b1785800-db42-11ea-823c-4f99f2f07cb5.png)

TFC Version: MC1.12.2-1.6.1.157
Vending block Version: 1.12.2-3.0.1.2

**Comment by eerussianguy** [comment]
Given that the grass is showing up grey in that photo, my guess is that that mod is handling Items poorly.

**Comment by ghost** [comment]
@eerussianguy Problem is that even vanilla items not showing with TFC.

**Comment by alcatrazEscapee** [comment]
This issue does not apply, or has been fixed in the current MC 1.18 versions of TFC, and as MC 1.12 is receiving no more development, it will be closed. If this issue arises again in 1.18, please file a new issue report.
