### ISSUE TITLE
Impossible to create stone anvil if place tool rack above stone block.

### ISSUE THREAD

**Issue by ghost** [TerraFirmaCraft/TerraFirmaCraft#1535]
**Describe the bug**
Make sure to include:
1. What did you expect to happen? - Successful creation of a stone anvil
2. What actually happened instead (i.e. what was the bug) - I cant create stone anvil with hammer, if tool rack above the stone block, in 1.7.10 you can do this without problems

**To Reproduce**
1. Place valid for anvils stone block on the ground
2. Place tool rack above stone block
3. Try to create stone anvil by right clicking with hammer on stone block.

**Meta Info**
 - TFC Version: MC1.12.2-1.6.1.157

This maybe a minor issue, but for people who moved from 1.7.10 to 1.12.2 TNG it can be confusing.

**Comment by Claycorp** [comment]
Then break the tool rack..?
It won't let you make it because there is a block above it, as intended to prevent people from making them to mine or mistakenly make them while building.

**Comment by ghost** [comment]
@Claycorp In 1.7.10 unlike 1.12.2 to create stone anvil you need to click on upside surface of block, so with that you can place non-solid blocks and cant accidentally create anvils.

Yes, i can break tool rack and create anvil before placing it, but i think it will be more convenient if stone anvil creation works like in 1.7.10

If this impossible to do, then be it
