### ISSUE TITLE
Incorrect growth visualization of HWYLA or TOP for saplings

### ISSUE THREAD

**Issue by ghost** [TerraFirmaCraft/TerraFirmaCraft#1536]
**Describe the bug**
1. I expected that growth tooltip of sapling will go smoothly from start to end of the stage.
2. After several days of growth, tooltip will stuck on 99%, when literal growth didn't even come close to this percentage.

**To Reproduce**
1. Place sapling on the ground (no matter if this fruit tree sapling or regular tree)
2. Skip continuously every day with command /timetfc add days 1
3. After several attempts growth in tooltip will stuck on 99%, while sapling actually didn't grow to the tree or to the trunk/leaves.

**Meta Info**
 - TFC Version: MC1.12.2-1.6.1.157

**Comment by eerussianguy** [comment]
99% means that the sapling is finished 'growing', but can't place a tree. Which typically means that the sapling is obstructed somehow, meaning that there's a block adjacent to it.

**Comment by alcatrazEscapee** [comment]
Sapling "growth" checks are twofold:
- is it past the pre-requisite time for the sapling to grow (this is what Hwyla is showing)
- are the conditions valid for a tree to grow.
