### ISSUE TITLE
Missing textures for donkeys and mules in the new update

### ISSUE THREAD

**Issue by ghost** [TerraFirmaCraft/TerraFirmaCraft#1538]
Screenshot tells everything:

![java_0NcUt4KZWv](https://user-images.githubusercontent.com/64742329/91242669-59b92e00-e78b-11ea-8a4a-3598b8641f38.png)

Version: MC1.12.2-1.7.0.158

**Comment by 1ahmadbassam** [comment]
![2020-08-26_11 18 57](https://user-images.githubusercontent.com/34858431/91279282-ce34a280-e774-11ea-878b-7ac12b282535.png)
I can confirm that as well. Quick code inspection shows that the donkey model is missing from assets.
