### ISSUE TITLE
Unable to feed new livestock animals in recent update

### ISSUE THREAD

**Issue by ghost** [TerraFirmaCraft/TerraFirmaCraft#1539]
**Describe the bug**
1. What did you expect to happen? Success feeding
2. What actually happened instead (i.e. what was the bug) I can lure new animals with food, but I cannot feed them.

**To Reproduce**
1. Spawn any new livestock animal.
2. Try to feed animal with valid food. For example, grain for Zebu.
3. Nothing happens.

**Meta Info**
 - TFC Version: MC1.12.2-1.7.0.158

**Comment by DisasterMoo** [comment]
Not a bug, you need to reset the config file in `[minecraft_folder]/config/tfc/animal_food_data.json`
