### ISSUE TITLE
Patchouli book causes crash

### ISSUE THREAD

**Issue by HeartyYF** [TerraFirmaCraft/TerraFirmaCraft#1541]
There are 2 things about it. One is that bear is renamed, so previous "bear"s in `predarors` should be renamed too. The other one is that opening `steel` section causes crash. Here is the crash report.

[crash-2020-08-26_10.16.45-client.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/5127189/crash-2020-08-26_10.16.45-client.txt)

EDIT: It has nothing to do with `steel` section, sry.

**Comment by alcatrazEscapee** [comment]
**Entire** log please.

**Comment by HeartyYF** [comment]
[latest.log](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/5127333/latest.log)
Here you are

**Comment by alcatrazEscapee** [comment]
```
[10:14:36] [Client thread/INFO]: [vazkii.patchouli.client.book.BookContents:reload:163]: java.lang.RuntimeException: Error while loading entry tfc:getting_started/predators
```
