### ISSUE TITLE
Most of animals spawn on chunk generation as babies

### ISSUE THREAD

**Issue by ghost** [TerraFirmaCraft/TerraFirmaCraft#1542]
**Describe the bug**
1. What did you expect to happen? I expected to have mostly full grown-up animals in groups.
2. What actually happened instead (i.e. what was the bug) Now they mostly spawn on chunk generation as babies, so it is hard to get meat from them on the beginning of playing (even from predators).

**To Reproduce**
1. Create a world
2. Fly around and you will see that almost every animal has baby state.

**Meta Info**
 - TFC Version: MC1.12.2-1.7.0.158

**Comment by DisasterMoo** [comment]
Addressed by https://github.com/TerraFirmaCraft/TerraFirmaCraft/commit/61cfbf182508ea876a4be856b8a6cd1335898d5f
