### ISSUE TITLE
Dye barrels turn into beds

### ISSUE THREAD

**Issue by AnodeCathode** [TerraFirmaCraft/TerraFirmaCraft#1550]
Seal a barrel of dye and it will eventually turn into a bed.
Make sure to include:
1. What did you expect to happen? A barrel of dye should do nothing when sealed
2. What actually happened instead (i.e. what was the bug). The barrel of dye produced a bed

**To Reproduce**
Attention to detail is important!
1. Do '...' Have a barrel of dye created from hot spring water and a dye. I used blue dye in my test
2. Then... seal the barrel. After an hour, the dye is gone and a bed is in the output slot.

**Meta Info**
 - TFC Version: TerraFirmaCraft-MC1.12.2-1.7.2.160
 - Were any other mods included? Can you reproduce it without these other mods? Just JEI, HWYLA.

**Comment by alcatrazEscapee** [comment]
Fairly sure this is the issue:

https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/f6c67271e39e37ba77a20ab186e0d1a45e271924/src/main/java/net/dries007/tfc/types/DefaultRecipes.java#L170

should reference `Items.BED` and not `Blocks.BED`. Reason being that bed does not have a standard `ItemBlock` and as such `Item.getItemFromBlock(Blocks.BED)` returns `Items.AIR`
