### ISSUE TITLE
VanillaFix causes Javelin's to crash when thrown, due to io.netty.handler.codec.EncoderException

### ISSUE THREAD

**Issue by Fr4gtastic** [TerraFirmaCraft/TerraFirmaCraft#1553]
**Describe the bug**
Make sure to include:
1. What did you expect to happen? **I expected my javelin to render on the ground.**
2. What actually happened instead (i.e. what was the bug) **Javelin does not render when thrown and the game crashes.**
3. If it was a crash, upload the full log file.
[crash-2020-09-01_11.22.38-client.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/5155410/crash-2020-09-01_11.22.38-client.txt)
4. If they would help to explain the issue, include screenshots

**To Reproduce**
Attention to detail is important!
1. Craft a stone javelin.
2. Throw it.

**Meta Info**
 - TFC Version: 1.7.2.160 
 - Were any other mods included? **Mod list included in crash log.** Can you reproduce it without these other mods? **No, pure TFC works just fine.**
 - If necessary, what other mods (including versions) MUST be present to experience the bug?

**Comment by alcatrazEscapee** [comment]
If you could narrow it down to what mods specifically are involved in the crash, that would be very helpful.

**Comment by Fr4gtastic** [comment]
It's VanillaFix, quite ironically. I disabled every mod but TFC and VF, the problem persisted. Disabled only VF, problem disappeared.

**Comment by alcatrazEscapee** [comment]
Well this is idiotic. I've tried to diagnose it but I've got nothing. Try reporting it to vanilla fix 🤷

**Comment by Fr4gtastic** [comment]
Do you mean you weren't able to replicate the issue?

**Comment by Rongmario** [comment]
I found that [SpartanWeaponry](https://www.curseforge.com/minecraft/mc-mods/spartan-weaponry) has the same issue. And it, too, does use `IEntityAdditionalSpawnData`, and writes and reads an `ItemStack` using `ByteBufUtils`, just like us.

**Comment by alcatrazEscapee** [comment]
This issue does not apply, or has been fixed in the current MC 1.18 versions of TFC, and as MC 1.12 is receiving no more development, it will be closed. If this issue arises again in 1.18, please file a new issue report.
