### ISSUE TITLE
Movement speed configuration for grass, snow, leaves and bushes not applying

### ISSUE THREAD

**Issue by staridiot** [TerraFirmaCraft/TerraFirmaCraft#1558]
I posted a [feature request ](https://github.com/TerraFirmaCraft/TerraFirmaCraft/issues/949)to make the movement penalty of various blocks configurable, it worked after it was added but no longer does. Regardless of what I change the option to the movement speed is neither increased or decreased.

**Meta Info**
 - TFC Version: MC1.12.2-1.7.2.160
 - Forge Version: 1.12.2-14.23.5.2847
 - No others mods included
 - Took place on a multiplayer server, modifying both server and client's configuration had no effect.

**Comment by HueboWasTaken** [comment]
I'm having the exact same problem

same forge version
TFC Version: 1.12.2-1.7.4.162

**Comment by alcatrazEscapee** [comment]
This is working exactly as intended for me, tested with plants, berry bushes, leaves, and snow. For the latter three, the modifier is applied exactly, the former has the different modifier (where it actually forces the real modifier, calculated from the plant's age and type, up to at least the minimum).

Are you testing this in creative mode?

**Comment by staridiot** [comment]
This is an issue, however not quite as simple as I first figured. This seems to be an issue with the server lacking movement checks and the client using it's configuration to determine player speed, not the server's configuration. So if I set the client to all 0 for slowest possible and I set the server to 1 for no penalty the client will be slowed because it's using the client's configuration not the server. Same happens in reverse, however there are no "player moved wrongly" warnings in console from what I'm assuming are lack of movement checks.

**Comment by alcatrazEscapee** [comment]
Yes, there are a number of issues that may crop up from the client and server disagreeing on config settings. You need to ensure that both server and client have the same configuration, TFC and/or forge will not sync them. As this has been fixed upstream (read: forge implemented syncable configs in post 1.13), and due to the waste of effort it would be to backport that, we operate under that assumption.

**Comment by staridiot** [comment]
Incompetency at it's finest.
