### ISSUE TITLE
Stereo sounds that should be Mono sounds?

### ISSUE THREAD

**Issue by BotionMan** [TerraFirmaCraft/TerraFirmaCraft#1563]
While playing I noticed that all of the animal sounds are stereo sounds. This makes them play on both speakers instead of having them come on the left/right speaker depending on where they come from. I don't know if this is intentional or not, but it could be fixed by converting all stereo sounds into mono sounds, as in vanilla.

**Comment by eerussianguy** [comment]
This is because our new animal sounds are ripped from Creative Commons licensed Youtube videos recorded on conventional audio equipment. I don't necessarily see any problem with it

**Comment by BotionMan** [comment]
imo it's distracting, but alright, thanks for the response... you don't say that on github, do you?
