### ISSUE TITLE
Unable to reach Brilliant White on forge with bellows & coal

### ISSUE THREAD

**Issue by trexxet** [TerraFirmaCraft/TerraFirmaCraft#1565]
I use the following setup for Forge: https://imgur.com/a/mSmtsAu
However, even if fed with Bituminous Coal and pushed Bellows constantly, the maximum temperature does not go past White, so I can't melt alloys in Vessel using Forge:
![image](https://user-images.githubusercontent.com/4649497/92919489-44096100-f439-11ea-8ff9-aa639ca8d0cd.png)

TFC Version: 1.7.3.161
I have some other TFC addons installed, which do not affect forge & metals (Aged Drinks, Ambiental, Dynamic Trees)

**Comment by alcatrazEscapee** [comment]
Coal burns at 1415 C, with bellows that's 2015 C, well above brilliant white. Cannot reproduce at all.

**Comment by trexxet** [comment]
Ow. Owie. Ouch.

I placed bellows in wrong direction: **the hole must face the forge**. I didn't notice that hole.

TNG wiki has no information about hole direction, however, 1.7.10 wiki mentions that. Wiki limits registration for my IP, so add it please.
