### ISSUE TITLE
Crash loop when falling block lands on firepit

### ISSUE THREAD

**Issue by staridiot** [TerraFirmaCraft/TerraFirmaCraft#1566]
**Describe the bug**
Happened on a server but from what I gathered a falling block landed on a fire pit and crashed the server. This lead to the server starting and crashing repeatedly. I had to deploy a backup to fix the constant crashing.

**To Reproduce**
Place fire pit, let something land on it. According to the person who owned the fire pit, there wasn't anything in it.

**Meta Info**
 - TFC Version: MC1.12.2-1.7.3.161
 - Forge Version: 14.23.5.2847
 - No other mods present
 - I did have TFC config settings `destroyItems` and `destroyOres` set to false, not sure if these play a role or not.

[crash-report.log](https://pastebin.com/CGPcxKCK)

**Comment by alcatrazEscapee** [comment]
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/0efbf98ad4b35547311ecb5e7d478ecede7f45fa/src/main/java/net/dries007/tfc/objects/blocks/devices/BlockFirePit.java#L427

`Item#getDefaultInstance` is client only. >:(
