### ISSUE TITLE
Removing recipes involving `tfc:wood/` items cause unrelated recipes to not appear in JEI

### ISSUE THREAD

**Issue by fat-sycophant** [TerraFirmaCraft/TerraFirmaCraft#1567]
So I made a crafttweaker script where I changed the recipes to all barrels 

And for some reason, JEI isn't working anymore. I know the change worked because I could craft an acacia barrel using the alternate method, yet I could not see any crafting table recipes in JEI. I could still see barrel and loom recipes however.
Later tests proved that removing the recipes of anything with <tfc:wood/> would cause JEI to stop functioning
[tfc.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/5215004/tfc.txt)

**Comment by fat-sycophant** [comment]
I apologize, I forgot to specify the mod versions
TerraFirmaCraft MC 1.12.2 - 1.7.3.161
Crafttweaker 2-1.12.2-1.0.2.31
JEI 1.12.2-4.16.1.301

**Comment by fat-sycophant** [comment]
I've gone back to version 0.25.3.87 and the bug isn't present

**Comment by eerussianguy** [comment]
Can we see the script?

**Comment by alcatrazEscapee** [comment]
This issue does not apply, or has been fixed in the current MC 1.18 versions of TFC, and as MC 1.12 is receiving no more development, it will be closed. If this issue arises again in 1.18, please file a new issue report.
