### ISSUE TITLE
Visual glitch affecting fruit tree leaves with optifine installed

### ISSUE THREAD

**Issue by JonJonsonsSon** [TerraFirmaCraft/TerraFirmaCraft#1568]
Flowering olive & lemon tree leaves, and presumably others, have this white, missing texture when one's graphics are set to fast, but not when set to fancy: https://i.imgur.com/pvckadW.png

I have the night vision potion effect in this picture, but I removed it with a bucket of milk afterward and the glitch was still occurring. This is happening in TFC 1.7.3.161.

Edit - the same glitch on a lemon tree with reindeer lichen on it: https://i.imgur.com/uyIAxVg.png

**Comment by Gaelmare** [comment]
This is the same issue as #753 Why is it happening again?

**Comment by alcatrazEscapee** [comment]
Full log please and/or installation and mod details, we had previously investigated this and found a resolution that appeared to work within vanilla albeit rather unconventional. I'd assume there's something going wrong in the middle.

**Comment by JonJonsonsSon** [comment]
[latest.log](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/5301376/latest.log)

**Comment by alcatrazEscapee** [comment]
Does the issue still occur
1) Without optifine?
2) If so, on a clean install with just TFC?

**Comment by JonJonsonsSon** [comment]
I removed optifine and the glitch stopped occurring, so it must've been the cause. https://i.imgur.com/jOTK8Gv.png

**Comment by alcatrazEscapee** [comment]
Why am I not surprised. 🙄 Optifine breaking rendering things in unknown and untraceable ways again.
