### ISSUE TITLE
Path blocks seem to be treated as non solids in some checks.

### ISSUE THREAD

**Issue by Gaboris** [TerraFirmaCraft/TerraFirmaCraft#1569]
It seems that when TFC performs certain checks it treats path blocks like if they were empty or non solid blocks.

As far as I understood these "checks" include whether or not a newly placed gravity affected block is supposed to roll down/fall and whether or not a pit kiln can be set on fire.

**What I expected**
Gravity affected blocks should treat paths as solid blocks and should only affect them by turning them into full dirt blocks when placed/fallen atop of them.
Pit kilns should light on fire even if they are surrounded by or are just next to a path block even if their top pixel is exposed.

**What currently happens**
If a gravity affected block is placed next to or above a path it falls into it as if it was empty (when other rules allow it) deleting the path in the process.
A pit kiln refuses to be lit by a fire starter or a thrown torch if even just one side of it touches a path.

**To Reproduce**
1. Place a path.
2. Place a gravity affected block (only dirt or cobblestone tested so far, but probably applies to all) next to or above the path.

1. Make a pit kiln.
2. Place a single or more paths on either its sides.
3. Try to light the kiln on fire either by a fire starter or a thrown torch.

This does not apply if a path is placed next to an already placed block or an already lit pit kiln.

**Meta Info**
 - TFC Version: 1.7.3.161
 - Optifine 1.12.2 HD U F5
 - Forge 14.23.5.2847
 - MultiMC 5 v0.6.11-1430

**Comment by alcatrazEscapee** [comment]
Path blocks are treated as non full blocks because they are, in fact, non full blocks. See #938

**Comment by Gaboris** [comment]
I LEGIT searched issues for "path" before making this post but I guess there were so many false mentions that I missed them.

Anyways I personally do not agree with this idea, but seeing how this has been brought up more then once before I won't argue with development and just hope for that "special casing" revisit mentioned in that duplicate.
