### ISSUE TITLE
TFC wooden chests are missing a oredict for mod compat

### ISSUE THREAD

**Issue by Mrthomas20121** [TerraFirmaCraft/TerraFirmaCraft#1573]
**Describe the request**
TFC Wooden chests don't have the chestWood oredict. also it might be better to use that oredict for the hopper recipe cause making hopper with a enderchest is wrong.

**Meta Info**
 - TFC Version: 1.7.3.161 (at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone? others mods mainly but tfc could benefit from it.

**Comment by fat-sycophant** [comment]
You could add this with crafttweaker if tfc wood stuff wasn't buggin out
