### ISSUE TITLE
ore_spawn_data.json can't be changed

### ISSUE THREAD

**Issue by JonJonsonsSon** [TerraFirmaCraft/TerraFirmaCraft#1575]
Whenever I save changes to the file, whether in single or multiplayer, the changes are always reverted back to their default settings. Here's the last version of that file I tried to save & use in a fresh single player world, only for it to be overwritten with the default values instantly: https://pastebin.com/YH23D23k
As far as I've seen by using diffchecker & notepad++, there isn't a single comma, bracket, brace, etc. out of place, but I could be wrong... Despite quadruple checking!
TFC version: 1.7.3.161

**Comment by alcatrazEscapee** [comment]
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/0efbf98ad4b35547311ecb5e7d478ecede7f45fa/src/main/java/net/dries007/tfc/ConfigTFC.java#L149

Check the config, disable this.
