### ISSUE TITLE
Compatibility with OptiFine / OptiFine parallax water not working

### ISSUE THREAD

**Issue by injektmepls** [TerraFirmaCraft/TerraFirmaCraft#1577]
OptiFine parallax water effect not working with TFC enabled.  Instead of displaying the effect (image 1), the water reverts back to the vanilla texture in TFC with no transparency effect (image 2).  All other shader effects seemed to be working correctly.

Issue was experienced with TFC 1.7.4.162 running OptiFine 1.12.2 HD U F5 and F6_pre1.  Confirmed that this conflict/bug occurred with multiple shader packs (Chocapic13, Voyager, and Cybox).

![parallax_working](https://user-images.githubusercontent.com/5820723/94383060-cc535b80-00f3-11eb-88d9-e8927fb3f882.png)

![parallax_not_working](https://user-images.githubusercontent.com/5820723/94383068-d1180f80-00f3-11eb-8e41-550d34d5aaeb.png)

**Comment by alcatrazEscapee** [comment]
Probably because that's not vanilla water, it's TFC's fresh water. Also it's optifine, a closed source jar mod which we don't support. In any case, it's not going to be our fix. You may have luck asking on our discord for people who've found workarounds.
