### ISSUE TITLE
spiders bug

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [TerraFirmaCraft/TerraFirmaCraft#1579]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
I enabled spawn mobs on the surface. but the problem with spiders is 1) they always attack the player, even during the day. why? this should not be the case 2) since they are focused on the player, they do not despawn and there may be dozens of them

2. What actually happened instead (i.e. what was the bug)
spiders should not touch the player during the day. spiders must despawn

**To Reproduce**
none

**Meta Info**
 - TerraFirmaCraft-MC1.12.2-1.7.4.162.jar

**Comment by alcatrazEscapee** [comment]
Cannot reproduce, with either config option. Spiders are passive towards the player during daytime and despawn exactly as expected.

Please post your `latest.log` file, in addition any specific reproduction info would be desired.
