### ISSUE TITLE
Visual bug

### ISSUE THREAD

**Issue by officialGerero** [TerraFirmaCraft/TerraFirmaCraft#1582]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
Transparent frame of items not overlapping each other when placed
2. What actually happened instead (i.e. what was the bug)
"Transparent"  item frame overlaps other  placed items
![2020-09-27_22 10 35](https://user-images.githubusercontent.com/40302455/94608416-0fedc700-02a6-11eb-877d-b1ae0f9db7fc.png)

**To Reproduce**
Attention to detail is important!
1. Place a couple of  items on the ground
2. Look on them with an angle

Tested on ceramic vessels 

**Meta Info**
 - TFC Version: 0.1.7.3.161

**Comment by alcatrazEscapee** [comment]
Full log please. (`latest.log` in the `.minecraft` folder).

**Comment by officialGerero** [comment]
[latest.log](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/5356165/latest.log)

**Comment by alcatrazEscapee** [comment]
This issue does not apply, or has been fixed in the current MC 1.18 versions of TFC, and as MC 1.12 is receiving no more development, it will be closed. If this issue arises again in 1.18, please file a new issue report.
