### ISSUE TITLE
Concise description of what the enhancement is

### ISSUE THREAD

**Issue by AlexRover** [TerraFirmaCraft/TerraFirmaCraft#1583]
**Describe the request**
Make sure to include:
1. What problem or issue would this enhancement solve?
2. Describe the feature itself - what would change, what would happen. In general more detail is good!

**Meta Info**
 - TFC Version: 1.7.4.162 (at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
 - If necessary, what other mods (including versions) would this require?

1.  2.Hello, now I am working on the assembly for myself and faced the problem of not being able to break the ore on the anvil, he suggests heating it up and putting it one by one, it would be cool if I could not only weld metal and forge, but also crush something on the anvil, that the same flux, at least one add-on offers to break diamonds in hands, but it is not as convenient as on an anvil.
I would also like to be able to add recipes to the ore washing gutter, this is the next stage of ore processing

TerraFirmaCraft-MC1.12.2-1.7.4.162
--

**Comment by alcatrazEscapee** [comment]
What on earth...

I have no idea what you are suggesting, everything you've said makes no sense.

**Comment by AlexRover** [comment]
I propose to add another method of processing things on anvils "break" to get broken ore and possibly something else

Also the ability to customize and add recipes to the ore rinsing chute
