### ISSUE TITLE
Mobs are dropping armor with enchantments

### ISSUE THREAD

**Issue by Envel-Nikita-Gutsenkov** [TerraFirmaCraft/TerraFirmaCraft#1584]
with mobs falls enchanted armor -> in TFK there are no enchantments -> armor should drop without enchantments, please fix it

p.s. sorry for not a template answer, there is really nothing more to explain

Meta Info

TerraFirmaCraft-MC1.12.2-1.7.4.162.jar

**Comment by alcatrazEscapee** [comment]
After a conversation with AnodeCathode about a related case, we've identified that this does not seem to be a TFC bug as there's no way that TFC equipment would get enchantments applied via vanilla enchantment methods. (The offending mod in this case was BWM) Can you reproduce with just TFC?
