### ISSUE TITLE
Shift Clicking fluids out of Jugs.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#1587]
The ability to shift click a jug to empty the fluid inside of it similar to emptying a wooden bucket would be nice, good way to remove accidentally collected salt water.
Configurable "on vs off" option, ideally.

**Comment by hron84** [comment]
It would be better if we can boil them out. Heat in a firepit/forge and at some point it swaps the filled jug with an empty one.

**Comment by hron84** [comment]
Yay, thanks @alcatrazEscapee
