### ISSUE TITLE
classic terrafirmacraft musics

### ISSUE THREAD

**Issue by sinanisler** [TerraFirmaCraft/TerraFirmaCraft#1589]
i played alot 1.7.10 and i remember the tfc musics it was awesome.

i am trying 1.12.2 rightnow and i dont hear the terrafirmacraft music playlist anymore.

are you planing to add the musics?

**Comment by Fr4gtastic** [comment]
There is a [resource pack](https://www.curseforge.com/minecraft/texture-packs/terrafirmacraft-classic-music) adding the music, so I guess the devs won't add it themselves. Don't quote me on that though.

**Comment by alcatrazEscapee** [comment]
ea129b4e409fb6c8be9bb7beda369dce44b89800
