### ISSUE TITLE
block gravity system as standalone mod

### ISSUE THREAD

**Issue by Biviho** [TerraFirmaCraft/TerraFirmaCraft#1594]
hi, i wanted to ask if it's possible to relase the cave-ins and falling block system with the ability to define support beams as a standalone mod for 1.12 at least.
i personally think that how terrafirmacraft handle this is in a pretty deep way and it would be a good feature as a standalone mod for those modpack where adding all the other things from terrafirmacraft is a bit problematic.

basically this will need to have a config to define blocks that will cause cave (stone behaviour) ins with a config for the blocks they will turn into, blocks that need to be supported by terrain (brick behaviour) and blocks that can't stack (dirt/cobblestone behaviour)
also the ability to config what blocks are support blocks

**Comment by alcatrazEscapee** [comment]
Nope!

In 1.16 with the additional customization options made available by data packs, everything you just asked to be configurable already is. We're still very likely not going to split it into a separate mod.
