### ISSUE TITLE
Hyenas drop canid meat

### ISSUE THREAD

**Issue by EnderiumSmith** [TerraFirmaCraft/TerraFirmaCraft#1595]
![2020-10-06_19 43 13](https://user-images.githubusercontent.com/20334653/95238676-83498880-0812-11eb-9008-c42d10fa0f8a.png)

**Comment by DisasterMoo** [comment]
Not a bug, all "canine" animals drop it, e.g: Wolf, Direwolf, Hyena, Jackal, etc.

**Comment by EnderiumSmith** [comment]
@DisasterMoo one of those doesnt belong.

https://en.wikipedia.org/wiki/Hyena
