### ISSUE TITLE
Leaves textures are broken with optifine on fast graphics

### ISSUE THREAD

**Issue by EnderiumSmith** [TerraFirmaCraft/TerraFirmaCraft#1596]
When optifine is installed the transparent part of the leaf texture renders green instead of black on fast graphics. I looked into this a while ago as Twilight Forest was for some reason the only mod immune to this and i found that to fix this the leaf texture must be the vanilla one. Not copying the texture, literally using the texture from the minecraft assets in the model path. I reported this to optifine twice but got no response after years. It looks like the TFC textures arent vanilla so a different fix will have to be found. This bug is quite annoying as 1.12 is a lot laggier than 1.7 without having to turn on fancy graphics.
![2020-10-06_19 15 26](https://user-images.githubusercontent.com/20334653/95239679-f99aba80-0813-11eb-9b99-4086b3af3e9f.png)

**Comment by alcatrazEscapee** [comment]
Not supporting optifine, you're on your own there. I'd assume this is due to the way we handle #753 and if such we aren't changing that because it's caused all manner of headache on it's own and the fix for which is dodgy at best.

**Comment by EnderiumSmith** [comment]
its unrelated to 753. fruit trees still look like that too but for a different reason.
