### ISSUE TITLE
Teleporting to another dimension causes NPE

### ISSUE THREAD

**Issue by V10lator** [TerraFirmaCraft/TerraFirmaCraft#16]
When the player teleports to another world by climbing/falling this is the result: https://pastebin.com/R7jKGGHq

**Comment by alcatrazEscapee** [comment]
Take a look at the full log. In there you will see a line that says "[main/WARN] [tfc]: You are not running an official build. Please do not use this and then report bugs or issues."

**Comment by V10lator** [comment]
- The build is from https://jenkins.dries007.net/view/TFC//job/TerraFirmaCraft/
- The line you told me to look for is not in the log
- I'm the author oft V10verlap trying to track this mod incompatibility down before it gets widely used

**Comment by Bunsan** [comment]
This crash is not specifically a compatibility issue with your mod. This is an issue with changing dimensions as the same crash occurs when going through a nether portal. We are early in development so we've not addressed issues with other dimensions yet.
