### ISSUE TITLE
Allow adding slab/stair recipes for the chisel without having to setup crafting table recipe for it

### ISSUE THREAD

**Issue by SeriousCreeper** [TerraFirmaCraft/TerraFirmaCraft#1601]
**Describe the request**
Currently we can only add recipes to the chisel for the "smooth" mode. 
Ideally i would like to be able to add stair and slab recipes, without them being craftable in a crafting table. 

What i'm trying to achieve is that early on, making stairs and slab requires the chisel & hammer (remove all crafting table recipes for those) and at a later point use something like the sawmill from Pyrotech to allow automating crafting them instead.

**Meta Info**
 - TFC Version: 1.7.4.162
 - Is this a compatibility feature for other mods? (**in a way yes)**

**Comment by eerussianguy** [comment]
https://github.com/TerraFirmaCraft/TerraFirmaCraft/commit/eb94fa942bba09386f98bc4c46de1958f43a7013
