### ISSUE TITLE
Filling a bucket from a barrel-...

### ISSUE THREAD

**Issue by JonJonsonsSon** [TerraFirmaCraft/TerraFirmaCraft#1611]
When in survival mode, filling a bucket - either wooden or metal - with fluid from a barrel works as expected. However, when you try to fill a bucket with fluid from a barrel in creative mode, the bucket in your hand will remain empty despite an appropriate amount of fluid being deleted from the barrel

Tested using a black dye barrel in TFC v1.7.4.162

**Comment by alcatrazEscapee** [comment]
This seems consistent with how vanilla handles creative mode buckets: If you click an empty bucket on a water source, the water source is removed and you keep the empty bucket.
