### ISSUE TITLE
gold panning not working 1.12.2

### ISSUE THREAD

**Issue by sirblockwood101** [TerraFirmaCraft/TerraFirmaCraft#1612]
yeah have gravel on dry land fill with gold pan and use on running water and it just does not work

**Comment by alcatrazEscapee** [comment]
There's really not enough information here for us to diagnose the problem. I believe it's probably a case of not using the gold pan correctly, or the effect of #885.

If the former, try asking in our discord for support.

**Comment by DisasterMoo** [comment]
Should've been the effect of #885. If there are any issues in this new release, please open a new issue.
