### ISSUE TITLE
Forge and Blast Furnace inconsistencies and unintended differences?

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1615]
In both TECharcoalForge and TEBlastFurnace, Bellows providing air actually make the TE heat faster. I guess since the heating of the contents is dependent on their heat conductance, it doesn't help much to heat up the TE faster? This is not what I remember from Classic.

Both TE also cool slower with supplied air and no fuel/lower temp fuel which probably helps the player, but doesn't make sense. 

Contrary to what I understood about Classic, the BlastFurnace doesn't consume more fuel when supplied air via bellows.

CharcoalForge uses CapabilityItemHeat.adjustTempTowards, BlastFurnace does not.

**Comment by alcatrazEscapee** [comment]
45a652c9fa5f85d7e345eb68ee397ccf9c25028f
