### ISSUE TITLE
Cannot make torches

### ISSUE THREAD

**Issue by harvald** [TerraFirmaCraft/TerraFirmaCraft#1616]
When I put stick into firepit, there is tip "catching fire", then "lit" and stick disappear. There are no torches.

Firepit is burning normal. I can cook food. Tried also with "bunch of sticks", but no luck.

 - TFC Version: TerraFirmaCraft-MC1.12.2-1.7.5.163.jar
 - No other mods.

**Comment by alcatrazEscapee** [comment]
Sounds like #567, are you using LiteLoader / Sponge / any other server software?

**Comment by harvald** [comment]
You're right! Thank you. After I've removed LiteLoader, problem disappeared.
