### ISSUE TITLE
Support beams placement check can go through solid blocks

### ISSUE THREAD

**Issue by alcatrazEscapee** [TerraFirmaCraft/TerraFirmaCraft#1618]
Bit of an odd placement case:

X/Y cross section:
```
SB..TS
S....S
S....S
```
Where `S` is a support beam, `B` is a solid block. Placing a support beam at `T` will place a full support beam, despite the placement should be being blocked by the block at `B`.

It only occurs if the block `B` is directly adjacent to the other support column. Causing a block update near the placed supports will cause them to break.

**Comment by LordFokas** [comment]
Also reproduces with 2 block gap:
```
SBTS
S..S
S..S
```

and 5 block gap:
```
SB...TS
S.....S
S.....S
```

but **not** with 3 block gap:
```
SB.TS
S...S
S...S
```

**Comment by LordFokas** [comment]
![image](https://user-images.githubusercontent.com/3021352/101833062-55453500-3b30-11eb-9171-15672f831820.png)
