### ISSUE TITLE
Incompatibility with Snow! Real Magic! due to registry replacement of `snow_layer`

### ISSUE THREAD

**Issue by juraj-hrivnak** [TerraFirmaCraft/TerraFirmaCraft#1642]
**Describe the bug**
- What did you expect to happen?
Game to startup

- What actually happened instead
Game crashed on startup

### Log
https://paste.ee/p/ztqHB

**Meta Info**
 - TFC Version: **1.12.2** - **1.7.9.167**

Others:
  [✔️] animania-1.12.2-base-2.0.0.23
  [✔️] antiqueatlas-1.12.2-4.6.3
  [✔️] AppleCore-mc1.12.2-3.4.0
  [✔️] AppleSkin-mc1.12-1.0.14
  [✔️] appliedenergistics2-rv6-stable-7
  [✔️] ASMC-1.12.2-1.0.2
  [✔️] auginter-1.1.0-1.12.x
  [✔️] AutoRegLib-1.3-32
  [✔️] BadMobs-1.12.2-1.1.40
  [✔️] base-1.12.2-3.13.0
  [✔️] Baubles-1.12-1.5.2
  [✔️] BetterAdvancements-1.12.2-0.1.0.77
  [✔️] BetterDiving-1.12.2-1.5.8
  [✔️] BetterFps-1.4.8
  [✔️] BetterQuesting-3.5.329
  [✔️] BiomesOPlenty-1.12.2-7.0.1.2444-universal
  [✔️] BiomeTweaker-1.12.2-3.2.369
  [✔️] BiomeTweakerCore-1.12.2-1.0.39
  [✔️] blockgravity-2.0.5
  [✔️] Bookshelf-1.12.2-2.3.590
  [✔️] BurningTorch-1.1.3
  [✔️] Ceramics-1.12-1.3.7
  [✔️] ClientTweaks_1.12.2-3.1.11
  [✔️] clothesline-1.12.2-0.0.3.0-bundle
  [✔️] CodeChickenLib-1.12.2-3.2.3.358-universal
  [✔️] comforts-1.12.2-1.4.1.3
  [✔️] ContentTweaker-1.12.2-4.9.1
  [✔️] Controlling-3.0.10
  [✔️] CookingForBlockheads_1.12.2-6.5.0
  [✔️] coroutil-1.12.1-1.2.37
  [✔️] CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha
  [✔️] CraftTweaker2-1.12-4.1.20.602
  [✔️] CreativeCore_v1.10.34_mc1.12.2
  [✔️] Cuisine-0.5.22-build929
  [✔️] CustomMainMenu-MC1.12.2-2.0.9.1
  [✔️] Cyclic-1.12.2-1.20.8
  [✔️] dawnoftime_builder_edition-1.0.7
  [✔️] Divergent-Underground-1.12-0.64.0
  [✔️] DynamicSurroundings-1.12.2-3.6.2.1
  [✔️] DynamicSurroundingsHuds-1.12.2-3.6.0.0
  [✔️] DynamicTrees-1.12.2-0.9.21
  [✔️] DynamicTreesBOP-1.12.2-1.4.4
  [✔️] DynamicTreesForestry-1.12.2-1.0.9
  [✔️] DynamicTreesPHC-1.12.2-2.0.5
  [✔️] EmergingTechnology-1.12.2-1.3.26-alpha
  [✔️] Exotic+Birds+1.12.2-3.2.0
  [✔️] Farseek-1.12-2.5.1
  [✔️] FE-1.12.2-0.1.3.1
  [✔️] foamfix-0.10.10-1.12.2
  [✔️] forestry_1.12.2-5.8.2.422
  [✔️] Forgelin-1.8.4
  [✔️] ForgeMultipart-1.12.2-2.6.2.83-universal
  [✔️] gamestagebooks-1.12.2-1.0.2-universal
  [✔️] GameStages-1.12.2-2.0.123
  [✔️] Geolosys-1.12.2-3.0.10
  [✔️] horse_colors-1.12.2-1.4.0.1
  [✔️] Hwyla-1.8.26-B41_1.12.2
  [✔️] CharcoalPit-[1.12]-1.20
  [✔️] Chunk+Pregenerator+V1.12-2.4E
  [✔️] ido-1.12.2-1.1.0
  [✔️] ImmersiveEngineering-0.12-98
  [✔️] immersivepetroleum-1.12.2-1.1.9
  [✔️] ImmersivePosts-0.2.1
  [✔️] InventoryTweaks-1.63
  [✔️] ItemPhysic_Full_1.4.34_mc1.12.2
  [✔️] ItemStages-1.12.2-2.0.51
  [✔️] IvToolkit-1.3.3-1.12
  [✔️] jei_1.12.2-4.16.1.302
  [✔️] journeymap-1.12.2-5.7.1
  [✔️] JustEnoughPetroleum-0.1
  [✔️] Kiwi-1.12.2-0.5.3.32
  [✔️] lightningtweaks-1.12.2-1.2.1.0
  [✔️] LittleTiles_v1.5.0-pre199_73_mc1.12.2
  [✔️] Mantle-1.12-1.3.3.55
  [✔️] matmos-1.12.2-35.2
  [✔️] MCTImmersiveTechnology-1.12.2-1.8.87
  [✔️] MouseTweaks-2.10-mc1.12.2
  [✔️] MrTJPCore-1.12.2-2.1.4.43-universal
  [✔️] NaturesCompass-1.12.2-1.8.5
  [✔️] noRecipeBook_v1.2.2formc1.12.2
  [✔️] NotEnoughIDs-1.5.4.4
  [✔️] NotEnoughPets-1.12.2-v2.2.0
  [✔️] NoWorldgen5You-1.12.2-1.0.6
  [✔️] NuclearCraft-2o.4.7-1.12.2
  [✔️] OreLib-1.12.2-3.6.0.1
  [✔️] outfox-0.1.5-mc1.12.2
  [✔️] Pam's HarvestCraft 1.12.2zg
  [✔️] Patchouli-1.0-22
  [✔️] phosphor-forge-mc1.12.2-0.2.7-universal
  [✔️] platforms-1.12.0-1.4.6
  [✔️] PrettyBeaches_1.12.2-1.1.0
  [✔️] ProjectRed-1.12.2-4.9.4.120-Base
  [✔️] ProjectRed-1.12.2-4.9.4.120-fabrication
  [✔️] ProjectRed-1.12.2-4.9.4.120-integration
  [✔️] ProjectRed-1.12.2-4.9.4.120-lighting
  [✔️] ProjectRed-1.12.2-4.9.4.120-mechanical
  [✔️] ProjectRed-1.12.2-4.9.4.120-world
  [✔️] Puddles-1.1
  [✔️] Quark-r1.6-179
  [✔️] questbook-3.1.1-1.12
  [✔️] randompatches-1.12.2-1.22.1.7
  [✔️] RealFirstPerson2-1.12.2-1.3.2
  [✔️] RecipeStages-1.1.3
  [✔️] RecurrentComplex-1.4.8.2
  [✔️] Re-Fraction+V1.0
  [✔️] ResourceLoader-MC1.12.1-1.5.3
  [✔️] RTG-1.12.2-6.1.0.0-snapshot.1
  [✔️] rustic-1.1.7
  [✔️] scarper-1.1
  [✔️] Scavenge+V1.12-1.8.3.2
  [✔️] SereneSeasons-1.12.2-1.2.18-universal
  [✔️] shetiphiancore-1.12.0-3.5.9
  [✔️] SimpleDifficulty-1.12.2-0.3.4
  [✔️] SnowRealMagic-0.3.3
  [✔️] Sound-Physics-1.12.2-1.0.9
  [✔️] SpiceOfLife-mc1.12-1.3.12
  [✔️] StandardExpansion-3.4.173
  [✔️] Streams-1.12-0.4.8
  [✔️] TConstruct-1.12.2-2.13.0.183
  [✔️] TerraFirmaCraft-MC1.12.2-1.7.9.167
  [✔️] TFC-Metallum-MC1.12.2-1.4.0
  [✔️] TidyChunk-1.12.2-1.0.0.0
  [✔️] TinkersComplement-1.12.2-0.4.3
  [✔️] TinkerSurvival-1.12.2-1.2.2.1
  [✔️] TipTheScales-1.12.2-1.0.4
  [✔️] tropicraft-MC1.12.2-7.1.9.115
  [✔️] VanillaFix-1.0.10-150
  [✔️] Waddles-1.12.2-0.6.0
  [✔️] walljump-1.12.2-1.3.2
  [✔️] Wawla-1.12.2-2.6.275
  [✔️] weather2-1.12.1-2.6.12
  [✔️] World-Stripper-1.6.0-1.12.2
  [✔️] worleycaves-1.12.2-1.5.2

**Comment by eerussianguy** [comment]
You have installed a ton of coremods that change loading. Try disabling those first (Foamfix, vanillafix, phosphor, quark, applecore...)

Also a couple misunderstandings -- Streams is not compatible with TFC, don't install it that's just gonna cause problems
AppleCore/AppleSkin are not compatible with TFC, they'll make stuff look wrong.
Recurrent complex sometimes crashes with TFC in-game

**Comment by alcatrazEscapee** [comment]
> You have installed a ton of coremods that change loading.

This shouldn't be relevant based on a `populateSearchTree` crash.

My initial guess is either a mod conflict similar to #381 based on the location. Would need to figure out which mod is exclusive and then debug into what recipe / item is throwing NPEs. If I had to guess it seems like a badly registry replaced something is sticking around somewhere.

**Comment by juraj-hrivnak** [comment]
Update here! Sorry for the late reply.

- So, I removed all the coremods (Foamfix, vanillafix, phosphor, quark, applecore...) But the crash persists.
These are currently loaded coremods:
>   IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
>   LoadingPlugin (AdChimneys-1.12.2-3.5.15.0-build.0560.jar)
>   ForgelinPlugin (Forgelin-1.8.4.jar)
>   clothesline-hooks (clothesline-hooks-1.12.2-0.0.1.2.jar)
>   MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
>   LoadingPlugin (AdPother-1.12.2-1.2.12.0-build.0558.jar)
>   OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
>   TransformLoader (DynamicSurroundings-1.12.2-3.6.2.1.jar)
>   CorePlugin (ForgeEndertech-1.12.2-4.5.5.0-build.0561.jar)
>   BiomeTweakerCore (BiomeTweakerCore-1.12.2-1.0.39.jar)
>   CoreModLoader (Sound-Physics-1.12.2-1.0.10-1.jar)
>   Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
>   ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
>   ParticleCullingLoadingPlugin (particleculling-1.12.2-v1.0.1.jar)
>   CreativePatchingLoader (CreativeCore_v1.10.44_mc1.12.2.jar)
>   ItemPatchingLoader (ItemPhysic_Full_1.4.34_mc1.12.2.jar)
>   JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-55.jar)
>   LittlePatchingLoader (LittleTiles_v1.5.0-pre321_mc1.12.2.jar)
>   IvToolkit (IvToolkit-1.3.3-1.12.jar)
I will try to remove all the coremods possible.

Here is the full log: https://paste.ee/p/SbNEN
Modlist:
  [✔️] AdChimneys-1.12.2-3.5.15.0-build.0560
  [✔️] AdPother-1.12.2-1.2.12.0-build.0558
  [✔️] appliedenergistics2-rv6-stable-7
  [✔️] BadMobs-1.12.2-1.1.40
  [✔️] base-1.12.2-3.13.0
  [✔️] Baubles-1.12-1.5.2
  [✔️] BetterQuesting-3.5.329
  [✔️] BiblioCraft[v2.4.5][MC1.12.2]
  [✔️] BiomeTweaker-1.12.2-3.2.369
  [✔️] BiomeTweakerCore-1.12.2-1.0.39
  [✔️] Bookshelf-1.12.2-2.3.590
  [✔️] ClientTweaks_1.12.2-3.1.11
  [✔️] clothesline-1.12.2-0.0.3.0-bundle
  [✔️] CodeChickenLib-1.12.2-3.2.3.358-universal
  [✔️] CoFHCore-1.12.2-4.6.6.1-universal
  [✔️] CoFHWorld-1.12.2-1.4.0.1-universal
  [✔️] comforts-1.12.2-1.4.1.3
  [✔️] ContentTweaker-1.12.2-4.9.1
  [✔️] Controlling-3.0.10
  [✔️] CookingForBlockheads_1.12.2-6.5.0
  [✔️] coroutil-1.12.1-1.2.37
  [✔️] CraftTweaker2-1.12-4.1.20.616
  [✔️] CreativeCore_v1.10.44_mc1.12.2
  [✔️] Cyclic-1.12.2-1.20.8
  [✔️] dawnoftime_builder_edition-1.0.7
  [✔️] DynamicSurroundings-1.12.2-3.6.2.1
  [✔️] DynamicSurroundingsHuds-1.12.2-3.6.0.0
  [✔️] EmergingTechnology-1.12.2-1.3.26-alpha
  [✔️] Exotic Birds 1.12.2-3.2.0
  [✔️] FantasticLib-1.12.2.044
  [✔️] FastWorkbench-1.12.2-1.7.3
  [✔️] forestry_1.12.2-5.8.2.422
  [✔️] ForgeEndertech-1.12.2-4.5.5.0-build.0561
  [✔️] Forgelin-1.8.4
  [✔️] ForgeMultipart-1.12.2-2.6.2.83-universal
  [✔️] gamestagebooks-1.12.2-1.0.2-universal
  [✔️] GameStages-1.12.2-2.0.123
  [✔️] Hwyla-1.8.26-B41_1.12.2
  [✔️] Chunk Pregenerator-V1.12-2.4.1
  [✔️] ido-1.12.2-1.1.0
  [✔️] ImmersiveEngineering-0.12-98
  [✔️] immersivepetroleum-1.12.2-1.1.9
  [✔️] ImmersivePosts-0.2.1
  [✔️] industrialforegoing-1.12.2-1.12.13-237
  [✔️] IndustrialWires-1.7-36
  [✔️] InventoryTweaks-1.63
  [✔️] ItemPhysic_Full_1.4.34_mc1.12.2
  [✔️] IvToolkit-1.3.3-1.12
  [✔️] jei_1.12.2-4.16.1.302
  [✔️] journeymap-1.12.2-5.5.4
  [✔️] JourneyMapStages-1.12.2-2.0.9
  [✔️] JustEnoughIDs-1.0.3-55
  [✔️] JustEnoughPetroleum-0.1
  [✔️] lightningtweaks-1.12.2-2.0.0.0-alpha1
  [✔️] LittleTiles_v1.5.0-pre321_mc1.12.2
  [✔️] Mantle-1.12-1.3.3.55
  [✔️] MCMultiPart-2.5.3
  [✔️] MCTImmersiveTechnology-1.12.2-1.8.93
  [✔️] Mekanism-1.12.2-9.8.3.390
  [✔️] MekanismGenerators-1.12.2-9.8.3.390
  [✔️] modtweaker-4.0.18
  [✔️] MouseTweaks-2.10-mc1.12.2
  [✔️] MrTJPCore-1.12.2-2.1.4.43-universal
  [✔️] MTLib-3.0.6
  [✔️] multiblockstages-1.2.0
  [✔️] NaturesCompass-1.12.2-1.8.5
  [✔️] NoAdvancements-1.12.2.002
  [✔️] noRecipeBook_v1.2.2formc1.12.2
  [✔️] NuclearCraft-2o.4.7-1.12.2
  [✔️] OpenBlocks-1.12.2-1.8.1
  [✔️] OpenModsLib-1.12.2-0.12.2
  [✔️] OreLib-1.12.2-3.6.0.1
  [✔️] outfox-0.1.5-mc1.12.2
  [✔️] particleculling-1.12.2-v1.0.1
  [✔️] Patchouli-1.0-23.6
  [✔️] platforms-1.12.0-1.4.6
  [✔️] PrettyBeaches_1.12.2-1.1.0
  [✔️] ProjectRed-1.12.2-4.9.4.120-Base
  [✔️] ProjectRed-1.12.2-4.9.4.120-fabrication
  [✔️] ProjectRed-1.12.2-4.9.4.120-integration
  [✔️] ProjectRed-1.12.2-4.9.4.120-lighting
  [✔️] ProjectRed-1.12.2-4.9.4.120-mechanical
  [✔️] ProjectRed-1.12.2-4.9.4.120-world
  [✔️] questbook-3.1.1-1.12
  [✔️] RecipeStages-1.1.3
  [✔️] RecurrentComplex-1.4.8.2
  [✔️] RedstoneFlux-1.12-2.1.1.1-universal
  [✔️] Re-Fraction V1.0
  [✔️] rustic-1.1.7
  [✔️] scarper-1.1
  [✔️] Scavenge V1.12-1.8.3.2
  [✔️] shetiphiancore-1.12.0-3.5.9
  [✔️] SnowRealMagic-0.3.3
  [✔️] Sound-Physics-1.12.2-1.0.10-1
  [✔️] StandardExpansion-3.4.173
  [✔️] TConstruct-1.12.2-2.13.0.183
  [✔️] TerraFirmaCraft-MC1.12.2-1.5.5.155
  [✔️] tesla-core-lib-1.12.2-1.0.17
  [✔️] ThermalDynamics-1.12.2-2.5.6.1-universal
  [✔️] ThermalFoundation-1.12.2-2.6.7.1-universal
  [✔️] ThermalInnovation-1.12.2-0.3.6.1-universal
  [✔️] TidyChunk-1.12.2-1.0.0.0
  [✔️] TinkersComplement-1.12.2-0.4.3
  [✔️] tinkersjei-1.2
  [✔️] TipTheScales-1.12.2-1.0.4
  [✔️] Waddles-1.12.2-0.6.0
  [✔️] WailaHarvestability-mc1.12-1.1.12
  [✔️] walljump-1.12.2-1.3.2
  [✔️] Wawla-1.12.2-2.6.275
  [✔️] weather2-1.12.1-2.6.12
  [✔️] World-Stripper-1.6.0-1.12.2

**Comment by Rongmario** [comment]
I believe the crash comes from `Snow! RealMagic!` as that overrides `snow_layer` which we also override. Remove that mod and it should work.

**Comment by juraj-hrivnak** [comment]
Yeah! :D **that was it!** I got a lot of mods that could override some stuff, like `Divergent Underground`, `Real Torches` or similar, but I forgot about the `Snow! RealMagic`! Thanks!

Should I rename this issue or close it and make a new one? Or keep it as it is and close it?

**Comment by alcatrazEscapee** [comment]
See the config option `enableFrozenOverrides`.

That will voluntarily disable our registry replacement. You can choose this, or removing Snow! RealMagic!. This is the same conflict with Primal Core (w.r.t torch replacements).
