### ISSUE TITLE
Blocks fall horizontal when not supported by beam

### ISSUE THREAD

**Issue by Red3Tango** [TerraFirmaCraft/TerraFirmaCraft#165]
**[0.11.0.49]**
When placing collapsible blocks on support beams, when limit is reached (5th block) the blocks shifts horizontally first then falls. Instead of falling straight down as expected (as in 1.7.10).

![support](https://user-images.githubusercontent.com/13739585/61173669-a1630300-a553-11e9-8008-82e81e1f7408.png)

**Comment by alcatrazEscapee** [comment]
Can you show an example of exactly what you are doing and what you expect to happen vs. what is actually happening?
