### ISSUE TITLE
Decayed food should not be ingredients in custom recipes.

### ISSUE THREAD

**Issue by Woody-0w0** [TerraFirmaCraft/TerraFirmaCraft#1651]
**Describe the bug**
1. What did you expect to happen?
Decayed food should not be ingredients in recipes.
2. What actually happened instead (i.e. what was the bug)
Decayed food can be ingredients in a custom recipe which is added by crafttweaker.

**To Reproduce**
 'add crafttweaker recipes as:
```recipes.addShapeless(<wlgr:bait>*3,[<cfm:item_knife>.reuse(),<tfc:food\fish>,<tfc::food\fish>]);```
will not exclude decayed fish as ingredients.
'

**Meta Info**
 - TFC Version: any
 - Were any other mods included? Can you reproduce it without these other mods?
 crafttweaker
 - If necessary, what other mods (including versions) MUST be present to experience the bug?
 crafttweaker

**Comment by alcatrazEscapee** [comment]
Not sure why you expected this to be any different - craft tweaker is completely unaware of food decay, and as such has no ability to discriminate based on it (nor even if we could, make it automatically behave this way). TFC uses custom recipe types (`damage_item_shapeless` and `damage_item_shaped`) which handle food decay in this way if you use vanilla json recipes. For custom machines, they all need to - at some level - be aware of food decay and handle it explicitly, usually requiring an addon.
