### ISSUE TITLE
Hopper working as vanilla

### ISSUE THREAD

**Issue by CrushDust** [TerraFirmaCraft/TerraFirmaCraft#1657]
Not entirely sure if this is a feature or a bug, but in the original wiki, it is stated that the hopper is now an olive press, and lacks its original features. However, now it doesn't work as an olive press, something which would be very nice to have when you have to grind stacks of olives.

I tried placing a hopper on top of a barrel with a stone on top in creative, but the olives were just transported into the barrel, as to expect from a vanilla hopper.

TFC Version: TerraFirmaCraft-MC1.12.2-1.7.9.167
Forge Version: 1.12.2-forge1.12.2-14.23.5.2847

**Comment by Charnuz** [comment]
That's because that is intended, you do that in the grindstone now
https://tng.terrafirmacraft.com/Differences_From_Classic
