### ISSUE TITLE
Can brine far too much food with one bucket of brine

### ISSUE THREAD

**Issue by Hawk777** [TerraFirmaCraft/TerraFirmaCraft#1658]
I can brine a 64-item stack of raw beef with a single bucket of brine.

**To Reproduce**
1. Spawn cows using spawn eggs and kill them until you have 64 raw beef.
2. Using JEI, give yourself an acacia barrel.
3. Using JEI, give yourself a brine bucket.
4. Place the barrel on the ground and open its UI.
5. Add the brine bucket to the barrel, then remove the empty bucket.
6. Add the stack of 64 raw beef to the barrel.
7. Seal the barrel.
8. Wait for the brining recipe to complete.
9. Unseal the barrel.
10. Retrieve 64 brined raw beef from the item slot.

**Meta Info**
 - TFC Version: 1.7.10.168
 - JEI Version: 4.16.1.301
 - Forge Version: 14.23.5.2854
 - No other mods present

**Comment by Charnuz** [comment]
~This might have been fixed by #1692, if this was an issue~ Turns out it's still an issue

**Comment by Charnuz** [comment]
Can confirm this as a bug actually. Brining will take 125mb of brine per item in the stack, or the amount of liquid in the barrel if there is not enough liquid. The entire stack will get the Brined modifier even if there was not enough liquid for each item.
