### ISSUE TITLE
Duped/Voided Ingots in IE Assembler

### ISSUE THREAD

**Issue by RedStoner** [TerraFirmaCraft/TerraFirmaCraft#1664]
I added a filled, cooled mold into the recipe in the IE assembler. If u place the filled molds in the processing inventory, nothing happens. But, if you put in empty molds, the machine will start popping out ingots.

A similar thing happens with Logistic Pipes crafting. Though instead of getting free ingots, the machine just voids the item. 
I believe this to be happening with the way the crafting recipe for ingots from molds is being done. I don't think recipe data is being passed along to the machines to allow them to properly handle the craft.

**Meta Info**
 - TerraFirmaCraft-MC1.12.2-1.7.10.168
 - ImmersiveEngineering-0.12-98
 - logisticspipes-0.10.3.40

**Comment by eerussianguy** [comment]
Would be best if you posted the recipe you added.

**Comment by RedStoner** [comment]
I have been able to reproduce this with all filled ingot molds i have put into the machine.

**Comment by Rongmario** [comment]
It is very much a critical bug, but it is not fixable from our end, other than blocking IE out from our end which is undesirable.

**Comment by RedStoner** [comment]
Is it possible to block IE from just crafting mold recipe's? That would be better than servers having to disable the autocrafters completly.

**Comment by alcatrazEscapee** [comment]
This issue does not apply, or has been fixed in the current MC 1.18 versions of TFC, and as MC 1.12 is receiving no more development, it will be closed. If this issue arises again in 1.18, please file a new issue report.
