### ISSUE TITLE
Gold Pan not updating when used on dirt.

### ISSUE THREAD

**Issue by NE451** [TerraFirmaCraft/TerraFirmaCraft#1672]
The Gold Pan doesen't work when used on dirt, it washes up indefinitely and 3/10 times it desyncs for 30s - 1m.
I'm using the latest version of the mod downloaded on Curseforge, latest Forge build for 1.12.
I don't use any modpacks, this was on a fresh install without any other mods.

The gold pan works correctly when used on gravel and sand, only the dirt version is bugged.
I've spoken discord on the #tng-talk channel and someone was able to reproduce the issue successfully. 

**Meta Info**
 - TFC Version: 1.12.2-1.7.10.168.

**Comment by Rongmario** [comment]
Just pasting my response from Discord: 
![image](https://user-images.githubusercontent.com/3684700/105651560-1e906780-5eaf-11eb-83de-fd5ed5cc53d7.png)

Some current suggestions: seeds, loose rocks, bones.

**Comment by alcatrazEscapee** [comment]
As far as I'm aware there was no plan when this was added, it's just unimplemented.
