### ISSUE TITLE
Items dissapear when you try when you pick them from ground with Shift+V when inventory is full

### ISSUE THREAD

**Issue by pickar2** [TerraFirmaCraft/TerraFirmaCraft#1674]
Items dissapear when you try when you pick them from ground with Shift+V when inventory is full

**To Reproduce**
1. Fill inventory with something, so there are no empty slots
2. Pick up item from ground by Shift+V
3. Item dissapears, nothing drops, your inventory is not changed

**Meta Info**
 - TFC Version: TerraFirmaCraft-MC1.12.2-1.7.11.169
 - Were any other mods included? No

**Comment by Rongmario** [comment]
Confirmed and fixed
