### ISSUE TITLE
[1.12.2 Enhancement] Unsealed Barrel Recipes

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#1677]
1. What problem or issue would this enhancement solve?
The ability to implement new barrel transformation recipes with the barrel "unsealed" rather than "sealed". For those times where you want to let the environment take control rather than fermentation!
2. Describe the feature itself - what would change, what would happen. In general more detail is good!
Barrel recipes would be allowed to be created to require the recipe take place with it is "unsealed" rather than when it is "sealed".

**Comment by alcatrazEscapee** [comment]
This wouldn't add any additional capability or functionality that already isn't achievable with existing barrel recipes, and is at best, a cosmetic change for the end user. The effort to support such a cosmetic feature is not worth the headache it would create.
