### ISSUE TITLE
Trees can float in air without block underneath [11.0.49]

### ISSUE THREAD

**Issue by MsgLosers** [TerraFirmaCraft/TerraFirmaCraft#168]
[11.0.49]
Perhaps very semi-semi-semi-related to #165 ?

If a dirt block falls down from underneath a tree, say because of gravity for instance, the tree remains floating in air. Only reporting because in 1.7 you could not remove the block directly underneath a tree.

**Comment by aldo1028** [comment]
actually in 1.7 you could mine it, the tree would then slowly disappear
