### ISSUE TITLE
Misleading multiblock in guidebook entry for wrought iron

### ISSUE THREAD

**Issue by ironsnake345** [TerraFirmaCraft/TerraFirmaCraft#1680]
**Describe the bug**
Make sure to include:
There's some erroneous data in the entry for wrought iron production in the Patchouli guidebook. In the section of this entry describing the construction of the bloomery multiblock, it makes no actual description of the orientation of the bloomery hatch itself. This wouldn't be an issue, if not for the fact that the multiblock diagram shown in the book - which the player is expected to build from - explicitly shows the bloomery hatch facing inward, with the face up against the charcoal pile while the bloomery only actually works if the bloomery hatch is facing outward, with the face flush with the outside of the chimney. This should be fixed ASAP if possible, since constructing the bloomery to the specs shown in the book causes it to not work at all.

**To Reproduce**
Right click the patchouli guidebook to open. Go to advanced metalworking > wrought iron (once it is unlocked) and flip to page 5. The multiblock diagram shown there (which can also be visualized into the world) shows the bloomery hatch in the wrong orientation.

**Meta Info**
TFC version 1.7.11.169. Using the modpack "TerraFirmaCraft Reditus 2" which includes Patchouli. Obviously, without Patchouli to make the guidebook exist, this doesn't occur.

**Comment by alcatrazEscapee** [comment]
This issue does not apply, or has been fixed in the current MC 1.18 versions of TFC, and as MC 1.12 is receiving no more development, it will be closed. If this issue arises again in 1.18, please file a new issue report.
