### ISSUE TITLE
Intense LAG in singleplayer world

### ISSUE THREAD

**Issue by TsplayerT** [TerraFirmaCraft/TerraFirmaCraft#1681]
I'm not sure what's going on but it seems to me that the freeze and delay of the response time of the local singleplayer server is due to some calculation of the mod in this excerpt:

```
[Server thread/INFO] [tfc]: Calendar Time = 969839 (3839), Player Time = 3572, World Time = 3841, doDaylightCycle = true, ArePlayersLoggedOn = true
[Server thread/INFO] [tfc]: Calendar is behind by 2 ticks, jumping calendar time to catch up
[Server thread/INFO] [tfc]: World time and Calendar Time are out of sync! Trying to fix...
```
**List of mods:** [mods.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/5962163/mods.txt)
**Log file:** [latest.log](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/5962169/latest.-.Copia.log)
**Minecraft version:** 1.12.2
**TerrafirmaCraft version:** 1.12.2-1.7.11.169
**Forge version:** 14.23.5.2854

**Comment by alcatrazEscapee** [comment]
This sounds like... wait for it... you're lagging. Real shocker that one.

The short answer is that message has nothing to do with your lag. It's simply telling you "hey, you might be lagging". Looking at the log it is nowhere near prevalent enough that it would need to be to have any significant performance drop effect due to the logging overhead.

Case and point...
```
[Server thread/WARN] [net.minecraft.server.MinecraftServer]: Can't keep up! Did the system time change, or is the server overloaded? Running 2780ms behind, skipping 55 tick(s)
```

The server's telling you it's struggling, and I can promise the calendar also struggling is a symptom, not the cause.

**Comment by TsplayerT** [comment]
Can you help me discover the cause of the lag? Can you tell me which mods have the most impact?

**Comment by TsplayerT** [comment]
I added a mod called [LagGoggles](https://www.curseforge.com/minecraft/mc-mods/laggoggles) to help me find out what the problem is.
But just like in the image below as an example, it doesn't show what are the biggest causes of lag.

![image](https://user-images.githubusercontent.com/6465230/107984428-af39ff00-6fa6-11eb-8f3e-264b3117bbf4.png)

**Comment by Rongmario** [comment]
> I added a mod called [LagGoggles](https://www.curseforge.com/minecraft/mc-mods/laggoggles) to help me find out what the problem is.
> But just like in the image below as an example, it doesn't show what are the biggest causes of lag.

EnderIO is an inherent source of lag, I haven't looked into exactly why but it is.

For this type of lag, you might want to use [spark](https://www.curseforge.com/minecraft/mc-mods/spark) instead. It provides more detail.
