### ISSUE TITLE
[1.12.2] Crash when plucking a parrot

### ISSUE THREAD

**Issue by Charnuz** [TerraFirmaCraft/TerraFirmaCraft#1682]
This happens because https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/1.12.x/src/main/java/net/dries007/tfc/CommonEventHandler.java#L1065 tries to cast animals to EntityAnimalTFC when it should do IAnimalTFC, as not all entities that implement IAnimalTFC are EntityAnimalTFC such as parrots.

[log on pastebin](https://pastebin.com/YP7MBfCN)
[crash log file](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/5977424/crash-2021-02-14_03.57.02-server.txt)

**Meta Info**
 - TFC Version: 1.12.2-1.7.11.169
 - Haven't tried without LagGoggles since its in the stacktrace but I dont think its related

**Comment by Rongmario** [comment]
Confirmed and fixed
