### ISSUE TITLE
Rare case, thirst UI doesn't update [11.0.49]

### ISSUE THREAD

**Issue by MsgLosers** [TerraFirmaCraft/TerraFirmaCraft#169]
[11.0.49]

In rare cases the thirst UI doesn't update. Mentioned to @alcatrazEscapee in chat.

I entered Creative mode once during play, but this happened multiple times after this and a relog didn't correct it.

Also when thirsty the player takes hunger-damage... :sadface:

**Comment by alcatrazEscapee** [comment]
Hunger damage is intentional. The UI sounds like a sync issue, I'll look into that
