### ISSUE TITLE
Breaking a sealed barrel resets the time it was sealed

### ISSUE THREAD

**Issue by Flaksmith** [TerraFirmaCraft/TerraFirmaCraft#1691]
Noticed this a while ago but didn't see anyone bring it up, just seal and break any barrel and it won't remember the time it was sealed.

This isn't just a visual bug, it resets the timing of recipes as well.

Semi-related but as of the latest update the text displays incorrectly with certain recipes such as preserving in vinegar, might be the length of the text causing it to wrap.

**Comment by Rongmario** [comment]
Confirmed.

**Comment by Flaksmith** [comment]
This bug is still happening in 172, after doing some tests the date now resets to the time the barrel was broken.
![2021-02-28_16 33 55](https://user-images.githubusercontent.com/46166245/109432097-2b3f3880-79e4-11eb-9877-3403ce237877.png)
![2021-02-28_16 33 58](https://user-images.githubusercontent.com/46166245/109432104-309c8300-79e4-11eb-9866-73646f645f24.png)
![2021-02-28_16 34 21](https://user-images.githubusercontent.com/46166245/109432106-34300a00-79e4-11eb-9f5a-731b837ff976.png)
