### ISSUE TITLE
Sugar Cane recipe gives incorrect amount of sugar

### ISSUE THREAD

**Issue by Flaksmith** [TerraFirmaCraft/TerraFirmaCraft#1692]
In JEI the recipe for sugar calls for 5 Canes and 600mb of water to make 1 piece of sugar, but when you actually do it you get 5 sugar instead. Which recipe is supposed to be the correct one?

**Comment by Rongmario** [comment]
Tested and the correct amount (1) is outputted.

Are you playing a modpack that perhaps modified the recipe?

**Comment by Flaksmith** [comment]
I'm playing 170 with no modpack.

Here's the recipe in jei which is like what you're getting
![2021-02-20_18 51 35](https://user-images.githubusercontent.com/46166245/108610099-87cfa180-73ad-11eb-985a-0d81f37b6665.png)


this is what I get with 15 sugar cane and a full barrel of water
![2021-02-20_18 51 08](https://user-images.githubusercontent.com/46166245/108610093-81412a00-73ad-11eb-901d-85059f24b4eb.png)

**Comment by Rongmario** [comment]
Confirmed, this will only occur when there are more than 1 set of inputs.

**Comment by Charnuz** [comment]
It also consumes the required amount of liquid per item in the stack.
