### ISSUE TITLE
Wood Ash artwork looks like sawdust 

### ISSUE THREAD

**Issue by drhaber** [TerraFirmaCraft/TerraFirmaCraft#1695]
The artwork for `<tfc:wood_ash>` 
<img width="38" alt="Screen Shot 2021-02-19 at 12 38 57 PM" src="https://user-images.githubusercontent.com/56454522/108540651-72744d80-72af-11eb-98da-b70a64b6559b.png">

Looks like it is meant to be sawdust instead of Wood Ash

**Comment by eerussianguy** [comment]
TFC doesn't even add sawdust?

**Comment by drhaber** [comment]
it does not but the art work for ash pictured in the original post when compared to the sawdust art of other mods it is very ambiguous and further clashes with the conceptual color of ash vs sawdust

where ash would be more grey with black particulates 
![wood-ash-uses](https://user-images.githubusercontent.com/56454522/108548011-3fcf5280-72b9-11eb-805b-74803c12927c.jpg)

Saw dust is more of the brown tan color 
![download](https://user-images.githubusercontent.com/56454522/108548117-6097a800-72b9-11eb-8643-80e476389251.jpeg)
