### ISSUE TITLE
Saplings not dropping

### ISSUE THREAD

**Issue by Simmareth** [TerraFirmaCraft/TerraFirmaCraft#1696]
Having cleared several chunks worth of tree ;eave with bare hands, scythe, and knife, I have yet to get a sapling drop since the 12.2.58 update.  Additionally, when clearing saplings planted prior to the update to make way for a building, all saplings broken disappeared.  

Addendum - Lack of saplings occurs on an SSP world generated prior to patch, and on a server map also generated prior to patch.  A fresh ssp map is yielding sapling when leaves are broken.

**Comment by Rongmario** [comment]
I'm sorry, where did you get this `12.2.58` update? Our latest right now is `1.7.12.170`

**Comment by Simmareth** [comment]
Oh damn, typed in the modpack version.  My apologies.

**Comment by alcatrazEscapee** [comment]
This issue does not apply, or has been fixed in the current MC 1.18 versions of TFC, and as MC 1.12 is receiving no more development, it will be closed. If this issue arises again in 1.18, please file a new issue report.
