### ISSUE TITLE
Underground caveins occur randomly while walking on surface [11.0.49]

### ISSUE THREAD

**Issue by MsgLosers** [TerraFirmaCraft/TerraFirmaCraft#170]
[11.0.49]

Underground caveins can be heard randomly while walking on the surface. Similarly, you can sometimes see surface-blocks fall in the distance as chunks load in. This would also affect issue #168 as blocks under trees could fall down on their own when they shouldn't.

**Comment by alcatrazEscapee** [comment]
Surface blocks falling is not a bug - it happens occasionally when blocks are updated, i.e. from grass attempting to spread. Cave-ins should definitely not be occurring - however I am fairly convinced that any cave ins you are hearing are just soil blocks, which make a similar sound, as I can't hear any whatsoever.

**Comment by alcatrazEscapee** [comment]
This was likely caused by gravel falling, as prior to #182 it was using the stone sound instead of the dirt sound, resulting in it sounding like a cave in. I have heard surface blocks falling and that is working as intended.
