### ISSUE TITLE
A config to exclude specific trees from dropping saplings.

### ISSUE THREAD

**Issue by ufospiral** [TerraFirmaCraft/TerraFirmaCraft#1701]
This config would be a blacklist to exclude specific trees from dropping saplings, and would allow players or modpack makers to control what trees drop saplings. This would include sequoia and I think kapok by default.

**Meta Info**
 - TFC Version: 1.7.12.170 (at time of request)
 - This would be an enhancement for TFC alone

**Comment by eerussianguy** [comment]
A code solution would be ideal, but since you need a mod to add trees (as far as I'm aware) you can cancel the drops using the proper Forge event.

**Comment by eerussianguy** [comment]
Possible in 1.18 with datapacks
