### ISSUE TITLE
Hide scraping has targeting problem

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1705]
When a hide is scraped, the scraped location on the 4x4 grid is lower by a few pixels from the location the player looks at.

**Meta Info**
 - TFC Version: latest
 - Seen in TNFC modpack, but have noticed it for a while

**Comment by Gaelmare** [comment]
Two examples. The right-click was performed at the location pointed at in the screenshots, but the section of hide closer to the player was scraped.
![2021-03-24_21 10 06](https://user-images.githubusercontent.com/58122689/112413354-a9da7d80-8ce5-11eb-85bb-36d06525e902.png)
![2021-03-24_21 09 40](https://user-images.githubusercontent.com/58122689/112413357-aa731400-8ce5-11eb-9544-1e1b92920ce8.png)

**Comment by eerussianguy** [comment]
Should have been closed in #1774
