### ISSUE TITLE
Trying to run a server with terrafirmacraft

### ISSUE THREAD

**Issue by MehcaWolf** [TerraFirmaCraft/TerraFirmaCraft#1706]
I've installed TFC 1.12.2 into my own forge and the servers forge and mod folder but when running the server only runs the hud and other aspects but the main features of the mod such as the rocks and unable to break trees without an axe or even drinking water was unavailable .

**Comment by jklw10** [comment]
are you sure the world type is TFC CLASSIC?

**Comment by alcatrazEscapee** [comment]
From our FAQ:

> How do I get TFC world generation on a server?
In server.properties, You need to set the level-type to tfc_classic. Alternatively, you can delete both the world folder, and server.properties, and launch the server again - TFC will set the correct level type.
