### ISSUE TITLE
Crash with PMMO, Chunk protection tick causing chunk loading (?)

### ISSUE THREAD

**Issue by jklw10** [TerraFirmaCraft/TerraFirmaCraft#1707]
**To Reproduce**
Attention to detail is important!
probably something to do with the mod performant?

crash report
https://pastebin.com/gXGeNqP6

logs after crash report. someone from PMMO side said that based on this the crash was on your side.
https://pastebin.com/qAXS3K0D

**Comment by alcatrazEscapee** [comment]
Looks like the only thing I can see wrong on our side is that the `ChunkData.get()` call should be blocked by a loaded chunk check, it really shouldn't be forcing chunks to load. Otherwise I cannot see anything on our side that's fixable.
