### ISSUE TITLE
Undead-horse-riding skeletons spawned from lightning try to use their maces like bows

### ISSUE THREAD

**Issue by ooooonnnnn** [TerraFirmaCraft/TerraFirmaCraft#1713]
**To Reproduce**
Wait for a lightning to spawn a group of horse mounted skeletons

**Meta Info**
 - TFC Version: 1.7.14.172

**Comment by eerussianguy** [comment]
Would just be solved by #1676

**Comment by alcatrazEscapee** [comment]
This'll be "fixed" by not fixing it.

**Comment by eerussianguy** [comment]
That's the way we do it around here
