### ISSUE TITLE
Food rots in FTB Quests

### ISSUE THREAD

**Issue by Exzept1on** [TerraFirmaCraft/TerraFirmaCraft#1714]
**Describe the bug**
Food Rots in FTB Quests, quests.

**To Reproduce**
1. Install TFC
2. Install FTB Quests
3. Create quest with TFC food
4. Waiting...
5. Foods roots

**Meta Info**
 - TFC Version: 1.7.14.172
 - FTB Quests 1.12.2 - 9.0.15
 - Forge 2855

**Comment by alcatrazEscapee** [comment]
See #1651, #458
