### ISSUE TITLE
Only black unfired vessels can be reverted into clay balls

### ISSUE THREAD

**Issue by Charnuz** [TerraFirmaCraft/TerraFirmaCraft#1717]
Black unfired vessels are the only dyed vessel that can be uncrafted

**Meta Info**
 - TFC Version: 1.7.14.172

**Comment by eerussianguy** [comment]
Seems to be the recipe ceramics/unfired_clay_recycle/vessel_glazed specifies a meta of 0. Would probably be fixed by removing the data specification?

**Comment by Charnuz** [comment]
Just tested that and the crafting helper seems to throw an exception? :/

com.google.gson.JsonParseException: Missing data for item 'tfc:ceramics/unfired/vessel_glazed'
