### ISSUE TITLE
Temperature and Rainfall Compatible with Vanilla

### ISSUE THREAD

**Issue by Woody-0w0** [TerraFirmaCraft/TerraFirmaCraft#1730]
**Describe the request**
Make sure to include:
1. Temperature and Rainfall Compatible with Vanilla Biome
2. make Other dimensions Vanilla biome can grow crops and fruit trees

**Meta Info**
 - TFC Version: latest
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
   compatibility feature for Vanilla
 - If necessary, what other mods (including versions) would this require?
   Any mods provide new dimensions

**Comment by Woody-0w0** [comment]
eg:
if (rainfall == 0){
rainfall = biome raining possibility*400;
temperature = tfctemperature +biometemperature -20;}

**Comment by alcatrazEscapee** [comment]
Nope. Feel free to write this compat layer as an addon, we're not going to support using tfc outside the tfc world type.
