### ISSUE TITLE
Boars don't drop items when killed with thrown javelins

### ISSUE THREAD

**Issue by ooooonnnnn** [TerraFirmaCraft/TerraFirmaCraft#1734]
**To Reproduce**
Kill a boar/deer/coyote only by throwing javelins at them.

**Meta Info**
 - TFC Version: 1.7.16.174

**Comment by Charnuz** [comment]
Can't replicate this. Since only adults drop items, was it an adult? Could be a mod conflict

**Comment by ooooonnnnn** [comment]
Hmm, I didn't know that... possibly they weren't adults, and the triple coincidence seemed like a bug.
