### ISSUE TITLE
Wooden Barrels can pickup non-whitelisted fluids

### ISSUE THREAD

**Issue by Charnuz** [TerraFirmaCraft/TerraFirmaCraft#1738]
For example, you can use an empty barrel to pick up lava source blocks. This does not actually fill the barrel, but does destroy the fluid block, allowing you to clear an area of non-whitelisted fluids very quickly. Barrels probably shouldn't be able to pick up non-whitelisted fluids.

Note: if the raycast hits a block it will just place the barrel instead of picking up the fluid

**Meta Info**
 - TFC Version: 1.7.17.175
 - No other mods required

**Comment by alcatrazEscapee** [comment]
This issue has been fixed in the current MC 1.18 versions of TFC - understanding that the tag is a replacement for the whitelist.
