### ISSUE TITLE
Can not pick up placed items with an item in the offhand

### ISSUE THREAD

**Issue by ooooonnnnn** [TerraFirmaCraft/TerraFirmaCraft#1739]
**To Reproduce**
1. Place down a small vessel or two with v
2. Hold torches in your offhand
3. Try to pick up one of the vessels

**Meta Info**
 - TFC Version: 1.7.17.175

**Comment by Charnuz** [comment]
Minecraft forces you to use your offhand item when you shift right click, not sure if this can be fixed.

**Comment by alcatrazEscapee** [comment]
This issue has been fixed in the current MC 1.18 versions of TFC.
