### ISSUE TITLE
"doSeasons" config?

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#1742]
**Describe the request**
1. What problem or issue would this enhancement solve?
Allow the ability to disable seasons changing (not disable seasons themselves), this would allow locking the world into one specific season.

**Meta Info**
 - TFC Version: 1.12.2-1.7.17.175 (at time of request)

**Comment by eerussianguy** [comment]
would be more appropriate as a config for disabling monthly temp. Don't feel awesome about changing stuff in the climate classes (don't want to break something)

**Comment by UnlimatedStone9** [comment]
I don't think that would help with my intentions. The idea was to keep a single season in place throughout the entire ingame year, disabling monthly temp, by the sounds of it, would essentially remove seasons as a whole.

**Comment by alcatrazEscapee** [comment]
There isn't a good way to go about this beyond existing workarounds.

- Disabling the calendar achieves this (`/gamerule doDaylightCycle false`) at the expense of daytime.
- Setting the number of days per month to a maximum value integer effectively guarantees the month will never change, and hence the season, while preserving the day/night cycle
- Any other solution which allows both days and months to progress, while expecting the season to stay the same, is ignoring the reality of the situation that seasons *are* months, are used in many places, and trying to decouple what a month is from what the season is complicated. It's also worsened by the fact that a lot of mechanics rely on the fact that months (seasons) change, such as doing updates modulo a year.
