### ISSUE TITLE
Crash during world gen in 16.x `ConcurrentModificationException`

### ISSUE THREAD

**Issue by KyleDavidE** [TerraFirmaCraft/TerraFirmaCraft#1747]
**Describe the bug**
Crash during world gen in 16.x

[crash-2021-03-27_22.26.32-server.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/6216856/crash-2021-03-27_22.26.32-server.txt)
[crash-2021-03-27_22.38.07-server.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/6216857/crash-2021-03-27_22.38.07-server.txt)

**To Reproduce**
1. Load up a creative world and fly around for a bit

**Meta Info**
 - TFC Version: 1.16.5-dev

**Comment by KyleDavidE** [comment]
For the record I was able to fix it locally by just replacing the HashMap in `ChunkDataCache` with a `ConcurrentHashMap` but I'm out of my depth with concurrent java so I don't know if that is the best way to fix this.

**Comment by KyleDavidE** [comment]
Was able to replicate on #1727 

[crash-2021-03-28_14.48.26-server.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/6217875/crash-2021-03-28_14.48.26-server.txt)

**Comment by eerussianguy** [comment]
This is something meant for discord. If it is something that needs to be fixed, it can be addressed that way. Clay was wrong in telling you to put a report here.

The last thing we need is to start supporting a version of the mod that is not released, is not stable, and is not meant for end users. We also don't need you going and testing *incomplete pull requests* for us. You choosing to go out of your way to build the mod and 'test' it for us is just silly. If I were to file a bug report for every bug in 1.16 there would be a whole tracker full of them.
