### ISSUE TITLE
food stacking key dupe bug

### ISSUE THREAD

**Issue by agilmore2** [TerraFirmaCraft/TerraFirmaCraft#1751]
1. Split a stack of at least two food items and put part of it in the player crafting grid
2. note that an output appears.
3. Hover over the remaining stack in inventory, and press the stack food key.
4. The food in the crafting grid gets pulled out and stacked, yet the output is still valid.
5. Grab the food in the crafting output slot and put into player inventory.

**Meta Info**
 - TFC Version: build 175
 - TFC alone, also tested in TNFC

**Comment by koenigstag** [comment]
Build 176 has the same duplication bug. 

Crafting output slot in player's inventory has a food item, even when food ingredients are gone after stacking then to other food in the inventory.
Grabbed food from crafting output slot is a valid item and is not an visual bug.
