### ISSUE TITLE
Unable to place clays items

### ISSUE THREAD

**Issue by diamondpumpkin** [TerraFirmaCraft/TerraFirmaCraft#176]
TFC: v0.11.0.49
Forge: 1.12.2-14.23.5.2768 (Stable)

Running a server and unable to place clay items. This was fixed in v0.8.2.44 but it appears to be back.

**Comment by alcatrazEscapee** [comment]
1) Do you see any error messages in either the server log or the client log when you try and place an item?
2) Confirm you are using the place item key bind and not just right clicking?

**Comment by diamondpumpkin** [comment]
1. There are no logs in either client or server.
2. I can confirm my place item bind is right click.

I also noticed this does not work on single player either. I also installed the latest (forge-1.12.2-14.23.5.2838) version of forge, no luck. I had a couple of client side mods (Xaeros Minimap & Optifine), removing those didn't fix it. I'll keep poking around the forge versions.

**Comment by alcatrazEscapee** [comment]
Does it work with a key instead of right clicking? May be a conflict of interactions with right click.

**Comment by diamondpumpkin** [comment]
No, I tried it with keys instead, still nothing.
