### ISSUE TITLE
Changing age parameters causes previously spawned animals to despawn

### ISSUE THREAD

**Issue by DanteTorn** [TerraFirmaCraft/TerraFirmaCraft#1760]
**Describe the bug**
Setting I:elder=X to 0 does not disable animals as intended, it makes them despawn, although for some reason mules are the only animal that isn't affected.
Only adults despawn. Random juveniles made while spamming a spawn egg remain. Wild animals that don't age are also not affected (due to not having that option at all).

**To Reproduce**
1. Make a TFC world and spawn animals in it.
2. Exit Minecraft.
3. Set I:elder=X to I:elder=0
4. Load up Minecraft, go into world.
5. All adult animals except mules and wild will despawn immediately. Any spawned in manually will also despawn immediately.
6. Exit Minecraft.
7. Set I:elder=X to I:elder=100
8. Load up Minecraft, go into world.
9. Animals spawned in will function as normal.

**Meta Info**
 - TFC Version: 1.7.18.176
 - Running TechNodeFirmaCraft modpack. Also tested clean install running only Forge and TFC with same results. Same version of TFC is used in both the modpack and clean installs.

**Comment by eerussianguy** [comment]
From what I can tell much of the stuff old age and lifecycle is initialized on entity spawning. So when you change the old date after spawning the animal, you're going to cause lots of weird behavior (like despawning). There's nothing that tells livestock to despawn (this should never happen) but IIRC forge removes erroring entities.

Basically to fix this you would need some way to synchronize config changes with all entities in world. As with most things related to changing how the game operates while you're playing it, its going to be almost impossible to fix properly. So unless someone can find a fix I'm going to close this for now
