### ISSUE TITLE
Make Liquid Metals Poor Faster Depending On Temperature.

### ISSUE THREAD

**Issue by MalekiRe** [TerraFirmaCraft/TerraFirmaCraft#1780]
Something that would increase immersion and give a better sense of how stuff turns from liquid into solid, would to increase the flow rate of for example, putting a clay mold into a vessel, and the rate at which metal liquid is emptied into it is determined by temperature, not any super crazy variation, but I feel having stuff flow really fast when its brilliant white, and semi-slow when its about to turn solid really would improve the feel.

**Comment by MalekiRe** [comment]
If you give me the go ahead, ill fork this and make the change.

**Comment by eerussianguy** [comment]
Bring this up in discord please

**Comment by eerussianguy** [comment]
Closed via discord discussion unless a good proposal comes up
