### ISSUE TITLE
Crash with  1.7.19.177 version and Dynamic Trees

### ISSUE THREAD

**Issue by Tavarnarmo** [TerraFirmaCraft/TerraFirmaCraft#1783]
Hello, that's a weird one. After actualisation to newest version of TFC (1.7.19.177) in all of my worlds every time when dynamic trees tree is either burning or cut down there is a crash, crash report here https://gist.github.com/Tavarnarmo/84ce3b4cb539d84d9e32fd4d03217026.

**Comment by Charnuz** [comment]
This isn't caused by TFC, and I wasn't able to reproduce this. Possibly needs more information.

**Comment by eerussianguy** [comment]
Report this to DynamicTreesTFC, we don't maintain that mod.

It might be an interaction with @Rongmario 's mod since IIRC that's the one that messes with BakedQuads

**Comment by Rongmario** [comment]
It's a LoliASM issue: https://github.com/LoliKingdom/LoliASM/issues/17, already reported. It's also not an interaction with neither TFC or DynamicTreesTFC but with Dynamic Trees itself.

**Comment by Gaelmare** [comment]
Looks like using Optifine is a workaround according to that linked bug?

**Comment by Rongmario** [comment]
> Looks like using Optifine is a workaround according to that linked bug?

Nah, its just LoliASM currently checks if Optifine exists and disables the `squashBakedQuads` module automatically. The temp fix is to disable `squashBakedQuads` module.
