### ISSUE TITLE
Crash when added to mod pack

### ISSUE THREAD

**Issue by HatcheryRoosters** [TerraFirmaCraft/TerraFirmaCraft#1791]
This happened when the mod was added to my pack, latest version.
[crash-2021-06-19_00.07.21-client.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/6679987/crash-2021-06-19_00.07.21-client.txt)

If there is a mod that must be taken out, I hope it's an unnecessary one

**Comment by alcatrazEscapee** [comment]
You have too many blocks registered (hint: TFC adds a lot). Either install the mod Just Enough IDs, or remove mods until you're under the limit. This is a fundamental Minecraft limitation, nothing do here.
