### ISSUE TITLE
Removing Ingots from a multi-block tall stack of Ingots may break the stack of Ingots.

### ISSUE THREAD

**Issue by LegionBreaker** [TerraFirmaCraft/TerraFirmaCraft#1792]
**Describe the bug**
When the player removes an Ingot from a stack of Ingots and it reduces the number of block spaces taken up by the stack _(IE reduce size from 65 to 64, or 129 to 128 Ingots)_ the game will break/destroy the block-container for the stack of ingots at the point in which the player right-clicked it. It should break the top-most block-container (which no longer contains any Ingots and therefore should no longer exist), but it instead breaks the block the player right-clicked to remove the ingot - resulting in the game dumping 2+ stack of Ingot entities on the ground.

**To Reproduce**
Example 1:
1) Place down 65 Ingots of any type in a single pile/stack. (this creates a full block worth of the Ingots in a stack, and a single Ingot in the block space above it).
2) Right-click the bottom (full-block if Ingots) to remove an Ingot from the stack.
- What happens: You pick up 1 Ingot. The bottom stack breaks, dropping 64 Ingot entities on the ground.
- What I expect to happen: You pick up 1 Ingot.

Example 2:
1) Place down 129 Ingots of any type in a single pile/stack. (this creates two full blocks worth of the Ingots in a stack, and a single Ingot in the block space above those).
2) Right-click the middle block of ingots to remove an Ingot from the stack.
- What happens: You pick up 1 Ingot. The middle stack breaks, dropping 64 Ingot entities on top of the bottom stack of 64 Ingots.
- What I expect to happen: You pick up 1 Ingot.

Notes:
I technically noticed this while playing TNFC 1.12.2 several weeks ago, but this seemed like a TFC:TNG bug as it happened with the vanilla TFC ingots. I retested the bug today with just Forge mod loader and the latest release version of TFC:TNG I could find on the CurseForge website.

**Meta Info**
 - TFC Version: 1.7.19.177
 - Were any other mods included? - No
 - Can you reproduce it without these other mods? - Yes
 - If necessary, what other mods (including versions) MUST be present to experience the bug? - N/A
 
 ~LegionBreaker

**Comment by eerussianguy** [comment]
Debatable whether this is a bug but it's possible to fix, someone would just have to rewrite the breaking logic to check and self-insert from the above stacks. Though the stacks may not always match in which case we're opening a bit of a can of worms. Someone can feel free to take a crack at this

**Comment by eerussianguy** [comment]
936d62b
