### ISSUE TITLE
Creatures in the RespawnableCreatures config do not respawn or spawn from eggs

### ISSUE THREAD

**Issue by AnodeCathode** [TerraFirmaCraft/TerraFirmaCraft#1793]
Creatures in the RespawnableCreatures config do not respawn ever. Nor do they spawn when a spawn egg is clicked in compatible conditions. 

Make sure to include:
1. What did you expect to happen? Bears continue to terrorize the server
2. What actually happened instead (i.e. what was the bug) The server becomes much less terrifying

**To Reproduce**
Attention to detail is important!
1. Do 'Play and kill all the bears'
2. Then do 'Wait until the heat death of the universe for new bears to spawn.

This does work in 1.7.11.169 and prior. Since the .170 version (which added @DisasterMoo [Livestock respawning](https://github.com/TerraFirmaCraft/TerraFirmaCraft/pull/1665/files)) it's been broken.

**Meta Info**
 - TFC Version: TerraFirmaCraft-MC1.12.2-1.7.19.177
 - Were any other mods included? Can you reproduce it without these other mods? Done in bare TFC instance.

**Comment by alcatrazEscapee** [comment]
This issue does not apply, or has been fixed in the current MC 1.18 versions of TFC, and as MC 1.12 is receiving no more development, it will be closed. If this issue arises again in 1.18, please file a new issue report.
