### ISSUE TITLE
there is a java.lang.nullpointerexception in the most recent edition of terrafirmacraft. I am not sure what causes it, and it seems like vanilla fix doesn't know what mod is causing the crash at all. but I have determined that terrafimacraft is the cause 

### ISSUE THREAD

**Issue by TerraCraft** [TerraFirmaCraft/TerraFirmaCraft#1798]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
2. What actually happened instead (i.e. what was the bug)
3. If it was a crash, upload the full log file (`latest.log`)
4. If they would help to explain the issue, include screenshots

**To Reproduce**
Attention to detail is important!
1. Do '...'
2. Then do '...'

**Meta Info**
 - TFC Version: 0.X.X.XX
 - Were any other mods included? Can you reproduce it without these other mods?
 - If necessary, what other mods (including versions) MUST be present to experience the bug?

**Comment by eerussianguy** [comment]
We need actual info. Try reading the issue template:

Describe the bug
Make sure to include:

    What did you expect to happen?
    What actually happened instead (i.e. what was the bug)
    If it was a crash, upload the full log file (latest.log)
    If they would help to explain the issue, include screenshots

To Reproduce
Attention to detail is important!

    Do '...'
    Then do '...'

Meta Info

    TFC Version: 0.X.X.XX
    Were any other mods included? Can you reproduce it without these other mods?
    If necessary, what other mods (including versions) MUST be present to experience the bug?

**Comment by alcatrazEscapee** [comment]
This is a pointless issue without more details.
