### ISSUE TITLE
I really like the way the ingots are placed on the ground in this Mod!!!

### ISSUE THREAD

**Issue by Emperorsking** [TerraFirmaCraft/TerraFirmaCraft#1813]
This Mod places metal ingots on the ground, which makes me feel very immersive while playing, but I have to install TFC every time I want to use this feature. Most of the time, I don't want to play TFC survival mode, I wish I could separate this feature out and make it a Mod, any suggestions? What should I do?

**Comment by alcatrazEscapee** [comment]
> I wish I could separate this feature out and make it a Mod, any suggestions?

The code is here and EUPL, go nuts. But, really not a TFC issue... at all.

**Comment by AlyceOsbourne** [comment]
Also, Stackie exists
