### ISSUE TITLE
Possible Bug: Surface rocks/sticks/twigs generate underwater

### ISSUE THREAD

**Issue by kotoroshinoto** [TerraFirmaCraft/TerraFirmaCraft#1815]
In TerraFirmaCraft-Forge-1.17.1-2.0.1-alpha.jar, these surface items are present underwater as well as on the ground above water.

I couldn't tell if this was intentional or not, but it doesn't hurt to report it.

**Comment by alcatrazEscapee** [comment]
Yup, that's why they're waterlogged!

**Comment by kotoroshinoto** [comment]
I thought that might be the case, but you never know, there could be a general code for waterlogging things
