### ISSUE TITLE
Conflict with Fluidlogged API [1.12.2]

### ISSUE THREAD

**Issue by Lylythii** [TerraFirmaCraft/TerraFirmaCraft#1818]
**Describe the bug**
Fault is no-doubt on TFC's end, felt I should report it to both.

Fluidloggable blocks cannot be fluidlogged with TFC fluids using TFC buckets.
Attempting to fluidlog a block using TFC fresh/salt/hot water or Vanilla water, using a TFC bucket, will delete the block/replace it with the fluid.
[doesn't appear to occur with other TFC fluids like limewater or molten metals]

**To Reproduce**
- Place a fluidloggable block.
- Take a TFC bucket & attempt to fill said block. [block will be placed on the side of the block, rather than in the block]

- Place a fluid.
- Place a fluidloggable block inside that fluid.
- Attempt to fill said fluidlogged block with a TFC fluid. [block will be repalced]

**Expected behavior**
- Blocks should not be replaced.
- Fluids from TFC buckets should place inside fluidloggable blocks.

**Video**
https://youtu.be/tBRzlzhcj1I

**Comment by Lylythii** [comment]
https://github.com/jbredwards/Fluidlogged-API/issues/37

**Comment by alcatrazEscapee** [comment]
This issue does not apply, or has been fixed in the current MC 1.18 versions of TFC, and as MC 1.12 is receiving no more development, it will be closed. If this issue arises again in 1.18, please file a new issue report.
