### ISSUE TITLE
Data on ceramic vats cannot be saved

### ISSUE THREAD

**Issue by ghost** [TerraFirmaCraft/TerraFirmaCraft#1824]
Server Version: 1.12.2
Mod Version: 1.7.21.179
Situation:Don't know why, some players use small ceramic cylinder can't save the data, such as open a small ceramic cylinder GUI to put items inside, close the GUI data doesn't seem to save, when once again open the small ceramic cylinder GUI is empty inside, when the ceramic have items under the condition of small cylinder, the player can infinite small cylinder inside take out items,After taking out the item, close the GUI, and then open the GUI small VAT. The item inside is still inside, and there is no error in the background, so I can't know what happened.

**Comment by alcatrazEscapee** [comment]
This issue does not apply, or has been fixed in the current MC 1.18 versions of TFC, and as MC 1.12 is receiving no more development, it will be closed. If this issue arises again in 1.18, please file a new issue report.
