### ISSUE TITLE
1.18.x Salt Lick Generation

### ISSUE THREAD

**Issue by vvvv-vvv** [TerraFirmaCraft/TerraFirmaCraft#1833]
Salt licks have priority during generation resulting in floating trees.
I am not sure how big this issue is as I have not found many instances of it appearing (just two) while exploring the world.
Example:
![2021-12-29_21 36 36](https://user-images.githubusercontent.com/70375142/147701722-1c5c012a-91fe-4b7b-aeae-c300e18c9155.png)

**Comment by alcatrazEscapee** [comment]
They ([among others](https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/f963e2fb8987fcd3febd01d95574590cb6a6c21b/resources/world_gen.py#L638-L642)) need a [`decorate_air_or_empty_fluid()`](https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/f963e2fb8987fcd3febd01d95574590cb6a6c21b/resources/world_gen.py#L965) added.
