### ISSUE TITLE
1.18.x Fallen Tree Generation

### ISSUE THREAD

**Issue by vvvv-vvv** [TerraFirmaCraft/TerraFirmaCraft#1834]
Fallen trees can generate with just 1 block of contact, this creates these peculiar structures:
![2021-12-29_21 49 38](https://user-images.githubusercontent.com/70375142/147703858-7cb8bb25-b861-49d0-8220-64f74e4ac5c5.png)

![2021-12-29_21 42 26](https://user-images.githubusercontent.com/70375142/147703918-8f234e69-f02b-4c57-8232-f155e0a75b62.png)

**Comment by alcatrazEscapee** [comment]
Should probably have a flat enough decorator for extreme cases, but this is otherwise intentional (as it does in some cases create interesting terrain such as a log bridging a ravine or river)
