### ISSUE TITLE
1.18.x Oceanic Biome Vegetation Generation

### ISSUE THREAD

**Issue by vvvv-vvv** [TerraFirmaCraft/TerraFirmaCraft#1835]
The Oceanic biome set does not generate any vegetation (this happens basically 100% of the time I encounter an oceanic type biome).

Example:
![2021-12-29_22 11 44](https://user-images.githubusercontent.com/70375142/147703982-e5bc7fb9-0510-4d13-88c4-91c5baf98862.png)

**Comment by alcatrazEscapee** [comment]
I could've sworn I fixed this already in a different version...

**Comment by vvvv-vvv** [comment]
> 

Yes, you have, I guess the ocanic biomes are just really fussy
