### ISSUE TITLE
Placed items don't carry through Save & Quit (1.18.x)

### ISSUE THREAD

**Issue by billyma6** [TerraFirmaCraft/TerraFirmaCraft#1845]
When I placed my vessels with ore down in my pit and save & exited before lighting the fire, after loading back into the world the items vanished, and /data tells me the block only has block id "tfc:placed_item" with no data of what items they were.

**Comment by billyma6** [comment]
Just checked, none of my items I placed onto the ground with V saved.

**Comment by alcatrazEscapee** [comment]
Ah, I think this is due to the switch from `save` to `saveAdditional` in 1.18, I forgot to check that before the recent build.
