### ISSUE TITLE
HarvestCrash

### ISSUE THREAD

**Issue by HatcheryRoosters** [TerraFirmaCraft/TerraFirmaCraft#1847]
What do I do about this

[crash-2022-01-06_20.26.37-client.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/7825669/crash-2022-01-06_20.26.37-client.txt)

It says Harvest Craft did it, what do I do?

**Comment by alcatrazEscapee** [comment]
```
java.lang.RuntimeException: Invalid id 4096 - maximum id range exceeded.
```

You have too many blocks, either remove some or add a mod that removes the ID limit.
