### ISSUE TITLE
(SUGGESTION) Return of old TFC animals

### ISSUE THREAD

**Issue by HatcheryRoosters** [TerraFirmaCraft/TerraFirmaCraft#1848]
TFC has been missing some animals from 1.12.2 (I'm not sure if they appeared at all) So maybe bring them back so TNG players like me can enjoy them: Buffalo, Bison, Reindeer, Bass, Trout, Wahoo, Pollock, Ibex, Warthog, Zebra, Peccary, Bighorn Sheep, White Tailed Deer, Elk

**Comment by alcatrazEscapee** [comment]
Yes 1.18.x is incomplete.

**Comment by HatcheryRoosters** [comment]
I'm a 1.12.2 player
