### ISSUE TITLE
Alloys not mixing properly in crucible (1.18)

### ISSUE THREAD

**Issue by atticcat** [TerraFirmaCraft/TerraFirmaCraft#1852]
![image](https://user-images.githubusercontent.com/96800193/148803107-5bc339e5-4687-4fba-b669-5b57670ab45f.png)

I haven't tried with a pit kiln to see if there's the same issue, but at least in the crucible, alloys don't seem to be outputting - I just get unknown metal, even though this matches the recipe json exactly.

**Comment by eerussianguy** [comment]
For some reason this is because we have multiple instances of the same metal floating around, causing them to not be equal during comparisons. Stay tuned
