### ISSUE TITLE
Remaining vanilla animals

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#186]
Most animals from 1.7.10 have been ported to 1.12.2. There are still some animals awaiting having their TFC mechanics ported, as well as some animals added to vanilla in versions beyond 1.7.10 that could be adapted to work in TFC.

List:
- Wolves (1.7.10 TFC feature)
- Horses (1.7.10 TFC feature)
- Squid (1.7.10 TFC feature)
- Donkeys (I'm not sure how these were handled)
- Mules (Also not sure)
- Ocelots/cats (Existed during 1.7.10, but were not utilized)
- Rabbits (1.8 vanilla feature)
- Polar bears (1.10 vanilla feature)
- Llamas (1.11 vanilla feature)
- Parrots (1.12 vanilla feature)

Also, some vanilla mobs added beyond 1.12.2 could be integrated into the mod in 1.14 builds and beyond:
- Cod (1.13 vanilla feature)
- Salmon (1.13 vanilla feature)
- Pufferfish (1.13 vanilla feature)
- Tropical fish (1.13 vanilla feature)
- Turtles (1.13 vanilla feature)
- Dolphins (1.13 vanilla feature)
- Pandas (1.14 vanilla feature)
- Foxes (1.14 vanilla feature)
- Ostriches (1.15+ vanilla feature)
- Meerkats (1.15+ vanilla feature)

**Comment by alcatrazEscapee** [comment]
This is a suggestion, not an issue, and as such fits better on our discord server. The remaining 1.7.10 animals are already noted.
