### ISSUE TITLE
Crucible math not matching up (1.18.x)

### ISSUE THREAD

**Issue by billyma6** [TerraFirmaCraft/TerraFirmaCraft#1860]
When I melted down 4 pieces of poor bismuthinite (each 25mB) to get an ingot, I poured it into an ingot mold and ended up with 99mB inside the mold despite the crucible also saying 100mB when melted.

**Comment by billyma6** [comment]
Also, stacked ores of the same type still only count as one item instead of all in the stack. 2 tetrahedrite (30mB of copper) melts into only 15mB of copper.

**Comment by eerussianguy** [comment]
Confirmed that melting is adding up incorrectly. The other bit is that crucibles mistakenly do not limit the stacksize to 1 as they should, which will be fixed.
