### ISSUE TITLE
Crash (1.18.1)

### ISSUE THREAD

**Issue by billyma6** [TerraFirmaCraft/TerraFirmaCraft#1868]
Was playing the new update firing some fire clay bricks in a pit kiln then got this crash
[crash-2022-01-20_14.50.18-client.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/7908972/crash-2022-01-20_14.50.18-client.txt)
.

**Comment by alcatrazEscapee** [comment]
Downgrade your Forge version (39.0.20 will work), this is a Forge breaking change in https://github.com/MinecraftForge/MinecraftForge/pull/8235
