### ISSUE TITLE
Trees Don't Drop All Their Logs

### ISSUE THREAD

**Issue by Whhyymee** [TerraFirmaCraft/TerraFirmaCraft#1870]
Sometimes trees don't drop all the logs shown. For example, A maple tree made of four logs didn't drop any while using a stone ax. Another example is a Chesnut tree with 6 logs only dropped two when cut down with a stone ax. This happens most times but not always. Sometimes the trees drop the appropriate amount of logs but it's mostly inconsistent.

I'm playing on TerraFirmaCraft-MC1.12.2-1.7.21.179

**Comment by alcatrazEscapee** [comment]
Stone axes are not as effective as metal ones.
