### ISSUE TITLE
Some crafting recipes use unobtainable vanilla blocks (1.18.x)

### ISSUE THREAD

**Issue by billyma6** [TerraFirmaCraft/TerraFirmaCraft#1873]
The recipe for the quern, handstone, and composter all use vanilla items: vanilla stone for the quern and handstone, and vanilla dirt for the composter, meaning that they aren't craftable using dirts from TFC since no vanilla dirt or stone spawns.

**Comment by eerussianguy** [comment]
I think the raw stones are missing the #minecraft:stone tag

However the composter uses #minecraft:dirt which we do populate so I'm not sure on that one. I'll have to check
