### ISSUE TITLE
Snow/ice not melting under blocks (1.18.x)

### ISSUE THREAD

**Issue by billyma6** [TerraFirmaCraft/TerraFirmaCraft#1874]
Snow layers and icicles that formed during winter underneath blocks where there was shade from the sun didn't melt at all, even when /tfc climateChunkUpdate was used. Snow on the surface didn't seem to melt either, unless it was nearby a heat source like a lit firepit or forge.

**Comment by billyma6** [comment]
For ex, there is still snow underneath a house I built despite the ambient temperature now being 13.8 degrees C

**Comment by alcatrazEscapee** [comment]
> Snow layers and icicles that formed during winter underneath blocks where there was shade from the sun didn't melt at all

*At the moment* this is intentional, due to a rework of the way snow melting works to be based on local chunk ticks, rather than random ticks (and as a result, basically less laggy).

> Snow on the surface didn't seem to melt either

This, I cannot reproduce, surface snow melted fine in my tests.
