### ISSUE TITLE
Anvil doesn't auto select recipe and shows ghost forging progess [1.12.2-1.7.22.180]

### ISSUE THREAD

**Issue by evan345** [TerraFirmaCraft/TerraFirmaCraft#1878]
Did some forging in the *.180 release and noticed that...

- The anvil wouldn't automatically select the recipe when only one recipe was possible. 
              **Test case:** when finishing some high carbon black steel and some high carbon blue steel.
- The anvil shows forging progress even when you have removed the ingot from the anvil. And even if you put a new fresh ingot into the anvil, the anvil doesn't update. It still shows the previously selected recipe and the forging progress of the previous ingot.
              **Test case:** Making some gold lamps, worked on one ingot till it got to cold. Removed the ingot, the UI didn't change, Then put a fresh ingot in, still no change on the UI. Trying to work the fresh ingot had no effect till I reselected the lamp recipe and then when I started working on the new ingot, the UI finally updated, showing the new forging progress.

Note: both these things work as expected in *.179

**Comment by eerussianguy** [comment]
5a652dfd9260818540a1e5957278b4fafff9cc98
