### ISSUE TITLE
Calling stack.getCapability with IItemSize throws ClassCastException due to illegal capability instance with Advanced Rocketry

### ISSUE THREAD

**Issue by eagleyes005** [TerraFirmaCraft/TerraFirmaCraft#188]
Sometimes when you try TFC with other mods and it does not recognize which item size give to him the game just crash.

Here is the log:
[crash-2019-07-19_12.24.14-client.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/3413108/crash-2019-07-19_12.24.14-client.txt)

**Comment by eagleyes005** [comment]
This problem seems to be with new AR version, not TFC.

**Comment by alcatrazEscapee** [comment]
I'm fairly confident that the issue is on Astral Sorcery's side here. That said, I've been unable to reproduce this so I can't say for sure.

**Comment by eagleyes005** [comment]
AR devs confirmed to me that the problem is with TFC. When the mod tries to give to Advanced Rocketry space suit an item weigh.

Btw i don't have Astral Sorcery in my pack.

**Comment by eagleyes005** [comment]
![a](https://user-images.githubusercontent.com/47163423/61582135-443ff200-aafd-11e9-8c98-12c7c4efd943.png)

**Comment by alcatrazEscapee** [comment]
Yeah, I meant Advanced Rocketry. TFC doesn't assume that any item has a special size - it attaches a capability. If AR's space armor has a problem with that then it's not a TFC issue.

**Comment by Silfryi** [comment]
Also: Side note: Only Z devs, I moderate the discord and help with issues when I can.

**Comment by eagleyes005** [comment]
Ok, sorry. I thought you are a Dev. Since you answered my question.

**Comment by alcatrazEscapee** [comment]
For reference: <https://github.com/zmaster587/AdvancedRocketry/issues/1639>

**Comment by alcatrazEscapee** [comment]
See https://github.com/TerraFirmaCraft/TerraFirmaCraft/issues/962#issuecomment-610999478, and https://github.com/TerraFirmaCraft/TerraFirmaCraft/issues/962#issuecomment-613004519
