### ISSUE TITLE
Apply For Reprint in MCBBS

### ISSUE THREAD

**Issue by HeartyYF** [TerraFirmaCraft/TerraFirmaCraft#189]
Due to the language barrier, many in China have no idea what things are happening here, so I want to reprint this mod in Chinese. Certainly I won't provide download, only redirect them to here.
This may help increase the fame of this mod, and may attract some potential developers.

**Comment by dries007** [comment]
Go ahead, you can also help us with a translation if you want. But not yet, we will setup a system for translations and other things like artwork soon.
Please link to here (GitHub) for more info and CurseForge for downloads.

**Comment by HeartyYF** [comment]
I've pulled a second request to TFC-Assets repo about updating zh_cn.
