### ISSUE TITLE
Material softness issues [1.18.2 Alpha 2.0.11-12]

### ISSUE THREAD

**Issue by KittenRaee** [TerraFirmaCraft/TerraFirmaCraft#1894]
All materials are too easy to destroy by hand comparatively to 1.12 version.
For example you can punch down solid rock in 10 seconds in 1.18 vs 70 seconds in 1.12. While this doesn't yield resources from stone as tool requirement is still a thing; increased softness in materials makes shovel in particular a skippable tool, as you can punch piece of soil faster than you could've mined it even with a stone shovel in previous version.

1.18 rock breaking
https://user-images.githubusercontent.com/23376922/158066746-b74ef013-80da-45d0-a4be-011930bd0cd7.mp4

1.12
https://user-images.githubusercontent.com/23376922/158066876-48499236-4f1e-48d8-a1ed-806a5dafc53e.mp4

1.18 dirt digging by hand
https://user-images.githubusercontent.com/23376922/158066907-44eb88c9-94ad-4ddc-8f28-7f4905333194.mp4

1.12
https://user-images.githubusercontent.com/23376922/158066909-01f88abb-da24-45a4-ad0f-c5ff60423254.mp4

**Comment by Charnuz** [comment]
Wrong issue, can't remove from the timeline due to a github issue

**Comment by alcatrazEscapee** [comment]
A lengthy diagnostic of what occurred between these two versions. In short:

- All tools got weaker, and lower tier tools significantly so.
- All blocks used much closer to vanilla hardness values, which were significantly lower than TFC's defaults.

The remedies for these were to (mostly) revert these changes:

- Tools remained toned town a bit (to bring values closer to vanilla), but lower tier tools were buffed comparatively.
- Many blocks got their hardness raised.

```
=== 1.12 Analysis ===


RockCategory.hardness = [1.4, 1.6]

Block.hardness = [
  BlockRockVariant = Type.factor * RockCategory.hardness
  BlockPlanksTFC = 2.0
  BlockLogTFC = 2.0
  BlockLogTFC (natural) = 5.0
]

Type.factor = [
  BRICKS, RAW, SMOOTH = 1
  COBBLE = 0.75
  SAND = 0.05
  DIRT = 0.15
  GRAVEL, CLAY, GRASS = 0.2
]

ToolMaterial.efficiency = [
  ROCK = [6, 7]
  COPPER = 8
  BRONZE = [9, 11]
  IRON = 12
  STEEL = 14
  BLACK_STEEL = 16
  COLORED_STEEL = 18
]

BreakSpeedEvent.modifier = [
  BlockRockVariant = 1 / 10
  BlockLogTFC = 1 / 7.5
]

=== 1.18 Analysis ===

RockCategory.hardness = [-0.4, 0.2]

Block.hardness = [
  DIRT, CLAY, SAND = 0.5
  GRASS = 0.6

  LOG = 2.0
  LOG (natural) = 2.0 * pi
  PLANKS = 2.0

  RAW = 2 + RockCategory.hardness
  BRICKS = 2.0
  COBBLE, SMOOTH = 1.5
  GRAVEL = 0.8
]

Tier.speed = [
  STONE = [2.5, 3.0]
  COPPER = 4.5
  BRONZE = [5.5, 6.5]
  IRON = 8.0
  STEEL = 9.5
  BLACK_STEEL = 11
  COLORED_STEEL = 12
]

=== 1.12 -> 1.18 Comparison / Remedy ===

// Ratio of old efficiency / new speed
Tier.efficiencyToSpeed [
  STONE ~ 2.35
  COPPER ~ 1.7
  BRONZE ~ [1.6, 1.7]
  IRON ~ 1.5
  STEEL ~ 1.5
  BLACK_STEEL ~ 1.45
  COLORED_STEEL ~ 1.5
]

// Adjust so that all tools are down by ~1.5 from 1.12 values
// Effectively a buff for lower tier tools in 1.18
Tier.speed = [
  STONE [2.5, 3.0] -> [4.0, 4.7]
  COPPER 4.5 -> 5.25
  BRONZE [5.5, 6.5] -> [6, 7.3]
]

// New block hardness values are modified from 1.12, but scaled down by ~1.5x
// This is to line up with the new (weaker vs. 1.12) tools
Block.hardness = [
  SAND = [0.7, 0.8] -> 0.5

  DIRT = [2.1, 2.4] -> 1.5
  GRAVEL, CLAY, GRASS = [2.8, 3.2] -> 2.0

  COBBLE = [10.5, 12] -> [6.5, 7.5]
  BRICKS, RAW, SMOOTH = [14, 16] -> [8.5, 9]

  LOG = 8
  LOG (natural) = 16
  PLANKS = 1.5
]

```
