### ISSUE TITLE
Jarring biome borders (1.18.2 Alpha 2.0.12)

### ISSUE THREAD

**Issue by vvvv-vvv** [TerraFirmaCraft/TerraFirmaCraft#1903]
Worlds generate with sharp, geometric, jarring biome borders.

Expected: more flowing (not straight lines) or blended biome transition
![2022-03-18_16 09 51](https://user-images.githubusercontent.com/70375142/159029831-e2866206-1cd8-4c57-bef5-e30a50f92c29.png)
s

**Comment by alcatrazEscapee** [comment]
N.B.
Worlds will continue to generate with sharp, generally geometric biome borders. And they already do, in many more places than this. It is in this sense, an artifact of our biomes being blended so well, over such a long distance, that local variations in the biome are smoothed out into this large scale straight-ness. The solution is to, like most other biome specific terrain generation, hide the artifacts with local variation and smoothing, in this case, by feathering the edge of the badlands sand transition. Straight lines are still visible yet on a much smaller scale.
![2022-04-16_15 20 35](https://user-images.githubusercontent.com/35673674/163689016-ea05ee30-c8b9-49fe-a790-04e183cba0ce.png)
![2022-04-16_15 19 38](https://user-images.githubusercontent.com/35673674/163689018-106b137c-639f-46a0-8eeb-b24bb9501fee.png)
