### ISSUE TITLE
Empty blocks generate in bodies of water (1.18.2 Alpha 2.0.12)

### ISSUE THREAD

**Issue by vvvv-vvv** [TerraFirmaCraft/TerraFirmaCraft#1904]
Worlds are generating empty blocks in rivers (and possibly other bodies of water)
![2022-03-18_16 17 20](https://user-images.githubusercontent.com/70375142/159030555-7bc3f1d4-eaa2-42a5-8a46-38bd94d0ee02.png)

**Comment by eerussianguy** [comment]
Places this happens:
- above underwater grass
- above loose rocks
- above kelp
- above loose rocks/underwater grass that is underneath of a floating plant

Notably this never happens without some kind of decoration

**Comment by alcatrazEscapee** [comment]
a0698c8a46f95fb838f2ffa85be5c6e88e9b4380
