### ISSUE TITLE
Old growth tree generation (1.18.2 Alpha 2.0.12)

### ISSUE THREAD

**Issue by vvvv-vvv** [TerraFirmaCraft/TerraFirmaCraft#1905]
Old growth trees can generate in precarious positions such as this:
![2022-03-19_17 45 01](https://user-images.githubusercontent.com/70375142/159130344-617fccc3-66a6-4a16-8713-ec3abfc0d5f1.png)

Most of the time with grass decoration placed where I would imagine the trunk would terminate normally.

**Comment by alcatrazEscapee** [comment]
This is known, and applies not only to old growth trees, but any trees without a 1x1 footprint (the only block that is checked is immediately below).
