### ISSUE TITLE
Improving equines (SUGGESTION)

### ISSUE THREAD

**Issue by HatcheryRoosters** [TerraFirmaCraft/TerraFirmaCraft#1906]
Necessarily speaking, I believe these would be great ideas
First, I believe that having more donkey and mule varieties would broaden them up a bit! The horse markings are their own texture, making it possible to put them on donkeys and mules as seen in the two images below.
![2022-03-19_18 20 15](https://user-images.githubusercontent.com/36781707/159140640-c5f02d2e-511a-41ff-90cf-d1473530ab4d.png)
![2022-03-19_18 20 29](https://user-images.githubusercontent.com/36781707/159140641-8aac8adb-c1ae-448e-9a85-10872da1c114.png)

Another thing I'd like to point out is that only a male donkey (jack) and a female horse (mare) can make a mule. Breeding a female donkey (jenny) and a male horse (stallion) will make a hinny. So in my opinion, it would be nice to see Hinnies in Minecraft.

**Comment by alcatrazEscapee** [comment]
This kind of suggestion is better suited to our discord's #suggestions channel, rather than our issue tracker.
