### ISSUE TITLE
Various torch issues [1.18.2 Alpha 2.0.13]

### ISSUE THREAD

**Issue by KittenRaee** [TerraFirmaCraft/TerraFirmaCraft#1913]
Torches on the ground drop nothing while broken, while wall torches drop a stick.

Wall torches reset orientation to face North when burned out.

Default torch burning value is 7200 (someone ate a 0?). Also comment in config states 72 000 ticks is one in-game hour.

Only wall torches respect burnout values, ground torches burn out by random tick when reignited (between 1 and ~50 seconds).

**Comment by Charnuz** [comment]
Working on a fix for these
