### ISSUE TITLE
Log Piles placed against other Log Piles destroys one log [1.18.2 Alpha 2.0.13]

### ISSUE THREAD

**Issue by KittenRaee** [TerraFirmaCraft/TerraFirmaCraft#1914]
Log piles are created empty and waste one Log if placed against another log pile.

https://user-images.githubusercontent.com/23376922/160152106-e33f503d-dfbe-4aa3-8cab-af40d1a5fc06.mp4

There are also various issues immediately after loading into the game, among others: stack size for logs is 32, sticks cannot be placed in campfires. After reloading save by quitting to menu and entering a world again, those issues are resolved

**Comment by eerussianguy** [comment]
I do wonder if we can write a game test for this, probably not since it's right click interaction

**Comment by alcatrazEscapee** [comment]
It should be possible with a fake player, provided we just place and trigger the right functions. Depends how much of the player interaction we need to verify (placing blocks should be testable, opening gui probably not)

**Comment by eerussianguy** [comment]
We have decided that the charcoal behavior works as intended, however it shouldn't get destroyed by dirt.
