### ISSUE TITLE
Floating plants can render underwater

### ISSUE THREAD

**Issue by Charnuz** [TerraFirmaCraft/TerraFirmaCraft#1917]
Happens when the water underneath the plant adjusts its height to meet water coming from above. Vanilla lily pad for comparison
![image](https://user-images.githubusercontent.com/16440978/160277889-df290da1-1162-4897-86fc-8692142b896b.png)

**Comment by eerussianguy** [comment]
Looked into this and there's no good way of fixing this. We cannot override getOffset anymore as that method moved to BlockStateBase, and i'd rather not do an expensive check anyway

**Comment by eerussianguy** [comment]
Model needs to be higher.
