### ISSUE TITLE
Stick bunch becomes single torch in firepit [1.18.2 Alpha 2.0.15]

### ISSUE THREAD

**Issue by madflavius** [TerraFirmaCraft/TerraFirmaCraft#1926]
Stick bunch becomes only a single torch in the firepit.

**REPRO:**

1. Start new world with no mods.
2. Place firepit, place logs, set alight with firestarter.
3. Place stick bunch into fire slot.
![image](https://user-images.githubusercontent.com/28602240/162290761-3f9c519c-2886-4c80-a8be-4a65bd0922b3.png)

4. Stick bunch becomes single torch.
![image](https://user-images.githubusercontent.com/28602240/162290831-ef4a8f7f-8f09-462e-9f5b-c2c86dbd69e3.png)

*If this is intended behavior please disregard. It is dissimilar from pre 1.18+ versions where 1 stick -> 1 torch.*

**Comment by alcatrazEscapee** [comment]
Can't reproduce post #1927, likely was resolved as well.
