### ISSUE TITLE
Cannot place sticks or stick bundles into firepit to make torches [1.18.2 Alpha 2.0.15]

### ISSUE THREAD

**Issue by madflavius** [TerraFirmaCraft/TerraFirmaCraft#1927]
Neither individual sticks or stick bundles can be crafted into torches at a firepit. The slot does not accept the stick or stick bundle.

**REPRO:**
1. Start new world with no mods.
2. Place firepit, place logs, set alight with firestarter.
3. Attempt to place stick bundle or single stick into the fire slot.

Failed with both left click (while holding full stack), right click (single item from a full stack), or single stick/stick bundle held in hand.
![image](https://user-images.githubusercontent.com/28602240/162291447-f8b63362-f64a-4cf4-b5dd-1b30c79a195e.png)

**Comment by alcatrazEscapee** [comment]
Fixed by 1499274b4973017a221c37dc0c9590254c367039
