### ISSUE TITLE
(Multiplayer) Players can't connect to LAN world  [1.18.2 Alpha 2.0.15] 

### ISSUE THREAD

**Issue by madflavius** [TerraFirmaCraft/TerraFirmaCraft#1929]
An attempt to play the new version of TFC on a LAN failed when players attempted to join. Single player works fine, but on both newly created worlds for 2.0.15, and existing worlds, players attempting to join over LAN join and immediately error out with the following message:

` [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: [PLAYER_NAME] lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "net.dries007.tfc.common.recipes.outputs.ItemStackModifier$Serializer.toNetwork(net.dries007.tfc.common.recipes.outputs.ItemStackModifier, net.minecraft.network.FriendlyByteBuf)" because the return value of "net.dries007.tfc.common.recipes.outputs.ItemStackModifier.serializer()" is null`

REPRO:

1. Create new world in single player with default settings with no additional mods.
2. Open to LAN.
3. Direct connect from second computer to host.
4. Error occurs on load.

**Comment by madflavius** [comment]
Closed per discussion in discord re: lack of support for Forge for "Open to LAN" functionality.

**Comment by alcatrazEscapee** [comment]
Confirmed occurs on dedicated servers as well.
