### ISSUE TITLE
Many blocks should be waterloggable but are not (1.18.2 Alpha 2.0.15)

### ISSUE THREAD

**Issue by vvvv-vvv** [TerraFirmaCraft/TerraFirmaCraft#1933]
![2022-04-15_15 13 23](https://user-images.githubusercontent.com/70375142/163575068-34f30e99-0346-4260-9974-12dab73b6511.png)

It should be waterloggable.

**Comment by eerussianguy** [comment]
Going to turn this into a kind of collector issue for things people want to be waterloggable and we think are reasonable to be waterloggable.

Currently we will have to make leaves waterloggable, because of 1.19
