### ISSUE TITLE
Crash due to "Invalid id 4096 - maximum id range exceeded." - Just Enough IDs

### ISSUE THREAD

**Issue by Nitrouille** [TerraFirmaCraft/TerraFirmaCraft#1939]
Hello,

When I launch Minecraft without the mod, everything works fine (so the crash comes from this mod)
When I launch my modpack with TerraFirma :
- I get this in latest.log : https://pastebin.com/0CzmNbFW
- And this in my crash report : https://pastebin.com/ZnyH5dCM

Could you help me asap please ?

Thanks a lot

**Comment by alcatrazEscapee** [comment]
You have too many blocks. Remove some mods that add blocks, or use the mod "Just Enough IDs" which removes the maximum block limit.

**Comment by Nitrouille** [comment]
What's the block limit ?

**Comment by KingofDogeII** [comment]
I installed just enough ids but now it crashes instantly and it says this crash may have been caused by invalid java runtime configuration.
