### ISSUE TITLE
Satiety is not consumed after loading applecore (1.12)

### ISSUE THREAD

**Issue by SakuraWuhen** [TerraFirmaCraft/TerraFirmaCraft#1943]
Hello! After repeated verification, I found that after loading 1.12 TFC and applecore at the same time, the satiety of survival will not be consumed. Since our server is very dependent on hunger reform, I would like to try to ask the authors if they have any clues on this, thank you!

applecore：https://www.curseforge.com/minecraft/mc-mods/applecore

**Comment by alcatrazEscapee** [comment]
This issue does not apply, or has been fixed in the current MC 1.18 versions of TFC, and as MC 1.12 is receiving no more development, it will be closed. If this issue arises again in 1.18, please file a new issue report.
