### ISSUE TITLE
[1.18.2] Predators sleep cycles get messed up

### ISSUE THREAD

**Issue by Therighthon** [TerraFirmaCraft/TerraFirmaCraft#1954]
I've noticed while testing predators that what time of day they sleep seems to vary based on when I spawn them in, rather than just what time of day it is. Often I'd have groups of predators I spawned in at the same time all going to sleep at the same time of day, and other groups of the same type of predator but spawned in at a different time that would be awake at different times. And not just some where nocturnal some were diurnal, they could go to sleep and wake up at any hour of the day, not just dawn and dusk.

**Comment by eerussianguy** [comment]
I may have fixed this in the last commit. The sleeping value was being serialized incorrectly

**Comment by eerussianguy** [comment]
have not seen this pop up in a long time.
