### ISSUE TITLE
[1.18.2] Dry Springs?

### ISSUE THREAD

**Issue by Alex33212** [TerraFirmaCraft/TerraFirmaCraft#1966]
Not entirely certain if this even is a bug or not, but in TFC 1.18.2-1.2.2 I've found a couple of "hot springs" that don't have any spring water (or lava) in them. Screenshots:

![2022-05-29_00 22 47](https://user-images.githubusercontent.com/13616305/170858373-f3a013b3-ab1a-4398-a6f2-f6cc53caddf4.png)
![2022-05-29_00 23 58](https://user-images.githubusercontent.com/13616305/170858378-b8c9e789-e9aa-4708-a3b0-b1698b8a643d.png)

**Comment by alcatrazEscapee** [comment]
Yes, dry springs appear in geologically less active areas.
