### ISSUE TITLE
[1.18.2] Springs replacing trees

### ISSUE THREAD

**Issue by Alex33212** [TerraFirmaCraft/TerraFirmaCraft#1972]
In 1.18.2-2.0.25, it's possible for hot springs to replace parts of trees with their stone.
![2022-05-30_20 57 07](https://user-images.githubusercontent.com/13616305/171090046-3ccfa793-7652-4691-a591-332eb5a7f959.png)
.

**Comment by alcatrazEscapee** [comment]
After extensive research, and flying around in terrain that looks like this...

![2023-10-31_22 36 36](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/35673674/86a10d2a-abf7-4a5c-a389-06f70e239223)

...trying to reproduce, I've only found this rare fossilized tree an elusive mystery, nowhere to be found! A freak coincidence, a chance of nature, and something to be treasured, not feared! And with this came a newfound respect for this rare occurrence. Who am I, but a developer, to say this is a bug? Is it not, in essence, the purest form of a feature? An esoteric creation, calling from above, to preserve the almighty stone trees found only when the wandering traveler desires them to be found? Why, it would be a travesty to even begin to _think_ about brutally restricting these marvels until only the plain, reductive, disappointing, dissatisfied generation remains. To tear away the mystery and excitement of the marveled fossil tree until but nothing remains but a spec of dust on a empty monitor screen as the millionth tree is once again cut down and the land is barren and unalive.
