### ISSUE TITLE
[1.18.2] Water jugs used on river water nullify flow

### ISSUE THREAD

**Issue by Alex33212** [TerraFirmaCraft/TerraFirmaCraft#1973]
In 1.18.2-2.0.25, filling a jug with the flowing part of a river causes that block to be replaced by non-flowing water.
![2022-05-30_17 58 05](https://user-images.githubusercontent.com/13616305/171090201-5935be56-b548-4fcd-9855-857a5323a60c.png)
.

**Comment by neumann-lukas** [comment]
I think that there is a bigger underlying problem. Rivers always generate new still "normal" water sources, this can be observed every time a flowing block is replaced (So it applies to buckets and normal block placing too).
