### ISSUE TITLE
[1.18.2] Wild 2 tall plants do not get harvested if only the top part is broken (in survival only)

### ISSUE THREAD

**Issue by vvvv-vvv** [TerraFirmaCraft/TerraFirmaCraft#1975]
Here is an example of a partially broken Wild Sugarcane plant. This is also the case for all 2 block tall food plants.
![2022-05-31_17 01 59](https://user-images.githubusercontent.com/70375142/171208582-1c3dec13-944b-4fea-84fa-100691b56cab.png)

**Comment by Matz-42** [comment]
This is still at thing in beta 2.1.10

Should probably be reopened.
