### ISSUE TITLE
[1.18.2] Sandwiches craft as rotten

### ISSUE THREAD

**Issue by Alex33212** [TerraFirmaCraft/TerraFirmaCraft#1977]
In 1.18-2.0.25, when crafting a sandwich, the end product is rotten despite all ingredients being good.
![image](https://user-images.githubusercontent.com/13616305/171310363-2071bdb1-dffb-489d-ae5d-dbc11bb35f40.png)

**Comment by alcatrazEscapee** [comment]
Can you get a log, and look for a line that looks something like this, and tell me what the `{}`s are?

```
Options: Assertions Enabled = {}, Boostrap = {}, Test = {}, Debug Logging = {}
```

**Comment by Alex33212** [comment]
`[01Jun2022 11:02:10.872] [modloading-worker-0/INFO] [net.dries007.tfc.TerraFirmaCraft/]: Options: Assertions Enabled = false, Boostrap = false, Test = false, Debug Logging = true`
