### ISSUE TITLE
server problem

### ISSUE THREAD

**Issue by BrainsII** [TerraFirmaCraft/TerraFirmaCraft#1998]
I created a server on Aternos and there was a pier TerraFirmaCraft but when starting the server on the server, the normal generation and not the mod, then I found out that I need to enter the name of the generation of the mod PLEASE SAY THE NAME OF THE GENERATION OF THE WORLD FASHION

**Comment by alcatrazEscapee** [comment]
This issue tracker is not used for support requests, if you have further questions please inquire in our discord.

That said, in 1.12 the level-type is `tfc:classic` and in 1.18 `tfc:tng`.
