### ISSUE TITLE
[1.12.2] Crafting table tops, when placed, display as a solid colour which I assume should be an overlay, while in the inventory they are correct

### ISSUE THREAD

**Issue by kurocat471** [TerraFirmaCraft/TerraFirmaCraft#1999]

**Comment by eerussianguy** [comment]
Send a photo

**Comment by kurocat471** [comment]
![2022-06-21_13 32 18](https://user-images.githubusercontent.com/74220178/174872962-429a942b-80e6-4690-af6b-d6074a017ea9.png)
See the placed pine workbench compared to the one in my hand

**Comment by eerussianguy** [comment]
Hm weird

**Comment by alcatrazEscapee** [comment]
This issue has been fixed in the current MC 1.18 versions of TFC.

**Comment by kurocat471** [comment]
@alcatrazEscapee has this also been fixed in 1.12.2 or just in the 1.18.X versions?

**Comment by eerussianguy** [comment]
No fix is coming for 1.12
