### ISSUE TITLE
Vessel content doesn't show unless taken out and put in again; Food expiry date changes randomly; Using Beehive kiln to make food gets improper number

### ISSUE THREAD

**Issue by HeartyYF** [TerraFirmaCraft/TerraFirmaCraft#200]
Vessel doesn't show its content unless taken out and put in again
![1](https://user-images.githubusercontent.com/17660052/61684399-f5d46280-ad4b-11e9-9f51-8e8d2492309f.jpg)
![2](https://user-images.githubusercontent.com/17660052/61684403-f79e2600-ad4b-11e9-82d3-ff2dceb08434.png)
When the metal is melted, vessels won't show instantly, unless being taken out and put in again.

Food expiry date changes randomly
![3](https://user-images.githubusercontent.com/17660052/61684476-24523d80-ad4c-11e9-9a64-cfbd4e219e1e.png)
![4](https://user-images.githubusercontent.com/17660052/61684477-24523d80-ad4c-11e9-91a2-20555d540f51.png)
Clicking on food makes its expiry date changes.

Using Beehive kiln to make food gets improper number
Even if you put 5 raw pork into it, you will only get one cooked pork. Besides, when right-side bar is full, you'll get nothing and pork disappears.

**Comment by alcatrazEscapee** [comment]
Please make a separate issue for each bug report.
