### ISSUE TITLE
[1.18.2] Cannot open workbenches gui

### ISSUE THREAD

**Issue by MrKRew02** [TerraFirmaCraft/TerraFirmaCraft#2011]
With new tag system I can craft vanilla crafting table and it works, so I can use it. But gui of custom wood workbenches from tfc doesn't work anymore.
build: 1.18.x-2.0.31-alpha

**Comment by alcatrazEscapee** [comment]
Was fixed by 1c67761b07e7acad48ad1c986725162f9f534de1
