### ISSUE TITLE
Feature request: Additional APIs like Season

### ISSUE THREAD

**Issue by Eonasdan** [TerraFirmaCraft/TerraFirmaCraft#2020]
Could you add some additional apis to 1.18 like getting the current season? Other temp data would be cool as well.

Also, could you pub the 1.18 release to CF please? I have a small modpack I'm playing with family.

Thanks

**Comment by alcatrazEscapee** [comment]
Please discuss with us on our [discord](https://discord.gg/PRuAKvY) with the specific nature of your API requests.
