### ISSUE TITLE
Game Crash Immediately After Startup, No Other Mods Present

### ISSUE THREAD

**Issue by Derpercoaster** [TerraFirmaCraft/TerraFirmaCraft#2021]
I am using version 1.12.2-1.7.23.181 of the mod. I have no other mods installed, but the game crashes immediately and presents exit code:1.

I know there are other issues here that are similar to mine, but the solutions suggested in those do not work for me.

Crash Report: [fml-crash-2022-07-27_20.44.28.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/9204767/fml-crash-2022-07-27_20.44.28.txt)

**Comment by alcatrazEscapee** [comment]
> Description: FML has discovered extracted jar files in the mods directory.
> This breaks mod loading functionality completely.
> Remove the directories and replace with the jar files originally provided.

pebkac
