### ISSUE TITLE
[1.18.2] Some fluids (IE) not accepted by barrel

### ISSUE THREAD

**Issue by fizechef** [TerraFirmaCraft/TerraFirmaCraft#2022]
Some fluids, notably those from Immersive Engineering, are not accepted by the barrel. Could be an issue with IE and other mods as well, but as the wooden bucket works fine, I belive its something with the barrel. Its not all modded fluids either, just some.

**Comment by alcatrazEscapee** [comment]
Both of them are controlled by tags, however in this case they are the same tag, so they shouldn't be any different. What fluids in particular, and how did you try and insert them?

**Comment by fizechef** [comment]
As far as I've tried its any fluid from IE. Creosote, Ethanol, Redstone Acid are the ones I tried. I tried inserting them using the bucketed liquid, normal buckets and tfc wooden buckets, and I tried picking up the liquid directly from the ground using the barrel. Doesn't work either way, using the bucket just places the fluid block on top on the barrel, using the barrel replaces the fluid block.

**Comment by fizechef** [comment]
I also have Create in the Modpack I'm making and the fluids from them work fine. Tried the Honey and Choclate and they work fine with both wooden bucket and barrel.

**Comment by fizechef** [comment]
Just gone back in to confirm again and using the bucket without shift just opens the barrel UI obviously.

**Comment by alcatrazEscapee** [comment]
So the issue was not that the barrel wasn't accepting fluids it should - the issue was the wooden bucket was accepting fluids it shouldn't. For future reference, both devices have a whitelist which is controlled with a tag, all of which are documented [here](https://terrafirmacraft.github.io/Documentation/1.18.x/data/tags/#fluid-tags).
