### ISSUE TITLE
TFC:TNG can not use Firestarter in Long press the right key

### ISSUE THREAD

**Issue by xlxyvergil** [TerraFirmaCraft/TerraFirmaCraft#2023]
TFC:TNG can not use Firestarter in Long press the right key
server：arclight-forge-1.18.2-1.0.6.jar
mod：TerraFirmaCraft-Forge-1.18.2-2.0.32-alpha.jar

**Comment by alcatrazEscapee** [comment]
We do not support using custom server software, as they tend and have in the past caused issues with TFC mechanics. Unless you can reproduce with a clean Forge install there's not much we can do. You may have luck reporting the issue to the server software team.
