### ISSUE TITLE
what kind of spam?

### ISSUE THREAD

**Issue by pro100andreika** [TerraFirmaCraft/TerraFirmaCraft#2028]
are you playing the game yourself? There are no animals that can be killed, or rather there are few of them. Do you know how to listen to people? I told you that there are mistakes. There are no ores on earth, very few. Crafting a bowl for washing does not work, the bowl does not extract resources for washing... Learn to listen to people, and not close your eyes!!

**Comment by alcatrazEscapee** [comment]
Completely ignoring our issue templates, and submitting a list of vague, low effort rambles, most of which either point to you using a vastly out of date version, or flat out not understanding the mod you're playing, or took the minimum amount of effort to find out more about the mod, and now sounding borderline conspiratorial and hostile - that is what classifies this as spam.
