### ISSUE TITLE
automatization in terrafirmacraft

### ISSUE THREAD

**Issue by Isaich24** [TerraFirmaCraft/TerraFirmaCraft#2029]
Hi. I would like to ask if it is planned to add the primitive devices for automatization in terrafirmacraft? I think water and wind powered devices will fit in well in the later stages of the game. For example, you can pay attention to the Create mod or Better With Mods. The game Vintage Story also has something similar.
![image](https://user-images.githubusercontent.com/111115749/184361823-dee2813e-0135-49a7-86e7-c94f4a3d9d7d.png)
![image](https://user-images.githubusercontent.com/111115749/184361987-96208e3f-5ee5-4ed9-9a80-d5dbbecc3981.png)

**Comment by alcatrazEscapee** [comment]
We use the issue tracker exclusively for bug reports, not suggestions or support requests. This post would be more suitable for our [discord](https://discord.gg/PRuAKvY)'s suggestions channel, where the conversation can continue there.
