### ISSUE TITLE
Issue Knapping, when item knapped and and attempt to put in inventory

### ISSUE THREAD

**Issue by ErikUnderwood** [TerraFirmaCraft/TerraFirmaCraft#2038]
When knapping and I attempt to put the item in my inventory if I do it too fast it will not place in my inventory. Seems to be a delay before I can do so. If I am slow it goes fine, if I go too fast though it does not register it. For version 1.18 alpha.

**Comment by eerussianguy** [comment]
There are some restrictions on what you can do with items after you knap them, this has to do with dupe glitches and unfortunately cannot be changed. If you can produce a video of what you are talking about and it shows a serious issue, then we'll take a look.
