### ISSUE TITLE
Crucible showing "Unknown Alloy" even if correct amounts are used, visual bug on Server only

### ISSUE THREAD

**Issue by fizechef** [TerraFirmaCraft/TerraFirmaCraft#2044]
Creating alloys in the crucible shows them as "unknown alloy" on MP-Servers sometimes. Happend to me when creating brass. Is just a visual bug, when extracting the metal using ingot molds it forms ingots of the correct alloy.

**Comment by fizechef** [comment]
Didn't have this issue in SP yet so I suspect its some server desync.

**Comment by alcatrazEscapee** [comment]
What were the exact steps from an empty crucible you used to create the alloy that is showing incorrectly (i.e. added X mB of Y, removed X mB..., etc.)?

**Comment by fizechef** [comment]
I used it normally to smelt some ores into ingots. I then emptied it completely. Then put 9 copper ingots in and let them smelt into molten copper, then 1 zinc ingot. It created unknown alloy with 900mb copper and 100mb zinc. I then put an ingot mold in to extract and it filled up with brass. Tried to replicate in SP and creative but wasn't able to.

**Comment by fizechef** [comment]
Bug is reproducable on my Server, just tried it.

**Comment by fizechef** [comment]
![2022-08-20_16 12 34](https://user-images.githubusercontent.com/63301315/185750527-71abcc9c-1fd1-41b0-b7e2-d4d5acbee270.png)
![2022-08-20_16 14 05](https://user-images.githubusercontent.com/63301315/185750576-a2ff30e4-5e03-4351-97e2-39ee6d2f9d57.png)
