### ISSUE TITLE
Using Forge to make food gets improper number

### ISSUE THREAD

**Issue by HeartyYF** [TerraFirmaCraft/TerraFirmaCraft#205]
Even if you put 5 raw pork into it, you will only get one cooked pork. Besides, when right-side bar is full, you'll get nothing and pork disappears.

**Comment by alcatrazEscapee** [comment]
What do you mean by the beehive kiln? A forge? A fire pit? A pit kiln?
Please explain exactly what you are doing, *in specific detail*, and what is happening.

**Comment by HeartyYF** [comment]
Sorry for that, I think it should be Forge, that's my fault and I have changed the title.
I recorded a gif to explain this.
![1](https://user-images.githubusercontent.com/17660052/61802061-6cfc1a80-ae62-11e9-8c62-c71e9a1b0be3.gif)
This also happens in fire pit.

**Comment by muzikbike** [comment]
Is "cateoryMeat" a typo?

**Comment by HeartyYF** [comment]
I think it should be categoryMeat, but sadly it's hardcoded. There are too many things hardcoded.

**Comment by alcatrazEscapee** [comment]
Yes it is a typo. But it's a bloody ore dict value. It's literally the easiest thing to tweak if you are so inclined. The meat cooking is very much a bug.
