### ISSUE TITLE
Molds not cooling down, with zero heat capacity.

### ISSUE THREAD

**Issue by alcatrazEscapee** [TerraFirmaCraft/TerraFirmaCraft#2053]
Issue report: when firing molds in a pit kiln, they won't cool down after the fact. Issue seems to be that they are saving themselves with 0 heat capacity somehow, either via a bad default or trying to calculate the heat capacity of empty.

![Image](https://cdn.discordapp.com/attachments/432527966266851339/1012081307465031710/2022-08-24_15.29.34.png)

**Comment by eerussianguy** [comment]
https://github.com/TerraFirmaCraft/TerraFirmaCraft/commit/28527f39b514ac238cafb01476dc6039978de3ab
