### ISSUE TITLE
[1.18.2] Washing bowl of soup in barrel gives vanilla bowl item back

### ISSUE THREAD

**Issue by SeriousCreeper** [TerraFirmaCraft/TerraFirmaCraft#2058]
As title says, washing a soup bowl in a barrel gives the vanilla bowl, instead of the TFC bowl. 

And a side question - would it be possible to get a config option for using vanilla bowls instead of TFC bowls? As in specifying if you get the TFC or the vanilla bowl when eating/washing soup.

Was trying to make food mods like Farmer's Delight work with TFC, but it requires the vanilla bowl to make dishes. 
Totally understand that this might be out of scope.

**Comment by alcatrazEscapee** [comment]
Washing soups in barrels will give back the bowl used to create the soup (as seen here using the [empty bowl modifier](https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/107878878ec6c9dfc5993a5c500698336e82c3b2/src/main/resources/data/tfc/recipes/barrel/clean_soup_bowl.json#L15)) Soups created from the creative inventory don't have a bowl as such and will default to returning the vanilla bowl (this causes it to display in JEI correctly)

A config option for this behavior would be counterproductive.

**Comment by SeriousCreeper** [comment]
Ooooh sorry i didn't realize that would already work with vanilla bowls, that's awesome.
