### ISSUE TITLE
No matter how much charcoal on the block,when you destroy it,you just acquire one charcoal.

### ISSUE THREAD

**Issue by hidfug** [TerraFirmaCraft/TerraFirmaCraft#208]
No matter how much charcoal on the block,when you destroy it,you just acquire one charcoal.

**Comment by DisasterMoo** [comment]
How are you trying to break it? Creative? I tried with bare hands and using shovels and couldn't reproduce it on survival.

**Comment by alcatrazEscapee** [comment]
This is an intentional behavior. When you break the block below a charcoal pile it breaks, but drops only one charcoal. It's done this way to prevent players from just breaking blocks underneath charcoal piles instead of harvesting the block layer by layer.

**Comment by muzikbike** [comment]
I think it would be better if charcoal piles acted like snow layers do on bedrock edition, but that's be a feature request.

**Comment by GreyMario** [comment]
Out of curiosity, how does that behavior interact with harvesting charcoal at the bottom of a pile that is more than one block tall? Does it cause the charcoal above to break entirely (and drop one charcoal)? I would nitpick that it should cut its way down from the top (as trees do).

**Comment by alcatrazEscapee** [comment]
Digging the bottom will remove the top off of the pile, same as 1.7.10.
