### ISSUE TITLE
Horseshoe Crab texture is missing pixels

### ISSUE THREAD

**Issue by Joe-org** [TerraFirmaCraft/TerraFirmaCraft#2098]
1)Penguins seem to unintentionally share the regeneration & resistance III factor of the tfc turtle when they hide in their shell. 
![2022-09-09_02 19 08](https://user-images.githubusercontent.com/113080914/189266900-e2bb4c36-7169-41dc-a3ad-040da8a01408.png)

2)The Horseshoe Crab has 3 untextured pixels on its side.
![2022-09-09_03 10 54](https://user-images.githubusercontent.com/113080914/189267055-8974d069-7a55-4582-be98-4de5158aff49.png)

**Comment by eerussianguy** [comment]
I could turn this off, but internally, penguins and turtles are teh same thing
