### ISSUE TITLE
Bears do not drop meat

### ISSUE THREAD

**Issue by jmdisher** [TerraFirmaCraft/TerraFirmaCraft#2103]
Bear meat was dropped in 1.12.2 and seems to be expected in 1.18.2 (referenced in game and here: https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/b6e3a079f69ba1a2bfe81200221cd3a6047aa55a/src/main/java/net/dries007/tfc/common/items/Food.java#L98).

It looks like it is missing from the corresponding loot tables.  For example, grizzly only has bone and large hide (https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/7154347e6f82d9a7ccbe40be05aea6192c619fd6/src/main/resources/data/tfc/loot_tables/entities/grizzly_bear.json) while horse includes its meat, bone, and medium hide (https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/506e2d6f4b5a0b6e1f2d70577e1c574fe28f129e/src/main/resources/data/tfc/loot_tables/entities/horse.json).

**Comment by Joe-org** [comment]
Predators in 1.18 dont drop meat anymore. This is intentional.

**Comment by jmdisher** [comment]
Not sure why that change was made (them dropping meat made sense) but I suspect my confusion was that the items still show up in JEI, even though they are not dropped in game.  It seemed conspicuously missing.

**Comment by eerussianguy** [comment]
Feel free to discuss in discord
