### ISSUE TITLE
Can't Stack Food Items While in Creative Mode Inventory

### ISSUE THREAD

**Issue by Joe-org** [TerraFirmaCraft/TerraFirmaCraft#2104]
As the title says.

**Comment by lumagatto** [comment]
you can't stack food items while in most other inventories from my experience on the test server.

**Comment by alcatrazEscapee** [comment]
This is, unfortunately, intended, to avoid unintended behavior when interacting with other mods' containers (without knowing the specifics of how their slots work, stacking food can mess up the contents of slots, and with slots that automatically populate their outputs, cause duplications or bypass restrictions). It's restricted explicitly to the player inventory. Creative mode it doesn't really matter, and the player should always be able to access their inventory. You can also always stack food via the explicit crafting recipe.
