### ISSUE TITLE
Horses getting stuck or extremely slowed down by leaves, while ridden. 

### ISSUE THREAD

**Issue by lumagatto** [TerraFirmaCraft/TerraFirmaCraft#2105]
If you dismount the horse, they move at the normal slowed down speed you get while moving through leaves.
Mostly happens when the horse can't touch the ground, i think. Sometimes the horse won't even fall down extremely slowly, it will just float indefinitely.

**Comment by alcatrazEscapee** [comment]
![good to know](https://user-images.githubusercontent.com/35673674/201218997-b3951fbb-22e0-49d7-8be6-e60ac3ef9050.png)

:shrug:
