### ISSUE TITLE
Baby Zombies spawned as chicken jockies seem to have no AI and are immune after the first hit.

### ISSUE THREAD

**Issue by lumagatto** [TerraFirmaCraft/TerraFirmaCraft#2106]
Happens on the test server 2.1.4

**Comment by alcatrazEscapee** [comment]
Cannot reproduce, zombies of all kinds exhibiting AI behaviors such as wandering, before and after punching them

**Comment by lumagatto** [comment]
![2022-09-26_00 48 25](https://user-images.githubusercontent.com/21110014/192169092-385217d3-43fa-45d2-b936-871464f74d0e.png)
