### ISSUE TITLE
Writing Errors in the TFC Field Guide under "The World" and its Chapters

### ISSUE THREAD

**Issue by Joe-org** [TerraFirmaCraft/TerraFirmaCraft#2108]
1)Under "Geology", On the page for **Continental Subduction** the (a area) line should be replaced with (an area).
![Continental Subduction AN](https://user-images.githubusercontent.com/113080914/189493859-2ee64385-999b-4a43-bb01-e3e8074c7261.jpeg)

2)Under "Ores and Minerals", All text mentioning (a ore) needs to be replaced with (an ore) instead. Stretching all the way from Native Copper, the pages in-between, to Tetrahedrite.
![Copper A Ore](https://user-images.githubusercontent.com/113080914/189494060-442546d1-bc89-4365-a8f9-053be6da3640.jpeg)
![Tetrahedrite A Ore](https://user-images.githubusercontent.com/113080914/189494061-4bde4c04-9ff0-4290-b86e-054451eb06ab.jpeg)

3)Under "Ores and Minerals", Either change the text for _Native Gold in Diorite_ with (Dacite) to match the rock type displayed for the visuals or change the cycling visuals to the Diorite Native Gold variants to match with the Diorite word used.
![Native Gold](https://user-images.githubusercontent.com/113080914/189494431-deac3d2e-c4b2-4761-a347-e9f63687c991.jpeg)

4)Under "Ores and Minerals", **Garnierite & Malachite pages** both have an extra "at" by accident.
![Nickel At At](https://user-images.githubusercontent.com/113080914/189494514-41227f55-d4a7-4c45-9c0f-710305d47a92.jpeg)
![Copper At At](https://user-images.githubusercontent.com/113080914/189494524-d8da198f-4890-4b3f-ad06-8215495f48f4.jpeg)

5)Under "Ores and Minerals", The **Limonite page** mentions malachite. This should be replaced with "limonite".
![Limonite](https://user-images.githubusercontent.com/113080914/189494633-76aab981-b9ea-44df-892e-a4cdf5987faa.jpeg)

6)Under "Wild Fruits", On the pages of both Olive Tree and Orange Tree, the a should be replaced with (an).
![An Olive Tree](https://user-images.githubusercontent.com/113080914/189494857-b4a241e9-6257-4086-aa18-31b5f402d696.jpeg)
![An Orange Tree](https://user-images.githubusercontent.com/113080914/189494860-7bafda8a-a514-41ab-943a-c595b91f7787.jpeg)

7)Under "Food and Water", The Thirst page has a typo on faster with an extra (t).
![Thirst Fastter](https://user-images.githubusercontent.com/113080914/189495024-f6334e8c-fc74-4662-8cfe-ddb63ea174e3.jpeg)

**Comment by alcatrazEscapee** [comment]
Reopening as I didn't regenerate the book assets, and need to batch it with other changes.
