### ISSUE TITLE
Avoid crash during chunk loading of NullPointerException

### ISSUE THREAD

**Issue by xxMrPHDxx** [TerraFirmaCraft/TerraFirmaCraft#211]
I tried playing with the world and crash after some time with the crash report below

[Crash Report](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/3439716/crash-2019-07-29_01.28.54-server.txt)

I suggest in the `net.dries007.tfc.world.classic.worldgen.WorldGenOreVeins.getVeinsAtChunk`, check for null entries and if `entries` did null return an empty List of Vein instead

**Comment by alcatrazEscapee** [comment]
Your suggestion doesn't actually fix the bug, which is that the weighted collection of veins shouldn't be null.

Can you please post your full log + the contents of `config/tfc/ore_spawn_data.json`

**Comment by xxMrPHDxx** [comment]
The issue was fixed

**Comment by alcatrazEscapee** [comment]
Except it's not is it, because there's evidently still a crash case when the user wants to spawn no veins.
