### ISSUE TITLE
The Bloomery can't be upgraded?

### ISSUE THREAD

**Issue by SheReyy** [TerraFirmaCraft/TerraFirmaCraft#2112]
MC: 1.18.2
Forge: 40.1.73
Mod Version: TerraFirmaCraft-Forge-1.18.2-2.1.5-beta.jar

Issue:
The Bloomery chapter mentions the fact that you can add 8 more pieces of Iron (+coal) by stacking up the chimney, two more layers of stone blocks. I've added multiple layers, but I can only add up to 24 pieces of ore. Am I missing something?

Expected behavior:
Adding two more layers of stone blocks, should allow you to add 8 more pieces of ore to the bloomery. That's if I understood everything right. If the cap of the bloomery is set to 24, then this can be closed.

![image](https://user-images.githubusercontent.com/91336389/189529222-63ad77af-7994-4adb-b8df-20dee5bfcc59.png)

In the next ss, the Molten block has 24 Charcoal and 24 Limonite pieces (20 Rich + 4 Normal). When attempting to drop 8 Charcoal and 8 Normal Limonite, they don't get added to the Molten block, so I can start the Bloomery with only 24 Pieces of ore. I'm using Smooth Marble for the whole Bloomery structure.
![image](https://user-images.githubusercontent.com/91336389/189529459-5d9f678b-0936-4a1d-8d16-9a4bf8ddc462.png)

**Comment by alcatrazEscapee** [comment]
> If the cap of the bloomery is set to 24, then this can be closed.

Eight per layer, up to 24 max.
