### ISSUE TITLE
`BananaPlantBlock` is calling deprecated `ICalendarTickable#setLastUpdateTick`

### ISSUE THREAD

**Issue by alcatrazEscapee** [TerraFirmaCraft/TerraFirmaCraft#2113]
This *likely* means that banana plants do not function correctly - not growing when loaded and only growing on `/time add` or similar time skips. Need to investigate.

**Comment by eerussianguy** [comment]
Has a user report today that bananas aren’t growing properly.

**Comment by Joe-org** [comment]
Yeah Banana Saplings still die off with good conditions for Temperature and Hydration.  **:(**
![2022-09-12_10 18 19](https://user-images.githubusercontent.com/113080914/189798076-98a2bc5d-2f45-4f93-823c-19feaf7227fe.png)
![2022-09-12_12 27 28](https://user-images.githubusercontent.com/113080914/189798094-948222d6-49c1-4238-ba89-17fbdb946d7e.png)
