### ISSUE TITLE
Hydration and Temperature Info Displayed twice on Jade specifically with all Tall Bushes.

### ISSUE THREAD

**Issue by Joe-org** [TerraFirmaCraft/TerraFirmaCraft#2114]
![2022-09-11_19 41 42](https://user-images.githubusercontent.com/113080914/189532621-80efa381-49e6-4982-b7bf-bc2a622c887e.png)

**Comment by alcatrazEscapee** [comment]
Cannot reproduce in latest version. Assuming it was fixed.
