### ISSUE TITLE
Unfired Large Vessels Being Very Light in Weight & Size.

### ISSUE THREAD

**Issue by Joe-org** [TerraFirmaCraft/TerraFirmaCraft#2115]
All Unfired Large Vessels(Default and Dyed) are not using the correct Weight & Size Value of their fired counterparts.
![2022-09-12_01 55 18](https://user-images.githubusercontent.com/113080914/189542337-64545e28-3c61-4bba-bcdf-7d4e5ec41747.png)
![2022-09-12_01 44 26](https://user-images.githubusercontent.com/113080914/189542422-fd199d97-713c-4c68-ba22-3d7162d9a0ac.png)
![2022-09-12_01 44 27](https://user-images.githubusercontent.com/113080914/189542426-90abd931-71a5-43e5-b916-f98da8310649.png)

**Comment by alcatrazEscapee** [comment]
Duplicate of #2124
