### ISSUE TITLE
Can't drink rain if standing on various non-solid blocks.

### ISSUE THREAD

**Issue by Zelse-DMD** [TerraFirmaCraft/TerraFirmaCraft#2119]
Standing on any of the above 4 surfaces, the player is no longer able to drink rain with right click. Moving to an open surface like dirt or stone the player is able to drink rain normally.

**Comment by Joe-org** [comment]
I can confirm this issue, though it seems like snow still allows the player to drink. But the other 3 definitely don't.(Humus/Road/Farmland)

https://user-images.githubusercontent.com/113080914/189796925-9e7a95f5-ade5-42be-98f3-2f6277b02752.mp4
