### ISSUE TITLE
Can't drink from rain when on all 4 Mud Blocks

### ISSUE THREAD

**Issue by Joe-org** [TerraFirmaCraft/TerraFirmaCraft#2121]
Similar to the previous issue that reported humus, farmland and path blocks blocking rain drinking. Silty & Loam Mud Blocks too prevent the ability to drink from the rain.

https://user-images.githubusercontent.com/113080914/189952169-7f73eb32-5dea-4183-b65e-c79143870f12.mp4

**Comment by alcatrazEscapee** [comment]
Duplicate of #2119
