### ISSUE TITLE
Cranberry Bushes not acting as intended. 

### ISSUE THREAD

**Issue by Joe-org** [TerraFirmaCraft/TerraFirmaCraft#2133]
Cranberry Bushes can grow and produce fruit out of water.

**Comment by TheRealM18** [comment]
Hello, I can confirm that you can place them. It is that you can stack 1 on top of 1 and then you can have a floating cranberry bush.

![image](https://user-images.githubusercontent.com/5025664/221986906-25252f04-c9d2-48e6-9330-b568db7b2803.png)


This is an example of what it is like.  If you want later I can show how to force make it happen.
