### ISSUE TITLE
Tool rack disappearing

### ISSUE THREAD

**Issue by Mercure250** [TerraFirmaCraft/TerraFirmaCraft#2137]
I had made a tool rack (of birch, to be specific), placed it on a shed made of mud brick, and put some of my tools on it. I went exploring far away (therefore the chunk was clearly not loaded anymore), and when I came back, the tool rack disappeared, along with the tools I put on it. I tried to see if it was a display bug, like left-clicking where it should be, and breaking the block on which it was supposed to be, with no result. It just completely vanished.

**Comment by eerussianguy** [comment]
Can we see a log file / mod list please?

**Comment by Mercure250** [comment]
I'm new to this, so I'm not sure how to give you the correct log file. Here are the mods I was using though.
![Screen Shot 09-24-22 at 03 48 PM](https://user-images.githubusercontent.com/34697807/192115966-0e87134b-00d6-463e-8cfb-6534a1012702.PNG)
(Forge version : 40.1.80)

**Comment by eerussianguy** [comment]
Please come see us in discord if you still experience this issue.
