### ISSUE TITLE
Anything (jugs, bottles, buckets...) should be refillable on flowing water.

### ISSUE THREAD

**Issue by lumagatto** [TerraFirmaCraft/TerraFirmaCraft#2138]
Allows building aqueducts with purposes more than just irrigation, mainly ease of access to water for drinking and working.

**Comment by alcatrazEscapee** [comment]
No, as I said in discord, I don't want to open the can of worms that is "buckets can pick up non source blocks", because that's what this is, and it *will* be inconsistent.
