### ISSUE TITLE
Cannot use ceramic jugs to store other liquids besides water

### ISSUE THREAD

**Issue by Nexonus** [TerraFirmaCraft/TerraFirmaCraft#2139]
Hi there, I've been recently playing on Cereal TerraFirmaCraft server (Modpack verrsion 1.0.3, TFC version 2.1.6, FirmaLife 1.1.7), I've encountered a few bugs that I wanted to report, one of the few I've seen was that you're no longer able to use ceramic jugs to store liquids, especially yeast starter - I do believe it didn't work for tannin and limewater as well. A few days before the server's update I've been normally using jugs to move yeast from one barrel to another. If it was an intentional change, let me know!

Thanks! :)

**Comment by alcatrazEscapee** [comment]
This was intended as the whitelist for these had been broken for some time. We may revisit this change as we're not happy with the current state of fluid movability, but with actual intent rather than just ignoring the jug whitelist.

1799fb9b23c1d031436de3d10b39177211cefc3c

**Comment by Nexonus** [comment]
Hi thanks a lot for a fast reply, alright I just wanted to make sure if it was an intentional change! :)
