### ISSUE TITLE
Mountain biomes are misspelt as "tfc:mountians" & "tfc:mountians_edge".

### ISSUE THREAD

**Issue by Verph** [TerraFirmaCraft/TerraFirmaCraft#214]
The TFC mountain biomes are misspelt as "tfc:mountians" and "tfc:mountians_edge".

![Capture](https://user-images.githubusercontent.com/44212698/62240078-77746200-b3d6-11e9-814c-7d0b5fa46edf.PNG)

**Comment by alcatrazEscapee** [comment]
Welp. I can't spell.
