### ISSUE TITLE
Using wooden water bucket on any stairs / waterloggable blocks causes them to vanish.

### ISSUE THREAD

**Issue by Nexonus** [TerraFirmaCraft/TerraFirmaCraft#2140]
Hi, I was planning to make a few reports but I've decided to make one for a few issues I've noted over a few last days while playing on Cereal Modpack (Modpack verrsion 1.0.3, TFC version 2.1.6, FirmaLife 1.1.7 - Mod list is available on CurseForge, however I can provide a list if needed). 

- Using wooden water bucket on any stairs / waterloggable blocks causes them to vanish. (Noted on Ash plank stairs and polished Andesite stairs)

Thanks a lot again ^^

**Comment by alcatrazEscapee** [comment]
1. Please don't report multiple issues in one report, it makes it harder to track.
2. Please don't report issues with addons or other mods here, report them to their respective trackers.

With that said, I've edited and refiled the two actual issues mentioned as they pertain to TFC.
