### ISSUE TITLE
Геологический молоток не отображает найденную руду

### ISSUE THREAD

**Issue by StraNIK112** [TerraFirmaCraft/TerraFirmaCraft#2142]
просто показывает что найдены залежи а какой залежи не при каких условиях не отображает. Играл только с TFC и Optifine и библиотекой для TFC

**Comment by alcatrazEscapee** [comment]
This is due to the fact that the Russian translation has not been updated to reflect some newer translation keys. Unfortunately, this is not something we can fix short of nuking these specific translation keys, it is waiting for translators to update to reflect newer changes (#2078)
