### ISSUE TITLE
[1.12] Able to shear underage sheep indefinitely

### ISSUE THREAD

**Issue by carrotbane2** [TerraFirmaCraft/TerraFirmaCraft#2147]
Rightclicking a familiarized, underage sheep with a knife gave me the message "This sheep♀ is too young." However, it still gave me a wool. This didn't visually change the sheep, and I could do it repeatedly, giving me 22 wool. Also, it didn't reduce the durability of my knife. I have a screenshot, but github won't let me upload it.

Version: TerraFirmaCraft-MC1.12.2-1.7.23.181.jar
I'm playing one of the most recent versions of technodefirmacraft.

**Comment by alcatrazEscapee** [comment]
Unfortunately, we are not supporting 1.12 anymore. If you have an issue with a modpack, please report it to the modpack maintainers.
