### ISSUE TITLE
All Bears have inaccurate facing of direction

### ISSUE THREAD

**Issue by Joe-org** [TerraFirmaCraft/TerraFirmaCraft#2155]
The Blue Line that indicates the direction an entity is facing is not properly functioning for the bears. When their model looks up the blue line points down, and so is the opposite.

https://user-images.githubusercontent.com/113080914/192198209-0bd27da7-742c-4508-8122-bad1297b4f1d.mp4

**Comment by eerussianguy** [comment]
https://github.com/TerraFirmaCraft/TerraFirmaCraft/commit/6a6b9f8b7bd7beafb154f266c21b75de07573294

dumb me
