### ISSUE TITLE
Twig ground clutter model is larger than stick

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#2158]
I like the models, just think the stick model should be a bit larger than it is.

![2022-09-26_11 01 25](https://user-images.githubusercontent.com/58122689/192337307-dc153b83-77af-4493-aea5-2eecf6236d08.png)

**Comment by alcatrazEscapee** [comment]
We use the issue tracker exclusively for bug reports, not suggestions or support requests. This post would be more suitable for our [discord](https://discord.gg/PRuAKvY)'s suggestions channel, where the conversation can continue there.
