### ISSUE TITLE
Way to collect ash without breaking the firepit

### ISSUE THREAD

**Issue by Mercure250** [TerraFirmaCraft/TerraFirmaCraft#2162]
I was wondering if it was possible to just do a left click or something similar to collect the ash from a firepit rather than breaking it. Having to constantly break it and re-create it in order to get more ash, especially now that ash is an important fertilizer, is kind of annoying, and doesn't really make sense to me.

**Comment by alcatrazEscapee** [comment]
We use the issue tracker exclusively for bug reports, not suggestions or support requests. This post would be more suitable for our [discord](https://discord.gg/PRuAKvY)'s suggestions channel, where the conversation can continue there.
