### ISSUE TITLE
Bismuth Bronze Alloy Percentages

### ISSUE THREAD

**Issue by obetheduck** [TerraFirmaCraft/TerraFirmaCraft#2163]
Trying to craft bismuth bronze in a small vessel and percentages don't seem to be working or there is a mechanic I am not aware of.
6 small chunks Cassiterite for 60 mb Tin 30%,4 small chunks bismuth for 40 mb 20%,  10 small chunks Tetrahedrite for 100mb Copper 50% is producing unknown metal.  I check in game doc and 2 wiki's and seem to agree with the percentages.

**Comment by alcatrazEscapee** [comment]
[From the Field Guide](https://terrafirmacraft.github.io/Field-Guide/en_us/getting_started/primitive_alloys.html)

> **Requirements:**
> 
> - 20 - 30 % : **Zinc**
> - 50 - 65 % : Copper
> - 10 - 20 % : Bismuth

---

Zinc/Sphalerite is not Tin/Cassiterite.
