### ISSUE TITLE
Mud brick stairs seem to have incorrect bounding box / player movement interaction

### ISSUE THREAD

**Issue by alcatrazEscapee** [TerraFirmaCraft/TerraFirmaCraft#2169]
> Bug report: Loam Mud Brick Stairs (Might be other stairs, but we know for sure these ones) have some sort of repulsive bounding box in the middle of the stair that prevents you from climbing them like stairs, and it actively attempts to reject you from being there or push you off of it if you manage to make it further up onto it 
> 
> There's no visual difference in the stairs; the funky pushy-away-y-hitbox-y thing doesn't show up visually
We do have stream evidence of it, though, can send a link with timestamp later
> [Stream Clip](https://clips.twitch.tv/BumblingKnottyMosquitoTebowing-ak897yhUP2bSqEio)

**Comment by eerussianguy** [comment]
brain fart
https://github.com/TerraFirmaCraft/TerraFirmaCraft/commit/e5acf05bf4db15a40b2ba04adddcb54b043b9aaa
