### ISSUE TITLE
No guidebook minecraft 1.12.2

### ISSUE THREAD

**Issue by Kehlun** [TerraFirmaCraft/TerraFirmaCraft#2177]
hello,

i was wondering if anyone could help me with this issue. i have 2 custom modpacks with terrafirmacraft, one big one and one small.
the big pack has the terrafirmacraft guidebook and the small one that just consists of terrafirmacraft, JEI doesnt. 
any help would be greatly appreciated. 
id like to have the guidebook available to me.

Thank you very much for your help

**Comment by alcatrazEscapee** [comment]
The mod "Patchouli" is required to have the guidebook.
