### ISSUE TITLE
[Feature Request] Allows side input/output for charcoal forge or any other way to automate it

### ISSUE THREAD

**Issue by Jerome226** [TerraFirmaCraft/TerraFirmaCraft#2181]
My suggestions would be to add generic item input on the side of the charcoal forge so if people add blocks like hopper into the insulation tag, they can automate it, would be very handy to have it automateable in base tfc too
If this isn't possible, please make a way to automate the charcoal forge that would not be too annoying, dropping items on top of it seems a possible solution but will make it impossible to automate if there a block in top of it(crucible) so i think side inputs  would the best way to do it.
I hope this gets implemented so i can automate my charcoal forge fuel.

**Comment by alcatrazEscapee** [comment]
> If this isn't possible, please make a way to automate the charcoal forge that would not be too annoying, dropping items on top of it seems a possible solution

This has been talked about and I have been planning to do this already.

> but will make it impossible to automate if there a block in top of it(crucible)

It will still be automate-able.
