### ISSUE TITLE
Config for changing the amount of metal contained in a ore

### ISSUE THREAD

**Issue by HermitOwO** [TerraFirmaCraft/TerraFirmaCraft#2185]
In 1.12 there was a config option for changing the amount of metal contained in a poor/normal/rich ore.
This config option is missing in 1.18.

**Comment by alcatrazEscapee** [comment]
This particular piece of data is now encoded in the relative [heating recipes](https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/1.18.x/src/main/resources/data/tfc/recipes/heating/ore/rich_hematite.json), and can be changed with a [Datapack](https://terrafirmacraft.github.io/Documentation/1.18.x/data/recipes/#heating). A config option for this will **not** be re-added as it is already configurable as is.
