### ISSUE TITLE
Candles cannot be lit through `StartFireEvent` callers

### ISSUE THREAD

**Issue by jamesjimmy88** [TerraFirmaCraft/TerraFirmaCraft#2192]
Might be working as intended, but I found it weird that I couldn't light up candles with a Firestarter.
I already "fixed" it with a CraftTweaker script, but I thought it was worth mentioning here.

**Comment by jamesjimmy88** [comment]
Derp derp derp Torches are a thing

**Comment by alcatrazEscapee** [comment]
That's the vanilla interaction; they should still be lightable via TFC.
