### ISSUE TITLE
Translation into Ukrainian

### ISSUE THREAD

**Issue by Minerafter** [TerraFirmaCraft/TerraFirmaCraft#2194]
I translated the mod (version 1.12.2) into Ukrainian, if possible please add my translation to the mod.
[uk_ua.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/9830832/uk_ua.txt)

**Comment by alcatrazEscapee** [comment]
We are not supporting or updating 1.12 anymore. Feel free to contribute to the translation efforts on the latest development version (1.18.x)
