### ISSUE TITLE
Version 2.1.15 seems to have broken support beams?

### ISSUE THREAD

**Issue by SvenParoth** [TerraFirmaCraft/TerraFirmaCraft#2196]
I was just checking out the new update, but noticed that the support beams didn't actually support anything anymore.
Example clip of .15 with 1.0 trigger chance: https://streamable.com/3i0hsj

In comparison to .14: https://streamable.com/xeid71

The other thing i noticed is most likely related to the blocks not being supported by the support beams, but bringing it up just in case - when i had placed the support beams and reduced trigger chance back to 0.1, the fake collapse particles still appeared when they shouldn't, since technically those blocks are supported by the beams: https://streamable.com/x4v7gg

**Comment by alcatrazEscapee** [comment]
Shit, I was going to check this but forgot (╯°□°）╯︵ ┻━┻

**Comment by alcatrazEscapee** [comment]
Fixed and released in v2.1.16
