### ISSUE TITLE
HIGH_MINERAL_ORE present rarity too high?

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#2199]
From today's TFCT stream, Pak's attempting to find kaolinite. Looking at <https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/1.18.x/resources/constants.py#L302> if ground level is usually <70, kaolinite and other HIGH_MINERAL_ORE rarities are more like 1:270 chunks, and the veins are smaller as well, so much harder to find.

Was this an intentional leap in difficulty for these ores?

The vertical range for this preset is quite a bit larger than any other as well, and the other ore preset with max y=210 is 1:20 chunks instead of 1:90.

**Comment by alcatrazEscapee** [comment]
We use the issue tracker exclusively for bug reports, not suggestions or support requests. This post would be more suitable for our [discord](https://discord.gg/PRuAKvY)'s suggestions channel, where the conversation can continue there.
