### ISSUE TITLE
bloomery

### ISSUE THREAD

**Issue by randalirozo** [TerraFirmaCraft/TerraFirmaCraft#2203]
Hi guys, I need help with the bloomery. I used to play with the old version like 8 yrs ago. 
Now I'm playing in 1.18.2, the latest forge and the latest tfc release.
I built the bloomery (already with 3 different stones (chiseled, smooth, brick). I added the 8 charcoal blocks, went to the top, added the limonite and the charcoal, but it does not accept it all, they just sit on the charcoals, nothing changes. I built the bloomery based on the blueprint in the game, and what I found in wiki. What could be the problem?

**Comment by alcatrazEscapee** [comment]
We use the issue tracker exclusively for bug reports, not suggestions or support requests. This post would be more suitable for our [discord](https://discord.gg/PRuAKvY), where the conversation can continue there.
