### ISSUE TITLE
Leafy Kelp and Winged Kelp are missing minecraft:kelp tag and thus cannot be dried.

### ISSUE THREAD

**Issue by Sanquira** [TerraFirmaCraft/TerraFirmaCraft#2206]
Leafy Kelp and Winged Kelp are missing minecraft:kelp tag and thus cannot be dried.

**Comment by alcatrazEscapee** [comment]
`minecraft:kelp` isn't a tag, nor do we intend to use the vanilla item. Please describe the actual issue?

**Comment by Sanquira** [comment]
Ok, my mistake. Closing
