### ISSUE TITLE
Composter shows weird date in Jade

### ISSUE THREAD

**Issue by pehala** [TerraFirmaCraft/TerraFirmaCraft#2207]
![image](https://user-images.githubusercontent.com/5594403/198842429-f7cd836a-ef1a-4d0e-b214-9e8b4f7829da.png)
It shows over a year. However, I am pretty sure they do not take over a year.

**Comment by RedRaspberry** [comment]
I've noticed this behavior with jade on many other things (crop growth time, animal growth time, etc)

**Comment by darthmichael7** [comment]
I can confirm this is happening with torches, jack o'lanterns, and saplings as well.
![image](https://user-images.githubusercontent.com/17346650/201367229-0f6ca91a-4a4e-44c0-a438-2ca2e8d6fb43.png)
![image](https://user-images.githubusercontent.com/17346650/201367391-c476a12f-4f2d-4118-9fdb-f92950ae97f0.png)
![image](https://user-images.githubusercontent.com/17346650/201367490-92e34533-66af-4ab4-b4e3-31dc16f2ae37.png)

Right clicking a jack o'lantern with a torch a second time seems to fix the issue.
![image](https://user-images.githubusercontent.com/17346650/201367519-add01342-f35e-43c2-b73f-b80231a3358d.png)
