### ISSUE TITLE
[1.18.2] TFC water types are [probably] set to render as blocks instead of translucent, preventing them from working with shaders

### ISSUE THREAD

**Issue by RedRaspberry** [TerraFirmaCraft/TerraFirmaCraft#2209]
I understand that this has been raised as an issue before for 1.12 and closed as wontfix; however since it's now possible to run shaders without optifine, I hope this is ok to ask.

**Modlist**: [All latest at time of writing] 
TFC 2.1.16, Starlight 1.0.2, Showcase Item, Rubidium 0.5.4, Patchouli 71.1, Oculus 1.2.5a, Mouse Tweaks 2.21, JEI 9.7.1.255, JourneyMap Intergration 0.13-31, JourneyMap 5.9.0beta2, Jade 5.2.5, Inventory Sorter 19.0.0, Gravestone Mod 1.0.1, FerriteCore 4.2.1

With that out the way:
I have been attempting to get TFC's water types working with Complementary shaders by editing the shader files myself to no avail. After asking for help in the Complementary discord, the consensus was that it would not be possible for either them or I to add support for the water types because "[tfc] is [...] rendering them like blocks instead of as translucents". I tried to look through the code here to check but I'm not really sure how to verify that. 

Any help would be much appreciated!
![image](https://user-images.githubusercontent.com/34117596/199184197-58df3d42-acee-40bb-9abf-c92d977af54f.png)
![image](https://user-images.githubusercontent.com/34117596/199184398-38cbd2f5-03ac-4263-b0ee-40a5cb9078f1.png)

**Comment by alcatrazEscapee** [comment]
The consensus in the complimentary shaders discord is wrong, there have been several users in the TFC discord that were able to edit the shader to include these blocks as water.

https://gist.github.com/Joe-org/9440d225f2dec7c59af06c127ab7a73a
