### ISSUE TITLE
[1.18.2] Variable height plants not dropping all items when broken from bottom

### ISSUE THREAD

**Issue by RedRaspberry** [TerraFirmaCraft/TerraFirmaCraft#2210]
This affects tree ferns and other plant types that can be stacked - if you break the bottom one, you only get a single plant back, but if you break each one from the top to the bottom down you get 1 plant back for every block broken. Is this intended?

**Comment by alcatrazEscapee** [comment]
This is consistent with vanilla behavior for i.e. vines, as harvesting them requires a tool.
