### ISSUE TITLE
[1.18.2] [Suggestion] Log piles should be colorized based on the logs contained within

### ISSUE THREAD

**Issue by RedRaspberry** [TerraFirmaCraft/TerraFirmaCraft#2211]
This would be useful for quickly discerning what logs are in a pile without having to open them up.
My idea would be to break the log pile into 4 quadrants (possibly even changing the model depending on how many stacks of logs are in the pile, as pit kilns do), and coloring each quad with whatever color of log is in the pile.

**Comment by alcatrazEscapee** [comment]
We use the issue tracker exclusively for bug reports, not suggestions or support requests. This post would be more suitable for our [discord](https://discord.gg/PRuAKvY)'s suggestions channel, where the conversation can continue there.
