### ISSUE TITLE
[1.18.2] Repeated CMEs on multiplayer server causing players to be kicked

### ISSUE THREAD

**Issue by RedRaspberry** [TerraFirmaCraft/TerraFirmaCraft#2212]
Details:
I am self-hosting a server for me and a friend to play through TFC on. Several times so far, one of us has caused a CME that kicked the other player or themselves from the server with no further explanation in the logs or error itself. 
This has most often happened while eating carrots that we have brined and pickled & sometimes with other foods. I have also been kicked after jumping into the leaves of an olive tree. 
In the cases where it is caused by eating food, the effect occurred the *instant* the eating event started (ie, when you first press right click). 
This has happened both pre and post v16. My best guess is that something is wrong with foods that have multiple effects applied to them (things that have been solely brined, pickled, salted, etc have never produced this effect).
Image attached.
![image](https://user-images.githubusercontent.com/34117596/199190990-6594ac21-2753-4ec5-a9a0-16a1d3f71e0e.png)

**Comment by alcatrazEscapee** [comment]
Please include the logs from both the client and server at time of this issue occurring.

**Comment by RedRaspberry** [comment]
[client] https://gist.github.com/RedRaspberry/f05dca511e82aa773f6b9a0c2389d412
[server] https://gist.github.com/RedRaspberry/3a99887075a04edcf7d3c620033dcb9e

Both logs have been slightly edited to remove chat and player / server ips along with cutting for file size, none of the cut log was relevant in any way (the missing 7 hours of log was literally just chat messages and "boat went too fast!!")

**Comment by alcatrazEscapee** [comment]
Please upload **the full log files**, not just whatever snippets you think are relevant.

**Comment by RedRaspberry** [comment]
If there's any specific sections you want (like the startup of the server), sure, but seeing as the server was up across multiple days and minecraft has a funny tendency to split the log when that happens I'm going to have to piecemeal it together. 
I understand the want for full logs, I get the annoyance with me only providing what *I* think is important when there could be other things, but at least take a look at what I sent- the issue isn't present anywhere else in the logs, I know because I read them fully and I know all the times the issue occurred from being the one who was playing at the time. I can tell you that all that's missing is chat, ip addresses, and a spam of "player moved too fast:" from exploring in a boat (which happen on basically every server I've ever hosted).

**Comment by RedRaspberry** [comment]
Wrote up some quick regex to match anything I don't want public. Here's the full set of logs from start of server to end of server.
[server] https://gist.github.com/RedRaspberry/7221043d56c24162eb715583f58a62e1
[client] https://gist.github.com/RedRaspberry/2a8c13f1f82e53ac63103d821dd7983e

Hope this is enough information.

**Comment by alcatrazEscapee** [comment]
I cannot reproduce, with food items that have 10k traits added. What mods are present on both the server and client? What software are you using to host the server?

**Comment by eerussianguy** [comment]
Additionally it would be good to know if you were using a plain forge install or some other kind of modified version such as Magma or using a cracked launcher.

**Comment by RedRaspberry** [comment]
Plain forge install on both server and client, server is not in offline mode (not cracked) and both of us are using legitimate accounts through the Minecraft launcher through curseforge. Server and clients using latest forge at time of writing.
I'll update this in a moment with the full modlist, not at my PC right now.

**Comment by RedRaspberry** [comment]
I should also note that it's not a completely consistent issue; ie not EVERY food item with multiple traits will do this, but of the ones that do they have always had multiple traits which is why it was my best guess. If you want I could provide the world folder itself.
Anyways, modlist is:
TFC 2.1.16
[All below are latest version at time of writing]
FerriteCore 4.2.1
GraveStone Mod 1.0.1
Inventory Sorter 19.0.0
Jade 5.2.5
JourneyMap 5.9.0beta2
JourneyMap Intergration 0.13-31
JEI 9.7.1.255
Mouse Tweaks 2.21
Oculus 1.2.5a
Patchouli 71.1
Rubidium 0.5.4
Showcase Item 1.0
Starlight 1.0.2

Notably, this issues was occurring before we updated TFC and added a good handful of the above mods; the original install was the following:
TFC 2.1.14
Jade
JourneyMap
JourneyMap Intergration
JEI
Patchouli
Mouse Tweaks

**Comment by RedRaspberry** [comment]
I'm also using custom JVM arguments on the server, but I highly doubt they have anything to do with this.
`
-Xms10G -Xmx10G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=100 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=32M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=20 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dsun.rmi.dgc.server.gcInterval=600000`

**Comment by alcatrazEscapee** [comment]
Another case noted in discord with the same CME. Advice suggests it only occurs when there are >=2 people on the server at a time and eating pickled food.

[latest.log](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/10051853/latest.log)
