### ISSUE TITLE
[1.18.2] [Suggestion] Food items

### ISSUE THREAD

**Issue by RedRaspberry** [TerraFirmaCraft/TerraFirmaCraft#2213]
These are just quick suggestions of things I feel would be nice to have:
-A breadbowl made by combining a salad or soup with a loaf of bread; would allow you to get fruit and grain in the same meal.
-A pumpkin slice item to mirror melon slices.

Additionally, it is currently possible to put full melons and pumpkins into a sandwitch, despite them providing no nutrition. These recipes should be removed in favor of recipes using the sliced versions which provide nutrition.

**Comment by alcatrazEscapee** [comment]
We use the issue tracker exclusively for bug reports, not suggestions or support requests. This post would be more suitable for our [discord](https://discord.gg/PRuAKvY)'s suggestions channel, where the conversation can continue there.
