### ISSUE TITLE
[Suggestion] Too many wild crops generated in the TFC world

### ISSUE THREAD

**Issue by recolic** [TerraFirmaCraft/TerraFirmaCraft#2219]
## Issue description

I created a new random TFC survival world, and trying to play it. I spent 6 minutes, and run about 400 blocks. But I have already spotted 15 patches of wild crops, and I got so many food & seeds. It's obviously too much, and some players will not be farming at all.

I think there should be less crop generation, for example, multiple it with `1/5` or even `1/8`. I also tried to read TFC config file, but there is no way to apply a modifier without modifying the source code. 

Screenshots attached: 

![my-test](https://user-images.githubusercontent.com/19610256/199645163-6bc094a9-6a26-432f-a4ba-926245c89e21.png)
![2](https://user-images.githubusercontent.com/19610256/199645149-b507cd9b-57f5-4871-9073-92f2b480c397.png)

## System Info

```
TerraFirmaCraft 1.18.x-2.1.18-beta
OpenJDK 17.0.5 on Linux
```

Test world seed: `-166280079787610568`

**Comment by alcatrazEscapee** [comment]
We use the issue tracker exclusively for bug reports, not suggestions or support requests. This post would be more suitable for our [discord](https://discord.gg/PRuAKvY)'s where the conversation can continue there.

**Comment by alcatrazEscapee** [comment]
> I also tried to read TFC config file, but there is no way to apply a modifier without modifying the source code.

I will also mention, this is entirely modifiable - along with the rest of world generation - via a datapack, requiring no source code changes at all.
