### ISSUE TITLE
Spawning baby predators with spawn eggs causes the game to crash & re-opening the world crashes the game

### ISSUE THREAD

**Issue by Joe-org** [TerraFirmaCraft/TerraFirmaCraft#2223]
Click the spawn egg of any predator on an adult and a baby predator would appear, but right after that. The game will crash.

**Comment by alcatrazEscapee** [comment]
Crash log please.

**Comment by Joe-org** [comment]
> Crash log please.

This is it right?
[crash-2022-11-10_17.19.37-server.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/10028341/crash-2022-11-10_17.19.37-server.txt)
