### ISSUE TITLE
Too many icicles

### ISSUE THREAD

**Issue by lumagatto** [TerraFirmaCraft/TerraFirmaCraft#2225]
The amount of icicles that form is exaggerated.
Icicles look good but not when they occupy half the possible spots in a build and are 5m long.

Here are icicles after roughly 2 months of winter
![2022-11-10_22 22 05](https://user-images.githubusercontent.com/21110014/201443412-9ea71b0c-2cce-443d-a051-3f0cdf88c352.png)

**Comment by alcatrazEscapee** [comment]
Hello! We use the issue tracker exclusively for bug reports, not suggestions or support requests. This post would be more suitable for our [discord](https://discord.gg/PRuAKvY), where the conversation can continue there.
