### ISSUE TITLE
Manatee Woes

### ISSUE THREAD

**Issue by Joe-org** [TerraFirmaCraft/TerraFirmaCraft#2231]
Manatees still use the default Minecraft cod fish sounds and subtitles. Also yeah, they slide really well for an aquatic creature on land.

https://user-images.githubusercontent.com/113080914/201658094-100d46ea-39a0-4465-bb50-86920783465b.mp4

**Comment by eerussianguy** [comment]
please use more descriptive titles also fixed in https://github.com/TerraFirmaCraft/TerraFirmaCraft/commit/c614057b16da47d851db57df0ff3548ac29a4e49
