### ISSUE TITLE
Server crash when using Crafting Tweaks + TFC?

### ISSUE THREAD

**Issue by SeriousCreeper** [TerraFirmaCraft/TerraFirmaCraft#2238]
Heya,

i'm not entirely sure what is causing this, and if this is an issue on CraftingTweaks side on TFC's, but we had 2 server crashes recently that i think point at foodhandler when using craftingtweaks. 

Crash report here: https://pastebin.com/wVSGjd67

Been trying to recreate this but haven't had much success yet, as i'm not quite sure what specifically would cause this. 

Let me know if this is something i should report on CraftingTweaks side instead. 

-SC

**Comment by alcatrazEscapee** [comment]
This is an issue where crafting tweaks spins in an infinite loop trying to use our food combining recipe. It can be reproduced by compressing any stack of food items. It can also be reproduced with a datapack, no TFC, and only crafting tweaks.

In the meantime, it appears crafting tweaks has a mechanism to blacklist certain items from being the result of a compression recipe. That should solve it too.

The issue has been reported with crafting tweaks as it's on them to fix.

https://github.com/ModdingForBlockheads/CraftingTweaks/issues/182
