### ISSUE TITLE
Lapis Lazuli Powder has missing recipes

### ISSUE THREAD

**Issue by 0xC0ncord** [TerraFirmaCraft/TerraFirmaCraft#2239]
For some reason it seems that the recipe needed to be able to create blue dye from Lapis Lazuli powder is missing. Either the item does not belong to the blue dye ore dictionary or an explicit recipe needs to be added. As of right now, the Lapis Lazuli Powder seemingly has no functional purpose.

Forge Version: 40.1.84
TFC Version: 1.18.2-2.1.18-beta

**Comment by eerussianguy** [comment]
To clarify, there is no such thing as ore dictionary.
