### ISSUE TITLE
[1.7.10] May I post a better Chinese translation online in public?

### ISSUE THREAD

**Issue by Vorm-CN** [TerraFirmaCraft/TerraFirmaCraft#2241]
I (named "CWHHH" in my TFC server) with my friend "King" have just found and fixed some mistakes and shortcomings in zh_CN.lang of 0.79.29.922. Changes are noted in it in detail. The original lang file didn't change in 0.79.30.925. [Here](https://github.com/Vorm-CN/Better-zh_CN.lang-of-TFC-1.7.10) is my lang file. Please check.
I wonder if I can post this translation on www.mcbbs.net, a Chinese Minecraft forum.

**Comment by alcatrazEscapee** [comment]
This repository is not for 1.7.10. Nor are we supporting 1.7.10 TFC anymore. You must obey the terms of the [License](https://github.com/TerraFirmaCraft/TFC-1.7.10/blob/master/license.txt) of that repository.
