### ISSUE TITLE
Saplings dont grow.. TFC (v  1.18.2 2.2.0 release)

### ISSUE THREAD

**Issue by VBshow** [TerraFirmaCraft/TerraFirmaCraft#2243]
i noticed this issue without JEI at first because my saplings just didnt grow up, so then i decided to download JEI to see maybe te problem is tem or something,,,, i saw in the update log this problem were fix but as you can see.... :( 
![2022-11-27_09 04 00](https://user-images.githubusercontent.com/119146632/204123639-351e8a12-e48b-4413-b049-f69fd32aa049.png)

**Comment by alcatrazEscapee** [comment]
9cb52fbccd854450453c93690258eb8a90997cca
