### ISSUE TITLE
Optifine Crash?

### ISSUE THREAD

**Issue by MissSweetViolet** [TerraFirmaCraft/TerraFirmaCraft#2245]
I was wondering if Optifine is not supported? I tried looking on the CurseForge and site/wiki pages, but could find nothing. 
When I try to use this with Optifine (needed by a wolf texture pack I wanted to use), I crash upon trying to load the world. 
I'm in 1.18.2. Forge version 40.1.73 and have tried both versions HD6 and HD7 on Optifine's Site with the same result.

This was my latest log; https://mclo.gs/PrM9l8E

**Comment by alcatrazEscapee** [comment]
As Optifine is a closed source jar mod, we do not support or recommend it's use, nor can we fix any issues arising when it's used. They would need to be reported to Optifine. There are well documented crashes on 1.18.2 with Optifine and Forge, no TFC involved, not to mention any other issues.

**Comment by mjevans** [comment]
For anyone that finds this later (google / existing issue search / etc)...

Presently (late 2022), and for MC 1.18.2 (maybe 1.19 too), there are some alternatives to Optifine.  I'm currently using someone else's TFC based pack which includes rubidium and oculus, without any known render issues.

https://www.curseforge.com/minecraft/mc-mods/rubidium
Rubidium -- "is an Unofficial Fork of CaffeineMC's "Sodium", made to work with Forge Mod Loader."

https://www.curseforge.com/minecraft/mc-mods/oculus
Oculus -- (Shaders for Rubidium) Unofficial Fork of "Iris", made to work with FML 

https://www.curseforge.com/minecraft/mc-mods/magnesium-extras -- Lots of stuff, including a Zoom key

https://www.curseforge.com/minecraft/mc-mods/dynamiclights-reforged

++
Notes for Fabric, not-Forge packs:

https://modrinth.com/mod/sodium
Sodium is a free and open-source rendering optimization mod for Minecraft 1.16+ which greatly improves frame rates and stuttering while fixing many graphical issues. It boasts wide compatibility with the Fabric mod ecosystem when compared to other rendering-focused mods, and it does so without compromising on how the game looks, giving you that authentic block game feel.

https://modrinth.com/mod/iris
A modern shaders mod for Minecraft intended to be compatible with existing OptiFine shader packs
