### ISSUE TITLE
Using timetfc to set ticks to 0 keeps an artifact of daytime.

### ISSUE THREAD

**Issue by HeartyYF** [TerraFirmaCraft/TerraFirmaCraft#225]
From debug info you can see 00:28, but that time should be night.
![2019-08-03_22 52 39](https://user-images.githubusercontent.com/17660052/62413421-6ed39400-b641-11e9-96cd-2fc01947c25e.png)

**Comment by alcatrazEscapee** [comment]
I can't reproduce. Please remove all other mods - including optifine, liteloader, etc. and see if the issue persists.

**Comment by HeartyYF** [comment]
I can reproduce.
2 possibilties,
- There is already a fix for it, after 0.13.0 was released, and you are using a newer version.
- You use /timeftc to change time from daytime to night, spawn a zombie, and change time back to daytime. This won't prevent zombie from burning.

**Comment by HeartyYF** [comment]
I know where the problem exists now.
Using /timetfc set ticks 0 still keeps an artifact of daylight.
