### ISSUE TITLE
Lava / Fire death does not cook dropped meat

### ISSUE THREAD

**Issue by mjevans** [TerraFirmaCraft/TerraFirmaCraft#2260]
Lava / Fire death does not cook horse meat.

TFC 2.2.2 for MC 1.18.2

https://clips.twitch.tv/CleanFrailLorisBudBlast-tTS-h794ueMi783u

**Comment by alcatrazEscapee** [comment]
This does not happen in general for TFC foods or loot items. And my initial reaction is that it shouldn't; or at least it should have a *heavy* negative food modifier.

**Comment by mjevans** [comment]
Passed that on to the streamer at the end of the same stream the clip is from.

They seem to be happy everything is working as intended.  It just looked like a bug since it's not what they and everyone else expected.
