### ISSUE TITLE
Deer Hind-leg has white uncoloured pixel

### ISSUE THREAD

**Issue by Joe-org** [TerraFirmaCraft/TerraFirmaCraft#2261]
The Hind-leg of Deers have an uncoloured white pixel.
![2022-12-15_00 45 37](https://user-images.githubusercontent.com/113080914/207950880-b6f8639c-7a61-49b3-a9b2-8df47fda38eb.png)
![2022-12-15_00 45 50](https://user-images.githubusercontent.com/113080914/207950977-686b5be4-f4f8-4f93-976d-159fef595d9a.png)

**Comment by eerussianguy** [comment]
lol I bet this just drives you insane, doesn't it

**Comment by Joe-org** [comment]
You know me so well.  :")
