### ISSUE TITLE
Some mod combinations prevent generation of foliage

### ISSUE THREAD

**Issue by DadddyLongLegs** [TerraFirmaCraft/TerraFirmaCraft#2263]
Ive noticed large biomes with no plants. it seems really common and if its what you spawn in it leaves you with no food or trees

https://cdn.discordapp.com/attachments/252196474983677955/1054324836069015562/2022-12-19_02.55.20.png

i tried linking a picture but it may not work

**Comment by eerussianguy** [comment]
This is most definitely due to a mod conflict, without a mod list and log or knowing what datapacks you have we can't help. Please also use more descriptive titles

**Comment by alcatrazEscapee** [comment]
Looking back, I believe this was being caused by https://github.com/alcatrazEscapee/cyanide/issues/13, and without any further info I'm going to assume that was the case (and resultant fix). If this is reoccurring with more information (i.e. particular mod conflict), we can look into it.
