### ISSUE TITLE
If the XP bar is disabled, move health, hunger, etc. down.

### ISSUE THREAD

**Issue by MagmaSlime123** [TerraFirmaCraft/TerraFirmaCraft#2270]
Title. Not sure why there's a big blank space.

Bars are from a resourcepack being used from the Content channel.
![2022-12-23_20 18 56](https://user-images.githubusercontent.com/51277766/209419460-327a16b7-1c6c-4c5a-8c10-9ade077f5414.png)

**Comment by eerussianguy** [comment]
#2316
