### ISSUE TITLE
Visual texture differences for burning torches?

### ISSUE THREAD

**Issue by Lylythii** [TerraFirmaCraft/TerraFirmaCraft#2278]
Currently it's difficult to tell how old a torch is.
Took a look & don't believe this can be changed with a simple resource-pack.
I'd be happy to provide textures for torch burn states if necessary!

**Comment by alcatrazEscapee** [comment]
We use the issue tracker exclusively for bug reports, not suggestions or support requests. This post would be more suitable for our [discord](https://discord.gg/PRuAKvY)'s suggestions channel.

That aside, no it is not changeable via a resource pack unless said resource pack can read block entity NBT (which I don't believe it can).
