### ISSUE TITLE
Missing sound effects for farming interactions

### ISSUE THREAD

**Issue by natrow** [TerraFirmaCraft/TerraFirmaCraft#2292]
- Placing sticks on climbing crops
 - Using fertilizer items

**Comment by alcatrazEscapee** [comment]
This isn't an issue. These aren't missing as in, we try and play a sound that doesn't exist, or we are missing a subtitle. If that *is* the case, please make it clear. These just don't have sounds. This is a fine suggestion but we don't use our issue tracker for tracking suggestions.

**Comment by alcatrazEscapee** [comment]
Apparently russian actually wanted to do this, hence asking for an issue, my bad 😅
