### ISSUE TITLE
Penguins act strange when presented with fish entities on land.

### ISSUE THREAD

**Issue by alcatrazEscapee** [TerraFirmaCraft/TerraFirmaCraft#2294]
Reported from discord:

> i found that penguins starts to go crazy when they see a fish on the ground flopping

https://user-images.githubusercontent.com/35673674/213760144-76cf143f-43a7-4abc-9d52-2b7c8650f077.mp4

Seem to be moving as if they are in water but on land. AI malfunction?

**Comment by eerussianguy** [comment]
https://github.com/TerraFirmaCraft/TerraFirmaCraft/commit/8d1ca18b305882cad26628f0f74729fd91a7a8f5
