### ISSUE TITLE
Animal suggestions

### ISSUE THREAD

**Issue by HatcheryRoosters** [TerraFirmaCraft/TerraFirmaCraft#2297]
When I had the 1.12 version, mobs like llamas and parrots had the TFC treatment. The 1.18 doesn't have that, and I was wondering if any Vanilla animals missed from the 1.12 version (along with post-1.12 mobs like the bees, and missing TFC exclusives like the hare) will be added to the 1.18 version soon.

Also, I have an idea: You could add in some of the the Minecraft Earth variants as versions of existing animals (with variants for both males and females). For realism, you should add the ones that are based on real life breeds.

I hope you see this as interesting and I hope to hear back soon!

**Comment by alcatrazEscapee** [comment]
We use the issue tracker exclusively for bug reports, not suggestions or support requests. This post would be more suitable for our [discord](https://discord.gg/PRuAKvY)'s suggestions channel.
