### ISSUE TITLE
Some animal genders are missing (also no female mules) (v.2.2.5)

### ISSUE THREAD

**Issue by HatcheryRoosters** [TerraFirmaCraft/TerraFirmaCraft#2302]
Using TheOneProbe, I was able to determine the genders of animals. I realized that the genders for some of the animals are missing, and those animals are:

Rabbit, fox, ocelot, panda, cod, pufferfish, salmon, tropical fish, jellyfish, bluegills, lobster, crayfish, isopod, horseshoe crab, dolphin, orca, manatee, squid, and octopoteuthis.

Also, I don't know if this is me but none of the mules spawning are female (yes, mules can be both male and female, same thing with hinnies)

**Comment by alcatrazEscapee** [comment]
Genders for these animals are intentionally omitted as they have no bearing or relevance. The animals are not tameable and we do not differentiate in their model or asset. Thus as far as we are concerned, it does not exist.

**Comment by HatcheryRoosters** [comment]
I just thought it would be a neat addition. And all the other animals have genders, so why not do it to all the others? (Well not all, mostly the mammals and birds but you get my point)
