### ISSUE TITLE
Unknown alloy cast into ingot doesn't separate into constituent metals when remelted inside a crucible

### ISSUE THREAD

**Issue by Yesname** [TerraFirmaCraft/TerraFirmaCraft#2320]
Wouldn't it be great if it did?

**Comment by alcatrazEscapee** [comment]
![no](https://media.tenor.com/GgSc9yr_yh0AAAAC/star-wars-star-wars-meme.gif)

**Comment by Clashsoft** [comment]
I wish it did. Sometimes I misclick a vessel into the crucible output slot while it is still "unknown", then stupidly and frantically put it back into the input slots, only to have the entire thing ruined. It's not like the composition of metals changes in any way.
