### ISSUE TITLE
[Question] About new translations

### ISSUE THREAD

**Issue by FITFC** [TerraFirmaCraft/TerraFirmaCraft#2322]
Hello, I would like to know if when sending a translation you are accepting it, I saw that the mod is gigantic +3k of lines of translations, if you are accepting it, can I send it in parts? (Since it is very intensive)

Leaving the translation topic a bit... do you have plans to keep updating the mod for new versions of the game?

**Comment by alcatrazEscapee** [comment]
See [Info for Translators](https://github.com/TerraFirmaCraft/TerraFirmaCraft/wiki/Info-for-Translators) if you wish to provide a translation. Yes, you do not have to translate absolutely everything, any work is welcome.
