### ISSUE TITLE
Empty Ingot Casts have temperature

### ISSUE THREAD

**Issue by DavidTriphon** [TerraFirmaCraft/TerraFirmaCraft#234]
After emptying a clay ingot mold of its liquid into a cast or other ingot mold, the original mold still has temperature that decreases over time.

![2019-08-04_13 29 03](https://user-images.githubusercontent.com/20526831/62428905-34f3a380-b6bc-11e9-9ce0-f075ecc8e4e6.png)

**Comment by muzikbike** [comment]
Same stuff with emptied clay vessels.

**Comment by alcatrazEscapee** [comment]
This is fully intentional.
