### ISSUE TITLE
Terrafirmacraft breedable mobs pushed/run away when holding food

### ISSUE THREAD

**Issue by radiomike** [TerraFirmaCraft/TerraFirmaCraft#2341]
When a player is holding food for a breedable mob and the mob steps down from a block, the mob runs/gets pushed away from the player at high speed. 

This is in the atm-gravitas pack version - 1.9b
TFC Mod version - 2.2.11

Also see https://github.com/AllTheMods/tfc/issues/17 - includes a video of what happens.

**Comment by valipopescu** [comment]
happens to me with all the baby animals ... less often with the adults but still see them flying 10+ chunks into the lake south of my house :)

**Comment by eerussianguy** [comment]
unable to reproduce with just TFC installed.
