### ISSUE TITLE
Drinking milk makes you lactose intolerant (Saturation to NaN value)

### ISSUE THREAD

**Issue by pietro-lopes** [TerraFirmaCraft/TerraFirmaCraft#2344]
### Tested on:

- Version: 2.2.11 (ATM Gravitas pack, version 1.9b)
- Singleplayer and Multiplayer feels affected too (can't run commands on Multi)

### How to reproduce:

Check your saturation beforehand:

`/tfc player @p query saturation`
`Saturation is 5 / 20`

Set water level to below 100 so you can drink
`/tfc player @p set water 95`

Now drink milk with _Ceramic Jug_ or flasks if _TFC Water Flask_ available
`/tfc player @p query saturation`
`Saturation is NaN / 20`

Try to drink water/eat food and Saturation value will be stuck to NaN forever.
The only way to reset is by death.

**Comment by remixzy** [comment]
🤖 I can confirm this bug sir 🤖

**Comment by eerussianguy** [comment]
https://github.com/TerraFirmaCraft/TerraFirmaCraft/commit/f282996437822bb64332cdb0c1658e4125d88e81
