### ISSUE TITLE
Zombie mobs drop vanilla minecraft potatoes

### ISSUE THREAD

**Issue by DavidTriphon** [TerraFirmaCraft/TerraFirmaCraft#235]
Zombie mobs can occasionally drop vanilla Minecraft potatoes. These potatoes can be planted anywhere on the ground to let grow. Breaking the planted potatoes resets their decay time so they never go bad. Letting the crop mature just gets you more vanilla potatoes like default behavior.

![2019-08-04_12 21 42](https://user-images.githubusercontent.com/20526831/62428975-383b5f00-b6bd-11e9-81e7-67abc18ab789.png)

**Comment by HeartyYF** [comment]
Besides, there is no mean to cook potaoes. However, potatoes can provide carbonhydrates.

**Comment by DavidTriphon** [comment]
They also drop carrots, which can be similarly planted, and vanilla iron bars, which can be used to craft vanilla shields earlier on.

**Comment by alcatrazEscapee** [comment]
This is still an issue
