### ISSUE TITLE
my days are too short, please help

### ISSUE THREAD

**Issue by deadrabbit12** [TerraFirmaCraft/TerraFirmaCraft#2351]
Good afternoon. I would like to add the ability to increase the duration of the day and night cycle, but all my attempts bring only one thing (screen attached), is it possible to somehow configure it, I use minecraft version 1.18.2
![фоваыим](https://user-images.githubusercontent.com/53154054/228065759-384210d4-23d3-4041-974b-8bce762c86fd.jpg)

**Comment by alcatrazEscapee** [comment]
No.
