### ISSUE TITLE
Why we can't place lumber now?

### ISSUE THREAD

**Issue by EdwyReed** [TerraFirmaCraft/TerraFirmaCraft#2352]
Hi! 
I mean those long 1x1 microblocks. Sure, now we can use chisel, but it was so easy to just make lumbers and make big things in few minutes. Is there any reason, why it wasn't included in TFC:TNG ?

**Comment by alcatrazEscapee** [comment]
Hello! We use the issue tracker exclusively for bug reports, not suggestions / support requests / questions. This post would be more suitable for our [discord](https://discord.gg/PRuAKvY).
