### ISSUE TITLE
Bug: Wolves attack while asleep

### ISSUE THREAD

**Issue by jcrawl16** [TerraFirmaCraft/TerraFirmaCraft#2354]
Wolves are somehow able to move and attack me even though they are sitting down and Zs are floating above them, it's honestly kinda funny at first, just seeing them slide like that, but then it stops being funny after they've killed me 5 times while they're asleep.

**Comment by Sethyboy0** [comment]
I've had this with bears in 1.18.2 in the auto-TFC modpack.

**Comment by Varnus** [comment]
Also experienced this bug some time ago in the ATM Gravitas modpack

**Comment by Ozzymud** [comment]
Just tossing in a sleeping lion killed me in 1.18.2 in the auto-TFC modpack.

**Comment by alcatrazEscapee** [comment]
Closing as we're not supporting 1.18 anymore, given the uncertain issue status. If this occurs in 1.20.1, please open a separate issue with reproduction information.
