### ISSUE TITLE
Feature Request: Bone flutes

### ISSUE THREAD

**Issue by jcrawl16** [TerraFirmaCraft/TerraFirmaCraft#2355]
I switched over from TFC Plus recently, that's 1.7.10 only which just feels too outdated, and this 1.18 version of TFC feels alot more polished as well. But one feature I miss alot from TFC Plus is instruments, would it be possible to implement something similar in a future update?

**Comment by alcatrazEscapee** [comment]
Hello! We use the issue tracker exclusively for bug reports, not suggestions or support requests. This post would be more suitable for our [discord](https://discord.gg/PRuAKvY).
