### ISSUE TITLE
Some cross-shaped plants exhibit unnatural mirror symmetry when viewed from certain angles

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#2359]
![2023-04-15_16 08 58](https://user-images.githubusercontent.com/52297970/232248429-bf845b7f-4b52-497b-ada5-28bb7d40fd74.png)

If the texture mapping is to be preserved, this could be fixed by having each of the two planes that make up the plant use a different texture.

**Comment by eerussianguy** [comment]
> having each of the two planes that make up the plant use a different texture.

This well never happen. We can make the textures less symmetrical but there is absolutely zero precedent for doing that.
