### ISSUE TITLE
Javelins thrown by skeletons do not stick inside of players

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#2362]
This is technically inconsistent with arrows, another piercing projectile, which do in fact do this.
![2023-04-15_20 21 17](https://user-images.githubusercontent.com/52297970/232249472-d6a2fb8c-7ef3-4d99-a4e7-f66acbf8c9f9.png)

I remembered this being the case in 1.7.10 and decided to test it just to be sure. It technically worked back then, but in a buggy way: they appeared as arrows when stuck in the player, rather than javelins.
![2023-04-15_20 06 52](https://user-images.githubusercontent.com/52297970/232249520-28b8b3f8-ee7d-4800-9470-8e03e39d1f5f.png)

**Comment by alcatrazEscapee** [comment]
This is technically consistent with tridents, another piercing projectile, which don't in fact do this.

I'd also say this falls under the general purview of suggestion/enhancement and thus should be put in our discord's `#suggestions` channel, not our issue tracker.
