### ISSUE TITLE
Feature request for physics based water

### ISSUE THREAD

**Issue by SnoutBug** [TerraFirmaCraft/TerraFirmaCraft#2364]
I think the physics in tfc are awesome and they add that missing bit of realism to the game.
I would also love to see some physics for water as well. There are already some implementations (like [water physics overhaul](https://www.curseforge.com/minecraft/mc-mods/water-physics-overhaul)) which add some really satisfying water dynamics to the game.

Implementing physics similar to the mod I mentioned would cause water to be a scarce resource (small ponds could be used up quite quickly) which would match the already above average difficulty of tfc.
Drinking from ponds could also decrease water levels slightly which would make the survival aspect even more realistic.

Additionally buckets would not be overpowered since they can't be used to create infinite water sources anymore.

Rain could actually fill ponds slightly - starbound like, but also dry up when they are created without a proper base layer (such as clay).

Another benefit would be the revival and active maintaining of a water simulator (sadly the development for the mentioned mod seems to have stopped)

I'm just spitballing to paint a basic picture of the possibilities such a system could bring, I am aware that this would be no minor change, but an awesome change non the less.

**Comment by alcatrazEscapee** [comment]
We use the issue tracker exclusively for bug reports, not suggestions or support requests. This post would be more suitable for our [discord](https://discord.gg/PRuAKvY).
