### ISSUE TITLE
Mobs have a hard time pathfinding up a block

### ISSUE THREAD

**Issue by erv123** [TerraFirmaCraft/TerraFirmaCraft#2366]
I've experienced mobs having a hard time pathfinding up a block, mobs like lions can be cheesed with it, but also it makes leading mobs a massive pain
Asked on discord if anyone else has had it, and other players reported it too

**Comment by TheNameSimonWasAlreadyTaken** [comment]
This happens mostly if the block the animal wants to jump up has either fallen leaves or at least a double thick snow layer on top of it, both have hitboxes that prevent most animals from being leaded up them.

**Comment by CandyFiend** [comment]
This also happens if the mob is standing on a similar block (or touches it). I removed all the blocks under the mob and he calmly jumped even on blocks with sticks, stones, plants, snow, etc.

**Comment by eerussianguy** [comment]
https://github.com/TerraFirmaCraft/TerraFirmaCraft/pull/2521
https://github.com/TerraFirmaCraft/TerraFirmaCraft/pull/2520
