### ISSUE TITLE
Rocks and sticks not spawning on servers

### ISSUE THREAD

**Issue by rtpop** [TerraFirmaCraft/TerraFirmaCraft#2369]
I have a server hosted on gportal. But for some reason, sticks and rocks will not spawn on the server. When I load a singleplyer world, they spawn fine. I simply copied the mod file from my PC to the server, so it should be the same version of the mod. And other features of the mod are working fine. But I am unable to progress because I can't get any stones.

**Comment by alcatrazEscapee** [comment]
We use the issue tracker exclusively for bug reports, not suggestions or support requests. This post would be more suitable for our [discord](https://discord.gg/PRuAKvY).
