### ISSUE TITLE
Sprinting/breaking/falling particles of TFC grass is biome-tinted

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#2372]
This is the exact same issue as #710, but for 1.18.2 rather than 1.12.2.

It'd be expected that grass blocks would either use the dirt texture without the biome-dependent tint (like vanilla grass blocks), or would use the grass block top texture with the tint (which is what the fix to #710 did).
![2023-04-28_21 53 18](https://user-images.githubusercontent.com/52297970/235252678-334a4efb-9b81-41c2-9259-579ceca41c77.png)
![2023-04-28_21 53 46](https://user-images.githubusercontent.com/52297970/235252686-e3ad2bac-3612-4ffd-902f-2532b7533af4.png)

**Comment by eerussianguy** [comment]
Was already fixed in 1.20
