### ISSUE TITLE
Small ground items lack cullface arguments

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#2375]
![2023-04-28_21 54 10](https://user-images.githubusercontent.com/52297970/235254885-b9ffa23c-db7e-41d0-8e8f-e515ba07683c.png)
![2023-04-28_21 58 14](https://user-images.githubusercontent.com/52297970/235254887-35b8cf8a-6936-42b2-b1ad-b731ce60c827.png)

**Comment by eerussianguy** [comment]
#2379
