### ISSUE TITLE
2.2.17: Removed ability to light some devices by right clicking with a torch

### ISSUE THREAD

**Issue by Imsvale** [TerraFirmaCraft/TerraFirmaCraft#2384]
>### [TerraFirmaCraft 1.18.x-2.2.17](https://github.com/TerraFirmaCraft/TerraFirmaCraft/releases/tag/v2.2.17)
>Version 2.2.17
>
>### Changes
>* Removed the ability to light some devices by right clicking with a torch.

Can I ask why?

**Comment by alcatrazEscapee** [comment]
We use the issue tracker exclusively for bug reports, not suggestions or support requests. This post would be more suitable for our [discord](https://discord.gg/PRuAKvY).
