### ISSUE TITLE
Purpose of this mod?

### ISSUE THREAD

**Issue by lynrayy** [TerraFirmaCraft/TerraFirmaCraft#2390]
I don't see differences between old TFC and new (1.18.2), what is it's purpose? 
Why you can't made it better? I mean, campfire craft, log placing, stone tool's head craft and a lot of other things still works as outdated cringe. You can see how it SHOULD made in vintage story game!

**Comment by lynrayy** [comment]
I was hoping that the mod was updated to a grand new level, but it remained as old as it was before. Good luck!

**Comment by alcatrazEscapee** [comment]
lmfao
