### ISSUE TITLE
Melon's growing on non-dirt #tagged blocks

### ISSUE THREAD

**Issue by Romaq** [TerraFirmaCraft/TerraFirmaCraft#2391]
I'm using Auto TerraFirmaCraft with TerraFirmaCraft-Forge-1.18.2-2.2.18 release April 30, 2023.

I have melons (not tested pumpkins yet) growing on aqueducts and on top of a "large vessel" in the dirt (so empty air adjacent to the plant). According to the Minecraft Vanilla wiki,

"[For both pumpkins and melons, the stem] "attempts to generate a melon block in one of the four immediately adjacent blocks; however, this attempt may fail if the chosen adjacent block is not empty or the block beneath is not an appropriate block (those in the #dirt block tag in Java Edition, dirt/grass block/farmland/coarse dirt in Bedrock Edition).'"

If pumpkin/ melon generation does not respect the #dirt tag, it will not be possible to use gravel, cobble, or other blocks to force the direction of pumpkin/ melon growth without putting something there. Could the generation code please be looked at to respect the #dirt tag for loam and silty loam?

**Comment by eerussianguy** [comment]
For what it's worth, we're not under any obligation to keep the vanilla behavior

**Comment by Romaq** [comment]
I understand, and I totally get that. I would point out, however, that grouping item types by #tags saves a great deal of if-then logic. You can just deal with groups of items by tags. Preserving tags and tag behavior between TFC and Vanilla is useful, particularly in the ability to use data packs without having to explicitly recode them for TFC.

As far as pumpkin/ melon behavior, while I understand there is no obligation to follow Vanilla, preserving the behavior would decrease "surprise." I'd rather not have the melons grow on top of the aqueduct or other "non-dirt" locations. I could put a fence or some non-blocking object at that location... signs, perhaps, but preserving the #tag behavior might be useful to solve other bugs in the future.

**Comment by eerussianguy** [comment]
Is the implication that I don't understand what a tag is?

**Comment by Romaq** [comment]
My apologies. It is not my intent to cast aspersions or slights. It is my intention to avoid "surprise*" at the expected "spawns on #dirt tagged only" behavior and to promote vanilla behavior where it is feasible. Yes, I grasp your project isn't under Vanilla obligation. The point of your mod is to creatively depart from vanilla behavior. I support the ideals of your project. I was simply "surprised*."

Thank you for your interest in this report.

*surprise: https://en.wikipedia.org/wiki/Principle_of_least_astonishment

**Comment by eerussianguy** [comment]
https://github.com/TerraFirmaCraft/TerraFirmaCraft/commit/8e394cf020e0aae04d94c76b1411856a11409a5c
