### ISSUE TITLE
1.18.2 Startup Crash

### ISSUE THREAD

**Issue by Harvestminer** [TerraFirmaCraft/TerraFirmaCraft#2392]
**Forge Version:** 40.2.2
**Minecraft Version:** 1.18.2
**Dependencies-Installed:** Patchouli

**Exception:**
> [06:57:02] [Worker-Main-25/ERROR]: Exception caught during firing event: mcp/mobius/waila/api/IWailaPlugin
> 	Index: 1
> 	Listeners:
> 		0: NORMAL
> 		1: net.minecraftforge.eventbus.EventBus$$Lambda$4509/0x0000000800bfc448@4a404fea
> java.lang.NoClassDefFoundError: mcp/mobius/waila/api/IWailaPlugin
> 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
> 	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:116)
> 	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216)
> 	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226)
> 	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216)
> 	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
> 	at TRANSFORMER/tfc@2.2.19/net.dries007.tfc.TerraFirmaCraft.setup(TerraFirmaCraft.java:194)
> 	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
> 	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
> 	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
> 	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
> 	at LAYER PLUGIN/javafmllanguage@1.18.2-40.2.2/net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106)
> 	at LAYER PLUGIN/fmlcore@1.18.2-40.2.2/net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107)
> 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
> 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
> 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
> 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
> 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
> 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
> Caused by: java.lang.ClassNotFoundException: mcp.mobius.waila.api.IWailaPlugin
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
> 	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
> 	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
> 	... 22 more
> 
> [06:57:02] [Worker-Main-25/ERROR]: Caught exception during event FMLCommonSetupEvent dispatch for modid tfc
> java.lang.NoClassDefFoundError: mcp/mobius/waila/api/IWailaPlugin
> 	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
> 	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
> 	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:116) ~[securejarhandler-1.0.3.jar:?]
> 	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
> 	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?]
> 	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
> 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
> 	at net.dries007.tfc.TerraFirmaCraft.setup(TerraFirmaCraft.java:194) ~[TerraFirmaCraft-Forge-1.18.2-2.2.19.jar%2354!/:2.2.19]
> 	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
> 	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
> 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
> 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
> 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.2.2.jar%2357!/:?]
> 	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.2.2.jar%2356!/:?]
> 	at java.util.concurrent.
CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
> 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
> 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
> 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
> 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
> Caused by: java.lang.ClassNotFoundException: mcp.mobius.waila.api.IWailaPlugin
> 	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
> 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
> 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
> 	... 22 more

[crash-2023-05-10_06.57.12-fml.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/11441777/crash-2023-05-10_06.57.12-fml.txt)

**Comment by alcatrazEscapee** [comment]
This appears to be an oversight on my part. In the mean time, you can either install Jade, or downgrade TFC.

**Comment by Harvestminer** [comment]
> This appears to be an oversight on my part. In the mean time, you can either install Jade, or downgrade TFC.

Sounds good to me. Thanks for the work around!
