### ISSUE TITLE
TFC Common_setup event phase crash.

### ISSUE THREAD

**Issue by SSilice** [TerraFirmaCraft/TerraFirmaCraft#2393]
Weird issue after updating Terrafirmacraft and some other TFC related mods when launching now. never used to happen

[crash-2023-05-10_14.16.37-fml.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/11445248/crash-2023-05-10_14.16.37-fml.txt)

**Comment by alcatrazEscapee** [comment]
Duplicate of #2392
