### ISSUE TITLE
Valkyrien Skies/Eureka + Giant Kelp Issue

### ISSUE THREAD

**Issue by SSilice** [TerraFirmaCraft/TerraFirmaCraft#2394]
I run a modpsck including both Valkyrien Skies and TFC as well as many other mods however Giant kelp flowers as they are considered solid blocks, prevent Valkyrien skies/Eureka ships to go forward and cause them to get stuck. Looking for a possible way to limit how tall/close to the waters surface they can grow.

**Comment by alcatrazEscapee** [comment]
We use the issue tracker exclusively for bug reports, not suggestions or support requests. This post would be more suitable for our [discord](https://discord.gg/PRuAKvY).
