### ISSUE TITLE
Putting an item in a donkey's inventory crashes the game 

### ISSUE THREAD

**Issue by ISOUL22** [TerraFirmaCraft/TerraFirmaCraft#2395]
I gave the donkey a chest on 2.2.15 then updated from 2.2.15 to 2.2.20 and now any time I try to put an item in the donkey's inventory the game crashes.

Here is the crash log:
https://pastebin.com/SeLXAP1d
file:
[crash-2023-05-11_02.51.26-client.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/11450885/crash-2023-05-11_02.51.26-client.txt)

**Comment by atlanta0** [comment]
I gave a donkey a chest in 2.2.20 and this bug happened as well.
