### ISSUE TITLE
(minor) information missing in animal husbandry

### ISSUE THREAD

**Issue by SarixInTheHouse** [TerraFirmaCraft/TerraFirmaCraft#2399]
it's quite a small thing that I noticed recently.
- The page for Musk Ox does not state how long it takes for their wool to regrow
- the page for Mules says "they can have grains and fruits". Seems to me like a mistake and should be "they eat"

I also think each page should state the required familiarity to use the animal (shear, milk, ride)

**Comment by Random-Cookie** [comment]
The two pages in question
![2023-05-15_10 22 24](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/11795182/867d1fdc-3afa-4d9b-b2c9-6ff02a71afeb)
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/a57d4e33f6858051f2ccecece3c0a2fad9435ff0/resources/generate_book.py#L706
![2023-05-15_10 22 47](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/11795182/d1389f26-c789-466a-8cd7-e224cc1e7532)
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/a57d4e33f6858051f2ccecece3c0a2fad9435ff0/resources/generate_book.py#L716

**Comment by Random-Cookie** [comment]
Updated Pages:
![2023-05-15_11 48 29](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/11795182/1a0c5b2b-b510-4a5b-aeb7-326e81daa4a3)
![2023-05-15_11 48 42](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/11795182/18d31810-5681-4187-baaf-dda6b3d19a16)
