### ISSUE TITLE
Suggestion - Using Flux in Small Vessel

### ISSUE THREAD

**Issue by jseaz73** [TerraFirmaCraft/TerraFirmaCraft#2401]
When making a mistake in an alloy mixture...
Here is what I did ... 
1 vessel - 500 mb of Silver
1 vessel - 500 mb of Gold
1 vessel - 1500 mb of Copper.

I mixed the gold and silver together  
then added the gold and silver to the copper ...
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/16529812/6ecfc7ec-4bca-4198-9171-9925ec1f5bbe)

but now I have 1500 of copper & 1000 of unknown ...  just like real life, adding flux to a molten vessel will cause the slag to form and be able to get separated

I suspect what I should have done is Add the Silver and the gold to the Copper ...

**Comment by alcatrazEscapee** [comment]
We use the issue tracker exclusively for bug reports, not suggestions or support requests. This post would be more suitable for our [discord](https://discord.gg/PRuAKvY).
