### ISSUE TITLE
[1.18.2] Crash on superflat + 180 mods

### ISSUE THREAD

**Issue by SheReyy** [TerraFirmaCraft/TerraFirmaCraft#2404]
Mc: 1.18.2
Forge: 40.2.0
Tfc: TerraFirmaCraft-Forge-1.18.2-2.2.21.jar

Hi. I just wanted to leave this log here as it might help the development of the mod. For context I was trying to make a flat world in a pack with 180 mods. I loaded a vanilla flat world in this pack. Everything was fine for 10 seconds. After that, the game crashed. This ofc doesn't happen with just TFC installed. I can also say that the game started to generate vanilla TFC terrain outside of my render distance (or some not-flat terrain, idk - If I get close to it, the game crashes).

Log file:
[2023-05-18-2.log](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/11503083/2023-05-18-2.log)

Crash:
[crash-2023-05-18_02.15.18-server.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/11503085/crash-2023-05-18_02.15.18-server.txt)

**Comment by skyloutyr** [comment]
I am able to reproduce the issue in a smaller modpack (~79 mods) in a non-flat world with tfc Forge-1.18.2-2.2.24. For me it didn't happen initially when generating the world. However, the issue appeared upon a client restart and re-log into the world.

Matching mods with the original report are:
 Rubidium Dynamic Lights
 Fastload-Reforged
 BlazeMap
 Clumps
 configured
 starlight
 ToastControl
 rubidium_extras
 waterflasks
 TFCGyres-OreHints
 TFCGyres-RockLayerSize
 MouseTweaks
 Jade
 Furniture Compat for TFC/Macaw
 AstikorCarts
 TFC Homestead
 Ferrite Core
 Firmalife
 TFC Casting with Channels
 

Crash:
[crash-2023-06-15_20.11.44-server.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/11760869/crash-2023-06-15_20.11.44-server.txt)

Log:
[latest.log](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/11760875/latest.log)

**Comment by alcatrazEscapee** [comment]
If anyone is able to get reproduction steps with just TFC, or TFC + a few (i.e. one or two) that conflict, that would be immensely helpful.

**Comment by alcatrazEscapee** [comment]
In testing, I can generate and re-enter superflat worlds fine in TFC. Chalking this up to "unknown mod conflict" which we can't feasibly address. If a more specific issue crops up I'll take a look at it.
