### ISSUE TITLE
[mod interop] Invalid Chunk Data when using Canary mod

### ISSUE THREAD

**Issue by magicus** [TerraFirmaCraft/TerraFirmaCraft#2406]
I found an issue when running TFC and [Canary](https://www.curseforge.com/minecraft/mc-mods/canary) at the same time. When you enter a newly created chunk, TFC consider it to always be of "Temperate" climate with 10.0°C average temperature. When using the F3 screen, "Invalid Chunk Data" is displayed. If you save and quit, and reload the world, the chunk gets populated properly with climate data.

**Comment by magicus** [comment]
Example screen short of F3 screen:

![TFC-Canary-bug](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/6209108/f0a834cc-0408-4aaf-9848-b41b80d14cfa)

**Comment by alcatrazEscapee** [comment]
This is quite likely something that Lithium breaks that we're relying on either as part of Forge or Minecraft functionality. If someone wants to look into this, there may be a specific optimization in Lithium that we can disable, or request to be disabled automatically, which can be tested via trying various things in the Lithium config.

**Comment by magicus** [comment]
My guess is that it some Forge behavior that changes; Lithium tries hard not to break vanilla functionality so if that part is properly ported to Forge, the problem is more likely to lie in the Forge-specific parts of Canary.

**Comment by Helinos** [comment]
Adding `mixin.world.player_chunk_tick=false` to canary.properties resolves this issue.

**Comment by magicus** [comment]
@DontStarve72 Thank you! I can indeed confirm that this helps.

Maybe this should be documented somewhere?

**Comment by alcatrazEscapee** [comment]
Looks like there does exist a system in 1.20 to ship a "default disabled features" file, but I can't be asked at the moment to figure it out. In any case, this is a user config, "disable part of canary that breaks TFC". as mentioned above.

**Comment by ctrlaltmilk** [comment]
This got fixed in [Canary 0.2.9](https://github.com/AbdElAziz333/Canary/commit/7fc0ca185b9b87deb9bdcd142723935969aafe9b#diff-09217614d81942efd6ad50f6f5b5f0ba2815dfc100a67d0637800e4d986a7248), btw.
