### ISSUE TITLE
[1.18.2] Server connection error

### ISSUE THREAD

**Issue by maxundeli** [TerraFirmaCraft/TerraFirmaCraft#2409]
When connecting to my own server, I get the following error:
internal exception: com.electronwill.nightconfig.fore.io.ParsingException: Invalid bare key: =

Server forge - 40.2.0
Client forge - 40.2.1
TFC - TerraFirmaCraft-Forge-1.18.2-2.2.22.jar

**Comment by alcatrazEscapee** [comment]
aef26db8490c3cad368f2f8e22ea52ebef14a48c
