### ISSUE TITLE
Possible rice seed duplication issue

### ISSUE THREAD

**Issue by alcatrazEscapee** [TerraFirmaCraft/TerraFirmaCraft#2415]
From discord

> im not sure if this has been reported, but i just found out you can duplicate rice seeds by emptying a bucket onto them

worth looking into.

**Comment by eerussianguy** [comment]
Can't reproduce this

**Comment by Imsvale** [comment]
I've done this as well. I'm on Auto-TerraFirmaCraft 1.8.2 (latest). Also did it on ATFC 1.8.1.

https://imgur.com/a/ySNATL3
