### ISSUE TITLE
no ItemStack option in mod config menus

### ISSUE THREAD

**Issue by eligarner23** [TerraFirmaCraft/TerraFirmaCraft#2418]
ok I'm not going crazy but apparently Minecraft's max items to stack is 64 but this mod somehow modifies that to be 32 items instead. any reason behind that? or it is to make stacking item's harder for the time being? at least put in the General or Misc a setting to use the vanilla item stacking procedures and to turn them on or off or to increase or decrease the value of the stacks as well, but this isn't all that important as I'm obviously using MC 1.12.2 and i suppose updating or backporting in a mod is a hard thing to do regardless i dealt with that back than with my mod too.

**Comment by alcatrazEscapee** [comment]
We are not supporting 1.12 anymore. Item sizes are set by size/weight and are editable in that version via Craft Tweaker, and in current 1.18.2 versions via datapacks.

**Comment by eligarner23** [comment]
Ok thanks i guess ill still use 1.18.2 or above, i'll be sure to check out Craft Tweaker wish me  luck.
