### ISSUE TITLE
32-bit floats appear to be used somewhere in the terrain generation code, resulting in broken terrain at high distances

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#2423]
Admittedly this will be a hard thing to come across in plain TFC, but vanilla's terrain generation (and basically everything else about vanilla) works completely fine at distances like these in modern versions.

After 16,777,216 blocks out, this becomes very, very obvious:
![2023-05-30_21 46 53](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/647b7319-2315-4beb-9c4f-a9a4de42f333)
![2023-05-30_21 47 01](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/62c95b42-254d-4bce-b682-4c66c33bfa26)

Fixable by either switching out the affected 32-bit floats with 64-bit doubles, or switching from a float to an int or long if the decimal part is irrelevant and only the integer part is actually used.

**Comment by alcatrazEscapee** [comment]
"somewhere"

**Comment by felix91gr** [comment]
Is this... is this Terrafirma's version of the Far Lands? x3

**Comment by alcatrazEscapee** [comment]
Not fixing in 1.18 as it's a pain in the ass, would require re-doing the work completely, and would constitute binary breaking literally everything.
