### ISSUE TITLE
Thatch bed produces items when broken in Creative mode

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#2426]
Almost all blocks and items are programmed to drop nothing when broken in Creative. This being an outlier seems wrong to me.
![2023-05-30_22 10 34](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/3331ad00-f3b9-4cd9-be9c-d939f9522480)

**Comment by alcatrazEscapee** [comment]
The thatch bed more closely resembles a chest than it does a vanilla bed, as it stores the original blocks and item used to create it in inventory, both of which are user-editable. So this is intentional, and consistent with vanilla in this regard.
