### ISSUE TITLE
Bookshelf top textures rotate depending on facing direction

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#2429]
As per the vanilla fix to https://bugs.mojang.com/browse/MC-257506 this might not be what is intended. Enabling uvlock in the blockstates files might fix this.
![2023-05-30_22 31 07](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/006dc12a-61ae-43e3-ac2b-a2313dadd7ea)

**Comment by eerussianguy** [comment]
Fixed with bookshelf rework in 1.20.x
