### ISSUE TITLE
Breaking ground items damages tools

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#243]
Not sure if this is intentional.

![2019-08-04_22 18 20](https://user-images.githubusercontent.com/52297970/62429379-013d6b80-b706-11e9-94d4-31877b85eea1.png)
![2019-08-04_22 18 26](https://user-images.githubusercontent.com/52297970/62429380-01d60200-b706-11e9-8c8a-bca2b4d031f3.png)
![2019-08-04_22 18 28](https://user-images.githubusercontent.com/52297970/62429382-04385c00-b706-11e9-984a-2c8d77f0bd90.png)

**Comment by alcatrazEscapee** [comment]
Should only happen with knives, and if so, it's related to breaking plant type items

**Comment by alcatrazEscapee** [comment]
As placed items have hardness, this is already consistent.
