### ISSUE TITLE
Certain TFC containers are not consistently accessible in Spectator mode

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#2430]
Crucibles and small vessels, unlike vanilla blocks that can be interacted with in Spectator mode, will not be outlined nor show the crosshair when targeted. In addition, whether they are openable or not seems inconsistent - I can lose the ability to open them in Spectator mode sometimes for reasons unknown.
![2023-05-30_22 34 49](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/966d5c9f-eac6-45d4-b384-f57770ab4993)
![2023-05-30_22 34 50](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/53479537-cdc4-4331-93f1-954ce098dcda)
![2023-05-30_22 34 51](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/d506381b-d720-44f3-a8ff-7a624feb7ea0)
![2023-05-30_22 34 52](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/237401bf-92f9-47e3-ac6e-adca1297ddc9)

**Comment by alcatrazEscapee** [comment]
Duplicate of #682
