### ISSUE TITLE
Bell molds are not sorted among other clay molds correctly

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#2431]
Most notably the unfired version is not grouped with the other unfired versions.
![2023-05-30_22 34 02](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/8eb11e52-9a5f-4cda-95e8-fdae28772cb1)

**Comment by alcatrazEscapee** [comment]
Yes, this is incidentally due to registration order determining creative tab placement. More flexibility is allowed in >1.19 and it may be explicitly ordered then.
