### ISSUE TITLE
Breaking the top half of a two-high water plant deletes the water from the bottom half

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#2436]
![2023-06-01_01 12 27](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/57365e05-456f-43e4-8ade-c729d6b29c7b)
![2023-06-01_01 12 28](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/bc4ad541-48d6-4e80-9094-068eca94cee0)

Breaking the lower half works fine.

**Comment by eerussianguy** [comment]
Update: this only happens in creative (lol)

**Comment by eerussianguy** [comment]
https://github.com/TerraFirmaCraft/TerraFirmaCraft/commit/7f2f0f336c2d78b18f4692adf45bee0bce30cb9c
