### ISSUE TITLE
Z-fighting when a scribing table is placed on top of another scribing table

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#2438]
![2023-05-31_13 20 25](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/fb7414c3-7ebc-410f-bd4b-d49358b84661)

**Comment by alcatrazEscapee** [comment]
Duplicate of #2434

**Comment by muzikbike** [comment]
This still happens in 2.2.29 despite #2434 being fixed.
