### ISSUE TITLE
Grass block texture is not rotated randomly

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#2439]
Vanilla's is. I'm not sure whether TFC's is intended to be or not.
![2023-05-31_12 53 32](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/185bb55e-1c97-43ad-8676-9ae1d04d3b17)

**Comment by alcatrazEscapee** [comment]
Duplicate of #2434

**Comment by muzikbike** [comment]
This still happens in 2.2.29 despite #2434 being fixed.
