### ISSUE TITLE
Hunger regenerates in Peaceful mode, but thirst does not

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#244]
![2019-08-04_22 22 03](https://user-images.githubusercontent.com/52297970/62429424-6b561080-b706-11e9-98c2-8af0063ca06b.png)
A bit inconsistent.

**Comment by alcatrazEscapee** [comment]
c9271fd76997c2b6c5e86e8b0f93637b74e3ea5a
