### ISSUE TITLE
Preserve Food Items With Vessel Bug

### ISSUE THREAD

**Issue by iamntinevitable** [TerraFirmaCraft/TerraFirmaCraft#2443]
You can give food items the "preserved" tag, making them last longer by stacking them to more than 16, then right-clicking them into a vessel. The 16 items that go into the vessel are preserved, but the remaining stack, (if you had 17 or more items) will also have the "preserved" tag. This isn't just a visual glitch, as far as I can tell, because the display for how longs the food will last until it rots is also changed. It's possible that it is purely a visual glitch and the food will rot as if it's unpreserved, but I haven't tested that.
![Screen Shot 2023-06-02 at 12 53 10 PM](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/135309458/f1b853a7-c5e9-4563-90a6-425aef0feca9)
The above screenshot shows rye grain, which I have had for several months, and when it isn't "preserved" it will rot in 5 months (roughly). The grain is outside of the vessel, yet is still noted as preserved.

**Comment by alcatrazEscapee** [comment]
This looks like a bug I fixed a month ago, in https://github.com/TerraFirmaCraft/TerraFirmaCraft/commit/9b9b4bcaa45a96bbfef8b5dcd798cd8d5df23796 and I can't reproduce this in TFC v2.2.23.
