### ISSUE TITLE
Compatibility with CatServer

### ISSUE THREAD

**Issue by Grodion08** [TerraFirmaCraft/TerraFirmaCraft#2444]
When i trying to start server with TFC on core "CatServer" i recieving that crash report

Description: Exception in server tick loop

java.lang.AssertionError: Whoopsie, we missed the bukkit.
	at net.minecraft.world.food.FoodData.<init>(FoodData.java:27) ~[server-1.18.2-20220404.173914-srg.jar%2365!/:?] {re:mixin,re:classloading}
	at net.dries007.tfc.common.capabilities.food.TFCFoodData.<init>(TFCFoodData.java:92) ~[TerraFirmaCraft-Forge-1.18.2-2.2.23.jar%2363!/:2.2.23] {re:mixin,re:classloading}
	at net.dries007.tfc.common.capabilities.food.TFCFoodData.replaceFoodStats(TFCFoodData.java:74) ~[TerraFirmaCraft-Forge-1.18.2-2.2.23.jar%2363!/:2.2.23] {re:mixin,re:classloading}
	at net.dries007.tfc.ForgeEventHandler.onNewPlayerInWorld(ForgeEventHandler.java:1174) ~[TerraFirmaCraft-Forge-1.18.2-2.2.23.jar%2363!/:2.2.23] {re:classloading}
	at net.dries007.tfc.ForgeEventHandler.onPlayerLoggedIn(ForgeEventHandler.java:1154) ~[TerraFirmaCraft-Forge-1.18.2-2.2.23.jar%2363!/:2.2.23] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%2313!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%2313!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%2313!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%2313!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.firePlayerLoggedIn(ForgeEventFactory.java:835) ~[forge-1.18.2-40.2.4-universal.jar%2370!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:283) ~[server-1.18.2-20220404.173914-srg.jar%2365!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:179) ~[server-1.18.2-20220404.173914-srg.jar%2365!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:166) ~[server-1.18.2-20220404.173914-srg.jar%2365!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10050_(ServerLoginPacketListenerImpl.java:95) ~[server-1.18.2-20220404.173914-srg.jar%2365!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.Connection.m_129483_(Connection.java:251) ~[server-1.18.2-20220404.173914-srg.jar%2365!/:?] {re:mixin,re:classloading}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:160) ~[server-1.18.2-20220404.173914-srg.jar%2365!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1206) ~[server-1.18.2-20220404.173914-srg.jar%2365!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:397) ~[server-1.18.2-20220404.173914-srg.jar%2365!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1112) ~[server-1.18.2-20220404.173914-srg.jar%2365!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:952) ~[server-1.18.2-20220404.173914-srg.jar%2365!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:312) ~[server-1.18.2-20220404.173914-srg.jar%2365!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Linux (amd64) version 5.15.0-71-generic
	Java Version: 17.0.7, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 2608773192 bytes (2487 MiB) / 5289017344 bytes (5044 MiB) up to 8388608000 bytes (8000 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) E-2136 CPU @ 3.30GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 10
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.30
	Number of physical packages: 4
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 24384.73
	Virtual memory used (MB): 10029.05
	Swap memory total (MB): 16384.00
	Swap memory used (MB): 1672.21
	JVM Flags: 2 total; -Xms128M -Xmx8000M
	CraftBukkit Information: 
   Running: CatServer version 1.18.2-6c3f5965 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) false
   Plugins: {}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { WAITING Finalizer: [java.base@17.0.7/java.lang.Object.wait(Native Method), java.base@17.0.7/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@17.0.7/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176), java.base@17.0.7/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:172)], RUNNABLE Signal Dispatcher: [], TIMED_WAITING Timer-0: [java.base@17.0.7/java.lang.Object.wait(Native Method), java.base@17.0.7/java.util.TimerThread.mainLoop(Timer.java:563), java.base@17.0.7/java.util.TimerThread.run(Timer.java:516)], RUNNABLE Server thread: [java.base@17.0.7/java.lang.Thread.dumpThreads(Native Method), java.base@17.0.7/java.lang.Thread.getAllStackTraces(Thread.java:1662), TRANSFORMER/forge@40.2.4/org.bukkit.craftbukkit.v1_18_R2.CraftCrashReport.get(CraftCrashReport.java:33), TRANSFORMER/forge@40.2.4/org.bukkit.craftbukkit.v1_18_R2.CraftCrashReport.get(CraftCrashReport.java:17), TRANSFORMER/minecraft@1.18.2/net.minecraft.SystemReport.m_143522_(SystemReport.java:65), TRANSFORMER/minecraft@1.18.2/net.minecraft.CrashReport.<init>(CrashReport.java:34), TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_206568_(MinecraftServer.java:1018), TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:970), TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:312), TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer$$Lambda$9051/0x0000000802227800.run(Unknown Source), java.base@17.0.7/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING Thread-1: [java.base@17.0.7/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.7/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:376), MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.file.FileWatcher$WatcherThread.run(FileWatcher.java:190)], RUNNABLE DestroyJavaVM: [], WAITING Log4j2-AsyncAppenderEventDispatcher-1-AsyncFile: [java.base@17.0.7/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.7/java.util.concurrent.locks.LockSupport.park(LockSupport.java:341), java.base@17.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(AbstractQueuedSynchronizer.java:506), java.base@17.0.7/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463), java.base@17.0.7/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434), java.base@17.0.7/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1623), java.base@17.0.7/java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:420), MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.0/org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.dispatchAll(AsyncAppenderEventDispatcher.java:71), MC-BOOTSTRAP/org.apache.logging.log4j.core@2.17.0/org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.run(AsyncAppenderEventDispatcher.java:63)], RUNNABLE Netty Epoll Server IO #1: [TRANSFORMER/forge@40.2.4/net.minecraftforge.registries.NamespacedDefaultedWrapper.getId(NamespacedDefaultedWrapper.java:131), TRANSFORMER/forge@40.2.4/net.minecraftforge.registries.NamespacedDefaultedWrapper.m_7447_(NamespacedDefaultedWrapper.java:33), TRANSFORMER/minecraft@1.18.2/net.minecraft.world.item.Item.m_41393_(Item.java:73), TRANSFORMER/minecraft@1.18.2/net.minecraft.network.FriendlyByteBuf.writeItemStack(FriendlyByteBuf.java:457), TRANSFORMER/minecraft@1.18.2/net.minecraft.network.FriendlyByteBuf.m_130055_(FriendlyByteBuf.java:443), TRANSFORMER/minecraft@1.18.2/net.minecraft.world.item.crafting.Ingredient$$Lambda$10268/0x000000080263ef88.accept(Unknown Source), TRANSFORMER/minecraft@1.18.2/net.minecraft.network.FriendlyByteBuf.m_178352_(FriendlyByteBuf.java:130), TRANSFORMER/minecraft@1.18.2/net.minecraft.world.item.crafting.Ingredient.m_43923_(Ingredient.java:118), TRANSFORMER/minecraft@1.18.2/net.minecraft.world.item.crafting.ShapelessRecipe$Serializer.m_6178_(ShapelessRecipe.java:139), TRANSFORMER/minecraft@1.18.2/net.minecraft.world.item.crafting.ShapelessRecipe$Serializer.m_6178_(ShapelessRecipe.java:93), TRANSFORMER/minecraft@1.18.2/net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.m_179469_(ClientboundUpdateRecipesPacket.java:52), TRANSFORMER/tfc@2.2.23/net.dries007.tfc.common.recipes.DelegateRecipe$Serializer.toNetwork(DelegateRecipe.java:116), TRANSFORMER/tfc@2.2.23/net.dries007.tfc.common.recipes.DelegateRecipe$Serializer.m_6178_(DelegateRecipe.java:59), TRANSFORMER/minecraft@1.18.2/net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.m_179469_(ClientboundUpdateRecipesPacket.java:52), TRANSFORMER/minecraft@1.18.2/net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket$$Lambda$10279/0x000000080263cc58.accept(Unknown Source), TRANSFORMER/minecraft@1.18.2/net.minecraft.network.FriendlyByteBuf.m_178352_(FriendlyByteBuf.java:130), TRANSFORMER/minecraft@1.18.2/net.minecraft.network.protocol.game.ClientboundUpdateRecipesPacket.m_5779_(ClientboundUpdateRecipesPacket.java:27), TRANSFORMER/forge@40.2.4/net.minecraftforge.network.filters.VanillaPacketSplitter.appendPackets(VanillaPacketSplitter.java:68), TRANSFORMER/forge@40.2.4/net.minecraftforge.network.filters.ForgeConnectionNetworkFilter.splitPacket(ForgeConnectionNetworkFilter.java:61), TRANSFORMER/forge@40.2.4/net.minecraftforge.network.filters.ForgeConnectionNetworkFilter$$Lambda$10231/0x0000000802633b30.accept(Unknown Source), TRANSFORMER/forge@40.2.4/net.minecraftforge.network.filters.VanillaPacketFilter.encode(VanillaPacketFilter.java:61), TRANSFORMER/forge@40.2.4/net.minecraftforge.network.filters.VanillaPacketFilter.encode(VanillaPacketFilter.java:24), MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89), MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717), MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764), MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790), MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758), MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808), MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025), MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306), TRANSFORMER/minecraft@1.18.2/net.minecraft.network.Connection.m_178303_(Connection.java:224), TRANSFORMER/minecraft@1.18.2/net.minecraft.network.Connection.lambda$sendPacket$8(Connection.java:213), TRANSFORMER/minecraft@1.18.2/net.minecraft.network.Connection$$Lambda$10163/0x0000000802617390.run(Unknown Source), MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164), MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469), MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384), MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986), MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74), java.base@17.0.7/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING Timer-1: [java.base@17.0.7/java.lang.Object.wait(Native Method), java.base@17.0.7/java.util.TimerThread.mainLoop(Timer.java:563), java.base@17.0.7/java.util.TimerThread.run(Timer.java:516)], RUNNABLE Notification Thread: [], RUNNABLE FileSystemWatchService: [java.base@17.0.7/sun.nio.fs.LinuxWatchService.poll(Native Method), java.base@17.0.7/sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:314), java.base@17.0.7/java.lang.Thread.run(Thread.java:833)], RUNNABLE FileSystemWatchService: [java.base@17.0.7/sun.nio.fs.LinuxWatchService.poll(Native Method), java.base@17.0.7/sun.nio.fs.LinuxWatchService$Poller.run(LinuxWatchService.java:314), java.base@17.0.7/java.lang.Thread.run(Thread.java:833)], RUNNABLE Netty Epoll Server IO #0: [MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.channel.epoll.Native.epollWait(Native Method), MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.channel.epoll.Native.epollWait(Native.java:192), MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.channel.epoll.Native.epollWait(Native.java:185), MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.channel.epoll.EpollEventLoop.epollWaitNoTimerChange(EpollEventLoop.java:290), MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:347), MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986), MC-BOOTSTRAP/io.netty.all@4.1.68.Final/io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74), java.base@17.0.7/java.lang.Thread.run(Thread.java:833)], TIMED_WAITING Common-Cleaner: [java.base@17.0.7/java.lang.Object.wait(Native Method), java.base@17.0.7/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155), java.base@17.0.7/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140), java.base@17.0.7/java.lang.Thread.run(Thread.java:833), java.base@17.0.7/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:162)], TIMED_WAITING Spigot Watchdog Thread: [java.base@17.0.7/java.lang.Thread.sleep(Native Method), TRANSFORMER/forge@40.2.4/org.spigotmc.WatchdogThread.run(WatchdogThread.java:84)], RUNNABLE Reference Handler: [java.base@17.0.7/java.lang.ref.Reference.waitForReferencePendingList(Native Method), java.base@17.0.7/java.lang.ref.Reference.processPendingReferences(Reference.java:253), java.base@17.0.7/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:215)], TIMED_WAITING Timer hack thread: [java.base@17.0.7/java.lang.Thread.sleep(Native Method), TRANSFORMER/minecraft@1.18.2/net.minecraft.Util$8.run(Util.java:628)], TIMED_WAITING process reaper: [java.base@17.0.7/jdk.internal.misc.Unsafe.park(Native Method), java.base@17.0.7/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252), java.base@17.0.7/java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:401), java.base@17.0.7/java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:903), java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1061), java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1122), java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), java.base@17.0.7/java.lang.Thread.run(Thread.java:833)], RUNNABLE Server console handler: [java.base@17.0.7/java.io.FileInputStream.read0(Native Method), java.base@17.0.7/java.io.FileInputStream.read(FileInputStream.java:228), MC-BOOTSTRAP/jline.terminal@3.12.1/org.jline.terminal.impl.AbstractPty$PtyInputStream.read(AbstractPty.java:73), MC-BOOTSTRAP/jline.terminal@3.12.1/org.jline.utils.NonBlockingInputStream.read(NonBlockingInputStream.java:62), MC-BOOTSTRAP/jline.terminal@3.12.1/org.jline.utils.NonBlocking$NonBlockingInputStreamReader.read(NonBlocking.java:168), MC-BOOTSTRAP/jline.terminal@3.12.1/org.jline.utils.NonBlockingReader.read(NonBlockingReader.java:57), MC-BOOTSTRAP/jline.reader@3.12.1/org.jline.keymap.BindingReader.readCharacter(BindingReader.java:133), MC-BOOTSTRAP/jline.reader@3.12.1/org.jline.keymap.BindingReader.readBinding(BindingReader.java:110), MC-BOOTSTRAP/jline.reader@3.12.1/org.jline.keymap.BindingReader.readBinding(BindingReader.java:61), MC-BOOTSTRAP/jline.reader@3.12.1/org.jline.reader.impl.LineReaderImpl.doReadBinding(LineReaderImpl.java:848), MC-BOOTSTRAP/jline.reader@3.12.1/org.jline.reader.impl.LineReaderImpl.readBinding(LineReaderImpl.java:868), MC-BOOTSTRAP/jline.reader@3.12.1/org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:575), MC-BOOTSTRAP/jline.reader@3.12.1/org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:418), TRANSFORMER/forge@40.2.4/net.minecraftforge.server.console.TerminalHandler.handleCommands(TerminalHandler.java:46), TRANSFORMER/minecraft@1.18.2/net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:103)],}
   Recent tasks from 17450-17480{}
   Force Loaded Chunks: { world: {}, DIM-1: {}, DIM1: {},}
	Server Running: true
	Player Count: 1 / 20; [ServerPlayer['ThisKRuT'/22, l='ServerLevel[world]', x=-4247.15, y=79.00, z=-5871.52](ThisKRuT at -4247.147805181049,79.0,-5871.520033023379)]
	Data Packs: vanilla, mod:domum_ornamentum (incompatible), mod:structurize (incompatible), mod:forge, mod:tfc, mod:patchouli (incompatible), mod:blockui (incompatible), mod:multipiston (incompatible), mod:minecolonies (incompatible), mod:jei (incompatible), mod:cloth_config (incompatible), mod:architectury (incompatible), mod:antiqueatlas (incompatible), file/bukkit (incompatible)
	World Generation: Experimental
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		server-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: NOSIGNATURE
		domum_ornamentum-1.18.2-1.0.50-ALPHA-universal.jar|Domum Ornamentum              |domum_ornamentum              |1.18.2-1.0.50-ALPHA |DONE      |Manifest: NOSIGNATURE
		structurize-1.18.2-1.0.424-ALPHA (1).jar          |Structurize                   |structurize                   |1.18.2-1.0.424-ALPHA|DONE      |Manifest: NOSIGNATURE
		cloth-config-6.4.90-1.18-forge (1).jar            |Cloth Config v4 API           |cloth_config                  |6.4.90              |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.2.4-universal.jar                 |Forge                         |forge                         |40.2.4              |DONE      |Manifest: NOSIGNATURE
		TerraFirmaCraft-Forge-1.18.2-2.2.23.jar           |TerraFirmaCraft               |tfc                           |2.2.23              |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.18.2-71.1 (1).jar                     |Patchouli                     |patchouli                     |1.18.2-71.1         |DONE      |Manifest: NOSIGNATURE
		blockui-1.18.2-0.0.71-ALPHA.jar                   |UI Library Mod                |blockui                       |1.18.2-0.0.71-ALPHA |DONE      |Manifest: NOSIGNATURE
		multi-piston-1.18.2-1.2.15-ALPHA (1).jar          |Multi-Piston                  |multipiston                   |1.18.2-1.2.15-ALPHA |DONE      |Manifest: NOSIGNATURE
		minecolonies-1.18.2-1.0.1428-BETA.jar             |MineColonies                  |minecolonies                  |1.18.2-1.0.1428-BETA|DONE      |Manifest: NOSIGNATURE
		architectury-4.11.93-forge-1.18.2.jar             |Architectury                  |architectury                  |4.11.93             |DONE      |Manifest: NOSIGNATURE
		antiqueatlas-7.1.1-forge-mc1.18.2 (1).jar         |Antique Atlas                 |antiqueatlas                  |7.1.1-forge-mc1.18.2|DONE      |Manifest: NOSIGNATURE
		jei-1.18.2-forge-10.2.1.1004.jar                  |Just Enough Items             |jei                           |10.2.1.1004         |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: a8e4a5c6-8da4-47ed-8685-5750e098fd87
	FML: 23.05.22-1
	Forge: net.minecraftforge:40.2.4

**Comment by alcatrazEscapee** [comment]
We do not support custom server software as it has a tendency to cause problems with mods, and has done in the past for us. You may find help reporting the issue to the server software.
