### ISSUE TITLE
Patchouli Field Guide Loading Error

### ISSUE THREAD

**Issue by hockeyfamily07** [TerraFirmaCraft/TerraFirmaCraft#2447]
![1](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/136025990/ca29340b-0156-4a68-9dbc-2ee64a46e6ca)
![2](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/136025990/f1661f21-fb8f-4a25-9391-61c25b922f50)
![3](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/136025990/61ad075b-2fda-418d-af0f-2dbdadb553e8)

Was working fine a couple days ago, updated all mods and forge then the book stopped working. Forgot which version I started on but I tried combinations of old versions of TFC and patchouli. Screenshots are from Forge 40.2.9, TFC 2.2.24, Create 0.5.1.b, and Patchouli 71.1.

If anyone else is having issues this github post has help me in the meantime.
https://terrafirmacraft.github.io/Field-Guide/en_us/

Not sure why I cant add labels, sorry.

**Comment by alcatrazEscapee** [comment]
This is not a TFC issue, as you are explicitly trying to load a page added by an addon or modpack, as we do not have a page called `create_integration/ore_refining`.

This is either a problem because you updated mods or with your modpack, and I suggest taking the issue to them.
