### ISSUE TITLE
Mule froze and disappeared after putting saddle and chest on it

### ISSUE THREAD

**Issue by Imsvale** [TerraFirmaCraft/TerraFirmaCraft#2448]
I had a mule at 100 familarity, and I put a saddle on it, and then a chest. The mule then froze completely, I couldn't mount it or open its inventory. I relogged and it had vanished.

Auto-TerraFirmaCraft v1.8.2.

[latest.log](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/11701810/latest.log)

**Comment by Imsvale** [comment]
And now my old donkey has frozen as well. Wonder if it has something to do with the deployer with shears I have placed in the pen (for shearing the sheep).

Yep, it gets stuck under the deployer with shears with its head down. Probably if I relog it will disappear, like the mule did. Breaking the deployer brings it back to life and I can interact with it again.

Video clip: https://youtu.be/-t1CsDs1HLM

Happens with an empty deployer as well, so it's not the shears. Deployer trying to interact with the animal's inventory?

Does this belong here or with the ATFC guys?

**Comment by Imsvale** [comment]
Fun fact: Rotating the deployer also causes the donkey to sort of rotate with it. The donkey stays frozen, even though the deployer isn't interacting with it anymore.

**Comment by copygirl** [comment]
Sounds like the deployer's fake player managed to mount the donkey somehow. And not sure if related, but if I remember correctly, mounts will log off along with the player.

**Comment by alcatrazEscapee** [comment]
Closing as we're not supporting 1.18 anymore, given the uncertain issue status. If this occurs in 1.20.1, please open a separate issue with reproduction information.
