### ISSUE TITLE
Drinking water with bare hands shows the player's arm swinging; drinking with item in hand does not

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#245]
Again, this feels inconsistent.

![2019-08-04_22 24 12](https://user-images.githubusercontent.com/52297970/62429459-d0116b00-b706-11e9-9043-0717e34d93b7.png)
![2019-08-04_22 24 18](https://user-images.githubusercontent.com/52297970/62429460-d0116b00-b706-11e9-8821-45b443ab378f.png)

**Comment by alcatrazEscapee** [comment]
You're actually swinging your offhand if this happens, since you can't drink while holding an item. So the solution is either to disable the ability to drink with your offhand, or have this problem.

**Comment by alcatrazEscapee** [comment]
d482668be4a24d53c487c051a1afd736779d1201
