### ISSUE TITLE
Items placed on ground (using V key) occasionally disappear when breaking them

### ISSUE THREAD

**Issue by iamntinevitable** [TerraFirmaCraft/TerraFirmaCraft#2450]
Some important notes: this happened in Auto TerrafFirmaCraft (which is TFC with create integration) in ATFC V1.8.1 which uses TFC 2.2.15. I have since updated to ATFC V1.8.2, using TFC 2.2.21, and I haven't managed to recreate it in this version. I thought it happened again recently as I lost my pickaxe, but it turns out I had misplaced it (an explanation for the edit to this issue). The incident I wrote about below, however, had no possibility of me misplacing the items, as they disappeared after I saw them as items in the world.

I have had difficulty recreating this bug, but when it happened, I was using six or seven pit kilns to fire molds for tools along with several vessels. I collected the vessels from a few of the pit kilns but when I reached the tool molds, the items were there, and I didn't use the right-click function to pick up the items, I broke them, dropping all four items simultaneously. I saw the items appear in the world very briefly, but they disappeared and didn't go into my inventory. I was in survival, and I had sufficient open inventory slots to accommodate them, they just disappeared.

**Comment by alcatrazEscapee** [comment]
> I haven't managed to recreate it in this version

So, presumed fixed in new version, unless you can provide a reproduction case using TFC alone with said new version. Without an actual reproduction case there's jack we can do here.
