### ISSUE TITLE
Leather Knapping Bug

### ISSUE THREAD

**Issue by atlanta0** [TerraFirmaCraft/TerraFirmaCraft#2452]
As soon as one square is removed the GUI is closed and the leather is destroyed WHEN HOLDING A SINGLE LEATHER.

**Comment by artemisgreyrat** [comment]
This is still an Issue even while running the newest version of the 1.18.2 ver2.2.26

**Comment by alcatrazEscapee** [comment]
hmm, can confirm.

**Comment by alcatrazEscapee** [comment]
So it seems to happen only in prod now, which explains why my last fix in theory, did fix it. It doesn't happen in dev because of an obfuscation issue.
