### ISSUE TITLE
Plants can generate naturally on top of some blocks they cannot be placed on

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#2454]
![2023-06-16_15 06 23](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/902f642b-48b3-49c2-9147-9b520f55797e)

**Comment by alcatrazEscapee** [comment]
This is an artifact of non ordered feature generation, in this case due to erosion feature. There's nothing planned to deal with this and it's a non-issue in practice. (See #1972)
