### ISSUE TITLE
When breaking many two block tall plants, only the top half appears to produce particles

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#2457]
![2023-06-16_15 19 29](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/75ff1bb2-7220-4075-b8e2-836f51c62781)
![2023-06-16_15 19 31](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/9f0123a7-e8d3-4818-9fc9-6eb78502b6ba)
![2023-06-16_15 19 40](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/a02e0b67-7fcf-4dfa-89d0-8186376f2543)
![2023-06-16_15 19 41](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/668fa282-fb13-4ecd-b1ab-694352734fc0)

**Comment by eerussianguy** [comment]
Can you confirm this in survival?

**Comment by muzikbike** [comment]
Yes.

**Comment by eerussianguy** [comment]
Unable to reproduce in survival
