### ISSUE TITLE
Missing texture plane on maiden pink

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#2459]
This is an issue with the vanilla model (https://bugs.mojang.com/browse/MC-262720).

![2023-06-16_15 35 48](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/593d9a14-56e7-4682-811b-36506128e31d)

**Comment by eerussianguy** [comment]
I'm going to be redoing maiden pink when we port, so for now this is WAI
