### ISSUE TITLE
Outer faces of thatch blocks are not culled by other adjacent thatch blocks

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#2460]
This is inconsistent with vanilla powder snow, in which case the outer faces are culled by other blocks of the same type, as expected.
![2023-06-16_15 33 34](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/def8a8b8-1cf4-4d63-bfd8-82e8d57c57f4)
![2023-06-16_15 34 03](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/a72d742b-aff7-4ff9-a704-0a96c08b699d)

Note that the outer faces of thatch are also culled by solid blocks (as they should), *unlike* vanilla powder snow:
![2023-06-16_15 40 56](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/36ed0cf5-d771-466f-bafd-c787594a921f)

**Comment by eerussianguy** [comment]
This is intended, because when you walk inside powder snow you can see through all the other powder snows adjacent to you, which seems weird to me.
