### ISSUE TITLE
Some stone objects still have awkward names

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#2461]
Extension of the since-resolved #2427. I should probably try to be a bit more in-depth...
![2023-06-16_15 51 26](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/28600d2e-e2c7-49d8-b796-579bb451fc6d)
![2023-06-16_15 51 30](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/9a7956ee-8eb2-4387-8292-bf3857f2e4c1)

**Comment by eerussianguy** [comment]
You wanted the naming convention inverted... I inverted it... we're not doing it case by case. I'll remove some of the pluralization though but 'cobble marble slab' is staying
