### ISSUE TITLE
Double slabs made from smooth blocks of stone should look like two stacked slabs

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#2462]
A simple enough task, I should probably be able to get it done given a day or so. Each smooth double slab will need a new dedicated side texture and simple block model so that they match up with normal vanilla double slabs.
![2023-06-16_15 58 55](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/596a9432-71f2-42bb-afac-8feb5ed97344)
![2023-06-16_15 58 55_2](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/12ec2622-aa41-4711-9cbb-d29e8566773a)

This issue can be assigned to me basically instantly.

**Comment by alcatrazEscapee** [comment]
This is a suggestion, not an issue.
