### ISSUE TITLE
Charcoal pile problems

### ISSUE THREAD

**Issue by farms4life2016** [TerraFirmaCraft/TerraFirmaCraft#2467]
- When a falling entity (such as cobblestone) lands on a charcoal pile, the entity turns into an item instead of crushing the charcoal pile.
- When the block below a charcoal pile is removed, the charcoal pile will break but only drop 1 piece of charcoal, regardless of how many charcoal layers were in the pile
- Charcoal can be duped with the following setup:
![2023-06-21_20 44 29](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/72057188/5fbdb41e-5fe8-43f4-b8ab-cdadc68fb698)
A piece of charcoal is duped every time the sticky piston retracts. The charcoal pile will vanish instead if the redstone clock is too fast, which is why each repeater is set to 4 ticks.

Additional information: these potential bugs were discovered while playing the latest version of `Auto-TerraFirmaCraft`, a modpack made by `enigmaomega_` (which can be found on the CurseForge launcher). The version of TFC in the modpack is `TerraFirmaCraft-Forge-1.18.2-2.2.21.jar`. It's possible that these bugs have already been fixed in the latest version of TFC.

**Comment by alcatrazEscapee** [comment]
> When a falling entity (such as cobblestone) lands on a charcoal pile, the entity turns into an item instead of crushing the charcoal pile.

Intentional for falling blocks with lower toughness.

> When the block below a charcoal pile is removed, the charcoal pile will break but only drop 1 piece of charcoal

Intentional

> Charcoal can be duped

Very much not intentional.
