### ISSUE TITLE
Guide book shows certain items that currently aren't ingame

### ISSUE THREAD

**Issue by iamntinevitable** [TerraFirmaCraft/TerraFirmaCraft#2469]
In Advanced mechanics > Composter you can find what kinds of things can be composted, but certain things listed can't be obtained ingame, bell peppers, for example. It's a minor thing and I don't know if these are planned to be implemented but it's a small enhancement thing if it requires a fix.
![Screen Shot 2023-06-23 at 2 38 09 PM](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/135309458/32a9299f-516e-4dc9-8ea5-260f37e48a59)
![Screen Shot 2023-06-23 at 2 37 59 PM](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/135309458/c96ca376-9ee0-4585-9e41-a144ddce8d26)
![Screen Shot 2023-06-23 at 2 37 56 PM](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/135309458/45393e0c-9edb-4269-b113-f9fb2bf2c1a9)

**Comment by alcatrazEscapee** [comment]
So these are vaguely, "planned to be implemented", they just are not obtainable. Given that this just lists the contents of a tag, I don't think unimplementing these further is of any good sense. @eerussianguy thoughts, otherwise I'd say this is "working as intended, pending possible future implementation of these plants".

**Comment by eerussianguy** [comment]
It would be weird for us to
a) ask patchouli to check if items have a creative mode tab before displaying them / override that behavior ourselves somehow
b) have a separate tag for display in patchy
c) break/make needlessly harder any addon/datapack that may want to implement bell peppers by removing their attached data
