### ISSUE TITLE
`MealModifier.portions()` is public but `MealModifier.MealPortion` is private

### ISSUE THREAD

**Issue by Montessquio** [TerraFirmaCraft/TerraFirmaCraft#2475]
In [MealModifier.java](https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/1.18.x/src/main/java/net/dries007/tfc/common/recipes/outputs/MealModifier.java) the portions of a meal modifier may be accessed via `MealModifier.portions()`, however [the underlying record-class is private](https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/61419d89f4ac0812fd594ee940494db0d408ee4f/src/main/java/net/dries007/tfc/common/recipes/outputs/MealModifier.java#L147). This makes it impossible for other code to interact with meal portion data in-code.

Referencing the latest 1.18.2 version of TFC available from CurseForge, the following snippet will produce the compiler error `MealPortion has private access in MealModifier`.

```java
MealModifier = somehowGetAMealModifierInstance();
for(var portion : meal.portions()) {
    doSomethingWith(portion);
}
```

Since the portions list is already exposed, maybe it would be a good idea to change `MealPortion` to `public`?

**Comment by alcatrazEscapee** [comment]
What on earth for?

**Comment by Montessquio** [comment]
I'm trying to make a KubeJS plugin which exposes TerraFirmaCraft crafting to KubeJS scripts. In order to serialize/deserialize recipe modifiers I need to be able to access their data from from my code.
Although, this does stop any mod from dealing with meal portions programmatically in general, not just ones looking to interfere with the data loading process.
