### ISSUE TITLE
[Enhancement][1.18.x] bring back weld button in anvil UI

### ISSUE THREAD

**Issue by Kenshij** [TerraFirmaCraft/TerraFirmaCraft#2477]
Please bring back the weld button in the anvil ui. It's so unnecessary complicated to access the anvil ui to place metal bars, take hammer out, wait until hammer is charged up and then smack the anvil, access it to place hammer back.

**Comment by alcatrazEscapee** [comment]
No. Consider alternatives:

- You can do all your working with a hammer in the main hand - if there's no hammer in the hammer slot, one in your main hand will be used instead.
- You can do welding entirely without opening the UI, by right clicking to add and remove items.
