### ISSUE TITLE
Suggestion: magma blocks stay lit indefinitely

### ISSUE THREAD

**Issue by carrotbane2** [TerraFirmaCraft/TerraFirmaCraft#2478]
In vanilla, magma blocks stay lit forever, like netherrack. Is this a deliberate omission in TFC, or just overlooked? While it does provide a cheap permanent light source, I personally think the fire hazard (and risk of hyperthermia, when you use Ambiental) balances it out.

**Comment by alcatrazEscapee** [comment]
We use the issue tracker exclusively for bug reports, not suggestions or support requests. This post would be more suitable for our [discord](https://discord.gg/PRuAKvY)
