### ISSUE TITLE
When a tree is cut down, only the targeted log shows breaking particles

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#248]
All the logs should, since they're being broken.

![2019-08-04_23 12 43](https://user-images.githubusercontent.com/52297970/62429921-7bbdb980-b70d-11e9-9cf6-5fb4be91e255.png)

**Comment by alcatrazEscapee** [comment]
Except that would be a hell of a lot of particles, most of which aren't visible.

The closest thing to vanilla would be stacking a bunch of signs and breaking the one holding all of them, which only causes particles for the one being broken.

**Comment by muzikbike** [comment]
That's not the case in 1.13+.

**Comment by alcatrazEscapee** [comment]
Then it will get changed when TFC is in 1.13+. We aren't backporting vanilla changes to 1.12.
