### ISSUE TITLE
[Suggestion] Dog armors for protecting dogs when fighting

### ISSUE THREAD

**Issue by chemlzh** [TerraFirmaCraft/TerraFirmaCraft#2481]
There are some dog armor mods for vanilla, however these mods can't be used for TFC dogs. I think it would be useful if the mod adds dog armor for TFC dogs, so that they can get less damage when fighting.

**Comment by alcatrazEscapee** [comment]
We use the issue tracker exclusively for bug reports, not suggestions or support requests. This post would be more suitable for our [discord](https://discord.gg/PRuAKvY).
