### ISSUE TITLE
Wolves and Direwolves stuck in their sleeping animation but still move

### ISSUE THREAD

**Issue by Duck986** [TerraFirmaCraft/TerraFirmaCraft#2483]
Video: https://tempclip.com/wQk4v7Fi6VOHTkJ/watch

I'm not sure how this works, but sometimes I randomly find wolves that move or attack while in their sleeping animation

**Comment by h4ppyboy** [comment]
Cringe bug, getting attacked by sleeping bears, sabretooths and direwolves getting me mad

**Comment by eerussianguy** [comment]
Duplicate of #2354
