### ISSUE TITLE
[enhancement] allow flint and steel and fire charges to create firepit

### ISSUE THREAD

**Issue by Apot98** [TerraFirmaCraft/TerraFirmaCraft#2488]
under 1.18.2-2.2.27 flint and steel and fire charges can only re-ignite existing firepit, if trying to create a firepit with these fire starters, only a fire block will be created and all the item are lost.

**Comment by alcatrazEscapee** [comment]
We use the issue tracker exclusively for bug reports, not suggestions or support requests. This post would be more suitable for our [discord](https://discord.gg/PRuAKvY).
