### ISSUE TITLE
Horses cannot auto-step - intentional or bug?

### ISSUE THREAD

**Issue by cosmicdan** [TerraFirmaCraft/TerraFirmaCraft#2490]
Hi,

I have noticed that TFC horses do not have auto-step capability. Just wondering if this is an intentional design choice or a bug.

I have tried enabling Auto-jump in client settings and also editing jumpheight attribute via NBT Studio to no avail.

Thank you!

**Comment by alcatrazEscapee** [comment]
Cannot reproduce; multiple others in discord report that horses are capable of auto stepping, exactly as vanilla horses do. You may be trying to step onto something greater than a block high.

**Comment by cosmicdan** [comment]
Thank you for confirming. We finally found out it was a config issue with Pehkui - we made the horses a little smaller and this broke it :) apologies and thanks again!
