### ISSUE TITLE
Flower Charge banner pattern cannot be made with Oxeye Daisy + Paper

### ISSUE THREAD

**Issue by LammersInsects** [TerraFirmaCraft/TerraFirmaCraft#2497]
Although TFC has the items _Paper_ and _Oxeye daisy_, and according to JEI the recipe for the _Flower Charge Banner Pattern_ exists in TFC, the required ingredients are the Vanilla version of _Paper_ and _Oxeye daisy_ items, not the TFC version of those items. I would suggest to add the recipe for the TFC version of the items too. Thank you.

**Comment by alcatrazEscapee** [comment]
We use the issue tracker exclusively for bug reports, not suggestions or support requests. This post would be more suitable for our [discord](https://discord.gg/PRuAKvY).
