### ISSUE TITLE
Stacking certain types of berry bush causes visual gaps

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#2508]
Affects blackberries, raspberries, blueberries and elderberries.
![2023-09-07_20 19 29](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/d011b60d-bf75-4f14-a6c5-58ea66539d23)

**Comment by alcatrazEscapee** [comment]
This should not be placeable in this orientation.
