### ISSUE TITLE
Vanilla foxes cannot eat TFC berries

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#2509]
Not sure if this is relevant since TFC implements its own fox entity, but none of the berries added by the mod are part of the item tag #minecraft:fox_food.
![2023-09-07_20 16 30](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/77070ddd-0c0d-4bba-a929-840503e19bce)
![2023-09-07_20 16 51](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/66983ac5-0b37-4812-9ac1-6b385eae6f47)
![2023-09-07_20 16 52](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/1ac35e58-2a65-4bc3-a134-551cd25fdb58)

**Comment by alcatrazEscapee** [comment]
Vanilla foxes don't spawn; we have TFC foxes; don't care.
