### ISSUE TITLE
TFC light blocks are not shown by save mode structure blocks

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#2510]
Left 3 are TFC lights, right 2 are vanilla lights.
![2023-09-07_20 43 11](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52297970/75750902-6143-430e-b35e-80880b45e046)

**Comment by alcatrazEscapee** [comment]
In `StructureBlockRenderer`, vanilla explicitly checks for three blocks via `is` equality. This is such a niche concern it's not worth a mixin to the aforementioned class for this.
