### ISSUE TITLE
Bloomery rejecting input when lit

### ISSUE THREAD

**Issue by CaveNJ** [TerraFirmaCraft/TerraFirmaCraft#2511]
Using TFC in a modpack with create, firmalife, & homestead, among others. Whenever I fill the bloomery and try to light it, the block lit immediately disappears, dropping the contents at the bottom. It doesn't seem to matter what kind of iron I use, it's happening with rich ore, crushed iron ore, and tools. Tried filling the bottom with charcoal per 1.7.10 instructions, and input was no longer accepted.
![2023-09-16_11 14 21](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/127108007/ab83e958-1fd7-43d3-8f38-a3ff7dfd2326)
![2023-09-16_11 14 25](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/127108007/db2d483a-6ebb-4efd-bade-25003773077e)
![2023-09-16_11 14 40](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/127108007/c81ea264-cc7a-4a15-80bf-cd68bcf22fbc)
![2023-09-16_11 14 45](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/127108007/34fac366-8e98-44a5-ba17-a021398cd33e)
![2023-09-16_11 14 48](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/127108007/0bf30a06-0dd4-4a4c-8b68-8e1ace8a0366)
Originally encountered the issue in the 5/25 release, but it's happening with the latest release after I updated as well.

**Comment by alcatrazEscapee** [comment]
PEBKAC

See the [Field Guide](https://terrafirmacraft.github.io/Field-Guide/en_us/mechanics/bloomery.html)

> Light the **bloomery block**, and wait most of a day

The bloomery block - not the molten ore.
