### ISSUE TITLE
Pyrite not generating

### ISSUE THREAD

**Issue by Allmoz** [TerraFirmaCraft/TerraFirmaCraft#2525]
Hi,

It seems pyrite is not being generated with gold veins.

After some reading the code, in constants.py,  the pyrite generation is defined as part of native gold generation for  all the igneous rocks using  rock categories "['igneous_extrusive', 'igneous_intrusive']" for the spoiler_rocks:

https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/c3c78505ea4708a72c265130cbe84e2d72536aa7/resources/constants.py#L308

But at the moment of checking  those rocks in vein_ore_blocks in world_gen.py, the rocks categories are not being expanded to all the rock names, so it never generates that spoiler_ore:

https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/c3c78505ea4708a72c265130cbe84e2d72536aa7/resources/world_gen.py#L982

Pyrite is the only being affected right now, cose is the only one using a rock category in "spoiler_rocks".  Maybe expanding  spoiler_rocks with expand_rocks may be enough to solve it:

https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/c3c78505ea4708a72c265130cbe84e2d72536aa7/resources/world_gen.py#L1412

Cheers!

**Comment by Allmoz** [comment]
It seems it also should affect 1.20:

https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/b1f2590e2126c57be0f68f857814f799eed903d9/resources/world_gen.py#L1101C27-L1101C28

**Comment by alcatrazEscapee** [comment]
Yes, this is a known issue, it's not getting fixed in 1.18 due to affecting existing worlds, and is fixed in 1.20 by #2516

**Comment by Allmoz** [comment]
Nice, i reader a little and saw the todo in the spoiler_rock, i will wait.

Thanks!
