### ISSUE TITLE
Anvil Gui texture error

### ISSUE THREAD

**Issue by aliceingame** [TerraFirmaCraft/TerraFirmaCraft#2526]
TFC 1.18.2-2.2.30

There is an odd thing that show when the hammer icon "hit any" show in the instruction.

![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/4293373/e9cf3dc8-265d-499e-8982-7770db014511)

it seems to be this greyscale scroll in the texture
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/4293373/b8593522-7e4a-4993-8595-609b70e6f9f9)

**Comment by aliceingame** [comment]
Used color to define the zone for each icons.
Green is the hammer, blue the scroll, yellow is the overlap. Red was just to check the size.

So yes it's a texture problem, but also need to be fixed in the code to take different sections of the texture.

![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/4293373/1c7c0f1b-bc04-4e68-8131-4d4826eab579)
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/4293373/f65d7c26-57c8-48b0-88fa-d0956b8dfa9c)


![anvil](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/4293373/116b200a-1ed2-4a5b-9c93-e5ff389038a9)

**Comment by alcatrazEscapee** [comment]
Fixed in 1.20, given it's a minor texture error and can't be fixed without breaking existing texture packs (in which case is a "who breaks") not fixing for 1.18.
