### ISSUE TITLE
Incorrect generation of translateKey from ores from other mods during Prospecting

### ISSUE THREAD

**Issue by Exzept1on** [TerraFirmaCraft/TerraFirmaCraft#2528]
GTCEu uses a substitution system during the display of a localized string. Therefore, if the GTCEu ores add the `prospectable` tag, the following will be displayed, which is incorrect.

GTCEu lang file for stonetypes:
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52341158/e11c50bc-dc02-4a5c-8bb0-7acbce61b26b)

Error:
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52341158/af858e4f-6a5a-40dd-b63f-223a736f1dc5)

Versions: 1.18.2, 1.20.1-indev

**Comment by alcatrazEscapee** [comment]
Gross
