### ISSUE TITLE
Powderkeg texture error

### ISSUE THREAD

**Issue by aliceingame** [TerraFirmaCraft/TerraFirmaCraft#2529]
TFC 1.18.2-2.2.31

It's actually not a problem on the GUI texture but in how it is rendered.

Found this while updating my [resources pack](https://legacy.curseforge.com/minecraft/texture-packs/tfc-tng-alice-japanese-pack).

The button with the seal/unseat in the powder keg does not use the same behavior as the button in other interfaces like the barrel. Instead of only displaying the button on top of the GUI texture, it add something from a completely different texture on top of the GUI then add the seat button on top of that.

Using this modified texture (I removed the seal button and put the slot in green in the GUI), we can see there is an unrelated texture from elsewhere in my pack that show up.

The reason I noticed is that my texture use 16x16 button instead of 20x20, so for the border I see the border as it is in the GUI, but I see 1 pixel on each side as this unknown texture is 16x18.

![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/4293373/c8b7d426-0cf3-4508-8550-1d0f1d319309)

![powderkeg](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/4293373/28cdcee1-7935-4fe0-83ad-76d0eec1a26b)

For reference, here is my texture
Barrel
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/4293373/0d597435-1b8b-4602-8aa9-0b674655858f)

Powder keg
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/4293373/ca8a116d-794c-43ce-ab2d-c32478b19c8a)

texture
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/4293373/bdcb4c7d-e907-4cf4-bb4f-1cc10fefa255)

**Comment by alcatrazEscapee** [comment]
I think this `super` call is probably the culprit.

https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/c3c78505ea4708a72c265130cbe84e2d72536aa7/src/main/java/net/dries007/tfc/client/screen/button/PowderkegSealButton.java#L43
