### ISSUE TITLE
[TFC:TNG]:Time flow rate adjustment.

### ISSUE THREAD

**Issue by Jespericy** [TerraFirmaCraft/TerraFirmaCraft#2533]
I'd like to adjust the flow of time so that a day in the game is equal to 20 minutes in reality and becomes an hour. Because if it's in the server, his food will rot just too fast! But I used the original version and other mod methods and couldn't slow down his time flow, is there any way.

**Comment by alcatrazEscapee** [comment]
No

---

We use the issue tracker exclusively for bug reports, not suggestions or support requests. This type of post would be more suitable for our [discord](https://discord.gg/PRuAKvY).
