### ISSUE TITLE
Water color breakdown when installing Rubudium (Embeddium)

### ISSUE THREAD

**Issue by Exzept1on** [TerraFirmaCraft/TerraFirmaCraft#2536]
Rubudium: https://modrinth.com/mod/rubidium
Embeddium: https://modrinth.com/mod/embeddium (fork of Rubidium)

Poop water color xD

Version: TFC-1.20.1-3.0.0-beta

![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52341158/4d07ee6e-ac49-41a0-989f-f6a97c83a227)

**Comment by alcatrazEscapee** [comment]
Sodium how the f

**Comment by Exzept1on** [comment]
My mistake, water color works correctly with the latest version of embeddium (the water was brown on the old one), but the water connection still does not work correctly

![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52341158/1a5da8b3-0e8a-49d3-9c76-eb2bbb28bff0)

![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52341158/f7efd330-b24b-4d6b-9a4c-9cd6c47838df)
