### ISSUE TITLE
Untranslated langkey in some tooltips

### ISSUE THREAD

**Issue by Exzept1on** [TerraFirmaCraft/TerraFirmaCraft#2537]
Version: TFC-1.20.1-3.0.0-beta

Raw blocks:
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52341158/e0bad6c4-c4b4-454b-a729-34c3debd8978)

Hardened blocks:
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/52341158/728fbc6c-2bfa-49f2-8cb8-c46c3e134b0e)

Maybe some more, but I might not have noticed them.

**Comment by alcatrazEscapee** [comment]
Linked the wrong issue, fixed by d4d84242c0f1654d398068391ac727ceee07666f
