### ISSUE TITLE
(Forge bug, downgrade to 47.1.3) Crash in world generation: Feature order cycle detected

### ISSUE THREAD

**Issue by Imorby** [TerraFirmaCraft/TerraFirmaCraft#2539]
I need to know if I'm the only one having this problem with beta 1.20.1

**Comment by alcatrazEscapee** [comment]
Useless report without a crash log.

**Comment by DcNdrew** [comment]
[crash-2023-11-06_15.07.05-server.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/13267566/crash-2023-11-06_15.07.05-server.txt)

**Comment by alcatrazEscapee** [comment]
This is caused by a Forge/NeoForge bug in newer versions, please use **47.1.3** exactly.
