### ISSUE TITLE
Thatch allows rain to pass through

### ISSUE THREAD

**Issue by alcatrazEscapee** [TerraFirmaCraft/TerraFirmaCraft#2548]
If avoidable we should; this was fixable in previous versions, but I don't remember how. In 1.20 currently leaves (non-solid) cause rain to pass through (as they should), vanilla leaves (solid), don't.

**Comment by eerussianguy** [comment]
https://github.com/TerraFirmaCraft/TerraFirmaCraft/commit/7f7b354582612836e8f931e09311e5b72a824587
