### ISSUE TITLE
[1.20.1-3.0.1-beta] Gravity blocks do not recognize farmland as solid

### ISSUE THREAD

**Issue by Alex33212** [TerraFirmaCraft/TerraFirmaCraft#2551]
In 1.20.1-3.0.1-beta, when placing a gravity-affected block (dirt, cobble, etc) on top of a block next to tilled farmland, there is a chance that it "falls into" the space occupied by the farmland block, breaking it.

**Comment by alcatrazEscapee** [comment]
Duplicate of #886
