### ISSUE TITLE
[1.20.1-3.0.2-beta] TFC Fluids do not Display Properly in UI

### ISSUE THREAD

**Issue by Alex33212** [TerraFirmaCraft/TerraFirmaCraft#2555]
In TFC 1.20.1-3.0.2-beta, fluids other than water do not display in any UI elements, instead being completely invisible.

**Comment by eerussianguy** [comment]
https://github.com/TerraFirmaCraft/TerraFirmaCraft/commit/31c1da375786113e877f778bc8606deca7cb476e
