### ISSUE TITLE
Plant validity bar + tooltip need to be removed

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#256]
![2019-08-06_00 02 37](https://user-images.githubusercontent.com/52297970/62500284-a4ad7f80-b7dd-11e9-9967-c220e05d86e7.png)

**Comment by alcatrazEscapee** [comment]
imo it should just be turned into a tooltip - the hijacked durability bar doesn't fit to my tastes.

**Comment by alcatrazEscapee** [comment]
After some looking, I've found the entire tooltip / plant bar is broken and needs to be removed, as it's storing the validity as an instance property of the item, which will totally break as soon as multiple items are present in the world.
