### ISSUE TITLE
Sandwiches and soup "Never expire", according to Just Enough Items

### ISSUE THREAD

**Issue by MrHiTech123** [TerraFirmaCraft/TerraFirmaCraft#2560]
When I look at the recipes for soup and sandwiches in JEI, the outputted soup or sandwich has "Never Expires" in its tooltip. This led me to think that soup and sandwiches never expire, which obviously isn't true.

**Comment by alcatrazEscapee** [comment]
The alternative is having these expire and produce rotten food while in JEI which is an issue we've tried to avoid for a long time. We may be able to avoid rendering the tooltip though, I believe we already do the same with the creative inventory, but if it's not working as is, it's not likely to change.
