### ISSUE TITLE
Time stops advancing after game crash with rollback

### ISSUE THREAD

**Issue by jlbrewer** [TerraFirmaCraft/TerraFirmaCraft#2562]
I had a game crash (out of memory error, not a TFC problem) where I got rolled back a few minutes on reloading the game. Since then (and admittedly it took me a while to notice), time has stopped advancing in my world. Food expiration times are counting backwards, the sun isn't moving, the calendar isn't changing. Game tick things are still happening though (food is expiring, crops are growing.)

I updated to the latest TFC (and the corresponding bump in Forge version to 47.2.6) with no change.

I have these mods installed alongside TFC:

TFCAstikorCarts-1.20.1-1.1.7.1.jar
CraftTweaker-forge-1.20.1-14.0.25.jar
Patchouli-1.20.1-81-FORGE.jar
astikorcarts-1.20.x-1.1.6.jar
corpse-1.20.1-1.0.5.jar
incontrol-1.20-9.1.2.jar
inventorysorter-1.20.1-23.0.1.jar
Jade-1.20.1-forge-11.6.3.jar
journeymap-1.20.1-5.9.18-forge.jar
jei-1.20.1-forge-15.2.0.27.jar
JustEnoughResources-1.20.1-1.4.0.238.jar
MouseTweaks-forge-mc1.20-2.25.jar

I've uploaded my world save here: https://www.dropbox.com/scl/fi/g6uoaqtsmd6dwb8oek9hm/Forrester.zip?rlkey=ldh6bij705tgyhgao6wniu97k&dl=0

Let me know if you need any additional info.

**Comment by alcatrazEscapee** [comment]
TFC will persist the setting of `gamerule doDaylightCycle` if is believes it to be changed outside of TFC's own methods which turn it off when players are logged out. In this case it appears that as you crashed in an unusual situation, it got set to off without TFC realizing. You can fix this just by `/gamerule doDaylightCycle true`.

**Comment by jlbrewer** [comment]
This fixed the issue, thanks.
