### ISSUE TITLE
Axle on waterwheel rotate wrong direction on east/west

### ISSUE THREAD

**Issue by LeoBeliik** [TerraFirmaCraft/TerraFirmaCraft#2565]
https://imgur.com/g6c80qg

north/south works correctly, doesn't affect windmills

**Comment by Liriodendr0n** [comment]
I can confirm, this happens on my install of 3.1.0 too.
Additionally the trip hammer behavior is weird. The animation plays backwards and if you try and place the trip hammer mount in what looks like the forward direction it breaks on the first rotation.

These screenshots were taken facing east, with the river flowing south (left to right).
[https://i.imgur.com/crzmY27.png](https://i.imgur.com/crzmY27.png)
[https://i.imgur.com/crzmY27.png](https://i.imgur.com/cRkWbHa.png)
