### ISSUE TITLE
Ore blocks particle declaration is broken

### ISSUE THREAD

**Issue by alcatrazEscapee** [TerraFirmaCraft/TerraFirmaCraft#2568]
Results in missing textures when landing on them. Likely broken by my recent refactor to try and remove redundant `particle` declarations that I guess weren't redundant? I don't know why it doesn't work rn.

**Comment by eerussianguy** [comment]
can't reproduce...?

**Comment by alcatrazEscapee** [comment]
Confirmed, cannot reproduce. Also tried with Embeddium, Forge .2.20 (latest at time of writing).
