### ISSUE TITLE
River Streams turning orange in 1.20.1 forge 47.2.6+

### ISSUE THREAD

**Issue by SSilice** [TerraFirmaCraft/TerraFirmaCraft#2569]
River streams are a weird orange-ish brown color in version forge 47.2.6 and above. Picture

![2023-11-28_20 59 09](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/105840990/690ae62b-7f46-4dba-8eaf-e618c0e3420a)

**Comment by SSilice** [comment]
Forgot to add this is using Oculus/Rubidium

**Comment by alcatrazEscapee** [comment]
This is a bug in Rubidium and can be fixed by replacing Rubidium by Embeddium

Duplicate of #2536
