### ISSUE TITLE
Incompatibility with Valkyrien Skies and Clockwork

### ISSUE THREAD

**Issue by NewMajor73nanami** [TerraFirmaCraft/TerraFirmaCraft#2570]
As shown in the picture, we encountered an issue when attempting to make TerraFirmaCraft:The Next Generation compatible with Valkyrien Skies and Clockwork mod. We are certain that this is not a rendering issue, as the distorted areas have entities.
We have confirmed that in a Superflat world with Valkyrien Skies and Clockwork mod, the blocks in TFC:TNG is working normally.
![Cache_-7730193fa8b1bd29](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/94152219/ae54a327-9da3-4554-bf53-6ec1e15ee28f)

We suspect that because TFC mod overloaded the method "_creatStructures()_" of superclass and "_applyBiomeDecoration()_"  ( in net/dries007/tfc/world/TFCChunkGenerator.java ) to preload, the Valkyrien Skies failed to inject these methods. 

![VS问题方法1](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/94152219/7bb160ea-164e-4171-9d20-a182c90738d9)

![tfc问题方法 1](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/94152219/b86ee7bb-d273-410e-8d46-32e01a7c610b)
![tfc问题方法 2](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/94152219/8c34a99a-4027-4549-a677-b9cb76ecbc9b)

Moreover,  another method (_createReferences()_) may also encounter the same issues in the future.

Could you please address this problem? If not, we have to contact with VS team or plan to organize a team to resolve compatibility issues by ourselves. Thank you very much.

**Comment by alcatrazEscapee** [comment]
"Another mod is writing mixins into the vanilla chunk generator and is incompatible with you overriding these method" is **not** our problem, it's on them to make their mixins compatible with us. 

> Could you please address this problem?

You haven't stated a problem.. you've said "hey, you're overriding these methods in chunk generator", and my answer is, yes, and with good reason, and no we can't just remove these overrides, that would be moronic.

If there's an actual issue with TFC presented here, we can look into it. But "don't override these methods" is dumb, my answer to that is "don't mixin into the vanilla chunk generator and expect it to just work automatically with other mods chunk generators".

**Comment by ewoudje** [comment]
Should be fixed on vs2's end with the latest commit. (1.18.2)
