### ISSUE TITLE
screen frozen and game continue 

### ISSUE THREAD

**Issue by Moonkey96** [TerraFirmaCraft/TerraFirmaCraft#2571]
At random times, the game freezes and when it comes back the screen remains frozen but you can still hear the game running
mods:
tfc (Ambiental, FirmaLife, Water Flasks)
Optifine
Jade
JEI
Mouse Tweaks
and its libraries
Forge 1.18.2 40.2.14

**Comment by alcatrazEscapee** [comment]
There is nothing we can do with this report. I would say "remove optifine", because that's always generally a good idea. But lacking any other information, cannot reproduce.
