### ISSUE TITLE
TFC and Patchouli

### ISSUE THREAD

**Issue by EnderKnight20** [TerraFirmaCraft/TerraFirmaCraft#2574]
Minecraft keeps failing to load TFC and Patchouli. It says they require conflicting versions of forge. the photo will explain better than I can.
<img width="1440" alt="Screenshot 2023-12-06 at 12 50 29 PM" src="https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/153128407/676c144e-f965-4392-84f5-eab13e5308d9">

**Comment by alcatrazEscapee** [comment]
These version ranges are not conflicting.

- TFC requires **either** (46.1.3 or above, and below 47.1.6), **or**, 47.2.6 or above.
- Patchouli (this version) requires 47.1.47 or above.

47.1.30 satisfies **none** of those version requirements.
