### ISSUE TITLE
Heat bar when cooking food

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#258]
There was a bar that existed for food, that would come into existence and fill up when cooking. When it filled up completely, the meat would be cooked. I'm not sure if this was a vinalla tfc thing though.

**Comment by alcatrazEscapee** [comment]
This was due to the graded system of "cooked-ed-ness" that the old food items used to have. As that has been given the ax, it is no longer nessecary.
