### ISSUE TITLE
Horse armour uniquely requires raw jute

### ISSUE THREAD

**Issue by TheNameSimonWasAlreadyTaken** [TerraFirmaCraft/TerraFirmaCraft#2581]
The recipe for horse armour is the only recipe in the mod that takes raw jute instead of the other unraw jute that i forgot the name of, and i think that might be an oversight.
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/128638792/058d6598-24dd-47e0-af39-954276a34159)

**Comment by eerussianguy** [comment]
https://github.com/TerraFirmaCraft/TerraFirmaCraft/releases/tag/v3.1.3-beta
