### ISSUE TITLE
Moss spreads really far really quick

### ISSUE THREAD

**Issue by TheNameSimonWasAlreadyTaken** [TerraFirmaCraft/TerraFirmaCraft#2583]
As the title says, but a picture shows it better:
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/128638792/3c4c0c34-ff0b-4804-8bd0-2688ee23b638)
These moss patches are very common after some amount of time in the world, and quite overpowering.

**Comment by eerussianguy** [comment]
https://github.com/TerraFirmaCraft/TerraFirmaCraft/releases/tag/v3.1.3-beta
