### ISSUE TITLE
When snow starts to thaw, rings are left under the edges of trees

### ISSUE THREAD

**Issue by TheNameSimonWasAlreadyTaken** [TerraFirmaCraft/TerraFirmaCraft#2584]
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/128638792/703cd0d5-80b4-4e7d-acfd-8c47a73de7d8)
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/128638792/818312c9-8fa4-4290-a78e-49eef51d4593)

**Comment by eerussianguy** [comment]
calling this fixed for now with the leaf heightmap changes and stuff... we'll see. the snow will melt on random ticks either way.
