### ISSUE TITLE
Disc Veins don't handle projected Y values for indicators

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#2588]
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/1.20.x/src/main/java/net/dries007/tfc/world/feature/vein/VeinFeature.java#L143
should include projectedY.
Further, the code below for indicators needs to handle projection Y values correctly.

Since there are no disc metal ore veins, this wouldn't be exposed. I added indicators for mineral veins and nothing showed up for the coal veins.

**Comment by eerussianguy** [comment]
I can look into this when i have some time, but trying the change yourself and testing it wouldn't be unwelcome ;)
