### ISSUE TITLE
Game Failed to start

### ISSUE THREAD

**Issue by KelvinZhang512** [TerraFirmaCraft/TerraFirmaCraft#2589]
Minecraft 1.20.1 with Forge 47.1.3, launcher reports that this mod failed to inject while starting the game.
[error-2023-12-22_16.17.53.zip](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/13749875/error-2023-12-22_16.17.53.zip)

**Comment by alcatrazEscapee** [comment]
That log shows nothing of the sort, nor does it show any crash or failure to start, nor does it show TFC being the root cause of anything. There's nothing here we can actually look into, nor reproduce.

**Comment by KelvinZhang512** [comment]
Now I've installed a new Minecraft instance (1.20.1 with NeoForge 47.1.84) and TFC crashed the game. Could you add support for NeoForge?
[error-2023-12-27_20.55.17.zip](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/13778721/error-2023-12-27_20.55.17.zip)

**Comment by alcatrazEscapee** [comment]
We support NeoForge within the version range declared.

> Mod `tfc` requires `forge` 47.1.3 or above, and below 47.1.6, 47.2.6 or above
> Currently, `forge` is 47.1.84

We can't support newer versions due to a bug (https://github.com/neoforged/NeoForge/issues/256) in NeoForge which is unfixed in 1.20.1
