### ISSUE TITLE
If two ore types are in range of a pros pick, the output prints twice.

### ISSUE THREAD

**Issue by DavidTriphon** [TerraFirmaCraft/TerraFirmaCraft#259]
Steps to reproduce:
1. Find an area where two veins are in range of a prospector's pick.
2. Find a block that doesn't give a false negative.
3. Click on that block with the pick multiple times.

Expected result: print one line for every check.

Actual result: prints out two lines on every check.

Possible cause: output is printing for every vein found, despite that the message is the same.

![2019-08-06_18 59 54](https://user-images.githubusercontent.com/20526831/62589037-c7db3c00-b87c-11e9-80fe-94c788b1ef0f.png)

**Comment by alcatrazEscapee** [comment]
While yes this is a bug, you are complaining about the debug output...

**Comment by DavidTriphon** [comment]
That's debug output? I thought that was default... I didn't even realize.
