### ISSUE TITLE
The clearworld command's NOT_ORE preset doesn't clear gravel

### ISSUE THREAD

**Issue by MrHiTech123** [TerraFirmaCraft/TerraFirmaCraft#2594]
If you use the command /clearworld, with the preset NOT_ORE, like so, `/tfc clearworld 100 NOT_ORE`, then all non-ore blocks are deleted, but gravel is also not deleted for some reason, even though the only blocks not deleted should be ores..

**Comment by alcatrazEscapee** [comment]
`NOT_ORE` dynamically checks what blocks spawn as an vein feature; [gravel spawns in a vein feature](https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/1.20.x/src/main/resources/data/tfc/worldgen/configured_feature/vein/gravel.json), so no, you are wrong.
