### ISSUE TITLE
Birds glitch up fences/walls

### ISSUE THREAD

**Issue by Sunlis** [TerraFirmaCraft/TerraFirmaCraft#2600]
MC 1.18.2  
TFC 2.2.27

Some birds glitch into blocks when walking, causing them to pop on top of walls that are over 1 block tall. I stopped observing this once the wall was 2 blocks + 2 snow slabs tall.

Birds tested: Chicken, Quail, Pheasant, Turkey, Grouse, Penguin, Duck.
Buggy birds: Chicken, Duck

**Repro:**
- Put a bird in an area enclosed with a wall that animals shouldn't be able to jump over (anything more than 1 block tall, up to and including 2 blocks)
  - [optionally] Add additional birds. This seems to encourage the buggy behaviour to occur.
- Stand on the outside of the enclosure and hold food to attract the bird near the wall
- Move around the wall to encourage the bird to move around near the wall

**Expected:**
Bird remains contained within their enclosure

**Observed:**
Bird will spontaneously "jump" on top of the wall they are up against, allowing them to escape their enclosure

**Comment by alcatrazEscapee** [comment]
> Put a bird in an area enclosed with a wall that animals shouldn't be able to jump over (anything more than 1 block tall, up to and including 2 blocks)

Wrong, birds are able to jump higher than a single block. They have wings you know.
