### ISSUE TITLE
Game crashed after installing this mod

### ISSUE THREAD

**Issue by KelvinZhang512** [TerraFirmaCraft/TerraFirmaCraft#2607]
MC1.20.1, Forge 47.1.3, the game crashed shortly after being launched and here's what the launcher reported (I failed to find where this log really were on my computer)
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/48343945/b93eef5c-a702-45e0-b3a3-fbf750d49470)
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/48343945/159c147a-0b70-4bad-9434-6af29bfdee09)

**Comment by eerussianguy** [comment]
Closing this until we get a mod list and a full log.

**Comment by KelvinZhang512** [comment]
[console.log](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/13838598/console.log)
[debug.log](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/13838601/debug.log)
[latest.log](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/13838602/latest.log)
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/48343945/3fe77bcb-488e-4a2e-ac92-02636b82b061)
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/48343945/a2f77c2c-0fca-40e7-9dfb-e8ecb1fe5e58)
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/48343945/0acd4cac-bbbd-4a5e-897b-ce9372d3439f)
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/48343945/e8190bbd-cf48-4558-9dab-57d46e6e305f)

**Comment by eerussianguy** [comment]
Unfortunately with this many mods installed, this falls into the realm of modpack dev and not something we can diagnose on Github. Feel free to use our [discord](https://discord.gg/PRuAKvY) and ask for help from experienced devs.

**Comment by alcatrazEscapee** [comment]
```
[Serene Seasons Transformer]: Successfully patched shouldSnow
```
This is likely an incompatibility between TFC and serene seasons, and there's very little we can do here because the mods are fundamentally incompatible.
