### ISSUE TITLE
Eggs are preserved when placed in small vessels but not large ones

### ISSUE THREAD

**Issue by MrHiTech123** [TerraFirmaCraft/TerraFirmaCraft#2608]
If you place an egg in a large vessel, its expiration date is not doubled, like with all the other foods, but this does happen if it is placed in a small vessel

I'm not sure if they're meant to be preservable or not but either way something's wrong.

**Comment by alcatrazEscapee** [comment]
Did you not seal the large vessel...?

**Comment by MrHiTech123** [comment]
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/78568080/1903e3b7-6f82-4262-b73e-14ff2c0966aa)
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/78568080/674d9db8-f747-4590-b132-7a4d8ea46a25)
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/78568080/4f0c65f8-b2c4-4770-8c15-7482129376fc)

Here's what I have. I'm in version 3.1.4 which appears to be the most recent one.
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/78568080/e6746367-a627-4692-a7a5-c0324651a820)


Edit: I changed the second image to something that reflected the bug I was reporting, but the original second image I took had a completely different expiration date for some reason. I tried and failed to reproduce this error.

Here was the original second image:
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/78568080/01053565-1f34-4323-99e2-c393b41de7f0)

**Comment by MrHiTech123** [comment]
Some time passed in-game, and when I re-closed the vessel, this happened:
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/78568080/3ebab068-77de-42fa-a171-94ad3fc6a3f9)

The updated expiration date remained even after the vessel was unsealed again.
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/78568080/74251a74-69d4-4037-bbf6-5b138438dc30)

**Comment by eerussianguy** [comment]
confirmed
