### ISSUE TITLE
Mod conflict - knife does not break blocks

### ISSUE THREAD

**Issue by IKarum** [TerraFirmaCraft/TerraFirmaCraft#2609]
In version 1.20.1 the knife does not break the leaves, it attacks as if it were a vanilla sword. I disabled EpicFight but it continued. In other words, it was impossible to collect leaves and straw materials for the fire.

**Comment by eerussianguy** [comment]
Mod list?

**Comment by IKarum** [comment]
https://www.curseforge.com/minecraft/modpacks/ultimate-terrafirmacraft-survival/relations/dependencies

Sorry for sending the list like this, I have no experience in getting the list any other way
I tested removing the ones I thought might be, like ÉpicFigths, but it still continued.

**Comment by alcatrazEscapee** [comment]
As this does not happen in base TFC, I'm assuming a mod conflict. I would suggest trying to isolated which mod is causing the issue, and provide a clean reproduction case with just those mod(s).

**Comment by alcatrazEscapee** [comment]
See #2628
