### ISSUE TITLE
Crash on startup when Valkyrien Skies is installed 1.20.1

### ISSUE THREAD

**Issue by gabpa-gaming** [TerraFirmaCraft/TerraFirmaCraft#2610]
Version: 1.20.1
Forge version: 47.2.8
Replication: Install TFC and VS, it should crash on startup (tested with Create and Create Interactive also installed)

**Comment by alcatrazEscapee** [comment]
Attach a log file or crash log.

**Comment by gabpa-gaming** [comment]
[crash-2024-01-06_13.24.48-fml.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/13849655/crash-2024-01-06_13.24.48-fml.txt)

**Comment by alcatrazEscapee** [comment]
```
Caused by 1: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [valkyrienskies-forge.mixins.json:compat.tfc.MixinTFCChunkGenerator] from phase [DEFAULT] in config [valkyrienskies-forge.mixins.json] FAILED during APPLY
```

VS has some sort of mixin that's trying to provide compatibility for our chunk generator, which is failing. This is entirely on them to solve. See #2570 Suggest reporting this issue to them.
