### ISSUE TITLE
Axles turn the wrong direction when moved by a water wheel

### ISSUE THREAD

**Issue by MrHiTech123** [TerraFirmaCraft/TerraFirmaCraft#2612]
https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/78568080/9ab8835a-170d-4ac3-9f6b-9776e36f0784

**Comment by alcatrazEscapee** [comment]
Terrible issue report with no information, assuming duplicate of #2565

**Comment by MrHiTech123** [comment]
Yes—that's it. Sorry
