### ISSUE TITLE
1.20.1 Thirst and food nutritients are black / empty on Mohist server

### ISSUE THREAD

**Issue by Proxwian** [TerraFirmaCraft/TerraFirmaCraft#2617]
Affected all players on server. Food bar is working as intended, but thirst bar is always black, as well all nutritions in corresponded inventory tab.

Doesn't reproduce in singleplayer world.

![2024-01-21_18 59 08](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/31781674/94e50d37-f741-4214-b7f5-44e49ab8dea7)
![2024-01-21_18 58 51](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/31781674/6da33985-055f-4c8b-8fae-de89e7304f29)

**Comment by alcatrazEscapee** [comment]
Please provide a full log file, as well as what server software you are using.

**Comment by Proxwian** [comment]
Actually, that's a Mohist server. Checked again, and can't be reproduced with plain Forge server
[latest.log](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/14002275/latest.log)

**Comment by alcatrazEscapee** [comment]
We don't support custom server software, because they have shown time and time again, they don't properly implement Forge APIs which we rely on. You either have to use a Forge server, or take this issue up with Mohist.
