### ISSUE TITLE
Crash on load when attempting to run TFC with Rustic

### ISSUE THREAD

**Issue by Verph** [TerraFirmaCraft/TerraFirmaCraft#262]
The game crashes during load, when loading TFC with the mod named Rustic.
This is on a fresh install, with default configs et cetera.

The crash happens with TFC v0.18.0.44.
[crash-2019-08-08_01.52.10-client.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/3479286/crash-2019-08-08_01.52.10-client.txt)

Or if you prefer Pastebin: https://pastebin.com/ngFG1s8T

**Comment by alcatrazEscapee** [comment]
Oh my god, for once a mod compatibility report that I can actually reliable reproduce in dev.
