### ISSUE TITLE
Wiki page down

### ISSUE THREAD

**Issue by SquidOptical** [TerraFirmaCraft/TerraFirmaCraft#2621]
when i try to connect to the wiki page, i get a 522 cloudflare error message. im not sure where else to report this. 
edit: i also dont know how to use labels or this site. i made this account just to report this issue

**Comment by eerussianguy** [comment]
Wrong venue

**Comment by SquidOptical** [comment]
how do i find the right venue then? everything online just leads me either to here or the terrafirmacraft..com website thats down
