### ISSUE TITLE
[Crash][1.20.1][Server]Crash on generating new chunk

### ISSUE THREAD

**Issue by Tollainmear** [TerraFirmaCraft/TerraFirmaCraft#2624]
### Issue steps:
* Create world by using cmd(which was provided by mohist) `/worlds create test`
*  then select the `normal` type(tips: plz note that the world pending to create is a vanilla world type by using this cmd)
* then vanilla type world `test` was created and loaded
* (Tips: If I tp to the world now, before a server restart, the server won't crash)
* then stop and restart the server
* then tp by using `/worlds tp test`
* then server goes crash.

### log
The crash report is [this](https://gist.github.com/Tollainmear/3ef662e1c020dea0224c4b463988bd52)
and the console output while crashing is [this](https://gist.github.com/Tollainmear/c62511350ece760eb9a883747c01496d)

### Env:
MC version 1.20.1
Server type: Mohist 1.20.1 B525
Forge version: 47.2.20
TFC version: 3.1.6

**Comment by alcatrazEscapee** [comment]
We do not support the use of custom server software (i.e. Mohist) as it has caused issues in the past. You can try reporting this to them.
