### ISSUE TITLE
Can't use WorldEdit with some blocks from TFC

### ISSUE THREAD

**Issue by Proxwian** [TerraFirmaCraft/TerraFirmaCraft#2625]
Blocks, which doesn't have correct state (as WE devs wrote in issue below): all kinds of leaves + thatch.

https://github.com/EngineHub/WorldEdit/issues/2463

**Comment by alcatrazEscapee** [comment]
The WE devs are just wrong. Just as a guess it looks like it might be an issue with blocks containing our fluid property. I'm trying to dig through WE's code to see what is the issue given they've demonstrated bum fuck all inclination to look into it.
