### ISSUE TITLE
[1.20.1] Epic Fight incompatibility

### ISSUE THREAD

**Issue by Proxwian** [TerraFirmaCraft/TerraFirmaCraft#2628]
Can't throw a spear with Epic Fight mod installed. Both combat and build mode.

**Comment by alcatrazEscapee** [comment]
Honestly given we've had issues before with basic functionality with Epic Fight, and there's no indication that we're doing anything special here, this is just flat out Epic Fight breaking basic functions of our items, this should be reported to them as an issue.

**Comment by Proxwian** [comment]
🤡
