### ISSUE TITLE
[Compatibility Issue] No Hostile Mob Spawning with EpicSamurai Mod Installed

### ISSUE THREAD

**Issue by Tollainmear** [TerraFirmaCraft/TerraFirmaCraft#2630]
Hello TFC Team,

I've encountered an issue where, upon installing the EpicSamurai mod alongside TFC, no hostile mobs are spawning in the Overworld. Here are the details:

- TFC version: 3.1.6
- EpicSamurai mod version: [0.0.34.1]
- Minecraft version: [1.20.1]
- Forge version: [47.2.20]

Expected Behavior:
Hostile mobs should spawn normally according to TFC's mechanics.

Actual Behavior:
After installing EpicSamurai mod, hostile mob spawning in the Overworld is completely halted.

Steps to Reproduce:
1. Install TFC and EpicSamurai .
3. Create a new world and observe the Overworld during nighttime or in caves.

Additional Information[Potentially Important]:
- After deleting the `data/forge/tags/blocks/ores` directory and the `data/forge/tags/blocks/ores.json` file within the EpicSamurai.jar, hostile mobs began to spawn normally in TFC's Overworld.
- [the file which I deleted](https://github.com/VeroxUniverse/EpicSamurai-forge/tree/1.19.2-forge/src/main/resources/data/forge/tags/blocks)

This leads me to believe there is a strange interaction or conflict with how EpicSamurai mod registers its ore tags, which somehow affects the mob spawning mechanics in TFC. This is unusual and I'm unsure why it would have such an impact.

Any assistance or insights you can provide would be greatly appreciated.

**Comment by Tollainmear** [comment]
https://github.com/VeroxUniverse/EpicSamurai-forge/issues/33

**Comment by alcatrazEscapee** [comment]
Epic Samurai has broken tag definitions, more detail in the other issue. They're causing `#forge:ores` to not load.
