### ISSUE TITLE
[1.20.1, forge] Minecraft Run Crash

### ISSUE THREAD

**Issue by rthergithub** [TerraFirmaCraft/TerraFirmaCraft#2632]
code: 1
forge versoin: 47.2.20
no optifine
no crash log.
mod versoin:1.20.1-3.1.6
install terrafrimacraft and its associated add-ons, it crashes with exit code 1...

**Comment by alcatrazEscapee** [comment]
Stop spamming our issues tab with spam useless issue reports. I said, you need a log file or crash log for this to be remotely diagnosable.
