### ISSUE TITLE
There is a problem with the entrance.

### ISSUE THREAD

**Issue by Mayumchek** [TerraFirmaCraft/TerraFirmaCraft#2635]
When you log in, minecraft immediately closes and an error pops up. When there is no TerraFirmaCraft, it comes in without any problems.(my friends also have this error). ver 1.20.1

**Comment by Mayumchek** [comment]
[error.zip](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/14229187/error.zip)
maybe this will help

**Comment by alcatrazEscapee** [comment]
We do not provide support for cracked clients.
