### ISSUE TITLE
0 ingredient pot recipe causes crash

### ISSUE THREAD

**Issue by SnackJunkie** [TerraFirmaCraft/TerraFirmaCraft#2639]
When adding a 0-ingredient pot recipe via datapack (e.g. water to boiled water), the game crashes at Helpers.perfectMatchExists.

This is due to the line:
final boolean[] matrix = matrices[size - 1]

An ingredient list size of 0 results in an index of -1 and an out of bounds exception.

I belive this can be fixed by adding an additional check after the list size comparison, if both lists have size 0 then it's a match.

**Comment by SnackJunkie** [comment]
Can this be fixed on 1.18.2?

**Comment by eerussianguy** [comment]
1.18 is only receiving critical bugfixes, this will not be ported to 1.18.

**Comment by SnackJunkie** [comment]
Out of curiosity, what constitutes a critical bug fix? This causes a hard crash if you try to use an itemless recipe.

**Comment by alcatrazEscapee** [comment]
> if you try to use an itemless recipe.

In general, "I used your datapack API in a way you weren't expecting, and it didn't work", doesn't. This issue has zero impact unless you use a datapack in this specific way.

In the interest of our time and sanity, we do not and cannot support versions endlessly, and at the moment that means 1.18.x and lower shouldn't expect any future development.

**Comment by SnackJunkie** [comment]
Fair enough
