### ISSUE TITLE
Frogs do not Produce Froglights

### ISSUE THREAD

**Issue by AngellusMortis** [TerraFirmaCraft/TerraFirmaCraft#2641]
TFC Frogs do not produce [Froglights](https://minecraft.fandom.com/wiki/Froglight) when eating magma cubes. I tried feeding the frog first, getting their familiarity up, but nothing seems to work. 

I can use the vanilla frog spawn egg and the vanilla frogs still produce froglights correctly. 

Forge: 1.20.1-47.2.6
TFC: 3.1.8

no other mods.

**Comment by alcatrazEscapee** [comment]
Froglights aren't meant to be obtainable as an infinite light source.

**Comment by AngellusMortis** [comment]
Shroomlights and Glowstone also are infinite light sources and a lot easier to get then Froglights. All 3 of them require the Nether to aquire with Froglights being the hardest one to get.

**Comment by AngellusMortis** [comment]
Shroomlights: You need Nether access, a hoe and a pickaxe (for getting a decent supply of netherrack). Find a Crimson Forest and you can get shroomlights at about 1 stack/3 min. 

Glowstone: You need Nether access and a pickaxe. Optionally fortune. You can get a glowstone at about a stack/10 min.

Froglights: Nether access, a frog. Magma cube spawners _only_ spawn in bastion treasure rooms. 

Without a magma cube spawner one, you are more likely to get your frog killed then actually getting any usable amount of Froglights since natural magma cube spawns are not nearly as common. You could pick a biome that that does get piglins and build a spawn room that ghast cannot spawn in, but even then, you are looking at less froglights then just farming shroomlights. 

To get to a magma cube spawner, you need to find a bastion with a treasure room, clear out all of the piglins and build a spawn room. If you are able to do all of that, you have easily "beaten" any difficultly and content TFC can provide. 

It seems removing froglights does not serve any real benefit/difficultly outside of just removing a vanilla mechanic with no viable replacement. Froglights, aesthetically, look a lot better them shroomlights and glowstone and come in more colors. 

If the concern is the interaction with TFC and other mods in modpacks, that seems like a decision for modpack creators to make, not TFC. So maybe it should be locked behind a configuration setting? Rather than unilaterally making the decision to remove access to a vanilla Minecraft block/resource for everyone.

**Comment by alcatrazEscapee** [comment]
None of this is relevant. We have not disabled, or removed frog lights. We simply _haven't implemented them for TFC frogs._ And we're not going to. If you, the modpack maker, wants to make that decision, then you're free to. Vanilla implements froglight drops using the [loot table for magma cubes](<https://github.com/misode/mcmeta/blob/c140267d0f45067581aa9021fa2072157d64a6c3/data/minecraft/loot_tables/entities/magma_cube.json#L55-L79>) If you are so desired to edit those in your modpack, you can feel free, this _is_ a configuration option.
