### ISSUE TITLE
Optifine and Rubisium.

### ISSUE THREAD

**Issue by Lindosik** [TerraFirmaCraft/TerraFirmaCraft#2646]
When you try to open Minecraft with Optifine or Rubidium it's just crash without logs. 1.20.x

**Comment by alcatrazEscapee** [comment]
- We don't support the use of optifine as it's been known to cause issues in the past that we cannot debug
- Rubidium also has bugs that cause issues, Embeddium is a fork of the mod that is more updated

If you do not have a crash log or log, there is nothing we can do to help you. Thus cannot reproduce.
