### ISSUE TITLE
Eating doesn't give saturation

### ISSUE THREAD

**Issue by X-XLebyshek** [TerraFirmaCraft/TerraFirmaCraft#2648]
Minecraft 1.20.1, Forge 47.2.20, TFC 3.1.4

I'm playing on a modpack and when I try to eat, it only works from time to time, like if I were on a multiplayer server with high ping, but I'm not, and also when I finally eat. it doesn't add saturation. And also when I have TFC, it deletes recipes for workbench and for all tools, I don't know, whether it's a feature or not.

P.S. I tried using TFC without any other mods (except Patchouli) and it gives out the same issues

**Comment by eerussianguy** [comment]
Deleting recipes is intentional. We are not able to replicate food not being able to be eaten. Make sure you're eating TFC food. Closing for now until we get better info (what foods, what your mod list is, screenshots...)

**Comment by X-XLebyshek** [comment]
When I eat TFC food, it works. Is this also intentional that no other food gives you saturation or what?

**Comment by alcatrazEscapee** [comment]
TFC ignores hunger/saturation values added by other mods, yes, because said food has no decay, or nutrition information. Compatibility with said other mods can be added via datapacks.
