### ISSUE TITLE
Ingot molds will not stack together if ingots are extracted via different methods.

### ISSUE THREAD

**Issue by Arcanum3000** [TerraFirmaCraft/TerraFirmaCraft#2651]
I just tested this in 1.20.1-3.1.9.

Take a bunch of ingots in molds.  Extract some of the ingots by right-clicking while they're in the inventory.  Extract the other ingots using the crafting grid.  The empty molds of the first group will stack together, and the empty molds of the second group will stack together, but you can't combine groups in the same stack

Re-heating the first (right-click) group even slightly in e.g. a forge will "reset" them and allow them to stack with the crafting grid group, but they will no longer stack with the right-click group.

**Comment by alcatrazEscapee** [comment]
Please turn on `enableDebug` in the TFC client config, advanced tooltips (F3 + H), and show a screenshot of both molds, including with debug tooltips that are refusing to stack.

**Comment by Arcanum3000** [comment]
They appear to be identical according to the debug info.
![Base Profile Screenshot 2024 02 26 - 14 59 25 42](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/35147869/9e24761d-f233-45f6-b5d3-e4f1464eb46b)
![Base Profile Screenshot 2024 02 26 - 14 59 40 17](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/35147869/3c19d012-48c1-4234-80b4-229279cdaead)
