### ISSUE TITLE
The generation of banana is broken

### ISSUE THREAD

**Issue by Quaerere-Git** [TerraFirmaCraft/TerraFirmaCraft#2652]
**Affected Versions:**
1.20.1-3.1.4 and 3.1.9 (Maybe versions between them)

**How to reproduce:**
1. change the constant temperature and humidity to 95%/70% (Around 24℃ and 440mm)
2. modify the probability of banana, olive and orange trees to maxinum via datapack
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/42565872/8e43bc9f-b634-4498-b732-8631dac1c4eb)
3. create a new world

**Expectations:**
Banana trees should generate as frequent as olive and orange trees

**Reality:**
Olive and orange trees spawn very frequently while banana trees don't spawn at all
![2024-02-28_01 16 57](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/42565872/a069eb03-4589-417a-9d46-57d3ed4501ad)

**Comment by alcatrazEscapee** [comment]
![2024-02-27_14 59 38](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/35673674/93ec1492-61a4-4181-a1ea-16bd15eddb70)
