### ISSUE TITLE
Cannot load from int array because "this.surfaceHeight" is null

### ISSUE THREAD

**Issue by SnackJunkie** [TerraFirmaCraft/TerraFirmaCraft#2661]
Minecraft 1.20.1
Forge 47.2.20
TerraFirmaCraft 3.1.9
Distant Horizons 2.0.1-a

Using Distant Horizons distant generation feature results in this error from TFC

https://pastebin.com/e8GjuEcw

**Comment by alcatrazEscapee** [comment]
This would be something DH likely needs to look into or fix, they're not sufficiently mocking our world generator for distant generation.

```
[18:57:10] [Server thread/INFO] [LodWorldGen/]: ================WORLD_GEN_STEP_INITING=============
[18:57:10] [Server thread/INFO] [LodWorldGen/]: TerraFirmaCraft Chunk Generator detected: [class net.dries007.tfc.world.TFCChunkGenerator], Distant Generation will try its best to support it.
[18:57:10] [Server thread/INFO] [LodWorldGen/]: If it does crash, turn Distant Generation off or set it to to [PRE_EXISTING_ONLY].
```

**Comment by SnackJunkie** [comment]
https://gitlab.com/jeseibel/distant-horizons/-/issues/647

**Comment by lith-x** [comment]
There's a DH API for passing along [chunk generation](https://gitlab.com/jeseibel/distant-horizons-core/-/blob/main/api/src/main/java/com/seibel/distanthorizons/api/interfaces/override/worldGenerator/IDhApiWorldGenerator.java) info. Not super familiar with the inner workings of either project, so it may not be entirely useful, but thought I'd throw it in here.

**Comment by AtobaAzul** [comment]
Adding a bit to this, I'm having this issue with DH distant gen *disabled* or set to Pre-existing only, and even with DH rendering turned *off*.
https://cdn.discordapp.com/attachments/633906457921847296/1252778722428325952/Minecraft_Forge__1.20.1_2024-06-18_21-11-58.mp4?ex=6673749a&is=6672231a&hm=9f6117790cb053cc5a9bff3302b689c7b5dea528202f614984fb310331b4d314&
