### ISSUE TITLE
Nether Portal Doesn't Work!

### ISSUE THREAD

**Issue by awesomeplayer123** [TerraFirmaCraft/TerraFirmaCraft#2662]
After rereading the description of the mod, I don't know for sure if the nether portal doesn't work as a feature, but it doesn't light up after building the portal and lighting with a flint and steel.

Game Version - 1.20.1
Loader Version - 1.20.1-47.2.17
Forge
 Directly downloaded with Modrinth Launcher

**Comment by alcatrazEscapee** [comment]
From the server config:
```
enableNetherPortals = false
```
