### ISSUE TITLE
add sword cut melon recipe

### ISSUE THREAD

**Issue by erhabenha223** [TerraFirmaCraft/TerraFirmaCraft#2663]
why not
![PixPin_2024-03-17_18-29-02](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/65021888/b1c9820b-f75e-4e4f-9db1-9f25df623a19)

**Comment by alcatrazEscapee** [comment]
We use the issue tracker exclusively for bug reports, not suggestions or support requests. This post would be more suitable for our [discord](https://discord.gg/PRuAKvY).
