### ISSUE TITLE
Fix Support for Antique Atlas

### ISSUE THREAD

**Issue by edgardeivis** [TerraFirmaCraft/TerraFirmaCraft#2664]
current source code provides support inside world_gen.py, this however can't work since it uses the tag "antiqueatlas" instead of "antique_atlas"
this is how it shows up in game:
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/40432130/9a07839f-32d8-4a75-b502-4a6e61348d34)
this is a easy fix, please fix it 
line 1601 in world_gen.py
`    rm.data(('atlas', 'tiles', name), {
        'version': 1,
        'texture_set': 'antiqueatlas:%s' % atlas_texture
    }, 'assets')`
potentially fixed version:
`    rm.data(('atlas', 'tiles', name), {
        'version': 1,
        'texture_set': 'antique_atlas:%s' % atlas_texture
    }, 'assets')`

**Comment by edgardeivis** [comment]
i think some of the biome names for antique atlas have also changed

**Comment by edgardeivis** [comment]
turns out, the problem might be far more complex than this, not even making a resource pack and adding all the jsons in the correct place, or replacing the ones inside terrafirmacraft fixes this

**Comment by alcatrazEscapee** [comment]
To paraphrase from the (long) commit message, as Antique Atlas is not updated past 1.18.2, past an unofficial fabric port (which works on Forge through connector), making it both undocumented + impossible to setup in a dev env, the existing compat in 1.20.1 has been removed.
