### ISSUE TITLE
Cannot see smoke of firepit from some angle

### ISSUE THREAD

**Issue by erhabenha223** [TerraFirmaCraft/TerraFirmaCraft#2665]
https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/65021888/aef7f715-0e15-433e-a225-c2a839c22398

The animation of boiling water has same issue too
Minecraft V.1.20.1
Forge V.47.2.21
TFC V.3.1.9
No other Mods

**Comment by alcatrazEscapee** [comment]
This isn't an issue with specific angles or distances - it's purely a randomization issue. The video provided doesn't mean anything, given you're standing in problematic areas for less than a second. Particle generation _is_ random and can stop and start... that is typical of random events.

I can also reproduce visually problematic behavior with most vanilla blocks that emit particles - including campfires - and the underlying seeding issue that's causing this is likely not really fixable by us, although there may still be something we can adjust here to appear less random and more uniform.

**Comment by erhabenha223** [comment]
no it's not appear random，the video only last a sec because i can only upload video less than 10MB on github，i found this issue on survival when i try to cook eggs in pot，i could only hear and see the boiling water when i stand on some specific angel of the pot(now i think i should upload video about this not smoke which can see this issue more clear，my bad)，and then i created a new version with no other mods just TFC and record this video.

**Comment by erhabenha223** [comment]
> This isn't an issue with specific angles or distances - it's purely a randomization issue. The video provided doesn't mean anything, given you're standing in problematic areas for less than a second. Particle generation _is_ random and can stop and start... that is typical of random events.
> 
> I can also reproduce visually problematic behavior with most vanilla blocks that emit particles - including campfires - and the underlying seeding issue that's causing this is likely not really fixable by us, although there may still be something we can adjust here to appear less random and more uniform.

should i reply like this? i didn't use reply this before

**Comment by alcatrazEscapee** [comment]
Several issues were contributing here, including a seeding issue elsewhere which I was missing.
