### ISSUE TITLE
TFC 3.1.9 crashing with OptiFine

### ISSUE THREAD

**Issue by PR0J3CT12** [TerraFirmaCraft/TerraFirmaCraft#2667]
There is no errors in latest.log, but the game is crashing.
Mods: Optifine, TFC, Patchouli

Is it possible to play TFC with optifine?

**Comment by eerussianguy** [comment]
TFC is not compatible with Optifine.

This post would be more suitable for our [discord](https://discord.gg/PRuAKvY) where people can point you in the right direction for Shader support.
