### ISSUE TITLE
A bug about mineral processing

### ISSUE THREAD

**Issue by hidfug** [TerraFirmaCraft/TerraFirmaCraft#267]
![20190808135241](https://user-images.githubusercontent.com/34993841/62678372-f0317a80-b9e3-11e9-9870-2a3a63a7697a.png)

![20190808135230](https://user-images.githubusercontent.com/34993841/62678376-f6275b80-b9e3-11e9-80b8-3cc75e71a342.png)
When I put 64 tetrahedrites in vessel and fire it,I just acquire 100 units copper.

**Comment by alcatrazEscapee** [comment]
Duplicate of #242. If this persists in 0.18.0.44+ reopen this issue

**Comment by hidfug** [comment]
> Duplicate of #242. If this persists in 0.18.0.44+ reopen this issue

I found it in 0.14.1.53,and I download it from release.

**Comment by alcatrazEscapee** [comment]
Build numbers are borked. This is newer: <https://jenkins.dries007.net/TerraFirmaCraft>
