### ISSUE TITLE
Dupe bug with corpse mod and vessels

### ISSUE THREAD

**Issue by redstoneguy10ls** [TerraFirmaCraft/TerraFirmaCraft#2676]
EE might know of this already but im making an official report basically with the corpse mod you can dupe items in vessels.
if you right click on a vessel in the death history screen from the corpse mod accessed by pressing "u" by default you can take the items out of the vessel. But the items will remain on the corpse.
https://cdn.discordapp.com/attachments/1230313291822137415/1230317302990245979/2024-04-18_03-37-31.mp4?ex=6632e147&is=66206c47&hm=6069a286ac40528a755153d46587357e4f70fff994d6c5b9c8eda37fd46001cc&

Steps to reproduce
download both corpse and tfc
put an item into a vessel
have that vessel on your person
die
open the death history screen
click items
right click on the vessel

i reported it to them and they said 

`Please report this issue to their issue tracker. They need to check if they have access to the container to allow taking items out. This is not a bug of the corpse mod.`

**Comment by alcatrazEscapee** [comment]
Can you reproduce this with a bundle (the vanilla item) or does it only happen with a vessel.

If it works with a bundle, that's a corpse-mod-only issue.

**Comment by redstoneguy10ls** [comment]
it only works with the vessel does not work with the vanilla bundle

**Comment by dtangres** [comment]
Hi! Sorry to butt in - I replicated the process above on my modded install (Corpse + TFC added), and I haven't encountered any abnormal behavior. For reference, I'm playing with base Minecraft 1.20.1, modded with, among others:
- [TFC Vessel Tooltip](https://modrinth.com/mod/Xve2AFV9) [1.0]
- [Corpse](https://modrinth.com/mod/WrpuIfhw) [1.20.1-1.0.12]
- [TerraFirmaCraft](https://www.curseforge.com/projects/302973) [3.2.2]

I'd be happy to provide a full modlist and additional information if that helps diagnose the issue.
