### ISSUE TITLE
Charcoal forge UI has wrong item locations

### ISSUE THREAD

**Issue by MrHiTech123** [TerraFirmaCraft/TerraFirmaCraft#2677]
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/78568080/17f264a2-9651-42e6-9dfe-2180ccc72850)

Doesn't seem to be an issue in other UI's, just the charcoal forge. I tried the anvil and crafting table and both were fine.

**Comment by alcatrazEscapee** [comment]
Please post your log, and are you using any resource/texture packs?

**Comment by MrHiTech123** [comment]
I was accidentally using one for a patchouli book, but removing it had no effect.

Here's my log file. There's a lot of mods in it but most were removed and it didn't fix the problem.
[latest.log](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/15031150/latest.log)

It happened with this modpack, as well as a different one that didn't use Oculus (which otherwise would be the most likely candidate from these mods)
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/78568080/ef7a65af-12bd-4a9e-a482-7eb7c7152ec0)
