### ISSUE TITLE
Chunk generation crash: Cannot load from int array because "this.surfaceHeight" is null

### ISSUE THREAD

**Issue by Tshmofen** [TerraFirmaCraft/TerraFirmaCraft#2679]
_Minecraft 1.20.1
Forge 47.2.23
TerraFirmaCraft 3.2.1_

Might be connected to Distant Horizons that was installed previously, but the bug is reproducable even with only TFC and Patchouli active without any other modes. Also, DH says that I can just disable generation and it should prevent any issues with it (do not see why it would not? Maybe prerendered chunk is broken for some reason, and stays the same after I remove DH? Who knows), and that solution is obviously not a case. 

Considering the fact that DH correctly generated distant chanks for the zone I'm entering and displays LODs without crashes, and only when I'm actually loading the chunk by entering rendering distance nearby it crashes, it very much looks like TFC-side error.

Here's the log.
[tl-logger9240376971152024468.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/15040772/tl-logger9240376971152024468.txt)

And the [save file](https://drive.google.com/file/d/1fX1hmtmWuzl9iohcmbiBSMxZSRwVbF_n/view?usp=sharing), just in case - to reproduce the issue I just need to move forward a few chunks on it (with 8 render distance, or just crank it up to 32 to trigger the crash immediately). Though, seems like a pretty rare issue, was playing on that save for a 15-20 hours without any issues, and just was trying to reach other climates through ocean when that happened.

**Comment by alcatrazEscapee** [comment]
Duplicate of #2661
