### ISSUE TITLE
Extracting ash from a campfire with a pot on it will delete the pot

### ISSUE THREAD

**Issue by TalerzykTheMoth** [TerraFirmaCraft/TerraFirmaCraft#2683]
Whenever you want to extract wood ash from the campfire with a pot on it, by shift + rightclick, you will get the ash and the contents of pot (like sugar, but not fluid), yet the pot will just vanish. It only works if you extract ash by clicking the campfire itself, if you click the pot - you get everything

**Comment by eerussianguy** [comment]
I think there may be a misconception about how pots work in this post, but, either way, fixed the inconsistency
