### ISSUE TITLE
Crash 1.20.1

### ISSUE THREAD

**Issue by K3tchuup** [TerraFirmaCraft/TerraFirmaCraft#2688]
TerraFirmaCraft causes Primal Winter to crash in forge: 47.2.20 
https://www.curseforge.com/minecraft/mc-mods/primal-winter

**Comment by alcatrazEscapee** [comment]
These mods have a fundamental incompatibility that can't be resolved - TFC implements seasons, primal winter attempts to force a single universal weather.
