### ISSUE TITLE
Inherited ice physics on lower slabs

### ISSUE THREAD

**Issue by TalerzykTheMoth** [TerraFirmaCraft/TerraFirmaCraft#2693]
Whenever there are icicles originating from a bottom slab, the player standing on the slab will "inherit" ice physics from the icicles

**Comment by alcatrazEscapee** [comment]
While undesirable, this _is_ consistent with how ice functions. Although given icicles probably don't need the slickness from ice, we can probably avoid having that property at all, which would fix this behavior.

**Comment by eerussianguy** [comment]
https://github.com/TerraFirmaCraft/TerraFirmaCraft/commit/bd1244338724ae0e0d1000fd229347aa08583e6d

this was fixed a few days ago
