### ISSUE TITLE
Icicles appearing in underwater ocean caves in cold temperature zones

### ISSUE THREAD

**Issue by dtangres** [TerraFirmaCraft/TerraFirmaCraft#2695]
Screencaps:
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/14242403/0345099e-0288-494e-8165-561ba199652f)
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/14242403/bf3b3a5b-2a5b-4f00-bc79-a1602d8a6a3d)

Modlist:
- [True Darkness](https://modrinth.com/mod/mI4xkilT) [2.0.103]
- [ArborFirmaCraft](https://modrinth.com/mod/9q4wtMjp) [1.0.9-1.20.1]
- [Firma: Civilization](https://modrinth.com/mod/6o49a8Vz) [0.2.10-alpha-1.20.1]
- [TFC Vessel Tooltip](https://modrinth.com/mod/Xve2AFV9) [1.0]
- [Embeddium](https://modrinth.com/mod/sk9rgfiA) [0.3.17+mc1.20.1]
- [Dynamic FPS](https://modrinth.com/mod/LQ3K71Q1) [3.4.3]
- [Curios API](https://modrinth.com/mod/vvuO3ImH) [5.9.0+1.20.1]
- [Balm](https://modrinth.com/mod/MBAkmtvl) [7.2.2]
- [TFC Desire Paths](https://www.curseforge.com/projects/847065) [1.1.3]
- [TFC: Grooming Station](https://www.curseforge.com/projects/1003785) [1.20.1-0.1.2]
- [TFC Casting with Channels](https://www.curseforge.com/projects/820815) [0.2.3-beta]
- [EntityCulling](https://modrinth.com/mod/NNAgCjsB) [1.6.2]
- [Barrels 2012](https://modrinth.com/mod/hnvFIZaX) [2.1]
- [Cupboard utilities](https://www.curseforge.com/projects/326652) [1.20.1-2.6]
- [Tiny Item Animations](https://www.curseforge.com/projects/808006) [1.20-1.1]
- [TFC Hot or Not](https://www.curseforge.com/projects/499096) [1.0.4]
- [ImmediatelyFast](https://modrinth.com/mod/5ZwdcRci) [1.2.14+1.20.4]
- [Jade](https://modrinth.com/mod/nvQzSEkH) [11.8.0]
- [Starlight](https://modrinth.com/mod/iRfIGC1s) [1.1.2+forge.1cda73c]
- [Krypton Reforged](https://www.curseforge.com/projects/549394) [0.2.3]
- [TFC Caelum](https://www.curseforge.com/projects/999031) [1.2]
- [TFC Improved Badlands](https://www.curseforge.com/projects/969207) [1.0.2]
- [Client Tweaks](https://modrinth.com/mod/vPNqo58Q) [11.1.0]
- [aleki's Easy Held Models](https://modrinth.com/mod/5hMNyIoI) [1.0.3-1.20.1]
- [Canary](https://modrinth.com/mod/qa2H4BS9) [0.3.3]
- [TFC Cast Iron Grill](https://modrinth.com/mod/AzzNDuCn) [2.1]
- [Corpse](https://modrinth.com/mod/WrpuIfhw) [1.20.1-1.0.12]
- [TFC Ambiental](https://modrinth.com/mod/K7eNiRnX) [1.20.1-3.3.0]
- [Radium](https://modrinth.com/mod/2gvRmQXx) [0.12.3+git.50c5c33]
- [Precision Prospecting](https://modrinth.com/mod/QV5ehY9M) [1.20.1-1.0.0]
- [TFC Support Indicator](https://modrinth.com/mod/RL8eBaUL) [1.0.1]
- [Ferrite Core](https://modrinth.com/mod/uXXizFIs) [6.0.1]
- [TFCGyres-OreHints](https://www.curseforge.com/projects/838993) [2.1]
- [Dynamic Lights](https://modrinth.com/mod/7YjclEGc) [1.7.1+mod]
- [Patchouli](https://www.curseforge.com/projects/306770) [1.20.1-84-FORGE]
- [Model Gap Fix](https://modrinth.com/mod/QdG47OkI) [1.15]
- [Fastload-Reforged](https://modrinth.com/mod/kCpssoSb) [3.4.0]
- [TFC Astikor Carts](https://www.curseforge.com/projects/844019) [1.1.8.1]
- [Connectivity Mod](https://www.curseforge.com/projects/470193) [1.20.1-5.5]
- [Just Enough Items](https://www.curseforge.com/projects/238222) [15.3.0.4]
- [Macaw's All-In-One for TFC](https://www.curseforge.com/projects/908983) [0.2.30-1.20.1]
- [Firmalife](https://modrinth.com/mod/5bKeBHw2) [2.1.3]
- [Smoothchunk mod](https://www.curseforge.com/projects/582327) [1.20.1-3.6]
- [recipeessentials mod](https://www.curseforge.com/projects/907856) [1.20.1-3.4]
- [Multi Mine](https://www.curseforge.com/projects/227887) [1.20.1.3]
- [AstikorCarts Redux](https://modrinth.com/mod/mnLFouB0) [1.1.7]
- [Caelum](https://modrinth.com/mod/Xkw3TXqP) [1.20.1-2.0.0.0]
- [TerraFirmaCraft](https://www.curseforge.com/projects/302973) [3.2.2]
- [ModernFix](https://modrinth.com/mod/nmDcB62a) [5.17.0+mc1.20.1]
- [TFC Ore Washing](https://www.curseforge.com/projects/959262) [1.0.3]
- [Cloth Config v10 API](https://modrinth.com/mod/9s6osm5g) [11.1.118]
- [Alternate Current](https://modrinth.com/mod/r0v8vy1s) [1.7.0]
- [TFC Water Flasks](https://modrinth.com/mod/ONgsGaM9) [3.0.2]
- [Mouse Tweaks](https://modrinth.com/mod/aC3cM3Vq) [2.25]
- [Gpu memory leak fix](https://www.curseforge.com/projects/882495) [1.20.1-1.8]
- [Better Combat](https://modrinth.com/mod/5sy6g3kz) [1.8.5+1.20.1]
- [Player Animator](https://modrinth.com/mod/gedNE4y2) [1.0.2-rc1+1.20]

**Comment by alcatrazEscapee** [comment]
Eh, this is fine, they are intentionally allowed to spawn into fluid depending on temperature, which this seems to be.
