### ISSUE TITLE
Drying Kelp on a Wrought Iron Grill/Charcoal Forge instantly creates Soda Ash

### ISSUE THREAD

**Issue by TalerzykTheMoth** [TerraFirmaCraft/TerraFirmaCraft#2696]
Putting Giant Kelp Flower on a lit grill or into a charcoal forge doesn't let you take Dried Kelp from it. The item inherits its temperature, therefore instantly turning into soda ash.

**Comment by Proxwian** [comment]
Can confirm. These items has identically recipe at the same temperature

![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/31781674/2083f63d-45b2-4807-9eae-e539d6ba5079)
![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/31781674/4e7a3233-a17a-49cd-bc25-eaf2d02b8307)
