### ISSUE TITLE
config missing & confusing naming issue

### ISSUE THREAD

**Issue by HeartyYF** [TerraFirmaCraft/TerraFirmaCraft#270]
![2019-08-08_22 09 37](https://user-images.githubusercontent.com/17660052/62711406-95bc0c80-ba2b-11e9-8c9e-bf197cd4761b.png)
![2019-08-08_22 09 41](https://user-images.githubusercontent.com/17660052/62711412-981e6680-ba2b-11e9-87f8-9c2bc2906e65.png)
![2019-08-08_22 09 45](https://user-images.githubusercontent.com/17660052/62711417-994f9380-ba2b-11e9-87b5-02260f2e567c.png)
You can see these should follow a same naming rule but they act differently. I think latter 2 shouldn't have space in their name.

![2019-08-08_22 23 37](https://user-images.githubusercontent.com/17660052/62711451-a8364600-ba2b-11e9-90d0-e41d8c359a9c.png)
I bet this can be found in lang files, but I don't know why it doesn't show.

**Comment by alcatrazEscapee** [comment]
Firstly - no. I can't see the issue, as I don't read Chinese. If you're going to report issues with screenshots, please take them in English.
Secondly, if you have two bugs, report them as two issues.
Finally, localization bugs should be reported to https://github.com/TerraFirmaCraft/TFC-Assets/issues

**Comment by HeartyYF** [comment]
I will fix config missing by myself. It's related to the source code.
