### ISSUE TITLE
Crash on startup [FORGE]

### ISSUE THREAD

**Issue by MaliciousLotus** [TerraFirmaCraft/TerraFirmaCraft#2704]
I have a pretty large modpack, around 117ish mods or so. I've had this mod BEFORE I added things such as ModernFix, and FerriteCore, along with Eureka! Ships! for optimization and more fun. Not sure if those are the problem but here's the crash log. https://pastebin.com/rERYR2wr

**Comment by alcatrazEscapee** [comment]
Duplicate of #2610
