### ISSUE TITLE
inaccurate vein location.

### ISSUE THREAD

**Issue by UnbridledAnger** [TerraFirmaCraft/TerraFirmaCraft#2706]
I'm playing TFC in the Auto TerraFirmaCraft modpack and am trying to find certain ore veins. I'm playing on a potato for a laptop so I am deciding to use commands to locate veins to cut down on resources spent searching. The problem is that the /tfc locate tfc:vein command is inaccurate. It IS mostly accurate when you use it near ore deposit signs(I'm forgetting the name of them, but they are the pebbles you find on the surface) Sometimes when you go to the coordinate it gives it turns out to be a place that would make no sense for the ore to spawn(see screenshot.) Besides this, I'm really loving this mod and modpack!
![Screenshot (28)](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/169866959/a8ec3071-b524-47ef-8c13-5437858c4ca0)

**Comment by alcatrazEscapee** [comment]
It's a debugging tool meant to find potential vein spawn locations chosen on a chunk independent basis, prior to actually spawning them.
