### ISSUE TITLE
Axles are invisible with chunk animator

### ISSUE THREAD

**Issue by AlexLikeFoxes** [TerraFirmaCraft/TerraFirmaCraft#2709]
Axles are invisible
Game version: 1.20.1
TFC Version 3.2.3
Forge: 47.2.32

**Comment by AlexLikeFoxes** [comment]
I found out what causes this, its another mod: chunk animator. Sorry for not checking the mod alone

**Comment by alcatrazEscapee** [comment]
After some further looking, chunk animator does in fact cause most of our block entities to not render, or at least, render with completely messed up position transforms. This happens with axles, bellows, looms, and pretty much every TFC BE that uses `RenderHelpers` to render faces directly.

Chunk animator has an issue (https://github.com/Harleyoc1/ChunkAnimator/issues/40) which has been closed for being "stale", but was open for a year prior about falling blocks not rendering correctly (being invisible). I can reproduce this in TFC with our falling blocks as well. Maybe this will get traction being reported to them, but this seems like entirely not our problem. Chunk animator is doing some weird shit that I don't care to try and understand, and they're breaking vanilla as well.
