### ISSUE TITLE
Mod injection failed

### ISSUE THREAD

**Issue by QianMuu** [TerraFirmaCraft/TerraFirmaCraft#2715]
I can't start my client because it says it can't inject the mod properly.
Here is my crash report:
[错误报告-2024-5-31_3.46.16.zip](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/15505092/-2024-5-31_3.46.16.zip)

**Comment by alcatrazEscapee** [comment]
This has nothing to do with TFC, you have a conflict between two mods that are trying to modify a field in `Biome`, neither mod is TFC
