### ISSUE TITLE
Crash during chunk loading

### ISSUE THREAD

**Issue by seBerserker** [TerraFirmaCraft/TerraFirmaCraft#2719]
After searching for rocks to make flux, the game crashes. The crash log indicates that a specific rock is the reason for this issue. As a result, I cannot go to that chunk. Other than that, everything is fine.
[crash-2024-06-01_18.39.26-server.txt](https://github.com/user-attachments/files/15522425/crash-2024-06-01_18.39.26-server.txt)

**Comment by alcatrazEscapee** [comment]
Without any further information, looks like a duplicate of #2661
