### ISSUE TITLE
River water and salt water do not waterlog

### ISSUE THREAD

**Issue by yorkeJohn** [TerraFirmaCraft/TerraFirmaCraft#2722]
The TerraFirmaCraft water variants `tfc:river_water` and `tfc:salt_water` do not waterlog blocks such as fences, slabs, stairs, etc.

**Comment by alcatrazEscapee** [comment]
River water is functionally fresh (vanilla) water and reports itself as such. Stairs, slabs, fences etc. are all coded with vanilla waterlogging in mind (i.e. they don't accept lava either) and so don't accept any modded fluids, including salt water.
