### ISSUE TITLE
Many missing recipes in 1.20.1 version

### ISSUE THREAD

**Issue by InTheProcess** [TerraFirmaCraft/TerraFirmaCraft#2728]
There are lots of recipes that are missing such as boat recipes and other stuff.  Could this be fixed?  I don't want to modify the jar file to add the recipes manually.

**Comment by alcatrazEscapee** [comment]
?? Name a single actual recipe you think is missing in TFC itself, that isn't either removed intentionally or by an addon.

**Comment by InTheProcess** [comment]
Ash boat under TFC:wood/boat/ash

There are many more missing boat recipes

**Comment by alcatrazEscapee** [comment]
No, they aren't.

![image](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/35673674/89cf205a-d428-45fd-ae34-e27757c80436)

You're probably using an addon that removes them, _like I said_.

**Comment by InTheProcess** [comment]
I will test it out.  Thanks
