### ISSUE TITLE
Can't hold vessel in hands

### ISSUE THREAD

**Issue by ROKBAS** [TerraFirmaCraft/TerraFirmaCraft#2733]
Vessel is too hot to touch. 
Can't  pour melted copper, but wiki says it should be obvious.
https://www.youtube.com/watch?v=m4lD2SfyYYQ
Terrafirmacraft 1.20.1
v. 3.2.4

**Comment by alcatrazEscapee** [comment]
You are using a modpack which changes behavior, ask them for support. In future our issue tracker is not for support requests, those should be directed to our discord, or the modpack's support channel(s).
