### ISSUE TITLE
Familiarity with animals returned to zero after re-entering the world

### ISSUE THREAD

**Issue by J4ckTh3R1pper** [TerraFirmaCraft/TerraFirmaCraft#2736]
version: 3.2.4
minecraft version: 1.20.1
loader: forge 47.2.6
modpack: All The Mods - Gravitas^2
Just as title said, however the familiarity returns to normal after chunk reloaded

**Comment by alcatrazEscapee** [comment]
Can't reproduce. Familiarity may decay over time if not raised past a minimum threshold, even if chunks are not loaded but the server is/was running. Without any further information or reproduction setup, assuming that was what happened here...

**Comment by iwishforducks** [comment]
It’s a visual bug. Had the same thing happen to me. Once you interact with an animal their familiarity will update back to normal.
