### ISSUE TITLE
HUD Compat/ enhancements

### ISSUE THREAD

**Issue by Cyberblaze-lp** [TerraFirmaCraft/TerraFirmaCraft#2741]
[1.12.2] So, i was playing around with the HUD options in the client config. My findings are listed below

1a: The way it is right now you can either choose to use the responsive health bar from TFC (aka show you your max health, adapts to things like nutrition) and exclude the armor bar, or use the vanilla health bar, enabling you to see your armor total, but your may HP is visually indifferent to change by TFC's mechanics. is this because of the damage type system overrides traditional armor points or sth?

I'd like it if you could keep the tfc health with the vanilla armor bar as a config setting. Truth be told, i feel naked without it

1b: while we're at it, you could divide the armor bar into 3 segments that each fill up with another translucent layer representing the 3 damage types
the regular armor could still be displayed below

2: The TFC hunger bar is totally unresponsive to anything vanilla or other mods add apart from food itself (i.e. the Saturation effect, Thaumcraft's sustainer charm, appleSkin's saturation overlay, etc.)
 my suggestion would be to make it a config option to simply use the vanilla hunger bar while applying a constant, configurable amount of exhaustion for passive hunger loss, and couple that to the thirst bar. 

if you choose to implement this, would be sweet if you could also make an option to choose if nutrition is updated on eating or on hunger refill for balancing reasons, as with the first option your health would stay the same if you used a sustainer charm, whereas the second one would make it trickle down to the lower limit the more you use the charm instead of preparing actual meals.

**Comment by alcatrazEscapee** [comment]
We are not maintaining 1.12 anymore; and suggestions for 1.20.1 should go to our discord, not here.
