### ISSUE TITLE
Snow-covered dirt doesn't obey gravity

### ISSUE THREAD

**Issue by MrHiTech123** [TerraFirmaCraft/TerraFirmaCraft#2742]
Dirt that has been covered with snow does not have gravity the same way that regular dirt does.

For example, if Loam Grass has been covered with snow, and the block is removed from underneath, it will not fall.

**Comment by alcatrazEscapee** [comment]
Cannot reproduce. Removing the block underneath snow behaves as intended. Tested with snow blocks, single and multiple snow layers:

https://github.com/user-attachments/assets/f6606743-9702-4f27-af03-2aac902d6910

I believe you may be confusing this with intended behavior, wherein the presence of a block on top (of which snow counts), affects the ability of a block to landslide to the side, which is evident in removing the snow on top causing a block to fall:

https://github.com/user-attachments/assets/7d3822d0-cf9f-4b75-9d93-bee365236e83
