### ISSUE TITLE
Crash when sealing barrel

### ISSUE THREAD

**Issue by meir** [TerraFirmaCraft/TerraFirmaCraft#2747]
I got TFC 3.2.6 installed for 1.20.x

Almost every time i try to seal a barrel it seems to crash the entire game.
It's not consistent, sometimes it does not crash, but most times it does.

This only happens with barrels, the large vessels dont seem to have this issue.

[crash-2024-07-26_13.57.27-client.txt](https://github.com/user-attachments/files/16391244/crash-2024-07-26_13.57.27-client.txt)

**Comment by alcatrazEscapee** [comment]
This crash does not appear to be coming from TFC; The crash is for a different mod's mixin into a vanilla class.

```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at net.minecraft.client.renderer.entity.ItemRenderer.handler$cke000$injectRenderModelSwapping(ItemRenderer.java:575) ~[client-1.20.1-20230612.114412-srg.jar%23386!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:alekiehm.mixins.json:ItemRendererMixin,pl:mixin:APP:creategoggles.mixins.json:ItemRendererMixin,pl:mixin:APP:embeddium.mixins.json:features.render.model.item.ItemRendererMixin,pl:mixin:APP:mixins.oculus.json:entity_render_context.MixinItemRenderer,pl:mixin:A,pl:runtimedistcleaner:A}

```

Potential culprits are `alekiehm`, `creategoggles`, `embeddium`, or `occulus`. I've tried to track down the source of who's injecting `injectRenderModelSwapping()`, and as far as I have seen it's not [Create Goggles](https://github.com/Robocraft999/CreateGoggles/blob/1.20.1/forge/src/main/java/com/robocraft999/creategoggles/forge/mixin/ItemRendererMixin.java), [Embeddium](https://github.com/embeddedt/embeddium/blob/20.1/forge/src/main/java/me/jellysquid/mods/sodium/mixin/features/render/model/item/ItemRendererMixin.java), or [Occulus](https://github.com/Asek3/Oculus/blob/1.20.1-new/src/main/java/net/irisshaders/iris/mixin/entity_render_context/MixinItemRenderer.java), and I could not find any source for Aleki EHM so could not verify that, and in leiu of any other source it strongly seems that is the mod with the culprit method.

Closing as a likely issue for Aleki EHM - this should be reported to them first.

**Comment by meir** [comment]
Thank you, i've looked at it, it seems to be the Easy Held Models mod by Alekiponi.

I'll check if they have a github page and start an issue there
