### ISSUE TITLE
Raw foods can't cook

### ISSUE THREAD

**Issue by quag-cactus** [TerraFirmaCraft/TerraFirmaCraft#2748]
Game version: 1.20.1
TFC Version 3.2.6
Forge: 47.3.5

I can't make "cooked food" in firepit UI (without pot) .
Food temperatures seem to reach the maximum level possible for the fuel wood. And whatever temperature is reached, cooked food can't be obtained.
![2024-07-26_23 27 48](https://github.com/user-attachments/assets/9a843fa0-c88d-4303-97fe-a1c26dc9adfd)

**Comment by gettingrich2925-bit** [comment]
i have same problem now

**Comment by JokePatent** [comment]
I agree tried to cook some mutton and a sheep's leg and I cooked it for a whole day, but got nothing in return.

**Comment by FrostBandit1** [comment]
as i see it the seed is broken and u need to make a new world that had worken for me
