### ISSUE TITLE
Exception generating new chunk

### ISSUE THREAD

**Issue by JeSOAS** [TerraFirmaCraft/TerraFirmaCraft#2750]
[crash-2024-07-30_15.09.27-server.txt](https://github.com/user-attachments/files/16430174/crash-2024-07-30_15.09.27-server.txt)
[latest.log](https://github.com/user-attachments/files/16430175/latest.log)

While exploring properly generated TFC world on a server experience crashes when players encounter particular chunks. 
Chunk deletion using Amulet doesn't help.

**Comment by alcatrazEscapee** [comment]
It appears you are trying to use a non-TFC world generator, but spawning some TFC entities as per

```
java.lang.IllegalStateException: Tried to access ChunkDataProvider but none was present on net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator@20dca2b7
```

In general a non-TFC chunk generator should work, although spawning TFC entities would not be supported, so I'm unsure what you're trying to do here, or what entities are trying to spawn.

**Comment by alcatrazEscapee** [comment]
Closing as unreproducible.
