### ISSUE TITLE
New textures for Polar bear, Grizzly bear, Black bear.  

### ISSUE THREAD

**Issue by Dodo-merm** [TerraFirmaCraft/TerraFirmaCraft#2755]
Hello, it seems to me that the texture of bears is very outdated compared to the new added mobs, so I created new textures for polar bear, grizzly bear, black bear. If you like everything, then please replace the old bears textures with new ones:

![Polar Bear](https://github.com/user-attachments/assets/5e32ff5c-aacb-4d75-8025-610217be13bd)
![Grizzly Bear](https://github.com/user-attachments/assets/b0e20daf-0c7d-4647-88a4-26d469f66b0d)
![Black Bear](https://github.com/user-attachments/assets/8a9c70df-89c5-4ca7-b928-89e78fb8c412)

![polar_bear](https://github.com/user-attachments/assets/e1574837-5ec4-4434-8aeb-f9e72f746bd0)
![grizzly_bear](https://github.com/user-attachments/assets/1e5d4326-83a0-42e3-b65f-64cd8b0bf643)
![black_bear](https://github.com/user-attachments/assets/d3da8da7-405d-486c-b269-4a4dab5afd83)

**Comment by alcatrazEscapee** [comment]
This is not how to submit a PR; please don't use our issue tracker as our suggestions channel.
