### ISSUE TITLE
Can I fork this for fabric?

### ISSUE THREAD

**Issue by xuanplus** [TerraFirmaCraft/TerraFirmaCraft#2768]
As title.

I don't know if it's going to work, but I want to try

**Comment by alcatrazEscapee** [comment]
If you are not interested in contributing to TFC, you have all the rights granted in [the license](https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12) which I suggest you read. If you go ahead, please make it clear this is your own project and not endorsed or supported by us.
