### ISSUE TITLE
When attempting to open casting interface with a small vessel it just says "too hot to open" and that's it. When it cools down the ore is gone.

### ISSUE THREAD

**Issue by JustSkotch** [TerraFirmaCraft/TerraFirmaCraft#2771]
Steps to recreate the issue:
1.Acquire small vessel (fired, obviously)
2.Put in any ore
3.Process it in a pit kiln
4.When taken out it will show the "too hot to open" tooltip until the vessel is cold and any casting is impossible

I'm using the mod in TerraFirmaGreg modpack of the latest version for 1.20.1

**Comment by alcatrazEscapee** [comment]
This should be reported to the modpack creators for player support, unless you can reproduce this issue with TFC alone.
