### ISSUE TITLE
pumice does not fall out when panning or slicing

### ISSUE THREAD

**Issue by gre4kapi** [TerraFirmaCraft/TerraFirmaCraft#2773]
I washed 5 stacks of rhyolite gold-bearing gravel, a lot of gold fell out, a lot of rhyolite stones and even pyrite, but not a single pumice
[https://imgur.com/a/5NbC4Rx](url)

**Comment by alcatrazEscapee** [comment]
"I got an unlucky result" is not an issue.

**Comment by gre4kapi** [comment]
According to the native_gold_rhyolite loot table, pumice should drop with a chance of 0.25
I checked in creative on a hundred stacks of Rhyolite Native Gold Deposit, not a single pumice, but 4 Raw Pyrite, the chance of which is 0.0533. I'm sure this is a real bug and not just an "unlucky result"
Ore washing setup and results:
[https://imgur.com/a/rzSijUU](url)
