### ISSUE TITLE
remove Meat/Bread burnup mechanic

### ISSUE THREAD

**Issue by BadsyEdgecat** [TerraFirmaCraft/TerraFirmaCraft#2775]
cooked meat and bread items being able to burn up, as was added in 3.2.6, makes it so that they are no longer easily able to stack, requiring the player to either wait, or plunge the items into water to "quench" them.
i appreciate the idea of realism in how it can be overcooked, but it just makes cooking a pain to deal with when every food item you cook has Heat nbt that makes it not stack. 
Also, the default burnup temperature for breads is bad for Firmalife's bread baking system, as a few wood types burn at bright red, which, with the fact that Firmalife's cooking mechanic in ovens has its own timer, means that by the time the dough becomes bread, it is also at the burnup point.

Apologies for if this is rude, I just think that this addition is shooting for additional realism in a way that doesnt add any real depth, and also introduces the ridiculous idea of 'a player soaks a loaf of bread in water to cool it, and then stores it away in a vessel or similar function to preserve it, despite the fact that that would encourage mold growth'

**Comment by alcatrazEscapee** [comment]
1. We don't use our issue tracker for suggestions, it is better suited to our discord
2. This is end-user customizable and you could remove this if you desired
3. Because we won't.
