### ISSUE TITLE
Dragon survival

### ISSUE THREAD

**Issue by The-Science-Cat** [TerraFirmaCraft/TerraFirmaCraft#2777]
the dragons in dragon survival can not regen hunger, so i think it would be awesome if you added a setting in server config to use default hunger and nutrition systems. thanks in advance.

**Comment by alcatrazEscapee** [comment]
No, we're not interested in broad scale disabling of core mechanics - this is also by the sounds of it, entirely a fixable issue and the proposed solution is an XY problem to compatibility with said mod.

**Comment by The-Science-Cat** [comment]
i see, ok
