### ISSUE TITLE
Barrels placed in racks face the wrong way

### ISSUE THREAD

**Issue by qwertyasdef** [TerraFirmaCraft/TerraFirmaCraft#2778]
When placing a barrel into a barrel rack, the tap faces away from you. This makes it annoying to have a barrel rack against a wall since you can't see the taps, or you need to break the wall and put the barrel in from the back every time you put a barrel in.

**Comment by eerussianguy** [comment]
We use the issue tracker exclusively for bug reports, not suggestions or support requests. This post would be more suitable for our [discord](https://discord.gg/PRuAKvY)'s suggestions channel, where the conversation can continue there.
