### ISSUE TITLE
[1.20.1-3.2.2] Allow using lidless jars to directly create unsealed jam

### ISSUE THREAD

**Issue by Hexicube** [TerraFirmaCraft/TerraFirmaCraft#2784]
Ran into this when going to make jam sandwiches, intuitively I should be able to use a jar with no lid and have it not be sealed for when I'm immediately using the jam rather than wasting a lid that isn't needed.

Based on changes since 3.2.2 it doesn't look like this has been added, if it has the github pages page for jam is out of date.

**Comment by alcatrazEscapee** [comment]
We use the issue tracker exclusively for bug reports, not suggestions or support requests. To which I believe I've already answered you.

**Comment by Hexicube** [comment]
There is no obvious place to make suggestions, and simply going "not planned" doesn't explain _why_ when TFC is supposed to be aiming for a "believable" experience (jars are obviously filled before being lidded).

**Comment by alcatrazEscapee** [comment]
> There is no obvious place to make suggestion

There's a channel named `#suggestions`... As I've already said, this is not the space to debate them.
