### ISSUE TITLE
Create pipes and crucible crash

### ISSUE THREAD

**Issue by AZV-EU** [TerraFirmaCraft/TerraFirmaCraft#2785]
[crash-2024-09-10_01.16.55-server.txt](https://github.com/user-attachments/files/16937517/crash-2024-09-10_01.16.55-server.txt)

When placing a curcible near a create fluid pipe, the crucible gets connected and after a second the game crashes.
Crashlog included in the thread.

**Comment by alcatrazEscapee** [comment]
Please attach a full log as I'm suspicious of a badly added compat recipe causing there to be a missing alloy or metal.

**Comment by AZV-EU** [comment]
[latest.log](https://github.com/user-attachments/files/16944801/latest.log)

**Comment by alcatrazEscapee** [comment]
```
[14:30:39] [Render thread/INFO]: tfc:kjs/atmo409nsxc2ybqzw0pl9semf: {"type":"tfc:alloy","result":"createaddition:electrum","contents":[{"metal":"tfc:gold","min":0.2,"max":0.3},{"metal":"tfc:silver","min":0.4,"max":0.8}]}
...
[14:30:40] [Render thread/ERROR]: There were 1 'metal' that were used but not defined: [createaddition:electrum]
```

Your pack is adding an alloy recipe for `createaddition:electrum`, which requires a metal to be present (see [Alloy Recipe](https://terrafirmacraft.github.io/Documentation/1.20.x/recipes/#alloy)), but not adding the corresponding metal, causing TFC to print this error, and then later crash. This is the fault of whomever is adding the recipe to fix.
