### ISSUE TITLE
1.20.1: Any Structure are not Spawning in

### ISSUE THREAD

**Issue by Joshernoob** [TerraFirmaCraft/TerraFirmaCraft#2787]
I'm Currently Working on a Modpack with this and Create as the main to mods and have a few Create structures that are meant to spawn around the world as you load it, however when i load the TerraFirmaCraft Preset and only that preset they will not load in

Not sure if this a bug or intended but it be great to have a way to use them

On the last Version of both mods and using 

- Create: Dynamic Village
- Create: Structure Arise FORGE
- Create: Create Space

All have in world generation on the surface I could not find and when i went Underground I Could not seem to find Alex Cave's Cave Generations as well

**Comment by Joshernoob** [comment]
full On Problem Here now As Seems That NO strucures are spawning with this mod enabled even vanilla ones..

**Comment by Joshernoob** [comment]
![Screenshot 2024-09-18 022801](https://github.com/user-attachments/assets/39a5301c-ba07-4c86-9f34-e96774bdefb0)

**Comment by alcatrazEscapee** [comment]
TFC does not spawn vanilla structures, this is intentional. You can add compatibility with individual structures with a datapack if desired.

**Comment by Joshernoob** [comment]
An option to disable this would be great.

Like the nether restriction in the server file.

Reason is that it prevents many modpack creators from using the mod as other mods are not compatible with vanilla structures disabled

Mods that add bosses or new NPCs are some good examples.

And stating other mods need to do the work to get your custom terrain compatible just going to make people hate it more.

> TFC does not spawn vanilla structures, this is intentional. You can add compatibility with individual structures with a datapack if desired.

**Comment by Joshernoob** [comment]
IF you Say you can not add or will not add that to the config then can you give me or anyone else permission to make an addon that will let players play with Structure enabled past what is meant in the mod

**Comment by alcatrazEscapee** [comment]
Modpacks with TFC and structures [already exist](https://www.curseforge.com/minecraft/modpacks/all-the-mods-gravitas2), you're yapping.
