### ISSUE TITLE
Leather can't make things.

### ISSUE THREAD

**Issue by CloudHillSea** [TerraFirmaCraft/TerraFirmaCraft#2789]
I can't make leather while I am playing.1.12.2，TFC，and I added an accessory mod "TFC water flasks"，The items inside can't be made either.

**Comment by CloudHillSea** [comment]
1.1262

**Comment by alcatrazEscapee** [comment]
1.12 is not supported anymore

**Comment by CloudHillSea** [comment]
Ok, I see. I will continue to troubleshoot the problem myself. Thanks to the author.
