### ISSUE TITLE
molds wont heat

### ISSUE THREAD

**Issue by LGMa09** [TerraFirmaCraft/TerraFirmaCraft#2791]
hello
i dont know why but my clay molds wont heat inside my pit killns
currently im using the version 3.2.6 on an aternos server 
i first downgraded the version from 3.2.7 to 3.2.6 but it stil didnt work
does sb know how to fix this?

**Comment by alcatrazEscapee** [comment]
We use the issue tracker is used for issue reports, not support requests. Please use our [discord](https://discord.gg/PRuAKvY) and upload your log file for someone to help.
