### ISSUE TITLE
Softlocked: Pit kiln and small vessel not working together

### ISSUE THREAD

**Issue by ghost** [TerraFirmaCraft/TerraFirmaCraft#2794]
I'm on The TerraFirmaCraft Starter Pack through CurseForge. 
Following the guide book given I tried to put 10 small Limonite I had found on the surface in a Vessel to make 1 wrought iron pickaxe head, to be able to progress. 

Problem: When the small vessel comes out of the pit kiln it stays on yellow-white** and never reaches white, when right clicked to open interface for casting it says "Too hot to open!"
Eventually it cools back to 0 heat again and then the ore inside is just completely unsmelted. 

Any other thread I found on this says either completed or solved but yet this is still a problem for me. 
I updated to the latest version for the main mod TerraFirmaCraft and the problem remained.

**Comment by alcatrazEscapee** [comment]
We use the issue tracker for bug reports, not support requests, please use our [discord](https://discord.gg/PRuAKvY) for those. You're clearly not following the guide book because nowhere does it say limonite, can be melted into wrought iron, in a pit kiln.
