### ISSUE TITLE
Firing multiple crucibles at once by small vessel

### ISSUE THREAD

**Issue by HoshinoTented** [TerraFirmaCraft/TerraFirmaCraft#2799]
I was trying to fire 2 unfired crucibles by placing them in the same slot in a small vessel, but I got only 1 crucible.
I guess the key is that the crucible is unstackable while the unfired crucible isn't.

TFC version: 3.2.7
I am playing tfc by [ATMG2](https://www.curseforge.com/minecraft/modpacks/all-the-mods-gravitas2), I am not sure whether it does matter.

**Comment by alcatrazEscapee** [comment]
This is works as intended; although we could make the unfired crucible not stackable to prevent the confusion in future. But in general, any heat recipe from a stackable -> unstackable item will have this issue.
