### ISSUE TITLE
Putting refined bloom in a crucible creates "unknown alloy"

### ISSUE THREAD

**Issue by Flaksmith** [TerraFirmaCraft/TerraFirmaCraft#280]
Putting a refined bloom of any size into an empty crucible (or one with wrought iron) creates an "unknown alloy" instead of wrought iron like it should.

For now, you can work around this by refining the bloom using an anvil.

**Comment by DisasterMoo** [comment]
This is already fixed in #264

**Comment by alcatrazEscapee** [comment]
Fixed by #264
