### ISSUE TITLE
FEATURE: Please add checks for Curios slots (Curios API) in overburdened calculation in TFC 1.20

### ISSUE THREAD

**Issue by koenigstag** [TerraFirmaCraft/TerraFirmaCraft#2800]
Found that TFC addons add Curios Slots (Back, Belt) and TFC does not count these slots in inventory weight calculations (Helper.countOverburdened method).
It would be great if TFC could see these slots too and add them to count, being soft dependent on curious api mod.

**Comment by alcatrazEscapee** [comment]
We use the issue tracker exclusively for bug reports, not feature suggestions or support requests.

**Comment by koenigstag** [comment]
Fine, will write in Discord #suggesions then

**Comment by koenigstag** [comment]
Made an tfc addon for this as it was adviced in discord #suggestions
https://github.com/koenigstag/tfc-curios-weight
