### ISSUE TITLE
BUG: Hopper does not extract item from Crucible output in 1.20

### ISSUE THREAD

**Issue by koenigstag** [TerraFirmaCraft/TerraFirmaCraft#2801]
Tested the basic Crucible automation and found that hopper cannot extract item from output slot when placed at bottom.

MC version: 1.20.1
TFC version: 3.2.7

**Comment by alcatrazEscapee** [comment]
The crucible output slots are the sides, not the bottom.

**Comment by koenigstag** [comment]
So in bare TFC the hopper is not usable with Crucible.
And what should I use for crucible automation?

If I'm understanding this right, it is intended to use with any pipes mod.
But what if pipes are not fit to the medieval modpack.
Can we have a config to define the output slot behavior?
