### ISSUE TITLE
bucket config bug

### ISSUE THREAD

**Issue by bojarskydev** [TerraFirmaCraft/TerraFirmaCraft#2804]
this function does not work, the bucket does not create a water source.
[mechanics.fluids]
		#
		# If true, TFC buckets that naturally place sources (colored steel) will place sources. If false, this behavior is disabled.
		enableBucketsPlacingSources = true
		
TFC Version: 3.2.7

**Comment by alcatrazEscapee** [comment]
This config option hasn't been updated for the removal of the _default_ behavior of colored steel buckets placing sources. The behavior now is _technically_ correct - none of TFC's added buckets have source placement capability by default, and they aren't able to be enabled via this option. This option, as is in it's current form, should be removed, but I'd rather not risk breaking any dependents. This can be resolved in 1.21
