### ISSUE TITLE
neoforge 1.21.x trees only drop sticks

### ISSUE THREAD

**Issue by Mr-Squid42** [TerraFirmaCraft/TerraFirmaCraft#2808]
when in early game i've tried cutting down a tree with a stone axe and only got sticks

if this is intended, there is no documentation on how to obtain logs.

**Comment by alcatrazEscapee** [comment]
There is no released version for 1.21

**Comment by Mr-Squid42** [comment]
when you go to the terrafirmacraft code page on this github page, it shows a version for 1.21.x
