### ISSUE TITLE
Game crashing on start

### ISSUE THREAD

**Issue by troy0h** [TerraFirmaCraft/TerraFirmaCraft#2812]
Minecraft is instantly crashing on a modpack containing only TFC and Patchouli
https://mclo.gs/S94UZ5m

**Comment by AtobaAzul** [comment]
Same happening here! TFC Ver 3.2.9

**Comment by alcatrazEscapee** [comment]
A class that hasn't changed in a year compiled differently between 3.2.7 and 3.2.9. What the fuck.

**Comment by Svetrikk** [comment]
After updating to 3.2.9 it crashes after entering a world.
[crash-2024-11-01_10.26.55-server.txt](https://github.com/user-attachments/files/17598201/crash-2024-11-01_10.26.55-server.txt)

**Comment by WooflessDelta** [comment]
Having the same issue on 3.2.9 & 3.2.8
[crash-2024-11-02_05.37.45-server.txt](https://github.com/user-attachments/files/17606739/crash-2024-11-02_05.37.45-server.txt)

Except it just states 'net.minecraft.world.level.material.FluidState net.dries007.tfc.common.fluids.IFluidLoggable.m_5888_(net.minecraft.world.level.block.state.BlockState)'

Mod works with the modpack I have on curseforge if I go back down to 3.2.7

**Comment by Svetrikk** [comment]
> Having the same issue on 3.2.9 & 3.2.8
> 
> [crash-2024-11-02_05.37.45-server.txt](https://github.com/user-attachments/files/17606739/crash-2024-11-02_05.37.45-server.txt)
> 
> 
> 
> Except it just states 'net.minecraft.world.level.material.FluidState net.dries007.tfc.common.fluids.IFluidLoggable.m_5888_(net.minecraft.world.level.block.state.BlockState)'
> 
> 
> 
> Mod works with the modpack I have on curseforge if I go back down to 3.2.7
> 
> 

Same for me. 3.2.7 works normally, 3.2.9 crashes the game after entering a world

**Comment by palduun** [comment]
same issue here.
Started after i placed a crucible down
[crash-2024-11-02_15.38.25-server.txt](https://github.com/user-attachments/files/17608379/crash-2024-11-02_15.38.25-server.txt)

**Comment by Martzl90** [comment]
Same Problem here. 
[crash-2024-11-03_10.26.27-client.txt](https://github.com/user-attachments/files/17609892/crash-2024-11-03_10.26.27-client.txt)

**Comment by Brettehwarrior** [comment]
Also experiencing crash on startup (can't get to main menu), tested on Forge 47.3, 47.2 and 47.1 with no other mods installed
Same thing happens in 3.2.9 and 3.2.8, but 3.2.7 seems to work fine
https://mclo.gs/pQL56Nu

**Comment by alcatrazEscapee** [comment]
https://github.com/TerraFirmaCraft/TerraFirmaCraft/commit/6a78c48d71aa330b90d901d6a0401e574c932ac1
