### ISSUE TITLE
Crashes in TFC Hardrock 1.18.2 modpack

### ISSUE THREAD

**Issue by ZXQWAS** [TerraFirmaCraft/TerraFirmaCraft#2823]
I've started https://www.curseforge.com/minecraft/modpacks/terrafirmacraft-hardrock (+distant horizons) yesterday and it was all fine. Then a BSOD happened and I went to sleep. Today it was discovered that that BSOD corrupted my save, so I loaded it from backup. But now I'm constantly getting these crashes as in the attachments. I have also deleted and reinstalled my instance in case it was corrupted, but this didn't help.
[crash-2024-11-10_11.43.10-server.txt](https://github.com/user-attachments/files/17691119/crash-2024-11-10_11.43.10-server.txt)
[!CRASH.txt](https://github.com/user-attachments/files/17691123/CRASH.txt)

**Comment by alcatrazEscapee** [comment]
Yes, this looks like your world is corrupted as it is missing chunk data TFC uses during generation.

**Comment by ZXQWAS** [comment]
Would you be so kind as to describe what exactly should I remove from my save to make it workable again? Meanwhile I have loaded all 5 previous backups (made every 30 minutes) and they all crash when I get close to the same vicinity. The exact chunks are not the same.

**Comment by ZXQWAS** [comment]
Ok, so I have deleted all chunks except closest to my base with MCA Selector, and it helped. Meanwhile, I find it very suspicious that I was able to play for so long with corrupted chunkdata, as it wasn't caused by BSOD since backups were made hours before, and I had no idea of this corruption. I did have a couple "normal" MC crashes though. Is there a tool to check TFC chunk integrity?
