### ISSUE TITLE
Flashing health and nutrition bar on server

### ISSUE THREAD

**Issue by Chozo142** [TerraFirmaCraft/TerraFirmaCraft#2830]
isolated to tfc but found in gravitas pack, Health bar and nutrition info all flash while you heal on servers, doesn't happen during single player

**Comment by srccc74** [comment]
Same issue, looks like it's happened after updating to latest version

**Comment by Adam4CZ** [comment]
Yesterday I updated my single player world and I'm having the same problem. I also included videos in my ticket #2835

**Comment by alcatrazEscapee** [comment]
Closing in favor of #2835
