### ISSUE TITLE
Raw eggs cannot be cooked

### ISSUE THREAD

**Issue by Adam4CZ** [TerraFirmaCraft/TerraFirmaCraft#2834]
Hello,

I found a problem in the recipe for cooked eggs.
I see in the TFC book and JEI recipe that it should be possible to make a cooked egg in the firepit at Hot****, but when I try to do this, the egg never cooks, even when I have the temperature even higher (when I tried going over Orange***, it broke, which is correct according to JEI)

Is it a bug, a conflict with another mod/addon, a bug in JEI or something else?

![TFC-book-cooked_egg-recipe](https://github.com/user-attachments/assets/25b4ddcf-d925-4c7f-b62b-50fdc5d49108)
![JEI-cooked_egg-recipe](https://github.com/user-attachments/assets/35bf4a65-de8d-4021-b344-45b38cc5075f)
![firepit-egg-not-cooked](https://github.com/user-attachments/assets/04607279-3f47-4db3-9ecd-f2fcde62cc77)

**MC version:** 1.20.1
**TFC version:** 3.2.10
**Mods/Addons:** Firmalife (2.1.13), Farmer's Delight (1.2.5), Farmer's Delight TFC (1.0.5) and some others that I don't think have any bearing on the food recipes

**Comment by robbert229** [comment]
I think that this is related to the broken anvil recipes, reverting to the last release is a good temporary work around.

**Comment by Adam4CZ** [comment]
@robbert229 In which version does this recipe work? I had version 3.2.7 before the update and it didn't work in that version either.

**Comment by robbert229** [comment]
I don't exactly have the exact dates, but my hunch comes from investigating the anvil issue.

I have a fix that I am working on for the anvil issue, and I noticed that in the same area there appears to be an issue with eggs.

**Comment by alcatrazEscapee** [comment]
This is a recipe overlap between the cooked one, and destroyed one. The second one shouldn't exist (as it conflicts).

**Comment by Adam4CZ** [comment]
I can confirm that it's fixed in TFC v3.2.11
