### ISSUE TITLE
HP bar is buggy if not full

### ISSUE THREAD

**Issue by Adam4CZ** [TerraFirmaCraft/TerraFirmaCraft#2835]
I updated my singleplayer TFC today from 3.2.7 to the latest 3.2.10 and discovered this minor bug.
If I don't have full HP, my HP bar flickers. As soon as my HP fills up to full, this flickering stops. I did not have this problem in the previous older version.

https://github.com/user-attachments/assets/023fa28c-1e58-4d52-846e-f3fd68ddcf50

EDIT: I found that this problem is also in the Nutrition GUI. I am attaching the second recording. It looks like it's trying to sort of revert to the default value when the player first joins the world.

https://github.com/user-attachments/assets/030cb1e1-d5ae-49c8-a197-15f272e8f9a2

**MC version:** 1.20.1
**TFC version:** 3.2.10

**Comment by Adam4CZ** [comment]
I found that someone only reported this problem as on the server #2830 . But I have this problem even in the single-player world after updating to the latest version.

**Comment by izharus** [comment]
To reproduce the bug:
Minecraft 1.20.1, Forge (43.1.3 or 43.3.8 - haven't tested others), TFC 3.2.10.

1) Create a new world.
2) Skip to daytime: `/time set day.`
3) Take 400-500 HP damage by falling.
4) Run around the world for a few minutes and wait until your food bar decreases slightly.
5) As soon as this happens, the health bar will start glitching, as shown in the video. The health bar keeps glitching until your HP is full.

**Comment by Adam4CZ** [comment]
I can confirm that it's fixed in TFC v3.2.11

**Comment by izharus** [comment]
> I can confirm that it's fixed in TFC v3.2.11

For me too.
