### ISSUE TITLE
Fruit trees don't drop saplings

### ISSUE THREAD

**Issue by Adam4CZ** [TerraFirmaCraft/TerraFirmaCraft#2838]
Is there some condition, only a small chance of dropping sapling from fruit trees, or do they not drop? I have already broken several "elbows" of fruit trees with an axe and so far not a single sapling has dropped. I only ever get sticks and fruit leaves (Firmalife).

**MC version:** 1.20.1
**TFC version:** 3.2.11 (but same was on 3.2.10 and 3.2.7)

**Comment by alcatrazEscapee** [comment]
Cannot reproduce.

**Comment by Adam4CZ** [comment]
@alcatrazEscapee is there like only 20% chance, special condition to drop (specific season) or anything like that? I have already broken several "elbows" of many fruit trees with an axe and so far not a single sapling has dropped.

**Comment by Adam4CZ** [comment]
Here's game recording: https://drive.google.com/file/d/14RSb_kcymqIk4r8PsMrByzRmdeXdsO-8/view?usp=drive_link (too big to upload it directly)
