### ISSUE TITLE
food with 0% saturation should show that in the shift overlay

### ISSUE THREAD

**Issue by wchristian** [TerraFirmaCraft/TerraFirmaCraft#2839]
Right now food with 0% saturation simply does not mention saturation at all.

![image](https://github.com/user-attachments/assets/1644edd5-ab0b-4e53-b84f-8638275f0f65)

This has the unfortunate side effect of never teaching newbies that saturation is a thing at all, or that saturation is in fact a value they can see ingame as on sandwiches.

![image](https://github.com/user-attachments/assets/79eb3155-049f-4bf2-80e2-00f7a1c0606e)

Making even saturation 0% show on all other foods would lead to organic and emergent discovery of the mechanic.

(Originally reported in https://github.com/AllTheMods/Gravitas2/issues/412 but i was informed this might be a better place.)

**Comment by alcatrazEscapee** [comment]
We do not use the issue tracker for suggestions, this would be more suited for our discord, but moreover, 

> Right now food with 0% saturation simply does not mention saturation at all.

Intentional, and consistent with water, and all other nutrient values that aren't present on the food. Including all of those would bloat the tooltip unnecessarily. It is already capable of emergent discovery by seeing it on a sandwich for the first time, as you've demonstrated.

**Comment by wchristian** [comment]
> as you've demonstrated

You're assuming there, and you know what happens when you assume.

Your assumption is completely wrong. I never discovered it. The current design does not provide a reason to, at the game stage where it is important.

The nutrition values are mostly useless until one reaches the stages of the game where actively modifying HP becomes important, and until that point no other food had shown anything but nutrition under the shift menu so there was no point whatsoever in looking it up. Meanwhile the saturation value is extremely important early on when food is scarce.

I only ever learned about it because someone else pointed it out after 100+ hrs of play.

By your logic about "bloating" it would honestly be more useful to remove the nutrition tooltips altogether, given how little they matter.
