### ISSUE TITLE
Crash with Create ponder when raining

### ISSUE THREAD

**Issue by dnk1234567** [TerraFirmaCraft/TerraFirmaCraft#2842]
Version:
TerraFirmaCraft 3.2.11
Create 0.5.1-j

The procedure to reproduce:
1. Create a world

2. Opening a Create's ponder screen which has mobs:
![2024-12-07_17 22 57](https://github.com/user-attachments/assets/5fe8f5fd-97d0-4262-9a7a-7fcb34f8e25d)

I used Deployer, and it worked well in clear weather.

3. Using command to set the weather to rain

4. Repeat step 2, the game will crash after this moment:
![2024-12-07_17 25 23](https://github.com/user-attachments/assets/2d309d2c-e9ef-4a0a-a5c2-dfb45a62646a)

Crash Report:
[crash-2024-12-07_17.25.28-client.txt](https://github.com/user-attachments/files/18047835/crash-2024-12-07_17.25.28-client.txt)

**Comment by alcatrazEscapee** [comment]
6594bc5713ce98b5a46f41034685c28bbb10a71a
