### ISSUE TITLE
Smithing table UI not working

### ISSUE THREAD

**Issue by Gamevirus9** [TerraFirmaCraft/TerraFirmaCraft#2844]
The smithing table seems to be broken and nothing can be placed within the table. I tried multiple different trims but nothing seems to be able to be placed within. This was on the most current version on 1.20.1. Banners were not tested from the different sewing patterns but trims definitely were not functional.

**Comment by alcatrazEscapee** [comment]
Cannot reproduce with a solo TFC instance, trims are functional.
