### ISSUE TITLE
Incompatible with C2ME (Fabric)

### ISSUE THREAD

**Issue by 01XUAN** [TerraFirmaCraft/TerraFirmaCraft#2845]
3.2.11versions  The probability of occurrence is not high, or it may be caused by other mod.
java.lang.NullPointerException: Cannot load from int array because "this.surfaceHeight" is null
[2024-12-11-4.log](https://github.com/user-attachments/files/18091844/2024-12-11-4.log)

**Comment by 01XUAN** [comment]
C^2M-Engine and TFC are not compatible （I didn't see it on the test before ?   When testing, it was found that the number of frames loading new snow-covered chunk in the winter was much more stable）

**Comment by alcatrazEscapee** [comment]
C2ME is a Fabric mod and there's no feasible way for us to provide support for it or use it in a dev environment. And they are likely, again, because they're a fabric mod, breaking chunk loading hooks added by Forge that we rely on.
