### ISSUE TITLE
Ore amount error

### ISSUE THREAD

**Issue by Thyr0s** [TerraFirmaCraft/TerraFirmaCraft#2847]
I just got my first mined copper, and poor is showing as melting to 60 mB, normal as 25, and Rich as 35. 
![2024-12-15_13 00 26](https://github.com/user-attachments/assets/92806f5d-2c52-440c-a491-b6d7ba6d2fe3)
![2024-12-15_13 00 29](https://github.com/user-attachments/assets/0b03795d-8f2a-46c7-8af6-2d087e9e8c8f)
![2024-12-15_13 00 30](https://github.com/user-attachments/assets/384f0a26-4c50-40e3-ad21-21be81c04b8d)

**Comment by alcatrazEscapee** [comment]
4 x 15 = 60, yes

**Comment by Thyr0s** [comment]
I'm a complete idiot, sorry for the bother. don't know HOW I managed to forget I'd mined multiple
