### ISSUE TITLE
Export Block ID's

### ISSUE THREAD

**Issue by douglasdtlltd** [TerraFirmaCraft/TerraFirmaCraft#2850]
Is there any way to export or make a list of block Id's for plants and blocks to add them to a shader pack? 

I've already done about a hundred of them, and I dont want to do them by hand any more. 

I just need a way to make a whole list instead of copying and pasting one by one from "setblock 1 1 1 tfc:plant/*"

**Comment by alcatrazEscapee** [comment]
We use the issue tracker exclusively for bug reports, not suggestions or support requests. This post would be more suitable for our [discord](https://discord.gg/PRuAKvY).
