### ISSUE TITLE
Crash on load with Pam's Harvestcraft installed

### ISSUE THREAD

**Issue by Verph** [TerraFirmaCraft/TerraFirmaCraft#288]
The game crashes when loading TerraFirmaCraft with Pam's Harvestcraft installed. These are the only two mods on a fresh install.

The following versions were used:
_Pam's Harvestcraft v1.12.2ze
TerraFirmaCraft v0.19.0.47_

Here's a Pastebin error report: https://pastebin.com/Grb29JFm

_No crashes happens if loaded with TFC v0.18.1.46_

**Comment by alcatrazEscapee** [comment]
Hmm, it appears my quick fix to make temperature work properly was somewhat non-ideal. I'll take a look at this and see if I can't reconcile the temperature system I'm going for with whatever pams is doing here.
