### ISSUE TITLE
Pumpkin can synthetize pumpkin seeds.

### ISSUE THREAD

**Issue by hidfug** [TerraFirmaCraft/TerraFirmaCraft#291]
![-1ea4bf20b256e0d8](https://user-images.githubusercontent.com/34993841/62828753-7a662280-bc20-11e9-991c-9acc8d77ad4a.png)

**Comment by hidfug** [comment]
0.18.0.45

**Comment by alcatrazEscapee** [comment]
This is the vanilla pumpkin -> seeds recipe that needs to be added to the remove recipe list
