### ISSUE TITLE
Charcoal can make mineral disappear.

### ISSUE THREAD

**Issue by hidfug** [TerraFirmaCraft/TerraFirmaCraft#293]
When I use charcoal melt mineral,the mineral will disappear even if I put vessel in it.
This bug is found in 0.18.0.45.

**Comment by alcatrazEscapee** [comment]
Please be more specific. What **exactly** are you doing, what do you expect to happen, and what is actually happening. If you're using the charcoal forge to melt metals, yes, they will melt and not return anything. To collect their metal you need to place empty molds in the side slots, or use a crucible.

**Comment by hidfug** [comment]
Can not the vessel collect melted mineral in charcoal forge?
