### ISSUE TITLE
World generation not working on a brand new Forge server

### ISSUE THREAD

**Issue by Tr0ll13n** [TerraFirmaCraft/TerraFirmaCraft#294]
Brand new Forge forge-1.12.2-14.23.5.2838-universal server installation, TFC build #47 only mod installed. The world is generated Vanilla style. Health bar is OK, Vanilla recipes are gone, but sticks and rocks are not there, and trees can be punched by hand.

Attached log and debug files.

[Logs.zip](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/3489732/Logs.zip)

**Comment by alcatrazEscapee** [comment]
When I said post the logs, I meant just upload them in discord as this is not an issue with TFC, this is an issue with your setup. That said, I messed up earlier - the property you need to change is `level-type`, not `level-name`
