### ISSUE TITLE
Internal server error when starting fire in a firepit

### ISSUE THREAD

**Issue by Tr0ll13n** [TerraFirmaCraft/TerraFirmaCraft#295]
Tried with builds #47 and #48, TFC only mod on client and server.

When trying to start a fire in a firepit, player is disconnected because of an internal server error. 

Log attached.
[Java error on pit kiln.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/3490243/Java.error.on.pit.kiln.txt)

**Comment by alcatrazEscapee** [comment]
Full log please, not just what you think is the relevant part.

**Comment by Tr0ll13n** [comment]
Actually reproduced this morning on client, with a fresh build 48 installation. Logs attached.
[Logs - Firepit crash.zip](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/3491510/Logs.-.Firepit.crash.zip)

**Comment by Tr0ll13n** [comment]
With server crash log attached.
[crash-2019-08-12_10.28.42-server.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/3491512/crash-2019-08-12_10.28.42-server.txt)
