### ISSUE TITLE
Log blocks don't block light despite being solid

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#296]
I'm not sure if this is intentional, but in vanilla blocks on top of grass kills the grass, so it's not exactly consistent.

**Comment by GreyMario** [comment]
![2019-08-11_21 18 46](https://user-images.githubusercontent.com/502797/62845550-b7143700-bc7d-11e9-8c0a-67bd6bb9e02c.png)

A picture's worth a thousand words... and this one speaks volumes.

The cause is that logs don't actually block light.
