### ISSUE TITLE
Jei show recipes incompletely.

### ISSUE THREAD

**Issue by hidfug** [TerraFirmaCraft/TerraFirmaCraft#297]
![_(WGH{9I{(8Z5`2`$Q%3VHV](https://user-images.githubusercontent.com/34993841/62863608-de313e00-bd3b-11e9-9505-ae3f6f5a90bc.png)
![_JFYW8 (4@9BVG L5(W}8PN](https://user-images.githubusercontent.com/34993841/62863612-e12c2e80-bd3b-11e9-90bf-0e9e02ff7558.png)
![_1TB)4XZN)DGNUL`DDVN)2J](https://user-images.githubusercontent.com/34993841/62863618-e38e8880-bd3b-11e9-8bd9-7f5680d3f2ab.png)

**Comment by alcatrazEscapee** [comment]
I don't see a problem here. All of the above are valid recipes.

**Comment by DisasterMoo** [comment]
I've fixed this, the problem is that forge base Ingredient class stores `ItemStacks` to look up for valid outputs. Our `FluidIngredient` extends it by converting Fluid -> ItemStack but only provides forge's Universal Bucket. Here: cf37af47241581d5ac5fa3bf5f498c1be25e15cb
