### ISSUE TITLE
Berry bushes can generate underwater

### ISSUE THREAD

**Issue by technostarbtd5** [TerraFirmaCraft/TerraFirmaCraft#303]
Title describes the issue. Berry bushes can generate underwater. I have seen them generate in deep oceans, although it is likely that berry bushes can generate in other locations.

See image below:
 #https://i.imgur.com/1jEyoNO.png

World generated using latest github build. #

**Comment by alcatrazEscapee** [comment]
Please use the latest jenkins build, not the one from github. (0.20.1.51 at time of writing)

**Comment by GreyMario** [comment]
I'd like to bring up that this is not exclusive to berry bushes and as such should be checked and fixed for other affected items as well; per Jenkins [build #52](https://jenkins.dries007.net/TerraFirmaCraft#build-52) on world seed `HARDCORE` near `x: 773, y: 141, z: 452` a wild Potato was observed growing [submerged in swampland freshwater](https://cdn.discordapp.com/attachments/432527966266851339/611792485756305409/2019-08-15_22.24.33.png).
