### ISSUE TITLE
Fallable blocks should crush non solid blocks beneath them instead of popping off

### ISSUE THREAD

**Issue by JoseVillaa** [TerraFirmaCraft/TerraFirmaCraft#306]
I expected it to drop the normal dirt block instead of the grass block

To reproduce dig a column that would make the dirt fall due to gravity and place a torch underneath just when the column start falling (as to dig sand fast in vanilla minecraft). The top block will drop a grass type block

TFC Version 0.20.2.52

**Comment by alcatrazEscapee** [comment]
What should happen here, is the falling block should destroy any non-solid blocks underneath it - so the torch would break and the grass would not.

**Comment by muzikbike** [comment]
I think there should still be a way to get grass blocks in survival, perhaps through the same method as raw stone is obtained.
