### ISSUE TITLE
vinegar barel recipe bug

### ISSUE THREAD

**Issue by Mrthomas20121** [TerraFirmaCraft/TerraFirmaCraft#310]
**Describe the bug**
the vinegar barel recipe only show beer as input.

**To Reproduce**
look at vinegar recipe or look at any alcohol recipe using u to show what recipes they are used for.

**Meta Info**
 - TFC Version: 0.20.2.52

**Comment by alcatrazEscapee** [comment]
Commit message got messed up - this is fixed by 742a8dd3bdd8e8f91a2921a01ff0e51eaaeb04fa
