### ISSUE TITLE
Water jugs can stack when spamming left click

### ISSUE THREAD

**Issue by DavidTriphon** [TerraFirmaCraft/TerraFirmaCraft#313]
**Describe the bug**
1. What did you expect to happen?

Water jugs should not stack while full of water

2. What actually happened instead (i.e. what was the bug)

Water jugs can stack while full of water

4. If they would help to explain the issue, include screenshots

![2019-08-20_15 30 25](https://user-images.githubusercontent.com/20526831/63392047-e0ae1c00-c369-11e9-8eec-c61434e8ddeb.png)

**To Reproduce**
1. Accumulate multiple water jugs of 1 in each stack
2. Pick up 1 jug in hand
3. Spam left click to attempt to place in other water jug stacks.
4. If spamming on one single jug does not work, mouse over multiple jugs while continuing to spam left click, do not stop.
5. Eventually you will end up with a stack of 2 jugs. This stack of 2 jugs can be placed on any other water jug to increase the stack size.
6. Attempting to add 1 jug to the larger stack will not add a jug, but swap stacks in hand. left clicking again will add the multiple jugs to the single jug.

**Meta Info**
 - TFC Version: 0.21.0.53
 - Were any other mods included? Can you reproduce it without these other mods?
WAILA, JEI, JourneyMap
Did not test due to no suspicion of these mods

**Comment by DisasterMoo** [comment]
Just found out that in 1.7.10, jugs never stacked when empty

(tested in TechNodeFirmaCraft, but i think that is the same for any fork of TFC)
