### ISSUE TITLE
Food Expiration Date Lost upon Relogging to Server

### ISSUE THREAD

**Issue by Therighthon** [TerraFirmaCraft/TerraFirmaCraft#317]
If you are on a server and log off with a food item in your inventory, the creation date gets set to negative a bajillion when you log back in, causing it to rot. This does not happen when exiting to main menu and reloading a single-player save.

**Comment by alcatrazEscapee** [comment]
Did this occur after an extended period logged off? Or does it occur regardless of the time spend logged off?

**Comment by Therighthon** [comment]
Regardless of time logged off

**Comment by alcatrazEscapee** [comment]
I *think* this will be fixed by 7d972f9ec3ba2ac55644f17668670229d26dc89a - I'll reopen if not
