### ISSUE TITLE
Hunger does not decrease + nutritional values tab is empty

### ISSUE THREAD

**Issue by ferrolite** [TerraFirmaCraft/TerraFirmaCraft#323]
1. I have played for nearly two in-game days and my hunger has not decreased at all. Difficulty is Easy. I have cheats enabled in the world (which I didn't use to give myself infinite hunger or anything of the sort). Has something changed with the hunger mechanics?

2. I clicked the ~~nutrition tab~~ skills tab expecting to see the ~~nutritional value bars~~ skill bars and was instead met with an empty tab. 
![2019-08-22_00 00 35](https://user-images.githubusercontent.com/53090564/63468649-14279e00-c471-11e9-9e57-af393752c774.png)

I have a feeling that these two oddities are related somehow.

Here are some files to replicate this:

1. My [`saves/xenolith` folder](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/3527365/xenolith.zip). The world it all went down in.
2. My [`mods` folder](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/3527328/mods.zip). Contents:
    - **`TerraFirmaCraft-MC1.12.2-0.21.3.56.jar`**
    - `CodeChickenLib-1.12.2-3.2.3.357-universal.jar`
    - `Hwyla-Mod-1.12.2.jar`
    - `jei_1.12.2-4.15.0.268.jar`
    - `journeymap-1.12.2-5.5.5.jar`
    - `OptiFine_1.12.2_HD_U_E3.jar`
    - `PlaceableTools-1.7.10-1.2.0.36.jar`
    - `Wawla-1.12.2-2.5.273.jar`
3. My [`resourcepacks` folder](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/3527345/resourcepacks.zip). It contains a single custom pack to change rain and snow; it should not be interfering with any of the above, but I am including it regardless.

[EDIT] That was the skills tab. Oops!

**Comment by alcatrazEscapee** [comment]
Well for starters, you're looking at the skills tab, not the nutrition gui.
 🤦‍♂

**Comment by Aegwadar** [comment]
I'm encountering this same issue now. Running only thing that is taking down hunger.

![2019-08-21](https://user-images.githubusercontent.com/7348211/63482251-3962df00-c466-11e9-90fd-990ef9e66805.png)

Running only TerraFirmaCraft-MC1.12.2-0.20.2.52 and forge-1.12.2-14.23.5.2768.

Easy difficulty, no cheats/mods.

**Comment by Aegwadar** [comment]
![2019-08-21 (1)](https://user-images.githubusercontent.com/7348211/63482341-8941a600-c466-11e9-86d8-7397478ffc10.png)

Above was supposed to be this screenshot; with nutritional info displayed

**Comment by ferrolite** [comment]
@alcatrazEscapee, while it is true that that was the Skills tab (my mistake!), it is also not supposed to be completely empty, right?

@Aegwadar, I appreciate your screenshot. It’s good that the actual nutrition tab is working.

**Comment by alcatrazEscapee** [comment]
Anything that normally takes down hunger in vanilla will contribute - so running, jumping, breaking blocks, etc. I see no actual problem there.

Skills aren't implemented yet, see #163

**Comment by ferrolite** [comment]
I hadn’t seen the thing about skills! Thanks for filling me in. I believe this issue can be closed at this point.
