### ISSUE TITLE
TFC Stair blocks make entities inside them completely dark

### ISSUE THREAD

**Issue by DavidTriphon** [TerraFirmaCraft/TerraFirmaCraft#338]
**Describe the bug**
1. What did you expect to happen?

I put my head into the underside of a stair block.
I expected to stay the same light level.

2. What actually happened instead (i.e. what was the bug)

My entire body turned dark.

3. If it was a crash, upload the full log file (`latest.log`)

No crash.

4. If they would help to explain the issue, include screenshots

Player model in vanilla stairs versus TFC stairs.
![2019-08-25_21 33 30](https://user-images.githubusercontent.com/20526831/63665497-71c52e80-c780-11e9-9ed2-76d456cfce35.png)
![2019-08-25_21 33 32](https://user-images.githubusercontent.com/20526831/63665498-71c52e80-c780-11e9-8d70-9c64621829e7.png)

Item entities turn black while inside stairs.
![2019-08-25_21 32 59](https://user-images.githubusercontent.com/20526831/63665496-71c52e80-c780-11e9-90d9-443fa370c538.png)

**To Reproduce**
1. Place some slabs on the ground
2. Place some upside down stairs 2 blocks above the slabs.
3. Walk on the slabs so that your head is in the stairs.
4. Your body turns black.

Note: any entities that fit into the air space of TFC stair blocks turn black, such as items.

**Meta Info**
 - TFC Version: 0.21.4.DEV
 - Were any other mods included? Can you reproduce it without these other mods?
No other mods.

**Comment by alcatrazEscapee** [comment]
I'd like to point out that the method in which vanilla decides to assign `useNeighborBrightness` is to check, after registering vanilla blocks, if `block instanceof BlockStairs || block instanceof BlockSlab`, which conveniently only applies to vanilla stairs, and is also in the last place I'd think to look.
¯\_(ツ)_/¯
