### ISSUE TITLE
Crops don't take into account farmland moisture, 

### ISSUE THREAD

**Issue by alcatrazEscapee** [TerraFirmaCraft/TerraFirmaCraft#342]
Farmland moisture could probably be averaged with rainfall to find a medium between strict growth conditions and manual watering. Farmland moisture calculation should be adjusted to take this into account - be 30 / 70 influenced by area vs surrounding water. Crops should then only check the farmland moisture instead

Crops also are missing nutrients checks - this needs to be part of larger changes to farmland. Nutrients was discussed as being saved to chunk data rather than part of farmland. Possible avenues for replenishment via grass growing, or random ticks on fallow farmland blocks? (Note: this would largely eliminate the need to rotate crops around, rather just have mixed farms in a chunk)

**Comment by aldo1028** [comment]
suggestion to maybe leave it up to each individual farm block and leave crop rotations in. Not sure what benefits the chunk data might have, but if you are stuck with setting up farmland near where 4 chunks meet at your base it sounds like it would be a pain

**Comment by DisasterMoo** [comment]
Made crops take into account moisturize to grow (just a tiny bit). Nutrients will not see any implementation in 1.12.
