### ISSUE TITLE
Can't work Black High Carbon Steel Ingot in a Steel Anvil

### ISSUE THREAD

**Issue by Flaksmith** [TerraFirmaCraft/TerraFirmaCraft#351]
![2019-08-30_12 18 08](https://user-images.githubusercontent.com/46166245/64029983-3fb92100-cb20-11e9-9c73-a884d1cdb8c4.png)
See the text in the chat

I suspect it's the same issue we had before with pig iron not being workable in a wrought iron anvil.

**Comment by DisasterMoo** [comment]
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/3719943774d7116de9da100245d95fdca4fe3e73/src/main/java/net/dries007/tfc/types/DefaultMetals.java#L172 this needs to be `TIER_IV`
