### ISSUE TITLE
Blackberries and Raspberries despawn if they drop too close to the bush

### ISSUE THREAD

**Issue by Flaksmith** [TerraFirmaCraft/TerraFirmaCraft#353]
Since these bushes (can't remember if there are others) have the properties of a cactus they cause items to despawn when they land inside them. Either make berries automatically go to your inventory (like rocks and sticks) when harvesting them, or remove the deleting properties of the bushes.

As a side note, could we get tree fruit to behave the same if you choose the former option?

**Comment by muzikbike** [comment]
I'd prefer the deleting properties to be removed so they're a bit closer to vanilla 1.14 bushes.
