### ISSUE TITLE
Heating recipes doesn't show all the options for heating like other recipes.

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#357]
It should match like the crafting does where it shows all the things that can heat stuff.
![](https://i.imgur.com/cv3c66R.png)

**Comment by alcatrazEscapee** [comment]
Specifically what should it show? It can't show a fire pit or charcoal forge as they don't have associated items. Crucible doesn't make sense to show there imo. And "heating ability" is not something restricted to certain catalysts - anybody can add a new device that heats stuff with no way to automatically detect it.

**Comment by Claycorp** [comment]
The IE auto-crafter isn't an item and they have the model there. Something can be figured out to fix it.

Also it seems to pick up on other mod crafting tables if you add them thus there must be some logic to it. Either they are adding it or JEI is picking up on it.

**Comment by alcatrazEscapee** [comment]
Well no, it is an item, that's how they fixed it
