### ISSUE TITLE
Anvil recipes list ignores all tier requirements nor mentions them.

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#358]
![](https://i.imgur.com/RZHdFmp.png)
This shows red steel getting worked but still shows all anvil tiers. Either ones that can't work it need to be removed or tier information needs to be applied to the recipes.

**Comment by alcatrazEscapee** [comment]
Recipe catalysts are registered per type, not per recipe, so in order to do the first we'd have to split anvil recipes per tier, which I think is an awful solution. So in this case the recipe should probably just display the tier as text in the upper left / right corner.
