### ISSUE TITLE
[Crash]Report

### ISSUE THREAD

**Issue by MokoBlack** [TerraFirmaCraft/TerraFirmaCraft#36]
[crash-2019-03-21_13.43.53-server.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/2990988/crash-2019-03-21_13.43.53-server.txt)

**Comment by Bunsan** [comment]
You aren’t using the forge version which we are using for development. 1.12.2-14.23.4.2705 Please replicate the error in the proper version of forge.
