### ISSUE TITLE
Platinum Melting temperature is too high for the forge/crucible

### ISSUE THREAD

**Issue by Flaksmith** [TerraFirmaCraft/TerraFirmaCraft#387]
Melting temperature is set above the maximum temperature obtainable via the forge or crucible. According to another person Lead has the same problem.

**Comment by UnlimatedStone9** [comment]
I did some of my own testing and lead definitely melts fine, platinum however isn't melting...

![image](https://user-images.githubusercontent.com/40124890/64479068-85718b80-d1a9-11e9-8f39-75cac40cf3dc.png)
