### ISSUE TITLE
Other mods metals/items can't be placed into anvils

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#388]
1. What did you expect to happen?
Be able to place GTCE red steel into TFC's anvil like JEI claims to work.

2. What actually happened instead (i.e. what was the bug)
Couldn't place ingot into anvil.

To put it simply, whilst materials from other mods are happy to melt in crucibles, heat up and be forge-able, TFC anvils only ever accept TFC ingots to be placed into anvils.

![image](https://user-images.githubusercontent.com/40124890/64392525-124f0480-d045-11e9-9004-db08a6c885bb.png)

**Comment by alcatrazEscapee** [comment]
What is the craft tweaker script you are using to make these ingots forgeable?

**Comment by alcatrazEscapee** [comment]
Closing as per discord discussion, you need to add the forgeable capability either via addon or craft tweaker.
