### ISSUE TITLE
[Wiki] TFC Pit Kiln CraftTweaker documentation non functional.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#391]
I would appreciate some help here!
None of these tested import examples work...

import mods.terrafirmacraft.PitKiln;
import mods.terrafirmacraft.Pitkiln;
import mods.tfc.PitKiln;
import mods.tfc.Pitkiln;
import mods.terrafirmacraft.Kiln;
import mods.terrafirmacraft.kiln;
import mods.tfc.Kiln;
import mods.tfc.kiln;

**Comment by alcatrazEscapee** [comment]
See https://github.com/TerraFirmaCraft/TerraFirmaCraft/wiki/Heating

**Comment by UnlimatedStone9** [comment]
I'm sorry but this is still nonfunctional and I would appreciate further explanation.
