### ISSUE TITLE
Barrels cancel processes when unloaded

### ISSUE THREAD

**Issue by ferrolite** [TerraFirmaCraft/TerraFirmaCraft#392]
If a refining process (e.g. turning sand into mortar in a limewater barrel) is started and the player leaves the area so that the chunk becomes unloaded, the process will be cancelled (e.g. the sand will be in limewater without the "Result: Mortar" text, and there will be no mortar if long enough has passed).

 - TFC Version: 0.23.7.4

**Comment by Therighthon** [comment]
To corroborate, I had this issue when logging in and out of a world.

After sealing a barrel, the barrel noted the time it had been sealed, and what it would produce correctly. After exiting the single player world and reloading it, however, the output text vanishes, though the date sealed remains. As an aside, the processes will not complete from using /timetfc to advance time, but will still go to completion in its natural time if the barrels are not unloaded.
Before closing world: https://i.imgur.com/KY1scVa.png
After reopening: https://i.imgur.com/XzXPtQT.png

**Comment by alcatrazEscapee** [comment]
Barrels use total time to determine date, so advancing time via command won't have an affect - that is expected. I believe that barrels aren't saving their cached recipe, and should be re-checking cached recipe either on load, or on read from NBT.
