### ISSUE TITLE
rocks and sticks generate on top of pre-built structures

### ISSUE THREAD

**Issue by DavidTriphon** [TerraFirmaCraft/TerraFirmaCraft#393]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?

I updated my TFC version from .57 to .74
I didn't expect rocks and sticks to spawn on top of my structures.

2. What actually happened instead (i.e. what was the bug)

rocks and sticks generated on my exposed floors and roofs

3. If it was a crash, upload the full log file (`latest.log`)

no crash

4. If they would help to explain the issue, include screenshots

![2019-09-07_18 37 43](https://user-images.githubusercontent.com/20526831/64482057-f19ac200-d19e-11e9-82fd-9cf12e371cdc.png)

**To Reproduce**
Attention to detail is important!
1. Create and play a world in a previous .57 version
2. Clear out an area and place blocks to guarantee that the area is cleared.
3. Update TFC to .74
4. Play the world. Find rocks and sticks on the placed blocks.

**Meta Info**
 - TFC Version: 0.21.4.57 and 0.23.7.74
 - Were any other mods included? Can you reproduce it without these other mods?

WAILA, JMap, JEI

 - If necessary, what other mods (including versions) MUST be present to experience the bug?

I did not test this issue with other mods or other configurations. I suspect that this is a one time thing. I'm mainly worried about why rocks and sticks generated a second time on world load.

**Comment by alcatrazEscapee** [comment]
This is part of a larger issue with world regeneration - it should really use the inhabited time of the chunk as a measure to determine if regeneration needs to occur. It shouldn't just run regeneration after a certain time (which is the current case). This would be better implemented as part of a proper spawn protection system, as it can use the same chunk data values.

**Comment by Heimdell** [comment]
Probably, the regeneration of grass/ticks/stones was causing my thatch bed to unroot.

**Comment by alcatrazEscapee** [comment]
Marking this as not fixed as the current "fix" for this isn't satisfactory imo. I'd like to rework regeneration of debris to be spawn protection based, which requires a bit of effort, and I'd rather not throw in a half solution until we can get that sorted
