### ISSUE TITLE
Charcoal pits are broken, as well as forges.

### ISSUE THREAD

**Issue by Firecracker74** [TerraFirmaCraft/TerraFirmaCraft#400]
No charcoal is created in the pit, the wood burns away. You cannot place dirt over wood piles when making charcoal. Forges cannot be lit and the iten charcoal seems to have been removed as I could not get it even through commands/creative.

**Comment by alcatrazEscapee** [comment]
Please create separate reports for separate issues. For what you have mentioned:
 - make sure the forge has the correct requirements (chimney, surrounded by solid blocks), in order to be lit.
 - there is no TFC specific charcoal, nor does TFC remove vanilla charcoal.
