### ISSUE TITLE
Clay knapping should not consume clay if recipe isn't completed

### ISSUE THREAD

**Issue by alcatrazEscapee** [TerraFirmaCraft/TerraFirmaCraft#408]
Clay knapping shouldn't remove the items if you close the inventory gui. It makes logical sense, as you can just slap the clay back into a ball and try again.
 - Maybe add an `onCloseGui` to the knapping gui and hook it for clay type only?

v0.23.7.74

**Comment by Flaksmith** [comment]
Is fire clay handled differently? I remember back in 1.7.10 clay knapping behaved like you stated above, however for some reason fire clay behaved like it does now (always consumed the 5 clay).

Also can you make it so the 5 clay is consumed upon closing the gui? I remember in 1.7.10 the moment you completed the pattern for a mold it would consume the 5 clay even if you somehow messed up and clicked another tile afterwards. In that case you would get no mold and the 5 clay would be consumed.

**Comment by alcatrazEscapee** [comment]
This isn't fixed properly as of v0.25.2.86

**Comment by alcatrazEscapee** [comment]
This also affects completing multiple recipes: i.e. hoe -> hammer will consume 10 clay, 5 each time a recipe completes.

**Comment by alcatrazEscapee** [comment]
fe755923e4439a2b47574ef8864449d2a04ea0e4
