### ISSUE TITLE
Knapping items deletes output with full inventory

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#420]
**Describe the bug**

1. What did you expect to happen?
The item to drop onto the floor instead of disappear.
2. What actually happened instead (i.e. what was the bug)
It attempted to put the item into my full inventory and just deleted the item.

**To Reproduce**
1: Have a full player inventory.
2: Attempt to knapp an item but don't select the output item, just exit the knapping GUI.

**Meta Info**
 - TFC Version: 1.12.2-0.23.2.70

**Comment by DisasterMoo** [comment]
This is intended. It works like the crafting table, so, if user don't grab the output the crafting isn't complete. Also take note that it is intended that some knapping recipes (rock and leather) consumes the ingredient at start so if you don't grab the output the recipe is lost.

**Comment by alcatrazEscapee** [comment]
I disagree. If there is an item in the GUI when you close it, I would expect it to function like a crafting table - either dump it into your inventory if possible, or spit it out onto the ground.
