### ISSUE TITLE
Melon crop drops preservable melon blocks which leads to even more melon items

### ISSUE THREAD

**Issue by DavidTriphon** [TerraFirmaCraft/TerraFirmaCraft#422]
**Describe the bug**
1. What did you expect to happen?

I harvested a melon plant in the wild.
It dropped something other than seeds.
I expected to be able to eat it.

2. What actually happened instead (i.e. what was the bug)

It dropped a melon block which was non-edible.
It's also unable to be crafted into something else edible.

3. If it was a crash, upload the full log file (`latest.log`)

no crash

4. If they would help to explain the issue, include screenshots

![2019-09-13_21 39 41](https://user-images.githubusercontent.com/20526831/64903502-3b881a00-d66f-11e9-9a37-4007b80c1fa0.png)

**To Reproduce**
1. Harvest a mature melon plant.
2. Attempt to eat the melon it drops.
3. You can't. It's not food.

**Meta Info**
 - TFC Version: 0.23.7.74
 - Were any other mods included? Can you reproduce it without these other mods?
WAILA, JEI, JMap
 - If necessary, what other mods (including versions) MUST be present to experience the bug?
did not test.

**Comment by alcatrazEscapee** [comment]
If we make the blocks (pumpkin and melon) obtainable, they should decay. Which means they need to take into account when they are placed + broken and preserve the decay value. Likely require a registry replacement of melon + pumpkin blocks so that they store the item when placed in a TE, and drop said item when broken.

As for the melon not giving food, place the melon and break it (vanilla mechanic). Up for debate if we need to add something else.

**Comment by alcatrazEscapee** [comment]
To add to this: Our texture override is the wrong one - we override the slice texture with a full melon, which leads to weird behavior where breaking a melon block drops many melons.

**Comment by DavidTriphon** [comment]
So currently melon crops drop melon block items. Those melon blocks can be preserved indefinitely because they have no decay time. Then when they are placed and broken, they drop new fresh melon items that are retextured to look like full melons instead of slices. This results in melons being the best crop by far for obtaining food because it has a storage state that never rots and each item is actually about 3-6 pieces of food.

This should probably be fixed by making melons drop melon slices instead of melon blocks.
