### ISSUE TITLE
[Crash] ExPetrum + TFC

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#424]
**Describe the bug**
1. What did you expect to happen?
Game to launch.
2. What actually happened instead (i.e. what was the bug)
Game crashed on startup.
3. If it was a crash, upload the full log file (`latest.log`)
https://paste.dimdev.org/iramagefuy.mccrash

**To Reproduce**
1: Install ExPetrum and TerraFirmaCraft together.

**Meta Info**
 - TFC Version: 1.12.2-0.23.2.70

If my assumptions are correct, something to do with how TerraFirmaCraft changes item stack sizes and the way ExPetrum handles items is conflicting.

ExPetrum:
https://github.com/V0idWa1k3r/ExPetrum/issues/23

**Comment by alcatrazEscapee** [comment]
ExPetrum's backpack item is the problem here. It doesn't do any checks on whether or not a capability exists before just returning it's inventory, unlike basically every other item capability in the game. On them to fix.
