### ISSUE TITLE
[Crash] TFC, ThermalExpansion/Foundation and CraftTweaker?

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#425]
**Describe the bug**
1. What did you expect to happen?
The game to launch.
2. What actually happened instead (i.e. what was the bug)
Game crashed on startup.

Crash with all three:
https://paste.dimdev.org/zudumisovo.mccrash
Crash without CraftTweaker:
https://paste.dimdev.org/puxosacuye.mccrash

**To Reproduce**
Install TFC, ThermalExpansion/Foundation and CraftTweaker.

**Meta Info**
 - TFC Version: 1.12.2-0.23.2.70
 - Were any other mods included?
TFC, ThermalExpansion/Foundation and CraftTweaker.

**Comment by UnlimatedStone9** [comment]
I managed to receive this crash without either ThermalExpansion/Foundation or CraftTweaker installed. On a different client with different mods, this crash has been occurring for me a lot lately and it's very unusual, things will seem to work fine, I'll relaunch the game and TFC just refuses to ever work again.
https://paste.dimdev.org/ezipobedif.mccrash

**Comment by alcatrazEscapee** [comment]
It *looks* like something is trying to get the translation key / tooltip of a gemstone item used as an ore dictionary value... very curious

**Comment by alcatrazEscapee** [comment]
Note: I think I've fixed this because I just essentially made all the call paths for this safe - it may still be present if I've misunderstood the issue (as I've not been able to reproduce this).

**Comment by UnlimatedStone9** [comment]
Confirmed fixed!
