### ISSUE TITLE
Custom knappable items.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#427]
I think it would be, if at all possible, incredibly useful to be able to create custom knappable items.
To put it simply, I would choose what item can be knapped, wool for example, how many get consumed when knapping (just like how clay consumes 5 but rocks consume 1), whether or not you can try again (like clay where if you fail you don't lose all 5 clay), if you require a tool (like leather with knives), and furthermore what their outputs/recipes are.
Additionally the ability to remove existing items like rocks/clay/leather and add to those categories, Eg: adding PrimalCore rocks to be useable as igneous/metamorphic/sedimentary rocks.

This just improves compatibility and customisation, nothing more.

**Comment by alcatrazEscapee** [comment]
There's two things here:

 - making an existing item usable as an ingredient for existing knapping is doable - ideally this will be accomplished with an ore dictionary value (if it isn't already)
 - making a new knapping gui / system altogether can be done via an addon, using the API to add a new knapping type and implementation

**Comment by DisasterMoo** [comment]
Vanilla clay doesn't have an ore dict entry by default. The only one that needs to be updated to ore dict is charcoal in `IPlaceableItem`.

**Comment by alcatrazEscapee** [comment]
We can add `clay` to vanilla clay, `fireClay` to ours. That should solve both situations
