### ISSUE TITLE
Item's constructed from ore dictionary entries use wildcard metadata (32767) instead of 0

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#430]
**Describe the bug**
1. What did you expect to happen?
Nothing.
2. What actually happened instead (i.e. what was the bug)
For some odd reason TFC item textures often break in other mods "machines/containers", I've seen this happen with the outputs of GregTech machines/block drops and the BetterWithMods crucibles/kilns
4. If they would help to explain the issue, include screenshots
![image](https://user-images.githubusercontent.com/40124890/64973963-de28de80-d8a3-11e9-8043-05752fde23df.png)

**To Reproduce**
1. Install another mod like GregTech or BetterWithMods (for GregTechs case set 'tfc' as modPriority in gregtech.cfg)
2. Create a TFC metal using that mod (GregTech ore nugget drops, GregTech primitive blast furnace, BetterWithMods Crucible etc)

**Meta Info**
 - TFC Version: 1.12.2-0.23.8.75

**Comment by alcatrazEscapee** [comment]
Does the ingot have any NBT or metadata attached? Use F3 + H to view advanced tooltips, and enable debug tooltips in the TFC config. Full log would also be useful here.

**Comment by UnlimatedStone9** [comment]
<tfc:metal/ingot/steel:32767> The item seems to receive a massive increase in metadata in the GregTech blast furnace... That's very abnormal.
I'll do some testing with BetterWithMods one was created with this metadata too <tfc:metal/ingot/steel:32767>.
My first guess was it was trying to take the metadata of GregTech's steel ingots but that's not the same; <gregtech:meta_item_1:10184>.
I couldn't get Advanced Tooltips to work.
I also noticed that debug mode was enabled by default in the configs, since version 1.12.2-0.23.8.70, could still be enabled in 1.12.2-0.23.8.75.
These were my logs:
[latest.log](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/3617578/latest.log)

**Comment by alcatrazEscapee** [comment]
It's trying to create a result from an ore dictionary ingredient, which is configured to accept any metadata values, despite not using any of them. This could probably be fixed on TFC's end, but it may be difficult to track down all the cases
