### ISSUE TITLE
Remove ore:ingotIron from wrought iron

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#431]
A good few mods prefer to use wrought iron and iron separately, a configuration option to separate both metals and remove the ore:ingotIron/ore:nuggetIron etc from TFC Wrought Iron would be incredibly useful, it would also limit the two different forms of iron from crossing recipes.

**Comment by Claycorp** [comment]
TFC doesn't have an iron equivalent, Far more mods use iron than wrought iron.

In either case with TFC installed they would be effectively the same as you can't get iron without recipe/oredict changes. Just remove the oredict with CraftTweaker as you will need it anyway.

**Comment by alcatrazEscapee** [comment]
See #362. I'm not opposed to adding a config option for it.

**Comment by Claycorp** [comment]
> Adding the config option has no point.
> 
> With the ordict, All iron crafting recipes can be made and vanilla iron is unobtainable, wrought iron overlaps would need to be CT'ed to fix them if you don't want them to overlap.
> 
> Without the ordict all iron crafting recipes can't be made and vanilla iron is unobtainable, Wrought Iron is fine and untoched. You would need to CT a recipe for vanilla iron or change all the recipes to another iron.
> 
> Both ways result in the same outcome.

Posting the message from discord about this.

**Comment by alcatrazEscapee** [comment]
Superseded by #442
