### ISSUE TITLE
Calendar/Year length configs missing

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#432]
It's as simple as that, we need a config option for how long years are.

**Comment by alcatrazEscapee** [comment]
See the `/timetfc` command, there's an option for changing month length. (It's saved per world)

**Comment by alcatrazEscapee** [comment]
See the `/timetfc` command, there's an option to change month length, it's saved per world.

**Comment by UnlimatedStone9** [comment]
Sweet, thanks Alc!
