### ISSUE TITLE
Config option to disable the ability to place ingot stacks

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#436]
I think it would be a nice improvement to be able to, optionally, disable the ability to make ingot piles, given other mods, such as charset immersion, do this mechanic better, and allow creating stacks from ingots of any mod, I think it would be nice if people were able to disable TFC's ingot stack mechanics, for consistency.

It could also be done if people just want ingots to only be store-able in containers because they don't like ingot stacks for whatever reason.

Merely a quality of life enhancement for customization, nothing more.

**Comment by alcatrazEscapee** [comment]
> do this mechanic better, and allow creating stacks from ingots of any mod
So the real suggestion here is to improve TFC's ingot piles?

I am opposed to just adding in disable config options for various mechanics or features unless there's a very specific need for it. *Especially* with the current state of the mod, "X doesn't work well or isn't fully implemented" is a really bad reason for asking to disable it.

**Comment by UnlimatedStone9** [comment]
Well, given that TFC ingot piles only handle ingots, and aren't gamebreaking to be disabled (i.e not needed for a large content adding feature, merely cosmetic), and the only downside to disabling them is not having easy storage (which likely isn't an issue if you're disabling them anyways), I think it would be a useful addition for players to be able to disable them.
Unless you're willing to allow ingot piles to handle sheets, plates, gears, rods, gems/crystals, double ingots, etc alongside regular ingots, TFC's ingot piles are just bloat when using better alternatives.
While yes TFC isn't meant to be torn apart for better alternatives to replace, it is nice to have the option to disable small parts of the mod.
A player might just not want ingot piles, period. That's up to them to disable it then.

Just my thoughts.
