### ISSUE TITLE
[Ore Dictionary Fixes] Lapis and Sulfur

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#437]
Sulfur needs to be added to the ore:dustSulfur ore dictionary to be use-able in other recipes.
Lapis ore needs to be removed from ore:gemLapis as that is the dictionary for the actual lapis gem, this means the raw ore can be used in gem requiring recipes, oreLapis and gemLapisLazuli should work as the ore, ore dictionaries.

**Comment by alcatrazEscapee** [comment]
Superseded by #442
