### ISSUE TITLE
[Suggestion, Enhancement] Bellow Pitkilns.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#439]
Bellows can speed up the firing of pottery, etc, in a pit kiln when actively worked.
This would be the equivalent of raising the forges/crucibles temperature to heat things more.

**Comment by UnlimatedStone9** [comment]
Since we don'y have a modern pitkiln, this seems like a fair trade off.

**Comment by alcatrazEscapee** [comment]
First off, you can already use the forge + bellows as a pit kiln.
Second off, if you have something not a bug, then don't use the "bug report" template.
Third, suggestions for new mechanics are better suited for discord discussion rather than issues on github.
