### ISSUE TITLE
Missing ore dictionary names / use in recipes

### ISSUE THREAD

**Issue by alcatrazEscapee** [TerraFirmaCraft/TerraFirmaCraft#442]
Mega-issue for missing ore dictionary names.

 - [ ] Sulfur should be added to `dustSulfur`
 - [ ] Lapis is using `gemLapis`, should use `oreLapis` and `dustLapis` respectively. (TFC doesn't really have an equivalent for vanilla's lapis.
 - [ ] Add `craftingTableWood` to workbenches (vanilla uses both workbench and crafting table). Don't add each per type.
 - [ ] Make the additional `ingotIron` configurable - TFC should all use wrought iron, this is only added for compat anyway.
 - [ ] Mortar should be added to `mortar`
 - [ ] `plate[Metal]` should be optional, as it's only for compatibility (TFC uses `sheet`), and it's not a direct conversion to most modded plates which are 1-1 with ingots.
 - [ ] `gemCinnabar` should be `oreCinnabar` (are there others?)

**Comment by UnlimatedStone9** [comment]
Alcatraz suggested discussing here so I am.

Foods such as cooked and raw meat need to be added to the ore:listAllmeat, ore:listAllmeatraw and ore:listAllmeatcooked ore dictionaries.
Each specific food such as steak and beef for example need to be added to ore:meatBeef, ore:meatBeefraw and ore:meatBeefcooked.

Alcatraz's argument was that it's too specific to need adding, and that it's mainly for customisation in which any pack maker could add it themselves.

My argument was that it's a standard list of ore dictionaries in mods, such as BetterWithMods, Forestry and Pam's HarvestCraft for example.

**Comment by DisasterMoo** [comment]
> My argument was that it's a standard list of ore dictionaries in mods, such as BetterWithMods, Forestry and Pam's HarvestCraft for example.

I disagree. Forge already adds a bunch of ore dict entries for some vanilla items for default mod compatibility (such as the `ore:charcoal`, `ore:ingotIron`, etc) and it doesn't add the ones you mentioned. It is specific to some mods that add recipes from "anyMeat" or "anyRawFood".

To help your argument, can you grab a good list of mods that does this by itself (if you put the mod alone, that mod alone would add these ore dicts)
