### ISSUE TITLE
Food ore dictionaries missing.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#443]
Foods such as cooked and raw meat need to be added to the ore:listAllmeat, ore:listAllmeatraw and ore:listAllmeatcooked ore dictionaries.

Each specific food such as steak and beef for example need to be added to ore:meatBeef, ore:meatBeefraw and ore:meatBeefcooked.

**Comment by alcatrazEscapee** [comment]
I'm of the opinion that these are too specific to be useful without customization anyway, in which case it can be on the pack maker to add them themselves. Although I'm not a pack maker so I'm not aware of how many other mods would use this standard. Either way, discussion can happen in #442

**Comment by UnlimatedStone9** [comment]
@alcatrazEscapee, these ore dictionaries are standard in most food containing mods. BetterWithMods, Pam's, Forestry etc.
Adding them to TFC is only courteous and would in fact allow you to use TFC foods in other modded recipes without heavy configuration.
Being able to just install a mod and be able to use TFC's meats in their recipes is a hell of a lot better than having to learn and write CraftTweaker scripts.
It's just a thought. Since most people seem to use them.
