### ISSUE TITLE
Configurable Pitkiln/charcoal pit fire lighting items.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#444]
A configuration option or CraftTweaker method for what items can burst into flames when dropped onto Pitkilns or charcoal pits would be incredible useful.
It would consist of, what item bursts into flames, and how long it takes in ticks to light the fire.

**Comment by Claycorp** [comment]
This is partly covered by #394 

A better system does need to be looked into though for sure on the whole lighting things across the whole mod.
