### ISSUE TITLE
Logs are able to be placed in chests

### ISSUE THREAD

**Issue by alcatrazEscapee** [TerraFirmaCraft/TerraFirmaCraft#446]
They should be stored in log piles - may have to change the size restrictions on chests, or hardcode an exception for logs?

**Comment by DisasterMoo** [comment]
Which do you prefer: Logs' size = LARGE or HUGE? Gonna restrict chests to the desirable size.

**Comment by alcatrazEscapee** [comment]
Partially fixed by 8fbc2741d78db8916c3e1a10bdafd05360da3d69, then fixed for hoppers by f72897555db4642a38e9e56a0033cb2f5ea5c03f
