### ISSUE TITLE
Decorations creative tab is a mess.

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#45]
Many blocks are getting added in a mess of an order, They should be grouped better like the stair blocks.
![https://i.imgur.com/6w5G0TM.png](https://i.imgur.com/6w5G0TM.png)
![https://i.imgur.com/aoLmNQa.png](https://i.imgur.com/aoLmNQa.png)

**Comment by alcatrazEscapee** [comment]
Is it not grouped by wood type?

**Comment by Claycorp** [comment]
It should be grouped by block, not wood. That would match the way vanilla handles types.

If you want to do it by wood it should be consistent. All Ash blocks are together. Not Crafting tables, bookshelves then as Chests a separate block then a block of stone stairs with fence posts and buttons sorted like crafting tables and book shelves after the stone.

**Comment by alcatrazEscapee** [comment]
I'm assuming its based on insertion order, in which case it would probably require some ferkling around with this loop:
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/efdb61b146003d5cb8545060f51d2a4d12797532/src/main/java/net/dries007/tfc/objects/blocks/BlocksTFC.java#L304
