### ISSUE TITLE
Crash when exploring the world

### ISSUE THREAD

**Issue by Flaksmith** [TerraFirmaCraft/TerraFirmaCraft#457]
Was flying around in creative in a new world and all of a sudden the game froze then crashed
[crash-2019-09-22_21.48.57-server.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/3640336/crash-2019-09-22_21.48.57-server.txt)

**Comment by Trinsdar** [comment]
got the same crash: https://paste.dimdev.org/qiwubecija.mccrash

**Comment by Flaksmith** [comment]
Got the exact same crash just now in my main world
[crash-2019-09-28_10.58.16-server.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/3665494/crash-2019-09-28_10.58.16-server.txt)

**Comment by trilexcom** [comment]
same here https://gist.github.com/trilexcom/ccc45f32275cdc959861adf98bfcf1f7

**Comment by alcatrazEscapee** [comment]
As per #494 this seems like it isn't fixed.

**Comment by ourpar** [comment]
same crash here in version 0.25.2.86 [crash-2019-10-21_19.42.08-server.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/3753646/crash-2019-10-21_19.42.08-server.txt)

**Comment by agilmore2** [comment]
Just got this again with build 87 along with Worley's and several other mods.

**Comment by alcatrazEscapee** [comment]
I *believe* that this is to do with lava + water forming basalt cobblestone, which then quickly becomes a falling block, causing an infinite loop of forming more cobblestone and creating falling blocks. The resolution is to switch the formation of basalt cobblestone for rhyolite raw stone. (although what would form vanilla stone still forms basalt raw stone)
