### ISSUE TITLE
Age of world determines decay for newly created foods.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#458]
**Describe the bug**
1. What did you expect to happen?
Freshly created food without decay to be formed.
2. What actually happened instead (i.e. what was the bug)
Food decayed as soon as it was produced. Likely because of the age of the world.
![image](https://user-images.githubusercontent.com/40124890/65453368-f61bd780-de3a-11e9-9ed9-11146b218440.png)

**To Reproduce**
1: Add a recipe for food to something. Example uses a GregTec CE macerator.
2: Set the calendar forward and try to produce the food item.
3: Profit?

**Meta Info**
 - TFC Version: 1.12.2-0.23.8.75

Example scripts I used to produce the recipe using CraftTweaker, GregTech CE and TFC:

import mods.gregtech.recipe.RecipeMap;
val macerator = mods.gregtech.recipe.RecipeMap.getByName("macerator");
macerator.recipeBuilder()
    .inputs(<tfc:food/barley_grain> * 1)
    .outputs(<tfc:food/barley_flour> * 1)
    .duration(200)
    .EUt(2)
    .buildAndRegister();

**Comment by UnlimatedStone9** [comment]
Okay I did a little more testing on a brand new world and it seems food still immediately decays.
That's bad.

**Comment by alcatrazEscapee** [comment]
There's many things that could be going on here. The gist is that any recipes in TFC that deal with food manually account for setting the initial creation date when the food item is created. Any other mods won't deal with this naturally.

As far as I know there isn't a solution for this. If anyone has alternatives feel free to discuss them.

**Comment by alcatrazEscapee** [comment]
This *should* be better in general, based on how the individual mod handles their recipes. It's still not really fixable without an addon for specific mods though.

**Comment by alcatrazEscapee** [comment]
Various aspects have been improved, but insofar as this concerns other mod's machines, compatibility is going to have to be in the form of addons. We hope to have a small cooking system that gives pack makers the ability to add interesting mechanics and recipes that take into account decay.
