### ISSUE TITLE
Spawn is sometimes set in water.

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#46]
Sometimes spawn will land in water, you will spawn on the ground in said water. Yellow mark is where the world spawn is for this world.
![https://i.imgur.com/760krRS.jpg](https://i.imgur.com/760krRS.jpg)

**Comment by alcatrazEscapee** [comment]
This is already fixed in prototypes for 1.14. I doubt it will get looked at in 1.12 as from my testing it is fairly uncommon, can be avoided by creating a new world (which is not the only reason you would do this in TFC), and in general there's always land in sight.
