### ISSUE TITLE
vanilla shield is craftable with wrought iron ingots in two different ways

### ISSUE THREAD

**Issue by DavidTriphon** [TerraFirmaCraft/TerraFirmaCraft#463]
**Describe the bug**
1. What did you expect to happen?

I didn't expect to be able to craft a vanilla shield with TFC iron ingots.

2. What actually happened instead (i.e. what was the bug)

there are two recipes to make vanilla shields with TFC iron ingots.

3. If it was a crash, upload the full log file (`latest.log`)

no crash

4. If they would help to explain the issue, include screenshots

![2019-09-25_20 47 00](https://user-images.githubusercontent.com/20526831/65656708-a7ef0b80-dfd5-11e9-9450-513a514900fb.png)

**To Reproduce**
1. Have JEI installed
2. look up recipes for vanilla shield

**Meta Info**
 - TFC Version: 0.23.8.75
 - Were any other mods included? Can you reproduce it without these other mods?

JEI, JMap, WAILA

 - If necessary, what other mods (including versions) MUST be present to experience the bug?

JEI is the easiest way to check

**Comment by alcatrazEscapee** [comment]
TFC added recipe removed in 2502ea5968c07b8c0fa818eca70ba47bdfe0240f
