### ISSUE TITLE
Crash after opening small vessel GUI

### ISSUE THREAD

**Issue by Flaksmith** [TerraFirmaCraft/TerraFirmaCraft#466]
Opened up the vessel and was about to move stuff into it when the game suddenly froze and crashed. Using latest version # 76
[crash-2019-09-27_22.13.12-server.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/3664911/crash-2019-09-27_22.13.12-server.txt)

**Comment by Flaksmith** [comment]
After testing again it seems to be caused by me shift-clicking items into the vessel.

**Comment by alcatrazEscapee** [comment]
Seems to be a duplicate of #426
