### ISSUE TITLE
Soaked hides duplicate when placed.

### ISSUE THREAD

**Issue by Wayward24** [TerraFirmaCraft/TerraFirmaCraft#469]
**Describe the bug**
Soaked hides duplicate. Tested with different sizes of hide and on different logs.

**To Reproduce**
Right click a soaked hide on a log for scraping. Hide places but does not leave inventory.
New hide can be collected.

**Meta Info**
 - TFC Version: 0.24.1.78
 - Mods: Hwyla, Journey Map, JEI, Wawla, HarvestCraft, optifine
 - Not tested without other mods.

**Comment by DisasterMoo** [comment]
Missing `stack.shrink(1)` after this:
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/9f8ccdcf5dbdcfa34328a27176c3bf855eb21404/src/main/java/net/dries007/tfc/objects/items/ItemAnimalHide.java#L82
