### ISSUE TITLE
Name prefixes on wood, ceramics, metal and stone tool items is unneeded.

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#47]
Currently all metal items are named as such. `metal/[type]/[material]`
Wood follows the same name system but with `wood/` instead.
Stone tools are the same but with `stone/`.
Ceramics does the same by adding `ceramics/` but only to part of the ceramics. Molds don't have it.

Dropping these prefixes would shorten names as they add nothing of value to the names. Also nothing else follows this name system.

**Comment by Claycorp** [comment]
Thought I should note this here too.
Talked to Dries, This is done for the automation stuff and to separate out the JSON files. So instead of removing them everything should match it.

**Comment by alcatrazEscapee** [comment]
So what I'm hearing is:
 - Switch molds to `ceramics/mold/blah`
 - Remove `half` prefix from slabs
 - Keep everything else the same
?
