### ISSUE TITLE
Horses can't be tamed.

### ISSUE THREAD

**Issue by Wayward24** [TerraFirmaCraft/TerraFirmaCraft#470]
Describe the bug
Horses don't tame or eat. Also, http://prntscr.com/pdp369

To Reproduce
Try to tame a horse.

Meta Info

    TFC Version: 0.24.1.78
    Mods: Hwyla, Journey Map, JEI, Wawla, HarvestCraft, optifine
    Not tested without other mods.

**Comment by DisasterMoo** [comment]
You need to get it's familiarity to 30% first before trying to tame a horse.
