### ISSUE TITLE
Metal sheets have smithing skill bonus applied

### ISSUE THREAD

**Issue by DavidTriphon** [TerraFirmaCraft/TerraFirmaCraft#472]
**Describe the bug**
1. What did you expect to happen?

I didn't expect metal sheets to have a skill bonus applied. I expected to be able to stack my metal sheets.

2. What actually happened instead (i.e. what was the bug)

Metal sheets have a skill bonus, they cannot be stacked.

3. If it was a crash, upload the full log file (`latest.log`)

no crash.

4. If they would help to explain the issue, include screenshots

![2019-10-05_11 27 06](https://user-images.githubusercontent.com/20526831/66259211-1d3fa680-e763-11e9-8bc0-272afbc9519c.png)

**To Reproduce**
1. Heat up a double ingot to working temperature.
2. Use a capable anvil and hammer to smith the double ingot into a metal sheet.
3. Check the sheet for a skill bonus.

**Meta Info**
 - TFC Version: 0.24.3.80
 - Were any other mods included? Can you reproduce it without these other mods?

JEI, WAILA, JMap

 - If necessary, what other mods (including versions) MUST be present to experience the bug?

did not test

**Comment by alcatrazEscapee** [comment]
Fixed in 403513f887aa4e8e0c4c7688970d9970af85d833
