### ISSUE TITLE
Querns cannot be used if the handstone has taken durability damage.

### ISSUE THREAD

**Issue by DavidTriphon** [TerraFirmaCraft/TerraFirmaCraft#475]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?

I expected to be able to use the quern.

2. What actually happened instead (i.e. what was the bug)

If there was a handstone that had taken damage in the quern, it would not turn. Taking out the damaged handstone prevents me from re-inserting it. I can insert a new handstone and grind again, but only once per handstone.

3. If it was a crash, upload the full log file (`latest.log`)

no crash.

4. If they would help to explain the issue, include screenshots

**To Reproduce**
1. Place a quern.
2. Insert an item that is grindable like kaolinite or graphite.
3. Insert a new undamaged handstone.
4. shift right click on the handle to use the quern. Wait for it to finish.
5. The quern hitbox changes. It cannot be used a second time.
6. take out the handstone. It is damaged. Attempt to re-insert the damaged handstone. It will not work.
7. Insert a fresh handstone.
8. Use the quern again. It will work.

**Meta Info**
 - TFC Version: 0.24.3.80
 - Were any other mods included? Can you reproduce it without these other mods?

JEI, WAILA, JMap

 - If necessary, what other mods (including versions) MUST be present to experience the bug?

It was not tested if any of the before mentioned mods caused the bug.

**Comment by Flaksmith** [comment]
looks like there is no hitbox for it, based on my casual observation.

**Comment by alcatrazEscapee** [comment]
Nothing to do with the hitbox. The handstone item just doesn't match the ore dict name when damaged. It used to, but that got changed to try and avoid shotgunning items with `OreDictionary.WILDCARD_VALUE` metadata. (see #430)
