### ISSUE TITLE
Vanilla shears can be crafted using wrought iron sheets

### ISSUE THREAD

**Issue by DavidTriphon** [TerraFirmaCraft/TerraFirmaCraft#476]
**Describe the bug**
1. What did you expect to happen?

I didn't expect to be able to craft vanilla shears when there are already equivalent mod versions of shears.

2. What actually happened instead (i.e. what was the bug)

all mod shears can be crafted by welding two knife blades together. vanilla shears can be crafted using two wrought iron sheets. This appears inconsistent and to be a leftover crafting patch/bugfix.

3. If it was a crash, upload the full log file (`latest.log`)

no crash

4. If they would help to explain the issue, include screenshots

![2019-10-05_13 29 16](https://user-images.githubusercontent.com/20526831/66260490-26853f00-e774-11e9-8836-73b2ed9fa7dc.png)

**To Reproduce**
1. Open JEI
2. search shear
3. left click on vanilla shears
4. observe the crafting recipes available, which include using two wrought iron sheets.

**Meta Info**
 - TFC Version: 0.24.3.80
 - Were any other mods included? Can you reproduce it without these other mods?

JEI, WAILA, JMap. JEI is required for observing if the bug is fixed directly.

 - If necessary, what other mods (including versions) MUST be present to experience the bug?

It was not tested if the aforementioned bugs cause the issue.

**Comment by alcatrazEscapee** [comment]
todo:
 - [ ] Remove vanilla shears recipe
 - [ ] Remove the old TFC crafting recipe

**Comment by alcatrazEscapee** [comment]
Fixed in aa2dc303fc892b3a7d08940a849d8dac6a48286a
