### ISSUE TITLE
Can't scrape hides

### ISSUE THREAD

**Issue by Flaksmith** [TerraFirmaCraft/TerraFirmaCraft#478]
Build 80

Placed soaked hides on logs and tried to scrape them with my bismuth bronze knife, right clicking on the hides with the knife does nothing.

**Comment by alcatrazEscapee** [comment]
Two questions:
 - Does it work when the knife has no durability damage? and
 - If you enable advanced + debug tooltips, does the `toolKnife` ore dictionary name appear on the damaged knife.

If so, it's related to the fix for #430 and it is also fixed in my dev env at the moment.
