### ISSUE TITLE
Dirt blocks destroy charcoal - makes charcoal pits somewhat problematic

### ISSUE THREAD

**Issue by alcatrazEscapee** [TerraFirmaCraft/TerraFirmaCraft#479]
Since gravity blocks are now destroyers of anything not solid, they will break charcoal blocks that aren't solid (and potentially even full block ones?) this results in a very lossy charcoal pit, as charcoal piles broken this way only drop one charcoal.

Possible fixes:
 - make falling blocks special case charcoal somehow?
 - make charcoal transform without causing block updates?
 - make dirt that falls crush charcoal but drop the whole stack (instead of just 1, which is there to prevent cheeky digging of charcoal piles)

**Comment by Flaksmith** [comment]
For non solid charcoal blocks, would it be possible to make the dirt above it convert to "dirt sheets" that are just like the charcoal sheets and fill up the remaining */8s of the block? When you break them with a shovel it should give you nothing.
