### ISSUE TITLE
chest animation broken

### ISSUE THREAD

**Issue by Flaksmith** [TerraFirmaCraft/TerraFirmaCraft#480]
Build 80

When you open a chest and leave the gui open, after some time you'll hear the sound of the chest closing, and when you exit the gui the chest animation is stuck in the open position.

![2019-10-06_13 45 00](https://user-images.githubusercontent.com/46166245/66272063-8563ba80-e83f-11e9-8b9d-0d3dececde98.png)

**Comment by DavidTriphon** [comment]
I’ve also been experiencing this.

**Comment by Volkann1234** [comment]
I'm having that issue too
