### ISSUE TITLE
Breaking fruit tree branches with an axe does not drop saplings

### ISSUE THREAD

**Issue by Flaksmith** [TerraFirmaCraft/TerraFirmaCraft#482]
Build 80

Breaking branches with the saw still drops saplings, but the axe no longer does.

**Comment by alcatrazEscapee** [comment]
I can't reproduce. Have you actually tested this? They don't drop saplings every time.

**Comment by Flaksmith** [comment]
It seems to be affecting trees grown in older versions, loaded up a new world and everything was fine, on my old world saplings never dropped from any of the 50 trees in my orchard when using the axe (made a backup thankfully).
