### ISSUE TITLE
Ore gen currently incompatible with Worley's Caves

### ISSUE THREAD

**Issue by agilmore2** [TerraFirmaCraft/TerraFirmaCraft#484]
As detected in the crazy Wednesday fly-by-night modpack and in the latest TFC build, (83), ore clusters do not spawn when the Worley's Cave mod is also active. If the Railcraft mod is also on,  some chunks or chunk sized sections of the clusters spawn.

**To Reproduce**
1. Turn off all mods in Wednesday FBN modpack except TFC, Worley's and Railcraft
2. create new world using seed 'tfc' and enabled cheats
3. in creative mode, go to 410,160,216 (x,y,z), about 340 blocks towards the sun... 
4. /stripworld 35
5. View copper cluster holes

Screenshots of the issue with just TFC, TFC+Worley's, TFC+Worley's+Railcraft, and TFC+Worley's 1.5.1 are attached.

Just TFC:
![2019-10-09_21 14 08](https://user-images.githubusercontent.com/6852298/66539290-b6b0e480-eae4-11e9-93dd-d21a0a52e3a1.png)
TFC+Worley's+Railcraft:
![2019-10-09_22 13 19](https://user-images.githubusercontent.com/6852298/66539291-b6b0e480-eae4-11e9-99a2-8f92c6584acc.png)
TFC+Worley's:
![2019-10-09_22 21 17](https://user-images.githubusercontent.com/6852298/66539292-b6b0e480-eae4-11e9-89ce-cf87764b5b8c.png)
TFC+Worley's 1.5.1 (Look at that goodness!):
![2019-10-09_22 27 25](https://user-images.githubusercontent.com/6852298/66539293-b6b0e480-eae4-11e9-94a5-b5e9069d97d9.png)

**Meta Info**
 - TFC Version: 0.24.6.83 and previous
 - Worley's Caves 1.4.1 or 1.5.1
 - Railcraft 1.12.2-1.8.0

Recognizing that Oregen is on the 1.12 project todo list, I hope this is still a little helpful!

**Comment by alcatrazEscapee** [comment]
This was very helpful, thanks. I've been able to reproduce this, it seems to be the same cause as #361.
