### ISSUE TITLE
Skills resetting after death

### ISSUE THREAD

**Issue by TheMightyMcGrew** [TerraFirmaCraft/TerraFirmaCraft#491]
**Describe the bug**
Make sure to include:
1. Skill levels advancments to stay after death
2. All skill advancement and experience of skills reset after death

**To Reproduce**
Attention to detail is important!
1. Gain skill experience or level advancement in skills
2. Die and respawn

**Meta Info**
 - TerraFirmaCraft-MC1.12.2-0.24.6.83
 - Hwyla, JEI, Journeymap, theoneprobe
 - No other mods necessary

**Comment by agilmore2** [comment]
I just observed this in my SSP, build #86
