### ISSUE TITLE
When shift clicking items into an inventory, they will go to the first available slot even if a partial stack is present

### ISSUE THREAD

**Issue by Flaksmith** [TerraFirmaCraft/TerraFirmaCraft#492]
Build #85

Noticed this behavior when I was shift clicking seeds into a chest, in the attached image the squash seeds in my inventory went to the first empty slot instead of the stack already there.
![2019-10-13_21 53 06](https://user-images.githubusercontent.com/46166245/66724711-e4a76900-ee03-11e9-9c73-57fa0b8145ab.png)
![2019-10-13_21 53 24](https://user-images.githubusercontent.com/46166245/66724712-e96c1d00-ee03-11e9-9661-cafce5e78d93.png)

If the stack already inside the chest is moved to that empty spot, then the stacks will combine like normal when shift clicked.
![2019-10-13_21 55 18](https://user-images.githubusercontent.com/46166245/66724748-2d5f2200-ee04-11e9-84e1-4efe99b791aa.png)
![2019-10-13_21 55 23](https://user-images.githubusercontent.com/46166245/66724752-30f2a900-ee04-11e9-8f81-82e9bbc446f3.png)

**Comment by alcatrazEscapee** [comment]
Is this specific to TFC chests? or are there other inventories you've noticed this behavior with?

**Comment by Flaksmith** [comment]
I believe I've observed this behavior with the player inventory, but it's 100% confirmed with chests and I would imagine vessels too.
