### ISSUE TITLE
Barrels should function as fluid containers (via exposed capability) as items

### ISSUE THREAD

**Issue by Flaksmith** [TerraFirmaCraft/TerraFirmaCraft#493]
Always found it to be really useful especially if I want to use every last mb of limewater to process pelts, if you have a few barrels already part way empty you either have to make more barrels (not a problem, but next thing you know you've got like 50 of them on the go) or lose the contents in the ones you got.

**Comment by alcatrazEscapee** [comment]
Going to re-categorize this issue, as solving the larger problem (barrels as items aren't fluid containers) will automatically make this a feature (as they will just function as buckets)
