### ISSUE TITLE
Grain crafting doesn't produce extra straw

### ISSUE THREAD

**Issue by alcatrazEscapee** [TerraFirmaCraft/TerraFirmaCraft#497]
Knife + raw grains in the crafting grid should produce extra straw. Requires a separate crafting recipe type to produce extra output, similar to molds.

As of 0.25.2.86

**Comment by DisasterMoo** [comment]
Just a few concerns, if me or anyone wants to implement it:

- In 1.7, food didn't stack, so, a crafting recipe there would always craft 1 item -> 1 output + straw (quantity depending on oz) in the same slot. How to handle that in 1.12+, where user can partially craft the itemstack clicking in the output slot?
- In the same manner, but not that big of issue, knives took only one damage for the full 160 oz. Should we damage for each crafting operation and ignore the balancing?
- Also, another suggestion that can be implemented with this: Knives could remove decay from food by "cutting out" the rotten percent, again, measured by oz. Thoughts?

I say we should add a chopping board and treat it as a device (with TE and custom recipes) to handle all that, and possibly, use it in cooking system (salads, sandwiches).

**Comment by alcatrazEscapee** [comment]
* Straw was always dumped into your inventory - we need to handle that the same way we do empty molds returning from unmold recipes I'd imagine.
* Yes, damaging each crafting recipe makes more logical sense. I don't think it's a huge issue.
* This doesn't exist any more, since there's no meaning to "the rotten percent". Food has a finite expiration date.

I'd like to hold off on a full blown cooking implementation into after 1.0, since I don't think it's particularly important system, and it's going to have to drastically change from 1.7 anyway.
