### ISSUE TITLE
Hot Springs generate oddly and lack Hot water.

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#50]
~They are also all made of granite when in 1.7.10 I believe they only spawn with Rhyolite. Wiki has no info so I can't confirm it. Allowing a random Igneous rock to spawn would be a nice touch if possible.~ Seems to change already, oops.

![https://i.imgur.com/aN8zxzX.png](https://i.imgur.com/aN8zxzX.png)
![https://i.imgur.com/IYOzqkI.png](https://i.imgur.com/IYOzqkI.png)
![https://i.imgur.com/z6CKySs.png](https://i.imgur.com/z6CKySs.png)

Two fer one!
![https://i.imgur.com/FgDdTBf.jpg](https://i.imgur.com/FgDdTBf.jpg)

**Comment by alcatrazEscapee** [comment]
Fissures are able to spawn with non-hot water, i.e. lava or fresh water. However this is already noted in https://github.com/TerraFirmaCraft/TerraFirmaCraft/projects/2#card-17673269
