### ISSUE TITLE
TFC bucket cant be used to milk cows

### ISSUE THREAD

**Issue by Abdyman** [TerraFirmaCraft/TerraFirmaCraft#506]
1. What did you expect to happen? using a TFC bucket would work to milk TFC cows
2. What actually happened instead (i.e. what was the bug) TFC bucket are not recognized to and don't give any response from the animal, whether its male or female or milked or not
3. If it was a crash, upload the full log file (`latest.log`) no crash log

**To Reproduce**
Attention to detail is important!
1. Do '...' download build #86
2. Then do '...' g try to milk cow with high familiarity

**Meta Info**
 - TFC Version: build 86
 - Were any other mods included?  No other mods

**Comment by aldo1028** [comment]
happened to be looking at the code for this, in EntityCowTFC it only checks for Vanilla bucket in line 122
-  if (itemstack.getItem() == Items.BUCKET)
it doesn't do a check for woodenTFC bucket
