### ISSUE TITLE
Sheep can be sheared without any Familiarity

### ISSUE THREAD

**Issue by Abdyman** [TerraFirmaCraft/TerraFirmaCraft#507]
**Describe the bug**
Make sure to include:
1. What did you expect to happen? Sheep should have high familiarity before they can be sheared
2. What actually happened instead (i.e. what was the bug) can shear sheep at any time
3. If it was a crash, upload the full log file (`latest.log`) no

**Meta Info**
 - TFC Version: build 86
 - Were any other mods included? no

**Comment by TheMightyMcGrew** [comment]
can confirm in multiplayer server build #86
