### ISSUE TITLE
Charcoal pits use pitkiln time to burn.

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#509]
Currently Pit Kilns and Charcoal pits use the same burn time config value.
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/33d49e411a0eb8f48372910ea1c549fddf65148f/src/main/java/net/dries007/tfc/objects/te/TELogPile.java#L105
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/9dd48613b239b438d0d913d949c1d713d6057891/src/main/java/net/dries007/tfc/objects/te/TEPitKiln.java#L296

Charcoal pits should have their own value.

**Comment by alcatrazEscapee** [comment]
Fixed in 440a7d15bebfb8d8a294c0b6fb23684adeaa76c2
