### ISSUE TITLE
Config Reorganization

### ISSUE THREAD

**Issue by alcatrazEscapee** [TerraFirmaCraft/TerraFirmaCraft#515]
Current config setup is divided into three categories: General, World, and Client. The latter two are sufficient categories, however the General section is becoming quite large (which makes it difficult to scroll through for specific config options), and unorganized. We'd also like to open up a lot more things to be configurable, so ideally this would happen before the config gets too large. I'd propose a few separate categories:

 - General (for misc. config stuff that still fits here)
 - Balance (for balance related tweaks, changing numbers, etc.)
 - Mechanics (for enabling / disabling mechanics, or changing how the mod functions)
 - Packmakers (a section for options that are more technical, and basically only exist for pack makers. i.e. `crushingDamageSources`)

**Comment by Claycorp** [comment]
Dropping this here for future reference when I get around to doing this.
https://www.minecraftforge.net/forum/topic/58739-11121102-solved-config-categories-folders/
