### ISSUE TITLE
Stone and sand are Medium / Very Small rather than Heavy / Very Small

### ISSUE THREAD

**Issue by ferrolite** [TerraFirmaCraft/TerraFirmaCraft#519]
![2019-10-30_22 58 44](https://user-images.githubusercontent.com/53090564/67902882-7b955480-fb6a-11e9-98ce-e91de03809fc.png)

Thus they can stack up to 64 rather than 32 as expected.

This bug applies to every block in the "TFC Rock & Soil Blocks" tab.

(Although the screenshot is in creative mode, I first encountered this in survival.)

 - TFC Version: 0.25.3.87

**Comment by ferrolite** [comment]
Chests have the same problem, wrong weight. They should be Heavy.

**Comment by ferrolite** [comment]
![image](https://user-images.githubusercontent.com/53090564/68549756-13613100-03fc-11ea-8a33-462d0e8c65ad.png)

The problem persists in the newest version.

* TFC Version: 0.25.3.88

**Comment by alcatrazEscapee** [comment]
Yeah, it would, because it was not fixed, not does that version make any changes whatsoever. The changelog even says "No changes"...
