### ISSUE TITLE
Ore gen reads default config file but doesn't copy to /config/tfc/

### ISSUE THREAD

**Issue by JonJonsonsSon** [TerraFirmaCraft/TerraFirmaCraft#52]
https://pastebin.com/c16auYWr
Playing around with alpha builds of TFC since September of last year without seeing any ore all this time seems to confirm that ores aren't spawning. I thought they simply weren't implemented yet, but after noticing those error messages in the console, maybe they are implemented, but not quite properly? I'm really not sure

**Comment by Claycorp** [comment]
What version are you using?
They certainly do spawn in my dev environment and its a fresh copy from last night.
![https://i.imgur.com/906YRHH.jpg](https://i.imgur.com/906YRHH.jpg)

**Comment by JonJonsonsSon** [comment]
v0.2.1.35. I've also used WorldEdit to remove a lot of stone blocks on several occasions, the most recent being a few minutes ago, and still haven't seen any ores before:
https://i.imgur.com/64lOo5I.jpg
https://i.imgur.com/htUbQKq.jpg
If it helps, here's a latest.txt log file: https://pastebin.com/q3FrRTb8

**Comment by Claycorp** [comment]
Can you repeat the issue without all the extra mods?

**Comment by alcatrazEscapee** [comment]
Those console warnings mean your json ore configuration is bad. Try deleting the ore gen json and reloading TFC. If the default config is bad, that is a separate issue.

**Comment by JonJonsonsSon** [comment]
After deleting that file from last September and generating a new world, ores are spawning now! Unfortunately WAILA no longer informs me of what I'm looking at it, including vanilla blocks 🤔 This is probably unrelated
Oh, and no new oregen file was generated in place of the one I deleted. Is that a problem, or is that fine?

**Comment by alcatrazEscapee** [comment]
That is a different bug. It seems if a config file isn't found, it just reads the default one instead of creating a default one.
