### ISSUE TITLE
HWYLA and VanillaFix causing spam in crash reports when looking at large vessel

### ISSUE THREAD

**Issue by Aiva418** [TerraFirmaCraft/TerraFirmaCraft#520]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
2. What actually happened instead (i.e. what was the bug)
3. If it was a crash, upload the full log file (`latest.log`)
4. If they would help to explain the issue, include screenshots

I placed and used a large vessel. That's what I expected to happen. What I didn't expect to happen was a spam of toasts and crash logs from VanillaFix telling me that HWYLA has encountered a problem. These reports quickly take up a lot of space, and there doesn't seem to be a way to disabling them. I can't tell which mod is directly causing the issue, but it only seems to happen when looking at the large vessel from TFC, so I'm putting it here.

Crash Report: https://hastebin.com/utecewenox.rb
Log File: too large to upload due to spam

**To Reproduce**
Attention to detail is important!
1. Install the latest versions of TerraFirmaCraft, HWYLA, and VanillaFix.
2. Open any world.
3. Place and look at a large vessel and watch as you get a steady stream of toasts and like 65 crash reports.

**Meta Info**
 - TFC Version: 0.25.3.87
 - VanillaFix Version: 1.0.10-99
 - HWYLA Version: 1.8.26-B41_1.12.2
 VanillaFix and HWYLA are required for this to be replicated.

**Comment by alcatrazEscapee** [comment]
Offending method call seems to be here: https://github.com/TehNut/HWYLA/blob/1.12/src/main/java/mcp/mobius/waila/addons/capability/HUDHandlerTank.java#L61 May be something messed up with the large vessel's tank properties.

**Comment by DisasterMoo** [comment]
Let me get this right: You don't want to expose the fluid handler (via any side), only internally? The expected behaviour is fluids can only be inputted via GUI?

**Comment by alcatrazEscapee** [comment]
The large vessel doesn't have any form of fluid handling - that got added and then removed during development. It's only an inventory, and as such should not expose any form of fluid handler.
