### ISSUE TITLE
Water Jugs stack when full, can't be filled from vanilla cauldron

### ISSUE THREAD

**Issue by agilmore2** [TerraFirmaCraft/TerraFirmaCraft#522]
When water jugs are full, they stack back into "jug", and can be split back out individually.

I would think that you could fill a jug from a full vanilla cauldron, but that doesn't work, maybe because it's an all or nothing full thing?

**Meta Info**
 - TFC Version: 0.25.3 build 87
 - seen last with several other mods, but unnecessary to reproduce.

**Comment by alcatrazEscapee** [comment]
Stack-ability has been fixed. The vanilla cauldron is not a general purpose fluid container (as much as it acts like one, and as it's basically never going to be necessary in base TFC, I don't really see a need to replace it.
