### ISSUE TITLE
Filling water jugs also right-clicks with off-hand

### ISSUE THREAD

**Issue by agilmore2** [TerraFirmaCraft/TerraFirmaCraft#523]
Filling a water jug with a stack of torches in your off-hand results in placing a torch too.

**Meta Info**
 - TFC Version: 0.25.3 build 87
 - several other mods, not needed to reproduce

**Comment by UnlimatedStone9** [comment]
If I might add to this, this also allows you to bucket things like water using wooden buckets in either hand, essentially doubling the fluid.
