### ISSUE TITLE
unfired large vessels are heavy/huge, in classic they were heavy/large

### ISSUE THREAD

**Issue by agilmore2** [TerraFirmaCraft/TerraFirmaCraft#533]
Unfired large vessels are heavy/huge, while fired vessels are Medium/Huge. 

In Classic, they were both heavy/large.

This results in gaining the massive debuff when carrying more than one unfired large vessel:
![2019-11-13_00 33 06](https://user-images.githubusercontent.com/6852298/68742638-e5235300-05ad-11ea-9cc6-5ed93103383d.png)

I understand sealed large vessels having this impact, but I didn't think it was intended that unfired large vessels have the same impact?

**Meta Info**
 - TFC Version: 0.25.3 build 87

**Comment by alcatrazEscapee** [comment]
The resolution in this case is actually to make them Huge / Medium:
 - It matches the current large vessel (which becomes huge / medium, or huge/heavy if sealed)
 - Huge means it can be placed in the pit kiln as a single item, rather than four.
