### ISSUE TITLE
Allow anvils to accept ore:dustFlux instead of specifically being TFC flux.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#534]
Currently only ore:hammer is allowed to be used with TFC anvils, and while that's fine for compatibility, if any other mod adds ore:dustFlux to one of their items, it can't be used as a flux.
I suggest having anvils require an ore dictionary entry rather than just TFC flux.

**Comment by alcatrazEscapee** [comment]
This is already the case.
![this already works](https://user-images.githubusercontent.com/35673674/68781463-d49ec700-0605-11ea-95ea-b6e0a9e14980.PNG)

**Comment by UnlimatedStone9** [comment]
Oh, odd. Must've overlooked it then. Thanks Alc!
