### ISSUE TITLE
Suggestion: Ability to add other molten metal types to Crucibles using CraftTweaker

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#536]
It would be incredibly useful if you could add other types of "molten metal" using CraftTweaker.
Like having the ability to set Molten Neodymium as a metal, what it's melting temperature is and then be able to configure what melts into it, so we're not limited by only the default entries.

**Comment by alcatrazEscapee** [comment]
No. This has already been said - It isn't possible without a hell of config based block, item, and fluid registration, which we are not willing to do in base TFC. If you need to add non-TFC metals to work with everything in TFC, then you need an addon to register the metal, and TFC will be able to handle the relevant registrations.
