### ISSUE TITLE
Metal can melt into the crucible when the crucible is full, deleting the metal item.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#537]
**Describe the bug**

Heating an item to the point of melting, in a crucible that is full of molten metal, will melt said items and essentially delete any metal you would've recieved, instead of keeping the molten items in the crucible.

**To Reproduce**
Fill the crucible entirely with molten metal. Try to melt more metal, watch it get deleted.

**Meta Info**
 - TFC Version: 1.12.2-0.25.2.86

**Comment by alcatrazEscapee** [comment]
While I can see this being a pain, this is realistic. It makes no sense to let an item be "liquid" while it's still in item form, neither does it to prevent the item from melting.
