### ISSUE TITLE
TFC makes enderIO a sagmill recipe that exceeds max output

### ISSUE THREAD

**Issue by Archilyte** [TerraFirmaCraft/TerraFirmaCraft#538]
Latest version of EnderIO and TFC as of this writing
[New Text Document.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/3856191/New.Text.Document.txt)
Thats the log (wasnt a crash so couldnt seperate)
i think tfc is trying to make enderio sagmill turn octuple compressed cobble into the cobble it is equivalent to

**Comment by Archilyte** [comment]
latest version of forge as of this writing as well

**Comment by tyler489** [comment]
This is actually caused by 4x compressed cobble and it occurs because terrafirmacraft has a smaller than 64 stack size

**Comment by alcatrazEscapee** [comment]
In which case, there is a fix: Use craft tweaker to change the item stack size (by setting the size / weight) back to 64. TFC tries to make it's best guess about what to change stack sizes to, and for the most part it's accurate, but it's inevitable that something will get messed up.

[Craft Tweaker Docs](https://github.com/TerraFirmaCraft/TerraFirmaCraft/wiki/ItemRegistry)

**Comment by tyler489** [comment]
Alternatively blacklisting/disabling that recipy on enderio end would also work

**Comment by Archilyte** [comment]
ok thanls
