### ISSUE TITLE
config option to not make TFC change max stacksize of items

### ISSUE THREAD

**Issue by Archilyte** [TerraFirmaCraft/TerraFirmaCraft#539]
Pls
i have been getting way too many crashes/ errors
i have too many conflicting recipes
i just want a config that reverts all stack size to what it would have been normally

**Comment by alcatrazEscapee** [comment]
What *specifically* is the issue with other mods? Most recipes should be independent of stack size, and those that are can be configured via craft tweaker to give it a new item size.

TFC makes a lot of assumptions about item stack sizes, disabling that would potentially break a lot of assumptions TFC makes, hence I'm not inclined to add said config feature. Is there potentially another issue here that could be solved?

**Comment by Archilyte** [comment]
alright, it seems that only enderio machines has this problem. right now i fixed it by dividing the output to respect the stack size limit as much as possible.

**Comment by alcatrazEscapee** [comment]
That seems like a fix then.
