### ISSUE TITLE
Fire pits: 2 bugs

### ISSUE THREAD

**Issue by JonJonsonsSon** [TerraFirmaCraft/TerraFirmaCraft#54]
1: They only consume 1 log, then stop consuming logs after that point
2: They burn forever at a temperature of Bright Red
https://i.imgur.com/c9W2018.png
(The temperature in the picture is orange+ due to using bellows)

**Comment by alcatrazEscapee** [comment]
They are working fine in my dev env. Logs take 50 sec (depends on the log) to be consumed. They burn at different temperatures dependent on the log type.

**Comment by alcatrazEscapee** [comment]
Should be fixed by v0.5.0.38, see #76.
