### ISSUE TITLE
Not a bug

### ISSUE THREAD

**Issue by Komplein** [TerraFirmaCraft/TerraFirmaCraft#541]
Is this any chance to see nutrition compatibiluty feature with other food mods? (Like Cuisine, Pam's HC and other). And also vanilla block compatibility (by craft) for use TFC with other global mods without craft tweaker recipe spaming?

**Comment by DisasterMoo** [comment]
Sorry, I poorly fixed the last issue. Looks like what needs to be done here: https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/44acc0182845206ca38d5e4a51a7e38c686475dc/src/main/java/net/dries007/tfc/objects/items/ceramics/ItemSmallVessel.java#L414
should be:
```java
IItemSize cap = CapabilityItemSize.getIItemSize(stack)
if(cap != null)
{
    ...
}
```
@alcatrazEscapee

**Comment by alcatrazEscapee** [comment]
We are not going to special case other mod's food. The relevant craft tweaker scripts, or an addon mod, can be made and used. Maintaining compatibility with arbitrary mods is beyond the scope of TFC.

As it is, everything can be configured without the use of an addon as all the craft tweaker hooks are provided.
