### ISSUE TITLE
Crucible metal loss indicators

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#542]
Since metal isn't going to be prevented from melting in a crucible when it's full, might I suggest some visual indicators? For example, a tool tip on the item, when the crucible is full, stating it's metal will be lost, bubbling smoke particles on top of the crucible before and as the metal melts? To indicate that your extra metal is burning away.

**Comment by alcatrazEscapee** [comment]
There already is:
 - A tooltip on the item indicating how many units of what metal it will melt into
 - A visual display of the metal content in the crucible in world (the fluid in the crucible) that will fill up as your crucible fills
 - An exact number of units and fill meter inside of the crucible itself, stating how many units it contains

What more do you want?

**Comment by UnlimatedStone9** [comment]
Okay, fair point. However I've never found that the fluid display was very clear, it blends into the GUI too much. If that's not to change though a possibility is this.
Adding the fire extinguishing sound (sizzling) when your metal melts away, and smoke particles above the crucible to show said metal will be lost, surely that's more clear to a person if they leave the GUI without realizing.

**Comment by alcatrazEscapee** [comment]
Superseded by #620
