### ISSUE TITLE
Can't cook raw wolf meat and raw rabbit meat

### ISSUE THREAD

**Issue by ferrolite** [TerraFirmaCraft/TerraFirmaCraft#545]
![image](https://user-images.githubusercontent.com/53090564/69100846-63746f00-0a5e-11ea-95ef-15f1e5657674.png)

I can cook the meats on the left just fine,. The meats on the right cannot be cooked. 😕 

- TFC Version: 0.26.3.93

**Comment by alcatrazEscapee** [comment]
It seems the issue is not that the recipe doesn't exist, but the foods aren't getting marked as heatable, thus not allowing them to be placed in the fire pit.
