### ISSUE TITLE
Barrels open state toggle-able via redstone.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#555]
I think it would be a very good idea to allow barrels to be opened or closed depending on a redstone signal input, this would make barrel automation 100% given the player can already pipe items and fluids into barrels, which they can.
Currently barrels can only be semi automated because the player has to manually open or close the barrels.

**Comment by alcatrazEscapee** [comment]
Any mod that has a right click simulator *should* be able to open + close barrels, as they can be toggled by shift + right clicking.

That said, redstone is a more vanilla friendly and more intuitive method of automation and makes more sense for this situation.
