### ISSUE TITLE
Comparators cannot detect barrel item or fluid values.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#556]
That's it really, comparators don't light up when a barrel has either items or a fluid in it, this isn't necessary but it would be a nice addition.

**Comment by Therighthon** [comment]
Probably fluid values would make the most sense for them to track, since that is what is more likely to change without user input.

**Comment by UnlimatedStone9** [comment]
Fluid values would be ideal yes, you can count items using other methods and detect them using other storage containers, so fluid makes sense.

**Comment by alcatrazEscapee** [comment]
Alternatively, in line with #555, it may make sense to have the barrel output a comparator signal if it is sealed. Other mods should be able to read / check item contents or fluid contents through clever automation.
