### ISSUE TITLE
Stone Anvil has no bottom texture.

### ISSUE THREAD

**Issue by Volkann1234** [TerraFirmaCraft/TerraFirmaCraft#557]
Stone Anvil has no bottom texture
I can see through it.

Version: TerraFirmaCraft-MC1.12.2-0.26.4.94
Screenshot:
![xD](https://user-images.githubusercontent.com/54782754/69182171-86b42280-0b21-11ea-8f17-5197d400bd96.png)

**Comment by alcatrazEscapee** [comment]
This is a  separate issue from #559, it should stay a separate issue.
