### ISSUE TITLE
Ore spawn bugged in build 95

### ISSUE THREAD

**Issue by BigE1293** [TerraFirmaCraft/TerraFirmaCraft#558]
**Describe the bug**
Make sure to include:
1. What did you expect to happen? 
2. What actually happened instead (i.e. what was the bug): No ore nuggets are spawning in this build, as well as ore
![0-26-X-XX_messed_something_up](https://user-images.githubusercontent.com/57960280/69183640-564c9400-0ae1-11ea-94d1-d3ed41f32828.png)

3. If it was a crash, upload the full log file (`latest.log`)
4. If they would help to explain the issue, include screenshots

**To Reproduce**
Attention to detail is important!
1. Do 'create a new world'
2. Then do 'look around for ore nuggets, non existant'

**Meta Info**
 - TFC Version: 0.26.4.95
 - Were any other mods included? Can you reproduce it without these other mods? (journey map was the only other mod, besides that no)
 - If necessary, what other mods (including versions) MUST be present to experience the bug?

**Comment by alcatrazEscapee** [comment]
Delete `config/tfc/ore_spawn_data.json`, as there was a config change in v89 that resulted in breaking old config files. If that doesn't resolve the issue then I'll reopen this.
