### ISSUE TITLE
Stone anvils have reduced hardness compared to stone blocks

### ISSUE THREAD

**Issue by Volkann1234** [TerraFirmaCraft/TerraFirmaCraft#559]
1. What did you expect to happen?
I expected to mine stone anvils slow just like other rocks...

2. What actually happened instead (i.e. what was the bug)
I can transform stones to stone anvils with hammer and break them to make the mining process easier.
Also, stone anvil has no bottom texture.

**Meta Info**
 - TFC Version: 0.26.4.94
 - Were any other mods included? Can you reproduce it without these other mods?
No other mods.

Video:
https://youtu.be/Yjwuql2dN7w

Screenshot about no bottom texture

![xD](https://user-images.githubusercontent.com/54782754/69184106-4060c280-0b25-11ea-8d68-b2bdf9a76243.png)

**Comment by alcatrazEscapee** [comment]
The formation of stone anvils without an air block on top is #532. This is just likely the separate hardness, which is leftover from when we increased hardness on ores + rocks to match classic.

**Comment by agilmore2** [comment]
In classic, anvils were easier to break than raw stone too. Making an anvil also doesn't damage the hammer.
