### ISSUE TITLE
Completed mold usage

### ISSUE THREAD

**Issue by JonJonsonsSon** [TerraFirmaCraft/TerraFirmaCraft#56]
If you hold a ceramic mold that's filled with copper, whether it's an ingot mold or a tool mold, then right click, you won't receive the ingot/tool head, but there is a little up & down bobbing animation that signifies something tried to happen when you used it
https://i.imgur.com/c8kqScY.png

**Comment by alcatrazEscapee** [comment]
This isn't an issue. Two things are happening:
1) To get the tool head you have to craft it in a crafting grid, as per 1.7 mechanics
2) If the mold is molten, you can right click it to open the pouring GUI, to transfer metal between containers
