### ISSUE TITLE
Grass path block not supporting other blocks nearby

### ISSUE THREAD

**Issue by Volkann1234** [TerraFirmaCraft/TerraFirmaCraft#564]
**Describe the bug**
1. What did you expect to happen?
I right clicked to a grass block while holding a shovel to make grass path.

2. What actually happened instead (i.e. what was the bug)
Other grass and dirt blocks near me just fall,
because grass path block not supporting other blocks nearby.

**To Reproduce**
1. Right click to a grass block with shovel on a hillside.

**Meta Info**
 - TFC Version: 0.26.4.94
 - No other mods

Screenshots:
![2019-11-20_18 45 54](https://user-images.githubusercontent.com/54782754/69264573-a0647100-0bd8-11ea-829b-91fcd37e86ca.png)

![2019-11-20_18 45 56](https://user-images.githubusercontent.com/54782754/69264585-a65a5200-0bd8-11ea-96ed-22ae65faf2e7.png)

**Comment by alcatrazEscapee** [comment]
This is consistent with current behavior - valid "side support" blocks must be full, solid blocks.
