### ISSUE TITLE
Update Version 94 | Food Decay with JEI

### ISSUE THREAD

**Issue by liquidblur** [TerraFirmaCraft/TerraFirmaCraft#565]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
food not to be expired
2. What actually happened instead (i.e. what was the bug)
food expired
3. If it was a crash, upload the full log file (`latest.log`)
NA
4. If they would help to explain the issue, include screenshots
https://gyazo.com/9eb86ab15c03236c18e9ce848af8e2f0 update 94 does this to food in JEI going back to 93 causes it to revert to food showing in JEI as not expired/spoiled
**To Reproduce**
Attention to detail is important!
1. Do '...'
install 94 update
2. Then do '...'
look in JEI

**Meta Info**
 - TFC Version: 0.26.4.94
 - Were any other mods included? Can you reproduce it without these other mods?
yes/yes
 - If necessary, what other mods (including versions) MUST be present to experience the bug?

**Comment by alcatrazEscapee** [comment]
Seeing as the change in build 94 that made this happen was switching from "on client, everything is un-decayable" to "client now receives data from server about decay", we are not reverting that particular fix. Rather, see #458, as it's the same root issue.
