### ISSUE TITLE
Raw stone blocks drop + pick block copy metadata

### ISSUE THREAD

**Issue by reddler97** [TerraFirmaCraft/TerraFirmaCraft#566]
lava and water will form Basalt or Rhyolite with metadata 1 instead of 0(discovered through craftTweakers command "/ct hand"). this causes each variant to float(not fall off when not supported. which isn't conducive to harvesting from automation machines) and do not have textures for the rocks they drop as well as not having textures when middle-clicked in creative

![2019-11-21_19 38 07](https://user-images.githubusercontent.com/8678826/69391033-1deeb680-0c97-11ea-82af-59589227cfd9.png)
 
I think it might be related to the fix used in #457

**Comment by alcatrazEscapee** [comment]
Yes, that is exactly the fix. The not-popping off is intentional, as otherwise it creates infinite stone machines that have the potential to generate naturally in the world: not good.

The drop + pick block can be fixed - they should drop normal raw stone.
