### ISSUE TITLE
Torches not created in firepit with LiteLoader

### ISSUE THREAD

**Issue by KWik** [TerraFirmaCraft/TerraFirmaCraft#567]
**Torches are not generated in the hot firepit when LiteLoader is installed**

1. When adding sticks to the hot, burning firepit, I expected the sticks to turn into torches.
2. Instead, the output is empty. This was attempted with 32 sticks or more.
4. I did record this behavior with OBS, so just toss me a DM in Discord and Ill reply with the video.

**To Reproduce**
Attention to detail is important!
1. Do make a fresh firepit.
2. Then do add a log, and heat until mid temperature, just to be on the safe side.
3. Add sticks. See them disappear.
4. Remove LiteLoader (quit, remove, restart)
5. Add sticks, see them burn.
6. Reinstall LiteLoader 1.12.2-SNAPSHOT (quit, add, restart)
7. See the sticks disappear.

**Meta Info**
 - TFC Version: 0.26.4.94
 - Minecraft Coder pack9.42
 - Forge Mod loader 8.0.99.99
 - Minecraft Forge 14.23.5.2847
 - JEI 4.15.0.291
 - Journeymap 1.12.2-5.5.3
 - LiteLoader 1.12.2-SNAPSHOT
 - TheOneProbe 1.12-1.4.28
 - TOPAddons 1.12.2-1.12.0

Ran in MultiMC. tested both with and without the extra mods. Only LiteLoader interferred.

Obvious fix: Don't use LiteLoader :)

**Comment by alcatrazEscapee** [comment]
Unless this is something that someone from LiteLoader can point out what we would need to change, then this is not going to get looked at.

> Obvious fix: Don't use LiteLoader :)

Unfortunately, yes.
