### ISSUE TITLE
Keeping Entity spam in console.

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#569]
Another issue skeleton issue for debugging....
Could be tied to #568 or #547 

Currently starting the test server results in 158 lines of `[23:11:32] [Server thread/WARN] [net.minecraft.world.WorldServer]: Keeping entity tfc:pigtfc that already exists with UUID ba103e3b-e40b-4047-8f7a-0ef9da81a80a`
Of all the TFC animals I would assume that are spawn loaded. but then it will also do this to any animals that are then loaded out of memory in other chunks once they get loaded.

**Comment by alcatrazEscapee** [comment]
Both linked issues have been fixed (in some sense). Animals have gone quite large refactors to the point where the original issue is probably moot. If not, let's look into it.
