### ISSUE TITLE
Snowfall causes Bloomery Hatch to be destroyed

### ISSUE THREAD

**Issue by ianthina** [TerraFirmaCraft/TerraFirmaCraft#570]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
I expected the Bloomery Hatch to remain attached to its structure.
2. What actually happened instead (i.e. what was the bug)
A layer of snow appeared in the cavity of the empty bloomery, and the bloomery hatch dropped as an item on the ground.
3. If it was a crash, upload the full log file (`latest.log`)
4. If they would help to explain the issue, include screenshots

**To Reproduce**
Attention to detail is important!
1. Do '...'
Create a valid bloomery, keep it empty of ore.
2. Then do '...'
Wait for snowfall to place a layer in it.

**Meta Info**
 - TFC Version: 0.26.4.94
 - Were any other mods included? Can you reproduce it without these other mods?
No, vanilla TFC
 - If necessary, what other mods (including versions) MUST be present to experience the bug?

**Comment by p0kes** [comment]
Just saw this happen with snowfall onto a 8 charcoal stack behind the bloomery. v98 test server.
