### ISSUE TITLE
daylight game rule isn't ever enabled. Build 95

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#572]
Looks like you did one of the ol fantastic Copy, Pasta and forget to edit.

https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/10eb2f5d562d48ab85dfb485427cc1efad530569/src/main/java/net/dries007/tfc/CommonEventHandler.java#L415-L419

This is part of the playerJoin event and should be setting/checking and setting the dalyight gamerule to true instead of false. The code seems to be a direct copy paste of the code from the playerLogOut event

https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/10eb2f5d562d48ab85dfb485427cc1efad530569/src/main/java/net/dries007/tfc/CommonEventHandler.java#L438-L442

Oops!

**Comment by alcatrazEscapee** [comment]
idk how I ever thought that was going to work 🤦‍♂
