### ISSUE TITLE
FirePit

### ISSUE THREAD

**Issue by PacoMods** [TerraFirmaCraft/TerraFirmaCraft#573]
**Describe the bug**
When trying to create a fire pit a fire block is spawned but no fire pit.

**To Reproduce**
Attention to detail is important!
1. Do 'throw 3 sticks on same block'
2. Then do 'right click fire starter on same blocks sticks sit'

**Meta Info**
 - TFC Version: 0.26.4.95
 - Without any other mods

**Comment by alcatrazEscapee** [comment]
You need a log in addition to the normal sticks, see <https://tng.terrafirmacraft.com/Differences_From_Classic>
