### ISSUE TITLE
Frigid water

### ISSUE THREAD

**Issue by JonJonsonsSon** [TerraFirmaCraft/TerraFirmaCraft#574]
Lava and cacti present a threat in hot regions, but what about cold regions? It would be interesting if a new type of water - frigid - spawned in cold regions and had some adverse effect(s) on players. Potential effects include damage over time, slowness, and faster oxygen deprivation when submerged.
Or, rather than a new block being created, this effect/these effects were applied to players in any body of water at or below a certain temperature threshold.

 - TFC Version: 0.26.4.95 (at time of writing).
 - This would be an enhancement for TFC alone.

**Comment by alcatrazEscapee** [comment]
From the enhancement issue template, this is better suited to discord discussion.
> Suggest an enhancement or small new feature. This is NOT for new mechanics, those should be discussed in our discord.
