### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by eagleyes005** [TerraFirmaCraft/TerraFirmaCraft#575]
1. What did you expect to happen?
Start the game

2. What actually happened instead (i.e. what was the bug)
CTD

3. If it was a crash, upload the full log file
[crash-2019-11-23_09.35.12-client.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/3882429/crash-2019-11-23_09.35.12-client.txt)

**Meta Info**
 - TFC Version: 0.26.4.95
 - Other mods included (you can see in the crash report)

**Comment by eagleyes005** [comment]
I forgot to mention that in TFC version 0.26.1.91 with the same other mods this crash did not occur.

**Comment by alcatrazEscapee** [comment]
Your addons need to be updated for the new version
