### ISSUE TITLE
Add replacement recipe for vanilla lead as replacement for Classic rope.

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#576]
Jute has no use. As slimes may not spawn in TFC worlds(?), we should add a recipe for vanilla leads using jute fiber. What should we use instead of the slimeball?

**Comment by Gaelmare** [comment]
burlap carpet? burlap instead of large hide for straw bed?

**Comment by Claycorp** [comment]
This would something that need to be discussed in the discord, It's not a bug.
Also Jute does have a use, It makes burlap.

**Comment by Gaelmare** [comment]
True. Wanted to get this issue recorded somewhere.

**Comment by Gaelmare** [comment]
Per discussion today, should recreate classic recipe for rope with 5 jute fiber to vanilla lead. Should not use string oredict, so leads cannot be made with 5 string.
