### ISSUE TITLE
Obsidian can be made when lava meet water.

### ISSUE THREAD

**Issue by hidfug** [TerraFirmaCraft/TerraFirmaCraft#578]
Obsidian can be made when lava meet water.
**Meta Info**
 - TFC Version: 0.26.4.95

**Comment by alcatrazEscapee** [comment]
This is a vanilla mechanic we have no intention of changing

**Comment by hidfug** [comment]
Then players can enter the nether. @alcatrazEscapee

**Comment by flarn2006** [comment]
...Yeah? What's wrong with that?
