### ISSUE TITLE
Mapping "place item" (default: V)  to a mouse button doesn't work.

### ISSUE THREAD

**Issue by AtomicBlastPony** [TerraFirmaCraft/TerraFirmaCraft#579]
**Describe the bug**
1. What did you expect to happen?
"Place item holder block" key to work when mapped to mouse1, mouse2, mouse3, mouse4 or mouse5 like any other action (all Vanilla keys work fine)
2. What actually happened instead (i.e. what was the bug)
After mapping the key to mouse4 and pressing it, I didn't get consistent results. The item was only placed about 1 in 4 attempts and there was a long delay. Mapping it to mouse2 didn't work either. Jumping and opening inventory works fine with mouse4.

**To Reproduce**
Map the "Place item holder block" action to any mouse button and attempt to use it.

**Meta Info**
 - TFC Version: 0.26.4.94
 - Were any other mods included? Can you reproduce it without these other mods?
InventoryTweaks, JEI, TellMe, and Vivecraft (non-VR mode at the time), none of which should affect the mouse.

**Comment by alcatrazEscapee** [comment]
Fixed in bc1880d3a44fb99c4cf223d4bb0c032251ca301c
