### ISSUE TITLE
Tools are displayed as regular items in hand in VR

### ISSUE THREAD

**Issue by AtomicBlastPony** [TerraFirmaCraft/TerraFirmaCraft#580]
Tools and weapons like swords, shovels, etc are considered to be normal items like string or sticks by Vivecraft and thus they appear small and facing the player when held in hand, probably because they don't use the vanilla definition of tools. The only tools that are rendered properly are the hoe and the prospector's pickaxe.
Javelins are recognized as bows and appear in the left hand with an arrow in the right.

**Meta Info**
 - TFC Version: 0.X.X.XX (at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
 - If necessary, what other mods (including versions) would this require?
Vivecraft Forge for 1.12.2

**Comment by alcatrazEscapee** [comment]
> probably because they don't use the vanilla definition of tools.

and

> The only tools that are rendered properly are the hoe and the prospector's pickaxe.

seem to be in quite direct contradiction, because hoes and prospectors picks also don't use vanilla tool classes. They also use identical `item/handheld` models so unless someone can tell me what's actually wrong with our tool items I'm out of ideas.

**Comment by alcatrazEscapee** [comment]
This issue does not apply, or has been fixed in the current MC 1.18 versions of TFC, and as MC 1.12 is receiving no more development, it will be closed. If this issue arises again in 1.18, please file a new issue report.
