### ISSUE TITLE
Custom food values

### ISSUE THREAD

**Issue by Ravin890** [TerraFirmaCraft/TerraFirmaCraft#582]
1. What problem or issue would this enhancement solve?
If a mod adds in any food item it allows the player to add custom values for them as opposed to having a default value to have the item not randomly tossed into a category.
2. Describe the feature itself - what would change, what would happen. In general more detail is good!
It would allow for more items to be added into tfc if modpack makers wanted to without having to bother you guys or other mod devs to add in the values for when tfc is found in the pack. 

**Meta Info**
 - TFC Version: 0.26.6.97
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
Technically other mods

Though I know the food value system might not be completed yet it may also reduce the time to back track and rewrite anything if this could be implemented.

**Comment by alcatrazEscapee** [comment]
This is already configurable via craft tweaker, see https://github.com/TerraFirmaCraft/TerraFirmaCraft/wiki/ItemRegistry
