### ISSUE TITLE
Improper day-night circle

### ISSUE THREAD

**Issue by HeartyYF** [TerraFirmaCraft/TerraFirmaCraft#583]
**Describe the bug**
![2019-11-25_21 55 41](https://user-images.githubusercontent.com/17660052/69546251-5ca1ab00-0fce-11ea-87a6-3edb3cc230ff.png)
You can see from debug info that it's 0935 in July now. it should be daytime but I can't see sun, only moon.

**To Reproduce**
Start a new world and play for about 2hr.

Besides, using `/timetfc set day` doesn't flush day to night.

**Meta Info**
 - TFC Version: 0.26.6.97

**Comment by alcatrazEscapee** [comment]
When specifically did this problem occur? Did the time slowly drift backwards or forwards? Did it occur after a login or logout? Are you on multiplayer or singleplayer?

You're command syntax is incorrect - day is not a value, it's a unit. Try `/timetfc add ticks 1` and see if that fixes the calendar.

**Comment by HeartyYF** [comment]
Both multiplayer and single player this can happen. Time didn’t slowly drift backwards or forwards, instead it runs steadily. Just clocktime and daylight doesn’t match.
About the command: I mean using `/timetfc set day` with any number (like /timetfc set day 2 or etc.) set time to 00:00 without changing daylight.

**Comment by alcatrazEscapee** [comment]
So when did the calendar issue happen? When you ran `/timetfc set day X`? (Note: this command does not, or at least should not, modify the time whatsoever. It should only affect the calendar, as in the day/month/year unless you use `/timetfc set ticks`)

**Comment by HeartyYF** [comment]
1. The issue can occur without any command used. As time goes by in game, it automatically happen.
2. Using the command can also trigger the issue, but I'm not sure whether it has the same cause as 1. Using the command not only affect the calendar, but also set time to 00:00.
