### ISSUE TITLE
Raw grain bunches are consumable

### ISSUE THREAD

**Issue by ferrolite** [TerraFirmaCraft/TerraFirmaCraft#585]
Barley, Oat, Rice, Rye and Wheat in their freshly harvested state can be eaten like normal food. That seems to be unintended, as eating freshly harvested grains in 1.7.10 is impossible.

 - TFC Version: 0.26.6.97

**Comment by alcatrazEscapee** [comment]
This was intentional - they have severely reduced hunger and nutritional values to typical grains to compensate for the lack of processing.
