### ISSUE TITLE
HUD display changes

### ISSUE THREAD

**Issue by DisasterMoo** [TerraFirmaCraft/TerraFirmaCraft#586]
Configurable style options on how to display health, thirst and hunger bars.

Health
- [x] Vanilla (Heart Textures)
- [x] TFC Classic (Health bar with customizable format)

Hunger
- [x] Vanilla (10 meat chunks)
- [x] TFC Classic (green bar)

Thirst
- [x] TFC Classic (blue bar)
- [x] None (disable thirst bar)

**Comment by alcatrazEscapee** [comment]
As per #441, the goal would be each individual component is able to be enabled and disabled without affecting other parts of the vanilla UI

**Comment by HeartyYF** [comment]
What about oxygen bar while diving/swimming? Design a new bar to adapt to other TFC bars?

**Comment by Abdyman** [comment]
to make the numbers line up more with the numbers other entity's have and the damage the weapons and player can do i would suggest making the value for health 20.00. This would allow for nutrient small buffs to be shown as a fraction of a health point and give something visible to motivate the player to get their nutrient value up. i would highly suggest removing the option for 100% value as this information would never show the player any health benefits applied by TFC or any other mod.
