### ISSUE TITLE
Charcoal pit should be added to JEI for charcoal.

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#588]
Currently there is no mention of charcoal pits in JEI. Would be a good idea to add a fake recipe thing or some info about them.

**Comment by alcatrazEscapee** [comment]
This is one of a large list of "things that you have to go to the wiki to find out". I don't think there's much point adding stopgap documentation to JEI, as you'd still have to use the wiki. We already have a plan to do a proper guidebook / field journal already which would cover this issue.

Basically, I don't see a point in putting effort into JEI documentation over writing the guide book.

**Comment by Abdyman** [comment]
would agree with alc, think this would be better left to a guidebook or wiki
