### ISSUE TITLE
Ceramic jugs delete liquids it can't be filled with

### ISSUE THREAD

**Issue by rhapsodyman2000** [TerraFirmaCraft/TerraFirmaCraft#591]
Empty ceramic jugs delete liquid blocks when you attempt to fetch unassigned liquids, such as lava or hot water. The ceramic jug is left empty.
TerraFirmaCraft version 0.26.6.97

**Comment by alcatrazEscapee** [comment]
Seems the issue is that any fluid not pick-up-able by ceramic jugs still get removed from the world but don't fill.

**Comment by rhapsodyman2000** [comment]
I believe that there is no ID for Jugs filled with Hot water.

**Comment by alcatrazEscapee** [comment]
Different fluids don't have a different ID. There's a list in the config with the valid fluids pickupable with the ceramic bucket. Try adding hot water to that list and seeing if the jug can pick that up.

**Comment by rhapsodyman2000** [comment]
Wouldn’t know how too 😫. Besides, there is no texture for it that I can see.

**Comment by alcatrazEscapee** [comment]
> Besides, there is no texture for it that I can see.

The texture uses the forge bucket blockstate, so this is meaningless. Fluid textures are made using an overlay at runtime. The issue here is just that the ceramic jug will allow picking up fluids despite not actually filling the fluid container.
