### ISSUE TITLE
Spindles don't seem to have durability, yet are used in a `damage_item` recipe for crafting wool yarn

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#592]
**Describe the bug**
Crafting Wool with a spindle stack creates additional spindles
1. What did you expect to happen?
No extra spindles be created
2. What actually happened instead (i.e. what was the bug)
Duplicate spindles!

**To Reproduce**
Wool and at least two stacked spindles in the crafting area. Take the Wool Yarn.

**Meta Info**
 - TFC Version: 97 on the test server and SSP

**Comment by alcatrazEscapee** [comment]
Spindles definitely should not stack if they are a tool that can take durability damage.

**Comment by Gaelmare** [comment]
They have a durability of 40. They definitely shouldn't stack, though!
