### ISSUE TITLE
Allow custom date format as part of locale (i.e. in language file)

### ISSUE THREAD

**Issue by 3TUSK** [TerraFirmaCraft/TerraFirmaCraft#594]
**Describe the request**
In `ICaldnearFormat`, it currently has:
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/a1a31fd0f89a2a8d23c9b5b540a44bcf5086c4db/src/main/java/net/dries007/tfc/util/calendar/ICalendarFormatted.java#L50-L54

this is currently used by `/timetfc` command. On success of execution, the mod gives the adjusted time as feedback.   
A quick search reveals that this is also used elsewhere, e.g. barrel/vessel sealing date, calendar GUI, food expiry tooltip, etc..  
I would like to see that the date format can be specified via language file for better internationalization support; right now, the format is Month/Day/Year which is not universal across the world. That said - is it possible to use `I18n.format` here?

**Meta Info**
 - TFC Version: 0.26.6.97 (at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone? TFC alone.
 - If necessary, what other mods (including versions) would this require? N/A.

**Comment by alcatrazEscapee** [comment]
No, it is not possible to use `I18n.format`, as that's a client side only method. That said, it would be possible to make this part of the proxy return
