### ISSUE TITLE
Rain goes into snow

### ISSUE THREAD

**Issue by HeartyYF** [TerraFirmaCraft/TerraFirmaCraft#598]
**Describe the bug**
![2019-11-28_18 14 21](https://user-images.githubusercontent.com/17660052/69894079-afc08880-1355-11ea-9b09-19b7d4d89785.png)
It's raining but snow is generated everywhere.

**To Reproduce**
Wait for rain in Autumn. Perhaps in Mountains Edge biome.

**Meta Info**
 - TFC Version: 0.26.6.97

**Comment by alcatrazEscapee** [comment]
The temperature is above 0 C - what do you expect to happen?

Snow / rain will completely depend on the day's temperature.

**Comment by HeartyYF** [comment]
Then it should snow instead of rain
