### ISSUE TITLE
build 98 client-side crash on PlayerWakeUpEvent

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#599]
Finally made a bed, slept, and couldn't get out of bed after day came. 

https://gist.github.com/Gaelmare/90d2a5c74f3612aaff7d976788d6e717

Server stayed up!

 - TFC Version: build 98

**Comment by Gaelmare** [comment]
force killing the MC client and restarting gets back in just fine

**Comment by alcatrazEscapee** [comment]
7594a401411849024c7ebf2a6746bae04ee10fcc
