### ISSUE TITLE
Sleeping in bed makes ingots in forge loose heated state

### ISSUE THREAD

**Issue by BigE1293** [TerraFirmaCraft/TerraFirmaCraft#601]
**Describe the bug**
Make sure to include:
1. What did you expect to happen? Sleeping in bed will get the forge to heat an ingot up to melting point
2. What actually happened instead (i.e. what was the bug) after sleeping, ingots went from dark red to warming even though bough there was fuel in the forge
3. If it was a crash, upload the full log file (`latest.log`)
4. If they would help to explain the issue, include screenshots

**To Reproduce**
Attention to detail is important!
1. Do 'put ingots in a forge and start the forge’
2. Then do 'wait until night and sleep in a bed, the ingots should have reset their heated state to warming’

**Meta Info**
 - TFC Version: 0.X.X.97
 - Were any other mods included? Can you reproduce it without these other mods?
 - If necessary, what other mods (including versions) MUST be present to experience the bug?

**Comment by alcatrazEscapee** [comment]
This is exactly what we have intended to happen. When you sleep, the world doesn't tick - it just does some very basic fast-forwarding of certain blocks. Which means for the charcoal forge, it will consume fuel and potentially die out. The contents will not continue to heat as that would involve simulating the entire forge process over a time jump.
