### ISSUE TITLE
berry bushes spawning in desert

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#602]
Think they probably should also care about rainfall, temp, etc?

![2019-11-30_23 27 41](https://user-images.githubusercontent.com/58122689/69910461-28146180-13c9-11ea-9bc8-81e78d0c5dc0.png)

 - TFC Version: build 99

**Comment by alcatrazEscapee** [comment]
They seem to make no checks for the block underneath.

**Comment by allenshoff** [comment]
Re @alcatrazEscapee , I think that's correct, as I've discovered them on ice as well:

![bushes spawning on ice](https://user-images.githubusercontent.com/28602240/72048327-65de9280-3271-11ea-9dad-086db46f85dc.png)

**Comment by Mithrik** [comment]
Another example of berry bushes spawning on top of ice. They also can generate afterwards as this particular lake was already explored and therefore generated prior to it freezing in winter and there were no bushes then on its surface.

![2020-01-20_17 18 08](https://user-images.githubusercontent.com/26398239/72773889-dd8fb400-3bc5-11ea-9f94-fefe22998e02.png)
