### ISSUE TITLE
Small Vessel containing liquid metal heats slower in Forge than one containing ore.

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#603]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
Small Vessels in a Forge to heat at same speed regardless of content.
2. What actually happened instead (i.e. what was the bug)
Vessel with liquid metal heated slower than one containing solid ore.

**To Reproduce**
Attention to detail is important!
1. Do '...'
Place two vessels in a forge at the same time, the one with liquid metal in heats slower than the one containing ore. 

**Meta Info**
 - TFC Version: 0.X.X.98 on test server.

**Comment by alcatrazEscapee** [comment]
This is intentional - different items have different heat capacities. When a vessel is filled with liquid metal, the heat capacity is of the metal inside. Otherwise, it takes the heat capacity of the vessel (which is higher)
