### ISSUE TITLE
Farmland reverts to grass block.

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#604]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
Farmland to stay as farmland, unless affected by a player.
2. What actually happened instead (i.e. what was the bug)
Farmland reverted to a grass block without any user interaction.

**To Reproduce**
Make farmland and plant seeds before winter. 
Watch plants become surface seeds in winter.
Return in Spring to see grass block with seeds on top.
(Of course the seeds part may be irrelevant in reproducing, only experienced once and haven't tried to reproduce yet.)

**Meta Info**
 - TFC Version: 0.X.X.98, on test server.

**Comment by alcatrazEscapee** [comment]
> Watch plants become surface seeds in winter.

This part is completely intended. It sounds like your crops died due to cold temperatures

**Comment by p0kes** [comment]
I left that in in case it was relevant to the farmland reverting (i.e. having a seed on the surface).

**Comment by p0kes** [comment]
Happening for a second time. All blocks under the seeds in the image were farmland. Perhaps the snow or ice affects them?
![2019-12-03_11 11 35](https://user-images.githubusercontent.com/58256171/70049021-a4729480-15c3-11ea-9f93-558bbc91aa70.png)

**Comment by alcatrazEscapee** [comment]
Yes, this will happen. Crops will die, farmland dries out until there's no moisture, then it will turn to dirt, then grass. Ice does not count as a valid hydration source.
