### ISSUE TITLE
Partially filled mold appears empty when accessed from chest

### ISSUE THREAD

**Issue by KalebGreek** [TerraFirmaCraft/TerraFirmaCraft#605]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
Mold stored in chest should show the content of the mold instead of nothing.
2. What actually happened instead (i.e. what was the bug)
Mold appears empty and stackable with other empty molds stored in chest.
3. If it was a crash, upload the full log file (`latest.log`)
4. If they would help to explain the issue, include screenshots

![2019-12-01_12 18 49](https://user-images.githubusercontent.com/18741744/69916086-297b7380-1435-11ea-9744-e9a5eb177a05.png)
![2019-12-01_12 18 52](https://user-images.githubusercontent.com/18741744/69916087-297b7380-1435-11ea-9abb-70b5e57bdd1b.png)

**To Reproduce**
Attention to detail is important!
1. Store partially filled mold in a chest.
2. Close chest.
3. Open chest, the mold appears empty
4. Move the mold back to inventory, game updates the item state correctly and shows the contents.

**Meta Info**
 - TFC Version: 0.27.0.98
 - Were any other mods included? Can you reproduce it without these other mods?
No mods included besides TFC and Forge.
 - If necessary, what other mods (including versions) MUST be present to experience the bug?

**Comment by DisasterMoo** [comment]
Probably related to #584
