### ISSUE TITLE
Placement of non charcoal items as charcoal piles.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#606]
**Describe the bug**
1. What did you expect to happen?
Nothing, it shouldn't do anything.
2. What actually happened instead (i.e. what was the bug)
I was able to place a non charcoal item that shared the ore:charcoal ore dictionary with regular charcoal, this allows converting non charcoal items into charcoal.

**To Reproduce**
Take an item that is part of ore:charcoal (PrimalCore pure carbon for example), and attempt to place it onto the ground.

**Meta Info**
 - TFC Version: 1.12.2-0.27.1.99

**Comment by alcatrazEscapee** [comment]
Yes, that's how the ore dictionary works. Any item with the ore dictionary `charcoal` can be placed into a charcoal pile. If this is a problem then remove the ore name `charcoal` from said non-charcoal items.

**Comment by UnlimatedStone9** [comment]
This seems like an unusual choice as it allows converting items into charcoal, I shouldn't have to remove ore dictionaries from items that work as intended in recipes because TFC chooses to do this.
I don't understand why it was a necessary addition anyways.

**Comment by alcatrazEscapee** [comment]
- If something is in the ore dictionary `charcoal`, that should mean it is charcoal, or equivalent to charcoal. That's literally the purpose of the ore dictionary.
 - The alternative is to hardcode it to vanilla charcoal only, with no potential for customization, which we didn't do, for obvious reasons.

**Comment by UnlimatedStone9** [comment]
Is there not a possibility for configure-able charcoals via the existing TFC configs? As a better alternative to automatically accepting all items that are used as a charcoal equivalent in recipes but logically are not charcoal.
