### ISSUE TITLE
Multiple ore types in naturally generated veins of ore.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#609]
**Describe the request**
Make sure to include:
1. What problem or issue would this enhancement solve?
Purely a mixture of aesthetics and survival enhancement for geologically accurate ore formations.
2. Describe the feature itself - what would change, what would happen. In general more detail is good!
Ores would be able to be configured with more than one block type for a vein, an example of this would be generating gold ore clusters within a magnetite vein, to add some color and additional resources to the ore veins.

**Meta Info**
 - TFC Version: 1.12.2-0.27.1.99 (at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
Both.

**Comment by Abdyman** [comment]
this sounds like it could make prospecting possibly harder, as you would get multiple readings with different information by moving just a couple of blocks

**Comment by UnlimatedStone9** [comment]
I'm not sure I agree with that statement @Abdyman, as far as I can tell, it should be possible to have the hotbar indicator say something like
"Found sample of Tetrahedrite and NativeGold", "Found sample of Magnetite, Limonite and Iron", etc.

**Comment by Abdyman** [comment]
it wouldn't make it impossible or crazy hard even, it would just make it a little more complex im thinking, as far as narrowing down the exact one you are looking for if that happens to be the case

**Comment by UnlimatedStone9** [comment]
That I can agree with, and personally I think it would be a great addition to TFC, it would compliment its play style very well and would allow for much nicer geological constructions.

**Comment by alcatrazEscapee** [comment]
After a pretty systematic rewrite of ore generation, this will be by default present in 1.15, along with the ability to specify rock type -> stone mappings, and a whole host of other convenience features.
