### ISSUE TITLE
pressing V while not looking at a block crashes the game

### ISSUE THREAD

**Issue by Sty2k5** [TerraFirmaCraft/TerraFirmaCraft#622]
**Describe the bug**
Make sure to include:
1. What did you expect to happen? absolutley nothing
2. What actually happened instead (i.e. what was the bug) CTD 
[latest.log](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/3924704/latest.log)

3. If it was a crash, upload the full log file (`latest.log`)
4. If they would help to explain the issue, include screenshots

**To Reproduce**
Attention to detail is important!
1. Do '...' open the game
2. Then do '...' without facing a block press v with an item in hand

**Comment by DisasterMoo** [comment]
This looks like a bug in TFCTech (i'm it's dev). Are you using the latest, 1.0.2 version?

**Comment by Sty2k5** [comment]
yes

**Comment by alcatrazEscapee** [comment]
I can't reproduce with just TFC. Nor does that crash have anything to do with placed items, or TFC at all.
