### ISSUE TITLE
Can't top up almost full barrel using jug

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#626]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
To be able to top up an almost full barrel to full level.
2. What actually happened instead (i.e. what was the bug)
The jug tried to fill the barrel, but only 60mB was needed. Nothing happened, the barrel wasn't filled at all and the jug still had water in.

**To Reproduce**
Attention to detail is important!
1. Do '...'
Try to fill the last <100mB of a barrel of water using a jug.

**Meta Info**
 - TFC Version: 0.X.X.103 on test server.

**Comment by DisasterMoo** [comment]
Jug only have two states: filled and unfilled. Since the container can't take the full value (100 mb) you can't empty a jug there.

**Comment by alcatrazEscapee** [comment]
To add on to this: the alternative is to have jugs delete fluid, which in all cases *except* infinite fluids, would be a worse outcome.
