### ISSUE TITLE
Bed bug

### ISSUE THREAD

**Issue by Mrthomas20121** [TerraFirmaCraft/TerraFirmaCraft#627]
**Describe the bug**
If you leave your bed while sleeping, the sun will "roll back in time" and you will see the sun fadding.
![2019-12-06_10 02 33](https://user-images.githubusercontent.com/34064092/70310283-8d27e700-180f-11ea-966c-8cada6382fa1.png)
the screenshot show what happen after you left your bed. it doesn't matter when you do it during the night. it always bring the sun back to as showed in the picture.
**To Reproduce**
start sleeping
then press the escape key to quit the bed

**Meta Info**
 - TFC Version: 0.27.3.103
 - Were any other mods included? yes Can you reproduce it without these other mods? yes

**Comment by p0kes** [comment]
Looks like #623

**Comment by Mrthomas20121** [comment]
Indeed. i'll close to not have duplicate.
