### ISSUE TITLE
Pit Kilns Aren't Working

### ISSUE THREAD

**Issue by Whhyymee** [TerraFirmaCraft/TerraFirmaCraft#629]
**Describe the bug**
1. I expected to place the clay vessel on the ground in a 1x1x1 hole by shift-right clicking
2. Instead, I shift-right clicked and nothing happened (the clay vessel was not placed). I was able to crouch, my right-click works when placing blocks, but when trying to place clay items, I can't.

**To Reproduce**
 1. Do install TerraFirmaCraft-MC1.12.2-0.27.3.103

**Meta Info**
 - TFC Version: 0.1.12.2
 - Other mods were included: theoneprobe-1.12-1.4.28, DynamicSurroundings-1.12.2-3.5.4.3, jei_1.12.12-4.15.0.268, journeymap-1.12.2-5.5.5, OptiFine_1.12.2_HD_U_E3, and OreLib-1.12.2-3.5.2.2
 - I tried making a pit kiln using only Terrafirmacraft (no other mods) and I still couldn't place down the clay items.
 - As far as I can tell, no other mod is causing the bug.

**Comment by alcatrazEscapee** [comment]
Press V to place pottery in 1.12
See https://tng.terrafirmacraft.com/Differences_From_Classic

**Comment by repin4** [comment]
Describe the bug

Hello, I'm having an issue where I'm unable to place straw to cover my clay jars or molds in TerraFirmaCraft. I've tried using Shift + right-click to place the straw, but it doesn't seem to work. Can anyone help with this issue or suggest a solution?
