### ISSUE TITLE
Chicken Jockies drop default stat "raw chicken" item, and doesn't drop bones.

### ISSUE THREAD

**Issue by HaphLife** [TerraFirmaCraft/TerraFirmaCraft#630]
**Describe the bug**
Make sure to include:
1. I expected to get the modded raw chicken item (with protein and fat), I also expected to get bones, but I did not.
2. Instead, I got raw chicken with the default stats (carbohydrates: 10)
4. Sorry I don't have a screenshot, I ate the chicken since I was still hungry.

**To Reproduce**
1. Kill a chicken jockie chicken in survival, I killed the zombie first.
2. Then pick up it's drops 
3. Then look at the tooltips of the "raw chicken" item you just picked up

**Meta Info**
 - TFC Version: 0.X.X.XX
 - Other mods I had on: JEI, Journeymap, NEAT
 - Mods necessary to produce the bug: I didn't try, but I presume none, since they were small mostly visual/inventory management mods and shouldn't have affected the mob's drops.

**Comment by Gaelmare** [comment]
To fix this, I expect we need to intercept the spawn event some how and ensure it's riding a tfc chicken instead?

**Comment by DisasterMoo** [comment]
https://github.com/TerraFirmaCraft/TerraFirmaCraft/pull/809/commits/aef53d33343249fa846eec206d22a0751a6ff384 may have fixed this too, need to confirm this after merge

**Comment by alcatrazEscapee** [comment]
In any case, it should prevent any vanilla animal spawns if the relevant config option is disabled. May not create any chicken jockies, but that's a trade off I'm willing to live with.
