### ISSUE TITLE
Configure-ability for custom block entries to have TFC gravity mechanics.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#632]
**Describe the request**
Make sure to include:
1. What problem or issue would this enhancement solve?
Blocks not falling like vanilla TFC gravity blocks. (i.e gravel can fall down slopes and hills, etc)
2. Describe the feature itself - what would change, what would happen. In general more detail is good!
It would allow configuring blocks to follow TFC's gravity mechanics for soils and cobblestones, an example would be allowing vanilla sand or gravel to fall like TFC sand or gravel.

**Meta Info**
 - TFC Version: 1.12.2-0.27.3.103 (at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
Both.

**Comment by alcatrazEscapee** [comment]
Can I suggest the mod Repose, by delvr, which does this exact thing.

**Comment by UnlimatedStone9** [comment]
Repose would be a good option if it allowed disabling the "slope" effect, which it does not.

**Comment by alcatrazEscapee** [comment]
> Repose would be a good option if it allowed disabling the "slope" effect, which it does not.

Wrong. See `Sloping Blocks: None`

**Comment by UnlimatedStone9** [comment]
I could use repose, if it provided an option to disable block "sloping", which it does not.

**Comment by UnlimatedStone9** [comment]
What version of Repose is being used? Configs don't show anything of the sort. @alcatrazEscapee

**Comment by alcatrazEscapee** [comment]
In which case, see #645
