### ISSUE TITLE
TFC molds don't produce NBT data with useful information.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#633]
**Describe the request**
Make sure to include:
1. What problem or issue would this enhancement solve?
Not even certain why, but if I recall correctly molds used to produce NBT data such as
"<tfc:ceramics/fired/mold/ingot>.withTag({FluidName: "copper", Amount: 100})",
however upon melting metal and casting it both using a crucible and a forge you will receive blank NBT data, i.e
"<tfc:ceramics/fired/mold/ingot>.withTag({})",
now that's fine and dandy but when it comes to custom recipes requiring filled molds, in other "machines" or processes other than the normal crafting table you can't really use these, and using the example shown first doesn't work.
I can happily add unmolding crafting recipes the same way TFC handles it, but no other methods.
Doubtful much can be done to fix this for modpack makers.
2. Describe the feature itself - what would change, what would happen. In general more detail is good!
Useful NBT data tags added to TFC mold type items that can be used in recipes and such other than the vanilla crafting interface.
**Meta Info**
 - TFC Version: 1.12.2-0.27.3.103 (at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
Yes. :p

**Comment by UnlimatedStone9** [comment]
If nothing can be done for this, then that's fine, I'll just find some form of work around or give up on using the molds the way I want to, but some consideration would be deeply appreciated!

**Comment by alcatrazEscapee** [comment]
This is intentional - capability implementations don't save their contents to stack NBT (See #395). Any mod that supports arbitrary recipe classes very likely can use their API to add recipes or ingredients which respect capability data.
