### ISSUE TITLE
Blast Furnace doesn't use much charcoal

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#635]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
Blast Furnace to use 1 charcoal for each piece of ore processed
2. What actually happened instead (i.e. what was the bug)
Only a few pieces or charcoal used to process 20 ore.

**To Reproduce**
Attention to detail is important!
1. Do '...'
Process 20 ore in Blast Furnace
2. Then do '...'
Break BF to recover ~17 charcoal afterwards?

**Meta Info**
 - TFC Version: 0.X.X.103 on test server.

**Comment by Gaelmare** [comment]
Classic consumed one piece of charcoal with every piece of ore melted, plus the ore used to keep the blast furnace hot at roughly the same rate as the forge. It didn't burn charcoal at an extra fast rate, if it helps. The melt in TNG seems to happen all at once, so maybe the extra speed on charcoal burn makes sense?
https://github.com/TerraFirmaCraft/TFC-1.7.10/blob/9979960a7c13c19e4e6d018aa774c8a707c85592/src/Common/com/bioxx/tfc/TileEntities/TEBlastFurnace.java#L156
