### ISSUE TITLE
Calendar: after sleeping in SMP, get out of bed at 1315 or later

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#642]
I thought days were kinda short, then noticed that the time right after getting out of bed was halfway through the day or more. Seems to be random what the time is, but so far always after noon. Have seen 1316, 1533, and 1648(!)

 - TFC Version: build 105

**Comment by p0kes** [comment]
Ah but did you notice how many thousand years you'd slept?
![sleepy](https://user-images.githubusercontent.com/58256171/70431954-0759a500-1a76-11ea-9a31-e9cb8de67062.png)
