### ISSUE TITLE
Conflict with Repose block drop duplication.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#645]
**Describe the bug**
Make sure to include:
1. What happened? (i.e. what was the bug)
Placing a soil block with TFC and Repose installed results in two falling block entities that can duplicate block drops.
**To Reproduce**
Attention to detail is important!
1. Install both mods.
2. Place a collapse-able block.
3. Profit.

**Meta Info**
 - TFC Version: 1.12.2-0.27.3.103
 - What other mods (including versions) MUST be present to experience the bug?
Repose: Repose-1.12-1.6.4

**Comment by alcatrazEscapee** [comment]
This sounds like an option for repose to whitelist / blacklist certain blocks (namely, TFC soils)

**Comment by DisasterMoo** [comment]
I've added a config for disabling/enabling certain falling features, see #809. I think this issue may be closed after merge since you can disable TFC falling altogether.
