### ISSUE TITLE
TFC Inventory tab buttons overlap with JEI

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#646]
**Describe the request**
Make sure to include:
1. What problem or issue would this enhancement solve?
Annoying JEI and Inventory clashing.
2. Describe the feature itself - what would change, what would happen. In general more detail is good!
The TFC inventory tabs for example would push JEI out of the way, this is standard for most mods that add slots that would otherwise conflict with JEI.

Shown here is TFC conflicting with JEI whilst Quark pushes it aside.
![image](https://user-images.githubusercontent.com/40124890/70467462-2b8ca480-1abd-11ea-9089-967f3193c6d0.png)

**Meta Info**
 - TFC Version: 1.12.2-0.27.3.103 (at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
Both
- If necessary, what other mods (including versions) would this require?
Just Enough Items.

**Comment by alcatrazEscapee** [comment]
Looks like we can solve this by using JEI's `IAdvancedGuiHandler`, similar as is done [here](https://github.com/mezz/inventory-tweaks/commit/95a64ab917a687e6d0ae57f1962ea763a699dae1).
