### ISSUE TITLE
Native Silver spawns in Gabbro now instead of Granite?

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#648]
Native Silver spawns in Gabbro now instead of Granite?

**Meta Info**
 - TFC Version: 0.X.X.105 on test server

**Comment by p0kes** [comment]
![silvergabbro](https://user-images.githubusercontent.com/58256171/70479115-95fd0f00-1ad4-11ea-97cc-e6e8482bcfe3.png)

**Comment by alcatrazEscapee** [comment]
Typo:
<https://github.com/TerraFirmaCraft/TFC-Assets/blob/f4bc88a9527c5db038ebeda1e2ea3845a3debd08/tfc/config/ore_spawn_data.json#L52>
