### ISSUE TITLE
JEI buttons for Anvils, Crucibles, Blast Furnaces, etc.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#649]
**Describe the request**
Make sure to include:
1. What problem or issue would this enhancement solve?
Easy access to the JEI pages of any of TFC's "machines" without having to search for the "machine" or a specific recipe in JEI to find said pages.
2. Describe the feature itself - what would change, what would happen. In general more detail is good!
Basically a mixture of quality of life and consistency with vanilla Minecraft and other mods.

**Meta Info**
 - TFC Version: 1.12.2-0.27.3.103 (at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
Enhancement for TFC+JEI
 - If necessary, what other mods (including versions) would this require?
JEI.

**Comment by alcatrazEscapee** [comment]
Do you mean a clickable area on the machine GUI that would open the list of all recipes? (i.e. clicking on the arrow in a furnace opens all recipes there?)

The way I did this in Tinker's Forging was to have a little question mark in the top left corner of the gui that functioned for this purpose, and only displayed if JEI was enabled. This was less obtrusive, as most of TFC's guis don't have a typical "arrow" to see the progress of A -> B.

**Comment by UnlimatedStone9** [comment]
Yes that's what I mean, however you deem a suitable method if integrating it into TFC I'm fine with, as long as it's not too overwhelmingly obvious, but is clear to the player it's a JEI tab.
