### ISSUE TITLE
Planting seed then digging it up sometimes gives more than one seed

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#652]
Planting seed then digging it up sometimes gives more than one seed

(Agriculture master skill)

**Meta Info**
 - TFC Version: 0.X.X.105 on test server

**Comment by DavidTriphon** [comment]
If crops die by placing their seed on the ground, doesn't it stand to reason that killing a plant sooner by hand should also drop exactly 1 seed? Maybe a better way would be to only drop extra seeds when the plant also drops food, but still drop exactly 1 seed up until that point.

**Comment by DavidTriphon** [comment]
Gaelmare pointed out to me that this issue wasn't closed. This has been fixed by the crop fixes PR.
