### ISSUE TITLE
Rose Gold Anvil Missing

### ISSUE THREAD

**Issue by bryceio** [TerraFirmaCraft/TerraFirmaCraft#653]
The tier two rose gold anvil seems to be missing from the game as attempting to craft it failed and looking in JEI after installing it showed it was not an item.

If this was intentional, it would be nice to have included on the list of changes from 1.7 on the wiki.
![2019-12-10_20 44 25](https://user-images.githubusercontent.com/7949826/70587966-036e7580-1b91-11ea-9cf1-ee8e6c185862.png)

**Comment by alcatrazEscapee** [comment]
Feel free to add it to the wiki yourself, it's open to anyone to edit.
