### ISSUE TITLE
#414 Doesn't work for non vanilla clay balls. (Knapping GUI overwrites right click events)

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#657]
**Describe the bug**
Make sure to include:
#414 reported an issue with clay not being right click-able into containers and such because of the knapping GUI, while resolved, this doesn't work with non vanilla clay ball items. (TFC clay blocks have this issue, but shouldn't be knappable anyways, nevertheless issue persists for non vanilla clay balls)

**To Reproduce**
Attempt to right click vanilla clay balls into something, example being PyroTech's compacting bin.

**Meta Info**
 - TFC Version: 1.12.2-0.27.6.106

**Comment by alcatrazEscapee** [comment]
Testing with clay blocks (although I don't see any reason why this would be different from our end with vanilla clay), knapping is correctly taking lower priority than:
 - chests, both vanilla and TFC
 - sleeping in a bed
 - opening a charcoal forge or crucible

And based on inspecting the call path of all the above, we're correctly subscribing to the event at lowest priority and maintain the `onBlockActivated` call. From this I conclude it's not our problem.

This is a pyrotech issue. Maybe their compacting bin only accepts clay balls and not ore dictionary clay 🤔
