### ISSUE TITLE
Obsidian can be broken but disappears (isn't an item)

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#661]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
Expected to get obsidian when it is mined.
2. What actually happened instead (i.e. what was the bug)
It disappears.

**Meta Info**
 - TFC Version: 0.X.X.105

**Comment by alcatrazEscapee** [comment]
What pickaxe were you using to break the obsidian? It is absolutely an item - it's the vanilla obsidian block. However it's entirely possible that the pickaxe you were using does not have the mining level of a diamond pickaxe (which is required to break obsidian and have it drop)

**Comment by p0kes** [comment]
Ah OK understood, it was a steel pickaxe. 
In that case I'd have expected the obsidian not to break, rather than break and disappear?

**Comment by alcatrazEscapee** [comment]
No, breaking without dropping is vanilla behavior.
