### ISSUE TITLE
Non-spoiled items sometimes create spoiled results

### ISSUE THREAD

**Issue by RiverC** [TerraFirmaCraft/TerraFirmaCraft#662]
**Describe the bug**
Food items that are old enough, when used to produce a quicker-spoiling product, may produce an already-spoiled product even though none of the inputs are spoiled.

**To Reproduce**
Example: Take older corn and mill it into flour. If the corn is old enough (it need not be spoiled;) when you try to make dough out of it, the dough to be output will be green (it will be spoiled before even being made.)

It makes sense that flour which is nearer to being spoiled will produce dough that will spoil even sooner, but it doesn't make sense that unspoiled flour would ever produce spoiled dough.

**Meta Info**
 - TFC Version: MC1.12.2-0.27.6.106
 - No mods that affect this were added.

**Comment by alcatrazEscapee** [comment]
What specific operations can cause this to happen? I spent a while proving mathematically that the system we use to adjust decay dates keeps the decay percentage invariant, so if this is happening it's likely not getting called from something that creates new stacks.

**Comment by RiverC** [comment]
It happened with corn. Let me see if I can reproduce it. I had old corn (that was preserved but not spoiled--) I took it out, ground it into corn meal, and went to mix it. The dough in the output grid was green, so I made corn whisky.

**Comment by CaveAnon** [comment]
Have had this happen with meat when cooked in the firepit.

**Comment by RiverC** [comment]
Just had it happen with wolf meat. 

Steps

1. Have a piece of meat that expires today, but isn't yet expired.
2. Cook it in the firepit
3. The resulting cooked meat will be spoiled.
