### ISSUE TITLE
Dough amounts are less rather than more than flour amounts when mixing.

### ISSUE THREAD

**Issue by RiverC** [TerraFirmaCraft/TerraFirmaCraft#663]
**Describe the bug**
Mixing flour and water produces about half as much dough (in weight) rather than double. 

**To Reproduce**
Mill flour. Mix with water. Two flour (10 oz of flour) and water will produce 1 dough (5 oz of dough,) rather than the usual which is double (2 flour + water = 4 dough or 10 oz flour + 10 oz water = 20oz of dough.)

Uncertain if this is intended, but it's not listed as a difference between 1.7 and 1.12. 

TFC's wiki states, under Bucket:

"Dough
When combining flour with fresh water, the resulting dough will have double the weight. If the flour weighs more than 80 oz, crafting the dough will leave the flour in the crafting grid, minus the 80 oz used to create a max weight piece of dough."

**Meta Info**
 - TFC Version: MC1.12.2-0.27.6.106

**Comment by alcatrazEscapee** [comment]
This just requires going through the recipes and fixing them if anyone's up for that
