### ISSUE TITLE
SpongeForge server empty result in Pit Kiln.

### ISSUE THREAD

**Issue by yaroslav4167** [TerraFirmaCraft/TerraFirmaCraft#664]
**Describe the bug**
If i use SpongeForge server - pit klin broken.
On forge server - all good.

**To Reproduce**
1.
![1](https://user-images.githubusercontent.com/18057310/70852054-9535f580-1ea5-11ea-9de8-83195f2b3d9e.png)
2.
![2](https://user-images.githubusercontent.com/18057310/70852059-a67f0200-1ea5-11ea-9ff1-a4e607f39380.png)
3. Burning...
4.
![4](https://user-images.githubusercontent.com/18057310/70852076-e940da00-1ea5-11ea-98e7-45d8e3524351.png)
Empty =c

**Meta Info**
 - TFC Version: 0.27.7.107
 - SpongeForge: 1.12.2-2838-7.1.8-RC3963

**Comment by alcatrazEscapee** [comment]
If someone from Sponge / SpongeForge can point out what's going on here then I'll be happy to take a look, but otherwise it's not going to get fixed on our end (basically due to time constraints).

> Obvious fix: Don't use SpongeForge.

**Comment by clienthax** [comment]
@alcatrazEscapee How does the Pit Kiln work? is it replacing the block/TE in the same tick as looking up the new TE?

**Comment by clienthax** [comment]
@alcatrazEscapee This is pretty much the description of the issue currently https://github.com/SpongePowered/SpongeForge/issues/3001#issuecomment-539758127

**Comment by cybmp3** [comment]
https://github.com/SpongePowered/SpongeCommon/pull/2462
A lovely guy fixed this bug.
Thank him.

**Comment by yaroslav4167** [comment]
On sponge 1.12.2-2838-7.1.9-RC3979 this bug fixed. 
issue resolved.

**Comment by alcatrazEscapee** [comment]
For further reference: apparently this, while it was fixed, is actually an issue in *newer* sponge versions and may be fixed by https://github.com/SpongePowered/SpongeCommon/pull/2488

Follow said issue for updates unless we hear back from sponge people about something that's a bug on our end.
