### ISSUE TITLE
Add config file option for changing default month length

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#666]
Per discord today, would be really nice to have!

 - TFC Version: build 107
 - Enhancement for TFC alone?

**Comment by Claycorp** [comment]
As per the discussion, the config file option would be the default month length. It still can be edited per world with the command.

**Comment by KaneHart** [comment]
Would be great for pack makers, etc.

**Comment by Gaelmare** [comment]
I looked at this, and solving this is more involved than I thought. Crop growth times are set in forge preinit and never adjusted when the month length changes. The config options aren't available in preinit, so not sure how to fix. I'm thinking the crop growth should also be scaled when the month length changes.
