### ISSUE TITLE
Nether visit causes apparent loss of Skills and health/hunger/thirst bar updates

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#667]
Nether visit causes apparent loss of Skills, and Health etc. bar update. Returns on reconnecting to server.

**To Reproduce**
Travel to Nether

**Meta Info**
 - TFC Version: 0.X.X.107, on test server

**Comment by alcatrazEscapee** [comment]
This is probably something to do with MC's weird dimension change code (which looks very much like what happens when the player dies, in which this behavior would be expected.)

**Comment by p0kes** [comment]
This is still occurring to some extent.

**Comment by p0kes** [comment]
Health bar OK, value not.
Hunger OK
Thirst always maximum.
Skills blank.
