### ISSUE TITLE
Glowstone can't be crafted from Glowstone Dust

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#668]
**Describe the bug**
Can't craft Glowstone from Glowstone Dust

**Meta Info**
 - TFC Version: 0.X.X.107

**Comment by Claycorp** [comment]
This isn't a bug, it's an intentional recipe removal as glow-stone should not under normal TFC circumstances be obtainable.

If you want the recipe add it back via CT or other recipe adding mod.

**Comment by alcatrazEscapee** [comment]
Problem being, infinite light sources in TFC are much more valuable than vanilla. Rather than outright disabling the nether (bad), we do this as a stopgap for obtaining glowstone.
