### ISSUE TITLE
Bloomery textures incorrect

### ISSUE THREAD

**Issue by RiverC** [TerraFirmaCraft/TerraFirmaCraft#671]
**Describe the bug**
When loading the bloomery, the top texture seems to be lit even before the bloomery is lit, and the side texture visible through the hatch is never lit, even when the bloomery is lit.

Expected: the top doesn't glow until you light it from the front, and the front (inside) texture glows once lit.

**To Reproduce**
1. Load a bloomery by placing the charcoal layer (8) in the hatch. 
2. Go to the top of chimney and begin by dropping your ore.
3. When the ore is incorporated into the stack inside the bloomery, it will immediately begin to glow as though lit.
4. Going back to the front, the stack from the inside will not be lit. If you use a firestarter on it, it will not change texture.
5. When you close the hatch however, the hatch will glow indicating the bloomery is lit.
6. The bloomery will otherwise work correctly, indicating this is just a texture issue.

**Meta Info**
 - TFC Version: MC1.12.2-0.27.7.107

**Comment by DisasterMoo** [comment]
The stack, you mean the charcoal pile? if so, that's intended. The top I have fixed tho.
