### ISSUE TITLE
Vinegar making destroys unsourable alcohol

### ISSUE THREAD

**Issue by RiverC** [TerraFirmaCraft/TerraFirmaCraft#672]
**Describe the bug**
Expected that if I put insufficient fruit in a barrel to sour the alcohol, it will fail to turn into vinegar. Instead, if I put one piece of fruit (5 oz) in a full barrel of alcohol, I end up with one fruit's worth of vinegar and the rest of the alcohol vanishes!

TFC Wiki states:

> Vinegar
> Vinegar is created by adding a large enough piece of fruit to an alcohol barrel, and then sealing the barrel for 8 hours. Fruit is the limiting factor in this recipe, meaning that for every 1,000 mB of alcohol in the barrel, there must be at least 10 ounces of fruit in the input slot. Adding an excess of fruit will simply consume the entire fruit in making the vinegar.

**To Reproduce**
Here is what I did:
1. Make at least 500mb of whisky. (I made 4000mb specifically)
2. place one piece of fruit (5oz) in the finished barrel and seal it. 
3. When it is done souring, you'll have 250mb of vinegar; the rest of your whisky disappeared!

(also, I think the recipe outputs differ than TFC Wiki.)

**Meta Info**
 - TFC Version: MC1.12.2-0.27.7.107

**Comment by Claycorp** [comment]
TFC uses minimum quantity recipes now.
This means that whatever you craft with will always craft if you at least meet the minimum requirement or any multiples of it.

This is standard with nearly all mods that do fluid crafting and allows people to craft things if they get weird numbers of liquids. You will just need to do a bit more planing ahead by either storing some in another container/save up to craft or face the loss.

**Comment by RiverC** [comment]
This isn't noted anywhere that I can think of, ergo it either needs to fixed to match the TFC Classic behavior (crafting is limited by amount of Fruit) or explicitly noted that the behavior is the opposite of TFC Classic.

**Comment by Gaelmare** [comment]
I'll update the Differences page in the wiki with this information.

**Comment by alcatrazEscapee** [comment]
For reference:
> TFC uses minimum quantity recipes now.

This is correct, *except* for recipes that convert instantly, which will avoid converting until there is enough of the item to consume the entire amount of fluid. We made this change both for classic consistency, and that instant recipes are less forgiving for inputting in an incorrect ratio initially. (As opposed to a barrel recipe which you have to seal)
