### ISSUE TITLE
Tool enchanting only allows for Unbreaking enchant

### ISSUE THREAD

**Issue by CaveAnon** [TerraFirmaCraft/TerraFirmaCraft#674]
Description:

When enchanting tools through either anvil, enchantingtable or loot-table functions, the only enchant allowed on any kind of tool is Unbreaking.

**Meta Info**
 - TFC Version: 0.27.7.107

**Comment by alcatrazEscapee** [comment]
As far as I can tell this is because we don't subclass vanilla tool / armor classes and instead use our own hierarchy. We aren't going to rewrite that at this stage, so this may be more difficult to fix.

**Comment by DisasterMoo** [comment]
> As far as I can tell this is because we don't subclass vanilla tool / armor classes and instead use our own hierarchy. We aren't going to rewrite that at this stage, so this may be more difficult to fix.

Confirmed that this is the case. Vanilla's enchantments checks in `EnumEnchantmentType.canEnchantItem` for a `instanceof` `ItemTool` or `ItemSword` for example. So, to fix this we gonna need a rewrite of metal tools.
