### ISSUE TITLE
Bookcases don't increase enchanting tables enchanting level

### ISSUE THREAD

**Issue by CaveAnon** [TerraFirmaCraft/TerraFirmaCraft#675]
**Describe the bug**
When surrounding an enchanting table with tfc bookshelves the available enchantment levels do not go up.

**To Reproduce**
1. Get an enchanting table
2. Surround with bookshelves
3. Attempt to enchant item.

**Meta Info**
 - TFC Version: 0.27.7.107

**Comment by alcatrazEscapee** [comment]
```java
Block#getEnchantPowerBonus(World world, BlockPos pos);
```
should fix this.
