### ISSUE TITLE
Brine recipe is missing bucket of vinegar

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#678]
**Describe the bug**
Can't make Brine, recipe looks to be missing the vinegar bucket.
![brine](https://user-images.githubusercontent.com/58256171/71123311-44423c00-21da-11ea-9514-e75d75e0397e.png)

**Meta Info**
 - TFC Version: 0.X.X.107

**Comment by Gaelmare** [comment]
Brine currently requires one bucket of salt water into a whole barrel of fresh water.

**Comment by Gaelmare** [comment]
It will also consume a wood bucket, if you use one. It does not consume a vanilla bucket if you put the salt water in with one.

**Comment by alcatrazEscapee** [comment]
There's an interesting mechanic happening here:
 - vinegar recipes use a fluid ratio mixing calculation - i.e. if you add 10mB + 1 mB, you get out 10 mB of product. Scaled up for the amount required.
 - Showing that in a GUI, when the input will try and be drained of possible fluid, is difficult (i.e. if you use a tank item from another mod, the exact amount will be drained. Using a bucket will result in 1 B being drained and the rest being lost).

This could be improved to actually show the ingredient, however we actually decide to handle fluid item ingredients. (Maybe vanilla bucket with custom tooltip / name set via display tag on NBT?):
 <https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/40d0ac3709e8ea0c24a2285060e8bf310b88c164/src/main/java/net/dries007/tfc/objects/inventory/ingredient/IngredientFluidItem.java#L35>

The recipe difference is already fixed.
