### ISSUE TITLE
Can't determine if horses are male or female

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#681]
**Describe the bug**
Right clicking on a horse doesn't show male/female message.

**Meta Info**
 - TFC Version: 0.X.X.107

**Comment by DisasterMoo** [comment]
Addressed by https://github.com/TerraFirmaCraft/TerraFirmaCraft/pull/528

That PR also adds the possibility of naming animals differently based on gender.

**Comment by alcatrazEscapee** [comment]
#528
