### ISSUE TITLE
Barrel crash

### ISSUE THREAD

**Issue by Mrthomas20121** [TerraFirmaCraft/TerraFirmaCraft#683]
**Describe the bug**
Picking up barrel crash the game

**To Reproduce**
- you put a barrel in the world
- you add a copy to your hand with ctrl and the standard creative block picking method(usually mouse wheel).
- open your inventory
- get the cursor on the barrel you added to your hand
- it crash

**Meta Info**
 - TFC Version: 0.27.7.107
https://paste.dimdev.org/ubujajafof.mccrash

**Comment by Gaelmare** [comment]
Can you reproduce this with Forge build 2678? Could you please give a screenshot of the barrel right before the game crashes?

**Comment by Gaelmare** [comment]
I can't reproduce this.

**Comment by Mrthomas20121** [comment]
i'll see what i can do.

**Comment by alcatrazEscapee** [comment]
Problem is this line:
<https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/40d0ac3709e8ea0c24a2285060e8bf310b88c164/src/main/java/net/dries007/tfc/objects/items/itemblock/ItemBlockBarrel.java#L131>
assumes a inventory of size 1, which will crash when generating the tooltip.

**Comment by alcatrazEscapee** [comment]
`BlockBarrel` needs to override `getPickBlock` and return a stack with the appropriate NBT tag for the sealed barrel (if it is sealed) and the unsealed one if not. Minecraft tries to be helpful and append the tile entity data in the `BlockEntityTag` section
