### ISSUE TITLE
Animal's offspring don't inherit mother's familarity?

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#685]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
Bred animal offspring (pigs in this instance) to inherit some of the mother's familiarity.
2. What actually happened instead (i.e. what was the bug)
None was inherited.

**Meta Info**
 - TFC Version: 0.X.X.107

**Comment by Gaelmare** [comment]
Disaster has an outstanding PR with a bunch of animal fixes in it. We should retest this after that lands, as well as #525. I think that if familiarity decays too quickly after birth it might cause this bug too?
