### ISSUE TITLE
Way to move plants outside of the zone they are allowed to live in.

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#689]
Many people like to collect plants from places they have gone to decorate with them.
The current system in the game doesn't allow this to work anywhere. This could be crafting them with some special soil to get a "resilient plant" or something. Pots could work as well but wouldn't be ideal.

An example of what people have been doing in the test server:
![https://i.imgur.com/qpGai6F.png](https://i.imgur.com/qpGai6F.png)
![https://i.imgur.com/CeTCUPQ.png](https://i.imgur.com/CeTCUPQ.png)

**Comment by eerussianguy** [comment]
Was thinking about this yesterday. Probably simple to register our own flower pot that can accept TFC flowers. I could do custom models for the plants that aren't explicitly flowers. The idea of adding a garden soil that will prevent them from popping off is good too.
