### ISSUE TITLE
Water bottles need balance.

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#691]
Currently the main go to option in TFC for water is a jug, but even easier is the glass bottle. As vanilla bottles can be filled from fresh water and can be drunk from to fill the thirst bar these are the better option as they stack when empty an, provide an indestructible container and can be obtained incredibly early in most worlds while they cost next to nothing.

TFC: 107

**Comment by Gaelmare** [comment]
As a glassmaker, what do you think we should do about this in core TFC?

**Comment by alcatrazEscapee** [comment]
Simplest option: remove recipe for glass bottles and/or gate it behind some tech.
Or, use our already existing override to make the glass bottle have a chance of breaking when you drink from it.

**Comment by Fr4gtastic** [comment]
Haven't you guys thought about about porting the TFC+ glassworking tech? Making bottles would require some more effort and you could also make them breakable.

**Comment by Claycorp** [comment]
We aren't copying TFC+.

If we want to do something to fix it we will make our own solution.

**Comment by Fr4gtastic** [comment]
Not copying then, but some kind of glassworking system might be a good idea and I personally like the one featured in TFC+.
