### ISSUE TITLE
Food & Water drain in creative.

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#692]
Food and water are draining in creative again when they shouldn't be.

TFC: 107

**Comment by KaneHart** [comment]
Can confirm makes testing a bit interesting hehe :)

**Comment by JonJonsonsSon** [comment]
Can confirm this as well.

**Comment by alcatrazEscapee** [comment]
Rather interestingly, vanilla actually still handles `FoodStats#onUpdate` every tick. Which includes checking for saturation, food decay, healing, etc. The difference is that `FoodStats#addExhaustion` is called exclusively from `EntityPlayer#addExhaustion`, which makes a single check to `this.capabilities.disableDamage` before delegating to the `FoodStats`.
