### ISSUE TITLE
Raw meat is edible and has no adverse effects. 

### ISSUE THREAD

**Issue by TheDyreBanana** [TerraFirmaCraft/TerraFirmaCraft#694]
1. What did you expect to happen?
I expected raw meat to be inedible like it is in the 1.7.10 release, or at least have some adverse effect on my health.

2. What actually happened instead (i.e. what was the bug)
The meat was edible and had zero negative effects so it is perfectly safe to eat. From what I could tell it also gives around the same nourishment food bar wise, thus makes cooking meat obsolete. Especially since raw meat keeps longer than cooked meat. 

*Meta Info*
 - TFC Version: 0.27.7.107
 - Were any other mods included? Can you reproduce it without these other mods?
~Wawla, Schematica, FTBLib, FTBUtils, noRecipebook, MouseTweaks, moreoverlays, modnametooltip, Justenoughresources, journeymap, jei, Hwyla, inventorytweaks 

yes its reproducible with just TFC TNG.

**Comment by RiverC** [comment]
I wouldn't expect raw beef to be inedible or less nutritious... without the taste system though, it is an open question as to why not to eat it raw. (Raw pork on the other hand...)

**Comment by alcatrazEscapee** [comment]
> gives around the same nourishment food bar wise

While this is true it is misleading. *Every* food will give the same nourishment food bar wise - two haunches. The difference is in the nutrition and saturation values of each food, of which raw food has less.

**Comment by UnlimatedStone9** [comment]
I've seen some mods do a great job with this by adding a hunger effect for eating raw meats, thus making it a rotten flesh equivalent where it's good in dire situations but not useful in the long run.
