### ISSUE TITLE
Cloth can be put on loom

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#699]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
To not be able to put cloth on loom.
2. What actually happened instead (i.e. what was the bug)
I put the cloth I just made onto the loom by accident (easily done when spamming the loom to weave). Wasn't immediately obvious how to get it off or even why this was possible.

**To Reproduce**
Attention to detail is important!
1. Do '...'
Right click loom with wool cloth in hand.

**Meta Info**
 - TFC Version: 0.X.X.107

**Comment by p0kes** [comment]
![loomcloth](https://user-images.githubusercontent.com/58256171/71534937-12c42180-28fa-11ea-9c5c-47b8c93e4098.png)

**Comment by Gaelmare** [comment]
This isn't allowed in Classic, but I don't think it harms much A texture pack could add cool cloth for display on a loom?

**Comment by Gaelmare** [comment]
Except it only goes onto the loom and fills it up partway, and only wool works, not burlap or silk cloth. Hmm.

**Comment by Gaelmare** [comment]
This is intended. Wool cloth can be woven into wool blocks on a loom.
