### ISSUE TITLE
Minecart is light/v.small

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#700]
Minecart is light/v.small

**Meta Info**
 - TFC Version: 0.X.X.107

**Comment by Gaelmare** [comment]
Not sure what the right answer is here. Find all the various vanilla blocks that should be non-default sizes and set them, one-by-one?

**Comment by alcatrazEscapee** [comment]
Yes, if it's an item that TFC co-opts. See:
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/40d0ac3709e8ea0c24a2285060e8bf310b88c164/src/main/java/net/dries007/tfc/api/capability/size/CapabilityItemSize.java#L43
