### ISSUE TITLE
Pickling fruit consumes vinegar.

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#702]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
The brined fruit to become pickled.
2. What actually happened instead (i.e. what was the bug)
Vinegar disappeared.
**To Reproduce**
Attention to detail is important!
1. Do '...'
Add brined fruit to barrel of vinegar.

**Meta Info**
 - TFC Version: 0.X.X.107

**Comment by alcatrazEscapee** [comment]
This is consistent with other barrel recipes, I don't see a need to specifically make this follow classic behavior. 125 mB is also the nicest multiple-of-eight for balance purposes (a stack of 64 corresponds to is 8000 mB).
