### ISSUE TITLE
Add in-game message for missing TFC world type.

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#704]
There are often lots of questions why a server has a vanilla world. 99% of people are going to want a TFC world so a message and config option for it should be added when a player joins on a server it lets them know they need to set `tfc_classic` in the server.properties.

**Comment by UnlimatedStone9** [comment]
Might I suggest this message be configurable so pack developers don't have to deal with their player base being confused in very specific situational events?

**Comment by Claycorp** [comment]
Then use the config option to turn off the message? The message doesn't need to be configurable.

**Comment by UnlimatedStone9** [comment]
That's exactly what I'm talking about, Clay, a disable option.

**Comment by Claycorp** [comment]
> TFC world so a message and config option for it should be added

???

**Comment by UnlimatedStone9** [comment]
> "and config option"
Didn't take note of that part.

**Comment by alcatrazEscapee** [comment]
This was effectively resolved in 932f60f0d0a83928e43c150a7c6049f655f44de4
