### ISSUE TITLE
Melting ores in a forge causes world breaking crashes.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#705]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
Ore to melt and to leave my world in tact.
2. What actually happened instead (i.e. what was the bug)
Crash that prevents opening said world.
https://paste.dimdev.org/idevepukez.mccrash

**To Reproduce**
Attention to detail is important!
1: Place an ore into a forge and attempt to melt it (I used 5 normal "25U" tetrahedrite ore melting it into 4 ingot molds)
2: Melt at appropriate heat and cause a ticking block entity issue.

**Meta Info**
 - TFC Version: 1.12.2-0.27.7.107

**Comment by Gaelmare** [comment]
I just attempted to reproduce, and could not. Can you please be more specific with what you did?
![2019-12-30_21 57 57](https://user-images.githubusercontent.com/58122689/71610603-9d518e80-2b4f-11ea-9868-8ca6eab23087.png)
![2019-12-30_21 58 07](https://user-images.githubusercontent.com/58122689/71610604-9d518e80-2b4f-11ea-9424-cb2938dd775c.png)

**Comment by UnlimatedStone9** [comment]
I wasn't in the GUI when it happened, I exited it and opened my inventory, (likely irrelevant but I had the game in the background as I was speaking on Discord).

**Comment by Gaelmare** [comment]
I attempted to reproduce again, with my inventory open instead, and could not. If you can give some more specifics how you caused this, that would be great!

**Comment by alcatrazEscapee** [comment]
Also can't produce with items listed. Can you reproduce this crash with just TFC?

**Comment by UnlimatedStone9** [comment]
Just looking at my mods list, the only mods that could potentially interfere with TFC is TFC: Metallum, as it adds new metals and could possibly break forging in some way, alternatively Tinkers' Construct adds molten copper along with other molten metals, TFC seems to always be overwritten by other mods when it comes to fluids so it could also be that.
My attempts to reproduce the crash didn't work unfortunately, even with the same mod list.
I can't provide much more information unfortunately, that's all I can remember and I've been as specific as I could.

**Comment by alcatrazEscapee** [comment]
If there's other occurrences or information we can look into them. Otherwise if it's not reproducible...
