### ISSUE TITLE
Water appears invisible under lava

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#714]
![2019-12-31_02 00 46](https://user-images.githubusercontent.com/52297970/71607446-70ae6e80-2b71-11ea-9b3b-2fee9de1b697.png)

Not for vanilla water:
![2019-12-31_02 01 26](https://user-images.githubusercontent.com/52297970/71607449-80c64e00-2b71-11ea-83d5-e9acf6d00756.png)

**Comment by Bunsan** [comment]
Related to #711 Water render and other parts of the fluid code have known issues.

**Comment by alcatrazEscapee** [comment]
This issue has been fixed in the current MC 1.18 versions of TFC.
