### ISSUE TITLE
Nether portal lead dupe

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#715]
Not sure if this is a vanilla bug or not. I started the process of moving two chickens 10k blocks via a nether portal with two leads. When I was done, I had three. This was on the test server, build 107.

I went through the nether to the overworld location, pulled or pushed the chickens through, then pulled them through the nether back to the original portal. There was a side trip where one bumped through a different portal on the way.

I've not attempted to dial in a reproducer yet.

**Comment by alcatrazEscapee** [comment]
Vanilla nether portal, vanilla lead, yeah, this isn't something that belongs here unless there's an actual case for a TFC problem.
