### ISSUE TITLE
/findrocks command for finding specific rock types.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#717]
**Describe the request**
1. What problem or issue would this enhancement solve?
Inability to find specific rock types, similarly to how /findveins can find ore veins.
2. Describe the feature itself - what would change, what would happen. In general more detail is good!
The command /findrocks would work the same as /findveins but for natural rock types, sure this isn't massively practical for TFC but it would make pack development a hell of a lot easier for me, and potentially other users who rely on testing world generation bound to a specific rock type.

**Meta Info**
 - TFC Version: 1.12.2-0.27.7.107 (at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
Yes.

**Comment by alcatrazEscapee** [comment]
This is not feasible with the current rock generation, as it's very tied to chunk generation and we're not going to make any changes to the existing world gen code. It is something to be looked at in 1.14, but for now this shall be tabled as it's existence as an issue in 1.12 has no relevance to 1.14.
