### ISSUE TITLE
Rock Knife Blade Large Item instead of Small

### ISSUE THREAD

**Issue by KaneHart** [TerraFirmaCraft/TerraFirmaCraft#720]
**Describe the bug**
Rock Knife Blade shows up as Large instead of Small and can't be stored correctly.
![image](https://user-images.githubusercontent.com/425853/71652828-86996c00-2cf6-11ea-88a6-5611e7908d3a.png)
Rock Knife Blade should be set to small. 

**Meta Info**
 - TFC Version: 0.27.7.107

**Comment by Gaelmare** [comment]
When we knapp something out of a tiny, light rock, it should also be tiny and light.
