### ISSUE TITLE
Implement falling block missing features?

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#721]
Falling blocks/cobblestone don't do the following:
destroy loose ore items
destroy ore blocks
damage the player

Play would be easier with these gone, but they are classic features.

**Comment by muzikbike** [comment]
Never been a fan of them destroying ore blocks honestly, I think it'd be better if ores hsd their own cobblestone.

**Comment by Abdyman** [comment]
it was a config option as to if it would destroy ore or not, as far as i know most ppl turned it to off.
