### ISSUE TITLE
lamps should be completed

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#722]
TNG lamps are not yet functional. This should be fixed.

**Comment by alcatrazEscapee** [comment]
In order to make them properly functional: a press / juicer (we don't want to replace the vanilla hopper) that can be used to obtain olive oil.

**Comment by Gaelmare** [comment]
Todo list:
- [X] Olive oil production
- [x] Placeable lamp block/item
- [x] Lamp model and facings
- [x] Switchable light source
- [x] Fluid Tank and fuel
- [x] Burn rate and config
