### ISSUE TITLE
crash Cannot get property PropertyInteger

### ISSUE THREAD

**Issue by cybmp3** [TerraFirmaCraft/TerraFirmaCraft#723]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
 server crash down.
2. What actually happened instead (i.e. what was the bug)
Normal play just mining.
3. If it was a crash, upload the full log file (`latest.log`)
[crash-2020-01-03_14.08.50-server.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/4018253/crash-2020-01-03_14.08.50-server.txt)
[latest.log](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/4018250/latest.log)
[2020-01-03-6.log.gz](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/4018251/2020-01-03-6.log.gz)
[debug-5.log.gz](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/4018252/debug-5.log.gz)

4. If they would help to explain the issue, include screenshots

**To Reproduce**
Attention to detail is important!
1. Do '...'
2. Then do '...'

**Meta Info**
 - TFC Version: TerraFirmaCraft-MC1.12.2-0.27.7.107.jar
 - Were any other mods included? Can you reproduce it without these other mods?
othermods writen in crash report
 - If necessary, what other mods (including versions) MUST be present to experience the bug?

**Comment by Bunsan** [comment]
Please let us know what mod the sakura trees are from and if there is a Pepper crop from another mod.

**Comment by cybmp3** [comment]
> Please let us know what mod the sakura trees are from and if there is a Pepper crop from another mod.
https://github.com/0999312/Sakura_mod
this

**Comment by 0999312** [comment]
I‘m sorry. it's really my fault.
I have fix that.

**Comment by alcatrazEscapee** [comment]
By the looks of it then it's a Sakura issue, and potentially a fixed one? Either way I don't think this is a TFC issue.
