### ISSUE TITLE
Add The ability to make new metals with tfc from existing items with ct

### ISSUE THREAD

**Issue by Mrthomas20121** [TerraFirmaCraft/TerraFirmaCraft#724]
**Describe the request**
1. What problem or issue would this enhancement solve?
That ways we can do everything with crafttweaker and don't have to create mods although for the long term a mod is best.
2. Describe the feature itself
Add The ability to make new metals with tfc from existing items with crafttweaker.
having a method like : mods.terrafirmacraft.Metals.create(String name);
that way we can use that metal to create alloy and stuff.

**Meta Info**
 - TFC Version: 0.27.7.107 (at time of request)
 - If necessary, what other mods (including versions) would this require?
Crafttweaker

**Comment by alcatrazEscapee** [comment]
No. This has been discussed many times, it's not what the metal registry system is designed to be able to do. It is something that is being looked at in 1.14 to open up to datapacks.
