### ISSUE TITLE
Larger Firepits Cause Sound issues.

### ISSUE THREAD

**Issue by KaneHart** [TerraFirmaCraft/TerraFirmaCraft#725]
**Describe the bug**
Make sure to include:
On Multiplayer my mate made a big Firepit and it caused that audio shuddering sounds that might also be causing or can cause performance issues on a client.

Example: https://www.youtube.com/watch?v=V3oE-jFum7M

**To Reproduce**
Make a Large Firepit and lite her up! 

**Meta Info**
 - TFC Version: 0.27.7.107

**Comment by Bunsan** [comment]
Is this TFC only or are other mods loaded. Please provide a complete report to help save time.

**Comment by DisasterMoo** [comment]
What he means is the Charcoal Pit (burning log piles that create charcoal blocks).

The issue explained: Each Log Pile is making a burning sound, hence larger pits cause issues. See : https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/5b42d32d09e6a5f10e57912ffd814a04869b5895/src/main/java/net/dries007/tfc/objects/blocks/wood/BlockLogPile.java#L105
