### ISSUE TITLE
Prevent logs from being placed in large vessels

### ISSUE THREAD

**Issue by allenshoff** [TerraFirmaCraft/TerraFirmaCraft#729]
Logs can be placed in large vessels. This seems unbalanced as you can store many more logs in a very small area. Especially when TFC goes to all the trouble to make the log pile.

![logs-in-vessels](https://user-images.githubusercontent.com/28602240/72049635-29f8fc80-3274-11ea-8231-2418d63b2ae2.png)

Right now it looks like (BlockLogTFC.java, Lns 213-222) logs are Large/Light. They were changed in [8fbc274](https://github.com/TerraFirmaCraft/TerraFirmaCraft/commit/8fbc2741d78db8916c3e1a10bdafd05360da3d69) to prevent them from being placed in chests.

**To Reproduce**
1. Create a large vessel.
2. Place full stacks of logs in large vessels.
3. Can now store 144 logs in one block instead of 16.

**Meta Info**
 - TFC Version: 0.27.5.105
 - CraftTweaker was installed, but not operational and had no effect on the behavior.

**Comment by alcatrazEscapee** [comment]
Large vessel should probably use the same condition as chests then, `< Large` instead of `< Very Large`
