### ISSUE TITLE
Toggles in config file to disable TFC's texture overwrites for vanilla items.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#739]
**Describe the request**
1. What problem or issue would this enhancement solve?
A means of disabling TFC's overwriting of vanilla textures without use of other mods or resource packs.
2. Describe the feature itself - what would change, what would happen. In general more detail is good!
A config option to toggle overwriting vanilla textures.

Quark does this, so I know it's not impossible.

**Meta Info**
 - TFC Version: 1.12.2-0.28.0.110 (at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
Yes.

**Comment by alcatrazEscapee** [comment]
No. Use a resource pack. That is *exactly* what they are designed to do.
