### ISSUE TITLE
Crops should have different temperature ranges

### ISSUE THREAD

**Issue by DavidTriphon** [TerraFirmaCraft/TerraFirmaCraft#741]
**Describe the request**
1. What problem or issue would this enhancement solve?
TFC Classic had different temperatures that each plant required in order to stay alive or grow. Currently all TNG crops require exactly 5-35C.

2. Describe the feature itself - what would change, what would happen. In general more detail is good!
Change the TNG crop temperature values to more closely match those in classic. Classic only cared about minimum ranges, but TNG doesn't make a difference between alive and growing, so there's some leanway to be done.

**Meta Info**
 - TFC Version: (at time of request)
0.28.0.110

 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
This is an enhancement for TFC alone.

 - If necessary, what other mods (including versions) would this require?
none

**Comment by alcatrazEscapee** [comment]
> TNG doesn't make a difference between alive and growing

Yes, it does, or at least should. See <https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/838dd798de233841987cf2f00aabaaf53b0eb648/src/main/java/net/dries007/tfc/api/types/ICrop.java#L33> vs <https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/838dd798de233841987cf2f00aabaaf53b0eb648/src/main/java/net/dries007/tfc/api/types/ICrop.java#L42>

**Comment by DavidTriphon** [comment]
Somehow I missed that. But it's unfortunate that the alive parameters aren't explicit. I think that would be an improvement to allow crops to not die with a greater tolerance than 5 degrees.

**Comment by alcatrazEscapee** [comment]
#749
