### ISSUE TITLE
An expansion of Fire Clay.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#747]
**Describe the request**
Make sure to include:
1. What problem or issue would this enhancement solve?
It would expand the uses of clay and fire clay quite largely.
2. Describe the feature itself - what would change, what would happen. In general more detail is good!
A fire clay kiln crafted using normal fire clay bricks, mortar and potentially a grill (given that the grill is re-implemented, suggested in #748.), can be used to improve the firing of items in a homely space, rather than having a large bulky forged in the middle of the room, a kiln can be placed neatly against a wall, it is slower at heating ingots and such but is quicker at cooking foods, and can be used for unique recipes such as firing normal clay blocks into terracotta, which can be carved or dyed into a variety of decoration blocks.
Fire Brick Kilns can be used to fire the newly introduced fire clay blocks, a duplicate of the already existing clay blocks, fire clay blocks will now fire into a "re-introduced" hardened clay, a terracotta equivalent with a darker but less color warped aesthetic used for decoration or otherwise.
Terracotta (the vanilla block), could be chiseled down using an ordinary chisel to produce clay fired bricks (the vanilla brick), something that can be produced by firing normal unfired clay bricks (a new item), that is crafted by knapping clay or in the 2x2 GUI, similarly to fire clay bricks now.
Fire clay bricks can be crafted the same way by deconstructing hardened clay (the fire clay terracotta block).
The addition of terracotta and hardened clay means you can now fire 4 clay at the same time as you would 1 clay, or quicker, which allows producing clay bricks or fire clay bricks in bulk at four times the efficiency.

**Meta Info**
 - TFC Version: 1.12.2-0.27.7.107 (at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
TFC, but could be useful for compatibility.

**Comment by UnlimatedStone9** [comment]
In regards to the conversation I had with Claycorp for the suggestion #730

**Comment by Abdyman** [comment]
This is something similar to what was added in the old Cooking With TFC mod, and was a much welcome change come mid game. It was used as a replacement for the fire pit to heat more ceramic items and quicker. as a side note, not sure if this or something similar to it could be used as a replacement for the charcoal pit, a charcoal kiln perhaps. Maybe the new kiln can have the option to do charcoal and clay

**Comment by UnlimatedStone9** [comment]
Interesting idea, if I were to consider this, a post-primitive means of producing charcoal would probably be via a coke oven, you would construct insulated firebricks using firebricks and graphite, or graphite clay to construct graphite bricks. These would be used to build the coke oven.
Charcoal could then be produced by encasing log piles in these coke bricks and create a modular coke oven that would cut the charcoal pit burn times down to 33%-50% the regular burn time.
This is how it would function, in concept.
![image](https://user-images.githubusercontent.com/40124890/73877588-d8329a80-4850-11ea-9a6a-66f39b8e2b07.png)
You would then cover the top in coke bricks, or perhaps a hatch or door could be introduced that allows walking into the multiblock charcoal coke oven.
A hatch door concept.
![image](https://user-images.githubusercontent.com/40124890/73877788-365f7d80-4851-11ea-9ef2-f355a5d533d7.png)

**Comment by UnlimatedStone9** [comment]
This would ideally be its own suggestion though, if it doesn't rely on firebricks.

**Comment by alcatrazEscapee** [comment]
Closing as this doesn't fit here as per the description of the enhancement request:
> Suggest an enhancement or small new feature. This is NOT for new mechanics, those should be discussed in our discord.
