### ISSUE TITLE
A reintroduction of the grill.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#748]
**Describe the request**
Make sure to include:
1. What problem or issue would this enhancement solve?
Some cooking enhancements.
2. Describe the feature itself - what would change, what would happen. In general more detail is good!
The grill was a fairly unused but potential holding item in TFC Classic, I think it could be used really well in TNG, both on its own and alongside some Fire Clay expansions suggested in #747.
The grill would cook food at twice the rate of a campfire, and at a similar speed as the Kiln suggested in #747.
This makes cooking on the grill more efficient than cooking in a campfire, and is much more aesthetically pleasing, it could be heated by lighting a forge, campfire or normal fire below it, a campfire could have a chance of smoking foods, whilst the forge could potentially burn/cook them quicker, a normal fire would have no change other than cooking the food at a normal speed.
Forges would no longer be able to cook food like they do now, I don't think it makes sense to throw raw meat into a pit of charcoal and not be given a burned or heavily charred or distasteful food in return.

**Meta Info**
 - TFC Version: 1.12.2-0.27.7.107
 (at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
TFC, unless you count modded foods/addons as compatibility.

**Comment by alcatrazEscapee** [comment]
This (most likely) will get wrapped up into a large set of changes to cooking, food re-balancing, and nutrition which is currently planned but with no actionable steps at the moment. Closing as until such time, there's nothing to be done here.
