### ISSUE TITLE
Effects of carrying multiple barrels applied after placing one

### ISSUE THREAD

**Issue by Mithrik** [TerraFirmaCraft/TerraFirmaCraft#751]
**Describe the bug**
When carrying a single sealed barrel (which was empty) in the middle of rain from one place to the other, the moment I placed the barrel in the ground, the effects of carrying multiple sealed barrels suddenly got applied to me, despite not carrying more items in my inventory that could have caused this issue (like other barrels). Additionally, despite usually restricting all movement, it was possible to move around under these effects, though jumping and breaking blocks was not possible.

![image](https://user-images.githubusercontent.com/26398239/72650951-37327d00-393f-11ea-9ae9-ca9c26166085.png)
This image shows the effects being applied. Notice that the player is not hungry/thirsty and is not carrying any heavy items (or barrels for that matter).

The effects of carrying multiple barrels disappeared after exiting the world and logging back in.

Later attempts at reproducing the bug failed, but instructions of what I was doing prior to it are below to see if anything is at fault there.

**To Reproduce**
(This is a recollection of what I was doing before the bug, one of these actions may or may not have had an effect.)
1. Place an oak barrel on the world where it can gather fresh water from rain.
2. Wait for rain or make it rain.
3. Seal the barrel and move it out of the rain.
4. Unseal the barrel and break it to remove whatever liquid it was holding.
5. Seal it again.
6. Move it elsewhere while sealed and place it down. Try to jump over and place the barrel when you fall down if nothing happens, as I jumped over a chest when placing the barrel that unleashed the bug.

Additionally:
As can be inferred from the screenshot, I was also carrying an Oak Door at the time. It is not a heavy item but it is huge, so that could have played into the incident.

**Meta Info**
 - TFC Version: 0.28.0.110
 - List of other mods used along TFC:
   - HWYLA 1.8.26
   - Ido 1.1.0
   - InventoryTweaks 1.63
   - JEI 4.15.0.628

**Comment by alcatrazEscapee** [comment]
Can't reproduce, if it occurs again then it'll get looked into.
