### ISSUE TITLE
white fruit trees on fast graphics

### ISSUE THREAD

**Issue by shawnm355** [TerraFirmaCraft/TerraFirmaCraft#753]
Fast graphics tends to cause fruit tree leaves to render as white,
**To Reproduce**
put on fast graphics and look at a fruit tree

**Meta Info**
 - TFC Version: 0.28.0.110
 - i have some mods like water flasks in this screenshot but i can reproduse it without

![2020-01-05_13 43 39](https://user-images.githubusercontent.com/34388628/72666455-72d15380-39e0-11ea-9c90-815061ca009c.png)

**Comment by Claycorp** [comment]
Alright, I looked into this and figured out the problem.

The issue: Fruit trees are made up of up to 2 textures. Fruits/Flowers are overlays onto a base block and Fast graphics removes alpha.

Details:
The problem with this is that all the alpha on the overlay is converted to opaque pixels in fast graphics. These pixels retain the color information they have when the file is saved or is defaulted to one color, depends on editor. If there isn't any color it's just white.

Options to fix:
- Merge the two textures into one & remove tint.
Issue here is that these trees use a tint index like all the other trees to match the seasons, but if we combine the colored parts with the green tinted part our colors will now also be tinted. So the tint would need to be removed.
- Keep the current system but edit the overlay.
So we can cheat the fast rendering by adding 1% alpha colors to the texture as MC will cull anything below 50% and make it 100% alpha. With this we can combine the textures in the overlay to get leaf looking blocks vs boxes of terrible. BUT this doesn't allow the tint to be applied so the overlay leaves will not match as bare leaves will still have the tint applied.

Either way the fix will get rid of the ugly textures but something won't work exactly as expected but it's better than the above. There isn't a way around this with the existing systems.

Also with this some other trees need to be looked at as they also have the same issue with bad colors in the alpha areas. All of the following leaves need to be fixed.

- [ ] Banana Flower, Fruit & Leaves
- [ ] Cherry Flower, Fruit & Leaves
- [ ] Green Apple Flower, Fruit & Leaves
- [ ] Lemon Flower, Fruit & Leaves
- [ ] Olive Flower, Fruit & Leaves
- [ ] Orange Flower, Fruit & Leaves
- [ ] Peach Flower, Fruit & Leaves
- [ ] Plum Flower, Fruit & Leaves
- [ ] Red Apple Flower, Fruit & Leaves
- [ ] Acacia Leaves (Set Alpha area to black)
- [ ] Chestnut Leaves (Set Alpha area to black)
- [ ] Acacia Leaves (Set Alpha area to black)
- [ ] Palm Leaves (Set Alpha area to black)
- [ ] Maple Leaves (Set Alpha area to black)
- [ ] Blackwood Leaves (Set Alpha area to black)
- [ ] Rosewood Leaves (Set Alpha area to black)
- [ ] Sycamore Leaves (Set Alpha area to black)
