### ISSUE TITLE
temperatureMode=ENDLESS does not work

### ISSUE THREAD

**Issue by JonJonsonsSon** [TerraFirmaCraft/TerraFirmaCraft#755]
Using a fresh config file & the latest version of TFC, I restarted MC after changing cyclicTemperatureRegions from true to false, made a new world, and it doesn't quite work.
From 0 to -20k Z (North), it works as expected.
From -20k to -40k or -45k, it cycles back to warming up to the temperatures you'd expect around 0 Z, despite that setting being set to non-cyclical ("If you want an endless north / south with a temperate equator, set this to false.").
Beyond that, no matter how far north you go, the temperature is pretty temperate, with the minimum temp ranging from about -4 to 0 C.

 - TFC Version: 0.28.1.111

**Comment by alcatrazEscapee** [comment]
I'm assuming this is the same problem as #637, in that we internally calculate the period of the sin wave (and thus the cutoff point for non cyclic temperature regions) to be twice what it should be

**Comment by JonJonsonsSon** [comment]
This bug exists in the current version of TFC, which is -MC1.12.2-1.6.1.157.
For more context, the current version of TFC doesn't use "cyclicTemperatureRegions=false" anymore, but "S:temperatureMode=", which is set to "ENDLESS" in this case. I'm using the following settings:

        # If Cyclic, this controls the length (in blocks) of the temperature regions. The temperature values change in a wave-like pattern (sine wave).
        # Wandering straight in a direction increases or decreases temperature. When you travel this many blocks, the temperature begins changing in the other direction.
        # Min: 1000
        # Max: 1000000
        I:latitudeTemperatureModifier=1000000

        # This controls how temperature is affected by how far from equator you are.
        # Valid values:
        # CYCLIC
        # ENDLESS
        S:temperatureMode=ENDLESS

**Comment by JonJonsonsSon** [comment]
Tested in a new world in v . The bug still exists, unfortunately. Testing results:

0, 0: Avg temp: 13C / Temperature: 25C
-5k: 4C, 19C (going north & getting colder, as it should)
-10k -4, 13
-20k -14 6
-30k -12 11 (still going north yet getting warmer, which it shouldn't)
-40k -11 22
-50k -9 32
-60k -10 36
-70k -12 30 (still going north and getting colder again, cyclically)
-80k -11 21
-90k -13 10
-100k -12 7
