### ISSUE TITLE
TFC swords don't have a sweep attack.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#757]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
Swords to have a sweeping attack, like most every vanilla or modded sword. (likely not part of ItemSword class.)
2. What actually happened instead (i.e. what was the bug)
No sweep attack.
From a user who posted in the Discord:
https://www.youtube.com/watch?v=aJydq0XNqTw

**To Reproduce**
Attack an entity, clearer when there are more of said entity next to it.

**Meta Info**
 - TFC Version: 1.12.2-0.28.1.111.

**Comment by DisasterMoo** [comment]
Found the piece of code responsible for the sweeping.
In `EntityPlayer.attackTargetEntityWithCurrentItem` (L1425)  there's a check for `instanceof ItemSword` which marks a flag as true for the sweeping.
