### ISSUE TITLE
Balancing the combat system

### ISSUE THREAD

**Issue by DisasterMoo** [TerraFirmaCraft/TerraFirmaCraft#758]
Let's take care of the current combat system
- [x] Tweak vanilla mobs damage resistance
- [x] Tweak animals damage resistance
- [x] Tweak animals health
- [x] Tweak damage output of weapons (attack speed + damage type + damage value)
- [x] Maybe move vanilla threats underground (if so, a buff would be welcome) and make animals the threat aboveground

**Comment by DDZiroWan** [comment]
I just ended doing a new table with all the current weapon's speeds, damages and dps.
https://docs.google.com/spreadsheets/d/1f6zE_nkESJxyNvJzYfpgQRDmahUWCyJgiIFccW-Bvk0/edit?usp=sharing

Just looking at these values, I can notice some issues:

1. Most tools don't have a damage type but still have huge dps. If I understand armor correctly, this makes them better weapons against tfc armor than weapons themselves, as the weapons with damage types have their damage reduced by armor. I would suggest to change how armor works as changing the tool's damage will make it useless for combat in any situation, or and trying to add damage types to all items usable as weapons will result in very weird situations when an tool has to have a damage type but there is not damage type that fits the item. I would make armor stronger against all damage (that is, higher than vanilla diamond), but give weaknesses to it in the case of specific damage types. That is: all armor will protect less against crushing and, for example, red steel would protect less against piercing. At high tiers, should result in armor absorbing more damage than a diamond armor, while against weaknesses should absorb damage like a diamond armor.

2. Some attack speeds are weird or dont make sense. 0.5 attack speed is painfully slow and gives the tool a very low dps even when damage per hit is extremely high. attack speeds of 7 are useless as it enable hitting enemies every 3 game ticks, which will rarely happen as there is a 10 tick immunity after an enemy gets hit. It also make calculating actual dps harder. 

3.All these high attack speeds, combined with the huge damage values, make every weapon or tool OP against mobs and animals and make 1.9+ combat a useless mechanic. It is a great mechanic! We should follow it, even if many people think 1.8 was better. TFC should go forward in time, don't get stuck in old mechanics, and anyone who really prefers 1.8 combat, there will surely be an addon for that.

4. Stone javelins and knives are better thank their copper counterparts.

5. The values are ugly to look at and calculate with mentally. One decimal should be the limit.

6. There are no interesting and complex relations between different tiers and weapons (aka broken meta). Just higher damage and the mace/spear. Swords are useless. 

I have trying thinking a system where all the 3 parts of combat (weapons, armor, and mobs) work fine together. The weapon part is in the google document, the armor part is at the end of point 1 and mobs should be fine with these.
I have introduced some interesting concepts in my suggestion, like copper-bronze tools being slower, making the bronze to iron upgrade more interesting and less evident (but still very great), and making bismuth bronze and blue steel better for piercing, bronze and red steel better for slashing and black bronze better for crushing.
Maces should still be a good weapon against general armor.
Swords are again the best melee weapon in unarmored combat.
Javelins are in beetween, which goes well with their versatility.
Pickaxes, axes, hammers, and knives can all be used easily for PVE and unarmored combat.
It is also balanced to be feel like vanilla combat, friendly to now players and already balanced with other mods' mobs.
