### ISSUE TITLE
sleeping through night does not impact hunger and thirst

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#762]
Not sure if this is an intended change or not.

**Comment by alcatrazEscapee** [comment]
Players need to use an abridged form of `ICalendarTickable` - ONLY when the player is currently logged on and there is a `PLAYER_TIME` change, should it fast-forward hunger and thirst.

For now we can ignore nutrition as there are already plans to handle that better.
