### ISSUE TITLE
Stone axes only had 90% log drop chance in Classic

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#764]
In Classic, trees chopped down with stone axes had 90% chance of each log dropping. 
https://github.com/TerraFirmaCraft/TFC-1.7.10/blob/9979960a7c13c19e4e6d018aa774c8a707c85592/src/Common/com/bioxx/tfc/Blocks/Flora/BlockLogNatural.java#L291

Do we want to implement this mechanic?

**Comment by alcatrazEscapee** [comment]
We do, although with 60% chance.
