### ISSUE TITLE
Cobble duplication using stair blocks and gravity

### ISSUE THREAD

**Issue by Mithrik** [TerraFirmaCraft/TerraFirmaCraft#766]
**Describe the bug**
When placing cobble stairs in a place where cobble becomes gravity-affected, normally you'd expect the block to turn into a single full cobble block and fall into a resting position.

However, if you place a stair in place where it has more than one side to fall into, such as a corner or a one block wide elevation, the stair block will produce a duplicate cobble block, so you end up with two cobble blocks instead of one.

**To Reproduce**
Place a cobble stair block on the edge on an elevation that triggers it to fall from gravity, which has two or more sides the block can fall towards.

**Meta Info**
 - TFC Version: 0.28.1.111

**Comment by Claycorp** [comment]
Cobble stairs falling and turning into cobblestone itself duplicates cobblestone. Takes 6 blocks to make stairs, to get 8. You gain two cobble every time it falls over an edge. Falling flat does not change the block.

Not sure why cobble stairs even fall as other cobble objects do not. (Slabs and walls)

**Comment by alcatrazEscapee** [comment]
I think the fix here is to remove gravity from cobble stairs (I'm not entirely sure how they got it in the first place)
