### ISSUE TITLE
Farming Issue (Crops don't update)

### ISSUE THREAD

**Issue by Whhyymee** [TerraFirmaCraft/TerraFirmaCraft#768]
**Describe the bug**
The crops show no indication of growth. They have been planted for more than 5 in-game months, a sufficient enough time for things to start growing, but none of the crops have shown signs of maturity. 
This sort of "lack of updating textures" (for lack of a better term) can also be noticed when casting. As one puts in a mold into a vessel holding molten metal, the unit number stays at 1. Upon removal, after about 6 seconds of it sitting there, the number suddenly says 100 Units. Usually one can see the number rise but that's not the case. 

**To Reproduce**
It's just something that happens when playing in this version of TFC. I loaded up a few worlds and had the same issues. 

**Meta Info**
 - TFC Version: MC1.12.2-0.28.2.113 and MC1.12.2-0.27.7.107
 - Mods: theoneprobe-1.12-1.4.28 / OreLib-1.12.2-3.5.2.2 / OptiFine_1.12.2_HD_U_E3 / journeymap-1.12.2-5.5.5 / jei_1.12.2-4.15.0.268 / DynamicSurroundings-1.12.2-3.5.4.3. Trying TFC without the mods still resulted in the same issues.

**Comment by alcatrazEscapee** [comment]
#749, #756

**Comment by Gaelmare** [comment]
I believe Disaster's changes fixed the second issue you mentioned, about the metal and heat content sync issues.

The crop not growing issue is still open.

**Comment by Gaelmare** [comment]
And... now it's not! Good job!
