### ISSUE TITLE
Vessels with molten ore don’t show how filled cast is until you right click the ingot twice

### ISSUE THREAD

**Issue by BigE1293** [TerraFirmaCraft/TerraFirmaCraft#769]
**Describe the bug**
Make sure to include:
1. What did you expect to happen? Vessel filled with ore to show much much liquid metal is going into the cast and how much is left in the vessel
2. What actually happened instead (i.e. what was the bug) putting any cast into a vessel of molten metal causes vessel to not show much much is left Until you go out and back into the vessel UI. Molds in the UI will not update their content percentage until you right click twice
3. If it was a crash, upload the full log file (`latest.log`)
4. If they would help to explain the issue, include screenshots
(Will upload a YouTube video showing this, it’s easier to show this than not)
**To Reproduce**
Attention to detail is important!
1. Do ‘fill a vessel with a tool metal (I used copper) and fire until the metal is liquid’
2. Then do 'try to put a mold unto the pour part of the Vessel UI'

**Meta Info**
 - TFC Version: 0.X.X.113 (most recent version)
 - Were any other mods included? Can you reproduce it without these other mods? (Chisel and bits, JM, Chisel)
 - If necessary, what other mods (including versions) MUST be present to experience the bug? NA

**Comment by alcatrazEscapee** [comment]
#756
