### ISSUE TITLE
Fruits get obstructed by branches when harvested from fruit trees

### ISSUE THREAD

**Issue by Mithrik** [TerraFirmaCraft/TerraFirmaCraft#772]
**Describe the bug**
Exactly what's in the tin. When harvesting fruits from fruit trees, the items get stuck in the branches instead of falling to the floor. This had been changed from Classic but it's in Build 113.

**To Reproduce**
Harvest a fruit tree, the fruits from blocks above branches will likely get stuck in said branches.

**Meta Info**
 - TFC Version: 0.28.2.113

**Comment by DisasterMoo** [comment]
Might harvest the fruit directly to the player's inventory and if not possible just drop on his feet.
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/0d9622cf2ea3d86922aa1b44e071679962a42ec8/src/main/java/net/dries007/tfc/objects/blocks/agriculture/BlockFruitTreeLeaves.java#L153-L161
