### ISSUE TITLE
Jute texture is far too big and has massive z-fighting issues due to it.

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#775]
![https://i.imgur.com/Hq1Pm1E.png](https://i.imgur.com/Hq1Pm1E.png)

TFC: 107

**Comment by aliceingame** [comment]
Back in 1.7, I sent a fix for it.
Bioxx liked the look of the large and bushy texture and decided to keep it : https://github.com/Deadrik/TFCraft/pull/475

You can get the texture from my pull request back then if you want to make it one tile large.
