### ISSUE TITLE
F3 menu no longer shows temperture

### ISSUE THREAD

**Issue by BigE1293** [TerraFirmaCraft/TerraFirmaCraft#789]
**Describe the bug**
Make sure to include:
1. What did you expect to happen? To see the average biome temp when I’m F3 mode
2. What actually happened instead (i.e. what was the bug) average biome temp and all temps are gone in F3 mode
3. If it was a crash, upload the full log file (`latest.log`)
4. If they would help to explain the issue, include screenshots 

**To Reproduce**
Attention to detail is important!
1. Do 'press F3’
2. Then do 'see that average biome temp and biome temp don’t exist”

**Meta Info**
 - TFC Version: 0.X.X.115
 - Were any other mods included? Can you reproduce it without these other mods?
 - If necessary, what other mods (including versions) MUST be present to experience the bug?

**Comment by alcatrazEscapee** [comment]
Config -> Set `Debug Mode` to `true` if you want all that extra info.
