### ISSUE TITLE
Ingots placable in large vessel UI 

### ISSUE THREAD

**Issue by BigE1293** [TerraFirmaCraft/TerraFirmaCraft#790]
**Describe the bug**
Make sure to include:
1. What did you expect to happen? Not to be able to put ingots into a large vessel
2. What actually happened instead (i.e. what was the bug) it worked anyways
3. If it was a crash, upload the full log file (`latest.log`)
4. If they would help to explain the issue, include screenshots

**To Reproduce**
Attention to detail is important!
1. Do 'make any ingot (bronze, iron, copper, etc)
2. Then do 'try to put the ingot into a large vessel’

**Meta Info**
 - TFC Version: 0.X.X.115
 - Were any other mods included? Can you reproduce it without these other mods?
 - If necessary, what other mods (including versions) MUST be present to experience the bug?

**Comment by DisasterMoo** [comment]
Should probably do the same for #518 

https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/f99b747086e72dc1fc8ac701b2ca29fb46eb176f/src/main/java/net/dries007/tfc/objects/te/TELargeVessel.java#L190-L199

Add a check for Smaller than Heavy
