### ISSUE TITLE
Add configs for all fluid related containers where possible.

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#796]
Things like the Crucible, Vessel, Barrel and such should all have config options for the maximum amount they can hold (if it can be done without remaking the whole thing)

**Comment by DisasterMoo** [comment]
Just leaving a reminder:
Barrels update as soon as the config changes (voiding surplus).
Small vessels will let you empty the contents(fluids only) before updating.
Crucibles, on the other hand, will not update, regardless. You need to break (empty) and replace.

And this is mostly side effects. My effort was done to make barrels not break GUI after config changes, the others worked like that as soon as i switched the maximum amount to config.
