### ISSUE TITLE
Furnaces, Smokers, Ovens.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#797]
**Describe the request**
Make sure to include:

1. What problem or issue would this enhancement solve?
Mid/late game "machines" for use in a post primitive TerraFirmaCraft world, so modern players don't have to rely on primitive crafting systems.

2. Describe the feature itself - what would change, what would happen. In general more detail is good!
Ovens: Ovens would server as a modern means of cooking/baking foods, you could bake breads, cakes and cookies in them. They would likely be crafted using clay bricks, which would in turn add a nice way to integrate vanilla Minecraft clay bricks into TFC.
Smokers: Again similar to the oven, main difference is it would be built up of a combination of stone bricks and smooth stones, and it would not only heat up foods but smoke them, as a modern equivalent of the smoking rack, if said feature is ever reintroduced, or if food smoking ever becomes a practical addition.
Furnaces: A modern mans Forge, the furnace would serve a fair few functions, one of which would be melting ores inside of vessels, this would be useful as a forge substitute which doesn't smelt things as efficiently as a crucible but does smelt things quicker than a forge and can smelt items in a vessel similarly to the pitkiln, unlike a crucible which melts items one at a time, this means you could bulk alloy items rather than manually add different items to a crucible and alloy them that way. The furnace would also serve as a means of heating up items quicker than a forge, probably at 175% the speed of a regular forge, it would be fueled using charcoal or could be fueled using coal coke for a 200% speed increase. This would work well with coke ovens for producing coal coke.
Disabled by default, Furnaces would have a toggle to automatically inherit vanilla furnace recipes.

**Meta Info**
 - TFC Version: 1.12.2-0.29.0.115 (at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
Enhancement, but has mod support applications.

**Comment by alcatrazEscapee** [comment]
Closing as this doesn't fit here as per the description of the enhancement request:
> Suggest an enhancement or small new feature. This is NOT for new mechanics, those should be discussed in our discord.
