### ISSUE TITLE
An expansion to charcoal pits. Coke ovens.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#798]
**Describe the request**
Make sure to include:
1. What problem or issue would this enhancement solve?
Implements a modern equivalent of the charcoal pit, for efficiency and aesthetics.
2. Describe the feature itself - what would change, what would happen. In general more detail is good!
The coke oven would serve as the modern mans equivalent of a charcoal pit. You would construct insulated firebricks using firebricks and graphite, or graphite clay to construct graphite bricks. These would be used to build the coke oven.
Charcoal could then be produced by encasing log piles in these coke bricks and create a modular coke oven that would cut the charcoal pit burn times down to 33%-50% the regular burn time.
This is how it would function, in concept:
![image](https://user-images.githubusercontent.com/40124890/74093815-4ab0ae00-4acf-11ea-8d80-f0636497781a.png)
You would then cover the top in coke bricks, or perhaps a hatch or door could be introduced that allows walking into the multiblock charcoal coke oven.
A hatch door concept:
![image](https://user-images.githubusercontent.com/40124890/74093829-83508780-4acf-11ea-90d6-c1afc57b5771.png)

**Meta Info**
 - TFC Version: 1.12.2-0.29.0.115 (at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
Enhancement, but has mod support applications.

**Images shown here are concepts using blocks from ImmersiveEngineering and Immersive Decor.**

**Comment by alcatrazEscapee** [comment]
Closing as this doesn't fit here as per the description of the enhancement request:
> Suggest an enhancement or small new feature. This is NOT for new mechanics, those should be discussed in our discord.
