### ISSUE TITLE
Knapping on PlaceBlockSpecial

### ISSUE THREAD

**Issue by Red3Tango** [TerraFirmaCraft/TerraFirmaCraft#80]
[0.5.0.38]

When right-clicking a knappable item on existing placed item, it opens the knapping interface. It allows you to knap based on count -before- placing the item on the ground.

Example: have 5 clay, right-click while holding clay to place, allows you to knap, even though there are now only 4 in inventory.

**Comment by alcatrazEscapee** [comment]
Edited for clarity: the packet send when the client presses "v" is called `PacketPlaceBlockSpecial`, which then creates a `BlockPlacedItem`.
