### ISSUE TITLE
Can't get items out of the Molds

### ISSUE THREAD

**Issue by DeanR97** [TerraFirmaCraft/TerraFirmaCraft#801]
if i try to get my items out of the molds, nothing happens. 
Right-clicking or putting the mold in the crafting table doesn't work.

the mold is fully cooled down.

![Screenshot](https://i.imgur.com/dyjjVA6.png)

TFC 1.12.2 0.29.0.115
OS: Ubuntu 19.10 x64
Java 1.8.0_242

**Comment by DisasterMoo** [comment]
Your mold must be full (100 units) and solid for you to actually take out tools/ingots.
