### ISSUE TITLE
add Config to let you determine the minimum and maximum crop growing temps

### ISSUE THREAD

**Issue by BigE1293** [TerraFirmaCraft/TerraFirmaCraft#802]
**Describe the request**
Make sure to include:
1. What problem or issue would this enhancement solve? Would be a nice aid to help server owners counter wilting for various crop types
2. Describe the feature itself - what would change, what would happen. In general more detail is good! Would let you plant crops, if you wanted, without having to worry about the minimum and maximum growing temps

**Meta Info**
 - TFC Version: 0.X.X.115(at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
 - If necessary, what other mods (including versions) would this require?

**Comment by alcatrazEscapee** [comment]
A few facts:

- This will likely be automatic in 1.16.2 because all of world gen has become a data pack, and
- All of configs are rewritten in >1.12 versions of forge,

yeah, no.
