### ISSUE TITLE
crash on world  creation

### ISSUE THREAD

**Issue by TheNimbleNinja** [TerraFirmaCraft/TerraFirmaCraft#805]
**Describe the bug**
Make sure to include:
1. What did you expect to happen? create a new world
2. What actually happened instead (i.e. what was the bug) game crashed
3. If it was a crash, upload the full log file (`latest.log`)
https://gist.github.com/TheNimbleNinja/c0f10f2f8b816300eb8752e58e2956e7
4. If they would help to explain the issue, include screenshots

**To Reproduce**
Attention to detail is important!
1. Do '...'
2. Then do '...'

**Meta Info**
 - TFC Version: TerraFirmaCraft-MC1.12.2-0.29.1.116.jar
 - Were any other mods included? Can you reproduce it without these other mods?
 - If necessary, what other mods (including versions) MUST be present to experience the bug?
https://gist.github.com/TheNimbleNinja/b66f594d735a75caa63eaaa697fd336a modlist

**Comment by DisasterMoo** [comment]
Can't reproduce, may be something related to FoamFix.
