### ISSUE TITLE
Alloying category not working in newer JEI builds

### ISSUE THREAD

**Issue by DisasterMoo** [TerraFirmaCraft/TerraFirmaCraft#806]
Seems to be blank in newer builds, works fine in JEI's build 222.

**Comment by Mithrik** [comment]
Can confirm. Additionally, refreshing it by clicking on the label of the category causes the game to crash.
![2020-02-12_19 44 54](https://user-images.githubusercontent.com/26398239/74396658-eabc4f00-4dcf-11ea-96d6-bbc60e154535.png)

 It may also disappear entirely, as the game probably realizes that the category is empty and removes it.
