### ISSUE TITLE
Animal dying bug

### ISSUE THREAD

**Issue by DesLandysh** [TerraFirmaCraft/TerraFirmaCraft#807]
**Describe the bug**

When I log-outed, there was a horse staying on a log pile and its head was in tree leaves. When I log-in, on my eyes the horse begin to take a damage and die (methinks, horse drowned in leaves)... 

Make sure to include:
1. What did you expect to happen?
I expect a horse will stay alive after my logining.
2. What actually happened instead (i.e. what was the bug)
the horse begin to scream as it takes a damage and in shortly it died
3. If it was a crash, upload the full log file (`latest.log`)
It's not crash at all
4. If they would help to explain the issue, include screenshots
I tell it just to know

**To Reproduce**
Attention to detail is important!
1. Do '...'
Horse stayed o a log pile, it's head was in maple leaves (distance between log pile and leaves is 1 block)
2. Then do '...'
When I come into the game again, a horse begin to take damage, as it's in a fire or drowned

**Meta Info**
 - TFC Version: 0.129.0.115
 JEI integration  ver. 1.5.1.36 (mouse cross wasn't point to the horse that moment)

**Comment by Azaysol** [comment]
@DisasterMoo is this something u fixed in the animal rewrite?

**Comment by DisasterMoo** [comment]
I'm not sure what is the direct cause of this. My guess is that their hitboxes isn't updated until reloading, in which case that if an animal grows in size (children aging) by a fair amount without reload, and then by a mere chance they walk very near a wall before reloading (see how hard it is to debug stuff) this happens. I will see how feasible it is to update hitboxes, but i don't promise anything

**Comment by Gaelmare** [comment]
I've had several fully grown sheep suffocate in walls. Only way to avoid this so far is to not use barns at all, but surround them completely with fences.
