### ISSUE TITLE
"Thirst" potion effect similar to "Hunger" potion effect.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#808]
**Describe the request**
Make sure to include:
1. What problem or issue would this enhancement solve?
A means of granting players a hunger like potion effect that affects players thirst bars.
Better thirst decrease when drinking salt water.
2. Describe the feature itself - what would change, what would happen. In general more detail is good!
Useful for mod integration in modpacks with unclean water, could be used for TFC salt water jugs instead of suddenly removing water from their thirst bar. Would likely be an option part of the CraftTweaker integration too.

**Meta Info**
 - TFC Version: 1.12.2-0.29.0.115 (at time of request)

**Comment by aschjo** [comment]
While the feature does make sense to be added, it removes the appearance of choice for thirst and along with this, the negative effects make it a strictly bad decision to drink water in a pinch. This is similar to why the developers decided not to have any dirty water or disease as it creates sort of an RNG mechanic that simply makes it unfun for the players early on.

**Comment by DisasterMoo** [comment]
What stone means is instead of just decreasing thirst bar instantly, add a potion effect that does that over time. This is a valid enhancement and is not like the "dirty water" idea (the point in !fss is that dirty water = punishing the player based on a RNG mechanic).

**Comment by UnlimatedStone9** [comment]
> While the feature does make sense to be added, it removes the appearance of choice for thirst and along with this, the negative effects make it a strictly bad decision to drink water in a pinch. This is similar to why the developers decided not to have any dirty water or disease as it creates sort of an RNG mechanic that simply makes it unfun for the players early on.

If I might point out, I actively mentioned it would be salt water and not fresh water, and a potion effect usable via other mods... 🙄
