### ISSUE TITLE
Capability instances are null at ClientEventHandler#onItemTooltip, causing NPE

### ISSUE THREAD

**Issue by addis2123** [TerraFirmaCraft/TerraFirmaCraft#81]
The game crashes during loading with there where multiple mods loaded. after removing many of the mods the crash was different. possibly mod incompatibilities that are one before another. the TFC labeled one was first.

[crash-2019-06-12_20.15.05-client.txt]  TFC Called (https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/3283650/crash-2019-06-12_20.15.05-client.txt)
[crash-2019-06-12_20.33.40-client.txt] Other (https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/3283651/crash-2019-06-12_20.33.40-client.txt)

**Comment by alcatrazEscapee** [comment]
Try with Astral sorcery v1.9.4 please, if possible

**Comment by addis2123** [comment]
Good news. astral sorcery V1.9.4 works when alone. but when combined with biomes-o-plenty the food handler is thrown.
[crash-2019-06-14_06.10.19-client.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/3290190/crash-2019-06-14_06.10.19-client.txt)

**Comment by alcatrazEscapee** [comment]
Fixed in https://github.com/TerraFirmaCraft/TerraFirmaCraft/commit/b3f545bf08881c053ebce7dcec8018df22325f02
