### ISSUE TITLE
116 update wiped horses/donkeys on test server?

### ISSUE THREAD

**Issue by p0kes** [TerraFirmaCraft/TerraFirmaCraft#822]
An FYI as much as much as a bug perhaps but seems that all my tamed horses and donkeys disappeared between 115 and 116 on the test server.

**Meta Info**
 - TFC Version: 0.X.X.116 on test server

**Comment by Claycorp** [comment]
Can confirm. Whatever changed with horses broke them on the server.

https://pastebin.com/ZgLsshwd

**Comment by alcatrazEscapee** [comment]
Is this a reoccurring problem? i.e. horses are not saving correctly? Or is it a one-time on update deal? If the former, it's a bug. If the latter, it's very likely a result of a data serialization change, and we're not writing data fixers at this point.

**Comment by DisasterMoo** [comment]
Clay's log is a bug from my copy-paste overlook: https://github.com/TerraFirmaCraft/TerraFirmaCraft/commit/3b5b7fcb373250553ae05d06de4d225f4fef7c7b#
Now then, i'm not sure if build 115 horses will update correctly in the next builds, but i agree we aren't writing data fixers.

**Comment by alcatrazEscapee** [comment]
Eh, vanilla sometimes has this problem in snapshots. If it should be fixed (as much as possible) I think that's fine.
