### ISSUE TITLE
Recent roadmap summary

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#824]
I wanted to capture this discord exchange from 2020-02-12:

[8:22 PM]  UncleGus: so, if TFC TNG has caught up to classic TFC, is there a roadmap for where it goes from here?
[8:25 PM]  AlcatrazEscapee: In 1.12:
 - food/nutrition rebalance and cooking system
 - (maybe) some new animal stuff
 - general improvements / bugfixes (always)
In 1.14:
 - top-to-bottom world gen rewrite
 - vanilla style texture updates across the board
 - structural code style changes, pack maker frendlification, datapacks, etc.

**Comment by alcatrazEscapee** [comment]
This is not the place for this - projects already has this info. That was also a off hand comment and in no way represents a specific commitment to a list of deliverable.
