### ISSUE TITLE
Allow addons to manage small bush generation

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#825]
If I wanted to replace the kapok bushes with dynamic trees, I wouldn't be able to because GEN_BUSHES is a private static final ITreeGenerator in WorldGenTrees.

Looks like it needs to be made not final and add a setter function. May also need to make TREE_GEN in ChuckGenTFC public?

 - TFC Version: build 116
 - would allow addons to handle bush gen
 - DynamicTreesTFC might want to do this.

**Comment by DisasterMoo** [comment]
I think we should collect things that should be extendable (for addons) like that one in a single enhancement issue.
