### ISSUE TITLE
Classic feature: Some people hate onions

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#826]
Classic had alternate textures and translations for onions with a config option "onionsAreGross".

We should replicate this essential Classic feature.

**Comment by alcatrazEscapee** [comment]
This is a trivial resource pack to make.
Adding a separate resource root with config based reloading is a bunch of work for really no benefit when the alternative is very easy.

**Comment by Gaelmare** [comment]
Thanks. I guess we'll need an achievement for picking an onion so we can
replicate the classic achievement of picking something that clearly isn't
an onion.

**Comment by alcatrazEscapee** [comment]
Also completely doable via resource pack, the hooks for advancements should all exist. If somebody wants to do this they definitely can.
