### ISSUE TITLE
Food Icons in the Creative Tab turn Rotten after some time

### ISSUE THREAD

**Issue by Mithrik** [TerraFirmaCraft/TerraFirmaCraft#827]
**Describe the bug**
After enough time in Creative Mode, the icons for the the food tabs (both vanilla and TFC's) turn rotten.

**To Reproduce**
Fastforward some time in a Creative world.

**Meta Info**
 - TFC Version: 0.29.2.117

**Comment by drhaber** [comment]
It Appears this issue is still happening `TerraFirmaCraft-MC1.12.2-29.5.120`
[Picture](https://i.imgur.com/VFWVqvQ.png)
