### ISSUE TITLE
Implement 'Cast Iron' molten metal and ingot molds?

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#836]
**Describe the request**
Make sure to include:
1. What problem or issue would this enhancement solve?
Consistency with vanilla gold being melted, and for a proper weak iron for modpack makers to use in the crucible.
![image](https://user-images.githubusercontent.com/40124890/74846701-d8d73080-5328-11ea-84c6-47a2642cf793.png)

**Meta Info**
 - TFC Version: 1.12.2-0.29.3.118 (at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
Both

**Comment by alcatrazEscapee** [comment]
We don't utilize vanilla gold, we provide the capability as a convenience. Adding cast iron just for the same convenience is why we designed our metal system to be very extensible to addons (read: use TFC Metallum or other mod). Actually utilizing a separate system of cast iron somewhere in our tech tree is an interesting suggestion, but which belongs in discord.

Basically, if you want X metal to be recognized by TFC, all the tools are there to make that happen already without building extra useless metals into TFC.
