### ISSUE TITLE
berry bushs if left wild should grow overtime

### ISSUE THREAD

**Issue by BigE1293** [TerraFirmaCraft/TerraFirmaCraft#850]
**Describe the request**
Make sure to include:
1. What problem or issue would this enhancement solve? Help with people trying to get more than one bush by traveling over 2000 blocks from base
2. Describe the feature itself - what would change, what would happen. In general more detail is good! Bushes in real life grow over time, at least wild ones do. Letting bushes that grow in the wild to grow over time helps with farming. Bushes in your inventory that you place shouldn’t grow or if they do grow over time very slowly

**Meta Info**
 - TFC Version: 0.X.X.XX (at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
 - If necessary, what other mods (including versions) would this require?

**Comment by DisasterMoo** [comment]
World regeneration currently is disabled since it caused more issues than resolve. Not sure if it will see the light of day, but that place is where our bushes would regenerate over time. Closing this since it already exist but is disabled.
