### ISSUE TITLE
Fuel Registy has broken code

### ISSUE THREAD

**Issue by Sty2k5** [TerraFirmaCraft/TerraFirmaCraft#851]
**Describe the bug**
Make sure to include:
1. What did you expect to happen? in craft tweaker i expected a code along the lines of mods.terrafirmacraft.ItemRegistry.registerFuel(<immersiveengineering:material:6>, 1800, 1500,true ,true); to work
2. What actually happened instead (i.e. what was the bug) the item registry threw an error that invalidated the script
3. If it was a crash, upload the full log file (`latest.log`)
4. If they would help to explain the issue, include screenshots
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/181751cf776079a06d60c5789593c1c8891d66e4/src/main/java/net/dries007/tfc/compat/crafttweaker/CTItemRegistry.java#L263

**To Reproduce**
Attention to detail is important!
1. Do '...' create a fuel registry in craft tweaker
2. Then do '...' load the game up

**Meta Info**
 - 

TerraFirmaCraft-MC1.12.2-0.29.0.115/current (after a restart and update)
 - Were any other mods included? Can you reproduce it without these other mods? yes for the mods, and no
 - If necessary, what other mods (including versions) MUST be present to experience the bug?
Craft Tweaker, and a mod that adds an acceptable not already registered fuel source

**Comment by Gaelmare** [comment]
The code checks if it can register the fuel, then throws an "already registered" error when it can. The if statement needs to be negated.
