### ISSUE TITLE
Quern can be used without material to grind

### ISSUE THREAD

**Issue by Mithrik** [TerraFirmaCraft/TerraFirmaCraft#853]
**Describe the bug**
Exactly what it says on the tin. The quern can be used when there is nothing to grind on it, with the quernstone losing durability in the process too.

**To Reproduce**
Use a quern without putting items on it.

**Meta Info**
 - TFC Version: 0.29.4.119

**Comment by Claycorp** [comment]
I don't think this is a bug personally.

You can use a furnace/forge without putting anything it in and that fuel is lost, this goes with many other TFC systems and even vanilla. Got to pay attention to what your doing.

**Comment by Azaysol** [comment]
would agree with Clays statement

**Comment by Mithrik** [comment]
Well, if it's considered so, I'm closing the issue.
