### ISSUE TITLE
Vanilla chests attempt to connect to TNG chests.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#855]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
Nothing
2. What actually happened instead (i.e. what was the bug)
This monstrosity:
![image](https://user-images.githubusercontent.com/40124890/75377391-a2218d00-58c9-11ea-84fe-15fa17124ead.png)
The vanilla chest has a double chest storage and the TNG one still functions as its own.

**To Reproduce**
Self explanatory, place the chests side by side.

**Meta Info**
 - TFC Version: 1.12.2-0.29.4.119

**Comment by UnlimatedStone9** [comment]
Chests exist as so, too.
![image](https://user-images.githubusercontent.com/40124890/75377539-eca30980-58c9-11ea-8e07-5cd16c0f70c0.png)
Oddly enough, only two vanilla chests can be made into double chests via this method.

**Comment by DisasterMoo** [comment]
If this isn't fixable without rewriting the thing, thankfully, i saved my old chest rewrite branch just in case: https://github.com/TerraFirmaCraft/TerraFirmaCraft/pull/223
