### ISSUE TITLE
[Suggestion] Burning Mobs should set fire to the Block they Died on

### ISSUE THREAD

**Issue by drhaber** [TerraFirmaCraft/TerraFirmaCraft#856]
Fire is incredibly threatening in TFC and when Undead Mobs are moved underground it would be a great addition for them to set fire to the block they were on if they burn to death in the sun.

**Comment by DisasterMoo** [comment]
Sorry, but i think this is addon/another mod territory. Not that it would fit or not TFC, but it's not a thing that only TFC could do (eg: another simple mod could do it and be used as standalone, so it would improve vanilla "realism").
