### ISSUE TITLE
Configuration Option for what "debris" spawns above specific rocks/ores/near trees.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#857]
**Describe the request**
Make sure to include:
1. What problem or issue would this enhancement solve?
Useful for pack developers to integrate new items to TFC.
2. Describe the feature itself - what would change, what would happen. In general more detail is good!
You would be able to configure what can be found as debris, in the form of surface samples (above ores), rocks (above select or all rock types), or sticks, (around/near trees/however sticks are told to generate right now).

**Meta Info**
 - TFC Version: 1.12.2-0.29.4.119 (at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
Yes.

**Comment by DisasterMoo** [comment]
Ore samples, just did. But changing which rocks generates atop certain rock layers or where to generate sticks requires rewriting world gen, which i'm not doing since 1.15 world gen is already being rewritten anyway.

**Comment by UnlimatedStone9** [comment]
That's cool, not possible to allow random sample to be created? So I could just throw random bits of flint anywhere.

**Comment by Claycorp** [comment]
I'd imagine its possible to hack around by making veins of stone that generate and give then the flint as an indicator.

**Comment by UnlimatedStone9** [comment]
Potentially so, though that would require 21 unique "ore" registrations to take place for one item to be scattered over all rock types.
It would also make other ores rarer too, nevertheless a good alternative, thanks for that.
Either way I'd rather see another "ground_fall" type system be added.

**Comment by Claycorp** [comment]
1.15 will have that I'd assume. I would like to see more control over the regen system too but with how buggy it has been that's another 1.15 thing.

**Comment by UnlimatedStone9** [comment]
Sounds good, it's too bad we can't have more control of certain things in 1.12.2, but 1.15+ is going to be legendary.
