### ISSUE TITLE
Newborn piglets are all hunchbacks

### ISSUE THREAD

**Issue by ex0planetary** [TerraFirmaCraft/TerraFirmaCraft#858]
What was expected to happen: Baby pigs look like...small pigs
What actually happened: Baby pigs need to go to the chiropractor. They look like this:
![2020-02-26_16 25 12](https://user-images.githubusercontent.com/18506935/75398279-692bed00-58b6-11ea-9d3a-e5e38f792408.png)
It only happens on the newborn pigs though (1st stage of growth)

**To Reproduce**
1. Find or breed a baby pig
2. Look at the pig

**Meta Info**
 - TFC Version: 0.29.4.119
 - I had a few other addons installed. Pigs are still broken if I remove the other mods though.

**Comment by DisasterMoo** [comment]
Not only pigs, but sheeps and cows also have the same issue.
