### ISSUE TITLE
Bellows render nitpick

### ISSUE THREAD

**Issue by alcatrazEscapee** [TerraFirmaCraft/TerraFirmaCraft#86]
![this_bellows_render_has_already_driven_me_up_the_wall](https://user-images.githubusercontent.com/35673674/59725267-0c424800-91fb-11e9-8d14-86db6bd54c4d.png)
Literally unplayable

**Comment by CtrlAltDavid01** [comment]
The textures in the middle are rotated by 90°, I just noticed!

**Comment by alcatrazEscapee** [comment]
Fixed in #101
