### ISSUE TITLE
Ingots can be stored in chests

### ISSUE THREAD

**Issue by Mithrik** [TerraFirmaCraft/TerraFirmaCraft#863]
**Describe the bug**
Perhaps due to another tweak to the weight/size system, ingots can now be placed inside chests.

**To Reproduce**
Try to put an ingot inside a chest.

**Meta Info**
 - TFC Version: 0.29.4.119

**Comment by alcatrazEscapee** [comment]
For reference, this (or similar ideas) has been discussed a couple times when this issues keeps reoccurring:
https://github.com/TerraFirmaCraft/TerraFirmaCraft/projects/3#card-33970985

**Comment by alcatrazEscapee** [comment]
Post 8e2819dd94ae5d73f669e390661099b8d6e82828 this is considered intentional behavior.
