### ISSUE TITLE
Drinking water directly from source doesn't apply cooldown

### ISSUE THREAD

**Issue by DisasterMoo** [TerraFirmaCraft/TerraFirmaCraft#866]
One of the things i noticed while play-testing: Drinking cooldown isn't working after a successful drink attempt, meaning you can drink yourself to full in less than a second just by holding right click.

**Comment by Gaelmare** [comment]
Alc broke this a while ago. I know it was commented on several times in chat, and a fix was promised. No issue ever made though, apparently. Good catch.
