### ISSUE TITLE
Crucible calls CapabilityItemHeat#addTemp twice per tick

### ISSUE THREAD

**Issue by Mithrik** [TerraFirmaCraft/TerraFirmaCraft#869]
**Describe the bug**
When you put an item into the crucible it heats up as fast as it is allowed to, without considering the heat capacity of the item itself. This results in items heating up way faster in the crucible than the forge/blast furnace.

**To Reproduce**
1. Fire up a forge with a crucible placed on top.
2. Place two identical items, one in the forge, the other in the crucible (I'd recommend wrought iron/a type of steel).
3. Watch the temperature of both items as they rise. The one in the crucible should get hot significantly faster.

**Meta Info**
 - TFC Version: 0.29.4.119

**Comment by alcatrazEscapee** [comment]
I don't believe it's ignoring heat capacity, as both machines are calling through to `CapabilityItemHeat#addTemp` which handles heat capacity, config values, and other calculation related buisness.

However, I think the crucible may just be double-heating each item each tick, as it's called here:
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/181751cf776079a06d60c5789593c1c8891d66e4/src/main/java/net/dries007/tfc/objects/te/TECrucible.java#L125
but then also later here, if the item doesn't melt in that tick
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/181751cf776079a06d60c5789593c1c8891d66e4/src/main/java/net/dries007/tfc/objects/te/TECrucible.java#L137

**Comment by DisasterMoo** [comment]
Oh, my bad, seems a copy paste derp 😛
