### ISSUE TITLE
Bug: Grass spawns on water

### ISSUE THREAD

**Issue by RedstonMaster** [TerraFirmaCraft/TerraFirmaCraft#87]
I was trying the latest version of TFC and I found that some grass was spawning on the water oddly
![2019-06-19_08 49 06](https://user-images.githubusercontent.com/43718572/59743109-95936200-926f-11e9-9055-fd50278b62b7.png)

**Comment by Bunsan** [comment]
This is a known issue that will be fixed when we move to 1.14+ and have waterlogged blocks.
