### ISSUE TITLE
Craft Tweaker Item Register for Water Containers 

### ISSUE THREAD

**Issue by drhaber** [TerraFirmaCraft/TerraFirmaCraft#873]
I noticed that in order to add water containers I can register them as food with no nutrition and only a water value... and even though this works I think it would be nice if it were possible to hook into the water jug mechanic more "correctly".

I was hoping it could look like this and the assumption is that it would only ever hold enough for one drinking action. 

registerItemwatersource(IItemStack, water amount float, return IItemStack);

**Comment by alcatrazEscapee** [comment]
This is called "creating a new item from a mod and giving it a right click action". If you have something already that functions this way as a food, then that's how this is (and should be) possible. We don't allow you to arbitrarily change other mod's right click actions, as it's a very delicately managed thing (even within TFC's source) via config or craft tweaker, adding a new water action would be the same.
