### ISSUE TITLE
Expose Heat destruction recipe to CT

### ISSUE THREAD

**Issue by DisasterMoo** [TerraFirmaCraft/TerraFirmaCraft#875]
Title describes it too well.

**Comment by DisasterMoo** [comment]
Seems that registering heat capabilities with the correct melting temp destroys input (burning food works if the cooked item melting point is reached). I'm leaving this open to be revised later, maybe in 1.15+.

**Comment by alcatrazEscapee** [comment]
I don't much see the purpose of this? Heat destruction recipes are just a wrapper around a normal heat recipe constructor call, which is already CT'able. In 1.15+ this is all gone, so there's no point adding it for future construction. Unless there's another aspect to this I'm missing, there's nothing here that can't already be done.
