### ISSUE TITLE
Charcoal placement rules inconsistent with snow; can only place when directly targeting charcoal

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#878]
With vanilla snow layers, you can add one more layer to the pile when targeting an adjacent block where appropriate; not the case for TFC charcoal.
![2020-03-07_21 42 32](https://user-images.githubusercontent.com/52297970/76152932-34d9dd00-60bd-11ea-83f2-9a0c3ddf8c7e.png)
![2020-03-07_21 42 41](https://user-images.githubusercontent.com/52297970/76152934-360b0a00-60bd-11ea-89fb-ad22e341fa0f.png)
![2020-03-07_21 42 42](https://user-images.githubusercontent.com/52297970/76152935-36a3a080-60bd-11ea-88e0-37ac7742e799.png)

**Comment by DisasterMoo** [comment]
iirc, this is done to facilitate charcoal insertion in bloomeries (not misclick add another charcoal layer when you click in walls).

**Comment by alcatrazEscapee** [comment]
Vanilla snow is also weirdly inconsistent in this respect. A single snow layer has no bounding box, but all other sizes do. You can place up to two layers of snow by right clicking on the side of a block, but no more than the first two. Charcoal isn't snow, nor is it remotely implemented in the same way, so I see no reason why it should act exactly the same.
