### ISSUE TITLE
Improve oregen system by adding debug info.

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#882]
Currently if you are having ore gen issues the only way to know it's working is to load a world and use the commands. But this only applies if the ore is even there to start with.

Some debug in the ore placement should be added to list out whats going on internally. Is one of the options preventing an ore from being placed? Are there other conditions not met? Anything that would make the generation fail should be logged under debug along with when it does succeed.

**Comment by DisasterMoo** [comment]
More input debug & info should go in this class: https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/1.12.x/src/main/java/net/dries007/tfc/util/json/VeinTypeJson.java

And, currently, missing a check about rarity <= 0 here: https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/181751cf776079a06d60c5789593c1c8891d66e4/src/main/java/net/dries007/tfc/util/json/VeinTypeJson.java#L41
