### ISSUE TITLE
Mass ore items are labelled as gemX instead of oreX

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#883]
**Describe the bug**
Make sure to include:
Ores like cinnabar, kaolinite, graphite and jet, etc, are labelled as gem[OreName] instead of ore[OreName], regardless of how they are visibly ores.

Visibly an ore, as it is encased in stone and mined directly from stone, it is unrefined, unlike redstone dust or lapis lazuli.
![image](https://user-images.githubusercontent.com/40124890/76263920-19570980-6258-11ea-94bf-a5d5c5093576.png)

Issues regarding this inconsistency have been "fixed" before, however this issue still exists and is absurd to have existed in the first place.
19 ores in Vanilla TFC have this issue as of late.

**Meta Info**
 - TFC Version: 1.12.2-0.29.4.119

**Comment by alcatrazEscapee** [comment]
We made a decision a while ago not to special case specific ores or gem items individually. All TFC ore items are either metals (which use `ore`), or minerals (which use `gem`). The current situation is the simplest for TFC, and as these are already modifiable by pack makers, we won't be special casing or changing minerals based on individual needs.
