### ISSUE TITLE
Gold pan desyncs on failure

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#885]
When a gold pan fails, it empties. However, the model does not update until an inventory update is forced. 

**To Reproduce**
1. Fill a gold pan with sand or gravel
2. Hold right click at source block til it snaps forward.
3. If it fails, the pan still looks full, but when right clicked, just waves around. 
4. If it succeeds, the pan looks empty.

The pan should empty if panning with it fails.

 - TFC Version: recent builds

**Comment by DisasterMoo** [comment]
Not fixed, see #1271.
