### ISSUE TITLE
Dirt blocks fall and crush tilled dirt.

### ISSUE THREAD

**Issue by ScavengerKing** [TerraFirmaCraft/TerraFirmaCraft#886]
Dirt blocks raised one level above nearby tilled dirt will fall and crush the tilled dirt, causing the tilled dirt to drop as an dirt block item.

**To Reproduce**
Place dirt block.
Till dirt around dirt block, one level below it.
Profit?

TerraFirmaCraft-MC1.12.2-0.29.4.119

**Comment by alcatrazEscapee** [comment]
This is consistent with falling block behavior - non full blocks will get destroyed, or (if the falling material is much softer than the block landing on), pop off as items. See #483.
