### ISSUE TITLE
Commands to force grow/tame entities/plant life.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#890]
**Describe the request**
Make sure to include:
1. What problem or issue would this enhancement solve?
Useful for testing features in creative mode.
2. Describe the feature itself - what would change, what would happen. In general more detail is good!
Makes taming entities for testing features in creative mode easier than what has to be done now (changing time of day, feed, time of day, feed, etc etc etc.)
Same deal for crop growth.
This is generally done when testing integrations in modpacks, like using horses with carts or testing wolf AI, etc. Quality of life really.

**Meta Info**
 - TFC Version: 1.12.2-0.29.4.120 (at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
Yes.

**Comment by Claycorp** [comment]
These would be good features for the debug wand.

**Comment by UnlimatedStone9** [comment]
Yeah, that makes sense. Whatever way we get it I would like to get it.

**Comment by alcatrazEscapee** [comment]
Given that this is rather low priority, I'll leave some alternative commands that do exactly what requested here:

 - For plants or crops, `setblock` can be used to directly advance the growth stage and/or set plants grown. Example: `setblock ~ ~ ~ tfc:crop/wheat 7`. The max growth stage metadata can be guessed by looking at F3.
 - For entities, `entitydata` can directly set these properties. Example: `/entitydata @e[c=1,type=tfc:pigtfc] {familiarity:1f}` sets the data of the nearest tfc pig to 100% familarity.
 - And as you already mentioned, `/timetfc` can also be a manual answer

**Comment by eerussianguy** [comment]
Possible in 1.18 with /data command which works on blocks and entities
