### ISSUE TITLE
CT Fuel Registery Overrides Default Bloomery Fuels instead of Adds

### ISSUE THREAD

**Issue by drhaber** [TerraFirmaCraft/TerraFirmaCraft#895]
1. What did you expect to happen?
This Script to add fuels 
`mods.terrafirmacraft.ItemRegistry.registerFuel(<minecraft:blaze_powder>, 1800, 1350, true, false);
mods.terrafirmacraft.ItemRegistry.registerFuel(<minecraft:coal_block>, 19800, 1415, true, true);
mods.terrafirmacraft.ItemRegistry.registerFuel(<forestry:charcoal>, 16200, 1350, true, true);
mods.terrafirmacraft.ItemRegistry.registerFuel(<immersiveengineering:material:6>, 4400, 1500, true, true);
mods.terrafirmacraft.ItemRegistry.registerFuel(<immersiveengineering:stone_decoration:3>, 39600, 1500, true, true);`
2. What actually happened instead (i.e. what was the bug)
That list overrode the default Bloomery Fuels. Coal Block, Charcoal Block (Forestry) and Both coke variants (item & Block) are accepted Bloomery Fuels 
4. If they would help to explain the issue, include screenshots
[Floating Charcoal](https://cdn.discordapp.com/attachments/432527966266851339/690323848255897660/unknown.png)

**To Reproduce**
Attention to detail is important!
1. Do 
Ct ass Bloomery Fuel
2. Then do 
Attempt to use the bloomery with default fuel

**Meta Info**
 -TerraFirmaCraft-MC1.12.2-29.5.120
 - Were any other mods included? Can you reproduce it without these other mods?
Of course lol
 - If necessary, what other mods (including versions) MUST be present to experience the bug?
CraftTweaker2-1.12-4.1.20

**Comment by DisasterMoo** [comment]
So, I just tested this in build 133 and seems to be working as intended (both charcoal and blaze powder were accepted):
```zenscript
ItemRegistry.registerFuel(<minecraft:blaze_powder>, 1800, 1350, true, true);
```

Should you or anyone else find this bug again feel free to re-open this issue and comment reproduction steps (one buggy crafttweaker script line would be ideal).
