### ISSUE TITLE
Config to disable leaves passability/modify density.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#896]
**Describe the request**
Make sure to include:
1. What problem or issue would this enhancement solve?
Allows for making TFC leaves solid, like vanilla/other mods, and allows mods like Passable Leaves to change how dense TFC leaves are.

**Meta Info**
 - TFC Version: 1.12.2-29.5.120 (at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
Yeah.
 - If necessary, what other mods (including versions) would this require?
Nah.

**Comment by Claycorp** [comment]
Why not implement configs for it in TFC?
Does passable leaves do something else TFC doesn't do?

**Comment by alcatrazEscapee** [comment]
I'd also point out:
 - Passable leaves is a core mod (ugly), so you're asking for a config option, to let another mod ASM into vanilla code in hopes of modifying our behavior.
 - It is also *a core mod that affects vanilla leaves*. After inspecting their source, if we were to implement this config option, passable leaves would have no affect on our leaves.

**Comment by UnlimatedStone9** [comment]
That's unfortunate.
A config in native TFC would be good then if none else.
