### ISSUE TITLE
Unloading and reloading a world makes barrels instantly convert contents even if unsealed.

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#898]
Fill a barrel with any valid recipe and don't seal it.
Quit to the main menu.
Load the world back up. 
Tada, Instant whatever inside of a sealed barrel. Thankfully it follows the recipe and will still consume items correctly.

 - TFC Version: 120

**Comment by alcatrazEscapee** [comment]
This was fixed in b6c38d9d3051d6b8e6de6bc2068e0c87f8d311f0 but not noted there
