### ISSUE TITLE
JEI "show recipes" is displayed above the output slot rather than on the "recipe/processing" arrow.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#907]
**Describe the bug**
This is self explanatory. "show recipes" JEI button should be on the recipe/processing "arrow", like most mods, and Vanilla tend to have.
![image](https://user-images.githubusercontent.com/40124890/77370544-09135400-6d59-11ea-84ac-1292837a6679.png)

**Meta Info**
 - TFC Version: 1.12.2-29.5.120

**Comment by alcatrazEscapee** [comment]
In most cases our GUIs display the `?` when there isn't a good arrow replacement, e.g. the Anvil GUI. Are there specific cases that you have an issue with, because otherwise this is working as intended.

**Comment by UnlimatedStone9** [comment]
Well, off the top of my head, the knapping GUI's could do with this instead.
You could put it on the 2 arrows (on either side of the fluid display) in the  crucible GUI instead of on a ``?``.
iirc the barrel GUI uses arrows, I don't know if it uses them though, or if it uses the ``?``.
