### ISSUE TITLE
If you remove sugar cane you need to remove recipe (or change it)

### ISSUE THREAD

**Issue by aliceingame** [TerraFirmaCraft/TerraFirmaCraft#912]
**Describe the bug**
Make sure to include:
No more TFC sugar cane = broken recipe that need TFC sugar cane

![image](https://user-images.githubusercontent.com/4293373/77482268-ebe39180-6dfb-11ea-8440-5914daab2668.png)

**To Reproduce**
Attention to detail is important!
Try to make sugar

**Meta Info**
 - TFC Version: 0.30

**Comment by alcatrazEscapee** [comment]
Well that was a mistake. I had meant to remove the plant version, not the food product.
