### ISSUE TITLE
Breaking Log with a hand

### ISSUE THREAD

**Issue by Mrthomas20121** [TerraFirmaCraft/TerraFirmaCraft#918]
**Describe the bug**
When you break a log with your hand, it drop the log.

**To Reproduce**
just break a log.

**What Should happen?**
You should be able to break a log but it shouldn't drop a log. it should just drop nothing.

**Meta Info**
 - TFC Version: 0.30.1.122
- Forge version:14.23.5.2847

**Comment by drhaber** [comment]
If this is rectified it should be a config toggle
