### ISSUE TITLE
TFC Dynamic Foods (Sandwhiches) not working with "Custom" Foods

### ISSUE THREAD

**Issue by drhaber** [TerraFirmaCraft/TerraFirmaCraft#919]
Make sure to include:
1. What did you expect to happen?

After Registering a food Item
`registerFood(<minecraft:chorus_fruit>,1,0.1,0.1,1.3,0,0.2,0.1,0,0);	
`
and Registering its as a cartegoryFruit
`<ore:categoryFruit>.add(<minecraft:chorus_fruit>);`

I expected to be able to make sandwiches using it.

[TFC Fruit working ](https://cdn.discordapp.com/attachments/646085141847998484/692401979552694292/unknown.png)

["Custom" Fruit not working](https://cdn.discordapp.com/attachments/646085141847998484/692402084649107476/unknown.png)

**Comment by alcatrazEscapee** [comment]
7419ec00adea52713b6e65636e77cf9e67538af5
