### ISSUE TITLE
Clicking on a pot freezes the game

### ISSUE THREAD

**Issue by MineShadow7** [TerraFirmaCraft/TerraFirmaCraft#923]
**Describe the bug**
Make sure to include:
1. Idk this feature is new. Maybe a GUI or smthn
2. Game freeze
3. Nope. No crash. Just a game full freeze

**To Reproduce**
Attention to detail is important!
1. Place a pot above fire pit
2. Click on it

**Meta Info**
 - TFC Version: TerraFirmaCraft-MC1.12.2-0.30.3.124
 - Other mods: TFC Metallum, TFC OversizedItemInStorageArea, TFC DynamicTrees
Tested - other mods don't matter

**Comment by alcatrazEscapee** [comment]
Can't do anything without a log here, because it's working fine as far as I can see.

**Comment by MineShadow7** [comment]
I'm not sure how but the problem was fixed. So it might be a second addon TFC OIISA causing the problems. Should we close this?

**Comment by Yahay944** [comment]
I have a similar issue. For me my server crashes when I interact with the pot. I checked it and even the second time just clicking on a pot above the fireplace crashes the server. Crash report is attached.

Mod info:
TFC Version: TerraFirmaCraft-MC1.12.2-0.30.3.124
Other mods: BettterFPS, chiselandbits, gravestone, just enough items (And client side mapwriter, inventory tweaks, optifine)
[crash-2020-03-28_01.34.23-server.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/4398089/crash-2020-03-28_01.34.23-server.txt)

**Comment by alcatrazEscapee** [comment]
Looking at that log it seems like it will only apply to fire pits which have been loaded from previous worlds, as we increased the inventory size (to allow for pots + grills). In which case, breaking and remaking the fire pit should fix it. Nothing we can retroactively do here.
