### ISSUE TITLE
isItemValid in ItemSmallVessel and ContainerSmallVessel implementations differ

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#927]
As discussed in my Quiver PR, https://github.com/TerraFirmaCraft/TerraFirmaCraft/pull/901#discussion_r396055778
the implementations of isItemValid differ. Time for the Gathering, there can only be one?

**Meta Info**
 - TFC Version: build 124

**Comment by alcatrazEscapee** [comment]
Expect they aren't different...
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/60a058d27865be5f3535c89438e5c209ec44b3d7/src/main/java/net/dries007/tfc/objects/items/ceramics/ItemSmallVessel.java#L391
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/60a058d27865be5f3535c89438e5c209ec44b3d7/src/main/java/net/dries007/tfc/objects/container/ContainerSmallVessel.java#L30

**Comment by Gaelmare** [comment]
Only because it was changed between when I made the comments on the PR and
now, sorry!

Glad to see that they agree.

Why are there two of them?

**Comment by DisasterMoo** [comment]
Yeah, i also found it weird when i was refactoring Size / Weight, forgot to ask if was needed. Seems to be just a cleanup issue (just call the capability instead of duplicating code), and Alc probably already fixed as he put the `fixed in dev` tag.
