### ISSUE TITLE
Winter food sources.

### ISSUE THREAD

**Issue by Claycorp** [TerraFirmaCraft/TerraFirmaCraft#930]
From the discord dev chat about servers and food spawned a nice idea of adding foods that can be foraged during winter.

Some of those ideas where:
- Nuts
- Cat tail roots
- Conifer needles
- Fruits/Berries that freeze

**Comment by alcatrazEscapee** [comment]
Would rather this be in discord since it's really just a new feature suggestion irrespective of it's merit.
