### ISSUE TITLE
Separate rock/sample/stick "debris" spawn rate configs.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#931]
**Describe the request**
Make sure to include:
1. What problem or issue would this enhancement solve?
Currently rocks, samples and sticks are all considered the same thing when toggling their spawning/regeneration in the config, this means I can't disable the generation of rocks/sticks without disabling surface samples. Or any combination of the three.
2. Describe the feature itself - what would change, what would happen. In general more detail is good!
Ability to disable/change rarity/regeneration of sticks, rocks and surface samples separate from one-another.

**Meta Info**
 - TFC Version: 1.12.2-0.30.3.124 (at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
Both.

**Comment by Claycorp** [comment]
I think that's the plan with 1.15+
Currently Rock/Stick regen is disabled in 1.12

**Comment by UnlimatedStone9** [comment]
Okay, but what about normal generation? I'd like to disable the sticks/rocks for customization via other mods. I don't want regen on anyways so...
My main point is I can't disable the generation of them separately, and for the sake of consistency I mentioned the ability to configure their rarities and such.
