### ISSUE TITLE
Cloud visible trough some blocks

### ISSUE THREAD

**Issue by aliceingame** [TerraFirmaCraft/TerraFirmaCraft#933]
**Describe the bug**
Make sure to include:
1. What did you expect to happen? See the block
2. What actually happened instead (i.e. what was the bug). Clouds (and beams from journey map marker) show through some blocks, the specific one I found are workbench and any TFC liquid. I thought it could be some kind of transparency issue with the texture, but the bottom of the crafting table is just wood.
3. If they would help to explain the issue, include screenshots, sake, workbench and molten metal.
![2020-04-01_17 52 31](https://user-images.githubusercontent.com/4293373/78190485-18259080-7442-11ea-8a94-5262e0a34de6.png)

**To Reproduce**
Attention to detail is important!
1. place block and look at the sky.

**Meta Info**
 - TFC Version: 124, forge 2847
 - Were any other mods included? no, I removed everything else.

**Comment by ufospiral** [comment]
The breaking texture when on the workbench makes it completely transparent as well
![2020-04-02_21 42 45](https://user-images.githubusercontent.com/50275864/78326943-7a5cbf00-7530-11ea-8f2c-8bf5f31f2498.png)

**Comment by frebib** [comment]
THANK YOU. This was really confusing me as it caused the DoF shader to render workbenches very strangely
