### ISSUE TITLE
Lapis Powder recipes have invalid inputs.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#935]
**Describe the bug**
Make sure to include:
It's been like this a while, but I forgot about reporting it. Weird it wasn't noticed by anyone else.
![image](https://user-images.githubusercontent.com/40124890/78312030-5ad29000-754a-11ea-8c85-b22ee4a0be0e.png)

**Meta Info**
 - TFC Version: 1.12.2-0.30.3.124

**Comment by aliceingame** [comment]
#897 
fixed in 125

**Comment by alcatrazEscapee** [comment]
Duplicate of #897
