### ISSUE TITLE
Neglected trees.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#936]
**Describe the bug**

![you forgot white elm](https://user-images.githubusercontent.com/40124890/78312509-f57f9e80-754b-11ea-9798-597e90281a15.png)

White elm was forgotten to the sands of TerraFirmaCraft Classic.

**Comment by alcatrazEscapee** [comment]
And, blackwood, rosewood, and palm took it's place.

**Comment by UnlimatedStone9** [comment]
Oh that was uncalled for! :p
