### ISSUE TITLE
Stone/Sticks popping off the ground

### ISSUE THREAD

**Issue by bhechinger** [TerraFirmaCraft/TerraFirmaCraft#94]
Walking around I'm finding stones and sticks that have popped off the ground and are floating as an item would be if you dropped it. This also seems to duplicate the item sometimes.

Sorry I don't have more details, I forgot to take a screenshot before picking them up. I'll look for others.

**Comment by alcatrazEscapee** [comment]
This will become much easier to identify if you can tell me where you see this happening.
