### ISSUE TITLE
Recipe for terracotta via pitkiln/forge using either clay or fire clay blocks.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#941]
**Describe the request**
Make sure to include:
1. What problem or issue would this enhancement solve?
Inability to obtain terracotta, glazed terracotta or anything that relies on it.
2. Describe the feature itself - what would change, what would happen. In general more detail is good!
Yes.

**Meta Info**
 - TFC Version: 1.12.2-0.31.0.125

 (at time of request)
 - Is this a compatibility feature for other mods? Or a enhancement for TFC alone?
Yes.

**Comment by Claycorp** [comment]
Oops, forgot to add that....
