### ISSUE TITLE
Weird edible foods

### ISSUE THREAD

**Issue by reddler97** [TerraFirmaCraft/TerraFirmaCraft#943]
in the 1.7.10 tfc version, you could not eat Flour nor Dough
now as of version 0.31.0.125 you can eat flour and dough for no nutrition 

side note "grain bundle"(eg. barley, wheat) and the associated Grain also don't have any nutrition I don't know how much of all of this is intended or not

TerraFirmaCraft-MC1.12.2-0.31.0.125.jar
Forge-14.23.5.2847

**Comment by alcatrazEscapee** [comment]
Yes, everything here is intentional. With the new nutrition system, unfinished grain products are edible but horrible for nutrition (they still restore hunger however and can be eaten in a pinch).
