### ISSUE TITLE
Storing sandwich in vessel make them loose nutrition value

### ISSUE THREAD

**Issue by aliceingame** [TerraFirmaCraft/TerraFirmaCraft#944]
**Describe the bug**
Make sure to include:
1. What did you expect to happen? sandwich to last longer in small vessel
2. What actually happened instead (i.e. what was the bug) lost all nutrition and never expire
4. If they would help to explain the issue, include screenshots
![image](https://user-images.githubusercontent.com/4293373/78453486-fdc8fe00-765f-11ea-9893-7037d1280aa1.png)

**To Reproduce**
Attention to detail is important!
1. Make a sandwich and store in a small vessel
2. Play
3. Get hungry and grab a sandwich
4. Eat and wonder why it does nothing

**Meta Info**
 - TFC Version: 125
 - Were any other mods included? Yes, but none that change food

**Comment by alcatrazEscapee** [comment]
I can't reproduce. Questions:
1) Was this single player or multiplayer?
2) Did you obtain the sandwich in question from JEI or through the creative menu?
3) Have you turned off decay in the config?

**Comment by aliceingame** [comment]
single player
all harvested ingredients
did not change anything to config
It take a bit of time to happen, if you close/open the vessel, it does nothing. So if you play a bit, get hungry, then it's no longer good.

**Comment by aliceingame** [comment]
... I just made one that auto broke without putting in vessel. One broke when picking up an other food item. I tossed them on the ground and now they all have their nutrition values back, but they all never expire.

**Comment by alcatrazEscapee** [comment]
I still can't reproduce but going to assume it's related to #1062
