### ISSUE TITLE
XP no longer gives health 

### ISSUE THREAD

**Issue by MCEventHorizon** [TerraFirmaCraft/TerraFirmaCraft#950]
After the latest update it seems that gaining levles no longer give health. I don't know if this is intentional but I haven't seen it in the changelogs.

TFC version: 0.31.1.126

**Comment by alcatrazEscapee** [comment]
It never has in TNG, but yes.

**Comment by MCEventHorizon** [comment]
Sorry, but what does TNG mean?

**Comment by Gaelmare** [comment]
TNG is the entire TFC 1.12 project. XP affecting health is not a thing in 1.12 TFC.

**Comment by MCEventHorizon** [comment]
Did something change with food then? I used to have 1000+ health and now I have 600 and I'm pretty sure I used to get hp when leveling up.

**Comment by eerussianguy** [comment]
Nutrition was just changed to work differently. See the recent changelog

**Comment by aliceingame** [comment]
It is possible to use a "skill" mod that use XP to level up the health bonus skill, Improvable skills does that, so it does reproduce the effect (but there is no penalty on the skill if you die, unlike classic where dying would mean loosing the HP bonus granted by XP.
Alternatively, could add a new HP skill in TFC, that would require XP to level, so player can decide where they spend their XP, on HP skill, or something else if they decide to add other features that allow enchanting or other use of XP. Could also reduce the bonus on death to have an insensitive to not die like in classic.

**Comment by DisasterMoo** [comment]
This will not be implemented, TNG now has a better nutrition window that works good enough for this purpose. Now, I support the creation of an addon that implement skills, one that could spend XP to level up and gives health boost.
