### ISSUE TITLE
Quern drop issue

### ISSUE THREAD

**Issue by MathiasV0** [TerraFirmaCraft/TerraFirmaCraft#951]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
When i destroy a Quern with a pickaxe, i would expect it to drop the quern itself and the handstone that was placed on top of it

2. What actually happened instead (i.e. what was the bug)
It only dropped the quern block, ie. i lost the handstone

**To Reproduce**
Attention to detail is important!
Break the quern with a handstone on top of it in survival with a pickaxe

**Meta Info**
 - TFC Version: 0.31.0.125

**Comment by Claycorp** [comment]
I wasn't able to reproduce this in 126 in SSP or SMP.
Perhaps it did drop but got lost or destroyed somehow?

**Comment by MathiasV0** [comment]
> I wasn't able to reproduce this in 126 in SSP or SMP.
> Perhaps it did drop but got lost or destroyed somehow?

I had that issue in 125 (newest version at the time) 
I havn't been able to reproduce the bug since updating (to 129), I'm guessing it got patched

**Comment by alcatrazEscapee** [comment]
Excellent. The unseen bug fix is the deadliest.
