### ISSUE TITLE
Donkeys and mules drop horse meat

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#959]
Not sure if this is intentional.

**Comment by eerussianguy** [comment]
Are they not horses?

**Comment by KemanDragon** [comment]
Donkeys and mules are both equines like horses, which means it's not at all farfetched that the meat would be similar enough to make it the same item. Pretty sure it's intentional.

**Comment by alcatrazEscapee** [comment]
Yeah, nah.
