### ISSUE TITLE
Chopping Trees destroys from bottom

### ISSUE THREAD

**Issue by Red3Tango** [TerraFirmaCraft/TerraFirmaCraft#96]
**[0.6.0.40]**
While chopping a tree, it destroys the tree from the bottom up, if tool breaks in the process it leaves the top part of the tree "floating".

Also when chopping the block that is not touching the ground it breaks the bottom block as well. Does not leave a "stump" as behavior in 1.7.10.

**Comment by alcatrazEscapee** [comment]
I could've sworn I fixed this...
