### ISSUE TITLE
Polar bears drop fish instead of bear meat and hides

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#960]
This is their vanilla drop, but it probably shouldn't apply here.

![2020-04-07_07 49 54](https://user-images.githubusercontent.com/52297970/78638602-74563d80-78a4-11ea-8647-c3f641d6af18.png)

**Comment by alcatrazEscapee** [comment]
We don't change anything about vanilla animals, so yes this will happen.
