### ISSUE TITLE
Llamas still drop leather instead of meat and hides

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#961]
Their vanilla drop but it doesn't make sense for them to drop pre-processed leather.
![2020-04-07_07 51 19](https://user-images.githubusercontent.com/52297970/78638739-b1bacb00-78a4-11ea-895e-7f79893072b7.png)

**Comment by alcatrazEscapee** [comment]
We don't change anything about vanilla animals, so yes this will happen.
