### ISSUE TITLE
Berry bushes should be smaller than a full block + connect to adjacent bushes

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#963]
1.7.10:
![2020-04-07_18 33 57](https://user-images.githubusercontent.com/52297970/78702244-325ae500-7900-11ea-9015-347c09e9faed.png)

1.12.2:
![2020-04-07_18 44 41](https://user-images.githubusercontent.com/52297970/78702286-3f77d400-7900-11ea-8f73-f2318b141e71.png)

**Comment by Claycorp** [comment]
Why? This just complicates bushes more than they need to be.

The TFC bushes are more realistic to what a bush type plant would be like.

**Comment by muzikbike** [comment]
Because it's a 1.7.10 feature?

**Comment by Claycorp** [comment]
It's not even a feature, It does nothing.

**Comment by muzikbike** [comment]
It absolutely was a feature, as the screenshots above clearly display.

**Comment by DisasterMoo** [comment]
That's just taste imo. Connecting to another bush or not, being full block or not is design choice. Anyway, closing.

**Comment by muzikbike** [comment]
This is a 1.7.10 feature, so it probably shouldn't have been closed.
