### ISSUE TITLE
Bunchberries, cloudberries and snowberries are named incorrectly

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#966]
Both in ID and display name, and as well as their bushes.

They display as Bunch Berry, Cloud Berry and Snow Berry, but should be Bunchberry, Cloudberry and Snowberry respectively, as these are their 1.7.10 and real life names.

**Comment by alcatrazEscapee** [comment]
Registry names aren't going to change (in 1.12), as that would be a needless breaking change. However the localization can indeed be fixed.
