### ISSUE TITLE
A way to obtain ice

### ISSUE THREAD

**Issue by muzikbike** [TerraFirmaCraft/TerraFirmaCraft#967]
Having it drop when no blocks are adjacent to it like with stone would probably work. Water would be considered an adjacent block.

**Comment by Claycorp** [comment]
What's the purpose of this for?
TFC doesn't use ice and the only way to get it in vanilla is with Silk Touch. You can add back in Silk or use another mod to get ice.

**Comment by drhaber** [comment]
maybe the best solution is to add a config option for enabling/disabling the Enchantment table?

**Comment by UnlimatedStone9** [comment]
There's already a toggle for that. ^
TNG allows re-enabling Vanilla recipes. What's best to suggest is allowing TFC bookshelves to work with enchantment tables, which I don't think do.

**Comment by alcatrazEscapee** [comment]
> What's best to suggest is allowing TFC bookshelves to work with enchantment tables, which I don't think do.
See #675

**Comment by muzikbike** [comment]
Even then I think there should still be a way to get ice blocks in a somewhat realistic way that fits into TFC, as enchanting tables would kinda break immersion. Having it work like stone does would be perfect.
