### ISSUE TITLE
Config to disable sapling drops from leaves.

### ISSUE THREAD

**Issue by UnlimatedStone9** [TerraFirmaCraft/TerraFirmaCraft#969]
**Describe the request**
Make sure to include:
1. What problem or issue would this enhancement solve?
Self explanatory, Classic did this, would be nice in TNG.

**Meta Info**
 - TFC Version: 0.31.1.126 (at time of request)

**Comment by alcatrazEscapee** [comment]
So, leaf drops = saplings. Saplings don't spawn on grass in TNG, I'm not sure what you're asking for.

**Comment by UnlimatedStone9** [comment]
Breaking leaves drops saplings, Classic had a toggle to remove sapling drops from leaves, I'd like that in TNG.
I merely assumed the random sapling spawns on grass was in TNG again, and asked for a toggle for that too, guess it's not in TNG then. That's fine with me!
