### ISSUE TITLE
Grass generating on Ground Items

### ISSUE THREAD

**Issue by Red3Tango** [TerraFirmaCraft/TerraFirmaCraft#97]
**[0.6.0.40]**
Grass can generate on top of ground items (sticks, stones, ore) causing them to float. after some ticks will eventually disappear though.

**Comment by alcatrazEscapee** [comment]
As per commit, this should be fixed, reopen if not.

**Comment by muzikbike** [comment]
I believe this may still be happenng:

Seed: 2903243570992731770

/tp 2014 150 13
