### ISSUE TITLE
Anvils can be placed in the ingot slot of other anvils

### ISSUE THREAD

**Issue by KemanDragon** [TerraFirmaCraft/TerraFirmaCraft#970]
1. I didn't expect the anvil to go into any slot of another anvil
2. The anvil went into the ingot slot of another anvil and showed up as a tiny anvil model
3. The game didn't crash
4. Screenshots included below to demonstrate.
![2020-04-07_12 46 53](https://user-images.githubusercontent.com/17956289/78731483-de56fd00-790d-11ea-80da-5252cd262873.png)
![2020-04-07_12 50 22](https://user-images.githubusercontent.com/17956289/78731493-e1ea8400-790d-11ea-95d3-cc1e84dabc95.png)

**To Reproduce**
Attention to detail is important!
1. Have an anvil placed and another in inventory
2. Attempt to place the anvil from inventory into the other anvil's ingot slot

**Meta Info**
 - TFC Version: 0.30.3.124
 - Other mods were included, but I tested with just TFC installed and it still did this.
 - No other mods have to be present.

**Comment by alcatrazEscapee** [comment]
There's no reason why this shouldn't work (aside from the obvious "wait that's smaller than expected"). However, seeing that anvils are technically valid metal items (they can be heated given they're made of metal), and there's no preexisting conditions that would stop a pack maker from adding an anvil recipe involving anvils, this will stay.

As for the "that's smaller than expected", this is a Minecraft oddity. Inventories are not to scale, for obvious playability reasons.
