### ISSUE TITLE
Capabilities (food) not synced on EntityItems, resulting in not showing the rotten food overlay when rendered in world.

### ISSUE THREAD

**Issue by aschjo** [TerraFirmaCraft/TerraFirmaCraft#972]
**Describe the bug**
Make sure to include:
1. What did you expect to happen?
For the spoiled meat to be dropped with the spoiled meat texture.
2. What actually happened instead (i.e. what was the bug)
Showed the cooked meat texture of dropped spoiled meat which originally had the spoiled texture in the player's inventory (All meats, as far as I know, has this bug)
3. If it was a crash, upload the full log file (`latest.log`)
N/A
4. If they would help to explain the issue, include screenshots
N/A
**To Reproduce**
Attention to detail is important!
- Cook any meat and let it become spoiled overtime (I used a campfire in this case)
- Then drop the meat on the ground; there should be a texture that looks like the cooked texture of that meat that became spoiled

**Meta Info**
 - TFC Version: 0.31.0.125
 - Were any other mods included? Can you reproduce it without these other mods?
There were other mods included; except these were clientside mods which would not affect the result. I was on the official TFC:TNG server when this was discovered. Yes.
 - If necessary, what other mods (including versions) MUST be present to experience the bug?
These mods **do not** need to be present to experience this bug; but the mods and their versions were as followed:
Controllable 0.8.0
FoamFix 0.10.10
Inventory Tweaks 1.64+dev.150
JEI 4.15.0.293
JourneyMap 5.7.1
Optifine HD_U_F5

**Comment by alcatrazEscapee** [comment]
As per discussion in discord, this is a sync issue, and a relatively harmless one as well. I'm not convinced if it's possible or even worth the effort to try and sync `EntityItem`s capability information.

**Comment by alcatrazEscapee** [comment]
This has been implemented as of 33449ac201a007449ac8809c25b9e547da62b615 for 1.17+ and won't be backported.
