### ISSUE TITLE
Mobs spawning on frozen lake in the winter

### ISSUE THREAD

**Issue by MCEventHorizon** [TerraFirmaCraft/TerraFirmaCraft#978]
**Describe the bug**
When it's winter, passive mobs will spawn on frozen lakes so when the lakes melt, they are left floating in the water.

**Meta Info**
 - TFC Version: 0.31.1.126

![2020-04-07_14 54 29](https://user-images.githubusercontent.com/15619786/79018484-368f3880-7b74-11ea-83a4-9491965c06f2.png)

**Comment by alcatrazEscapee** [comment]
I believe the problem here is that animals should check the block below (probably for grass) as part of their spawn mechanics.
