### ISSUE TITLE
Quern handstone bug

### ISSUE THREAD

**Issue by DisasterMoo** [TerraFirmaCraft/TerraFirmaCraft#980]
#BlameMoo
This line:
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/1dbe86d060bb93419070b5712dbefccfd527658e/src/main/java/net/dries007/tfc/objects/blocks/devices/BlockQuern.java#L227

should be:
```java
else if (selection == SelectionPlace.HANDSTONE && inventory.getStackInSlot(TEQuern.SLOT_HANDSTONE).isEmpty() && inventory.isItemValid(SLOT_HANDSTONE, heldStack))
```

Also, i think this issue can be further enhanced by:
- Instead of using ore dict to check handstone validity, use `instanceof ItemHandstone`
- Delegate the client-only drawing functions to the new `ItemHandstone` class
- Also, would be awesome to delegate the handle and input hitbox positions there
- Lastly, if we want to open up more control of the quern's features to addons (like, if a better handstone rotates/do recipes faster) add everything needed to this new class.

**Comment by alcatrazEscapee** [comment]
I disagree with the change to using `ItemHandstone` as a render delegate. We use ore dict as it's the obvious customization option for the least effort (on the pack maker side).

What should *not* happen, is the handstone should not be drawn in world using the actual item. That should be a constant render, using any handstone.

Addons using the quern should very likely just add their own quern (or, if they're adding an actual "better handstone", just make a better grinder. This is not a case to sacrifice simple customization for addon compatibility.
