### ISSUE TITLE
Cooking food in the forge makes cooked food stackable

### ISSUE THREAD

**Issue by ddemarco5** [TerraFirmaCraft/TerraFirmaCraft#982]
_1. What did you expect to happen?_
When cooking food in the forge, I expect to receive cooked food that is non-stackable

_2. What actually happened instead (i.e. what was the bug)_
The output cooked food becomes stackable

_4. If they would help to explain the issue, include screenshots_
Result after cooking some bear in a forge
![image](https://user-images.githubusercontent.com/1832038/79056988-ffbb3000-7c10-11ea-8e18-81e5f9343061.png)

**To Reproduce**
1. Fire up the forge
2. Put uncooked food into slots
3. When food becomes cooked, press shift-click to transfer food from forge to inventory
4. Enjoy your stackable food

**Meta Info**
 -TFC Version: tfc@0.31.1.126

 _- Were any other mods included?_ 
Yes: FML@8.0.99.99,forge@14.23.5.2847,inventorytweaks@1.64+dev.151.822d839,mcp@9.42,clumps@3.1.2,waila@1.8.26

_-Can you reproduce it without these other mods?_
Haven't attempted

**Comment by Gaelmare** [comment]
Food can be crafted together to stack.

**Comment by ddemarco5** [comment]
Upon further reading I understand that fact, but it'd be nice to unify the behavior of cooking output, no?

**Comment by ddemarco5** [comment]
After doing a bit more testing, it appears it's just a side effect of the fact that things of the same temperature/spoil time will auto-stack together. Since the things are cooked at the same moment, they expire at the same moment. And will stack.
