### ISSUE TITLE
Animals drop incorrect meat.

### ISSUE THREAD

**Issue by HeartyYF** [TerraFirmaCraft/TerraFirmaCraft#986]
**Describe the bug**
Llama drops horse meat, ocelot drops wolf meat, and camel drops nothing.
Also, no spawn egg for cats?

**Meta Info**
 - TFC Version: 1.0.0

**Comment by alcatrazEscapee** [comment]
Missing loot table declarations and supporting structure:

 - [ ] Llamas: 
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/3115add1806220435be88dbf6a0d520d9eda1959/src/main/java/net/dries007/tfc/objects/entity/animal/EntityLlamaTFC.java#L461
 - [ ] Ocelots:
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/3115add1806220435be88dbf6a0d520d9eda1959/src/main/java/net/dries007/tfc/objects/entity/animal/EntityOcelotTFC.java#L357
 - [ ] Camels seem to have no drop on purpose (?)
 - [ ] Squid should also drop calamari (needs to be added via loot table load event I believe)
