### ISSUE TITLE
Daily temperature is lower at noon and higher at midnight

### ISSUE THREAD

**Issue by Leinourdian** [TerraFirmaCraft/TerraFirmaCraft#993]
**Describe the bug**

1. What did you expect to happen?
In debug mode I'd expect the "Daily" temperature to be highest at noon and lowest at midnight. This would make intuitive sense as generally temperature is higher during the day IRL.

2. What actually happened instead (i.e. what was the bug)
Instead, the "Daily" temperature is highest at midnight and lowest at noon. I think this might lead to unintuitive situations where ice can melt at night.

![2020-04-14_22 25 27](https://user-images.githubusercontent.com/58150375/79265998-99980c80-7e9f-11ea-8baf-b27f43151896.png)
![2020-04-14_22 29 48](https://user-images.githubusercontent.com/58150375/79266000-9ac93980-7e9f-11ea-8119-69be5560d8dc.png)

**To Reproduce**
Make sure debug mode is on so you can see the "Daily" temperature. Press F3 and see how the "Daily" temperature changes with time of day.

**Meta Info**
 - TFC Version: 1.0.1.128
 - No other mods were included.

**To Fix**
I think this is caused by a simple math error over here:
https://github.com/TerraFirmaCraft/TerraFirmaCraft/blob/3115add1806220435be88dbf6a0d520d9eda1959/src/main/java/net/dries007/tfc/util/climate/ClimateHelper.java#L45
I think it should read like this instead:
`float hourModifier = (hourOfDay / 6f) - 1f;`

**Comment by alcatrazEscapee** [comment]
Lovely, thanks. I've been known for messing up some of those damn formulas before :P
